### ISSUE TITLE
Document and test reading config file from stdin #998

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#1004]
We should add some documentation and tests for #998

**Comment by errordeveloper** [comment]
@martina-if I think you meant to reference a different issue or PR...

**Comment by michaelbeaumont** [comment]
@martina-if i personally don't see the need to test this, feel free to reopen if you feel otherwise

**Comment by michaelbeaumont** [comment]
And it's documented with the description for the cli option `-f` at least
