### ISSUE TITLE
control plane log retention

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#1017]
User should be able to specify retention period for logs in CloudWatch.

[AWS Docs setting log retention](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html#SettingLogRetention)
[AWS API](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html)

**Comment by errordeveloper** [comment]
@gemagomez this wasn't done, we should assign it to a sensible milestone, e.g. 0.6.0 or 0.7.0.

**Comment by martina-if** [comment]
Are there any plans to work on this? :)

**Comment by Jeinhaus** [comment]
I think this would still be a great feature to have.

**Comment by sermilrod** [comment]
Could we have this in the roadmap please?

**Comment by aclevername** [comment]
> Could we have this in the roadmap please?

We will discuss this in our next planning meeting, but I think its likely this will get implemented :smile:

**Comment by cPu1** [comment]
This is out in https://github.com/weaveworks/eksctl/releases/tag/v0.73.0-rc.0
