### ISSUE TITLE
Print deprecation message when trying to create an EKS cluster with Kubernetes v1.10

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1049]
**Why do you want this feature?**

When trying to create a cluster with Kubernetes v1.10, from 0.2.0 onwards (post #1026 and #1029), the following is printed:
```console
$ ./eksctl-0.2.0 create cluster --version=1.10
[ℹ]  using region us-west-2
[✖]  invalid version, supported values: 1.11, 1.12, 1.13
```
This may be confusing for end-users who used to use version 1.10 and may have missed [0.2.0's release notes](https://github.com/weaveworks/eksctl/blob/master/docs/release_notes/0.2.0.md#bug-fixes-since-0140). 

**What feature/behavior/change do you want?**

We should instead have a message making it explicit that Kubernetes v1.10 was deprecated by EKS, e.g.:
```console
$ ./eksctl-0.2.0 create cluster --version=1.10
[ℹ]  using region us-west-2
[✖]  invalid version, 1.10 is now deprecated ; supported values: 1.11, 1.12, 1.13
see also: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
```

**Comment by rade** [comment]
I might be missing something here, but... "deprecated" normally means I can still use the feature but am discouraged from doing so and it may stop working at some future point. Whereas here I am no longer able to create 1.10 clusters.

**Comment by marccarre** [comment]
Agreed, I'd rather have "_is no longer supported_" as suggested [here](https://weaveworks.slack.com/archives/CJE5R99FV/p1563867980092600), but the term "_deprecated_" was [specifically mentioned](https://weaveworks.slack.com/archives/CJE5R99FV/p1563867869090000).

**Comment by marccarre** [comment]
Agreed, I'd rather have "_is no longer supported_". The term "deprecated" was specifically mentioned previously, hence I went for it here and in #1050.
