### ISSUE TITLE
MinInstancesInService and MaxBatchSize configurable

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#1059]
Allows for setting currently hardcoded values for the `UpdatePolicy`:
https://github.com/weaveworks/eksctl/blob/eefb3cf36f886bd043102aadda89e6e4525f5e5f/pkg/cfn/builder/nodegroup.go#L262-L272

This is currently hardcoded to MinInstancesInServcie = 0 and MaxBatchSize = 1

https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml#L415-L419

Has MinInstancesInService matching the Desired Capacity of the nodeGroup as well as `PauseTime: PT5M`

**Comment by aclevername** [comment]
Closed by https://github.com/weaveworks/eksctl/pull/3197
