### ISSUE TITLE
Support Terraform recipes as advanced cluster options

### ISSUE THREAD

**Issue by gjmveloso** [weaveworks/eksctl#1075]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
Customers may be interested on keep using their own Terraform recipes to fine-grained tuning on what to deploy regarding their EKS clusters and dependencies like VPCs, databases, etc.

**What feature/behavior/change do you want?**
eksctl working with custom Terraform recipe instead of only accepting CloudFormation templates

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by errordeveloper** [comment]
After some consideration, I've opened #1094 to discuss Terraform use-cases more broadly.

If we create a terraform provider, I think it will help with most of your concerns.

For example, you would be able to manage whatever you need with Terraform, and reference those resources in `eksctl_cluster` resource.

Here is an example of what it could look like:
```HCL
eksctl_cluster "cluster-1" {
  vpc {
    id = "${vpc_id}"
  }
  nodeGroups = [ ... ]
}
```
