### ISSUE TITLE
Move eksctl install flux's logic to pkg/addons/flux

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1076]
I think we should adopt the pattern that is used in `eksctl utils update-*`, much of this is very similar except that manifests are obtained from a library call, and we have a way for testing things if we use `pkg/kubernetes` the same way we do it in `pkg/addons/default`. Interaction Git and Flux can be tested as part of integration suite.

I think we should move business logic into [...] `pkg/addons/flux` for getting Flux resources created or updated in Kubernetes (similar to `pkg/addons/default`)
[...]

_Originally posted by @errordeveloper in https://github.com/weaveworks/eksctl/pull/1064#issuecomment-515935316_

**Comment by 2opremio** [comment]
I think it should go to `gitops/flux` instead

**Comment by marccarre** [comment]
FWIW, happy with either 🙂
