### ISSUE TITLE
"cannot list Kubernetes Services: Unauthorized" - which AWS permissions?

### ISSUE THREAD

**Issue by fabboe** [weaveworks/eksctl#1081]
Hi all,
this might relate to #1070 (and the issues that are referenced in that one).

But actually in my case I'm the owner/creator respectively assume the role of the owner.

My versions:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.2.1"}

$ aws --version
aws-cli/1.16.208 Python/3.6.8 Linux/4.15.0-54-generic botocore/1.12.198

$ kubectl version  
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
I create the cluster in this way:

```
aws sts assume-role --role-arn arn:aws:iam::123:role/CreateEKSClustersCloudFormation --duration 3600
```
```
eksctl create cluster \
--name test \                                           
--node-type p2.xlarge \
--nodes 4 \
--nodes-min 2 \
--nodes-max 4 \
--cfn-role-arn arn:aws:iam::123:role/CreateEKSClustersCloudFormation \
--ssh-access \
--ssh-public-key ~/.ssh/id_rsa.pub \
--region eu-central-1
```

That works okeyish (I do hit #520 but updating the authmap manually to add my worker nodes works). I can use the cluster so far functionally. 

Then I want to delete:
<assuming the role again as above>
```eksctl delete cluster --name=test --region=eu-central-1 -v 5```
this is the relevant stdout I believe (masked for IDs)
```
2019-08-02T09:29:35+02:00 [ℹ]  cleaning up LoadBalancer services
2019-08-02T09:29:35+02:00 [▶]  DEBUG: Request eks/DescribeCluster Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /clusters/test HTTP/1.1
Host: eks.eu-central-1.amazonaws.com
User-Agent: eksctl/{"BuiltAt":"","GitTag":"0.2.1"} aws-sdk-go/1.19.18 (go1.12.6; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY/20190802/eu-central-1/eks/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=134iyasd8t123156
Content-Type: application/json
X-Amz-Date: 20190802T072935Z
Accept-Encoding: gzip


-----------------------------------------------------
2019-08-02T09:29:35+02:00 [▶]  DEBUG: Response eks/DescribeCluster Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Length: 2268
Content-Type: application/json
Date: Fri, 02 Aug 2019 07:29:35 GMT
X-Amz-Apigw-Id: dyDu6F7rFiAFoeQ=
X-Amzn-Requestid: 471ee689-b4f7-812h-a618-57ahsd87tg12
X-Amzn-Trace-Id: Root=1-5d43e65f-d98hy12973y87tgasd


-----------------------------------------------------
2019-08-02T09:29:35+02:00 [▶]  {"cluster":{"name":"test","arn":"arn:aws:eks:eu-central-1:ARN_ID:cluster/test","createdAt":1564721940.931,"version":"1.11","endpoint":"https://1234.sk1.eu-central-1.eks.amazonaws.com","roleArn":"arn:aws:iam::ARN_ID:role/eksctl-test-cluster-ServiceRole-JABSDY1235","resourcesVpcConfig":{"subnetIds":["subnet-1","subnet-2","subnet-3","subnet-4","subnet-5","subnet-6"],"securityGroupIds":["sg-1"],"vpcId":"vpc-1","endpointPublicAccess":true,"endpointPrivateAccess":false},"logging":{"clusterLogging":[{"types":["api","audit","authenticator","controllerManager","scheduler"],"enabled":false}]},"identity":null,"status":"ACTIVE","certificateAuthority":{"data":"datastr="},"clientRequestToken":null,"platformVersion":"eks.4"}}
2019-08-02T09:29:35+02:00 [▶]  cluster = {
  Arn: "arn:aws:eks:eu-central-1:ARN_ID:cluster/test",
  CertificateAuthority: {
    Data: "datastr="
  },
  CreatedAt: 2019-08-02 04:59:00 +0000 UTC,
  Endpoint: "https://1234.sk1.eu-central-1.eks.amazonaws.com",
  Logging: {
    ClusterLogging: [{
        Enabled: false,
        Types: [
          "api",
          "audit",
          "authenticator",
          "controllerManager",
          "scheduler"
        ]
      }]
  },
  Name: "test",
  PlatformVersion: "eks.4",
  ResourcesVpcConfig: {
    EndpointPrivateAccess: false,
    EndpointPublicAccess: true,
    SecurityGroupIds: ["sg-1"],
    SubnetIds: [
      "subnet-1",
      "subnet-2",
      "subnet-3",
      "subnet-4",
      "subnet-5",
      "subnet-6"
    ],
    VpcId: "vpc-1"
  },
  RoleArn: "arn:aws:iam::ARN_ID:role/eksctl-test-cluster-ServiceRole-JABSDY1235",
  Status: "ACTIVE",
  Version: "1.11"
}
2019-08-02T09:29:35+02:00 [✖]  cannot list Kubernetes Services: Unauthorized
```

Now - which part shows me the conflict here? And what AWS permissions are the ones to "list Kubernetes Services"? Then I can ask for them.

Apart from this eksctl I do seem to have necessary permissions, as right now I do the remaining cluster cleanup of EC2 instances, gateways, network interaces and VPCs on my AWS (UI) of the same user (without the assume role but that my be implicit on the UI?).

Thanks for your help,
Fabian

**Comment by errordeveloper** [comment]
Hi. This is to do with ELB deletion, see https://github.com/weaveworks/eksctl/issues/1070.

**Comment by fabboe** [comment]
I see. Which concrete permissions are actually lacking? Are those not part of the [AmazonEKSServicePolicy](https://console.aws.amazon.com/iam/home#/policies/arn:aws:iam::aws:policy/AmazonEKSServicePolicy%24jsonEditor)?
Pardon my ignorance but the referenced naming of permissions ("Service list/delete permissions") doesn't map to concrete AWS permissions according to my Google skills.

**Comment by errordeveloper** [comment]
This is about access to the Kubernetes API, which is defined by IAM identity mappings in [`kube-system:ConfigMap/aws-auth`](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html). This essentially means you are not the owner of that cluster, another IAM user created it and they should add you to `kube-system:ConfigMap/aws-auth`, otherwise you can delete the cluster via CloudFormation. I'm going to close this, f you have other concerns please do leave a comment on #1070.

**Comment by dav-ell** [comment]
@errordeveloper Any idea what to do if the cluster you want to delete isn't appearing in CloudFormation?

**Comment by errordeveloper** [comment]
@dev-ell I don't work on this project since a couple of years, by the way... What often happen to me is that cluster I was looking for was in a different AWS regions or account, so try and check all of your regions and accounts.

**Comment by orsenthil** [comment]
Assuming you are an admin, and if you are struck at deleting a cluster due to this problem. Delete from AWS EKS Console (Web UI). a) Delete the nodegroups and b) Delete the EKS Cluster.
