### ISSUE TITLE
Combination of allow: false, publicKeyName in ssh config opens up port 22 access to the world for public nodegroup SG

### ISSUE THREAD

**Issue by dylburger** [weaveworks/eksctl#1089]
**What happened?**

We have the following config in the ssh block of the public nodegroup in our `cluster.yaml` file:

``` yaml
ssh:
  allow: false
  publicKeyPath: key.pub
```

This correctly loads the public key on the nodes, but there's still a rule on the public nodegroup security group to open port 22 to `0.0.0.0/0`:

<img width="1169" alt="Screen Shot 2019-08-02 at 21 52 25" src="https://user-images.githubusercontent.com/242668/62407608-d91c0400-b56f-11e9-88fd-2448ed813d87.png">

**What you expected to happen?**

I expect the `allow: false` directive in the ssh config to remove port 22 access to the world.

**How to reproduce it?**

Create a cluster with an ssh config using the example above, check the public nodegroup SG `eksctl` creates for the rules noted above.

**Versions**

```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.2.1"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

Let me know if y'all need logs, happy to provide.

**Comment by errordeveloper** [comment]
I believe that at present `publicKeyPath` overrides `allow: false`. It's certainly a bug and `allow: false` should definitely disable it. However, would like to enable SSH for public nodes and only allow access to the port within the VPC, or what is it that you'd rather see here? Right now, in the case of public nodegroups, we only have an option to allow access from anywhere or block it, otherwise why should you have SSH on a public nodegroup?

**Comment by dylburger** [comment]
My use case here was to remove public access on port 22, then open up access to our range of corporate office IPs by attaching a specific SG:

```
ssh:
  allow: false
  publicKeyPath: key.pub
securityGroups:
  attachIDs:
    - sg-abc123
```

This correctly attaches our SG, but as you note, still opens up port 22 to the world.

**Comment by martina-if** [comment]
I believe this was fixed here https://github.com/weaveworks/eksctl/pull/1545

**Comment by dylburger** [comment]
Great, thank you @martina-if !
