### ISSUE TITLE
can't launch in HKG region

### ISSUE THREAD

**Issue by lifeisgift** [weaveworks/eksctl#1102]
When launch in HKG, get the following error:
[ℹ]  using region ap-east-1
[ℹ]  setting availability zones to [ap-east-1a ap-east-1b ap-east-1c]
[ℹ]  subnets for ap-east-1a - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for ap-east-1b - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for ap-east-1c - public:192.168.64.0/19 private:192.168.160.0/19
[✖]  _**unable to determine AMI to use: unable to determine AMI for region ap-east-1,**_ version 1.13, instance type m5.large and image family AmazonLinux2

Need to add the AMI id for HKG.

**Comment by gemagomez** [comment]
@lifeisgift can you confirm what version of `eksctl` you are using?

**Comment by brycecarman** [comment]
Support for ap-east-1 was added in eksctl version 0.3.0. Please verify by running:

```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.3.0"}
```

See https://github.com/weaveworks/eksctl/releases/tag/0.3.0

**Comment by lifeisgift** [comment]
I write the ami ID to the yml, it works.

**Comment by gemagomez** [comment]
Thanks for confirming, @lifeisgift ! Closing this issue then.

**Comment by martina-if** [comment]
@lifeisgift Can you tell us which command flags and config file did you use when you got the error: mainly the Image Family and the AMI id.
