### ISSUE TITLE
ensure releases are made strictly of branches - protect master

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#1115]
Right now master branch is not protected as we used to make all releases of it. We should be able to make all release of release branches and turn on full protection for master. Before we do it, let's review release scripts and see if there is anything that may need tweaking.

**Comment by errordeveloper** [comment]
I just got read of direct `push origin master` calls in 67c6ea9a1aacdec65f8a80c0e2a0e5862cb908fe, but there is still `git push --force --tags origin`,  will need to check github docs on that.

**Comment by michaelbeaumont** [comment]
This seems done
