### ISSUE TITLE
heptio-authenticator-aws binary changed

### ISSUE THREAD

**Issue by gchaincl** [weaveworks/eksctl#112]
https://github.com/weaveworks/eksctl/blob/1c76d1b52ff8f6111092b1632d08680aa2a21f02/pkg/utils/kubectl.go#L36

Heptio Authenticator repo has moved to https://github.com/kubernetes-sigs/aws-iam-authenticator, thus returns an error for those who use the new repo

**Comment by errordeveloper** [comment]
As far as I'm aware, the binary name hasn't changed yet and [0.3.0](https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.3.0) is still the latest release.

I guess you must have installed it via `go get`? If so, please copy the binary for the timbering or patch `~/.kube/config` manually to use new binary.

If you install with `brew install weaveworks/tap/eksctl`, you will get `heptio-authenticator-aws` installed for you as a dependency.

This will become a bug when next version of authenticator gets release, but for now I don't think it's a bug 🐛 😺

**Comment by errordeveloper** [comment]
Certainly, I would love to see a PR – this should be simple enough for a first-time contributor! However I don't think we should block beta.1 on this (it's about to go out now), as recommended path is to use released binaries and not snapshots of master branch.

**Comment by errordeveloper** [comment]
see also https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/119
