### ISSUE TITLE
eks update for CNI and kube-proxy: should update to recommended version

### ISSUE THREAD

**Issue by biswajit-crvsh** [weaveworks/eksctl#1120]
**What happened?**
eksctl to update kube-proxy : 
________________________________
EKS kubernetes version: 1.13 

When update completes it leaves with the image tag : 602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.13.8 

I believe that tag does not exist and the correct one would be : 602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.13.7

eksctl to update CNI : 
When update completes it leaves with the image tag : 602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.5.0 

whereas AWS recommend the version 1.5.2. (602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.5.2)

**What you expected to happen?**
Update to the corresponding version based on kubernetes version. 

**How to reproduce it?**
eksctl update kube-proxy --name <cluster_name>

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
➜  ~ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.3.1"}
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by marccarre** [comment]
@biswajit-crvsh, many thanks for opening this issue!

This looks like a "duplicate" of #1088, which may also interest you, in particular [this comment](https://github.com/weaveworks/eksctl/issues/1088#issuecomment-519469522) and the [reply from AWS](https://github.com/weaveworks/eksctl/issues/1088#issuecomment-519798002).

We hope to fix this in a near future, once a way to get the versions mapping becomes available, or once the images' versioning changes, but in the meantime workarounds are:
- to upgrade to one of the Kubernetes versions for which there is an image,
- to follow this documentation to upgrade "manually": https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

**Comment by biswajit-crvsh** [comment]
@marccarre Thank you for the explanation. 

I was in the process of automate the whole upgrade process using a wrapper script with eksctl. 

However, no harm using manual install for kube-proxy and aws-node using kubectl for now. 

Thank you!
