### ISSUE TITLE
VPCs created with eksctl should be in its own CF stack

### ISSUE THREAD

**Issue by sstkwayne** [weaveworks/eksctl#1123]
When using eksctl to create a cluster with a new VPC, it would be great to have the VPC and all it's resources created as a separate Cloudformation stack from the EKS cluster. I recently had to tear down a cluster and because it is in the same stack with the VPC i had to tear that down as well. This is inconvenient because there wasn't anything wrong with the VPC configuration,

**Why do you want this feature?**
Having a separate VPC stack would allow users to create and destroy EKS clusters without having to teardown the VPC which might have other resources in it such as a DB, Peering connections, etc.

**What feature/behavior/change do you want?**
I would like to see eksctl create cluster command result in the creation of a VPC stack, a cluster stack and a nodegroup stack if defined in the yaml.

**Comment by errordeveloper** [comment]
There are other good reasons to do, e.g. sharing a VPC between a few clusters.

**Comment by errordeveloper** [comment]
This is already covered by #892.
