### ISSUE TITLE
add --config-file to all commands

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#1126]
Currently some commands still don't support `--config-file`, we should add it to all commands, and add `--validate` as well to allow users to control validation (#1124 already adds a field for it).
Verify that all commands support these flags

**Comment by Callisto13** [comment]
For anyone coming by to pick part of this up, these are the commands which as yet do no support the `--config-file` flag:

- [ ] `get cluster`
- [ ] `get labels`
- [ ] `set labels`
- [ ] `unset labels`
- [ ] `utils describe-stacks`
- [ ] `utils schema`
- [ ] `utils update-cluster-stack`
- [ ] `utils update-legacy-subnet-settings`
- [ ] `utils write-kubeconfig`

**Comment by neha-viswanathan** [comment]
Hello I can pick this up

**Comment by Callisto13** [comment]
Hey @neha-viswanathan sure, go for it!

I think let's have a PR for each action, to make reviewing etc easier 👍

**Comment by Skarlso** [comment]
- [ ] `get nodegroup`

**Comment by aclevername** [comment]
Not sure if its worth adding support for `eksctl unset labels`. The current suggested flow:
```
eksctl unset labels --cluster managed-cluster --nodegroup managed-ng-1 --labels kubernetes.io/managed-by,kubernetes.io/role
```

Having a cfg file option would only be useful for removing ALL labels. I don't know if thats really useful, it might just add more confusion.

**Comment by aclevername** [comment]
`--validate` flag no longer appears to be a thing: 
```
cd pkg/ctl/

rg "\"validate\""

```
