### ISSUE TITLE
`eksctl install flux` fails when you have a brand new github repo

### ISSUE THREAD

**Issue by kalbir** [weaveworks/eksctl#1137]
**What happened?**
I created a brand new github repo called `my-eks-cluster` and then ran `eksctl install flux --name=kalbir-test-1 --git-url=git@github.com:kalbir/my-eks-cluster.git --git-email=kalbir@gmail.com`. 

I got the following error:

<img width="811" alt="Screenshot 2019-08-09 at 10 20 59" src="https://user-images.githubusercontent.com/3952074/62878665-70781880-bd21-11e9-866f-305aeee42186.png">

It looks like when you create a new repo on github *without any files in it* (ie. no readme, no license) it does not set up any branches for that repo and this means that the initial clone in `eksctl install flux` fails.

**What you expected to happen?**

`eksctl install flux` to install flux and add the config to my git repo. I think I would be expecting at the end of the command there is a master branch in the repo and the relevant files are committed to the master branch. So probably eksctl should create the master branch somewhere in this process. 

**How to reproduce it?**

1. Create a new repo, "foo", on github, *without a readme or license*. It should look like this after creation:

<img width="1107" alt="Screenshot 2019-08-12 at 17 25 49" src="https://user-images.githubusercontent.com/3952074/62880855-470dbb80-bd26-11e9-8ed5-26d7681bb26f.png">

2. Run `eksctl install flux --name=<clustername> --git-url=git@github.com:<user>/foo.git --git-email=<email>`

**Anything else we need to know?**
Mac OS 10.14

**Versions**

```
└>> eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.3.0"}
```

```
└>> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```
└>> eksctl install flux --name=kalbir-test-01 --git-url=git@github.com:kalbir/my-eks-cluster.git --git-email=kalbir@gmail.com --region=eu-west-1
[ℹ]  Cloning git@github.com:kalbir/my-eks-cluster.git
Cloning into '/var/folders/7b/3kr7dlnn6231zcwcqjy_6pdh0000gn/T/eksctl-install-flux-clone018782554'...
fatal: Remote branch master not found in upstream origin
[✖]  cannot clone repository git@github.com:kalbir/my-eks-cluster.git: exit status 128
```

**Comment by errordeveloper** [comment]
To begin with, we could just document this as a requirement. However, long term, I think there is a number of aspects that needs to be review. For instance, I'm generally not clear what do we expect for the user, who owns the repo to begin with? How should we handle conflicts, e.g. existing files, (non-)existing branches? This is just one case of a non-existing branch.

Personally, I think ideally there should be just two modes:
1. given no repo, create it, populate it and use it
2. given a repo, just use it

Right now we are dealing with all cases in between the two above, to me it's all a big special case and I'm not sure we should support it in the same way that we support 1 & 2.

It maybe plausible to offer a mode where user has a repo and wants our help to populate it. In that cases, we could provide a command that lets them populate such repo with files generated from our profile(s). This mode would need to be very explicit about what files get written where, it maybe plausible to think of it as an advanced mode where additional options are available.

**Comment by gemagomez** [comment]
Let's document current behaviour for now and discuss how it should change down the line. It sounds like some extra design/thinking is required.

**Comment by errordeveloper** [comment]
In which case, I think it should be documented in the guide first and foremost https://github.com/weaveworks/eksctl/pull/1138.

/cc @dholbach
