### ISSUE TITLE
Site : add search functionality

### ISSUE THREAD

**Issue by bia** [weaveworks/eksctl#1143]
As discussed with @gemagomez this morning, as our documentation grows, it is becoming increasingly valuable to add a search bar to our website.
There are a [few different ways](https://gohugo.io/tools/search/) to implement this.

@martina-if maybe you have an idea of what the best one to pursue would be.
cc @sbernheim

**Comment by martina-if** [comment]
I don't have an opinion right now on what would be the best way to do it, I would need to read a bit on what works best with Hugo and Netlify.

**Comment by errordeveloper** [comment]
I don't see a reason why not just rely on regular search engines, perhaps we should do some search testing on how easy it is to answer eksctl question by using Google and DDG.

**Comment by gemagomez** [comment]
I don't know, @errordeveloper, I normally use the search engine to get to the website I am trying to search on and then I expect to be able to find items in there through the local search. That's how most technical documentation works. 

Some examples: 

- https://golang.org/doc/
- readthedocs websites
- https://docs.python.org/3/
- https://kubernetes.io/docs/home/
- etc

**Comment by errordeveloper** [comment]
> That's how most technical documentation works.

Yes, but I think it's rarely used, so I consider this low priority and would rather see any general improvements to the docs before this. There are plenty of [actionable issues](https://github.com/weaveworks/eksctl/labels/kind%2Fdocs).

**Comment by gemagomez** [comment]
I use them to search through docs and I am sure many other users do. You cannot assume people have your search habits. When a user is new to the project they are trying to do things and they are going to try to crawl the documentation without the need of a search engine. Non searchable docs are rather not user friendly.

**Comment by dholbach** [comment]
This is resolved with the move to `mkdocs`, check e.g. https://deploy-preview-2062--eksctl.netlify.app/ - it's just not part of a release yet.
