### ISSUE TITLE
There seems to be no ami for ubuntu-eks 1.13

### ISSUE THREAD

**Issue by cw-sakamoto** [weaveworks/eksctl#1152]
When I tried to start it as shown below, I got an error.

```
eksctl create cluster \
--name eks-ubuntu \
--version 1.13 \
--nodegroup-name workers \
--node-type t3.medium \
--nodes 2 \
--nodes-min 1 \
--nodes-max 4 \
--node-ami auto \
--node-ami-family Ubuntu1804 \
--vpc-public-subnets subnet-XXXX,subnet-YYYY
```
```
[✖]  unable to determine AMI to use: unable to determine AMI for region ap-northeast-1, version 1.13, instance type  t3.medium and image family Ubuntu1804
```

I confirmed ami on aws, `ubuntu-eks` for 1.13 image is not exists. How do I request an AMI for ubuntu creation?

**Comment by cPu1** [comment]
@cw-sakamoto thanks for the bug report. 

This has been fixed in https://github.com/weaveworks/eksctl/releases/tag/0.4.3 by adding the Ubuntu1804 AMIs for 1.13 in eksctl.
