### ISSUE TITLE
Automate version incrementation in release scripts

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1153]
**Why do you want this feature?**

Currently, when releasing, one has to figure out the next tag/version to pass to the release scripts. While we could still allow this, the scripts could also automatically figure out the next default version by:

- reading the latest version released on GitHub,
- resetting the "patch" digit,
- incrementing the "minor" digit.

In addition to this, the script could ensure the tag provided is well-formed, i.e.:

- release candidates match `[0-9]+\.[0-9]+\.[0-9]+\-rc\.[0-9]+`, e.g. `0.4.0-rc.0`
- releases match `[0-9]+\.[0-9]+\.[0-9]+`, e.g. `0.4.0`.

**Comment by michaelbeaumont** [comment]
Right now, one has to initially create the release branch with the correct name.
