### ISSUE TITLE
Support G3 GPU instance

### ISSUE THREAD

**Issue by Jeffwan** [weaveworks/eksctl#1157]
**Why do you want this feature?**
User wants to provision EKS cluster with G3 instances. 

**What feature/behavior/change do you want?**
A clear and concise description of the change you would like to see in eksctl.
https://github.com/weaveworks/eksctl/blob/2acf21f17e1c88dbf0eb70fdb39e70bdd6e41a4a/pkg/utils/utils.go#L9-L11

More test cases will be added to `static_resolver_test.go:`

I notice we hard coded GPU instance and we can add G3 here.

G3 use Tesla M60 and we tested EKS optimized AMI and Device Plugin works well with it.

**Comment by errordeveloper** [comment]
Closed via #1194.
