### ISSUE TITLE
Allow ASG size modification from eksctl

### ISSUE THREAD

**Issue by stevesloka** [weaveworks/eksctl#116]
It would be helpful to have `eksctl` allow for updating the desired node count for a cluster. I have some dev workflows where I want to scale up my node counts and then scale back.

Command example: 
```
$ eksctl edit cluster --nodes=5
```
Some tricky things that could happen are if the user wants to scale beyond the `max` defined in the ASG. Should `eksctl` return error or update the ASG to allow more instances? 

I'm happy to work through a design and help implement some features if desired.

**Comment by errordeveloper** [comment]
Thanks, this is definetly very useful feature we should add soon! I was thinking we need to add subcommand for nodegroups anyway, and this would fit nicely as `eksctl scale nodegroup --cluster=<name> --nodes=5 [<nodeGroupName>]` (inspired by `kubectl scale deployment`, of course).

**Comment by richardcase** [comment]
Looking at this now.

**Comment by errordeveloper** [comment]
Closed via #254.
