### ISSUE TITLE
eksctl update cluster to create the cluster automatically if not created

### ISSUE THREAD

**Issue by neelakansha85** [weaveworks/eksctl#1163]
**Why do you want this feature?**
It would be nice if `eksctl update cluster -f <path-to-config-file>` can automatically create the cluster if it is not created earlier. It does already thrown an error currently and knows that there is not cluster present with the given name. It helps with automation scripts used to create/manage the cluster config. 

This behavior is similar to many other tools such as kubectl when trying to apply certain changes to the config files. 

**What feature/behavior/change do you want?**
Changing default behavior of `eksctl update` to create the cluster if not present. If for some reason everyone doesn't feel like making this as a default behavior for `update` atleast enabling an optional parameter such as `--force` or `--create-if-not-present` or something similar should be helpful.

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by neelakansha85** [comment]
Seems like there is another open ticket covering this issue https://github.com/weaveworks/eksctl/issues/19

**Comment by michaelbeaumont** [comment]
Falls under #2774
