### ISSUE TITLE
get nodegroups command no longer display all nodegroups 

### ISSUE THREAD

**Issue by danyli78** [weaveworks/eksctl#1164]
**What happened?**
You can no longer get all nodegroups via a single command. You can only get individual nodegroup settings. 

**What you expected to happen?**
Expect to display all nodegroups without entering a nodegroup name, which was capable in v0.3.1. At least another flag/option to display all groups. 

**How to reproduce it?**
eksctl get nodegroup --cluster amg-non-prod-use1
[✖]  nodeGroups[0].name must be set

**Versions**
```
eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.4.0"}
```

**Comment by 2opremio** [comment]
This seems to have happened in dbedfd19fe6609b011944f01bf0f1728e69ac4ae (part of https://github.com/weaveworks/eksctl/pull/859 ). Here, specifically https://github.com/weaveworks/eksctl/pull/859/files#diff-316c11863e678a47a8959c72694d1f10R27 . @errordeveloper I figure this wasn't intentional?

**Comment by errordeveloper** [comment]
No, it definitely wasn't intentional.

**Comment by errordeveloper** [comment]
@2opremio just looking at this once again - the change (dbedfd1) was intentional, we do want to call validation and defaulting functions in all commands consistently, however some commands that   don't construct valid config when ran without a config file.
