### ISSUE TITLE
Acknowledge that AWS CloudFormation might create IAM resources parameter missing

### ISSUE THREAD

**Issue by historus** [weaveworks/eksctl#1170]
Hi,
trying our eksctl I ran the command 

<pre>
eksctl create cluster --name dev --version 1.13 --nodegroup-name standard-workers --node-type t3.medium --nodes 3 --nodes-min 1 --nodes-max 4 --node-ami auto --region us-east-1
</pre>
but since I was not able to check the check box "I acknowledge that AWS CloudFormation might create IAM resources." with the cli the creation failed with "The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 341d72ad-c400-11e9-a649-f3aea9112343)"

Saving the template from the CFN console and manually creating a stack from it and checking the check box works but breaks the eksctl experience and workflow. 
How can I acknowledge the creation of IAM resources from the eksctl?

Thanks

**Comment by cPu1** [comment]
The acknowledgement is required when creating a CloudFormation stack using the AWS console, not when using `eksctl` which uses the AWS API to provision resources. 

The error suggests your AWS CLI isn't configured with correct credentials. Can you ensure you're able to access AWS resources using the AWS CLI (for e.g., with `aws sts get-caller-identity`)? A common cause of this error is if you have MFA configured for your AWS account and the session token isn't refreshed.

**Comment by historus** [comment]
aws sts get-caller-identity is working as expected. 
output is
<pre>
{
    "Account": "1234567889", 
    "UserId": "09876543:johndoe", 
    "Arn": "arn:aws:sts::1234567889:federated-user/johndoe"
}
</pre>
but the create command is still failing.

I was thinking the capabilities were missing (https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html).

**Comment by historus** [comment]
I found the issue. The credentials were generated with GetFederationToken and are not allowed to make any IAM calls. I created the credentials in another way and then it is working. Thanks for the help.
