### ISSUE TITLE
Can't run custom cluster yaml-based config  cluster

### ISSUE THREAD

**Issue by inpicksys** [weaveworks/eksctl#1173]
**What happened?**
[✖]  loading config file "eks-cluster.yaml": no kind "ClusterConfig" is registered for version "eksctl.io/v1alpha5" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:60"

**What you expected to happen?**
Starting cluster deploy

**How to reproduce it?**
Latest example from your repo

**Anything else we need to know?**
Windows 10 OS

**Versions**
Please paste in the output of these commands:
```
$ eksctl version -> version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.24"}
$ Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Co
mpiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.- 
```

**Logs**

**Comment by errordeveloper** [comment]
That version of the API is not supported in 0.1.24, it was introduced a few versions later.
However, the latest version is 0.4.1 and you should upgrade.

**Comment by inpicksys** [comment]
Thanks. I upgraded kubectl tool several times, and see it used old one from docker C:\Program Files\Docker\Docker\resources\bin\kubectl.
Anyway thank you for quick response.
