### ISSUE TITLE
How to generate userdata and boostrap conf bytes?

### ISSUE THREAD

**Issue by shuangstar** [weaveworks/eksctl#1177]
We have some customized userdata and bootstrap to fill other files, such as connect to our intrenal monitor system, and balala. 
I have tried to change contens in pkg/nodebootstrap/assets/bootstrap.al2.sh and build my new eksctl binary. But the file passed into ec2 is not changed. I think we need to change variable bootstrapAl2Sh.

But how to generate these bytes. Is possible to provider a tool to generate those.
If the tool can automatically change the value of the variables, it's more better.

Thanks!

**Comment by errordeveloper** [comment]
Duplicate of #1178.
