### ISSUE TITLE
How to generate userdata and boostrap conf bytes? 

### ISSUE THREAD

**Issue by shuangstar** [weaveworks/eksctl#1178]
We have some customized userdata and bootstrap to fill other files, such as connect to our intrenal monitor system, and balala. 
I have tried to change contens in pkg/nodebootstrap/assets/bootstrap.al2.sh and build my new eksctl binary. But the file passed into ec2 is not changed. I think we need to change variable bootstrapAl2Sh.

But how to generate these bytes. Is possible to provider a tool to generate those.
If the tool can automatically change the value of the variables, it's more better.

Thanks!

**Comment by errordeveloper** [comment]
> I have tried to change contens in pkg/nodebootstrap/assets/bootstrap.al2.sh and build my new eksctl binary.

This file gets embedded as an asset (see `pkg/nodebootstrap/assets.go`). I am pretty sure `make build` will make sure to update that file.

Are you sure you have to achieve this by modifying the script? We provide both `preBootstrapCommands` (that allows you to run anything before `bootstrap.al2.sh` runs, and `overrideBootstrapCommand` (what allows you replace `bootstrap.al2.sh` entirely).

**Comment by shuangstar** [comment]
I'm on tag 0.3.1 to develop this. Run make build does't update the bytes. The function is not supported in this version?

**Comment by shuangstar** [comment]
> > I have tried to change contens in pkg/nodebootstrap/assets/bootstrap.al2.sh and build my new eksctl binary.
> 
> This file gets embedded as an asset (see `pkg/nodebootstrap/assets.go`). I am pretty sure `make build` will make sure to update that file.
> 
> Are you sure you have to achieve this by modifying the script? We provide both `preBootstrapCommands` (that allows you to run anything before `bootstrap.al2.sh` runs, and `overrideBootstrapCommand` (what allows you replace `bootstrap.al2.sh` entirely).

I'm on tag 0.3.1 to develop this. Run make build does't update the bytes. The function is not supported in this version?

**Comment by errordeveloper** [comment]
> I'm on tag 0.3.1 to develop this. Run make build does't update the bytes. The function is not supported in this version?

I am not sure why that is, it's unexpected.

How about using `preBootstrapCommands` or `overrideBootstrapCommand` in config file? You really shouldn't need to make any code changes.

**Comment by errordeveloper** [comment]
@shuangstar did you manage to get something working with `preBootstrapCommands` or `overrideBootstrapCommand`?

**Comment by martina-if** [comment]
Hi this has been inactive for a long time so I'm closing it but feel free to reopen it with more details if you need more help. Or reach us on [slack](https://weave-community.slack.com/archives/CAYBZBWGL)
