### ISSUE TITLE
integration tests shouldn't need to look in ~/.ssh

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#1179]
We should just check one in the repo, or generate it when the test runs. There is not need to have this dependency.

**Comment by errordeveloper** [comment]
Also, right now one has to use a key that is in private Weaveworks system, it should be possible for any contributor to run integration tests.

**Comment by michaelbeaumont** [comment]
Maybe I'm missing something but in order to do the Gitops tests we need to push branches somewhere so we do need _some_ private credentials?
