### ISSUE TITLE
UnsupportedAvailabilityZoneException: lack of capacity to support cluster

### ISSUE THREAD

**Issue by niksrc** [weaveworks/eksctl#118]
unable to create cluster control plane: UnsupportedAvailabilityZoneException: Cannot create cluster '****-**' because us-east-1c, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1d

**Comment by errordeveloper** [comment]
This appears to be a well known-issue with EKS currently (see https://github.com/weaveworks/eksctl/issues/75#issuecomment-400122625), I am not sure how eksctl could possibly address this – wdyt?

**Comment by niksrc** [comment]
Thanks for the quick reply. I'm wondering what eksctl does differently as i am able to create a cluster from the console every time in the same region.

**Comment by niksrc** [comment]
See this issue [https://github.com/coreos/coreos-kubernetes/issues/442](https://github.com/coreos/coreos-kubernetes/issues/442) where @mumosho suggests letting cloudformation decide which availabilty zone to choose for a user.
Here is the corresponding gist [https://gist.github.com/mumoshu/d375a37a87d09ecdc0cc0d1be322e628](https://gist.github.com/mumoshu/d375a37a87d09ecdc0cc0d1be322e628)

**Comment by niksrc** [comment]
@errordeveloper i was able to create the cluster by hard coding the index of the subnet in the template files and rebuilding eksctl. I don't think we can do anything to fix this unless aws provides an api for availability detection for a region.

Thanks for looking into this.

**Comment by errordeveloper** [comment]
@niksrc did you do something similar to what @jorihardman did in https://github.com/swipesense/eksctl/commit/ca185e446da624f0f65b27b57dd121d54adbe7c9? I think we should be able to incorporate something similar to that, but we might want to take it out of CloudFormation and also fix #101.

**Comment by errordeveloper** [comment]
I'd rather keep this issue open for now.

**Comment by errordeveloper** [comment]
@niksrc we are working on a fix in https://github.com/weaveworks/eksctl/pull/124, testing would be very helpful, we will let you know once it's ready to test (it's not yet).

**Comment by errordeveloper** [comment]
@niksrc we have merged a fix for this in #124. I've tagged 0.1.0-beta.2 and binaries should be available shortly – please let us know if it works for you!

**Comment by errordeveloper** [comment]
@niksrc turns out there is a bug in 0.1.0-beta.2 (https://github.com/weaveworks/eksctl/issues/129), we have merged a fix into master – would you mind to help us testing it before we figure if we need to do more to really solve the problem?

**Comment by errordeveloper** [comment]
After thinking about this for a while, it looks like we are better of exposing a flag for the time being, as it turns this is somehow different in every AWS account (at least that what seems to be the case from the docs.

> You may receive an error that one of the Availability Zones in your request does not have sufficient capacity to create an Amazon EKS cluster. If this happens, the error output contains the Availability Zones that can support a new cluster. Retry creating your cluster with at least two subnets that are located in the supported Availability Zones for your account.

**Comment by errordeveloper** [comment]
In the future we may try parsing the error message and retrying automatically, but it doesn't seem feasible right now as we would need to improve some of the internals and provide stack update functionality.

**Comment by niksrc** [comment]
@errordeveloper This worked smoothly, Thanks.

**Comment by errordeveloper** [comment]
Excellent! Could you please confirm which version of eksctl you have used?

**Comment by niksrc** [comment]
I used the latest master.
Tag 0.1.0-beta.3 c332060348833792c9a69f1ef71d1c8d76c3ffd7
