### ISSUE TITLE
review how flux installer works

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#1180]
Current implementation of `eksctl install flux` command comes with multiple flags and no config file support. We should review what are the most essential flags that it has to have.

For example, it has `--amend` mode, that is meant to allow user to tweak configuration object before those gets created in the cluster. This is not a kind of mode any other of `eksctl` commands has, we shouldn't need it. There are many ways for the users to install Flux, e.g. `fluxctl` now can write manifests, there is also the helm chart.

Additionally, it has `--git-flux-subdir` (with default value `flux`), it should probably be `<git-path>/<namespace>/` by-convention. And `--git-label` could just be a combination of cluster name, region and either one other parameter (`--namespace`?) or a hash of key parameters (e.g. `--git-branch`, `--git-path` and `--namespace` seem like good choices to me).

When we add config file support, we should be able to leave only most essential flags, i.e. `--git-url`, `--git-branch`, `--git-paths`, and expose the rest via config.

Also, the SSH key flux uses gets generated by flux, then installer waits, forwards port to the flux pod, and obtains the key. We should expose a way for user to specify an existing key, and arguably we shouldn't have to wait for flux pod to generate the key, generating the key locally in a file would be much more convenient, we can actually store in `~/.ssh`, so the user doesn't have to worry about loosing it (at the moment we only print it to stdout, and otherwise user has to get `fluxctl` installed to obtain it). Also, the fact that it waits for the pod, means there is a requirement for cluster to be able to start that pod, which is not guaranteed. And dependency of having to connect to the port inside the pod entails that we cannot seal this port, which maybe of interest to do by default, given that flux doesn't support TLS.

Finally, it's not clear to me whether flux gets installed globally with full access to the cluster, or it's only for `flux` namespace? I think we should only install it one namespace by default just for the purpose of what we need to achieve. We should allow user to do more, but that will have to be optional. 
Namely, the reason we install flux is so that user can manage some add-ons, like cluster autoscaler and ALB ingress. We cannot dictate how all workloads in the entire cluster are managed, and we should give flux access to the entire cluster by default, as you 
I recognise that flux doesn't take over any workloads that are not checked in the repo, however as soon as someone adds a workload to the repo, it will take it over,  and that can happen by accident without user knowing, especially when cluster is used by several teams.
Thereby, I think we should install flux just for the purpose of managing those add-ons, it should be confined to a single namespace or maybe 2 namespaces at most.
It should be easy enough for the user to install flux to manage all existing namespace, or globally, or in another namespace.

--- 

Having stated what I think about this, I'd like to hear the view of others. The purpose of this issue is to have a discussion.

**Comment by 2opremio** [comment]
> the fact that it waits for the pod, means there is a requirement for cluster to be able to start that pod, which is not guaranteed.

This was a product requirement. The command had to leave flux in a working state

**Comment by michaelbeaumont** [comment]
Likely out of date and irrelevant
