### ISSUE TITLE
nodeGroups[0].name must be set

### ISSUE THREAD

**Issue by shuangstar** [weaveworks/eksctl#1181]
Upgrade eksctl to 0.4.1. get nodegroup get :
# eksctl get nodegroup --cluster sel-labs
[✖]  nodeGroups[0].name must be set

Old eksclt version:
version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.38"}

New eksctl version:
version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.38"}

**Comment by cPu1** [comment]
This issue is a duplicate of https://github.com/weaveworks/eksctl/issues/1164. Please follow that issue for progress.
