### ISSUE TITLE
eksctl install flux --name or --cluster ?

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#1187]
Today most commands use the CLI argument `--name` to get the name of the resource they are operating so:

`eksctl create cluster --name cluster1` -> --name is the cluster name

`eksctl create nodegroup --cluster cluster1 --name ng1` -> --name is the name of the nodegroup and `--cluster` is the cluster name

In `eksctl install flux` we are using the argument `--name` for the cluster name and it should probably be `--cluster`.

`eksctl gitops apply` uses `--cluster` for the name of the cluster.

We should decide on a way to do it and make them consistent with each other.

**Comment by whereisaaron** [comment]
Please! When I first used `eksctl` this was a hassle, and it still is. I never know or can reliably guess which commands would use `--name` vs `--cluster`. If we can't decide, maybe we can have `--cluster-name` and `--nodegroup-name` that just work everywhere. A few more characters would be a small price to pay for consistency 🙏

**Comment by rndstr** [comment]
is `--cluster=` and `--nodegroup=` expressive enough?

looking at other *ctls, has there been put thought into having the principal resource as argument instead of a flag? `eksctl get cluster CLUSTER` instead of `eksctl get cluster --cluster=CLUSTER`?

**Comment by cPu1** [comment]
>looking at other *ctls, has there been put thought into having the principal resource as argument instead of a flag? eksctl get cluster CLUSTER instead of eksctl get cluster --cluster=CLUSTER?

`kubectl` works that way but OTOH, AWS CLI uses the `--name` option for most of its commands (`aws eks describe-cluster --name <name>`).

>In eksctl install flux we are using the argument --name for the cluster name and it should probably be --cluster.

To stick to our current convention, I agree with naming the option `--cluster` instead of `--name` since it's unclear from the sub-command what the principal resource is.
