### ISSUE TITLE
unknown field "spotAllocationStrategy"

### ISSUE THREAD

**Issue by yahavb** [weaveworks/eksctl#1191]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
aws released capacity-optimized pools. According to https://aws.amazon.com/blogs/compute/introducing-the-capacity-optimized-allocation-strategy-for-amazon-ec2-spot-instances/ `"SpotAllocationStrategy": "capacity-optimized"` is required to support it. 

**What feature/behavior/change do you want?**
when creating a mixed-instance node group, the pool/s to be launched will use "capacity-optimized" so the spot instances will use the least volatile pools. 

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".
```
nodeGroups:
    - name: mixed-instances-1
      minSize: 2
      maxSize: 5
      ssh:
        publicKeyName: id_rsa.pub
      instancesDistribution:
        maxPrice: 0.5
        instanceTypes: ["c4.large","c4.xlarge","c4.2xlarge","c4.4xlarge","c4.8xlarge","c5.large","c5.xlarge","c5.2xlarge","c5.4xlarge"]
        onDemandPercentageAboveBaseCapacity: 50
        spotAllocationStrategy: capacity-optimized
        spotInstancePools: 2
        onDemandBaseCapacity: 0

**Comment by ruecarlo** [comment]
Just one tiny correction in the  example provided  above in regards to `capacity-optimized`.

`capacity-optimized` and `spotInstancePools` are incompatible. `spotInstancePools` is only relevant to `lowest-price`

Doc link : https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html

**Comment by yahavb** [comment]
good call @ruecarlo

**Comment by martina-if** [comment]
fixed via https://github.com/weaveworks/eksctl/pull/1883
