### ISSUE TITLE
albIngress does not add correct permissions for ALB v1.1.2

### ISSUE THREAD

**Issue by asfernandes** [weaveworks/eksctl#1196]
I created cluster using `nodegroups[*].iam.withAddonPolicies.albIngress` but when creating an ingress using ALB v1.1.2 the logs show:

```txt
kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to get AWS tags. Error: AccessDeniedException: User: ... is not authorized to perform: tag:GetResources\n\tstatus code: 400, request id: e4d271f9-7b01-40aa-aba4-80321129b64e"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"http-echo-ingress2"}
```

If I manually attach the recommended policy to the nodegroup, it works.

**Comment by cPu1** [comment]
The error suggests that the policy `tag:GetResources` was missing, but this policy is indeed added by `eksctl` if `nodegroups[*].iam.withAddonPolicies.albIngress` is set. 

What policy did you have to attach to the node group? If you explicitly configured AWS ALB Ingress controller to use separate credentials by passing the `AWS_*` environment variables to the container, in which case the instance profile credentials are not looked up, you'll need to manually grant access to the user.

**Comment by asfernandes** [comment]
> The error suggests that the policy `tag:GetResources` was missing, but this policy is indeed added by `eksctl` if `nodegroups[*].iam.withAddonPolicies.albIngress` is set.
> 
> What policy did you have to attach to the node group?

This policy: https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.2/docs/examples/iam-policy.json

This is my cluster.yaml relevant section:

```yaml
nodeGroups:
  - name: ng-t3a-small-public
    iam:
      withAddonPolicies:
        ALBIngress: true
```

> If you explicitly configured AWS ALB Ingress controller to use separate credentials by passing the `AWS_*` environment variables to the container, in which case the instance profile credentials are not looked up, you'll need to manually grant access to the user whose credentials were used.

I did not. I only set `--cluster-name=`.

**Comment by cPu1** [comment]
```yaml
      withAddonPolicies:
        ALBIngress: true
```

So the issue is you're using `ALBIngress` instead of `albIngress`. The fields are case-sensitive. Using `albIngress` should fix the issue. Please let us know.

**Comment by asfernandes** [comment]
Humm, then it must be. I probably saw it wrong spelled in some place. I'll close it and inform when I test again.
