### ISSUE TITLE
Integration tests cause side effects impacting subsequent tests

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/eksctl#1210]
**What happened?**
Each individual integration test doesn't clean up after being done, causing side effects
which can impact subsequent tests in the same cluster.

For instance the `install flux` and `apply gitops` tests both install Flux, which should not work since the Flux installation isn't idempotent (until https://github.com/weaveworks/eksctl/pull/1203 lands).

**What you expected to happen?**
Each test cleans up when done or we use a separate, fresh cluster per test.

**Comment by errordeveloper** [comment]
We should generally have separate suites for each of different areas of functionality that we test, I've started #1192 to address that.

**Comment by martina-if** [comment]
I think this has been already solved here if not before https://github.com/weaveworks/eksctl/pull/1884
