### ISSUE TITLE
Add a way to provide the Flux SSH key, instead of port-forwarding to retrieve it

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1213]
> @marccarre I'd like to discuss the SSH key separately. My view is that it we shouldn't rely > on Flux to generate the key.
> 
> The reason to that is the following:
> 
> We will definitely need a way for user to specify the key file or body. We can do that in way where we have two different modes - key is either supplied and passed in, or it's generated by flux.
> If there was no extra complexity, I wouldn't mind that, however obtaining the key from flux requires forwarding a port, which we currently do, but I would rather get rid of this complexity and allow users to disable flux daemon port (possibly make that the default).
> So I think the design would be much less complex if we have two modes:
> - user provides the key, eksctl creates the secret
> - eksctl generates the key, writes it to a file locally and creates the secret

_Originally posted by @errordeveloper in https://github.com/weaveworks/eksctl/pull/1203#issuecomment-525261297_

---

_Part of: #1180_

**Comment by errordeveloper** [comment]
@marccarre thanks for opening the issue. To be clear my suggestion is that we should also review how key is generated when not provided by the user. In my mind It's much less complex to generate a key locally instead of waiting for Flux to do it and obtaining it via a tunnelled connection.

**Comment by errordeveloper** [comment]
See also #1211.

**Comment by Callisto13** [comment]
Closing due to https://github.com/weaveworks/eksctl/issues/2963
