### ISSUE TITLE
use ARN parser

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#1218]
We should consider defining ARN type and using the parser that SDK provides ([`github.com/aws/aws-sdk-go/aws/arn`](http://godoc.org/github.com/aws/aws-sdk-go/aws/arn)).

**Comment by aclevername** [comment]
> It looks like this package is now in use at least [in some places](https://github.com/weaveworks/eksctl/blob/8ab886b8752038a3ee521aa30dc356468211c6f0/pkg/iam/arn.go) throughout eksctl.

Yep, closing.
