### ISSUE TITLE
Refactor git.Client/executor.Executor

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/eksctl#1222]
1. Contexts shouldn't be stored for anything which isn't ephemeral and short-lived. They should just be passed when invoking each operation.
2. ~We should probably tie the git client to a specific directory, where the clone lives and clone upon creation of the client (the usage of the client always starts with a clone).~ We should make the directory explicit, not added implicitly when cloning.
3. Timeouts shouldn't be implicit, but simply passed through the context (related to #1212 )

**Comment by errordeveloper** [comment]
I'd say it's best to use a library instead, unless this would a minor change?

**Comment by michaelbeaumont** [comment]
I feel like this _might_ be solved/a part of #3066?
