### ISSUE TITLE
Missing m5.16xlarge from max_pods.map due to which kubelet fails to start

### ISSUE THREAD

**Issue by nithu0115** [weaveworks/eksctl#1229]
**What happened?**
A description of actual behavior (with error messages).
Missing m5.16xlarge from max_pods.map due to which kubelet fails

**What you expected to happen?**

Missing m5.16xlarge instance type from the max_pods.map is causing kubelet daemon not able to start issue. 

**How to reproduce it?**
Include the steps to reproduce the bug
Launch m5.16xlarge instance type which would fail to join the cluster. If you check kubelet logs, you would see below error:

```
Aug 29 18:58:50 ip-192-168-5-5.us-west-2.compute.internal kubelet[25640]: F0829 18:58:50.172283   25640 server.go:147] invalid argument "" for "--max-pods" flag: strconv.ParseInt: p
```

**Comment by errordeveloper** [comment]
This will be an easy fix, I've got a PR already - #1238. Adding to release milestone also.
