### ISSUE TITLE
CoreDNS add-on

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#123]
- [ ] working instruction for swapping out kube-dns
- [ ] plan for adding as proper addon

**Comment by errordeveloper** [comment]
@miekg are would you or other CoreDNS folks be interested to help with this?

**Comment by miekg** [comment]
We could probably help here.

@fturib  @chrisohaver

**Comment by fturib** [comment]
adding also @rajansandeep that helped already on integration of CoreDNS in several deployment tools

**Comment by rajansandeep** [comment]
@errordeveloper I have started to work on this.

**Comment by richardcase** [comment]
@errordeveloper - is the plan to install this addon by default when creating a cluster? 

Probably a good idea as per, https://github.com/kubernetes/community/blob/master/keps/sig-network/0012-20180518-coredns-default-proposal.md

**Comment by errordeveloper** [comment]
Perhaps it's something we can discuss. One counter argument would be about
sticking to what AWS officially supports.

**Comment by errordeveloper** [comment]
As of 1.11, EKS ships CoreDNS.
