### ISSUE TITLE
reconsider name of subdirectory created by `gitops apply` 

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/eksctl#1234]
Right now `gitops apply` stores the profile manifests under the `base` subdirectory.

Using `base` doesn't really make much sense (I think this is just a leftover from the time we were considering to use Kustomize). 

I think it would be more appropiate to use the quickstart-profile alias (e.g. `app-dev`) or infer a unique name from the repository URL if no alias exists.

**Comment by cPu1** [comment]
Agreed, the decision to use `base` was from the Kustomize proposal and using it for a templates-based solution (Go templates) doesn't make much sense.
