### ISSUE TITLE
unclear user feedback after running `gitops apply`/`install flux`

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/eksctl#1235]
Right now neither `install flux` nor `gitops apply` give you a clear confirmation of _everything is working_ after the commands finish succesfully:

1. `eksctl install flux` confirms that Flux and the Helm Operator are running but not a 100% confirmation of flux being capable of deploy workloads. Validation stops when asking the user to whitelist Flux's SSH key.

2. `eksctl gitops apply` doesn't confirm that the profile was actually deployed nor that the workloads are _working as expected_.

Improving (1) and (2) is hard for different reasons:

- (1) `eksctl install flux` currently requires manual intervention. I am not sure we can do much better without bypassing the SSH key addition (e.g. by providing the SSH key ourselves #1213 ) or blocking to wait for the user to add the SSH key and confirm it was added succesfully.
- (2) Is really hard for deeper reasons:
  a. Flux doesn't give you clear machine-friendly feedback on whether the deployment went well (some users have gone as far as parsing the Flux logs to gather this information).
  b. Kubernetes doesn't provide a general feedback mechanism telling you whether a set of resources have been deployed _successfully_ (for some definition of successfully). We could evaluate the state of the deployed resources on a case by case basis, but I think that's completely out of scope for `eksctl`.

**Comment by Callisto13** [comment]
Closing: https://github.com/weaveworks/eksctl/issues/2963
