### ISSUE TITLE
Clean up cmdutils package

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/eksctl#1240]
In particular the `cmdutils/cmdutils.go` contains flag parsing helpers which:

1. Should probably belong to the ctl package where they are used
2. Uses constant strings for flags (e.g. "--name" "--cluster") , which can get out of sync with the actual flags being declared, see

**Comment by errordeveloper** [comment]
The idea is that there are _many_ flags in common. If you don't put them in one place, they again get out of sync different ways.

**Comment by 2opremio** [comment]
That's not the case for some commands, and doesn't conflict with using constants  instead of string literals.
