### ISSUE TITLE
README.md install script should be refined to avoid root escalation

### ISSUE THREAD

**Issue by szegedim** [weaveworks/eksctl#1245]
**What happened?**
A description of actual behavior (with error messages).
I see this code in your readme.
```
curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin
```
It is super dangerous. Another script running will have a race on the file in tmp, they may be able to replace it before the file is copied to the final location gaining root from non-root access.

**What you expected to happen?**
Direct extraction to the final location. One line.

**How to reproduce it?**
Include the steps to reproduce the bug
Just run the script in the README.md

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
$ kubectl version
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by gemagomez** [comment]
Could you please suggest a change that would make the installation process more secure to the docs?

**Comment by szegedim** [comment]
@gemagomez thank you for the consideration.
I would do the following to avoid the unnecessary sudo. Folks can just add `~/.local/bin` to the current `$PATH`
```
# curl --tlsv1.3 --location "https://github.com/weaveworks/eksctl/releases/downlo
ad/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C ~/.local/bin
```

Unfortunately there is some prerequisite to this change since S3 does not seem to support TLS1.3:
```
# curl --tlsv1.3 --location "https://github.com/weaveworks/eksctl/releases/downlo
ad/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C ~/.local/bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   616    0   616    0     0   2588      0 --:--:-- --:--:-- --:--:--  2599
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github-production-release-asset-2e65be.s3.amazonaws.com:443
```
https://calcomsoftware.com/leaving-tls1-2-using-tls1-3/

**Comment by eightlimbed** [comment]
> It is super dangerous. Another script running will have a race on the file in tmp, they may be able to replace it before the file is copied to the final location gaining root from non-root access.

Hi @szegedim -- I just want to make sure I am understanding correctly... This is only dangerous if another process on the machine is (or wants to) opening `/tmp/eksctl`?

If not, can you please help me understand why the original instructions in the README are dangerous?

If so, how would another process know `/tmp/eksctl` is going to exist once `tar` finishes?
And wouldn't this dangerous behavior require a malicious actor to already have access to the user's machine?

**Comment by szegedim** [comment]
Yes, it is a bit dangerous practice, indeed. There are numerous reasons. That is why I pointed it out. Why do not you just do the copy on the fly instead of a temporary file, since it does not have any meaningful value? Another option is to ignore the sudo and just add the item to the path.

**Comment by eightlimbed** [comment]
> Yes, it is a bit dangerous practice, indeed. There are numerous reasons. That is why I pointed it out. Why do not you just do the copy on the fly instead of a temporary file, since it does not have any meaningful value? Another option is to ignore the sudo and just add the item to the path.

Can you give one reason why it's dangerous, please? I am trying to learn something :)

**Comment by szegedim** [comment]
You are one user on a shared machine. Why do you give that file to everyone on the same machine? Why do you move a random file from a shared /tmp that anyone can access or write to a shared location rather than using a user local directory? Why not sticking to the latest https standards? Why not doing the move, if the full download succeeds, potentially overwriting a working executable with a potentially corrupted one? Nowadays probably the issue is smaller, since lots of stuff is running in containers, so you do not access the outside file system but on bare metal machines these might be issues.

**Comment by martina-if** [comment]
Hi @szegedim thank you for bringing up this concern. We welcome contributions from the community, if you think this is important enough and have an idea on what would be instructions it would be very appreciated if you could open a PR to change these files:

- https://github.com/weaveworks/eksctl/blob/master/site/content/introduction/02-installation.md
- https://github.com/weaveworks/eksctl/blob/master/README.md
