### ISSUE TITLE
eksctl delete does not wait until complete resource deletion

### ISSUE THREAD

**Issue by Thomas999999** [weaveworks/eksctl#1246]
**What happened?**
We have automated EKS cluster creation/deletion vi terraform script using eksctl and existing VPC:
[0m[0mnull_resource.terraform_eks (remote-exec): [36m[✔]  using existing VPC (vpc-0d28700b6b6a19c77) and subnets (private:[] public:[subnet-0b5cc819ab7b281c1 subnet-0ea9eca76f3f22df7])

_aws eksctl delete_ command reports that all cluster resources were deleted but indeed they are not.
This is the output:
using region eu-west-1
[ℹ]  deleting EKS cluster "i027628-11111"
[✔]  kubeconfig has been updated
[ℹ]  cleaning up LoadBalancer services
[ℹ]  2 sequential tasks: { delete nodegroup "workers", delete cluster control plane "i027628-11111" [async] }
[ℹ]  will delete stack "eksctl-i027628-11111-nodegroup-workers"
[ℹ]  waiting for stack "eksctl-i027628-11111-nodegroup-workers" to get deleted
[ℹ]  will delete stack "eksctl-i027628-11111-cluster"
[✔]  all cluster resources were deleted

During automation of create and delete cluster environment with terraform this leads to errors as we run after the eksctl delete command the terraform destroy command (which waits on the output of eksctl delete). 
But the terraform destroy command ends with errors as VPC cannot be deleted as the EKS cluster is not completely deleted (still being deleted) and dependencies are not resolved. 

**What you expected to happen?**
I would expect that the command _eksctl delete cluster --name ${cluster_name}_ waits until all cluster resources (cloudformation stack, cluster) are really deleted and only then states:
_all cluster resources were deleted_

**How to reproduce it?**
setup and destroy a cluster (scenario using existing VPC environment) with eksctl and check that cluster and cloudformation stacks are still in status _delete in progress_ after message _all cluster resources were deleted_
It takes about 10 minutes until cluster resources are really deleted....

**Versions**
Please paste in the output of these commands:
```
[root@ip-192-168-4-217 ~]# eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.4.3"}
[root@ip-192-168-4-217 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.13", GitCommit:"954ff68d59e9dc62fa8252ffa9023a90ff8a358c", GitTreeState:"clean", BuildDate:"2019-02-13T11:15:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
[root@ip-192-168-4-217 ~]#

```

**Comment by errordeveloper** [comment]
Please use `--wait` flag. The current optimistic behaviour is not ideal, but we don't want to spend 10-15 minutes waiting.
