### ISSUE TITLE
Automatically attach EBS volumes to nodes

### ISSUE THREAD

**Issue by glapark** [weaveworks/eksctl#1253]
Hello,

I would like to automatically attach a set of EBS volumes to every EC2 instance (belonging to a given node group) when it starts. In our use case, Pods write temporary data to hostPath volumes, so host nodes need EBS volumes mounted to local directories. Our current workaround is to use instance storage instead of EBS volumes. That is, we use an instance type that comes with instance storage (e.g., m5d.x2large), and mount instance storage using preBootstrapCommands, e.g.:

    preBootstrapCommands:
      - "mkfs -t ext4 /dev/nvme1n1"
      - "mkdir -p /ephemeral1"
      - "mount /dev/nvme1n1 /ephemeral1"
      - "chown ec2-user:ec2-user /ephemeral1"

Any comment or help will be appreciated very much.

Thank you.

--- Sungwoo

**Comment by errordeveloper** [comment]
Hi @glapark, this is a good question. We do provide an EBS volume for all instance and mount it on `/`, do you require to use multiple pre-provisioned volumes? Would using a large root volume suffice? We expose a few fags - `volumeSize`, `volumeType`, `volumeIOPS` as well as `volumeKmsKeyID`. If you must use a separate volume, I'm all ears, but even then, I'd consider using a DaemonSet to set those volumes app, or look for something else. In `eksctl` we attempt to do the minimum require to boot a node, the idea is that any needs application my have should be achievable in some way through Kubernetes API.

**Comment by glapark** [comment]
Hello @errordeveloper,

Using a single large volume works okay for small instance sizes. However, when using large instance sizes, many threads/Pods can write a lot of intermediate data to local disks, and having multiple EBS volumes definitely helps (especially if the limit on the throughput of EBS volumes is reached).

The situation could be compared to running an EMR cluster. Each node in an EMR cluster is provisioned with multiple EBS volumes, instead of a single large EBS volume, for a good reason. For example, a Hadoop job can write intermediate data to all EBS volumes by rotating through them. Our use case is similar to such Hadoop jobs.

As a workaround, I tried to attach multiple dynamic PersistentVolumeClaims to each Pod (instead of sharing multiple EBS volumes among all Pods running in the same EC2 instance). This works, but is quite cumbersome. For example, it is unclear to me how to make sure that a new dynamic PersistentVolumeClaim is created on the same AZ as the destination Pod (perhaps because of my limited knowledge on EKS).

If eksctl is primarily responsible for booting a node, it sounds like attaching EBS volumes could be one of its basic operations :-)

--- Sungwoo

**Comment by errordeveloper** [comment]
> The situation could be compared to running an EMR cluster. Each node in an EMR cluster is provisioned with multiple EBS volumes, instead of a single large EBS volume, for a good reason. For example, a Hadoop job can write intermediate data to all EBS volumes by rotating through them. Our use case is similar to such Hadoop jobs.

Do you allocate a volume per e.g. workload or group of workloads? Could be based on a label selector?

I am not sure if there is solution to this, but I think there should be some kind of solution that doesn't require a particular configuration on the host.

> ...how to make sure that a new dynamic PersistentVolumeClaim is created on the same AZ as the destination Pod

I am not very clear on whether there is a solution to this, perhaps new EBS CSI driver solves this? I'd look into this as a foremost priority.

**Comment by glapark** [comment]
> Do you allocate a volume per e.g. workload or group of workloads? Could be based on a label selector?

We would like to allocate several volumes per node, not per Pod or workload, so that all Pods running on the node can share these volumes. This is because all Pods cooperate to process individual workloads (like a single SQL engine serving all incoming queries).

We thought about three approaches:

1. Attach instance storage and share it among all Pods. This is feasible using eksctl.

2. Attach EBS volumes to each node and share them among all Pods. We don't know how to achieve this using eksctl.

3. Attach dynamic PersistentVolumeClaims to each Pod. We know how to achieve this, but only in limited circumstances (where the cluster should run in a single AZ). Besides this is far from an ideal solution because these volumes store only temporary data.
 
For now, we use approach 1, with the limitation that we cannot use those instance types without instance storage.

> > ...how to make sure that a new dynamic PersistentVolumeClaim is created on the same AZ as the destination Pod
> 
> I am not very clear on whether there is a solution to this, perhaps new EBS CSI driver solves this? I'd look into this as a foremost priority.

We extended our code (without using eksctl) to do this.

--- gla

**Comment by errordeveloper** [comment]
Just out of curiosity, have you consider using EFS or other options?

**Comment by glapark** [comment]
Yes, I considered using EFS for local storage, but it was decided against.

Pros: 
1. easy to set up 
2. (very specific to our system) allows some optimization on network transmission because we can dispense with transmission between nodes

Cons:
Perhaps slow because of the limit on the throughput. If I understood the AWS documentation correctly, the throughput limit is per region. For example, with 1GB/s limit and 50 nodes in the cluster, each node can use 20MB/s in effect. 

For this reason, we decided to use instance storage.

--- gla

**Comment by michaelbeaumont** [comment]
Related use case: https://github.com/weaveworks/eksctl/issues/1313

**Comment by melodyyangaws** [comment]
> Hello @errordeveloper,
> 
> Using a single large volume works okay for small instance sizes. However, when using large instance sizes, many threads/Pods can write a lot of intermediate data to local disks, and having multiple EBS volumes definitely helps (especially if the limit on the throughput of EBS volumes is reached).
> 
> The situation could be compared to running an EMR cluster. Each node in an EMR cluster is provisioned with multiple EBS volumes, instead of a single large EBS volume, for a good reason. For example, a Hadoop job can write intermediate data to all EBS volumes by rotating through them. Our use case is similar to such Hadoop jobs.
> 
> As a workaround, I tried to attach multiple dynamic PersistentVolumeClaims to each Pod (instead of sharing multiple EBS volumes among all Pods running in the same EC2 instance). This works, but is quite cumbersome. For example, it is unclear to me how to make sure that a new dynamic PersistentVolumeClaim is created on the same AZ as the destination Pod (perhaps because of my limited knowledge on EKS).
> 
> If eksctl is primarily responsible for booting a node, it sounds like attaching EBS volumes could be one of its basic operations :-)
> 
> --- Sungwoo

+ 1 We have a similar use case that requires to mount multiple EBS volumes per node in EKS. We are running Spark benchmark test in 3TB scale. Plan to mount 4 EBS volumes per node as Spark's scratch space to increased the IOPS performance. Having a large 'D' instance type that comes with a huge local NVMe storage volume is the workaround at the moment. However, it's wasteful to use a large compute instance type just to have the huge storage. It would be more cost effective and scalable, if we can automatically attach multiple EBS volumes at the node level.

**Comment by cPu1** [comment]
> +1 We have a similar use case that requires to mount multiple EBS volumes per node in EKS. We are running Spark benchmark test in 3TB scale. Plan to mount 4 EBS volumes per node as Spark's scratch space to increased the IOPS performance. Having a large 'D' instance type that comes with a huge local NVMe storage volume is the workaround at the moment. However, it's wasteful to use a large compute instance type just to have the huge storage. It would be more cost effective and scalable, if we can automatically attach multiple EBS volumes at the node level.

@melodyyangaws thanks for sharing your use-case. We are looking on a feature that'd allow configuring multiple volumes for a nodegroup.

**Comment by alexsorokin-at** [comment]
Any updates here?

**Comment by Skarlso** [comment]
Pulled this into refinement to pick up and talk about. We'll see where we'll get to with this. Meanwhile, we accept contributions. :)

**Comment by Skarlso** [comment]
Gotcha, thanks. I'll look into this.

**Comment by Skarlso** [comment]
As per CloudFormation, we should be able to define a MountPoint which should do the trick. If that doesn't work however, then there is little as to what `eksctl` can do I'm afraid.

**Comment by Skarlso** [comment]
Sadly there is no option to auto mount a volume. And we no longer manipulate the userdata with custom scripts of our own that overwrite existing scripts.

You'll have to add a small script in override so the mounts are mounted upon launch. :/ Sorry.

**Comment by Skarlso** [comment]
For more info see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html.

I'm going to close this issue for now with this information. Please feel free to reopen if you stumble upon any other solution. Thanks!

**Comment by praneshpandurangan-at** [comment]
> @alexsorokin-at Hi!
> 
> So, now we have the options to define multiple mounts for EBS volumes with this PR: #4725
> 
> Is that useful?
> 
> Cheers, Gergely.

@Skarlso on behalf of Alex: I upgraded to 0.90.0, and was able to supply multiple volumes in the config, and it works as promised!

Thanks a lot for your work on this, we really appreciate this!

**Comment by Skarlso** [comment]
Fantastic! :) Glad it works. :)

**Comment by melodyyangaws** [comment]
> > @alexsorokin-at Hi!
> > So, now we have the options to define multiple mounts for EBS volumes with this PR: #4725
> > Is that useful?
> > Cheers, Gergely.
> 
> @Skarlso on behalf of Alex: I upgraded to 0.90.0, and was able to supply multiple volumes in the config, and it works as promised!
> 
> Thanks a lot for your work on this, we really appreciate this!

@praneshpandurangan-at,  do you mind to share your `preBootsrapCommands` or config script in terms of how to mount multiplevolumes? In my case, we have 3 EBS + 1 NVMe SSD. The following is how I mount the NVMe:
```
managedNodeGroups: 
  - name: test-ebs
    preBootstrapCommands:
      - "sudo mkfs.xfs /dev/nvme1n1;sudo mkdir -p /local1;sudo echo /dev/nvme1n1 /local1 xfs defaults,noatime 1 2 >> /etc/fstab"
      - "sudo mount -a"
      - "sudo chown ec2-user:ec2-user /local1"
```

**Comment by praneshpandurangan-at** [comment]
> > > @alexsorokin-at Hi!
> > > So, now we have the options to define multiple mounts for EBS volumes with this PR: #4725
> > > Is that useful?
> > > Cheers, Gergely.
> > 
> > 
> > @Skarlso on behalf of Alex: I upgraded to 0.90.0, and was able to supply multiple volumes in the config, and it works as promised!
> > Thanks a lot for your work on this, we really appreciate this!
> 
> @[praneshpandurangan-at](https://github.com/praneshpandurangan-at) do you mind to share your `preBootsrapCommands` or config script , in terms of how to mount multiple volumes? In my case, we have 3 EBS + 1 NVMe SSD attached to a single node group. The following is how I mount the NVMe, which is the same way as @[glapark](https://github.com/glapark), who raised the issue initially.
> 
> ```
> managedNodeGroups: 
>   - name: test-ebs
>     preBootstrapCommands:
>       - "sudo mkfs.xfs /dev/nvme1n1;sudo mkdir -p /local1;sudo echo /dev/nvme1n1 /local1 xfs defaults,noatime 1 2 >> /etc/fstab"
>       - "sudo mount -a"
>       - "sudo chown ec2-user:ec2-user /local1"
> ```

Hey @melodyyangaws! We do mounting work at node startup time. For our instance types (same as @glapark , m5d.x2large, but some are m5.foobar, ie, no instance store) AWS allows mounting upto 11 EBS volumes, and makes them available as nvme1n1, etc. Our script at startup time is effectively just

```
devices = nvme list -o json
ebsDevices = devices.filter(d.ModelNumber === Amazon Elastic Block Store).filter(d.DevicePath != pathOfRootVolume)
// do your mounting work on one or more of the ebsDevices.
```
You can find the pathOfRootVolume (this is the one that eksctl automatically attaches) by parsing the output of `findmnt / --json'`. If I understand correctly, you have to do a filter like the above, because you have no idea which EBS volume is root, and which ones are from your `additionalVolumes`.

AWS documentation that helped me understand the translation: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html. In the table, the relevant case for me is HVM and "Recommended for EBS volumes". The relevant part about the name translation is 
```The device names that you specify for NVMe EBS volumes in a block device mapping are renamed using NVMe device names (/dev/nvme[0-26]n1). The block device driver can assign NVMe device names in a different order than you specified for the volumes in the block device mapping.```

Hope that helps!

**Comment by melodyyangaws** [comment]
Thanks for the details @[praneshpandurangan-at](https://github.com/praneshpandurangan-at). Let me give it a try.

**Comment by melodyyangaws** [comment]
Want to share the final working solution. Just a minor change in the original script. It mounts all the available EBS & NVMe SSDs, except the root device volume:
```
managedNodeGroups: 
  - name: test-vol
    preBootstrapCommands: 
       - "IDX=1;for DEV in /dev/nvme[1-9]n1;do sudo mkfs.xfs ${DEV}; sudo mkdir -p /local${IDX}; sudo echo ${DEV} /local${IDX} xfs defaults,noatime 1 2 >> /etc/fstab; IDX=$((${IDX} + 1)); done"
       - "sudo mount -a"
       - "sudo chown ec2-user:ec2-user /local*"
```

**Comment by thamurepo** [comment]
managedNodeGroups:
  - name: eks-ng01
    instanceType: m5.4xlarge
    instanceName: eks-.prod-01
    preBootstrapCommands:
      - "sudo mkfs.xfs /dev/nvme1n1;sudo mkdir -p /data;sudo echo /dev/nvme1n1 /data xfs defaults,noatime 1 2 >> /etc/fstab"
      - "sudo mount -a"
      - "sudo chown ec2-user:ec2-user /data"
    labels: 
      role: xyz
      appName: xyz
    desiredCapacity: 3
    maxSize: 5
    minSize: 2
    ssh:
      allow: true
      enableSsm: true
      publicKeyName: aws-instance-key
    volumeSize: 100
    volumeType: gp3
    volumeThroughput: 700
    additionalVolumes:
      - volumeName: '/dev/xvdb' # required
        volumeSize: 100
        volumeType: 'gp3'
        volumeEncrypted: false
       #volumeKmsKeyID: 'id'
        volumeIOPS: 3000
        volumeThroughput: 700
    subnets:
      - subnet-0CC
      - subnet-02c41d30
      - subnet-0bd7eb0
    privateNetworking: true
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
