### ISSUE TITLE
0.5.0 release notes

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#1268]
So far I have:
```
# Release 0.5.0

## Features

- [IAM Roles for Service Accounts](https://eksctl.io/usage/iamserviceaccounts) (#1265)
- New experimental command [`eksctl gitops apply`](https://eksctl.io/gitops-quickstart/setup-gitops/) (#1165, #1138)

## Bug Fixes

- Don't require EKS cluster to be ACTIVE before deleting the cluster (#1010, #1259)
- Update max pods table (#1229)
- Reinstall Flux when it's already installed (#1084)

## Code Improvements

- Extract Git-related logic from `eksctl install flux` into a package (#1077)
- Restructure Git-related tests (#1231)
- Add integration test for `eksctl install flux` (#1078)
```

**Comment by errordeveloper** [comment]
We should also decide on whether RC is needed or not.

**Comment by cPu1** [comment]
We have been following the convention of starting each item with a capitalised word. For e.g.,
```
- update max pods table (#1229)
```
Do we no longer want to follow that? I don't have a strong preference on either style.

**Comment by gemagomez** [comment]
Can we point to the quickstart guide documentation as well?

**Comment by errordeveloper** [comment]
@cPu1 we've not followed it very consistently, e.g. 0.4.0 has a mix... but I wasn't aware of it and happy to stick to the convention.

Is there anything else important that [will go into the release](https://github.com/weaveworks/eksctl/milestone/20?closed=1) that I've missed?

**Comment by cPu1** [comment]
Found two more items to add to the release notes:
```
## Features

Add region Bahrain (me-south-1) (#1239)

## Code Improvements

Enforce SSH Git URLs in install flux & gitops apply commands
```
