### ISSUE TITLE
Make CloudFormation easier to compose

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#127]
At the moment we have a number of issues where compassable CloudFormation would help (#42, #69, #120, #122).

Managing templates as YAML and embedding them in Go using `bindata` is not particularly delightful, but not an issue per-se. What's hard is piecing together Go code and any logic that is implemented with CloudFormation  intrinsic functions, stack parameters and conditions.

Additionally, it would be much more convenient if we have a single stack composed of optional parts (VPC, IAM role, control plane), and separate (nested?) stacks for nodegroups. This would simplify much of our code.

So we could either invent something ourselves, if we wanted to, but I found that [goformation](https://github.com/awslabs/goformation#marshalling-cloudformationsam-described-with-go-structs-into-yamljson) already does what's needed (and I made an improvement (~https://github.com/awslabs/goformation/pull/95~, https://github.com/awslabs/goformation/pull/103) to it that allows to use `Ref`s and other intrinsics). 

The idea would be to compose the stack using Go structs. First of all we would use Go instead of CloudFormation for conditionals, as it's much easier to grasp all the parameters. We would leverage some CloudFormation runtime functionality to the minimum extended needed, but anything that would take more then one nested intrinsic function would be done in Go, unless information is only available inside of CloudFormation runtime (e.g. resource IDs for VPCs, subnets etc).

**Comment by errordeveloper** [comment]
cc @christopherhein @nckturner @PaulMaddox @jstrachan

**Comment by Raffo** [comment]
I've never used goformation myself, but it definitely look promising and I am generally against having too many big yamls that gets too complicated... so going "code first" would be IMO a very good thing (once your PR upstream is merged).

**Comment by errordeveloper** [comment]
I have started on this in #132, here is what it will look like:

```Go
func newRef(refName string) interface{} {
	return map[string]string{"Ref": refName}
}

func addResourcesForVPC(t *cloudformation.Template, stackName string, globalCIDR *net.IPNet, subnets map[string]*net.IPNet) {
	t.Resources["VPC"] = &cloudformation.UntypedAWSEC2VPC{
		CidrBlock:          globalCIDR.String(),
		EnableDnsSupport:   true,
		EnableDnsHostnames: true,
	}
	refVPC := newRef("VPC")

	t.Resources["InternetGateway"] = &cloudformation.AWSEC2InternetGateway{}
	refIG := newRef("InternetGateway")
	t.Resources["VPCGatewayAttachment"] = &cloudformation.UntypedAWSEC2VPCGatewayAttachment{
		InternetGatewayId: refIG,
		VpcId:             refVPC,
	}

	t.Resources["RouteTable"] = &cloudformation.UntypedAWSEC2RouteTable{
		VpcId: refVPC,
	}
	refRT := newRef("RouteTable")

	t.Resources["Route"] = &cloudformation.UntypedAWSEC2Route{
		RouteTableId:         refRT,
		DestinationCidrBlock: "0.0.0.0/0",
		GatewayId:            newRef("InternetGateway"),
	}

	for az, subnet := range subnets {
		name := "Subnet_" + az
		t.Resources[name] = &cloudformation.UntypedAWSEC2Subnet{
			AvailabilityZone: az,
			CidrBlock:        subnet.String(),
			VpcId:            refVPC,
		}
		t.Resources["RouteTableAssociation_"+az] = &cloudformation.UntypedAWSEC2SubnetRouteTableAssociation{
			SubnetId:     newRef(name),
			RouteTableId: refRT,
		}
	}

	t.Resources["ControlPlaneSecurityGroup"] = &cloudformation.UntypedAWSEC2SecurityGroup{
		GroupDescription: "Cluster communication with worker nodes",
		VpcId:            refVPC,
	}
}
```

So as you can see, we can probably avoid most of parameter passing and substitute parameters directly, and only use references where it's absolutely necessary.

**Comment by nckturner** [comment]
+1, This seems like it would be really useful as things get more complicated.

**Comment by richardcase** [comment]
I think this approach is good, its better for composability and testing.

I'm wondering if we could you use a 'builder' and/or fluent interface around goformat for composing the the template?

**Comment by errordeveloper** [comment]
@richardcase if you have any specific thoughts around that, please comment in #132.
