### ISSUE TITLE
Make aws-iam-authenticator the default

### ISSUE THREAD

**Issue by jicowan** [weaveworks/eksctl#128]
Now that the Heptio authenticator have been moved to aws-sig, make the aws-iam-authenticator the default.  When eksctl creates the kubeconfig, it still refers to the heptio-iam-authenticator.

**Comment by jicowan** [comment]
You can install the binary [with the new name] through go now.

**Comment by errordeveloper** [comment]
We have Homebrew "package" for macOS users, and that pulls released binary
URL.
And we don't require users to have Go toolchain, so `go get` isn't really
an option.

**Comment by errordeveloper** [comment]
duplicate of #112
