### ISSUE TITLE
eksctl version displays 0.2.0-xxx when built from the master branch

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/eksctl#1282]
**What happened?**

- Built `eksctl` from the `master` branch
- `./eksctl version` reports:
```
[ℹ]  version.Info{BuiltAt:"1567603534", GitCommit:"0.2.0-296-g94dfbe2", GitTag:""}
```

**What you expected to happen?**

I was expecting to see `0.5.0-2` in the GitCommit version

**How to reproduce it?**

- Checkout master
- make build
- ./eksctl version

**Comment by errordeveloper** [comment]
Does it still do that when if you fetch all tags?

**Comment by dlespiau** [comment]
No it doesn't change things.

**Comment by dlespiau** [comment]
Also tried `--tags` at first in case you were using lightweight tags before realising the tags weren't on the master branch.

If you do a `git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit`, searching for `tag: ` shows `0.2.0` is the latest tag on `master`.

**Comment by errordeveloper** [comment]
We should review release scripts and see what needs to be done to get tags onto master. I always assumed that tags weren't associated with branches and were just independent pointers to commits - TIL!

**Comment by rndstr** [comment]
> assumed that tags weren't associated with branches and were just independent pointers to commits

Your assumption was correct. The issue at hand is that the commit that was tagged is not reachable from master. Just by merging the `release-X.Y` branch–which contains the tagged commit–back to master, the tag would be reachable and show up with `git describe`.

Having tags on master would be nice but not sure feasible without risking races.
