### ISSUE TITLE
automate cherry-picking commit

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#1284]
Now that we have release branches, we need to cherry-pick changes from master to such branches.

It's tedious and error-prone, plus there are different ways to go about it. We should automate it. It would be nice to say `/cherry-pick release-0.2` in a PR comment, and have that PR cherry-picked once it get merged.

**Comment by errordeveloper** [comment]
Some of challenges that I face are:

- having to decide if you should cherry-pick the merge commit vs individual commits
- missing commits, or cherry-picking in wrong order
- merging instead of cherry-picking (I've done it at least once by accident)
- making changes on release branch and cherry-picking back to master

**Comment by marccarre** [comment]
Cherry-picked changes are:
- harder to track
    - they have different commit hashes,
    - they aren't listed by GitHub (unlike merged changes), e.g. https://github.com/weaveworks/eksctl/commit/5a97e9a6ea18ea001b2281196d2d373d520004ce and https://github.com/weaveworks/eksctl/commit/94e3555b6327fe38bdd9d38fef87a26644cc967f only appear in their respective branches even though they're identical,
- easier to get wrong (easy to forget one of the commits, easy to cherry-pick in the wrong order, etc.),

so I'd rather keep cherry-pick for exceptional cases and use simple `git merge`s instead.
This is a lot cleaner, a lot more tractable, and a much more robust workflow in my opinion.

**Comment by martina-if** [comment]
I agree with that, although once you have a RC you should only include urgent bug fixes and nothing 
else. So any other feature that was merged into master afterwards shouldn't be in the actual release.
For that case I see two options:
  - cherry picking the bug fixes into the release branch 
  - commit bug fixes to the rc branch and then merge that branch into master

What do you think?

**Comment by marccarre** [comment]
> cherry picking the bug fixes into the release branch

This I'd rather avoid, because of the aforementioned downsides of `cherry-pick`.

> commit bug fixes to the rc branch and then merge that branch into master

This works too, although is less granular than what I suggested above.
Therefore we'd have to be sure we want to merge the entire `release-X.Y` back to `master`.

Note that an equivalent approach to what I suggested above, if preferred, could be:

- merging the PR to `release-X.Y`, 
- **not** deleting the feature branch immediately,
- merging the feature branch to `master`,
- deleted the feature branch.

**Comment by martina-if** [comment]
I was thinking that we also have the [issue with the eksctl version](https://github.com/weaveworks/eksctl/issues/1282), so if we merge the release branch back to master, first, we don't miss anything, and secondly we could fix that issue.

**Comment by marccarre** [comment]
Yes, but there may be (hopefully, rare!) cases where `master` and release branches have diverged enough that we cannot just simply merge one into the other, but merging feature branches in both may still be possible. 

That being said, I agree we ought to fix #1282, **and** find a way to elegantly implement our merging process/workflow.

For example, one way to "enforce" the process, yet not have it become too much of a burden on a daily basis could be to:
1. have a script comparing both branches and flagging anything in one but not in the other, and...
2. have our release script call that script and ask for confirmation before releasing, or even...
3. having similar logic in a Slack bot which would:
    1. automatically notify us of any divergence between branches, until we either...
    2. mark them as acceptable divergences, or...
    3. tell the bot to automatically merge what needs to be merged where it needs to be merged.
