### ISSUE TITLE
Cluster deletion fails with "OIDC is only supported in Kubernetes versions 1.13 and above"

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#1289]
**What happened?**
When trying to delete a cluster created with a prior version of eksctl, the cluster deletion fails.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.5.0"}

$ kubectl version
Not applicable
```

**Logs**
```
$ eksctl delete cluster eks1
using region us-west-2
deleting EKS cluster "eks1"
OIDC is only supported in Kubernetes versions 1.13 and above
```

**Comment by errordeveloper** [comment]
I think we should add two new function - `ctl.CheckOpenIDConnectSupported` and `oidc.IsSupportedSupport` (that wraps it). 

Call `ctl.CheckOpenIDConnectSupported` above here:

https://github.com/weaveworks/eksctl/blob/a28b29a1a9334dbb1a44708436f978dccaacb16d/pkg/ctl/delete/cluster.go#L113

Call `oidc.IsSupportedSupport` above `oidc.CheckProviderExists` here:

https://github.com/weaveworks/eksctl/blob/a28b29a1a9334dbb1a44708436f978dccaacb16d/pkg/cfn/manager/delete_tasks.go#L119
