### ISSUE TITLE
not able to attach existing IAM for cluster & worker

### ISSUE THREAD

**Issue by rampatnaik** [weaveworks/eksctl#1308]
Hello

Can you help me to use IAM-role1 for cluster and role2 fornode-worker

both role1 and role2 exist . I wanted to reuse them . 

I am using eksctl 0.5.2 version

**Comment by michaelbeaumont** [comment]
Hi, please look at all of the IAM docs at https://eksctl.io/usage/iam-policies/ and report back if you're unable to use the existing features for what you need.
