### ISSUE TITLE
Directory name chopped off

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/eksctl#1309]
**What happened?**
When I run 
```
eksctl gitops apply --cluster development --region us-west-2 --git-url git@github.com:tidepool-org/cluster-development --quickstart-profile git@github.com:tidepool-org/eks-quickstart-app-dev --git-email derrick@tidepool.org  --output-path ./
```
eksctl creates a directory with the final character omitted:

$ ls
cluster-developmen

**What you expected to happen?**
$ ls
cluster-development

**How to reproduce it?**
Simple run the any gitops apply.

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
```
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.5.2"}
```
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by michaelbeaumont** [comment]
A lot of refactoring has been done around the gitops commands since this issue was created, closing. Please open a new issue if anyone encounters this again!
