### ISSUE TITLE
use Jsonnet for templating

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/eksctl#1314]
**Why do you want this feature?**
I love your new gitops support.  However, I am not so excited about your choice of Go templates. A better match for templating JSON is jsonnet, which I presume you already know since you hint about using a different templating language. 

I would support using jsonnet as the templating language. Also, I request that you allow your config file to contain values to pass to jsonnet.  Right now, you only pass cluster name and region.  However, it would be useful to pass more data.

**What feature/behavior/change do you want?**
Swap jsonnet for Go templates.  Allow passing a yaml/json config object to the jsonnet templating engine.

**Comment by whereisaaron** [comment]
I love passing JSON objects been my API’s. I love how efficiently my Javascript can parse it. But, as a human, coding in JSON or variants thereof makes me want to poke my own eyes out 😵. I would personally not like to be stuck with `jsonnet`. Well, unless I could delegate the task to someone I didn’t like 😀. On the other hand, if `jsonnet` is an extra supported option to YAML Go templates, then no problem, we can each choose our favorite.

**Comment by derrickburns** [comment]
@whereisaaron Have you written Helm template files that attempt to embed other yaml?  These use Go templates.

The authors of Helm 3 realized (correctly) that  Go templates are for manipulating **raw** text.  Go templates know nothing about the structure of the text being templated. So it is easy to write Go templates that do not produce valid YAML, particularly because of YAML's indentation rules. 

By contrast, Jsonnet is for generating Json.  It is, by all accounts, elegant, pure, functional language that is purpose built for manipulating Json.  Databricks has written hundreds of thousands of lines of jsonnet code.  Works for them.  Works for me.

**Comment by michaelbeaumont** [comment]
Go template aren't ideal for YAML, however `eksctl` templating is and most likely will remain very limited in scope.
