### ISSUE TITLE
[CoreDNS] use forward plugin instead of proxy plugin  in kubernetes 1.14

### ISSUE THREAD

**Issue by s-tokutake** [weaveworks/eksctl#1315]
**Why do you want this feature?**

I want to use CoreDNS forward plugin in EKS.

- Kubernetes 1.14 use CoreDNS forward plugin instead of proxy plugin by default. 
  - cf https://github.com/kubernetes/kubernetes/pull/73267
- CoreDNS proxy plugin has problems and it was deprecated.
  - cf https://github.com/coredns/coredns/issues/1443

**What feature/behavior/change do you want?**

- run ` eksctl utils update-coredns ` , and update coredns configmap to use  forward plugin.

**Comment by sayboras** [comment]
Related issue in EKS as reference https://github.com/aws/containers-roadmap/issues/489

**Comment by sayboras** [comment]
@s-tokutake @martina-if seems like we can close this as per https://github.com/weaveworks/eksctl/pull/1729
