### ISSUE TITLE
generate helm client cert when installing flux

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/eksctl#1323]
**Why do you want this feature?**
When using eksctl to install flux, eksctl creates a `tiller` instance that requires TLS.  Great! However, this means that one cannot use the `helm` client to talk to tiller without a cert (and enabled certain environment variables). 

It would be very helpful if eksctl generated that cert and placed it (can the CA info) in $HELM_HOME so that one could use a local helm client (after setting the env variables). 

This in what I had to do without this:
```
INPUT=/tmp/eksctl.out
DIR=$(cat $INPUT | grep "Public" | sed -e 's/"$//' -e 's/.*"//')
cd $DIR

export TILLER_HOSTNAME=tiller-deploy.flux
export USER_NAME=helm-client
echo '{"signing":{"default":{"expiry":"43800h","usages":["signing","key encipherment","server auth","client auth"]}}}' > ca-config.json
echo '{"CN":"'$USER_NAME'","hosts":[""],"key":{"algo":"rsa","size":4096}}' | cfssl gencert \
  -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem \
  -hostname="$TILLER_HOSTNAME" - | cfssljson -bare $USER_NAME
HELM_HOME=${HELM_HOME:-~/.helm}

cp $DIR/helm-client.pem $HELM_HOME/cert.pem
cp $DIR/helm-client-key.pem $HELM_HOME/key.pem
cp $DIR/ca.pem $HELM_HOME/ca.pem
```

**Comment by derrickburns** [comment]
Upon reflection, this does not solve a bigger issue: the inability for OTHER administrators to use a helm client for this cluster.

For this, the ability to generate a cert is needed after the initial bringup. For this, we need the CA private key to be persisted.  

Since this tool is dedicated to AWS, I would suggest placing the private key in AWS Secrets Manager.

**Comment by Callisto13** [comment]
Closing due to staleness
