### ISSUE TITLE
creating cluster with existing SG

### ISSUE THREAD

**Issue by rampatnaik** [weaveworks/eksctl#1332]
**Why do you want this feature?**
I am using eksctl to create my cluster 
we use terraform for SG and Networking/SG group create the id 
and we need to attach the existing SG  while creating the cluster

**What feature/behavior/change do you want?**
eksctl create cluster -f cluster.yaml
1. I wanted to attach the existing SG and 
2. I wanted to add tags while creating cluster
key       = "kubernetes.io/role/internal-elb"
value     = "1"

**Comment by martina-if** [comment]
related to #1551

**Comment by michaelbeaumont** [comment]
Duplicate of https://github.com/weaveworks/eksctl/issues/1551
