### ISSUE TITLE
Deploying to existing VPC, private subnets only fails 

### ISSUE THREAD

**Issue by dszryan** [weaveworks/eksctl#1334]
**What happened?**
`kubectl get nodes` return empty

**What you expected to happen?**
`kubectl get nodes` should return the two nodes deployed

**How to reproduce it?**
run this command 
`eksctl create cluster -f eks-k8s-cluster.yaml -v 3`
for this config:
```
---
kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: k8s-cluster
  region: ap-southeast-2
vpc:
  id: vpc-004eb8
  cidr: 10.8.0.0/16
  autoAllocateIPv6: false
  nat:
    gateway: HighlyAvailable
  subnets:
    private:
      k8s-cluster/subnet-private-2a:
        id: subnet-0ba46c
        cidr: 10.8.0.0/24
      k8s-cluster/subnet-private-2b:
        id: subnet-01e21f
        cidr: 10.8.1.0/24
      k8s-cluster/subnet-private-2c:
        id: subnet-0771a4
        cidr: 10.8.2.0/24
nodeGroups:
  - name: k8s-cluster-ng-t3a-small-1
    instanceType: t3a.small
    desiredCapacity: 2
    privateNetworking: true
    minSize: 1
    maxSize: 3
    availabilityZones: [
      "ap-southeast-2a",
      "ap-southeast-2b",
      "ap-southeast-2c"
    ]
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
        ebs: true
cloudWatch:
  clusterLogging:
    enableTypes: [
      "api",
      "audit",
      "authenticator",
      "controllerManager"
    ]
```

got this output 
```
[ℹ]  using region ap-southeast-2
[✔]  using existing VPC (vpc-004eb8c46f5e3b9f3) and subnets (private:[subnet-0ba46c341eb21d88f subnet-01e21fa251cac090b subnet-0771a45119fe91173 subnet-01e21fa251cac090b subnet-0ba46c341eb21d88f subnet-0771a45119fe91173] public:[])
[!]  custom VPC/subnets will be used; if resulting cluster doesn't function as expected, make sure to review the configuration of VPC/subnets
[ℹ]  nodegroup "nec-k8s-cluster-ng-t3a-small-1" will use "ami-09f2d86f2d8c4f77d" [AmazonLinux2/1.13]
[ℹ]  using Kubernetes version 1.13
[ℹ]  creating EKS cluster "nec-k8s-cluster" in "ap-southeast-2" region
[ℹ]  1 nodegroup (nec-k8s-cluster-ng-t3a-small-1) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 1 nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=ap-southeast-2 --name=nec-k8s-cluster'
[ℹ]  3 sequential tasks: { create cluster control plane "nec-k8s-cluster", create nodegroup "nec-k8s-cluster-ng-t3a-small-1", update CloudWatch logging configuration }
[ℹ]  building cluster stack "eksctl-nec-k8s-cluster-cluster"
[ℹ]  deploying stack "eksctl-nec-k8s-cluster-cluster"
[ℹ]  building nodegroup stack "eksctl-nec-k8s-cluster-nodegroup-nec-k8s-cluster-ng-t3a-small-1"
[ℹ]  deploying stack "eksctl-nec-k8s-cluster-nodegroup-nec-k8s-cluster-ng-t3a-small-1"
[✔]  configured CloudWatch logging for cluster "nec-k8s-cluster" in "ap-southeast-2" (enabled types: api, audit, authenticator, controllerManager & disabled types: scheduler)
[✔]  all EKS cluster resource for "nec-k8s-cluster" had been created
[✔]  saved kubeconfig as "/home/rdsouza/.kube/config"
[ℹ]  adding role "arn:aws:iam::810793034528:role/eksctl-nec-k8s-cluster-nodegroup-NodeInstanceRole-1X4KURBQLC5OW" to auth ConfigMap
[ℹ]  nodegroup "nec-k8s-cluster-ng-t3a-small-1" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "nec-k8s-cluster-ng-t3a-small-1"
[✖]  timed out (after 25m0s) waiting for at least 1 nodes to join the cluster and become ready in "nec-k8s-cluster-ng-t3a-small-1"
```
it finally does time out and `kubectl get nodes` does not list any nodes (after manually setting up kubeconfig)

**Anything else we need to know?**
this configuration works - notice custom vpc configuration is missing
```
---
kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: sample-test
  region: ap-southeast-2
nodeGroups:
  - name: k8s-cluster-ng-t3a-small-1
    instanceType: t3a.small
    desiredCapacity: 2
    privateNetworking: true
    minSize: 1
    maxSize: 3
    availabilityZones: [
      "ap-southeast-2a",
      "ap-southeast-2b",
      "ap-southeast-2c"
    ]
    iam:
      withAddonPolicies:
        ebs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
cloudWatch:
  clusterLogging:
    enableTypes: [
      "api",
      "audit",
      "authenticator",
      "controllerManager"
    ]
```
_it seems the ec2 instance with `privateNetworking: true` and a custom vpc configuration, gets 1 NIC and is unable to talk to the control plane - the master node._

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.5.3"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-29T18:43:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by martina-if** [comment]
Hi @dszryan , thank you for reporting this.

When we have seen this before it was usually a problem with the VPC. I recommend that you check  NAT gateway configuration and Route tables. Also check [this section of the help](https://eksctl.io/usage/vpc-networking/#use-existing-vpc-any-custom-configuration). It could be that the VPC doesn't meet a requirement for EKS.

**Comment by dszryan** [comment]
@martina-if - thanks for the link - saved me the trouble of comparing two deployment instances.

i have added the missed tags mentioned in the link - but still facing the issue

still investigating the cause presuming it is a vpc configuration issue

+RD

**Comment by errordeveloper** [comment]
Please check the NAT Gateway setup, access to EKS currently depends on it to be present and configured correctly.

**Comment by dszryan** [comment]
@errordeveloper, i have - the only difference being the reference cluster (created without vpc/subnet definition) creates a route table for each individual subnet (ie SubnetPrivateAPSOUTHEAST2A) - and the route tables have the same content, local routing followed by the routing to the NAT.

i have created one route table with with those rules and attached it to the three private subnets.

but i didnt that would be cause of the issue?

**Comment by dszryan** [comment]
do i need to ensure i add the following tags across the VPC as well?
- alpha.eksctl.io/cluster-name
- eksctl.cluster.k8s.io/v1alpha1/cluster-name

**Comment by dszryan** [comment]
the following updates fixed the issue.

1. added kubernetes.io/role/elb tag set to 1 for public subnets
2. added tags 'alpha.eksctl.io/cluster-name' and 'eksctl.cluster.k8s.io/v1alpha1/cluster-name' to all resources (well every resource the reference cluster has as well)

**Comment by martina-if** [comment]
Thanks @dszryan for getting back with the solution! Glad it got fixed :+1:

**Comment by dszryan** [comment]
no worries.

@martina-if : while the documentation did mention adding the internal-elb value, it didnt mention the elb value.
maybe the documentation can be updated?

**Comment by martina-if** [comment]
@dszryan Right, good point. I will add that. Or you can add it if you prefer :)

**Comment by dszryan** [comment]
tru - will double check the config and update the doco
