### ISSUE TITLE
How to assign a secondary IP to a node?

### ISSUE THREAD

**Issue by skwokie** [weaveworks/eksctl#1339]
Hi,

I'd like to ask how to assign more than one private IP (network interface) to a node? Can someone please help?

**Use case**
The server(s) that I'm trying to provision requires 2 network interfaces on each node. It has a proxy server running in a pod and it will be connecting with ten of thousands of devices, and it needs two interfaces because it needs more ports than one can provide.

**Environment**
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.4.2"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

Thanks.

**Comment by errordeveloper** [comment]
If this is an application that you are deploying on Kubernetes, I believe you probably should be looking for a custom CNI solution. All of non-primary network interface (ENIs) on EC2 instances in EKS are managed by the [VPC CNI component](https://github.com/aws/amazon-vpc-cni-k8s). It maybe possible to run a pod in host network and add some additional ENIs specifically for your application, but that means only one application can run on a each node a time, and in any case it gets very application-specific and customising host networking for such purpose is not advisable.

If you need more help with this, please provide more details about the type of application you have. 

With regards to custom CNI solutions, please take a look at [multus](https://intel.github.io/multus-cni/), there probably other options too. I have no first-hand experience of doing this on EKS, but I'd expect that there is a way to make use of either multus or some other solution.

**Comment by michaelbeaumont** [comment]
@skwokie Closing for now, please feel free to reopen or open a new issue if the above explanation didn't help
