### ISSUE TITLE
How to read generated userdata for nodegroup?

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [weaveworks/eksctl#1342]
**What help do you need?**
How to read generated userdata for nodegroup? it seems to be hashed in some way.

**Comment by errordeveloper** [comment]
We use common `gzip+base64` format.

https://github.com/weaveworks/eksctl/blob/02a50eeb1ffd4fd91ceee81b77a7cbaf32763f48/pkg/cloudconfig/cloudconfig.go#L110-L123

**Comment by errordeveloper** [comment]
Re-opening, as we should document it, it's not the first time this question came up.

**Comment by Aelshafei** [comment]
echo "<encoded_user_data>" | base64 --decode | gunzip
