### ISSUE TITLE
Make Kubernetes 1.14 the default version

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#1351]
The AWS console still shows 1.13 as the default version. eksctl should switch to 1.14 as the default version when the Amazon EKS UI sets 1.14 as the default version.

**Comment by mogren** [comment]
Kubernetes 1.14 is the default in the EKS AWS Console since Friday September 27th.

**Comment by sayboras** [comment]
@cPu1 as the PR https://github.com/weaveworks/eksctl/pull/1392 is merged, not sure if we can close this issue.

**Comment by sayboras** [comment]
@martina-if ☝️

**Comment by cPu1** [comment]
@sayboras indeed this can be closed. Thanks
