### ISSUE TITLE
Suspend ASG processes

### ISSUE THREAD

**Issue by Vlatombe** [weaveworks/eksctl#1355]
**Why do you want this feature?**
When using a node group spanning multiple availability zones and using cluster autoscaler, there can be problems due to a native ASG process rebalancing nodes between AZ. AWS provides a way to suspend this process called [AZRebalance](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-suspend-resume-processes.html).

**What feature/behavior/change do you want?**
I'd like a way to provide a list of ASG processes to suspend when creating a node group. For example, here is how [kops](https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#suspending-scaling-processes-on-aws-autoscaling-groups) does it.

**Comment by d-kuro** [comment]
I will try it.

**Comment by romeotheriault** [comment]
We just migrated to EKS from kops and are missing this functionality. It would be great if this functionality was added since we now have to manually update the auto scaling group's every time we create a new nodegroup.

**Comment by jcmontigny-fox** [comment]
Same here. But we understand it is better not to span a single ASG on several AZ.

**Comment by dougbyrne** [comment]
Hi, I believe that this should be reopened, as the changes in #2487 don't seem to work. The AZRebalance process is suspended only while cloudformation is updating the ASG. I don't think that ever happens in the eksctl workflows, as they are immutable. Regardless, that doesn't solve the problem in this issue.

**Comment by ebr** [comment]
Currently `asgSuspendProcesses` is mentioned in the documentation, so it's expected to work. But it doesn't.

Would it be helpful to update the documentation while this is being fixed/implemented?
