### ISSUE TITLE
node bootstrap docs

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#1357]
There's currently very little documentation about node bootstrap process, that should be addressed. E.g. `preBootstrapCommands` and `overrideBootstrapCommand` only documented by example, it's not crystal clear to users how these work.

See the following as evidence:
- https://github.com/weaveworks/eksctl/issues/1099
- https://github.com/weaveworks/eksctl/pull/1335#issuecomment-533424767
- https://github.com/weaveworks/eksctl/issues/1178

**Comment by whereisaaron** [comment]
The #1335 document is great information that would be useful in a details/advanced topic section on the `eksctl.io` website. It is certainly more in English and less technical than the [config file schema](https://eksctl.io/usage/schema/) that is already on the website 😄 

The bootstrap process is a key difference between `eksctl` clusters and ‘standard’ EKS clusters, so it worth documenting for users. And if users are ever investigating a node problem, it is helpful to know what goes were on an `eksctl` bootstrapped node.
