### ISSUE TITLE
Make VPC private endpoint access work within VPC

### ISSUE THREAD

**Issue by D3nn** [weaveworks/eksctl#1358]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
A clear and concise description of why you want this feature. Include use-cases and any specific constraints you may have.

**What feature/behavior/change do you want?**
A clear and concise description of the change you would like to see in eksctl.

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by D3nn** [comment]
When enabling access to the Kubernetes API endpoint from within the cluster, make the changes necessary for allowing such access within the VPC (security groups, DNS updates, etc).  Currently, we are pointing customers at the documentation for them to enable this access, but would be better if we could manage this for them, at least for nodes inside the VPC.

**Comment by morinap** [comment]
@D3nn I was discussing this use case on the recently resolved https://github.com/weaveworks/eksctl/issues/649 and have just opened a PR that takes one simple approach to address this. I'm definitely willing to work on a more robust approach as well if desired (such as dynamically adding the ingress rules to a eksctl-created security group), but this approach worked perfectly for my use case.

**Comment by D3nn** [comment]
Scenarios we would like to handle for the user rather than forcing them to make changes:
1.  Worker nodes should be able to make Kubernetes API calls
1. Private access through VPC peering needs to forward DNS to the EKS Control Plane Private Route53 DNS domain.  Control Plane security group updated for API access from VPC peer network(s)
1. VPN access from customer sites should be able to resolve Endpoint from the EKS Control Plane Private Route53 DNS domain.  Control Plane security updated for API access from corp networks
1. DirectConnect access from customer sites should be able to resolve Endpoint from EKS Control Plane Private Route 53 DNS domain.  Control Plane security updated for API access from corp networks.
