### ISSUE TITLE
Remove superfluous `ExecStart` from systemd unit

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#1367]
The line isn't required:
https://github.com/weaveworks/eksctl/blob/master/pkg/nodebootstrap/assets/10-eksclt.al2.conf#L11

After this line is removed, the assets will need to be regenerated. `make build` handles that.

**Comment by praveensastry** [comment]
I will take this

**Comment by Taco7** [comment]
Raised a PR @cPu1 https://github.com/weaveworks/eksctl/pull/1383

**Comment by errordeveloper** [comment]
That line is intentional, see [systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#id-1.14.3).
