### ISSUE TITLE
Canary tiller is broken.  Do not use it by default.

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/eksctl#1374]
There is a least one major bug in the canary version of Tiller.  Unfortunately, `eksctl` installs that version by default with the experimental helm/tiller installer.  I strongly recommend only installing v2.14.3 or a later tested version of Tiller.

**Comment by kalbir** [comment]
Thanks @derrickburns - this is closed by https://github.com/weaveworks/eksctl/pull/1433
