### ISSUE TITLE
Deprecate v1.11 in eksctl: Nov 4

### ISSUE THREAD

**Issue by kalbir** [weaveworks/eksctl#1375]
AWS are deprecating Kubernetes v1.11 on Nov 4, 2019: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

eksctl will have to remove the ability to create 1.11 clusters and provide a message as with the 1.10 deprecation (screenshot below). 

<img width="949" alt="Screenshot 2019-10-01 at 11 58 42" src="https://user-images.githubusercontent.com/3952074/65956702-e441c200-e442-11e9-908e-e2ea8651fe43.png">

**Comment by errordeveloper** [comment]
We should also increase the minumum version of kubectl we look for.

**Comment by martina-if** [comment]
closed by #1384
