### ISSUE TITLE
Retry API Calls

### ISSUE THREAD

**Issue by richardcase** [weaveworks/eksctl#138]
We should consider retrying calls to AWS endpoints depending on the error returned.

For example, if calling [DeleteCluster](https://docs.aws.amazon.com/eks/latest/APIReference/API_DeleteCluster.html) and `ResourceNotFoundException` then its safe to continue on with deletion. But if a `ServiceUnavailableException` is returned then we should probably retry.

We should look at all AWS endpoint calls.

Related to #136

**Comment by karinnainiguez** [comment]
Hey @richardcase is this still something that you'd like someone to tackle? 

I was researching it to see if I could help, but I see that the [Delete Cluster](https://docs.aws.amazon.com/eks/latest/APIReference/API_DeleteCluster.html) function you mention is called in the deprecated function, and the [DeleteStack](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DeleteStack.html) function is now called.  I may be misunderstanding your ask, but feel free to let me know if there's an API call there that you'd like to be retried.  Thank you so much!  Hope you have a great rest of your day!

**Comment by richardcase** [comment]
@karinnainiguez - my original thoughts related to the Delete* API calls. But i think any call we make to AWS Endpoints should potentially be retried if there is a error (i.e. such as ServiceUnavailableException). What do you think?

**Comment by errordeveloper** [comment]
I think is can be closed now, we have introduced a retry handler in #689.
