### ISSUE TITLE
Remove `eksctl utils install-coredns` from AWS EKS userguide

### ISSUE THREAD

**Issue by rndstr** [weaveworks/eksctl#1382]
The content at https://docs.aws.amazon.com/eks/latest/userguide/coredns.html mentions to run `eksctl utils install-coredns --name dev --approve` but that command was removed in `eksctl-0.2.0` due to Kubernetes v1.10 deprecation in AWS (#1026).

The user guide should be updated.

**Comment by nrdlngr** [comment]
This deprecated command has been removed from the Amazon EKS user guide. This issue can be closed.
