### ISSUE TITLE
eksctl create cluster fails, then cleanup does not clean up the cnf stack

### ISSUE THREAD

**Issue by tehshwann** [weaveworks/eksctl#1386]
## Env Details
```
C:\> Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' | Select-Object ProductName, InstallationType, ReleaseId

ProductName           InstallationType ReleaseId
-----------           ---------------- ---------
Windows 10 Enterprise Client           1809

C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

C:\> aws --version
aws-cli/1.16.238 Python/3.7.3 Windows/10 botocore/1.12.228
C:\> eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.6.0"}
C:\>
```

## Behavior

If `eksctl create cluster` fails, it suggests a command to cleanup. Running the cleanup command succeeds. Subsequently retrying the same `eksctl create cluster` command fails due to the Cloud Formation (CFN) stack already existing, suggesting the cleanup either did not clean up the CFN resources, or didn't wait for them to be removed completely.

## Expected Behavior

If `eksctl` fails and suggests a command to correct or cleanup the resources in the failed command, successful execution of the cleanup command should allow the use to re-run the initial command without running into idempotency issues. I.E. `eksctl create cluster --name foo` -> `eksctl delete cluster --name foo` ->  `eksctl create cluster --name foo` should be a viable workflow without manual cleanup.

## Repro

https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html

1. Created an IAM use with the `Administrators` IAM role policy attached
2. Installed awscli, eksctl, kubectl & restarted my powershell core session/shell
3. Initialized the aws cli with my iam user via `aws configure`
4. Attempted to create a new cluster using:
```
eksctl create cluster --name smaloy --version 1.14 --nodegroup-name linux-workers --node-type t3.medium --nodes 3 --nodes-min 2 --nodes-max 4 --node-ami auto
``` 
  * Cluster create failed with:
  ```
   [ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
   [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-west-2 --name=smaloy'
   ```
5. Attempted cleanup using the command mentioned in the failure message:
```
eksctl delete cluster --region=us-west-2 --name=smaloy
[ℹ]  using region us-west-2
[ℹ]  deleting EKS cluster "smaloy"
[ℹ]  1 task: { delete cluster control plane "smaloy" [async] }
[ℹ]  will delete stack "eksctl-smaloy-cluster"
[✔]  all cluster resources were deleted
```
6. Retried the cluster creation, and it failed:
```
eksctl create cluster --name smaloy --version 1.14 --nodegroup-name linux-workers --node-type t3.medium --nodes 3 --nodes-min 2 --nodes-max 4 --node-ami auto
[ℹ]  using region us-west-2
[ℹ]  setting availability zones to [us-west-2b us-west-2c us-west-2a]
[ℹ]  subnets for us-west-2b - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for us-west-2c - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for us-west-2a - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "linux-workers" will use "ami-05d586e6f773f6abf" [AmazonLinux2/1.14]
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster "smaloy" in "us-west-2" region
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-west-2 --name=smaloy'
[ℹ]  CloudWatch logging will not be enabled for cluster "smaloy" in "us-west-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-west-2 --name=smaloy'
[ℹ]  2 sequential tasks: { create cluster control plane "smaloy", create nodegroup "linux-workers" }
[ℹ]  building cluster stack "eksctl-smaloy-cluster"
[ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-west-2 --name=smaloy'
[✖]  creating CloudFormation stack "eksctl-smaloy-cluster": AlreadyExistsException: Stack [eksctl-smaloy-cluster] already exists
        status code: 400, request id: 03640324-9610-4c63-b386-becc4ea578b3
[✖]  failed to create cluster "smaloy"
```

**Comment by D3nn** [comment]
@tehshwann: `eksctl delete` initiates the cluster delete process (which deletes the appropriate stacks), but doesn't wait for the deletion of the stacks to complete by default.

If you're wanting to make sure the stacks are gone before rerunning the command, you should add the `--wait` parameter to the `eksctl delete` command

**Comment by bartcant** [comment]
I have the same issue:

eksctl create cluster --name damltest1   --region us-east-2  --node-type m5.large  --nodes 1
[ℹ]  eksctl version 0.16.0
[ℹ]  using region us-east-2
[ℹ]  setting availability zones to [us-east-2a us-east-2b us-east-2c]
[ℹ]  subnets for us-east-2a - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for us-east-2b - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for us-east-2c - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng-24e4a9e6" will use "ami-020a35f771eac7c58" [AmazonLinux2/1.14]
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster "damltest1" in "us-east-2" region with un-managed nodes
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-2 --cluster=damltest1'
[ℹ]  CloudWatch logging will not be enabled for cluster "damltest1" in "us-east-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-east-2 --cluster=damltest1'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "damltest1" in "us-east-2"
[ℹ]  2 sequential tasks: { create cluster control plane "damltest1", create nodegroup "ng-24e4a9e6" }
[ℹ]  building cluster stack "eksctl-damltest1-cluster"
[ℹ]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-2 --name=damltest1'
[✖]  creating CloudFormation stack "eksctl-damltest1-cluster": AlreadyExistsException: Stack [eksctl-damltest1-cluster] already exists
        status code: 400, request id: 48278a26-6dda-415e-8e45-c026f96314a2
Error: failed to create cluster "damltest1"

eksctl delete cluster --region=us-east-2 --name=damltest1 --wait
[ℹ]  eksctl version 0.16.0
[ℹ]  using region us-east-2
[ℹ]  deleting EKS cluster "damltest1"
Error: fetching cluster status to determine if it can be deleted: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: damltest1.
        status code: 404, request id: 7330d90e-fa0b-43fc-ad1f-46341af16b80

Note: I had previously manually deleted the "damltest1" cluster from the AWS Console,

**Comment by jglick** [comment]
`--wait` does not help. The stack is still there, and prevents `eksctl create cluster` from working with the same name:

```json
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:…:…:stack/eksctl-…-cluster/…",
            "StackName": "eksctl-…-cluster",
            "TemplateDescription": "EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by eksctl]",
            "CreationTime": "2022-01-12T18:25:17.618000+00:00",
            "DeletionTime": "2022-01-12T19:02:59.907000+00:00",
            "StackStatus": "DELETE_COMPLETE",
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        }
    ]
}
```

This should be reopened. #2014 is just a duplicate AFAICT. There appear to be no workarounds other than
* using a different cluster name
* [waiting for three months](https://stackoverflow.com/a/65129908/12916)

**Comment by Skarlso** [comment]
I'm not sure I understand the waiting for three months part. You can always just go and remove the cloudformation stack which was created. It's not the cluster that fails it's the created cloudformation stack name. Just delete the cloudformation stack and you are good to go.

**Comment by jglick** [comment]
> Just delete the cloudformation stack

Does not work. You get an `AlreadyExistsException`. See https://stackoverflow.com/a/65129908/12916 as linked above, and the AWS reference explaining

> The `aws cloudformation list-stacks` command returns information on deleted stacks for 90 days after they have been deleted.

The stack is still in the system under the name which a new `eksctl create cluster` command would try to reuse, just with a status of `DELETE_COMPLETE`. `eksctl delete cluster` claims the cluster does not exist; `aws cloudformation delete-stack` silently succeeds without doing anything.

**Comment by aclevername** [comment]
> > Just delete the cloudformation stack
> 
> Does not work. You get an `AlreadyExistsException`. See https://stackoverflow.com/a/65129908/12916 as linked above, and the AWS reference explaining

This is not the behaviour I have observed. I often `eksctl create cluster --name jk`, `eksctl delete cluster --name jk` and then sometime down the line re-create it via `eksctl create cluster --name jk`. This never results in the a clash because a stack with the same name used to exist. 

If you are getting `AlreadyExistsException` its more likely the stack is in a `CREATE_FAILED` or `DELETE_FAILED` state, and not actually `DELETED`. You might need to switch the filters you lookup cloudformation stacks with to see this in the console.

**Comment by aclevername** [comment]
> > Just delete the cloudformation stack
> 
> Does not work. You get an `AlreadyExistsException`. See https://stackoverflow.com/a/65129908/12916 as linked above, and the AWS reference explaining

This is not the behaviour I have observed. I often `eksctl create cluster --name jk`, `eksctl delete cluster --name jk` and then sometime down the line re-create it via `eksctl create cluster --name jk`. This never results in the a clash because a stack with the same name used to exist. 

If you are getting `AlreadyExistsException` its more likely the stack is in a `CREATE_FAILED` or `DELETE_FAILED` state, and not actually `DELETED`. You might need to switch the filters you lookup cloudformation stacks with to see this in the console.

**Comment by jglick** [comment]
Pretty sure it was in `DELETE_COMPLETE` as written, but I will verify this the next time I hit the issue.

**Comment by Skarlso** [comment]
<img width="472" alt="Screenshot 2022-01-22 at 17 19 16" src="https://user-images.githubusercontent.com/182850/150646844-678925d7-3f84-450d-819b-d80a85f2f150.png">

Attaching the screenshot here too if people find this issue first rather than the linked one.

**Comment by ncoder** [comment]
FWIW, i hit the same issue. 
problem if the stack is in:
```txt
"StackStatus": "ROLLBACK_COMPLETE",
```
but works fine after calling delete-stack, when it's in state:
```txt
"StackStatus": "DELETE_COMPLETE",
```

**Comment by mgolladevops** [comment]
I am able to delete the stack using the Delete button and recreate the cluster even with same name without any issue
![delete](https://github.com/eksctl-io/eksctl/assets/156544812/f23974f8-ec2a-4325-94c2-aa821ef2b13a)
