### ISSUE TITLE
pre-release TODOs

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#14]
- [x] make install instructions simpler with `latest_release` floating tag
- [x] review `--help` for all subcommand
- [x] test against internal EKS endpoint (and fix any potential issues)
- [x] squash the history into sensible chunks
- [x] ~update AMI IDs for each of the GA regions~
- [x] ~re-create the private repo~
- [x] ~push to the new repo and check CircleCI works~
- [x] remove TODOs from the code
- [x] tag 0.1.0-alpha.1
- [x] open the repo to the public
- [x] enable github pages

**Comment by christopherhein** [comment]
I think we can call this done @errordeveloper agree?
