### ISSUE TITLE
Simplify `eksctl enable profile`

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#1416]
The functionality of this command is to install flux to set up gitops and to install the components of a quickstart profile on the cluster.

This two actions will be performed by `eksctl create cluster -f cluster-01.yaml` when #1415 is finished. After that is done, `eksctl enable profile` should just perform the second action: install quickstart components on the cluster by adding them to a gitops repo.

This way the command will be doing one thing instead of two different things. Another advantage is that it can allow applying multiple profiles to the same cluster in the future.

**Comment by stefanprodan** [comment]
I think `enable profile` should check if Flux is running and if it isn't, only then install it. 

How would users upgrade Flux and Helm Operator after installing them with eksctl? For minor releases `kubectl set image` should work but it's not gitopsy.

**Comment by marccarre** [comment]
@stefanprodan, new issue created to address this: https://github.com/weaveworks/eksctl/issues/1534
