### ISSUE TITLE
nodegroup-scoped SSH keys

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#144]
Right now we have cluster-wide SSH key. When we add nodegroup management, SSH access should be controlled on nodegroup basis.

**Comment by whereisaaron** [comment]
Sounds fine, though curious what the use case for this is?

**Comment by errordeveloper** [comment]
The idea is that you can create a cluster with nodegroups that have no SSH access, and nodegroups that don't. For example, you can use one without SSH to run something that has to be very secure.

**Comment by errordeveloper** [comment]
This is actually already implemented as of 0.1.16.
