### ISSUE TITLE
Proposal: support .eksctlignore file

### ISSUE THREAD

**Issue by chanwit** [weaveworks/eksctl#1444]
To make an EKS profile portable, it would be great for `eksctl` to ignore contents of a directory if  `.eksctlignore` exists inside it.

## User Stories

As a profle user,
I would like the profile to be portable across two kinds, EKS and Firekube, of clusters,
so that I can validate the behaviour of the applications with Firekube then EKS.

As a profile developer,
I would like to prevent some YAML files from being processed by EKSctl,
so that the profile could become portable across tools.

## Scenario

Dave is a profile developer.
He puts `.eksctlignore` into a directory, `metallb-system`, so this directory would be ignored when commannd: `eksctl enable profile` is issued.

Ursa is a profile user.
She enables the profile on Firekube, then `metallb-sytem` is applied.
Then she enables the profile with EKSctl, then `metallb-system` is correctly ignored.

**Comment by chanwit** [comment]
@stefanprodan could you please help review this proposal?
thank you

**Comment by stefanprodan** [comment]
Another use case would be excluding directories like .github, .circleci or files like travis.yaml.

**Comment by stefanprodan** [comment]
I’m in favor of this proposal as it helps filtering out unnecessary files from eksctl profiles and also makes the profiles portable to other platforms.
