### ISSUE TITLE
Use own private key with eksctl install flux 

### ISSUE THREAD

**Issue by cw-sakamoto** [weaveworks/eksctl#1448]
**Why do you want this feature?**
- We want to use own private key with `eksctl install flux`
  - To skip the step of registering the new key created by `eksctl install flux`

**What feature/behavior/change do you want?**
- We want the key specified in `git-private-ssh-key-path` to be secrets.

**Comment by marccarre** [comment]
@cw-sakamoto, do you mean you would like to re-use a pre-existing Kubernetes `Secret` containing your private SSH key? If so, it should just work w/o providing anything via `--git-private-ssh-key-path` as we already check for the existence of the Flux `Secret` here: https://github.com/weaveworks/eksctl/blob/2fe768da7cb91c5cde630c4ea1ef729038672954/pkg/gitops/flux/installer.go#L301-L313

Also, FYI, for various reasons, we've been thinking of removing `--git-private-ssh-key-path` and having instead the user flow described in #1533. Would this help in any way?

**Comment by cw-sakamoto** [comment]
@marccarre Thanks for your comment!
When I tried with 0.6.0, I felt that the secrets I created by [this document](https://github.com/fluxcd/flux/blob/master/docs/guides/provide-own-ssh-key.md) were deleted, but I might have misunderstood.
When I checked again with the latest 0.8.0, the secrets were not deleted and remained..😀

This ticket will be closed as we can use own private key in any way.

I think https://github.com/weaveworks/eksctl/issues/1533 is also very good! Operations can be easily understood if unified with the `eksctl` not `kubectl`

I execute the command as follows, even if there is secret(`flux-git-deploy`), a comment will appear to register the key. Can this be stopped if there is `flux-git-deploy`?

command:
```
EKSCTL_EXPERIMENTAL=true eksctl install flux \
--cluster=eks-test \
--region=ap-northeast-1 \
--git-url=git@github.com:.... \
--git-email=.... \
--with-helm=false
```

comment after execute eksctl:
```
[ℹ]  please configure git@.....git so that the following Flux SSH public key has write access to it
ssh-rsa AAAAB3NzaC1yc2EAAAADA....
```

**Comment by marccarre** [comment]
@cw-sakamoto, glad it is working for you now! 🙂👍 
For reference, the behaviour you needed was introduced in https://github.com/weaveworks/eksctl/pull/1225, in particular:

> Also note that the Secret for Flux's private SSH key isn't changed, in order to avoid the user having to reconfigure Flux access to their repository.
