### ISSUE TITLE
eksctl get clusters is not clear about cluster status

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#145]
I have a cluster that hasn't been created yet, it's called `floral-mushroom-1533218176`.

It appears in regular list:
```
> eksctl get clusters
NAME
beautiful-gopher-1528350240
floral-mushroom-1533218176
>
```

But trying to get more info returns nothing:
```
> eksctl get clusters floral-mushroom-1533218176
>
```

I think we should at status column, or always filter ready clusters, and provide a flag to show non-ready ones.

**Comment by richardcase** [comment]
The problem with `eksctl get clusters floral-mushroom-1533218176` returning nothing is there is a filter that ignores clusters that aren't ready:

https://github.com/weaveworks/eksctl/blob/111674bf4c08dcc3ab88f555566636300251c152/pkg/eks/eks.go#L144

There is a status column already in the results so we should be good to go with this,
