### ISSUE TITLE
Add support to IAM policy for listing route53 tags

### ISSUE THREAD

**Issue by jwalton** [weaveworks/eksctl#1450]
This is sort of in between a bug and a feature request.  :)

**Why do you want this feature?**

`external-dns` added a feature a little while ago [allowing you to filter hosted zones by tag](https://github.com/kubernetes-incubator/external-dns/pull/804).  This could let you, for example, tag a bunch of zones with "k8s=true", and then prevent external-dns from altering domains you don't want it to edit.

The problem is that currently the IAM policy added for exeternalDNS doesn't have sufficient permission to allow this:

```
time="2019-10-15T18:42:48Z" level=error msg="AccessDenied: User: arn:aws:sts::092288472643:assumed-role/eksctl-mycluster-nodegroup-NodeInstanceRole-164HQLAML58VU/i-02698a1359d0971a1 is not authorized to perform: route53:ListTagsForResource on resource: arn:aws:route53:::hostedzone/ZFA3A53P71R7M\n\tstatus code: 403, request id: 14d98538-1541-4c38-8bb8-becaa5cc5489"
```

**What feature/behavior/change do you want?**

I'd like to see permission for ListTagsForResource added to the `externalDNS` addon policy.

**Comment by sayboras** [comment]
+1
