### ISSUE TITLE
eksctl get clusters output is confusing when no clusters a present

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#146]
```
> eksctl get clusters
NAME
>
```

I think it should say "No clusters found" instead, which would be more like what `kubectl` does.

**Comment by richardcase** [comment]
I agree, good point. I'll make this change.

**Comment by richardcase** [comment]
@errordeveloper - do you think the printer (table printer in this case) should output the "No clusters found" or should this be done by the calling code?

I think probably the printer as if we are using the JSON or YAML printer we just return an empty array.

**Comment by errordeveloper** [comment]
Yes, sounds like it should be in the printer.
