### ISSUE TITLE
go-bindata generates sporadic diffs

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1461]
**What happened?**

Sporadic diffs have been observed, both when building locally, and in CI (e.g. [#5143](https://circleci.com/gh/weaveworks/eksctl/5143)), despite always using:
```console
$ go-bindata --version
go-bindata 3.11.0 (Go runtime go1.1x.y).
Copyright (c) 2010-2015, Jim Teeuwen.
Copyright (c) 2017-2018, Kevin Burke.
```

**What you expected to happen?**

No diff, since no file was changed, and the version of `go-bindata` didn't change either.

**How to reproduce it?**

Unclear how to reproduce it.
Rebasing on latest `master` seems to sometimes miraculously "fix" it.
Other people reported that re-applying each commit one-by-one on top of `master` also "fixed" it for them.

**Comment by errordeveloper** [comment]
You should be able to run all the steps using `weaveworks/eksctl-build:19ff80e010d2fdb7be3c44fc6491e13395a682ad`, and results ought to be the same, unless something else is broke (e.g. go-bindata does something that is actually non-deterministic).

**Comment by errordeveloper** [comment]
Right now we don't have an easy way to determine the image tag, not without reading `Makefile`. Perhaps it's something we could improve on that by providing `make print-docker-build-image-and-args` or something like that.
