### ISSUE TITLE
Update AWS VPC CNI plugin to 1.6.0

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#1473]
Now that `amazon-vpc-cni-k8s` has a [`release-1.6`](https://github.com/aws/amazon-vpc-cni-k8s/tree/release-1.6) branch and [RCs](https://github.com/aws/amazon-vpc-cni-k8s/tree/v1.6.0-rc5) are getting released, it may soon be time to upgrade `eksctl` to CNI 1.6.

**Comment by sayboras** [comment]
it's released today as per https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.0
