### ISSUE TITLE
Publish docs for RCs

### ISSUE THREAD

**Issue by gemagomez** [weaveworks/eksctl#1478]
When we publish an RC, we should be making an RC version of the docs for the people testing to be able to read the documentation.

**Comment by michaelbeaumont** [comment]
Master is being published at https://master--eksctl.netlify.app/

**Comment by michaelbeaumont** [comment]
Idea: Use the netlify API, which I presume exists in some form, to add the `release-*` branch to the built branches in netlify

**Comment by Himangini** [comment]
Closing this for lack of interest.
