### ISSUE TITLE
fully automate and streamline build stages

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#1485]
- [x] push build image to registry on commits to master (#1484, #1486, #1491)
- [ ] push app image to registry on commits to master
- [ ] push app image on release 
- [ ] update `.build_image_manistest` and CI configs on commits to master, push commits back to the repo
- [ ] get rid of "intermediate" image
- [ ] release script should only use pre-existing build image

**Comment by errordeveloper** [comment]
@marccarre @martina-if is any of this still applicable?

**Comment by martina-if** [comment]
Some things still make sense but I think we can close this since some are in other issues.
