### ISSUE TITLE
LinuxKit support

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#149]
Should be easy enough. We can pass CA cert and much of other parameters that kubelet needs as metadata. Ideally, we should publish AMIs from CI and generate Go package with constants for those. Users should be able to use '--node-os=linuxkit' (unless they really want a custom AMI).

cc @rn @ijc @justincormack

**Comment by justincormack** [comment]
Yeah that would be nice! Am going on holiday soon but can take a look in September...

**Comment by errordeveloper** [comment]
I think it may end-up pretty simple. The CI part could be a little more involved, as we haven't got AWS access setup there, but I don't think it has to be an absolute requirement for the first version.

**Comment by errordeveloper** [comment]
We have Ubuntu now, so adding another OS is even simpler now! 👍

**Comment by justincormack** [comment]
Excellent!

**Comment by errordeveloper** [comment]
@justincormack did you have a chance to look into this?

**Comment by justincormack** [comment]
Sorry, not yet...
