### ISSUE TITLE
Autoscaler IAM Role for Service Account example doesn't work

### ISSUE THREAD

**Issue by scottyhq** [weaveworks/eksctl#1492]
**What happened?**
These documented examples of using a iam roles for service accounts for the cluster autoscaler pod do not seem to work: 
https://github.com/weaveworks/eksctl/blob/master/examples/13-iamserviceaccounts.yaml#L28
https://eksctl.io/usage/iamserviceaccounts/

**What you expected to happen?**
It seems that the autoscaler only supports this functionality for kubernetes versions > 1.16, as described in detail https://github.com/kubernetes/autoscaler/issues/2335
`Failed to create AWS Manager: cannot autodiscover ASGs: AccessDenied: User: arn:aws:sts::00000000:assumed-role/ceng-eks-test-worker-node/30e721c9-ceng-eks-test-worker-node is not authorized to perform: autoscaling:DescribeTags`

**How to reproduce it?**
See above linked issue.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version 
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.7.0"}
$ kubectl version 
(pangeo-deploy) scott@Scotts-MacBook-Pro deploy-jhub % kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:07Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-e9b1d0", GitCommit:"e9b1d0551216e1e8ace5ee4ca50161df34325ec2", GitTreeState:"clean", BuildDate:"2019-09-21T08:33:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by whereisaaron** [comment]
Support is merged but not yet in a tagged release of the auto scaler. Will be soon. Look our for a 2.3.0 tag: https://github.com/kubernetes/autoscaler/issues/2301

**Comment by Jeffwan** [comment]
It has been supported and we have a release month ago. Please check here
https://github.com/kubernetes/autoscaler/issues/2335#issuecomment-553494215

**Comment by michaelbeaumont** [comment]
This should now be fixed with the appropriate version, closing. Let us know here if something's not right!
