### ISSUE TITLE
EKS Cluster tagging support

### ISSUE THREAD

**Issue by nickkadams** [weaveworks/eksctl#1494]
With the release of EKS Cluster tags from Amazon: https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-eks-supports-cluster-tagging/

it would be nice to have it added to eksctl for cost center and compliance tagging.

**Comment by nickkadams** [comment]
Apologies, after reading more closely from the link I posted:
```
Support for tagging clusters using CloudFormation and the eksctl command line tool is coming soon.
``` 
it appears to be on a roadmap already.

**Comment by whereisaaron** [comment]
Hi @nickkadams there is a [tracking issue](https://github.com/weaveworks/eksctl/issues/778) for this CloudFormation limitation/lag and others here: https://github.com/weaveworks/eksctl/issues/778

It is also [this item](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/200) on the CloudFormation team's road map: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/200

As is both common and perplexing, CloudFormation can lag API changes by a lot. For tags this can be a lag measure in years, such as [EIP tags](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/84), which come to the API in 2017, came to Terraform a couple weeks later in 2017, but still aren't supported by CloudFormation in 2019.

What's great is we have the CloudFormation road map now, so we know EIP tags are being worked on right now, but unfortunately EKS tags are not even in the road map yet.

**Comment by nickkadams** [comment]
Thanks @whereisaaron for the additional info.

**Comment by kalbir** [comment]
Should be closed by https://github.com/weaveworks/eksctl/pull/2156. Reopen if there is an issue.
