### ISSUE TITLE
Offer `utils describe-stacks` output in pure JSON

### ISSUE THREAD

**Issue by whereisaaron** [weaveworks/eksctl#1495]
**Why do you want this feature?**
I'd like to be able to use `describe stacks` output to check or extract the state of `eksctl` cluster.
Right now the output is a hybrid/mix of plain text logging and JSON and so can't be parsed as JSON without pre-processing. And if you have to do that you might as well use the `aws cli` directly instead. So right now, for me, the `utils` comment is not very useful. But if it did output JSON, it would be quite useful (to me). JSON output would also enable JSON diff to track changes to a cluster.

**What feature/behavior/change do you want?**
I would like this to work:
`eksctl utils describe-stacks --name=mycluster | jq <expression>`
or this:
`eksctl utils describe-stacks --name=mycluster --output json | jq`

I can work around this by describing the stacks with the `aws cli` so this is just a wish list item. Just to say I think this utility would be more useful with a pure JSON output option.

**Comment by xinbinhuang** [comment]
Same here. This feature is really helpful for me.

**Comment by neha-viswanathan** [comment]
Hi @martina-if I'd like to work on this issue.

**Comment by martina-if** [comment]
Hi @neha-viswanathan great that you want to contribute to eksctl! :D @michaelbeaumont and @cPu1 are the maintainers of eksctl and can help you with it :)

**Comment by michaelbeaumont** [comment]
@neha-viswanathan Thanks for your interest, you're very welcome to take on this issue!
