### ISSUE TITLE
Support fish on eksctl completion

### ISSUE THREAD

**Issue by gjmveloso** [weaveworks/eksctl#1496]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
`fish` is an interactive shell that is gaining popularity as it's easier to use than `bash` or even `zsh`. Command-line applications that pushes `man` pages got completions generated by default but this is not the case of `eksctl`

**What feature/behavior/change do you want?**
Having an option to generate `fish` completion by doing `eksctl completion fish`

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by af12066** [comment]
ref. https://github.com/spf13/cobra/pull/754

**Comment by sayboras** [comment]
ref. https://github.com/spf13/cobra/pull/1048
