### ISSUE TITLE
Add tags when creating a cluster

### ISSUE THREAD

**Issue by richardcase** [weaveworks/eksctl#150]
It would be good if we can specify tags (i.e. key/value pairs) when creating a cluster. 

Many companies use tags to help allocate costs between various teams and to drive other classification of services. For example, everything we deploy must have the following tags:

- environment

- owner

- product

- service

**Comment by jmcarp** [comment]
I was going to write up a patch for this, since we need tagging too, but it looks like there's a migration from aws-sdk-go to goformation in progress, so I figured I'd hold off. Does that make sense?

**Comment by richardcase** [comment]
@jmcarp - the goformation change has landed in master if you fancied working on this? It might be worth following the kops naming convention: 

`--cloud-labels string                  A list of KV pairs used to tag all instance groups in AWS (eg "Owner=John Doe,Team=Some Team").`

@errordeveloper - do you have any thoughts around tags on the created resources?

**Comment by errordeveloper** [comment]
As of #132, it should be fairly easy to plumb custom tags through, see here:

https://github.com/weaveworks/eksctl/blob/f7a04d411d44a62705b7f06ad13e4ce70163e823/pkg/cfn/manager/api.go#L40-L42

Also, did you folks see #25?

**Comment by richardcase** [comment]
I missed #25. So we could add tags for the CloudFormation stacks and then when the EKS API supports tags at that at a later date as a follow up issue?
