### ISSUE TITLE
Automate release notes

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1507]
**Why do you want this feature?**

Currently, release notes are hand-crafted, which isn't ideal, as it is easy to miss something in these. It would be easier if these were (at least partially) automated.

Related to #1451. (Automatically mentioning external contributors in release notes.)

**Possible solutions**

1. Improve the current release script to scan all PRs going out and generate the release notes. (These release notes could then either be published as-is, or manually edited/improved.)

**Relevant resources**

- https://hypothesis.works/articles/continuous-releases/

**Comment by martina-if** [comment]
Fixed via https://github.com/weaveworks/eksctl/pull/1799
