### ISSUE TITLE
Automate labeling of PRs with targeted version

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1508]
**Why do you want this feature?**

`eksctl`'s team recently decided to use GitHub labels to indicate in which version of `eksctl` PRs would be released to the world. However, as with any manual task, it is easy to forget and not be consistent. We should therefore find a way to enforce & automate this.

**Possible solutions**

1. Have some GitHub "plugin" preventing us from merging until we add a version label?
2. Have the release scripts look at all PRs going out, and labeling them at the time of the release?

Feel free to suggest more below! 🙂 

**See also**:

- #1507 (Automate release notes.)

**Comment by michaelbeaumont** [comment]
Closing this for now as the labels have little remaining relevance.
