### ISSUE TITLE
zsh shell completion not working

### ISSUE THREAD

**Issue by andreamaruccia** [weaveworks/eksctl#1513]
**What happened?**

I am trying to use zsh shell completion like described in the documentation but somehow it does not work

**What you expected to happen?**
I expected that I could write eksctl and use tab in the terminal

**How to reproduce it?**

Here is what I tried so far:
Ran this
```bash
mkdir -p ~/.zsh/completion/
eksctl completion zsh > ~/.zsh/completion/_eksctl
```
then I put this in my .zshrc file
```bash
# eksctl
fpath=($fpath ~/.zsh/completion)
```
I already had this in the .zshrc file:
```bash
autoload -U compinit
compinit
```

**Anything else we need to know?**
I'm using macos 10.14.6 (18G87), installed eksctl with brew and using aws credentials trough profiles and aws config

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.7.0"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
no applicable

**Comment by andreamaruccia** [comment]
Seems that it works with the following version 0.11.1

**Comment by ryedin** [comment]
Same problem (zsh completion just simply doesn't work)

eksctl version
`[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.13.0"}`

This ticket should be re-opened

**Comment by cajual** [comment]
@ryedin not sure if this is still an issue for you but I was having the same issue until I made a minor change:

From terminal

`$ mkdir ~/.oh-my-zsh/completions`
`$ mv ~/.zsh/completion/_eksctl ~/.oh-my-zsh/completions/`

Then `vim ~/.zshrc` and modify the `fpath`:

`fpath=($fpath ~/.oh-my-zsh/completions)`
`:wq`

`$ source ~/.zshrc`

Auto-completions should work.
