### ISSUE TITLE
Shared Security Group is created even when manually provided

### ISSUE THREAD

**Issue by morsok** [weaveworks/eksctl#1531]
**What happened?**
When creating a cluster using a config file and manually providing security groups for nodegroups, eksctl still create a shared security group. This group however is not used (the manually provided one is correctly linked to the ec2 instances), so this is **not** breaking things.

Config used : 

```
    securityGroups:
      withShared: false
      withLocal: false
      attachIDs: ["sg-1111111", "sg-2222222"]
```

**What you expected to happen?**
No extra security group is created

**How to reproduce it?**
Create a cluster with a configuration file, disable shared and local security groups in the nodegroup config and provide already created security groups ids.

**Anything else we need to know?**

N/A

**Versions**
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.8.0"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
No logs related to the issue

**Comment by billchen8888** [comment]
Any update ?   I ran into the same issue -  the account/role I signed in is not allowed to create any new security group, so we are required to use existing security group for EKS - but somehow eksctl still tries to create new security group and it fails due to the permission.

**Comment by bgdnlp** [comment]
Please note that, while there aren't many people affected by this, for those that are affected (mostly enterprise) it can be a real pain or even a showstopper. It affects automation, updates, compliance and can even make eksctl unusable in certain environments. Being able to use pre-created security groups works, as long as eksctl respects that and doesn't try to be too smart about it.

**Comment by michaelbeaumont** [comment]
@bgdnlp Does setting the option `vpc.sharedNodeSecurityGroup` to a pre-created SG solve the issue?

**Comment by michaelbeaumont** [comment]
@morsok @billchen8888 Does either of you have the opportunity to test this?

**Comment by bgdnlp** [comment]
Setting `vpc.sharedNodeSecurityGroup` to an existing group doesn't create a new security group in eksctl 0.23.0.

That said, I believe the expectation is that if all node groups have `withShared: False` set, eksctl wouldn't create a security groups since it has no reason to. Not sure what it should do when changing a cluster that did have a shared SG. Deleting it prematurely might cause issues.

**Comment by michaelbeaumont** [comment]
@bgdnlp Closing this issue for the above.
