### ISSUE TITLE
Providing the Git private SSH key via its filepath is not GitOps friendly

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1533]
**Problem**

Currently, we accept `--git-private-ssh-key-path` and will soon have the equivalent in `ClusterConfig`. However, this will not work well with a cluster-level GitOps approach, as the file path only is meaningful for the local machine. 

**Solution**

Instead, we should refer a key in a Kubernetes `Secret` or in AWS, e.g.:

1. register the SSH key in AWS:
    ```console
    eksctl create keypair $keyName --from-file /path/to/private/ssh/key/file/id_rsa
    ```
2. run `eksctl enable repo` the following way:
    ```console
    eksctl enable repo --git-private-ssh-key-name $keyName
    ```
    or
    ```console
    eksctl enable repo -f /path/to/clusterconfig.yaml
    ```
    having `$keyName` present in there.

See also #1211, #1273

**Comment by Callisto13** [comment]
Closing due to https://github.com/weaveworks/eksctl/issues/2963
