### ISSUE TITLE
Eksctl overrides tag on VPC and subnets

### ISSUE THREAD

**Issue by morsok** [weaveworks/eksctl#1535]
**What happened?**
When creating a cluster within existing VPC and subnets (everything but cluster and nodegroups is managed with Terraform), eksctl changed the `kubernetes.io/cluster/clustername` tag value from `owned` to `shared`, causing a diff for the Terraform configuration.

**What you expected to happen?**
The tag of the VPC and subnets should not have changed

**How to reproduce it?**
Create a cluster when providing custom VPC and subnets

**Anything else we need to know?**

N/A

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.8.0"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
No logs related to the issue

**Comment by sekka1** [comment]
@morsok Are you creating the subnets with Terraform because eksctl doesnt have a way for you to point eksctl to a VPC and give eksctl the CIDRs you want for it to create it itself?

**Comment by michaelbeaumont** [comment]
Please comment here if this is still an issue!
