### ISSUE TITLE
incorrect usage of k8s.io/kubernetes

### ISSUE THREAD

**Issue by carnott-snap** [weaveworks/eksctl#1537]
**What happened?**
When importing `eksctl` as a library, I pull in `k8s.io/kubernetes` as a transitive dependency.

I would like to use the `k8s.io/kubernetes/pkg/cloudprovider/providers/aws` package version that is compatible with the other `kubernetes-1.12.6` libraries that I am importing. I am aware that we should not import `k8s.io/kubernetes` directly, per kubernetes/kubernetes#81878. I looked in [kubernetes/cloud-providers-aws](https://github.com/kubernetes/cloud-provider-aws), however I do not see any `kubernetes-1.12.6` tag and the code was removed at kubernetes/cloud-provider-aws@b377713a2f1de9d744a6f706b77b9d16f72012ed.

**What you expected to happen?**
Customers should not import `k8s.io/kubernetes` directly, see kubernetes/kubernetes#81878, and instead using component modules: `k8s.io/cloud-provider` and `k8s.io/cloud-provider-aws`.

**Anything else we need to know?**
I would have submitted this as a PR, since the `k8s.io/cloud-provider` fix is just a `find -exec sed`, unfortunately I am unclear what the best candidate for replacing `k8s.io/kubernetes/pkg/cloudprovider/providers/aws` is. [kubernetes/cloud-providers-aws](https://github.com/kubernetes/cloud-provider-aws) does not have any tags, let alone `kubernetes-1.12.6`, and the related logic was removed: kubernetes/cloud-provider-aws@b377713a2f1de9d744a6f706b77b9d16f72012ed. As such, I have created an upstream ticket to track the need: kubernetes/kubernetes#85022.

**Comment by michaelbeaumont** [comment]
Duplicate of https://github.com/weaveworks/eksctl/issues/813
