### ISSUE TITLE
Project structures

### ISSUE THREAD

**Issue by holidaycottages** [weaveworks/eksctl#1539]
What is the best way to set up my git repos when dealing with multiple deployments / micro services and one cluster?

So if I had 12 micro services in one cluster, but 12 separate git repos, how can I leverage gitops and things like flagger to automate the deployments? 

Would it be that on merge to master on a micro service it would update the repo for the deployment for that service?

**Comment by michaelbeaumont** [comment]
Hi @holidaycottages these are good questions but definitely specific to `flux` and `flagger`. Feel free to ask at [weave-community#flux](https://weave-community.slack.com/messages/flux) and [weave-community#flagger](https://weave-community.slack.com/messages/flagger). I'm going to close this issue! Thanks.
