### ISSUE TITLE
review how we list and delete clusters

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#154]
This would be good to do after #132 lands.

Right now we very optimistically let you run `eksctl delete <anything>`, and say that we will delete that (even if it doesn't exist). But the output is wrong, in fact we are very strict about what we actually delete. Also, when we actually do delete a cluster, we block on nodegroup, but don't block on control plane (because it would take very long and user shouldn't have to wait most of the time).

While with `eksctl get clusters`, we currenly list any cluster, even if it wasn't created by us. We should probably list only clusters that we have created via CloudFormation, but offer a flag to list all the clusters also, i.e. ones created by non-CloudFormation version of eksctl. It's debatable whether this flag may need to be on by default for backwards-compatibility, or we could just print a warning or something...

**Comment by kschumy** [comment]
@errordeveloper -- I would like to work on this feature. Can you assign this to me?

**Comment by errordeveloper** [comment]
Yes, happy to adding it to you, Kristen. However, I wouldn't advise
starting on this before #132 lands. Have you looked at any of the issues
with 'help wanted' label? Some of those don't have dependencies, and are
relatively easy to tackle.

**Comment by errordeveloper** [comment]
https://github.com/weaveworks/eksctl/invitations
