### ISSUE TITLE
Synchronise Flux after enabling a quickstart profile

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1543]
**Why do you want this feature?**

Once an EKS cluster is enabled for GitOps (via running `eksctl enable repo`), and Flux is running there, when a "quickstart" profile is enabled, given Flux synchronises with the Git repository every 5 minutes, users have to wait an average of 2.5 minutes before the components of the profile actually get installed by Flux. This isn't ideal as people may expect to see a change in their clusters immediately after running the `eksctl enable profile` command.

**What feature/behavior/change do you want?**

Various alternatives are possible (or a combination of these):

1. Add a log statement at the end of the execution of the command about the fact changes may not be visible immediately.
2. Add a log statement at the end of the execution of the command  asking users to run `fluxctl sync --k8s-fwd-ns ${FLUX_NS}` s.t. `FLUX_NS` is the Kubernetes namespaces where Flux is running.
3. Check if `fluxctl` is present in `${PATH}`, and if so check where Flux is running (either by scanning the cluster, or, once supported via #1415, by getting this information from `ClusterConfig`), and then having `eksctl` run the aforementioned command itself.
4. ~Add `fluxctl` as a dependency of `eksctl` (via `brew`, by packaging it inside the `eksctl` binary, etc.) and then having `eksctl` run the aforementioned command itself.~ (Adding a dependency isn't necessarily ideal.)
5. Port-forward into Flux and call the Flux API to synchronise with the Git repository, as done [here](https://github.com/fluxcd/flux/blob/master/cmd/fluxctl/sync_cmd.go#L58).

**Comment by michaelbeaumont** [comment]
Good to solve as part of #2964
