### ISSUE TITLE
Update AWS VPC CNI Plugin to 1.5.3 (latest default)

### ISSUE THREAD

**Issue by rndstr** [weaveworks/eksctl#1549]
The command `eksctl utils update-aws-node` applies the asset https://github.com/weaveworks/eksctl/blob/master/pkg/addons/default/assets/aws-node.yaml which is pointing to `amazon-k8s-cni:v1.5.0` currently

The latest cni points to [v1.5.3](https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html) and the asset should reflect that.

There has been a previous attempt at upgrading to `v1.5.4` #1376 which must have been reverted.

**Comment by mogren** [comment]
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.5.5 is out.

**Comment by rndstr** [comment]
@mogren should we use the latest version that is out (1.5.5) or the current recommended (1.5.3)?

**Comment by mogren** [comment]
We have not yet made v1.5.5 the default for new EKS clusters, but I can open a new issue once we do that. v1.5.3 is fine for now. Thanks!

**Comment by rndstr** [comment]
The manifest https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.5/config/v1.5/aws-k8s-cni.yaml now points to 1.5.5 (but the documentation still mentions 1.5.3 as recommended).
