### ISSUE TITLE
cluster verification

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#155]
It'd be neat to have some form of verification. This could come especially useful for troubleshooting in general, but also when user supplies any customisation (e.g. #69). This could also incorporate whatever we do in #151.

**Comment by errordeveloper** [comment]
Kops has some kind of verification functionality, we should look into what it does.

**Comment by errordeveloper** [comment]
I think comes helpful in the context of upgrades, and as more general form of some of the same concerns that #539 is meant to address.

**Comment by kalbir** [comment]
Closing as #587 better covers the problem IMO (and this is referenced there).
