### ISSUE TITLE
Assign multiple security groups to the EKS Cluster API

### ISSUE THREAD

**Issue by jitran** [weaveworks/eksctl#1551]
**Why do you want this feature?**
Currently without specifying any cluster security groups in the config yml, eksctl will create a security group named eksctl-\<cluster-name\>-cluster/ControlPlaneSecurityGroup that allows ingress from the worker nodes. 

We are using EKS in private mode and would like to grant our bastion host access to the private api. To get around the current limitation, we're adding an additional ingress rule to the ControlPlanSecurityGroup.

**What feature/behavior/change do you want?**
Would it be possible to extend the vpc::securityGroup config to take a list of security group ids? The nodeGroups config supports this.

**Comment by michaelbeaumont** [comment]
Duplicate of https://github.com/weaveworks/eksctl/issues/1805 (it has more activity & history)
