### ISSUE TITLE
Allow Cluster Endpoint API to be overriden

### ISSUE THREAD

**Issue by jitran** [weaveworks/eksctl#1552]
**Why do you want this feature?**
We are using EKS in private mode and access to it is via a bastion host. Our bastion host is locked down so we're tunnelling the eks-cluster-api endpoint on port 443 to our local machine on 127.0.0.1:8001.

Subsequently, we've configured our kube config file to access the api endpoint on port 8001, mapped eks-cluster-api to 127.0.0.1 in the hosts file, and kubectl is working fine.

However, eksctl for operations such as `eksctl update cluster` or `eksctl delete nodegroup` does not read the api endpoint and port number from kube config. It appears to extract it from the cluster's cloudformation stack's Endpoint output value. The value itself is https://eks-cluster-api-endpoint and assumes the default port 443. This in turn causes eksctl operations to fail as the endpoint is not available locally on port 443.

**What feature/behavior/change do you want?**
Allow the user to specify `--endpoint <custom-eks-cluster-api-endpoint>` or some other means to override the default behaviour.

Thank you

**Comment by martina-if** [comment]
closed via #1746

**Comment by asthasr** [comment]
This needs to be re-opened. There's currently no way to handle a bastion host serving as a "tunnel" to a private endpoint, as PR #1746 was reverted. Ideally this should not impact _any_ state of the cluster, as it's entirely client side.

**Comment by asthasr** [comment]
Okay, it looks like a SOCKS5 proxy can be used to overcome this issue. Go's HTTP client seemingly respects it inherently.

```
AWS_PROFILE=sts-qa \
HTTP_PROXY="socks5://127.0.0.1:4141" \
eksctl create cluster -f qa.yaml
```

After the cluster has been created, and a ingress rule added to the cluster's security group, `kubectl` can then be used similarly--although the name of the environment variable is different!

```
HTTPS_PROXY="socks5://127.0.0.1:4141" \
kubectl get nodes
```

**Comment by michaelbeaumont** [comment]
@asthasr Nice solution, thanks!
