### ISSUE TITLE
Upgrade CNI plugin to version 1.5.5

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#1553]
When we [reverted the upgrade to 1.5.4] (https://github.com/weaveworks/eksctl/pull/1423) we went back to version 1.5.0. We should use 1.5.5 now that it is released

_Originally posted by @jicowan in https://github.com/weaveworks/eksctl/pull/945#issuecomment-552612797_

**Comment by jicowan** [comment]
@martina-if thanks. Prior to you fixing this, would upgrading the cluster control plane from 1.11 to 1.12 with eksctl replace/overwrite the aws-node daemonset?  eksctl should only modify the aws-node daemonset when customers specifically want to upgrade that component.

**Comment by martina-if** [comment]
@jicowan As far as I remember, upgrading the control plane with `eksctl update cluster` shouldn't touch the aws-node. See this documentation https://eksctl.io/usage/cluster-upgrades/

**Comment by jicowan** [comment]
OK @martina-if.  I spoke to a customer recently who said their aws-node daemonset was downgraded from 1.5.3 to 1.5.0 when they upgraded their cluster from 1.11 to 1.12 with eksctl.  I have not had time to test it myself.

**Comment by rndstr** [comment]
duplicate of #1549

**Comment by marccarre** [comment]
@martina-if any reason this got re-opened? 🙂

**Comment by martina-if** [comment]
No, I don't remember reopening it :/ thanks!
