### ISSUE TITLE
AWS::EKS::Cluster/ControlPlane: CREATE_FAILED – "Subnet Id is required (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; ....

### ISSUE THREAD

**Issue by itbalan** [weaveworks/eksctl#1564]
Hello,

I am getting the below error when I create eks cluster - config spec is also given for quick reference, appreciate quick help!

AWS::EKS::Cluster/ControlPlane: CREATE_FAILED – "Subnet Id is required (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; ....

cluster-spec.yaml
-------------------
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: first-eks-cluster
  region: ap-southeast-1
vpc:
  id: "vpc-id"
  cidr: "#.#.#.#/24"
  subnets:
    Private:
      ap-southeast-1a:
          id: "subnet-######"
          cidr: "#.#.#.#/27"
      ap-southeast-1b:
          id: "subnet-######"
          cidr: "#.#.#.#/27"
    Public:
      ap-southeast-1a:
          id: "subnet-###########"
          cidr: "#######/28"
      ap-southeast-1b:
          id: "subnet-#########"
          cidr: "#.#.#.#/28"
iam:
  serviceRoleARN: "arn:aws:iam::<accountID>:role/<rolename>"

nodeGroups:
  - name: standard-workers

    instanceType: t3.medium
    desiredCapacity: 3
    iam:
      #instanceProfileARN: "arn:aws:iam::11111:instance-profile/eks-nodes-base-role"
      instanceRoleARN: "arn:aws:iam::<accountID>:role/<nodeinstance-role>"
    privateNetworking: false
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: [sg-######,sg-######,sg-#####,sg-######3]
    ssh:
      publicKeyName: 'sample-key'
    #tags:
      #'environment:basedomain': 'example.org'

**Comment by itbalan** [comment]
It is resolved after I remove vpc id and cidr.

**Comment by vishwas-mr** [comment]
@itbalan 
According to my attempt, if VPC ID and CIDR are removed, eksctl will create new subnets and not use the existing ones. Did you also face the same issue?

**Comment by jcleira** [comment]
maybe:

```
Private:
```

was causing the issue
