### ISSUE TITLE
Tags in managed node groups

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/eksctl#1571]
```
Tags (managedNodeGroups[*].tags) in managed nodegroups apply to the EKS Nodegroup resource and do not propagate to the provisioned Autoscaling Group like in unmanaged nodegroups.
```

Does this mean that tags will not get applied to instances and that the cluster autoscaler will not work?

**Comment by whereisaaron** [comment]
There is supposedly built-in support for cluster-autoscaler tags. This will only work if AWS automatically tags the ASG for the node group taints and labels, without then you can't scale from zero.

https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html
>Amazon EKS tags managed node group resources so that they are configured to use the Kubernetes Cluster Autoscaler.
>
>Important
>If you are running a stateful application across multiple Availability Zones that is backed by Amazon EBS volumes and using the Kubernetes Cluster Autoscaler, you should configure multiple node groups, each scoped to a single Availability Zone. In addition, you should enable the --balance-similar-node-groups feature.

**Comment by johnpetersjr** [comment]
I have experienced that when setting tags on a NodeGroup, the tags will propagate to the ASG and to the EC2 instances.

When settings tags on a managedNodeGroup, the tags do NOT propagate down to the ASG or EC2.

**Comment by sashasimkin** [comment]
Is there a way to tag corresponding ASGs and instances?

**Comment by galindro** [comment]
According to https://docs.aws.amazon.com/eks/latest/userguide/eks-using-tags.html, Amazon EKS *managed* node groups *do not* supports tag propagation yet. Currently, we would need to do some code to find the associated ASGs and tag them

**Comment by TBBle** [comment]
https://github.com/aws/containers-roadmap/issues/608 is the AWS containers roadmap issue tracking this feature.

**Comment by TBBle** [comment]
For Cluster Autoscaler specifically, the EC2 instances and Auto Scaling Groups created for Managed NodeGroups _are_ tagged with the expected labels:
```
k8s.io/cluster-autoscaler/enabled:true
k8s.io/cluster-autoscaler/<clustername>: owned
```

**Comment by TBBle** [comment]
It seems the recommended way to apply tags to EC2 instances in EKS Managed Node Groups is [using Launch Templates](https://github.com/aws/containers-roadmap/issues/608#issuecomment-675101463), which [eksctl supports](https://eksctl.io/usage/launch-template-support/). Is that sufficient to fulfill this feature request?

Cluster Autoscaler doesn't depend on tags on the EC2 instances, it depends on tags on the ASG, which are still unable to be customised per https://github.com/aws/containers-roadmap/issues/608.

**Comment by michaelbeaumont** [comment]
Seems like we could just set the tags on the launch template, since `eksctl` always uses launch template

**Comment by aclevername** [comment]
The `managedNodeGroups[*].tags` field already gets added to the launch template spec:
https://github.com/weaveworks/eksctl/blob/da899ad2176936d1045dc365ea3bba44647858c1/pkg/cfn/builder/managed_launch_template.go#L145-L164

This adds the tag to all EC2 instances. You still cannot add tags to the ASG https://github.com/aws/containers-roadmap/issues/608#issuecomment-675101463

**Comment by aclevername** [comment]
I'm going to close this issue as the original intent of this was to be able to tag the EC2 instances, which you can.



> It seems the recommended way to apply tags to EC2 instances in EKS Managed Node Groups is [using Launch Templates](https://github.com/aws/containers-roadmap/issues/608#issuecomment-675101463), which [eksctl supports](https://eksctl.io/usage/launch-template-support/). Is that sufficient to fulfill this feature request?
> 
> Cluster Autoscaler doesn't depend on tags on the EC2 instances, it depends on tags on the ASG, which are still unable to be customised per [aws/containers-roadmap#608](https://github.com/aws/containers-roadmap/issues/608).

I think if/when EKS add support for tagging the autoscaler it will likely be a no-op from our end, as we are already tagging the nodegroup and launch template, so its likely that if it was ever implemented the ASG would inherit the tags from one of those two.

**Comment by afirth** [comment]
@aclevername Without this change, cluster-autoscaler scale up from 0 ([eksctl docs](https://eksctl.io/usage/autoscaling/#scaling-up-from-0)) doesn't work with managed node groups.
Is it that eksctl can't implement this, or doesn't prioritize? If the latter, are you open to community contributions?
Either way, I'd like to reopen this for either a docs update to make it clear that it only works with unmanaged node groups, or a fix. The upstream issue is at 500 votes and still in "researching" - unlikely to be implemented I guess

**Comment by aclevername** [comment]
> @are you open to community contributions? 

absolutely!

> Either way, I'd like to reopen this for either a docs update to make it clear that it only works with unmanaged node groups, or a fix. The upstream issue is at 500 votes and still in "researching" - unlikely to be implemented I guess

:+1:

**Comment by Himangini** [comment]
@aclevername isn't this related to what @Skarlso is working on here https://github.com/weaveworks/eksctl/issues/4853 🤔  maybe I am missing something. 

@afirth thanks for your comments, we are happy to accept PRs if you have a fix in mind 🙌🏻 🎉

**Comment by afirth** [comment]
#5002 is open for review to fix this.
@cPu1 the problem with that is that cluster autoscaler is looking at the ASG tags

**Comment by afirth** [comment]
I think #5002 didn't link in a way to autoclose, but this is implemented there and should be closed?

**Comment by Skarlso** [comment]
Yep. Thanks! :)
