### ISSUE TITLE
Attribute: ClusterSecurityGroupId was not found for resource AWS::EKS::Cluster

### ISSUE THREAD

**Issue by treacher** [weaveworks/eksctl#1574]
**What happened?**
- I upgraded EKSCTL 0.9.0 -> 0.10.0
- Ran the following command: `eksctl update cluster -f <REDACTED> --approve`
- Then I observed the following error message:
```
 UPDATE_ROLLBACK_IN_PROGRESS – "Attribute: ClusterSecurityGroupId was not found for resource: <Redacted>" <- The resource here is AWS::EKS::Cluster
```

**What you expected to happen?**
I had expected the cluster upgrade to complete successfully.

**How to reproduce it?**
- Upgrade to EKSCTL 0.9.0 -> 0.10.0
- Run the following command: `eksctl update cluster -f <cluster-name> --approve`

**Anything else we need to know?**
MacOS Majave
Downloaded the binary through Homebrew

**Versions**
```
$ eksctl version - version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.10.0"}
$ kubectl version - version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:50:59Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
```

**Logs**
```
019-11-19 09:13:05 UTC+1100    eksctl-eks-sandpit-cluster    UPDATE_ROLLBACK_COMPLETE    -
2019-11-19 09:13:04 UTC+1100    eksctl-eks-sandpit-cluster    UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS    -
2019-11-19 09:12:51 UTC+1100    eksctl-eks-sandpit-cluster    UPDATE_ROLLBACK_IN_PROGRESS    Attribute: ClusterSecurityGroupId was not found for resource: eks-sandpit
2019-11-19 09:12:47 UTC+1100    eksctl-eks-sandpit-cluster    UPDATE_IN_PROGRESS    User Initiated
```

**Hypothesis**
This may be a bug as I don't think the attribute `ClusterSecurityGroupId` exists for https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html.
I believe this issue may be coming from the following line of code: https://github.com/weaveworks/eksctl/blob/d80a1f60fd39ea5aa49b323f516cec5302774599/pkg/cfn/builder/cluster.go#L130

**Comment by cPu1** [comment]
@treacher It appears that you ran `eksctl update cluster` on a cluster that was created with a prior version of eksctl. Can you confirm this?
We are working on this and should have a fix soon. For context, eksctl uses the `ClusterSecurityGroupId` to enable communication between both managed and unmanaged nodegroups. This field, however, was recently added to AWS EKS and the `update` command in eksctl wasn't amended to ignore it for older/existing clusters in the `0.10.1` release. 
Also, until a new version is released, the recommended version for now is `0.10.1`.

Meanwhile, to confirm, could you run `aws eks describe-cluster` on your cluster and verify that the `platformVersion` is below `eks.3`? (it's likely to be `eks.1` but it also depends on when the cluster was created)

**Comment by treacher** [comment]
Hello @cPu1 

Yes that's correct, I ran the update on an existing cluster.

Thanks for the context, I can confirm that the platformVersion is eks.1

**Comment by cPu1** [comment]
@treacher this has been fixed in https://github.com/weaveworks/eksctl/releases/tag/0.10.2
