### ISSUE TITLE
eksctl should associate exactly 1 security group having kubernetes.io/cluster tag with Nodes

### ISSUE THREAD

**Issue by rtripat** [weaveworks/eksctl#1581]
**What happened?**
Starting eksctl 0.10.0 and higher, eksctl is associating two security groups with the ` kubernetes.io/cluster/$CLUSTER_NAME` tag key to EC2 instances. This results in LoadBalancer services failing to launch with error similar to the one below

```
$ eksctl create cluster --name=eksworkshop-eksctl-unmanaged --nodes=3 --alb-ingress-access

$ aws eks describe-cluster --name eksworkshop-eksctl-unmanaged --query 'cluster.[platformVersion,version]' 
[
    "eks.3",
    "1.14"
]

$ k get nodes
NAME                                           STATUS   ROLES    AGE   VERSION
ip-192-168-3-116.us-west-2.compute.internal    Ready    <none>   16m   v1.14.7-eks-1861c5
ip-192-168-55-142.us-west-2.compute.internal   Ready    <none>   16m   v1.14.7-eks-1861c5
ip-192-168-66-144.us-west-2.compute.internal   Ready    <none>   16m   v1.14.7-eks-1861c5

$ aws ec2 describe-instances --filters Name=private-dns-name,Values=ip-192-168-3-116.us-west-2.compute.internal --query 'Reservations[*].Instances[*].[SecurityGroups]' --output text
sg-040c1508847c1bc69	eksctl-eksworkshop-eksctl-unmanaged-nodegroup-ng-08b217d0-SG-1W88EBXXP7DY9
sg-02e5792d2a2b628a9	eksctl-eksworkshop-eksctl-unmanaged-cluster-ClusterSharedNodeSecurityGroup-47J7MCHQUO89
sg-0a1244396e483e71f	eks-cluster-sg-eksworkshop-eksctl-unmanaged-94484000

$ k describe service frontend
Name:                     frontend
Namespace:                default
Labels:                   app=guestbook
                          tier=frontend
Annotations:              kubectl.kubernetes.io/last-applied-configuration:
                            {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"guestbook","tier":"frontend"},"name":"frontend","namespa...
Selector:                 app=guestbook,tier=frontend
Type:                     LoadBalancer
IP:                       10.100.237.199
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  30237/TCP
Endpoints:                192.168.22.236:80,192.168.33.168:80,192.168.68.210:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                      Age                From                Message
  ----     ------                      ----               ----                -------
  Warning  CreatingLoadBalancerFailed  14m (x2 over 15m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/frontend: Multiple tagged security groups found for instance i-014dcc4c45f31bb8b; ensure only the k8s security group is tagged; the tagged groups were sg-040c1508847c1bc69(eksctl-eksworkshop-eksctl-unmanaged-nodegroup-ng-08b217d0-SG-1W88EBXXP7DY9) sg-0a1244396e483e71f(eks-cluster-sg-eksworkshop-eksctl-unmanaged-94484000)
  Normal   EnsuringLoadBalancer        27s (x9 over 15m)  service-controller  Ensuring load balancer
  Warning  CreatingLoadBalancerFailed  26s (x7 over 15m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/frontend: Multiple tagged security groups found for instance i-078685366f4a65c20; ensure only the k8s security group is tagged; the tagged groups were sg-040c1508847c1bc69(eksctl-eksworkshop-eksctl-unmanaged-nodegroup-ng-08b217d0-SG-1W88EBXXP7DY9) sg-0a1244396e483e71f(eks-cluster-sg-eksworkshop-eksctl-unmanaged-94484000)
```

**What you expected to happen?**
Starting with EKS cluster version 1.14 and platform version eks.3, EKS API creates a `clusterSecurityGroup` which has the `kubernetes.io/cluster/$CLUSTER_NAME` tag. For such clusters, eksctl doesn't need to create and attach additional security group to the nodes

**How to reproduce it?**
1. Create a cluster with unmanaged nodes
2. Follow [instructions](https://docs.aws.amazon.com/eks/latest/userguide/eks-guestbook.html) here to deploy guestbook service
3. `kubectl describe service frontend`

**Anything else we need to know?**
Darwin

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.10.1"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by cPu1** [comment]
As I understand it, the `LoadBalancer` bug is a high-priority issue that needs to be resolved soon, so my main intent is to not diverge too much from what eksctl does for unmanaged nodes today without first thinking about all use-cases, which will require more time.

Instead of attaching the EKS default cluster security group ID (which has the cluster tags) to unmanaged nodes and removing the part where we attach our own security groups (one of which also has cluster tags), we'll:
1. Add an ingress rule to the shared node security group (that we currently create) for unmanaged nodes to allow traffic from the cluster default security group.
2. Add an ingress rule to the default cluster security group ID to allow traffic from the shared security group (that we create). I'm aware this will mutate a security group that's managed by EKS, but I've confirmed that EKS is able to delete the cluster even when the default SG is modified by adding an ingress rule.


For context, the main rationale behind adding the default cluster SG to unmanaged nodes was to allow communication between managed and unmanaged nodes, since managed nodes do not support attaching a custom SG.

**Comment by cPu1** [comment]
This has been fixed in https://github.com/weaveworks/eksctl/releases/tag/0.10.2

**Comment by joshkurz** [comment]
running into this on a nodegroup created with 0.13.0. Was this reintroduced somewhere? Every nodegroup that I create creates a new sg and tags it as owned which causes k8s to not allow LBs to get created.

**Comment by joshkurz** [comment]
my issue is on spot instances however, not just regular unmanaged nodes. Any chance that could have something to do with it? Unmanaged, non spot, nodes do work for me.
