### ISSUE TITLE
Typo: kubectl not found, v1.10.0 or newever is required

### ISSUE THREAD

**Issue by clareliguori** [weaveworks/eksctl#1599]
**What happened?**

```
$ eksctl create cluster
<snip>
[✖]  kubectl not found, v1.10.0 or newever is required
[ℹ]  cluster should be functional despite missing (or misconfigured) client binaries
[✔]  EKS cluster "fabulous-painting-1574463322" in "us-west-2" region is ready
```

**What you expected to happen?**
Typo: "newever" should "newer"

https://github.com/weaveworks/eksctl/blob/079c5b71ee90b9fcfa6d4c10f07e81a2c8fc0ac0/pkg/utils/kubectl.go#L30

**How to reproduce it?**
Don't have kubectl installed

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.10.2"}
```

**Comment by siri-ea** [comment]
Hi I have the same issue. After installing eksctl by following aws documentation, i see eksctl version as follows : [ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.10.2"}

**Comment by siri-ea** [comment]
ec2-user]# eksctl create cluster
[ℹ]  eksctl version 0.10.2
[ℹ]  using region us-east-2
[✖]  checking AWS STS access – cannot get role ARN for current session: RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: proxyconnect tcp: EOF

**Comment by yuyasugano** [comment]
This is the same for me. I ran this commend. eksctl create cluster --name demo-newsblog --region eu-west-1 --fargate

[?]  kubectl not found, v1.10.0 or newever is required
[?]  cluster should be functional despite missing (or misconfigured) client binaries
[?]  EKS cluster "demo-newsblog" in "ap-northeast-1" region is ready

I was trying to do this news blog for EKS on Fargate.
https://aws.amazon.com/jp/blogs/aws/amazon-eks-on-aws-fargate-now-generally-available/
