### ISSUE TITLE
Can we get rid of emojis/symbols in eksctl's logging, please?

### ISSUE THREAD

**Issue by eightlimbed** [weaveworks/eksctl#1601]
**Why do you want this feature?**
When my teammates send me error messages on slack it looks like this
<img width="913" alt="Screen Shot 2019-11-23 at 4 15 29 PM" src="https://user-images.githubusercontent.com/26889933/69487346-f1f54180-0e0c-11ea-9683-ce590ae39e98.png">

**What feature/behavior/change do you want?**
maybe just a regular test instead of the symbols

**Comment by kalbir** [comment]
Hey @eightlimbed, appreciate the ticket but we are not going to change this, we like the output :)

What you can do is use three backticks (```) in slack to get a more consistent output:

<img width="788" alt="Screenshot 2020-04-16 at 18 02 48" src="https://user-images.githubusercontent.com/3952074/79485148-a38b4e00-800c-11ea-9168-269d4840fbe7.png">
