### ISSUE TITLE
Attach custom security groups to managed node groups?

### ISSUE THREAD

**Issue by jwalton** [weaveworks/eksctl#1605]
Looking at the config file schema, it seems there's no way to add security groups to managed node groups?

I have a MongoDB node that's running outside of EKS, and what I was doing was adding a custom security group to my unmanaged node groups, and then allowing connections to MongoDB from that SG.  But, obviously, if I can't attach an SG to my EKS workers, I can't do this.  :P  Is there a better way to manage these sorts of permissions?

**Comment by cPu1** [comment]
This is a limitation of the EKS Managed Nodegroups API, which does not support attaching custom security groups yet. (It supports that only for SSH access right now).

We'll monitor the Managed Nodegroups API for support for this feature and add it to eksctl when it's available.

**Comment by calebpalmer** [comment]
This is a bit of a blocker for me.  Our clusters need to access RDS databases via a security group.  I suppose we could add inbound rules for the CIDRs of the private subnets the nodegroups exists in, but I'd prefer to allow via a security group.  Too bad AWS doesn't allow this yet, seems like a bit of a no brainer.

**Comment by whereisaaron** [comment]
@cPut1 I'm struggling to understand how to associate managed nodes with preexisting security groups. In my can I need to associate the security group needed for managed nodes to be able to access NAT gateways.

It seems weird that `ssh` has this generous facility, to link not one but a whole list of pre-existing security groups for `ssh` access, but there is no provision to associate security groups for any other purpose! You wonder what people are thinking on the other side of the wall sometime :-)

Although you can't specify security groups on the managed node groups, I notice the `vpc` section has spouted 'securityGroup' and 'sharedNodeSecurityGroup` options. As far I can tell from reading all of `eksctl.io` they are undocumented? Will they impact in any way the security groups assigned to managed nodes? Or else do you know what they are for?

**Comment by whereisaaron** [comment]
Found this containers road map issue tracking this limitation. AWS are suggesting the upcoming Launch Template support will enable attaching SGs. Add your 👍 over there:

https://github.com/aws/containers-roadmap/issues/609

**Comment by cPu1** [comment]
Support for custom security groups in managed nodegroups (https://github.com/weaveworks/eksctl/pull/2544) is out in https://github.com/weaveworks/eksctl/releases/tag/0.26.0-rc.1

Usage documentation and examples can be found at https://release-0_26--eksctl.netlify.app/usage/launch-template-support/ and https://release-0_26--eksctl.netlify.app/usage/eks-managed-nodes/ (The documentation will be live on eksctl.io in a few days when 0.26 is out).
