### ISSUE TITLE
refresh cluster CA when it expires

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#161]
Instead of having to use `aws eks` and `jq`, we let cloud-init write the certificate directly. We should finds a way to update the certificate before it expires.

**Comment by errordeveloper** [comment]
I think it'd make sense to do it via a CronJob. It'd be reasonable to suggest that we can schedule such a job for the time just before cert expires. The job could create DaemonSet basically. Alternatively, we have enough time to get kubeadm support, or provide add a simple Go program that fetches the CA cert every time before kubelet starts up.

**Comment by errordeveloper** [comment]
@mumoshu I think it doesn't actually have to be restarted right away, it's just that the CA needs to be there there when it happens to restart.

**Comment by whereisaaron** [comment]
Doesn't EKS support automatic certificate rotation for the kubelet? At least that is what AWS were promising in 2017 😄. Or EKS does support it but `eksctl` is not using that feature for nodes?

![image](https://user-images.githubusercontent.com/1109585/54628255-8839c200-4a4b-11e9-8039-1a41d9dc9e20.png)

**Comment by pawelprazak** [comment]
I believe if you use the original `bootstrap.sh` form the Amazon AMI it should work as advertised, but I haven't tested it.

Generally fetching CA at deploy time instead of boot time causes unnecessary complexity in the code IMO.

**Comment by errordeveloper** [comment]
On Tue, 9 Apr 2019, 9:53 am Paweł Prażak, <notifications@github.com> wrote:

> I believe if you use the original bootstrap.sh form the Amazon AMI it
> should work as advertised, but I haven't tested it.
>

I am not sure, I think that is only true for new nodes.

I don't believe it is setup to automatically refresh the CA.

> Generally fetching CA at deploy time instead of boot time causes
> unnecessary complexity in the code IMO.
>

Why? I think it is rather the opposite, as boot should be as stateless as
possible. When we deploy a new nodegroup we already have the CA, so we just
need to pass it to the node.

**Comment by pawelprazak** [comment]
Sorry I got confused by this line:
https://github.com/awslabs/amazon-eks-ami/blob/master/files/kubelet-config.json#L29

```json
"RotateKubeletServerCertificate": true
```

Sure, I see you point.

I guess it's a tradeoff between following EKS design/architecture in code and following your own architecture principles.

BTW, to pass ca/url pair we could reuse original `bootstrap.sh` with:
```
--b64-cluster-ca The base64 encoded cluster CA content. Only valid when used with --apiserver-endpoint. Bypasses calling "aws eks describe-cluster"
--apiserver-endpoint The EKS cluster API Server endpoint. Only valid when used with --b64-cluster-ca. Bypasses calling "aws eks describe-cluster"
```
