### ISSUE TITLE
Improve clarity of stringToString arguments in eksctl help/usage

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1616]
**What happened?**

Our help/usage isn't always very clear about what `stringToString` is:
```console
$ eksctl create cluster --help
[...]
      --tags stringToString       A list of KV pairs used to tag the AWS resources (e.g. "Owner=John Doe,Team=Some Team") (default [])
[...]
      --node-labels stringToString     Extra labels to add when registering the nodes in the nodegroup, e.g. "partition=backend,nodeclass=hugememory" (default [])
[...]
$ eksctl create nodegroup --help
[...]
      --node-labels stringToString     Extra labels to add when registering the nodes in the nodegroup, e.g. "partition=backend,nodeclass=hugememory" (default [])
[...]
$ eksctl set labels --help
[...]
  -l, --labels stringToString   Create Labels (default [])
[...]
```

Note that this comes from a dependency we use for CLI: https://github.com/spf13/pflag/blob/2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab/string_to_string.go#L61

**What would you rather have?**

Something clarifying more consistently that it is a sequence of key-value pairs, either:

- instead of `stringToString` (may require change upstream or a fork),
- as part of the description,

e.g.:

1. `key=value`
2. `k1=v1,...,kN=vN`

(votes/suggestions welcome)

**Comment by agbanagba** [comment]
Hi @marccarre, I'm new here and want to contribute to eksctl. I think there is no consistency in the description of the flags that use stringToString specifying it's a key-value pair and we can do better there.

I can jump on it if no one is working on it yet.

**Comment by marccarre** [comment]
Hi @agbanagba! 😊 Welcome to `eksctl` and thank you very much for offering to contribute! 🙇 
As far as I know, no one is working on this at the moment, so this would definitely help! 👍 
What would you have in mind to improve the experience here? 😮

**Comment by agbanagba** [comment]
Having a consistent description across flags using stringToString I think it best in this case. I'll jump right to it.
