### ISSUE TITLE
ARM64 ?

### ISSUE THREAD

**Issue by Fabio-Ottaviani-Dev** [weaveworks/eksctl#1624]
Hi, I tried to run it on Raspberry Pi, but doesn't work due to the different architecture, in the installation guide is provide only a amd64 version;
there is a version for ARM64?

**Comment by rndstr** [comment]
(for completeness, pasting the Slack response her)

> @gemagomez: 
>  we don't build for Arm64, there is no reason though why the project couldn't build there, so please > have a go at building and let us know how it goes
