### ISSUE TITLE
ssh key not getting added when passing custom name

### ISSUE THREAD

**Issue by dingn1** [weaveworks/eksctl#165]
**What happened?**
ssh key not getting added when passing custom name
did not see ` importing SSH public key` in the output and can not ssh after the cluster is created.
**What you expected to happen?**
This should run ` importing SSH public key`

**How to reproduce it?**
```eksctl create cluster --name=sone-name```

**Versions**
Please paste in the output of these commands:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ uname -a
Linux localhost 3.13.0-141-generic #190-Ubuntu SMP Fri Jan 19 12:52:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ eksctl version
2018-08-16T15:54:51Z [ℹ]  versionInfo = map[string]string{"builtAt":"2018-08-02T14:03:11Z", "gitCommit":"dca39f69e893b89d67156635c483b3f3e8236407", "gitTag":"0.1.0"}
```

### *note: this does not happen when purely run `eksctl create cluster `*

**Comment by errordeveloper** [comment]
It still gets used. You might want to run with `--verbose=4`, if you are not sure what's going on.
