### ISSUE TITLE
eksctl resources not really deleted after deleting cluster

### ISSUE THREAD

**Issue by scardena** [weaveworks/eksctl#1651]
**What happened?**
This is not an actual error. Basically eksctl reports that "all cluster resources were deleted", but this is not true, as even after getting the shell back, I can see that the eks cluster is in "Deleting" state. 

**What you expected to happen?**
I was expecting that after getting the message "all cluster resources were deleted", the resources were actually deleted. I don't know if this should apply for the rest of the resources, including vpc/subnets/routes/sec groups etc, as the message only says "cluster resources", but the fact that eks is still on "deleting" state, makes the initial statement no longer true.

**How to reproduce it?**
`eksctl create cluster`
`eksctl get cluster #To get the name`
`eksctl delete <whatever cluster name was returned by the previous command>`

**Anything else we need to know?**
Not really, fairly easy to reproduce, the output will pop up in like 2-3 min, and the actual deletion takes like 15.

**Versions**
eksctl version
version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.11.1"}

**Logs**
Not really required.

**Comment by kaikuchn** [comment]
This is related to (as in it's a part of) the problem I encountered https://github.com/weaveworks/eksctl/issues/1597

**Comment by cPu1** [comment]
@scardena `eksctl delete cluster` does not wait for the cluster's stack deletion to complete by default, because the actual deletion can take a few minutes (~10-15). In order to wait for the deletion to complete, use the `--wait` flag.
