### ISSUE TITLE
Command to delete/dissociate the identity provider

### ISSUE THREAD

**Issue by piyushjajoo** [weaveworks/eksctl#1653]
We use "eksctl utils associate-iam-oidc-provider" but there is no command to delete/dissociate the oidc-provider. 

Currently, associate-iam-oidc-provider command creates a new OIDC provider in IAM/Identity Providers and when we delete our cluster it doesn't delete the Identity Provider automatically. And since every new cluster creates a new OIDC resource, there is no way to use the existing identity provider. Hence we need a delete command so that we can delete the created identity provider.

**Comment by mreferre** [comment]
+1 

It would be handy for some scripting I am doing. Right now I am working it around like this: 
```
OIDCURL=$(aws eks describe-cluster --name $CLUSTER_NAME --output json | jq -r .cluster.identity.oidc.issuer | sed -e "s*https://**")
aws iam delete-open-id-connect-provider --open-id-connect-provider-arn arn:aws:iam::$ACCOUNT_ID:oidc-provider/$OIDCURL
```

Not elegant, but it seems to be working.

**Comment by fescobar** [comment]
This is another way to delete the OIDC associated to the cluster
```sh
aws iam list-open-id-connect-providers
ACCOUNT_ID=$(aws sts get-caller-identity | python3 -c "import sys,json; print (json.load(sys.stdin)['Account'])")
echo $ACCOUNT_ID
                
OIDCURL=$(aws eks describe-cluster --name $CLUSTER_NAME --region $REGION --query "cluster.identity.oidc.issuer" --output text  | python3 -c "import sys; print (sys.stdin.readline().replace('https://',''))")
echo $OIDCURL
aws iam delete-open-id-connect-provider --open-id-connect-provider-arn arn:aws:iam::$ACCOUNT_ID:oidc-provider/$OIDCURL
aws iam list-open-id-connect-providers
```
