### ISSUE TITLE
Make the creation of the Fargate role optional

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1669]
### Why do you want this feature?

Currently, all new EKS clusters are created with a `FargatePodExecutionRole`. While this role is pretty harmless as:

- it only has the `arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy` policy,
- it only is used by AWS to be able to schedule pods on Fargate,

it would still be better to be minimalist about it, so that users not leveraging the Fargate integration do not have to care nor worry about it.

----

N.B.: this was originally raised on Slack [here](https://weave-community.slack.com/archives/CAYBZBWGL/p1576268977007000):

> When I try to create a cluster it attempts to create a role for fargate (Role/FargatePodExecutionRole). How do I not create this role?
> [...]
> my issue is actually that creating the role isn’t allowed, unless I can **attach a permissions boundary** to it. So right now it is failing because of our permissions.
> I would be ok creating it if it would let me.

### What feature/behavior/change do you want?

1. Only create it:

    1. on cluster creation, if `--fargate` was provided,
    2. on Fargate profile creation, if the role doesn't exist already.

2. Add [permission boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) to it, here:
    https://github.com/weaveworks/eksctl/blob/521beec337285f9ab97a84d8a9fc2b337b3e4522/pkg/cfn/builder/fargate.go#L29-L37

**Comment by soony88** [comment]
I'm having the exact same problem.

The company I work at does not let us create IAM roles/policies therefore I'm running into permission issues.

We have a process of creating IAM roles through via a pipeline; if there was at least a way to specify an existing Fargate pod execution role we could get around this issue, but it does not seem like there is.

**Comment by soony88** [comment]
We ran into the same issue in my org,

We were not allowed to create roles under our federated profiles therefore the eksctl create cluster command kept failing every time it tried to create a role.

To get around this issue, we went through our company process on getting roles created,
and specified in our cluster config to use these roles rather than attempt to create one during the command.


cluster-config.yaml
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

iam:
  serviceRoleARN: "<arn>"
  fargatePodExecutionRoleARN: "<arn>"
```

**Comment by marccarre** [comment]
Note that the part of this issue related to permission boundaries is solved by #1638

**Comment by marccarre** [comment]
> on Fargate profile creation, if the role doesn't exist already.

Note that this was done as part of https://github.com/weaveworks/eksctl/pull/1665.

**Comment by mrPsycho** [comment]
can you release 0.13.1 with this fix?

**Comment by marccarre** [comment]
@mrPsycho, just to better understand your constraints, what prevents you from upgrading to 0.14.0 once it becomes available? cc: @cPu1, @martina-if, @gemagomez.

**Comment by mrPsycho** [comment]
nothing) but it looks like 0.14.0 has much more things to do, but it would be great to use it now. 

but, actually, we found one not very good thing - it truncates role name... and suffix is very long... we solved it by placing limits to our naming, but would be cool to use something shorter, then *-FargatePodExecutionRole-*

i understand, that this name is obvious, but... it takes 23 chars from naming, which sometimes leads to errors.
