### ISSUE TITLE
Option to set the client-id-list for the OIDC provider for use with STS VPC endpoints

### ISSUE THREAD

**Issue by john-auld** [weaveworks/eksctl#1672]
**Feature request**
Add an option in the OIDC settings section to set the audience (called client-id in the cli) to a value provided by the user.

**Why do you want this feature?**
The OIDC provider created by eksctl is configured with the global endpoint for the STS service (sts.amazonaws.com), which does not work for nodegroups in a private subnet having no direct Internet connection and a VPC endpoint for the STS service.

The VPC endpoint can only be configured with regional STS endpoints, such as sts.eu-west-1.amazonaws.com and not for the global endpoint sts.amazonaws.com.

If a VPC Endpoint is used for STS, the Audience setting in the console should be changed from sts.amazonaws.com to sts.aws-region.amazonaws.com.

**What feature/behavior/change do you want?**

Add an option to configure the client-id-list when creating new clusters. This affects the success of AssumeRoleWithWebIdentity calls to the STS service.

```
iam:
  withOIDC: true
  oidcClientIdList:
     - sts.eu-west-1.amazonaws.com
```

For reference purposes, the cli commands for configuring the OIDC provider are shown below.

```
aws iam create-open-id-connect-provider \
          --url $ISSUER_URL \
          --thumbprint-list $ROOT_CA_FINGERPRINT \
          --client-id-list sts.<region>.amazonaws.com
```

**Comment by aclevername** [comment]
Closing due to staleness. Feel free to re-open :smile:
