### ISSUE TITLE
Allow disabling public IP allocation in public subnet

### ISSUE THREAD

**Issue by jfautley** [weaveworks/eksctl#1684]
I know, on the face of it this sounds a bit odd - but hear me out... :)

**Why do you want this feature?**
We have a fairly standard "corporate world" AWS configuration, where we have an "inbound" VPC, which is directly routable from our corporate network, and then "workload" VPCs hidden behind this, that are not routable. We have no NAT or IGWs attached to any of our VPCs. In this respect, our 'public' VPC is the one routed from our corporate network, and our 'private' is one that's AWS-only.

`eksctl` currently mostly works in this respect, but it will allocate a public IP to an instance in the public subnet, even though it can't ever be used. It still sets off our security monitoring tools, though 😢 

**What feature/behavior/change do you want?**
Something along the lines of the below would be perfect:

```
nodeGroups
  - name: private-hosts
    instanceType: t3.large
    desiredCapacity: 2
    privateNetworking: true

  - name: routed-hosts
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: false
>>  assignPublicIP: false
```

**Comment by sayboras** [comment]
I faced the same issue, and found out that it's really EKS issue, but not eksctl. Here is the related feature request for EKS https://github.com/aws/containers-roadmap/issues/607.

**Comment by sayboras** [comment]
@jfautley @martina-if I think we can close this issue now, supported by AWS and eksctl 0.18.0.
