### ISSUE TITLE
use aws-iam-authenticator as default once new version is out

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#169]
https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/119

**Comment by errordeveloper** [comment]
We should also update the library.

**Comment by errordeveloper** [comment]
> Unable to install heptio-authenticator-aws since it is removed from github.

Not true. The binaries are here: https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.3.0

And here for Windows: https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/windows/amd64/heptio-authenticator-aws.exe

> Able to install aws-iam-authenticator but eksctl is not using it.

You will be able to do this soon, once we release 0.1.1, probably before end of this week.

**Comment by arun-gupta** [comment]
Looking forward to 0.1.1 release

**Comment by tsal** [comment]
editing the generated configuration to use `aws-iam-authenticator` seems to solve this issue just fine.

**Comment by arun-gupta** [comment]
0.1.2 does not seem to fix this as well. What is the ETA?

**Comment by errordeveloper** [comment]
@arun-gupta https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/119 is still open also. I would rather avoid creating a work-around, unless the chances of https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/119 being fixed in the next month are too low.

**Comment by arun-gupta** [comment]
Created a new cluster using eksctl and seems like this renaming is no longer required.

```
2018-12-14T18:17:31-06:00 [ℹ]  versionInfo = map[string]string{"gitCommit":"191474b2b0a6e6856b5f9c652c38b5f2f01bf7c9", "gitTag":"0.1.11", "builtAt":"2018-11-09T16:15:40Z"}
```

Should this still be open?

**Comment by errordeveloper** [comment]
Yes, this should be open until authenticator 0.4.0 is out and kubernetes-sigs/aws-iam-authenticator#119 closed, so that we can delete all references to `heptio-authenticator-aws`.

**Comment by errordeveloper** [comment]
Looks like `0.4.0-alpha.1` was released in October, but no new releases since then.

**Comment by errordeveloper** [comment]
[0.4.0](https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.4.0) is out now, we should try to add this for the next release.
