### ISSUE TITLE
Need help in setting up `Public access source whitelist`

### ISSUE THREAD

**Issue by Rajesh804** [weaveworks/eksctl#1697]
Hi, 

I need help with eksctl templte where we can allow specific IP addresses using the new feature -  **Public access source whitelist**. can any one please help with the exact snippet to use.

Thanks,
RR

**Comment by cPu1** [comment]
I believe you're referring to the ability to restrict access to the EKS Kubernetes public API endpoint. 
This can be achieved by adding this field to the ClusterConfig file:
```yaml
vpc:
  publicAccessCIDRs: ["1.1.1.1/32", "2.2.2.0/24"]
```
More details here: https://github.com/weaveworks/eksctl/blob/master/site/content/usage/06-vpc-networking.md#restricting-access-to-the-eks-kubernetes-public-api-endpoint

Please note that this is only available in [0.12.0-rc.0](https://github.com/weaveworks/eksctl/releases/tag/0.12.0-rc.0), there will be a `0.12.0` release some time this week.

**Comment by Rajesh804** [comment]
Thank you so much. This is exactly what I was looking for.

**Comment by cPu1** [comment]
Great. Please go through the documentation and open a new issue if you have any questions.
