### ISSUE TITLE
should "--override-existing-serviceaccounts" be an default behavior?

### ISSUE THREAD

**Issue by M00nF1sh** [weaveworks/eksctl#1698]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
I feel like the service-account for applications should be create along with the application. (e.g. embed in application's yamls which included SA/rbac roles/deployments/etc.)
EKSCTL's `eksctl create iamserviceaccount` should ideally only create an iam role and annotate existing SA with the role.....(which merely attach eks-specific behavior to a cloud-neutral k8s application)

**What feature/behavior/change do you want?**
make --override-existing-serviceaccounts an default behavior, or another command?

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by michaelbeaumont** [comment]
@aclevername You've been doing a lot of iamserviceaccount changes with #1497, wdyt?

**Comment by michaelbeaumont** [comment]
Relevant for #2774

**Comment by aclevername** [comment]
https://github.com/weaveworks/eksctl/issues/3042 seems quite similar to this. Seems to be a varying of opinion on what should happen regarding service accounts. I outlined in a [comment](https://github.com/weaveworks/eksctl/issues/3042#issuecomment-756730328) my thoughts on having the ability to skip service account creation/annotation. I think its a good idea, particularly in the context of a gitops setup combined with the `roleName` field for IAMServiceAccounts

**Comment by michaelbeaumont** [comment]
Closing, won't be changed until #2774
