### ISSUE TITLE
Add Cluster AutoScaler as an Addon

### ISSUE THREAD

**Issue by christopherhein** [weaveworks/eksctl#170]
Needs to add the following policy to the instance role:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
    ]
}
```

Apply the CA manifest file with the autoscaling group prefilled.

**Comment by errordeveloper** [comment]
I think we should be able to cater for this very easily once #132 lands.

**Comment by michaelbeaumont** [comment]
The IAM permissions are now available with `iamConfig.WithAddonPolicies.AutoScaler`. Seems like consensus is that the autoscaler addon itself doesn't need to be part of eksctl
