### ISSUE TITLE
eksctl use private eks endpoints.

### ISSUE THREAD

**Issue by AbubakrSamsodien** [weaveworks/eksctl#1701]
I tried creating a cluster and disabled public endpoints. 
all it did was give me a warning saying:

[✖]  warning, having public access disallowed will subsequently interfere with some features of eksctl. This will require running subsequent eksctl (and Kubernetes) commands/API calls from within the VPC.  Running these in the VPC requires making updates to some AWS resources.  See: https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html#private-access for more details

Then the build just failed. (using codebuild)

I understand that eksctl is busy maturing but  what i go was from the warning was that i might not be able to use all the available features if i dont use public endpoints.
my question is, will i ever be able to use eksctl with private endpoints fully featured? 
secondly, why has my build fail when setting "false" to public endpoints when creating a cluster?

this is my configfile:
`apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clustername
  region: eu-west-1

vpc:
  nat:
    gateway: Disable
  subnets:
    private:
      eu-west-1a: { id: subnet-xxxxx }
      eu-west-1b: { id: subnet-xxxxx }
    public:
      eu-west-1a: { id: subnet-xxxxx }
      eu-west-1b: { id: subnet-xxxxx }
  clusterEndpoints:
    publicAccess:  false
    privateAccess: true`

**Comment by slavkad** [comment]
+1

**Comment by fgg89** [comment]
+1

I'm also interested in this...

**Comment by sayboras** [comment]
Related to https://github.com/weaveworks/eksctl/pull/2071

**Comment by michaelbeaumont** [comment]
Closed by https://github.com/weaveworks/eksctl/pull/2071 as far as I can tell
