### ISSUE TITLE
Enable Port 10255 on Worker Nodes

### ISSUE THREAD

**Issue by jserviceorg** [weaveworks/eksctl#1707]
i am looking for a way to pass --kubelet-extra-args '--read-only-port=10255' as extra option to my worker nodes, can i somehow do this with eksctl? i dont want to bypass eksctl by editing the cloudformation part directly

**Comment by sayboras** [comment]
I don't quite understand the part you mentioned `editing the cloudformation`, however you can try to follow this docs https://eksctl.io/usage/customizing-the-kubelet to pass extra kubelet args.

As checked the code, this object is just the map, so you can basically pass any params. https://github.com/weaveworks/eksctl/blob/master/pkg/apis/eksctl.io/v1alpha5/types.go#L613

**Comment by aaronj314** [comment]
any examples on how to set the '--read-only-port' parameter?   I've tried many combinations and keep getting 'validating generated KubeletConfiguration object: error unmarshaling JSON: while decoding JSON: json: unknown field'.

**Comment by michaelbeaumont** [comment]
Thanks @sayboras, closing this!
