### ISSUE TITLE
create new nodeGroup - CloudFormation error

### ISSUE THREAD

**Issue by eladh** [weaveworks/eksctl#1713]
**What happened?**
create cluster without nodegroup or create one with logic error such as min count is less then desired count .

run  eksctl create nodegroup --config-file=data.yaml

--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-data
  region: eu-central-1 

nodeGroups:
  - name: infra-node-group 
    instanceType: a1.large
    desiredCapacity: 1 
    minSize: 1 
    maxSize: 2 
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    availabilityZones: ["eu-central-1a", "eu-central-1b"]

NodeGroup | - | AWS::AutoScaling::AutoScalingGroup | CREATE_FAILED | You must use a valid fully-formed launch template. The requested configuration is currently not supported. Please check the documentation for supported configurations. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: c4a3285b-3628-11ea-b1b3-5b5a5f678048)
-- | -- | -- | -- | --

adh@eladh-ThinkPad-X1-Extreme-2nd:~/Desktop/workspace/devops/eksctl$ eksctl create nodegroup --config-file=data.yaml
[ℹ]  eksctl version 0.12.0
[ℹ]  using region eu-central-1
[ℹ]  will use version 1.14 for new nodegroup(s) based on control plane version
[ℹ]  nodegroup "infra-node-group" will use "ami-07034b303e1ffc843" [AmazonLinux2/1.14]
[ℹ]  1 nodegroup (infra-node-group) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 1 nodegroups in cluster "agpulse-data"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create nodegroup "infra-node-group" } } }
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack has all required resources
[ℹ]  building nodegroup stack "eksctl-agpulse-data-nodegroup-infra-node-group"
[ℹ]  deploying stack "eksctl-agpulse-data-nodegroup-infra-node-group"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-agpulse-data-nodegroup-infra-node-group"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::IAM::InstanceProfile/NodeInstanceProfile: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroup/SG: DELETE_IN_PROGRESS
[!]  AWS::EC2::LaunchTemplate/NodeGroupLaunchTemplate: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterCP: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterCluster: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterAPI: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterClusterAPI: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterCluster: DELETE_IN_PROGRESS
[✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "You must use a valid fully-formed launch template. The requested configuration is currently not supported. Please check the documentation for supported configurations. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: c4a3285b-3628-11ea-b1b3-5b5a5f678048)"

**What you expected to happen?**
be able to create new nodegroup 

**How to reproduce it?**
create cluster without nodegroup or create one with logic error such as min count is less then desired count  , then create new nodegroup

**Anything else we need to know?**

**Versions**
Please paste in the output of these commands:
```
$ eksctl version = 0.12.0
$ kubectl version = Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by sayboras** [comment]
This could be related to instance type `a1` that you are using. EKS A1 is still under preview and not supported generally as per https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-ec2-a1-preview

**Comment by sayboras** [comment]
@eladh not sure if the above explanation makes sense to you, or you are facing other error.

**Comment by cPu1** [comment]
@eladh it appears the error you ran into was due to eksctl not having created a subnet in the availability zones you have specified for your nodegroup. There was a bug in 0.12 RC that swallowed validation errors from the subnet handling logic: https://github.com/weaveworks/eksctl/pull/1661. 

To instruct eksctl to create subnets in a specific set of availability zones, specify them at the top level as in:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-data
  region: eu-central-1

availabilityZones: ["eu-central-1a", "eu-central-1b"]

nodeGroups:
- name: infra-node-group
  availabilityZones: ["eu-central-1a", "eu-central-1b"]
# more fields
```

If you try this config on eksctl 0.13, you should get a validation error, something along these lines: `VPC doesn't have subnets in...`

**Comment by martina-if** [comment]
I am closing this but feel free to reopen it if you still have this issue after following my colleague's advice with a newer version of eksctl.
