### ISSUE TITLE
allow to customize coredns resources

### ISSUE THREAD

**Issue by omerlh** [weaveworks/eksctl#1716]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
We had an issue where corends pod used almost 500 mCPU, where the defined request in the pod is 100 mCPU. We had to edit the deployment manually using kubectl. This change will be reverted next time will run `eksct util update-coredns`.

**What feature/behavior/change do you want?**
An option to specify resources (request/limit) for utilis, ideally using eksctl config file.

**Comment by everpeace** [comment]
I would like to make coredns resource more customizable, `tolerations`, `nodeSelector`, etc.
