### ISSUE TITLE
eksctl operator

### ISSUE THREAD

**Issue by omerlh** [weaveworks/eksctl#1717]
**Why do you want this feature?**
Having full gitops flow for cluster creation - just commit the CRD to github, and the operator will create a new cluster per the provided spec.

**What feature/behavior/change do you want?**
Adding a new operator that will listen to eks ctl resources, and provision new eks cluster based on the resource spec. The spec can be based on the existing config file.

**Comment by marccarre** [comment]
Hi @omerlh, many thanks for opening this issue!
This is something which is actually on `eksctl`'s 2020 roadmap, and is work in progress.
We have an internal prototype at Weaveworks which is exactly what you are describing: a modified version of `ClusterConfig` as a CRD + operator monitoring it & updating the cluster via Kubernetes' cluster API. We plan to make it publicly available at some point, but it isn't ready just yet.
The issue to track would be #20. (I'll close this issue in favour of it if that's OK, but feel free to add your suggestions/requirements to #20! 😊)

**Comment by omerlh** [comment]
Thank you! That's so great to hear!
