### ISSUE TITLE
macOS Catalina: "eksctl" cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by rodrigc** [weaveworks/eksctl#1718]
On macOS Catalina 10.15, I downloaded the eksctl_Darwin_amd64.tar.gz for  0.12.0  from: https://github.com/weaveworks/eksctl/releases

when I tried to run it, I got this error message:

![image](https://user-images.githubusercontent.com/1895943/72381195-d3ece480-36cb-11ea-93cd-e04cb4bee250.png)

**Comment by rodrigc** [comment]
This is due to a new feature called Gatekeeper in macOS: https://support.apple.com/en-us/HT202491

You can follow the steps in that article to change the security settings so that you can run eksctl

**Comment by rodrigc** [comment]
Alternatively you can disable Gatekeeper in macOS:

http://osxdaily.com/2015/05/04/disable-gatekeeper-command-line-mac-osx/
https://www.hendrix.edu/HelpDesk/Computers_and_Devices/Mac_Computers/Disabling_and_Enabling_Gatekeeper_for_Mac_OS_X/

**Comment by rodrigc** [comment]
The Go team faced the same issue: https://github.com/golang/go/issues/34986

**Comment by martina-if** [comment]
:+1: Thanks @rodrigc I will close this but feel free to reopen it if you think there's any action needed.
