### ISSUE TITLE
snap installation can't access aws profiles.

### ISSUE THREAD

**Issue by yfried** [weaveworks/eksctl#1721]
**What happened?**
A description of actual behavior (with error messages).
Installed via snap and failed to create cluster using `--profile` flag

Remove snap package and installed from github/releases. Same command worked

**What you expected to happen?**
cluster creation

**How to reproduce it?**
install from snap
Run `eksctl create cluster ... --profile MYPROFILE`

**Anything else we need to know?**
Ubuntu 18.04

**Versions**
Please paste in the output of these commands:
```
eksctl version 0.12.0
kubectl version 1.15.7
```

**Logs**
```
[ℹ]  eksctl version 0.12.0
[ℹ]  using region us-east-2
[!]  retryable error (RequestError: send request failed
caused by: Put http://169.254.169.254/latest/api/token: dial tcp 169.254.169.254:80: connect: no route to host) from ec2metadata/GetToken - will retry after delay of 39.892905ms
[!]  retryable error (RequestError: send request failed
caused by: Put http://169.254.169.254/latest/api/token: dial tcp 169.254.169.254:80: connect: no route to host) from ec2metadata/GetToken - will retry after delay of 99.423428ms
```

**Comment by raeking** [comment]
encountered this issue as well. interested to know the resolution or workaround. thanks

**Comment by yfried** [comment]
Remove the snap package and install direct from GitHub releases page

**Comment by dholbach** [comment]
Thanks for sending this issue. We have a couple of issues to sort out regarding the snap, this will take a while, so I'd go with @yfried 's suggestion. In the meantime we'll disable the snap and re-enable once we have things figured out. Thanks for your patience.

**Comment by ymshenyu** [comment]
@dholbach Maybe you should use classic confinement like aws-cli and kubectl. See [here](https://ubuntu.com/blog/how-to-snap-introducing-classic-confinement) for details.

**Comment by dholbach** [comment]
Yes, @ymshenyu - that's the plan. This will require a discussion like in [1](https://forum.snapcraft.io/t/classic-confinement-for-fluxctl/13816) and [2](https://forum.snapcraft.io/t/fluxctl-personal-files-was-fluxctl-snap-wants-to-be-classic/11073) for `fluxctl`.

Let's collect requirements. Apart from reading profiles from arbitrary paths, what else will `eksctl` need to be able to do?

**Comment by ymshenyu** [comment]
@dholbach 
```
[pid 17550] openat(AT_FDCWD, "/home/guobang/snap/eksctl/x1/.aws/config", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 17550] openat(AT_FDCWD, "/home/guobang/snap/eksctl/x1/.aws/credentials", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 17550] openat(AT_FDCWD, "/home/guobang/snap/eksctl/x1/.aws/config", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 17550] openat(AT_FDCWD, "/home/guobang/snap/eksctl/x1/.aws/credentials", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 17550] openat(AT_FDCWD, "/home/guobang/snap/eksctl/x1/.aws/config", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 17550] openat(AT_FDCWD, "/home/guobang/snap/eksctl/x1/.aws/credentials", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 17550] openat(AT_FDCWD, "/home/guobang/snap/eksctl/x1/.aws/config", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 17550] openat(AT_FDCWD, "/home/guobang/snap/eksctl/x1/.aws/credentials", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by ymshenyu** [comment]
I think it's reading the wrong files.

**Comment by tuapuikia** [comment]
The snap needs to have classic confinement in order to use AWS credentials in the user's home hidden directory. 1 thing you can do is jailbreak the snap confinement by using the symlink method.

FYI, I'm the previous eksctl snap maintainer.
