### ISSUE TITLE
Add ability to use oath tokens for github authentication for the gitops parameters

### ISSUE THREAD

**Issue by JayG-EBSCO** [weaveworks/eksctl#1725]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
As an organization, we rely soley on oath tokens for github authentication, and do not use ssh keys. The following command example does not appear to have a method to use anything other than SSH keys:
`EKSCTL_EXPERIMENTAL=true \
        eksctl enable repo \
        --git-url git@github.com:example/my-eks-config \
        --git-email your@email.com \
        --cluster your-cluster-name \
        --region your-cluster-region`
Having to add an ssh key as a deploy key is cumbersome.

**What feature/behavior/change do you want?**
A clear and concise description of the change you would like to see in eksctl.

The command parameter `--git-url git@github.com:example/my-eks-config` needs to have the ability to pass credentials via https, using an oath token as an authentication option.

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by Callisto13** [comment]
Closing due to https://github.com/weaveworks/eksctl/issues/2963
