### ISSUE TITLE
Setting tlsCertFile and tlsPrivateKeyFile for kubelet for CIS benchmark remediation

### ISSUE THREAD

**Issue by affanhmalik** [weaveworks/eksctl#1740]
When I run CIS Kubernetes benchmark scanner kube-bench on my EKS nodes, one of the findings it reports is this:
`KUBE-BENCH [FAIL] 2.1.10 Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate`
Details of this test: https://github.com/aquasecurity/kube-bench/blob/master/cfg/cis-1.4/node.yaml#L222

Through trial and error, I discovered that the kubelet uses certs written to `/var/lib/kubelet/pki/kubelet-server-current.pem`. When I add this path to my nodeGroup config:
```
      tlsCertFile: /var/lib/kubelet/pki/kubelet-server-current.pem
      tlsPrivateKeyFile: /var/lib/kubelet/pki/kubelet-server-current.pem
```
 kubelet fails to start, because at start-up time the cert has not been provisioned. 

Questions:
How is the tls cert for kubelet provisioned inside a worker node?
Is there a way (in eksctl config.yaml) to update kubelet configs only after the cert has been provisioned?

**Comment by KR411-prog** [comment]
I have same question...Could anyone help on this ?

**Comment by martina-if** [comment]
Hi @affanhmalik , sorry that this went unnoticed for so long. 

> How is the tls cert for kubelet provisioned inside a worker node?

I am not sure how this works internally but I think the TLS certs are created as part of the tls bootstrapping. First the kubelet authenticates to the api server using a token and then it requests a certificate.

> Is there a way (in eksctl config.yaml) to update kubelet configs only after the cert has been provisioned?

No, unfortunately eksctl does not provide a way to modify the kubelet's configuration after cluster bootstrapping.

I am not sure what the remediation for this would be but hope that the above-mentioned comments help.

**Comment by 0lmi** [comment]
I faced with the same challenge and with this design I don't see any other solution except wait until keys appears and then re-configure and restart kubelet.
So as a workaround I added the following in my user data script in a launch template:
```
KEY_FILE=/var/lib/kubelet/pki/kubelet-server-current.pem
KUBELET_EXTRA_ARGS_CONFIG=/etc/systemd/system/kubelet.service.d/30-kubelet-extra-args.conf
counter=0
while [ $counter -lt 10 ]
do
    ls /var/lib/kubelet/pki/kubelet-server-current.pem 2>/dev/null
    status=$?
    if [ $status -eq 0 ]; then
        sed -i "s~'$~ --tls-cert-file $KEY_FILE --tls-private-key-file $KEY_FILE'~g" $KUBELET_EXTRA_ARGS_CONFIG
        systemctl daemon-reload
        systemctl restart kubelet.service
        break
    else
        sleep 5
    fi
    let counter=$counter+1
done
```

**Comment by hedasaurabh** [comment]
> I faced with the same challenge and with this design I don't see any other solution except wait until keys appears and then re-configure and restart kubelet. So as a workaround I added the following in my user data script in a launch template:
> 
> ```
> KEY_FILE=/var/lib/kubelet/pki/kubelet-server-current.pem
> KUBELET_EXTRA_ARGS_CONFIG=/etc/systemd/system/kubelet.service.d/30-kubelet-extra-args.conf
> counter=0
> while [ $counter -lt 10 ]
> do
>     ls /var/lib/kubelet/pki/kubelet-server-current.pem 2>/dev/null
>     status=$?
>     if [ $status -eq 0 ]; then
>         sed -i "s~'$~ --tls-cert-file $KEY_FILE --tls-private-key-file $KEY_FILE'~g" $KUBELET_EXTRA_ARGS_CONFIG
>         systemctl daemon-reload
>         systemctl restart kubelet.service
>         break
>     else
>         sleep 5
>     fi
>     let counter=$counter+1
> done
> ```

@0lmi I see you have added value for `--tls-cert-file` to `/var/lib/kubelet/pki/kubelet-server-current.pem`, is that correct ? Because I think this would be a private key and not a cert file?
