### ISSUE TITLE
Is it possible to setup CluseterDNS into Managed Node Group

### ISSUE THREAD

**Issue by pod2metra** [weaveworks/eksctl#1744]
We catch the issue that required to setup ClusterDns param, but we don't found any ability how to do that. Even via GUI or eksctl. 

For example: 
```
managedNodeGroups:
  - name: ng-workers
    clusterDNS: 169.254.20.10
```

**Comment by sayboras** [comment]
Not sure if it is working, but you can try to use `kubeletExtraConfig` configuration as metioned the below docs. Please let me know if you have any luck as well. Thanks :100: 

https://eksctl.io/usage/customizing-the-kubelet/

**Comment by sayboras** [comment]
I don't think it's possible with managed node group, basically we need to have the support from AWS. However, I just checked the CF https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html and CLI (https://docs.aws.amazon.com/cli/latest/reference/eks/index.html#cli-aws-eks), but can't find anything related to kubelet extra configuration. I might be wrong though.

@martina-if @cPu1 @marccarre For your inputs.

**Comment by martina-if** [comment]
Hi @pod2metra, customizing the kubelet is now supported, please check https://eksctl.io/usage/customizing-the-kubelet/. Hope that helps, if it doesn't please let us know by reopening this issue.
