### ISSUE TITLE
allow override for private only API for new cluste

### ISSUE THREAD

**Issue by jecafarelli** [weaveworks/eksctl#1745]
**Why do you want this feature?**
Currently when you try to setup a private only kubernetes cluster, it errors and doesnt let you to proceed. Stated in [this issue](https://github.com/weaveworks/eksctl/issues/1607) its because eksctl has issues joining the node groups to the master if its in private. I believe this is because it the cli wont be able to communicate with the api.

In some situations you actually might be able to communicate with the api when it is private (in my case im running inside and EC2 instance in aws, but you could also be peered with the network). In this case eksctl would not have any issues joining the nodes to the cluster.

**What feature/behavior/change do you want?**
It would be nice to have some sort of overide flag added to the cli, so that it would still error like it does, but then end with something like below so if you think it will work, it will allow you to continue.

> Error: warning, having public access disallowed will subsequently interfere with some features of eksctl. This will require running subsequent eksctl (and Kubernetes) commands/API calls from within the VPC.  Running these in the VPC requires making updates to some AWS resources.  See: https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html#private-access for more details. If you would like to still continue, please rerun the command with --private-overide

**Comment by jecafarelli** [comment]
for anyone who is looking for an automated way around this until eksctl allows you to do it, i created a base script that bootstraps the cluster for me. 

```
#Ip CIDR block for access to api
ADMIN_IP=192.168.0.1/32
REGION=us-east-1
EKS_NAME=cluster-name

# Create a cluster with both private and public endpoint on
# Should have the config file next to the bash script that creates it
eksctl create cluster  -f $EKS_NAME.yaml

# Grab the security group that the control plan uses
CP_SG=`aws eks describe-cluster --name $EKS_NAME --region $REGION | jq '.cluster.resourcesVpcConfig.securityGroupIds[0]' --raw-output`

#Add your ip adress CIDR to the ingress of that control plan so we can communicate with it
aws ec2 authorize-security-group-ingress  --group-id $CP_SG --protocol tcp --port 443 --cidr $ADMIN_IP

#Update the endpoint so it is no longer public
eksctl utils update-cluster-endpoints --name=$EKS_NAME --region $REGION --private-access=true --public-access=false --approve

# grab the config. I needed to do this because our subnets dont allow EGRESS to the public api endpoint
# and the create config command fails on me because it cant communicate through private API until SG is updated
eksctl utils write-kubeconfig --name $EKS_NAME --region $REGION
```

**Comment by cdenneen** [comment]
@jecafarelli Just for clarification the API access for 443 would need to be added to the clusterSecurityGroupId rather than the additional ones added to the cluster... so the CP_SG command would need to be modified as:

`aws eks describe-cluster --name $EKS_NAME | jq '.cluster.resourcesVpcConfig.clusterSecurityGroupId' --raw-output`

**Comment by martina-if** [comment]
I believe this is no longer the case. Please re-open if I'm mistaken.
