### ISSUE TITLE
How to modify ssh_config to connect to a private Git repo

### ISSUE THREAD

**Issue by karlmuscat** [weaveworks/eksctl#1767]
After create a new cluster using:

`eksctl create cluster --name test-cluster --managed`

and enabling flux using:

`EKSCTL_EXPERIMENTAL=true eksctl enable repo --git-url ssh://git-codecommit.eu-west-1.amazonaws.com/v1/repos/eks-config --git-branch test --git-email eks-flux@xxx --cluster test-cluster`

we have an issue where AWS CodeCommit and Flux cannot sync due to Flux not having access to CodeCommit. To fix this, we have to do two manual steps:
1) Add the public key outputted by eksctl into CodeCommit
2) Manually edit the SSH config file (/etc/ssh/ssh_config) in the Flux pod to add the AWS User ID. This is documented by AWS in step 8 [here](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-ssh-unixes.html)

Step 1 is not necessarily an issue. What bothers me is the manual step in Flux. 

Is there a way how to pre-configure this file before it gets deployed to the cluster?

**Comment by kamalvirk** [comment]
Was there any solution found to the above manual step?
