### ISSUE TITLE
Snap installation is broken

### ISSUE THREAD

**Issue by bpearson** [weaveworks/eksctl#1775]
**What happened?**
Installing eksctl using snap leads to a broken install that cannot access the filesystem or access the network. Host based binary works fine.

** Reproduction **
`$ snap install eksctl
eksctl 0.13.0 from eksctl team at Weaveworks (eksctl-snap) installed
$ cat cluster.yaml | eksctl create cluster -f -
[ℹ]  eksctl version 0.13.0-dirty
[ℹ]  using region ap-southeast-2
[!]  retryable error (RequestError: send request failed
caused by: Put http://169.254.169.254/latest/api/token: dial tcp 169.254.169.254:80: socket: permission denied) from ec2metadata/GetToken - will retry after delay of 38.207367ms
[!]  retryable error (RequestError: send request failed
caused by: Put http://169.254.169.254/latest/api/token: dial tcp 169.254.169.254:80: socket: permission denied) from ec2metadata/GetToken - will retry after delay of 73.121582ms
^C
$ eksctl create cluster -f ~/cluster.yaml 
Error: reading config file "/home/bpearson/cluster.yaml": open /home/bpearson/cluster.yaml: permission denied
`

**What you expected to happen?**
eksctl should be able to access network and filesystem

**Anything else we need to know?**
OS: Ubuntu 19.10
kubectl is installed as a snap (and it works fine)

**Versions**
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"1579594537", GitCommit:"0.13.0-dirty", GitTag:""}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dholbach** [comment]
Thanks @bpearson for sending this in. I commented on #1721 about this issue.
Closing this issue as a duplicate.
