### ISSUE TITLE
Enable dashboard using an option

### ISSUE THREAD

**Issue by arun-gupta** [weaveworks/eksctl#178]
Adding dashboard to an EKS cluster is quite an involving process as documented at https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html.

It would be a great customer experience to enable dashboard creation as an option to `create cluster` API.

**Comment by errordeveloper** [comment]
Yes, I'd love add it as one of the first add-ons

**Comment by aparamon** [comment]
Ditto https://github.com/giantswarm/kubernetes-elastic-stack

**Comment by kalbir** [comment]
The way we'd recommend doing this now is using a [profile](https://eksctl.io/gitops-quickstart/#enabling-a-quick-start-profile). The first quick start profile, [app-dev](https://github.com/weaveworks/eks-quickstart-app-dev) includes the kubernetes dashboard.
