### ISSUE TITLE
Add required subnet tag for internal loadbalancers

### ISSUE THREAD

**Issue by sean-abbott** [weaveworks/eksctl#1780]
**Why do you want this feature?**
We want to use eksctl for internal only applications. We have private subnets that are mapped into our network, and we want to be able to deploy applicaitons on eks and see them.

While attempting to install the guestbook application, I noticed that the tag required to make internal loadbalancers work wasn't applied to the subnets (https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html, 
```

Key | Value
-- | --
kubernetes.io/role/internal-elb | 1

```

When attempting to create the 

**What feature/behavior/change do you want?**
I would like eksctl to either have a setting or just assume you'll want loadbalnacers and to add this tag to my subnets, along with the kubernetes.io/cluster/<cluster-name> shared tag that is already added.

**Comment by sayboras** [comment]
@sean-abbott kindly help to share more details for above issue. Do you use the existing VPCs or eksctl dedicated vpc ? un-managed or managed node group ?

For existing VPC, I think it is making sense `not` to add the tags. As based on my experience, this will cause `drift` detection on existing VPC in your cloudformation.

I have quickly checked the code, it seems like eksctl is already added the tags for dedicated vpc https://github.com/weaveworks/eksctl/blob/master/pkg/cfn/builder/vpc.go#L47, so waiting for more information for further investigation.

**Comment by sean-abbott** [comment]
Existing VPCs. Un-managed node group.

I don't use cloudformation for my existing VPCs, I use terraform.

At the very least, in that case, I thin it makes sense to add the necessity of that option in the documentation. (which I would be happy to do). Or make it optional to add them / expect them. It's pretty easy for me to sync that up with terraform either way.

I think many folks, like me, will be coming to eksctl being pretty new to kubernetes in general, and having the only message you get be "no suitable subnet for loadbalancer" is super frustrating.

**Comment by sayboras** [comment]
@sean-abbott  Thanks for your reply, seems like the docs will be better choice I think. We can wait to hear inputs from maintainer of this project as well.

**Comment by sermilrod** [comment]
@sean-abbott that is assuming your ELBs are in the same subnet of your containers that might not be the case. It would be a mistake to add the ELB tag to the same containers subnet by default. If so, it should be configurable and the same applies to the `kubernetes.io/role/elb` tag.

**Comment by cdenneen** [comment]
> Updated:
> Just remember that the managed node group didn't support private subnet now, so I assume your case should be only un-managed node group.

@sayboras I just created a managed node group in AWS Console with private only subnets just fine.

**Comment by sean-abbott** [comment]
I was unable to do that. Can't remember exactly what the errors were. Would
like to be able to do that though.
