### ISSUE TITLE
Java SDK equivalent to EKSCTL.

### ISSUE THREAD

**Issue by padas2** [weaveworks/eksctl#1783]
**Reason for asking this feature:**
Hi,

We are moving our in-house pull request change validations (comprises of launching a set of containers for every pull request validation) from an ECS based approach to an EKS based approach.
The way to launch an EKS cluster via EKSCTL is really clean and great. 
For instance, we can provide a YAML template and EKSCTL would take care of everything else needed to launch the EKS cluster and even generates/modifies the kubeconfig file accordingly.

But all our codebase to launch containers onto the ECS cluster is completely based on Java/Groovy. And so even though we would very much like to use EKSCTL for our EKS cluster launch, we simply cannot go with it as the source code for EKSCTL is completely based in GO.

So would it be possible to get an Java SDK(or more accurately a Java API ) for EKSCTL.

PS: I had a look at the official AWS EKS Java SDK and even though it works in a way, it is not as clean and simple as the way EKSCTL works.

**Comment by vbudilov** [comment]
Have you looked into CDK? It should work for you: https://docs.aws.amazon.com/cdk/api/latest/java/index.html?software/amazon/awscdk/services/eks/package-summary.html

**Comment by martina-if** [comment]
Hi @padas2 , thank you for submitting this ticket. We appreciate your kind words about eksctl and I'm are glad to see you find it useful :) 

Building a Java SDK is not in our roadmap at the moment and  even though I see this could be useful, we have many exciting features coming so I'm afraid this will not be among our priorities in the short-mid term future.

It could be interesting to follow this ticket https://github.com/weaveworks/eksctl/issues/20. If this is implemented, Java integrations could be made more easily.
