### ISSUE TITLE
Add NodeGroup option to automatically install Amazon EFS Utils

### ISSUE THREAD

**Issue by allanchua101** [weaveworks/eksctl#1797]
**Why do you want this feature?**
In order to share EFS-based persistent volumes on multiple nodes, we have to install [efs-provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs). `efs-provisioner` will require manual installation of `amazon-efs-utils` package on the underlying EC2 instance for it to do its job. 

Clearly, this is not scalable as we have to ssh on each machine under the node group and install amazon-efs-utils.

**What feature/behavior/change do you want?**
In order to avoid manual installation of `amazon-efs-utils` on each worker node when deploying `efs-provisioner`,  It will be fantastic to automate this using a **NodeGroup** property.

**How to Install EFS Utils on Amazon Linux**

```sh
sudo yum install amazon-efs-utils -y
```

**Comment by martina-if** [comment]
Is this something that could be implemented as a GitOps profile?

**Comment by michaelbeaumont** [comment]
This should be possible using `preBootstrapCommands`.
