### ISSUE TITLE
Investigate why vpc cleanup only removes first ENI

### ISSUE THREAD

**Issue by sayboras** [weaveworks/eksctl#1806]
As mentioned in comment https://github.com/weaveworks/eksctl/pull/1786#discussion_r377961320, we might need to investigate on why only first ENI is removed as part of clean up.

**Comment by dosten** [comment]
I think we are facing this problem, we have a dangling ENI that prevents a successful deletion.

Looks like @cPu1 introduced that `return nil` in https://github.com/weaveworks/eksctl/pull/941

**Comment by sayboras** [comment]
oh forgot about this issue, let me investigate sometime this week.
