### ISSUE TITLE
Export to Terraform

### ISSUE THREAD

**Issue by mikemorris** [weaveworks/eksctl#181]
It would be great to offer an option to export a cluster configuration to be managed in Terraform, similar to the [`--target=terraform`](https://github.com/kubernetes/kops/blob/master/docs/terraform.md) functionality in kops.

Breaking this out from initial discussion in https://github.com/weaveworks/eksctl/pull/132#discussion_r208338871

/cc @richardcase @errordeveloper

**Comment by TigerC10** [comment]
> There are a couple of ways this could be achieved, but I'd like to understand the use-cases better.

For one, I think that eksctl is a great starting point for clusters with a lot of configurable options (like installing the WeaveNet cni).  For multi-cloud provider setups, terraform is fantastic - so if eksctl could output terraform scripts to be included in a multi-cloud provider project I think we get the best of both worlds.

**Comment by errordeveloper** [comment]
@TigerC10 thank you, this is quite helpful. Are there any other use-case?

**Comment by mikemorris** [comment]
My use-case is similar, although our infra is primarily on AWS - eksctl is a great quick setup tool, but we try to follow the "configuration as code" approach, using Terraform to manage all our infrastructure and tracking changes through a git repo (hopefully getting to a "GitOps" flow where changes are deployed by commiting and merging code eventually), would be great to at least be able to output the initial cluster config as Terraform files.

**Comment by bingochen87** [comment]
Looking eksctl to terraform config file

**Comment by Jonathan-7** [comment]
there's this project also written in go that supports exporting some AWS TF resources, but not EKS yet unfortunately.
https://github.com/GoogleCloudPlatform/terraformer

**Comment by errordeveloper** [comment]
Closing in favour of #1094.
