### ISSUE TITLE
Add instructions to install Windows version

### ISSUE THREAD

**Issue by arun-gupta** [weaveworks/eksctl#182]
https://github.com/weaveworks/eksctl/releases has Linux, Mac and Windows binaries. However, the current set of instructions on http://eksctl.io do not include instructions to install on Windows.

**Comment by errordeveloper** [comment]
@arun-gupta I was assuming curl command would work in a shell (cygwin or similar?). If you know a powershell equivalent off hand, it'd be most helpful! 

cc @stefanprodan

**Comment by richardcase** [comment]
We could probably use something like:

`powershell -command "& { iwr https://github.com/weaveworks/eksctl/releases/download/0.1.1/eksctl_Windows_amd64.zip -OutFile eksctl_Windows_amd64.zip }"`

And combine it with [Expand-Archive](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-6). 

I'll keep an eye on this one and if no one picks it up in a few weeks i will add this (when i retrieve my windows pc from the loft).

**Comment by pdefreitas** [comment]
The following one-liner downloads the latest release (as of now) into a temporary file, unpacks it into a eksctl directory in ProgramFiles and appends this new path into system-wide path. It should be as admin ofc.

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; Invoke-WebRequest -Uri https://github.com/weaveworks/eksctl/releases/download/0.1.11/eksctl_Windows_amd64.zip -OutFile eksctl_Windows_amd64.zip ; Expand-Archive -Path eksctl_Windows_amd64.zip -DestinationPath $Env:Programfiles\eksctl\ ; rm eksctl_Windows_amd64.zip ; [Environment]::SetEnvironmentVariable("Path", $env:Path + ";$Env:Programfiles\eksctl\", [EnvironmentVariableTarget]::Machine)
```

A production grade solution would be to make a PowerShell script like [Chocolatey](https://chocolatey.org/docs/installation) uses or maybe add this project to it ;)

**Comment by aparamon** [comment]
+1 on creating Chocolatey package!

**Comment by errordeveloper** [comment]
Help would be hugely appreciated!

**Comment by derwasp** [comment]
Here is my attempt at creating a package:
https://chocolatey.org/packages/eksctl/

This is the package source with the updater script:
https://github.com/derwasp/au-packages/tree/master/eksctl

Should update it once per 12 hours. So if a new version is released on github, it should automatically get released on chocolatey.org.
The package is in the process of being approved.

If at somepoint weaveworks would like to get permissions for the package, just reach out to me.
