### ISSUE TITLE
eksctl edit command

### ISSUE THREAD

**Issue by joshkurz** [weaveworks/eksctl#1822]
**Why do you want this feature?**
I'd like to be able to run `eksctl edit cluster foobar` to be able to edit a `eksctl` resource. This would do a simple `eksctl get` on the current resource as yaml output, and put into the users editor of choice. Then once they save, the correct `eksctl` update command would be ran.

**What feature/behavior/change do you want?**
To add an `edit` command to `eksctl`. This would follow suit with how `kubectl` works.

**Comment by sayboras** [comment]
I like this idea, hope that it is aligned with eksctl team.

There is a catch on this, currenlty update command didn't actually update all resouces though :cry:

**Comment by joshkurz** [comment]
The edit command could just support what is supported with update. I wouldn't want to add any extra logic to 'edit' that is not just a pass through to the update command. So if that means 'edit' only supports 'Clusters' for now, then that would have to do. 

Then whatever functionality is added to 'update' would automatically be available in 'edit'. Also we would have a single source of truth for any bugs or issues that updating a resource my have.

Are their plans to add 'update' functionality to other supported resources?
