### ISSUE TITLE
Spot Fargate support? and Example.

### ISSUE THREAD

**Issue by PorraphitChuasuk** [weaveworks/eksctl#1826]
Hi, I'm just found this project today and it look awesome. I see a ton of example but curious if spot fargate is supported?

**Comment by sayboras** [comment]
I can't find anything related to Fargate Spot for EKS, do you have any reference?

**Comment by sayboras** [comment]
oh just found out that it's currently raised as feature request https://github.com/aws/containers-roadmap/issues/622

**Comment by jarlva** [comment]
Hello, 
Any plans to implement spot for Fargate?
