### ISSUE TITLE
Support for create a GPU-accelerated cluster

### ISSUE THREAD

**Issue by arun-gupta** [weaveworks/eksctl#183]
**Why do you want this feature?**

EKS cluster can be created with a GPU-accelerated AMI as explained at https://aws.amazon.com/blogs/compute/running-gpu-accelerated-kubernetes-workloads-on-p3-and-p2-ec2-instances-with-amazon-eks/. `eksctl create cluster` API should provide support for that.

**What feature/behavior/change do you want?**

Update `eksctl create cluster` to pick the right AMI based upon instance type or allow the AMI id to be explicitly specified.

**Comment by arun-gupta** [comment]
// CC @countspongebob

**Comment by richardcase** [comment]
We'll have to do this i 2 parts, using the correct AMI for the instance type is the first part. And then when we have the addon framework we can add the NVIDIA device framework.

Until we get the addon framework we can add supply instructions about manually running the device framework.

**Comment by errordeveloper** [comment]
@richardcase sounds like a good plan!

So to clarify, after 1st part is done, users would be able to run `eksctl create cluster --node-type=<gpuInstanceType> [<flags>]` followed by `kubectl apply -f <gpuDriverManifest> [<flags>]`  to get going. And right now, one cannot do it, as AMI we use doesn't have GPU support. Is that correct?

And once we have add-ons (0.2.0), we will be able to cater for `eksctl create cluster  --addons=nvidia-gpu` to do the right thing.

@arun-gupta how does that sound?

**Comment by arun-gupta** [comment]
Sounds like a great plan to me, can't wait to try it out.

**Comment by arun-gupta** [comment]
Automatic installation of addon would be super!

**Comment by errordeveloper** [comment]
I think we can close this now, as further work will be tracked in #205. The @richardcase's changes are in master now and will be available in 0.1.2 binaries, which we are planning to cut today.

To use create a cluster with GPU nodes, you will need to do the following:
1. get `eksctl` 0.1.2
2. subscribe to GPU AMIs
3. run `eksctl create cluster --node-type=p3.8xlarge --timeout=40m`

I don't know if timeout doesn't have to be that long, but @richardcase should be able to confirm what value worked. The thing is that GPU nodes take longer too boot.

Docs PRs are welcome, but I'd like to get the 0.1.2 out as soon as possible, as #190 is pretty urgent.

**Comment by richardcase** [comment]
The main thing is you need to subscribe to the GPU Supported AMI:

https://aws.amazon.com/marketplace/pp/B07GRHFXGM

**Comment by richardcase** [comment]
If you have the AMI in your library then the default timeout should be sufficient. If you don't then it will take a long time to fail

**Comment by errordeveloper** [comment]
Ah, I see, didn't realise that!

**Comment by arun-gupta** [comment]
Confirming, it works as expected:

https://twitter.com/arungupta/status/1039992592350437377
