### ISSUE TITLE
Private networking with EKS and kubectl not responding

### ISSUE THREAD

**Issue by tahirali-endurance** [weaveworks/eksctl#1835]
We created an EKS cluster with private networking and after cluster creation, it is only connected from EC2 instance which is expected. We then updated the control plane security groups to allow inbound/outbound traffic from our office IP CIDR but it is still not allowing us to connect and keep saying **Unable to connect to the server: dial tcp <control plan ip>:443: i/o timeout**. We checked the firewall in our infrastructure and it is not blocking any traffic. Any idea what can potentially block the response?

**Comment by sayboras** [comment]
Just want to confirm if your office IP CIDR range is part of `private` subnets CIDR range.

**Comment by tahirali-endurance** [comment]
Thanks. What we found that if you choose private networking with EKS, the control plane can randomly go into private or public subnet. If it goes in public subnet, we have a network policy that restricts outbound traffic from public network to our office network.

**Comment by tahirali-endurance** [comment]
https://github.com/aws/containers-roadmap/issues/679

**Comment by sayboras** [comment]
Thanks for your info. 

We eventually did the same, enable public endpoints and whitelisting CIDR for corporate network.

**Comment by martina-if** [comment]
Hi @tahirali-endurance thank you for reporting this. If I understood correctly you found a solution to your issue so I will close this ticket. If you think there's an action that we should take regarding eksctl please reopen the ticket.
