### ISSUE TITLE
Setting DynamicKubeletConfig=true in the node group config doesn't appear to work

### ISSUE THREAD

**Issue by jicowan** [weaveworks/eksctl#1838]
**What happened?**
A description of actual behavior (with error messages).
Created a node group with DynamicKubeletConfig=true (in feature gates).  Created a configMap for the kubelet config and updated the node's spec with the following:
```
configSource:
    configMap:
      kubeletConfigKey: kubelet
      name: my-node-config-fgf72m767k
      namespace: kube-system
```
**What you expected to happen?**
The configuration should get dynamically applied from the ConfigMap.  The node status should get updated with a status.config but it never does. 

The config for the kubelet looks like this: 
```
[Service]
ExecStartPre=/sbin/iptables -P FORWARD ACCEPT
ExecStart=/usr/bin/kubelet --cloud-provider aws \
    --config /etc/kubernetes/kubelet/kubelet-config.json \
    --kubeconfig /var/lib/kubelet/kubeconfig \
    --container-runtime docker \
    --network-plugin cni $KUBELET_ARGS $KUBELET_EXTRA_ARGS
...
[Service]
# Local metadata parameters: REGION, AWS_DEFAULT_REGION
EnvironmentFile=/etc/eksctl/metadata.env
# Global and static parameters: CLUSTER_DNS, NODE_LABELS, NODE_TAINTS
EnvironmentFile=/etc/eksctl/kubelet.env
# Local non-static parameters: NODE_IP, INSTANCE_ID
EnvironmentFile=/etc/eksctl/kubelet.local.env

ExecStart=
ExecStart=/usr/bin/kubelet \
  --node-ip=${NODE_IP} \
  --node-labels=${NODE_LABELS},alpha.eksctl.io/instance-id=${INSTANCE_ID} \
  --max-pods=${MAX_PODS} \
  --register-node=true --register-with-taints=${NODE_TAINTS} \
  --allow-privileged=true \
  --cloud-provider=aws \
  --container-runtime=docker \
  --network-plugin=cni \
  --cni-bin-dir=/opt/cni/bin \
  --cni-conf-dir=/etc/cni/net.d \
  --pod-infra-container-image=${AWS_EKS_ECR_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/eks/pause-amd64:3.1 \
  --kubeconfig=/etc/eksctl/kubeconfig.yaml \
  --config=/etc/eksctl/kubelet.yaml
```
I do not see the flag for `--dynamic-config-file`

**Comment by jicowan** [comment]
I have tried setting KUBELET_EXTRA_ARGS in the kubelet.env file to --dynamic-config-dir and restarting the kubelet, but the kubelet still doesn't retrieve configuration from the ConfigMap.  I'd like to see better documentation on how to get this working when you provision a cluster with eksctl.

**Comment by jicowan** [comment]
Look like you have to `cp /etc/systemd/system/kubelet.service.d/10-eksclt.al2.conf` to `20-custom.conf` and add the `--dynamic-config-dir` flag to the bottom.

**Comment by kun432** [comment]
I tried eksctl v0.35.0 and got same the result. (To enable, I had to ssh each node, add kubelet's systemd unit file, and restart kubelet.)

This issue has already been closed but seems there's a note here about how-to-fix-manually only.

no fix anymore?
