### ISSUE TITLE
nodeGroups privateNetworking attribute is redundant

### ISSUE THREAD

**Issue by ozkologlu** [weaveworks/eksctl#1839]
Consider removing PrivateNetworking attribute - this can lead to error:

`ROLLBACK_IN_PROGRESS	No export named eksctl-my-eks-cluster::SubnetsPublic found. Rollback requested by user`

PrivateNetworking can be derived from cfg, default VPC configuration and whether`clusterSpec.VPC.Subnets.Public` is empty `clusterSpec.VPC.Subnets.Private` and populated

**Comment by sayboras** [comment]
In case of multiple node groups (e.g. one in public subnet, one in private subnet), we will still need this flag.
