### ISSUE TITLE
EKS has been launched in China region, please Support cn-north-1 and cn-northwest-1 EKS

### ISSUE THREAD

**Issue by liangruibupt** [weaveworks/eksctl#1859]
EKS has been launched in China region, but eksctl can not used in China region
AWS_REGION=cn-north-1

eksctl create cluster --name=${CLUSTER_NAME} --version 1.14 --nodes=2 --node-type t3.medium --managed --alb-ingress-access --region=${AWS_REGION}
Error: --region=cn-north-1 is not supported - use one of: us-west-2, us-east-1, us-east-2, ca-central-1, eu-west-1, eu-west-2, eu-west-3, eu-north-1, eu-central-1, ap-northeast-1, ap-northeast-2, ap-southeast-1, ap-southeast-2, ap-south-1, ap-east-1, me-south-1, sa-east-1

**Comment by cPu1** [comment]
@liangruibupt we have been working on adding support for China and it should be out in the next release of eksctl.
