### ISSUE TITLE
Add a configurable flag to support VPC traffic mirroring on default VPC

### ISSUE THREAD

**Issue by allanchua101** [weaveworks/eksctl#1868]
**Why do you want this feature?**
AWS VPC traffic mirroring helps in securing application by allowing security applications and tools to get visibility of traffic flowing inside a VPC cluster. 

**What feature/behavior/change do you want?**
In order to enable newly-added VPC feature called **Traffic Mirroring** on the default VPC created with the cluster, it would be nice to have a configurable flag in both the ‘create’ command and the YAML based creations

**Comment by sayboras** [comment]
I feel like that the default VPC created by eksctl should be minimal. The use case is to help any user to **quickly** spin up a new working cluster without knowing how to configure VPC.

Any advanced networking features will require more configuration/params to make it work. In case of traffic mirroring, you will need to provide a bunch of params for (Session, Filter, Rule, etc). For this use case, will it be better to manage the VPC outside of eksctl ?

**Comment by allanchua101** [comment]
@sayboras, Understood why the VPC generated is minimal. Closing this request for the mean time. 👍
