### ISSUE TITLE
IAM Role for service account is not working in AWS China regions

### ISSUE THREAD

**Issue by walkley** [weaveworks/eksctl#1871]
**What happened?**

I am testing the eksctl 0.15.0-rc.0. 

By following the [official doc](https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html) to set up IAM service account, then I connect to Pod to execute following command with service account enabled:
```
sh-4.2# aws sts get-caller-identity --region=cn-northwest-1
An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

Root cause of this issue is that the aws partition of OpenIDConnectProviderArn is in-correct: https://github.com/weaveworks/eksctl/blob/4d238734bef69eff6d2731e2c321371d6677970c/pkg/iam/oidc/api.go#L63

**What you expected to happen?**
IRSA should work in China regions.

**How to reproduce it?**
Just following [official doc](https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html)

**Anything else we need to know?**

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.15.0-rc.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by dz902** [comment]
Hi @walkley, is there a workaround to this in `v0.15.0-rc.0`?

**Comment by cPu1** [comment]
@dz902 this has been fixed in `master` and a release will be out this week. If you'd like to try it now, you can build from master.

**Comment by cPu1** [comment]
@walkley @dz902 the fix is out in https://github.com/weaveworks/eksctl/releases/tag/0.15.0-rc.1. Please try it out.
