### ISSUE TITLE
Ability to customize/override/set node names

### ISSUE THREAD

**Issue by gabrieldesousah** [weaveworks/eksctl#1882]
Hello, I am trying to get the real name of an instance and/or nodegroup using *kubectl get nodes* or *kubectl get pod -o wide* to identify in which instance any pod was. But the answer is the name that aws put (ip addres + region + compute.internal), like this:

```
NAME                                           STATUS   ROLES    AGE   VERSION
ip-192-168-0-74.sa-east-1.compute.internal     Ready    <none>   11d   v1.14.8-eks-b8860f
ip-192-168-36-60.sa-east-1.compute.internal    Ready    <none>   11d   v1.14.8-eks-b8860f
ip-192-168-39-156.sa-east-1.compute.internal   Ready    <none>   11d   v1.14.8-eks-b8860f
ip-192-168-76-196.sa-east-1.compute.internal   Ready    <none>   11d   v1.14.8-eks-b8860f
```

And what I want is anything like:
```
NAME     STATUS   ROLES    AGE   VERSION
NodeGroupA     Ready    <none>   11d   v1.14.8-eks-b8860f
NodeGroup A2     Ready    <none>   11d   v1.14.8-eks-b8860f
NodeGroup B     Ready    <none>   11d   v1.14.8-eks-b8860f
NodeGroup C     Ready    <none>   11d   v1.14.8-eks-b8860f
```

How I can do this?

OBS.: I tryed to follow this issue: https://github.com/weaveworks/eksctl/issues/1639 but I understand that this only rename in AWS Console and when I try to update the nodegroup, this error happen:

> Error: loading config file "nodegroups.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "instancePrefix"

**Comment by michaelbeaumont** [comment]
This is not possible at the moment. @cPu1 @martina-if
