### ISSUE TITLE
Support for Secrets Encryption

### ISSUE THREAD

**Issue by trevorrobertsjr** [weaveworks/eksctl#1895]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
AWS EKS Team launched support for secrets encryption using KMS keys. This can simplify users' secrets management. https://aws.amazon.com/blogs/containers/using-eks-encryption-provider-support-for-defense-in-depth/

**What feature/behavior/change do you want?**
Please add a flag for the eksctl create-cluster command to enable envelope encryption. If the customer provides a KMS key ARN, eksctl create-cluster should attempt to use that key. Otherwise, if no KMS key ARN is specified, and the flag is specified, eksctl create-cluster should create a new KMS key and use it with the encryption-config setting during EKS cluster creation.

Here is an example aws eks syntax I used to create a cluster with secrets encryption enabled:
```
$ aws eks create-cluster --name prod \
 --role-arn arn:aws:iam::123456789:role/eks-role \
 --resources-vpc-config subnetIds=subnet-1234567897436a,subnet-1234567899d92aa6,subnet-123456789cc43,securityGroupIds=sg-123456789db4d \
 **--encryption-config resources=secrets,provider={keyArn=arn:aws:kms:us-east-2:123456789:key/9f1e8669-1439-45c4-8b2b-123456789}**
```

Ideally, the two variants that I described above might look something like

`eksctl create cluster --name=mycluster --nodes=3 --managed --secretsencryption`

`eksctl create cluster --name=mycluster --nodes=3 --managed --secretsencryption=myARN`

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by cPu1** [comment]
This is out in [eksctl 0.15.0-rc.1](https://github.com/weaveworks/eksctl/releases/tag/0.15.0-rc.1)
