### ISSUE TITLE
China region delete cluster get delete IAM OIDC provider error message 

### ISSUE THREAD

**Issue by stevensu1977** [weaveworks/eksctl#1898]
**What happened?**
when I try delete my custer get  error message , I think may be because in china region IAM OIDC provider use "arn:aws-cn" not "arn:aws" as ARN prefix.

"eksctl delete cluster --name eksworkshop2 --region cn-northwest-1"

**How to reproduce it?**
just delete cluster,

**Anything else we need to know?**

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.15.0-rc.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

**Logs**
[ℹ]  eksctl version 0.15.0-rc.0
[ℹ]  using region cn-northwest-1
[ℹ]  deleting EKS cluster "eksworkshop2"
[ℹ]  either account is not authorized to use Fargate or region cn-northwest-1 is not supported. Ignoring error
[✔]  kubeconfig has been updated
[ℹ]  cleaning up LoadBalancer services
[ℹ]  2 sequential tasks: { delete IAM OIDC provider, delete cluster control plane "eksworkshop2" [async] }
[ℹ]  1 error(s) occurred while deleting cluster with nodegroup(s)
[✖]  deleting OIDC provider: InvalidInput: Incorrect ARN format arn:aws:iam::999999999:oidc-provider/oidc.eks.cn-northwest-1.amazonaws.com.cn/id/DC51867209DC11CFE32106F35C9EBA69
	status code: 400, request id: fadc05df-b200-44e0-9e68-2a34194cc0aa

**Comment by cPu1** [comment]
A potential fix for this issue is already in master. The fix will be out today with a a new RC.

**Comment by cPu1** [comment]
@stevensu1977 this should be fixed in https://github.com/weaveworks/eksctl/releases/tag/0.15.0-rc.1. Can you try it out and share the result?

**Comment by stevensu1977** [comment]
Sorry for late reply, it's fixed , I close this issue, thanks !
