### ISSUE TITLE
Cluster API CLI

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#19]
We would like to implement [Cluster API](https://github.com/kubernetes-sigs/cluster-api). One of the modes in which one can use Cluster API would be `eksctl apply -f cluster.yaml`, this would let users create and update clusters using a declarative format of a Cluster API object.
Another mode of using Cluster API would be via a controller running in a management cluster (#20).

**Comment by errordeveloper** [comment]
## What needs to be done here?

- [ ] `eksctl create cluster -f <configFile>` – #381
- [ ] `eksctl create  nodegroup -f <configFile>`
- [ ] `eksctl create -f <configFile>`
- [ ] `eksctl get/delete cluster -f <configFile>`
- [ ] `eksctl get/delete  nodegroup -f <configFile>`
- [ ] `eksctl get/delete -f <configFile>`
- [ ] `eksctl utils upgrade-{cluster,nodegroup} -f <configFile>` (in case we may need it as a temporary solution for upgrades, before we can implement fully idempotent `eksctl apply`)
- [ ] `eksctl apply -f <configFile>`

**Comment by mumoshu** [comment]
@errordeveloper It seems like we have `eksctl upgrade nodegroup` since #1566

**Comment by michaelbeaumont** [comment]
I suspect this issue isn't relevant anymore, there's already the [AWS provider](https://github.com/kubernetes-sigs/cluster-api-provider-aws/). We have an issue for declarative apply https://github.com/weaveworks/eksctl/issues/462

**Comment by michaelbeaumont** [comment]
Closing for now
