### ISSUE TITLE
[IRSA] Audience for aws-cn partition should be sts.amazonaws.com

### ISSUE THREAD

**Issue by walkley** [weaveworks/eksctl#1910]
**What happened?**
Failed to call below command in IRSA enabled pod in AWS China regions:
```
aws sts get-caller-identity
```
error message is 
```
Not authorized to perform sts:AssumeRoleWithWebIdentity
```

**What you expected to happen?**
IRSA should be work.

**How to reproduce it?**
Following official doc.

**Anything else we need to know?**
Most likely, this issue was introduced by PR #1877.
Actually, audience is a token rather than endpoint, which was set the eks-identity-webhook, the default value is sts.amazonaws.com

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.15.0-rc.1
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by cPu1** [comment]
Thanks for the hint. We couldn't test this in China since we don't have access there yet. We'll try to get  a fix out in the next release.

**Comment by walkley** [comment]
Thanks for the quick reply. Just ping me if you'd like to test or verify anything in AWS China regions, I'd happy to assist in that.
