### ISSUE TITLE
Doc: Incorrect URL in install instructions

### ISSUE THREAD

**Issue by dmacbride-ep** [weaveworks/eksctl#1915]
**What happened?**
The installation instructions at https://eksctl.io/introduction/installation/ do not work

**What you expected to happen?**
The instructions should work

**How to reproduce it?**
- Browse to https://eksctl.io/introduction/installation/
- try to perform the first step `curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp`

Result:
```
[ec2-user@mybox ~]$ curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Anything else we need to know?**
The cause is hte URL mentioned in the example command does not exist. The path https://github.com/weaveworks/eksctl/releases/download/latest does not exist.

**Comment by dmacbride-ep** [comment]
I'm working around it by downloading the following instead:
https://github.com/weaveworks/eksctl/releases/download/0.14.0/eksctl_Linux_amd64.tar.gz

**Comment by martina-if** [comment]
Hi @dmacbride-ep thanks for reporting this. This has already been fixed in master but we only deploy the website when we make a release, so this will be out when we release 0.15.0. You can check the correct instructions here:

https://github.com/weaveworks/eksctl/blob/master/site/content/introduction/02-installation.md

**Comment by shashlight** [comment]
It looks like this issue has resurfaced again? Looks like the URL is wrong. I'm getting the same error as the OP had reported.
FYI, I'm running Ubuntu 22.04 on my AWS EC2.

url --silent --location https://github.com/weaverworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz | tar xz -C /tmp

gzip: stdin: not in gzip format
tar: Child returned status 1
