### ISSUE TITLE
EKS 1.15 not supported

### ISSUE THREAD

**Issue by mbevc1** [weaveworks/eksctl#1927]
**What happened?**
When trying to run on EKS 1.15 using latest `eksctl`:
```Error: control plane version "1.15" is not known to this version of eksctl, try to upgrade eksctl first```

**What you expected to happen?**
Working `eksctl`.

**How to reproduce it?**
Bump EKS to 1.15 and use it.

**Anything else we need to know?**
Linux x86_64

**Versions**
Please paste in the output of these commands:
```
$ eksctl version = 0.15.rc1
$ kubectl version = 1.17
```

**Comment by cPu1** [comment]
Support for EKS 1.15 will be out in eksctl 0.15.0-rc.2, which will be out in a couple of hours. It's not supported in the version you're trying.

**Comment by mbevc1** [comment]
Thanks! Do we have a schedule for final release as well?

**Comment by cmacmurray** [comment]
Hey guys, thanks for the awesome response on this! This is how software development should be handled. 

C

**Comment by mbevc1** [comment]
Amazing response rc2 is already released :tada:
