### ISSUE TITLE
eksctl should issue a warning for attempted instanceType or AMI update to a nodegroup

### ISSUE THREAD

**Issue by doit-mattporter** [weaveworks/eksctl#1932]
Hi,

I am a senior cloud architect at DoiT International, and today I had a customer confused as to why his attempts to modify the instance types that can be used in an EKS nodegroup were not taking effect. He updated his cluster.yaml file, changing instanceTypes from ["c5.2xlarge", "c5n.2xlarge"] to ["c5.2xlarge"], then ran the following to make the change take effect:

eksctl update cluster --config-file=cluster.yaml

No change in instance type composition was seen in the cluster, and no errors or warnings were shown in the eksctl output. I was unable to find any documentation in AWS around this, and the eksctl output from running that command made no indication that there was an issue with the YAML. However, I did find in the eksctl documentation that AMI and instance types are immutable properties that cannot be changed for a nodegroup:

https://eksctl.io/usage/managing-nodegroups/ 

To avoid customer confusion on this point in the future, I think at a minimum the 'eksctl update cluster' command should print a warning message, if not throw an exception, when attempts to alter a cluster nodegroup's instance types or AMI is made, rather than outright ignore the requested change and print no messages out on the issue while continuing to deploy other changes made in the YAML.

**Comment by guysoft** [comment]
Getting issue here, no warning is shown:

```
$ eksctl update cluster --config-file=07-ssh-keys.yaml
[ℹ]  eksctl version 0.15.0-rc.2
[ℹ]  using region us-east-1
[!]  NOTE: config file is used for finding cluster name and region
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  re-building cluster stack "eksctl-shapedo-cluster"
[ℹ]  (plan) updating stack to add new resources [IngressDefaultClusterToNodeSG IngressNodeToDefaultClusterSG] and outputs [ClusterSecurityGroupId]
[ℹ]  checking security group configuration for all nodegroups
[ℹ]  all nodegroups have up-to-date configuration
```

**Comment by martina-if** [comment]
Hi @doit-mattporter and @guysoft,

Thanks for raising this issue. The `eksctl update cluster` command does not work as the kubectl update one. It's more of an upgrade. I think this command has been misnamed so it is quite confusing. I updated the help documentation for the command for now as renaming the command would be a breaking change.
