### ISSUE TITLE
NodeGroup Creation fails after eks k8s version upgrade to 1.15

### ISSUE THREAD

**Issue by ajayk** [weaveworks/eksctl#1933]
**What happened?**
NodeGroup Creation fails after eks k8s version upgrade to 1.15
**What you expected to happen?**
Nodegroup creation should create nodegroups 

**How to reproduce it?**
1. Create a cluster with eksctl 0.11.0 or below with k8s 1.14 with a nodegroup "my-first-worker"
2. Upgrade the cluster to 1.15 via aws console 
3. Upgrade the eksctl to the latest rc  `0.15.0-rc.2`
4. Create a new nodegroup "my-second-worker"

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
$ kubectl version
```

**Logs**

ℹ]  eksctl version 0.15.0-rc.2
[ℹ]  using region us-west-2
[ℹ]  will use version 1.15 for new nodegroup(s) based on control plane version
[ℹ]  1 nodegroup(s) that already exist (standard-worker-group-1) will be excluded
[ℹ]  nodegroup "standard-worker-2" will use "ami-000a48e69e7695a4a" [AmazonLinux2/1.15]
[ℹ]  using EC2 key pair "vpc-worker-production-us-west-2"
[ℹ]  1 nodegroup (standard-worker-2) was included (based on the include/exclude rules)
[ℹ]  combined exclude rules: standard-worker-group-1,standard-worker-group-1
[ℹ]  no nodegroups present in the current set were excluded by the filter
[ℹ]  will create a CloudFormation stack for each of 1 nodegroups in cluster "worker"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create nodegroup "standard-worker-2" } } }
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack is missing resources for Managed Nodegroups
[ℹ]  cluster stack is missing resources for Fargate
[ℹ]  adding missing resources to cluster stack
[ℹ]  re-building cluster stack "eksctl-worker-cluster"
[ℹ]  updating stack to add new resources [IngressDefaultClusterToNodeSG IngressNodeToDefaultClusterSG PolicyCloudWatchMetrics PolicyNLB ServiceRole] and outputs [ClusterSecurityGroupId]
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=us-west-2 --cluster=worker --name=<name>' for each of the failed nodegroup
[✖]  creating ChangeSet "eksctl-update-cluster-1584047536" for stack "eksctl-worker-cluster": ValidationError: Template error: Mapping named 'ServicePrincipalPartitionMap' is not present in the 'Mappings' section of template.
        status code: 400, request id: 40c8447a-0bd1-468b-a423-24837ddf0f62

**Comment by sayboras** [comment]
Based on the above error log, most likely the cluster got created without managed nodegroup and fargate support (i.e. 0.9 and before)

```
[ℹ] cluster stack is missing resources for Managed Nodegroups
[ℹ] cluster stack is missing resources for Fargate
```

**Comment by martina-if** [comment]
Exactly, there are certain resources not created by eksctl 0.11.0 that are needed later on. eksctl 0.14.0+ can handle the upgrade in a way that will update the CFN stacks so that all needed resources are there. 

It's always recommended to upgrade your cluster using `eksctl upgrade cluster` command. I think if you try that command with the latest version it will try to update your stacks.

**Comment by sayboras** [comment]
@martina-if I just tested it out with below steps. `update cluster` command helps to update stack partially, but not for iam related resource.

<details>
<summary>Create cluster with 0.9.0</summary>

```bash
# Create new cluster with 0.9
./eksctl create cluster                                                              
[ℹ]  eksctl version 0.9.0
[ℹ]  using region us-east-2
[ℹ]  setting availability zones to [us-east-2b us-east-2a us-east-2c]
[ℹ]  subnets for us-east-2b - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for us-east-2a - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for us-east-2c - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng-a39e1766" will use "ami-082bb518441d3954c" [AmazonLinux2/1.14]
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster "fabulous-mushroom-1584086711" in "us-east-2" region
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-2 --cluster=fabulous-mushroom-1584086711'
[ℹ]  CloudWatch logging will not be enabled for cluster "fabulous-mushroom-1584086711" in "us-east-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-east-2 --cluster=fabulous-mushroom-1584086711'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "fabulous-mushroom-1584086711" in "us-east-2"
[ℹ]  2 sequential tasks: { create cluster control plane "fabulous-mushroom-1584086711", create nodegroup "ng-a39e1766" }
[ℹ]  building cluster stack "eksctl-fabulous-mushroom-1584086711-cluster"
[ℹ]  deploying stack "eksctl-fabulous-mushroom-1584086711-cluster"
[ℹ]  building nodegroup stack "eksctl-fabulous-mushroom-1584086711-nodegroup-ng-a39e1766"
[ℹ]  --nodes-min=2 was set automatically for nodegroup ng-a39e1766
[ℹ]  --nodes-max=2 was set automatically for nodegroup ng-a39e1766
[ℹ]  deploying stack "eksctl-fabulous-mushroom-1584086711-nodegroup-ng-a39e1766"
[✔]  all EKS cluster resources for "fabulous-mushroom-1584086711" have been created
[✔]  saved kubeconfig as "/home/tammach/.kube/config"
[ℹ]  adding identity "arn:aws:iam::363193625107:role/eksctl-fabulous-mushroom-15840867-NodeInstanceRole-O6DJ6DJFUN5N" to auth ConfigMap
[ℹ]  nodegroup "ng-a39e1766" has 0 node(s)
[ℹ]  waiting for at least 2 node(s) to become ready in "ng-a39e1766"
[ℹ]  nodegroup "ng-a39e1766" has 2 node(s)
[ℹ]  node "ip-192-168-35-6.us-east-2.compute.internal" is ready
[ℹ]  node "ip-192-168-4-30.us-east-2.compute.internal" is ready
[ℹ]  kubectl command should work with "/home/tammach/.kube/config", try 'kubectl get nodes'
[✔]  EKS cluster "fabulous-mushroom-1584086711" in "us-east-2" region is ready
```

</details>

<details>
<summary> run update cluster </summary>

```bash
# Update cluster with lastest version
./eksctl update cluster fabulous-mushroom-1584086711 --approve
[ℹ]  eksctl version 0.15.0-rc.2
[ℹ]  using region us-east-2
[ℹ]  will upgrade cluster "fabulous-mushroom-1584086711" control plane from current version "1.14" to "1.15"
[✔]  cluster "fabulous-mushroom-1584086711" control plane has been upgraded to version "1.15"
[ℹ]  you will need to follow the upgrade procedure for all of nodegroups and add-ons
[ℹ]  re-building cluster stack "eksctl-fabulous-mushroom-1584086711-cluster"
[ℹ]  updating stack to add new resources [IngressDefaultClusterToNodeSG IngressNodeToDefaultClusterSG] and outputs [ClusterSecurityGroupId]
[ℹ]  checking security group configuration for all nodegroups
[ℹ]  all nodegroups have up-to-date configuration
```

</details>

<details>
<summary> Perform any action which triggers some IAM changes in cluster stack </summary>

```
# Perform any action which triggers some IAM change in cluster stack
./eksctl create fargateprofile --cluster fabulous-mushroom-1584086711 --namespace dev
[ℹ]  Fargate pod execution role is missing, fixing cluster stack to add Fargate resources
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack is missing resources for Fargate
[ℹ]  adding missing resources to cluster stack
[ℹ]  re-building cluster stack "eksctl-fabulous-mushroom-1584086711-cluster"
[ℹ]  updating stack to add new resources [FargatePodExecutionRole] and outputs [FargatePodExecutionRoleARN]
Error: error fixing cluster compatibility: creating ChangeSet "eksctl-update-cluster-1584088419" for stack "eksctl-fabulous-mushroom-1584086711-cluster": ValidationError: Template error: Mapping named 'ServicePrincipalPartitionMap' is not present in the 'Mappings' section of template.
	status code: 400, request id: ca8213c3-f63e-4b43-bf13-4f329bf16090
```

</details>

it's failing for the same reason
```
Error: error fixing cluster compatibility: creating ChangeSet "eksctl-update-cluster-1584088419" for stack "eksctl-fabulous-mushroom-1584086711-cluster": ValidationError: Template error: Mapping named 'ServicePrincipalPartitionMap' is not present in the 'Mappings' section of template.
	status code: 400, request id: ca8213c3-f63e-4b43-bf13-4f329bf16090
```
