### ISSUE TITLE
Amazon EKS now available in Ireland but not supported

### ISSUE THREAD

**Issue by KevinMonk** [weaveworks/eksctl#194]
**What happened?**
Amazon EKS is now available in Ireland but [this line is preventing eksctl from creating a cluster in the eu-west-1 region](https://github.com/weaveworks/eksctl/blob/33a7d24db7e68fa337cf967bcf3ae13ddeffe585/cmd/eksctl/create.go#L123).

**What you expected to happen?**
To be able to create a cluster in eu-west-1

**How to reproduce it?**
Try to create a cluster in eu-west-1

    eksctl create cluster --region=eu-west-1

**Anything else we need to know?**
Nope.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
2018-09-06T22:55:44+01:00 [ℹ]  versionInfo = map[string]string{"gitTag":"0.1.1", "builtAt":"2018-08-31T14:39:24Z", "gitCommit":"0578d6cd44d8c5a4ebe17825db882ad194f0bee4"}

$ uname -a
Darwin Kevins-MBP-2017 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```
eksctl create cluster --region=eu-west-1                                     
2018-09-06T22:16:26+01:00 [✖]  --region=eu-west-1 is not supported only us-west-2 and us-east-1 are supported
```

**Comment by richardcase** [comment]
@KevinMonk - thanks for raising the issue. Support for  Ireland (eu-west-1) is being worked as part of #189.

**Comment by errordeveloper** [comment]
@saily yes, the 0.1.2 release will be out shortly. I'm running the integration tests now, and all goes well (it should!), there will be binaries within the next hour.
