### ISSUE TITLE
AMI not automatically detected by default

### ISSUE THREAD

**Issue by otterley** [weaveworks/eksctl#1942]
It looks like eksctl still defaults to its static AMI list, which has not yet been updated for EKS 1.15:

```
Error: unable to determine AMI to use: unable to determine AMI for region us-west-2, version 1.15, instance type m5.large and image family AmazonLinux2
```

Is there some reason why `--node-ami=auto` is not yet the default?  I believe that the search order should be user-provided, then Parameter Store, then EC2 AMI search pattern, then static.  It doesn't appear to be that way today.

@cPu1 thoughts?

**Comment by cPu1** [comment]
Static resolution is no longer the default. If an AMI resolution strategy isn't specified, SSM Parameter Store is used. This is detailed here: https://github.com/weaveworks/eksctl/issues/1793

> I believe that the search order should be user-provided, then Parameter Store, then EC2 AMI search pattern, then static

That's the current behaviour.

Could you share the command/config for which you got the error? If you're still able to reproduce it, could you enable debug logging (by passing `-v4`) and share the output?

I just tested this using the parameters from your error message and it correctly chose SSM Parameter Store for resolving the AMI:

```shell
$ eksctl create cluster --node-type=m5.large --version=1.15 --region us-west-2 -v4
eksctl version 0.15.0                                                                                                                                           
using region us-west-2                                                                                                                                          
resolving AMI using SSM Parameter resolver for region us-west-2, instanceType m5.large and imageFamily AmazonLinux2                                             
nodegroup "ng-f5ff5d4f" will use "ami-000a48e69e7695a4a" [AmazonLinux2/1.15]                                                                                    
using Kubernetes version 1.15                                                                                                                                                                                                                                                                                                   
```

**Comment by otterley** [comment]
This was an error on my part - I was using the 0.14.0 release by mistake.  Closing as invalid.
