### ISSUE TITLE
Support for ARM nodes

### ISSUE THREAD

**Issue by kalbir** [weaveworks/eksctl#1949]
The A1 arm nodes are in [developer preview](https://github.com/aws/containers-roadmap/tree/master/preview-programs/). We would like to add the ability for `eksctl` to provision clusters with ARM nodes. 

At the moment there is a manual set of steps you need to achieve this: https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-arm-preview

More about Amazon A1 instances: https://aws.amazon.com/ec2/instance-types/a1/\

Linked ticket on AWS Container Roadmap: https://github.com/aws/containers-roadmap/issues/605

**Comment by martina-if** [comment]
related #1832
