### ISSUE TITLE
Add support for service linked role

### ISSUE THREAD

**Issue by kalbir** [weaveworks/eksctl#1950]
EKS will automatically provision a managed IAM role (Service Linked Role) during cluster creation. This makes it simpler and faster to setup an EKS cluster.

We will change `eksctl` behaviour so that we don't overdetermine IAM roles at cluster creation.

Linked to issue on AWS Container Roadmap: https://github.com/aws/containers-roadmap/issues/243

**Comment by sayboras** [comment]
Saw this one on my aws-feed today https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-eks-supports-service-linked-roles/ :tada:

**Comment by cPu1** [comment]
Fixed in #2079
