### ISSUE TITLE
`eksctl delete cluster` fails if a LoadBalancer service's backing ELB is still being deleted

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#1960]
**What happened?**
`eksctl delete cluster` fails if a `LoadBalancer` service is deleted via the Kubernetes API (e.g., kubectl) right before deleting the cluster, and the service's backing ELB is still being deleted.

**What you expected to happen?**
For `eksctl delete cluster` to delete all resources.

**How to reproduce it?**
On a cluster with a `LoadBalancer` service, delete the service (`kubectl delete svc <name>`) and immediately try deleting the cluster via `eksctl delete cluster`. If the ELB for the `LoadBalancer` is still being deleted, eksctl tries to delete the associated security group and that fails with a `DependencyViolation` error.

**Versions**
```
$ eksctl version
0.15.0
```

**Logs**

```shell
$ eksctl delete cluster cleanup-test
...
deleting Load Balancer Security Group orphans
deleting orphan Load Balancer security group sg-<redacted> with description "Security group for Kubernetes ELB <redacted> (default/svc)"
Error: cannot delete orphan ELB Security Groups: cannot delete security group k8s-elb-<redacted>: DependencyViolation: resource sg-<redacted> has a dependent object
	status code: 400
...

**Comment by martina-if** [comment]
Fixed if we fix #1070
