### ISSUE TITLE
List of IAM policies required for full use of tool

### ISSUE THREAD

**Issue by nbrandaleone** [weaveworks/eksctl#1961]
Hello,

It would be useful to know what IAM roles are required for the tool to work properly. Clearly, the ability to list/create/delete EKS clusters are necessary.  However, there is probably a reliance on LoadBalancers, EC2 and perhaps other resources.

I would like to build a minimal set of permissions for security purposes.  If you would document said permissions/roles, it would be appreciated and valued by the community.

**Comment by sayboras** [comment]
@nbrandaleone You can try to run eksctl in your account with default options such as `eksctl create cluster`. If the cluster created successfully, then you can easily extract list of policies or API calls from cloudtrail. 

This is the general appoach that I use daily.

I just created one cluster with `eksctl create cluster --version=1.15`, and below is the list of API calls that I got. Kindly note that different params/inputs might require one or few more permissions.

- AddRoleToInstanceProfile
- AllocateAddress
- AssociateRouteTable
- AttachInternetGateway
- AttachRolePolicy
- AuthorizeSecurityGroupEgress
- AuthorizeSecurityGroupIngress
- CreateAutoScalingGroup
- CreateCluster
- CreateInstanceProfile
- CreateInternetGateway
- CreateLaunchTemplate
- CreateNatGateway
- CreateRole
- CreateRoute
- CreateRouteTable
- CreateSecurityGroup
- CreateStack
- CreateSubnet
- CreateTags
- CreateVpc
- DeleteStack
- DescribeAutoScalingGroups
- DescribeAvailabilityZones
- DescribeCluster
- DescribeImages
- DescribeKeyPairs
- DescribeScalingActivities
- DescribeSecurityGroups
- DescribeStacks
- DescribeStacks
- DescribeSubnets
- DescribeVpcs
- GetCallerIdentity
- GetInstanceProfile
- GetOpenIDConnectProvider
- GetParameter
- GetRole
- GetRolePolicy
- GetStackPolicy
- GetTemplate
- ListFargateProfiles
- ListStackResources
- ListStacks
- ModifyVpcAttribute
- PutRolePolicy
- RevokeSecurityGroupEgress
- RevokeSecurityGroupIngress
- RunInstances
- TagRole
- UpdateAutoScalingGroup

**Comment by martina-if** [comment]
Hi @nbrandaleone, there is now [a page in the docs](https://eksctl.io/usage/minimum-iam-policies/) that keeps a minimal set of permissions needed by eksctl.
