### ISSUE TITLE
Tidy up logic related to infrastructure, build, release, distribution, et al.

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1980]
**Why do you want this feature?**

At the moment, we have logic related to infrastructure, build, Docker, release and distribution scattered a bit everywhere, which makes it rather difficult for anyone to find their way through it, know what is used or not, etc.:

```
.build_image.iid
.build_image_context
.build_image_manifest
.circleci
.docker
.eksctl_image.iid
.github
.golangci.yml
.goreleaser-local.yaml
.goreleaser.brew.yml
.goreleaser.yml
.license-header
.requirements
Dockerfile
Makefile
Makefile.common
Makefile.docker
build-image-manifest.sh
do-release-candidate.sh
do-release.sh
eksctl-image-builder.sh
hack/deploy-many-workloads.sh
hack/dump-coredns-manifests.sh
hack/dump-default-addons.sh
hack/run-integration-tests.sh
install-build-deps.sh
snap
tag-release-candidate.sh
tag-release.sh
tools
tools.go
```

**What feature/behavior/change do you want?**

Except for logic which absolutely has to follow some specific convention (e.g. `.circleci`, `.github`, etc.),  moving all logic to some directory (e.g. `build`), structuring all logic & scripts there, and removing single files & semantically weak directories (e.g. `hack`) would probably make it easier to navigate & maintain this logic.

For example:
```
build
|- debug
|- dependencies
|  |- install-build-deps.sh
|  `- [...]
|- dev
|- generate
|- licenses
|  |- license-header
|  `- [...]
|- release
|  |- snap
|  |- scripts
|  |  |- do-release-candidate.sh
|  |  |- do-release.sh
|  |  |- tag-release-candidate.sh
|  |  `- tag-release.sh
|  `- goreleaser
|     |- goreleaser-local.yaml
|     |- goreleaser.brew.yml
|     `- goreleaser.yml
`- docker
   `- [...]
```

**Comment by michaelbeaumont** [comment]
Tidied
