### ISSUE TITLE
Fail to build the build image

### ISSUE THREAD

**Issue by sayboras** [weaveworks/eksctl#1987]
**What happened?**
Failed to run `make eks-image`

**What you expected to happen?**
Docker build should be successful.

**How to reproduce it?**
Run `make eksctl-image`

**Logs**

```
Step 12/13 : RUN go install github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator     && mv $GOPATH/bin/aws-iam-authenticator /out/usr/local/bin/aws-iam-authenticator
 ---> Running in 90eb7cf56c5f
go: finding github.com/kubernetes-sigs/aws-iam-authenticator v0.5.0
go: downloading github.com/kubernetes-sigs/aws-iam-authenticator v0.5.0
go: extracting github.com/kubernetes-sigs/aws-iam-authenticator v0.5.0
go: github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator: github.com/kubernetes-sigs/aws-iam-authenticator@v0.5.0: parsing go.mod:
	module declares its path as: sigs.k8s.io/aws-iam-authenticator
	        but was required as: github.com/kubernetes-sigs/aws-iam-authenticator
```

**Comment by abdennour** [comment]
Hello @sayboras  , 

We have already provided [eksctl in container image](https://hub.docker.com/repository/docker/abdennour/eksctl) with two flavors :

- eksctl + aws CLI :  `docker pull abdennour/eksctl:0.16.0-aws-1.18.31`
- eksctl + aws CLI + kubectl : `docker pull abdennour/eksctl:0.16.0-aws-1.18.31-kubectl-v1.17.4`

**Comment by sayboras** [comment]
Thanks for your comment @abdennour. Good to know that you have maintained eksctl docker images. This is great alternative option to _run_ eksctl.

However, the underlying issue is to build the `build docker image`, which is used in CI to _compile_ eksctl binaries.
