### ISSUE TITLE
Add-ons for spot instances

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#199]
Once we have support for spot instances (#198), we should consider a few add-ons that make better use of spot instances.

I am aware for these few by @Pusher (cc @JoelSpeed & @gargath):

- https://github.com/pusher/k8s-spot-price-monitor
- https://github.com/pusher/k8s-spot-rescheduler
- https://github.com/pusher/k8s-spot-termination-handler

**Comment by whereisaaron** [comment]
Looks good. The `k8s-spot-termination-handler` works just like @mumoshu's `kube-aws` script.

**Comment by martina-if** [comment]
Ideally, these could be implemented as gitops profiles.
