### ISSUE TITLE
Retaining environment variables when using update-aws-node

### ISSUE THREAD

**Issue by andrew-ha** [weaveworks/eksctl#1993]
Reopening GitHub issue #933 

Re-opening this issue, as multiple customers looking for this feature and if this request is implemented, it will help all EKS customers who performs "update-aws-node" with environment variables set. 

I would suggest you to please have a look in ideas provided by @dschunack i.e use a configmap maybe for the ENV parameter or you can use the patch command.

**Comment by aclevername** [comment]
closing due to staleness. Feel free to re-open if this is still an issue

**Comment by eatwithforks** [comment]
I'm also running into this issue. Ideally, ClusterConfig addon's should take in environment variable configurations to eliminate a manual step after cluster creation to edit CNI's daemonset with environment variable updates such as WARM_PREFIX_TARGET.
