### ISSUE TITLE
Applying security patches on unmanaged nodes

### ISSUE THREAD

**Issue by tahirali-endurance** [weaveworks/eksctl#2001]
For unmanaged nodes(i.e. created by eksctl), how one can install security patches or any other custom upgrades. We found : https://github.com/weaveworks/eksctl/issues/348. Based on this, do we have to recreate the nodes groups every time if we want to patch any changes on worker nodes?

**Comment by martina-if** [comment]
Hi @tahirali-endurance, you are correct, to upgrade the un-managed nodegroups you need to recreate them. That's why we recommend using managed nodegroups instead. With those you can use `eksctl upgrade nodegroup`.
