### ISSUE TITLE
Unable to recreate cluster on failure from CLI

### ISSUE THREAD

**Issue by JonnyWaffles** [weaveworks/eksctl#2005]
Hi friends,

I attempted to create a cluster following the tutorial documentation. However, due to VPC resource constraints creation failed. I removed some old resources and attempted to create the cluster once more, but unfortunately the cloud formation stack with the same name already exists. I figure, okay I will just delete it and re-create it, but I cannot delete or update commands fail as the cluster was never successfully was created in the first place. 

It appears my only option is to delete the cloud formation templates create by the create command and then try again. Not sure if there is a more elegant solution?

**Comment by sayboras** [comment]
Based on my understanding, there is no other option :)

**Comment by martina-if** [comment]
Hi @JonnyWaffles , thank you for reporting this. That's correct, at the moment eksctl doesn't support continuation. That's something that would be very useful and we have a feature request issue to build something like this (https://github.com/weaveworks/eksctl/issues/188).
