### ISSUE TITLE
get -o yaml to return the exact yaml used to create the object

### ISSUE THREAD

**Issue by joshkurz** [weaveworks/eksctl#2018]
I would like to be able to run `eksctl get nodegroup -o yaml foo-bar` and get the exact yaml that was used to create the `foo-bar` nodegroup. Same goes for any resource created by `eksctl`. 

I have dug into the code a bit to try to send a PR for this. Getting stuck in a few places and was looking from guidance, suggestions. 

At first, I wanted to lookup the information in cloudformation, and replicate it back to the original YAML. After digging into the code, I am not sure if there is a straightforward way to achieve this, without lots of conditions and parsing involved. I would rather not go that route, as i'm sure it will get outdated quick and need to constantly be updated. I thought I would be able to get the CF template from the nodegroup and marshal it into a nodegroup object. I am stumbling here a bit. If you think this should be achievable let me know.

I had another idea that I was curious what your thoughts were. What if, when eksctl creates an object, eksctl creates a new object on the k8s cluster we are updating. So we would create a new CRD, `eksctl_$resource`. This object could then just be returned when a user wants to get it. This would allow for a nice way to store all the resources that have been created by eksctl.

So really I just want `eksctl get` to actually return the object yaml that I used to create the object. The nodegroup summary is not really helpful. Any assistance here would be great. I am happy to send a PR for this. Just want to make sure I am headed in the right direction.

**Comment by martina-if** [comment]
Hi @joshkurz , this would indeed be very useful. We have a couple of related/dup issues:

https://github.com/weaveworks/eksctl/issues/642
https://github.com/weaveworks/eksctl/issues/633

The thing is that as you point out, regenerating the ClusterConfig is currently very tricky so it would be a great deal of work. Most likely this will be tackled when the `eksctl apply` command is implemented. I will close this as a duplicate but thanks a lot for the investigation and the detailed explanation, this is very helpful. This will be cross-linked to the other issues but closed for now as dup if that's ok.
