### ISSUE TITLE
Cluster update from config file?

### ISSUE THREAD

**Issue by danil-smirnov** [weaveworks/eksctl#2038]
Hi,

I failed to find an answer in the documentation.

Is the config yaml true Inrastructure-as-code component?

Is it possible to change it and re-apply changes to existing cluster?

Or one must use CLI tool for any changes instead of the config?

This should be probably mentioned somewhere in the docs...

**Comment by dylanenabled** [comment]
It's not really Infrastructure as code in the sense of Cloudformation is. It doesn't calculate changesets and apply them automatically. In fact as far as I can tell most resources can't actually be edited in the config (ie, nodegroups), you just need to make new definitions and create that on the cli, then delete the old one.

Really all the config file does is populate arguments on the cli for you (like cluster name, region, and any settings for nodegroups etc). 

You still need to run the appropriate cli command (like create nodegroup) to actually do something.

**Comment by danil-smirnov** [comment]
Well, if it "populate arguments on the cli" for `cluster create` command why it can't do the same for another command, i.e. check nodegroup nodes parameter in the file and run appropriate command for me to scale the group?

Anyway, current yaml config file usage is quite confusing as it's immutable (while still editable) which should be definitely addressed in the docs.

**Comment by martina-if** [comment]
Hi @danil-smirnov , thank you, this is valuable feedback. I think @dylanenabled  explained it well.

Updating a cluster is something that was planned a long time ago but for different reasons, including its complexity, it hasn't been tackled yet. 
This is tracked here https://github.com/weaveworks/eksctl/issues/462
