### ISSUE TITLE
List Supported K8s Versions

### ISSUE THREAD

**Issue by shivasuri** [weaveworks/eksctl#2040]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
A clear and concise description of why you want this feature. Include use-cases and any specific constraints you may have.

Dynamically creating clusters for daily builds across several k8s versions.

**What feature/behavior/change do you want?**
A clear and concise description of the change you would like to see in eksctl.

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

Just something as simple as `eksctl list-k8s-versions`

**Comment by shivasuri** [comment]
here is a hacky way to get the list for anyone who wants it: `echo $(eksctl create cluster --version invalid 2>&1) | rev | sed 's/ //g' | cut -d ":" -f-1 | rev`

**Comment by smrutiranjantripathy** [comment]
I'm doing research on this issue. Would be submitting PR. (WIP)

**Comment by sayboras** [comment]
> `eksctl get supportedk8sversions` and maintaining the supported versions in a file in the repository. Please suggest your opinion on this approach.

For your list of supported version, you can refer to https://github.com/weaveworks/eksctl/blob/master/pkg/apis/eksctl.io/v1alpha5/types.go#L297.

For the command, in my opinion existing `eksctl version` can be used to show supported kube versions (e.g. breaking down by eksctl client version and EKS server supported version)

**Comment by smrutiranjantripathy** [comment]
I have raised a PR. Kindly take a look and provide feedback.
