### ISSUE TITLE
Remove dependency on aws authenticator binary

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#2042]
(related to #1109 ?)

## Cases:
- old eksctl using a newer AMI -> this will break unless the ssm url is changed (like v2 or something). They probably don't want to do this.
- What happens with the Ubuntu AMIs? (we think this is only for AL2)

## TODO afterwards:
- consider migrating to the supported bootstrap scripts instead of our custom one. If we had been using the official script we wouldn't have this situation of breaking AMIs

**Comment by cPu1** [comment]
Fixed in #2063
