### ISSUE TITLE
NVIDIA GPU driver add-on

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#205]
This is a follow-up to #183. We should make it very easy to enable GPUs end-to-end, the flag should probably be something like `--addon=nvidia-gpu`. But we will need to enable add-ons first (see #17 & #18).

**Comment by arun-gupta** [comment]
@errordeveloper Any updates on this?

I'll be talking about this more actively in the coming weeks/months and so a simplified set of steps would be very useful.

**Comment by errordeveloper** [comment]
@arun-gupta we'd like to have proper framework for add-ons in place for this, it's on the roadmap but due to the demand for config file support we haven't had a chance to move #242 along. Have you tried using a Helm chart for this?

**Comment by arun-gupta** [comment]
Subscribed to that issue. Not sure how Helm chart would help.

**Comment by michaelbeaumont** [comment]
`eksctl` already installs the device plugin when a gpu enabled nodegroup is created.
