### ISSUE TITLE
Eksctl 0.17 not creating nodes

### ISSUE THREAD

**Issue by neels-synthesis** [weaveworks/eksctl#2051]
**What happened?**
I tried creating an eksctl cluster with this piece of ansible: 
```
- name: Create cluster and create kubeconfig
  shell: eksctl create cluster --kubeconfig {{ role_path }}/files/kubeconfig -f {{ role_path }}/files/cluster.yml
```
and got the following error:
```
[ℹ]  nodegroup "workers" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "workers"
Error: timed out (after 25m0s) waiting for at least 1 nodes to join the cluster and become ready in "workers"
```
There is no nodegroup on the aws console, but the ec2 instances exist

**What you expected to happen?**
There to be a nodegroup and for instances to connect to the cluster
**How to reproduce it?**
Ran `eksctl create cluster -f cluster.yml` [this file](https://gist.github.com/neels-synthesis/575a278b1540c8323bf600abae59637f)

**Anything else we need to know?**
Using Manjaro linux with eksctl 0.17 binary from the website, regular AWS account with no MFA.

**Versions**
```
❯ eksctl version
0.17.0

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"archive", BuildDate:"2020-02-29T16:37:45Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
https://imgur.com/tIc2l2q

**Comment by sayboras** [comment]
@neels-synthesis can you share your config here? Not sure if you are using exsiting vpc or not, normally this issue happens if worker node is unable to join cluster.

**Comment by neels-synthesis** [comment]
@sayboras in the gist file above, [here you go](https://gist.github.com/neels-synthesis/575a278b1540c8323bf600abae59637f)

**Comment by sayboras** [comment]
Please help to check this [docs](https://eksctl.io/usage/vpc-networking/) if all conditions are met.

> - all subnets in the same VPC, within the same block of IPs
> - sufficient IP addresses are available
> - sufficient number of subnets (minimum 2)
> - internet and/or NAT gateways are configured correctly
> - routing tables have correct entries and the network is functional
> - tagging of subnets
> kubernetes.io/cluster/<name> tag set to either shared or owned
> kubernetes.io/role/internal-elb tag set to 1 for private subnets
> NEW: all public subnets should have the property MapPublicIpOnLaunch enabled (i.e. Auto-assign public IPv4 address in the AWS console)

**Comment by neels-synthesis** [comment]
All of the above boxes are ticked. Let me also add that creating a cluster with the exact same configuration using Rancher works properly, as well as via CloudFormations, it's just failing with eksctl

**Comment by myidalias** [comment]
furthermore, we have used the EXACT SAME CONFIG PREVIOUSLy...and it worked previously.
now it doesn't!

**Comment by alfalavi** [comment]
please make sure that all public subnets have "Auto-assign IPv4" enabled. Even though nodes were located in private subnets they were able to join cluster after these changes and were not able to join with "Auto-assign IPv4" setting disabled.
I think that another workaround is to rollback eksctl to previous version but didn't check it yet.

**Comment by myidalias** [comment]
re: version...it also yields the same result with eksctl version 0.13.0

**Comment by deoxyseia** [comment]
> Please help to check this [docs](https://eksctl.io/usage/vpc-networking/) if all conditions are met.
> 
> > * all subnets in the same VPC, within the same block of IPs
> > * sufficient IP addresses are available
> > * sufficient number of subnets (minimum 2)
> > * internet and/or NAT gateways are configured correctly
> > * routing tables have correct entries and the network is functional
> > * tagging of subnets
> >   kubernetes.io/cluster/ tag set to either shared or owned
> >   kubernetes.io/role/internal-elb tag set to 1 for private subnets
> >   NEW: all public subnets should have the property MapPublicIpOnLaunch enabled (i.e. Auto-assign public IPv4 address in the AWS console)

The last one (MapPublicIpOnLaunch enabled) works for me too. It's confused why I could upgrade a nodegroup and control plane from 1.14 to 1.15 without enable it, but is not possible to deploy new cluster node with a new control plane.

**Comment by cPu1** [comment]
The timeout error suggests that the private subnets may not have a route to a NAT gateway. Can 
you confirm this? Without a NAT gateway, the nodes will be unable to pull the CNI and kube-proxy etc, thereby preventing them from joining the cluster. 

Have you been able to create nodegroups before with the same config using an older version of eksctl? 

FWIW, you have `vpc.nat.gateway` set to `Disable`, but when specifying a custom VPC, that setting is not read. It's only for when eksctl creates a dedicated VPC.

**Comment by cPu1** [comment]
> furthermore, we have used the EXACT SAME CONFIG PREVIOUSLY...and it worked previously.
> now it doesn't!

Which version of eksctl was working with the same config? Does it still work with that version? Please share any additional details about how your subnets, routing tables and NAT gateway (if any) are set up.

**Comment by deoxyseia** [comment]
@cPu1 even the nodes in public subnets fail to join the cluster.

**Comment by cPu1** [comment]
> The timeout error suggests that the private subnets may not have a route to a NAT gateway. Can
> you confirm this? Without a NAT gateway, the nodes will be unable to pull the CNI and kube-proxy etc, thereby preventing them from joining the cluster.
> 
> Have you been able to create nodegroups before with the same config using an older version of eksctl?
> 
> FWIW, you have `vpc.nat.gateway` set to `Disable`, but when specifying a custom VPC, that setting is not read. It's only for when eksctl creates a dedicated VPC.

@neels-synthesis are you able to provide this information? Can you check if the latest eksctl version works for you?

**Comment by cPu1** [comment]
> @cPu1 even the nodes in public subnets fail to join the cluster.

Are you still facing this issue with 0.19 (or 0.20 RC)? Can you share your VPC and subnet settings, and nodegroup config?

**Comment by martina-if** [comment]
@neels-synthesis I am closing this since it's inactive and we cannot reproduce it. It is very tricky for us to troubleshoot clusters when the VPC is imported. Please reopen it if you manage to get more info that we can use to help out.
