### ISSUE TITLE
Recover the 404 template for the website

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#2061]
The old site had a 404 template. I think the new site that uses mkdocs should have a nice 404 page as well.

**Comment by dholbach** [comment]
Hum... not sure what to bring back again? This is what the new page should look like, vs right now: https://eksctl.io/missing

![Screenshot from 2020-04-21 16-15-23](https://user-images.githubusercontent.com/1346979/79876464-5f70c280-83eb-11ea-88f8-be6ef83cdca1.png)

**Comment by dholbach** [comment]
You can see it working right now at e.g. https://deploy-preview-2056--eksctl.netlify.app/missing

To me this looks fine, no?

**Comment by martina-if** [comment]
Yeah, that looks great, thanks! :D
