### ISSUE TITLE
default azs used is 2 not 3

### ISSUE THREAD

**Issue by pdeva** [weaveworks/eksctl#2073]
**What happened?**
The [docs](https://eksctl.io/usage/vpc-networking/) says eksctl will use 3 availability zones to create subnets with 3 public and 3 private subnets

> By default, eksctl create cluster will build a dedicated VPC, in order to avoid interference with any existing resources for a variety of reasons, including security, but also because it’s challenging to detect all the settings in an existing VPC. Default VPC CIDR used by eksctl is 192.168.0.0/16, it is divided into 8 (/19) subnets (3 private, 3 public & 2 reserved).

However, I get this:

```
eksctl create cluster
[ℹ]  eksctl version 0.17.0
[ℹ]  using region us-east-1
[ℹ]  setting availability zones to [us-east-1b us-east-1f]
```

only 2 az are used and 2 public and 2 private subnets are created. no reserved subnets are created either.

**What you expected to happen?**
should create 3 private, 3 public & 2 reserved subnets as described in docs

**How to reproduce it?**
run `eksctl create cluster`

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version 0.17.0
$ kubectl version 0.15.0
```

**Comment by martina-if** [comment]
Hi @pdeva, Thank you for reporting this. This is a known behavior of eksctl, see https://github.com/weaveworks/eksctl/commit/f450f5f4543e8da77c14a224b4c7b82bc6f51304

and 

https://github.com/weaveworks/eksctl/pull/294

Perhaps it would be good to update the docs with this exception.
