### ISSUE TITLE
Private-only endpoint fails for pure Fargate setup with transit gateways

### ISSUE THREAD

**Issue by AMALCGCG** [weaveworks/eksctl#2074]
**What happened?**
We have a configuration where we use transit gateways to communicate from otherwise private subnets. This allows the EKS control plane to communicate with the Fargate scheduler, and so we can spin up EKS clusters that have private-only endpoints visible only on our intranet.

**What you expected to happen?**
For our network topology, and a Fargate-only configuration, the following ClusterConfig options should pass validation:

```
vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
```

**Versions**
- eksctl version: 0.17.0
- kubectl version: v1.18.2

**Logs**
We get a validation failure, which is triggered from validation.go, line 119:

```
if PrivateOnly(endpts) {
  return ErrClusterEndpointPrivateOnly
}
```

**Anything else we need to know?**
When we patch the code to ignore that validation check, the cluster is created successfully and actually works perfectly. Our patch keeps the validation check, but only fails if there are node groups present. Thus it works for our (pure Fargate) setup. Updated validation.go, line 119:

```
if PrivateOnly(endpts) && len(c.NodeGroups) > 0 {
  return ErrClusterEndpointPrivateOnly
}
```

**Comment by sayboras** [comment]
Seems to be related to existing PR https://github.com/weaveworks/eksctl/pull/2071
