### ISSUE TITLE
cert-manager addon instance permissions has an unneeded permission

### ISSUE THREAD

**Issue by TBBle** [weaveworks/eksctl#2077]
**What happened?**

The instance role created by the cert-manager addon includes `route53:ListHostedZones`, however the cert-manager documentation does not list this as required.

**What you expected to happen?**

The addon permissions match the upstream documentation, or a bug is filed against the upstream documentation.

**How to reproduce it?**

Inspect [eksctl source](https://github.com/weaveworks/eksctl/blob/32027355678915365c68053e9293900b951cbc04/pkg/cfn/builder/iam_helper.go#L55) and compare with [the upstream documentation](https://cert-manager.io/docs/configuration/acme/dns01/route53/#set-up-a-iam-role).

I did this while I was attempting to recreate the same permissions using IRSA, to make sure I was reading/parsing it all correctly.

_It'd be a super-nice feature so support something like the instance addons for IRSA accounts, by the way. Although presumably in that case, only one addon per ServiceAccount... Anyway, that's a different feature request for later._

**Anything else we need to know?**

I suspect this was overlooked during refactoring to add cert-manager support to the existing external-dns support, as they are currently intertwined in the code. external-dns *does* [document this permission as needed](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#iam-policy), and so I guess [when cert-manager was added](https://github.com/weaveworks/eksctl/pull/885), it was copied over by accident.

**Versions**

N/A

**Logs**

N/A

**Comment by sayboras** [comment]
Very detailed issue :100:
