### ISSUE TITLE
cleanupAws in integration test is out of date

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#208]
This got me very puzzled actually, I nearly panicked that I found a bug in EKS. I found CloudFormation stacks in my account, but couldn't see actual EKS clusters.

Turns out we delete the cluster directly first:

https://github.com/weaveworks/eksctl/blob/142fd2b8fbec89678aec657e612482e1a46ef689/tests/integration/cleanup.go#L12-L14

Then we try to delete some stack, but using the old naming convention:

https://github.com/weaveworks/eksctl/blob/142fd2b8fbec89678aec657e612482e1a46ef689/tests/integration/cleanup.go#L16-L34

Obviously something that got overlooked earlier, easy to fix though. Probably it should just call `eksctl delete cluster`, wait and verify that both stacks get deleted using CloudFormation API (basically mirror what we do when we setup the integration tests).

**Comment by errordeveloper** [comment]
> ...wait and verify that both stacks get deleted using CloudFormation API (basically mirror what we do when we setup the integration tests).

Waiting for cluster stack to get delete may take too long actually, perhaps we don't have wait for that. Just check if `eksctl delete cluster` resulted in nodegroup stack going away, and cluster stack status becomes `DELETE_IN_PROGRESS`. If we decide to make `eksctl delete cluster` wait for all resource to get deleted, so be it, but for now we shouldn't have to make tests run too long before there is a need for that.

**Comment by richardcase** [comment]
In my head the integration test was always supposed to be full life cycle:
`create->list->delete`
and the cleanup code was only there if the test failed and we just needed to cleanup.

**Comment by errordeveloper** [comment]
Fixed by @Lazyshot via #255.
