### ISSUE TITLE
create iamserviceaccount doesn't read --cluster

### ISSUE THREAD

**Issue by SmartassSkeleton** [weaveworks/eksctl#2081]
**What happened?**

When trying to create a iam service account the command fails with the error `Error: --cluster must be set` even though I passed the flag within the command.

**What you expected to happen?**

```
$ eksctl create iamserviceaccount --cluster my-cluster my-iam-service-account
Error: --cluster must be set
```

I've tried changing the position of `--cluster` but got the same error over and over again.

**How to reproduce it?**

`$ eksctl create iamserviceaccount --cluster your-cluster iam-service-account`

**Anything else we need to know?**

OS: Mac OS Cataline 10.15.4 
shell: zsh
using default credentials

**Versions**

```
$ eksctl version
0.17.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

```
$ eksctl create iamserviceaccount --cluster my-cluster my-iam-service-account
Error: --cluster must be set
```

**Comment by sayboras** [comment]
@SmartassSkeleton thanks for reporting this issue, I can replicate this as well.

For the time being, you can use the below command to create iamserviceaccount

_eksctl create iamserviceaccount --cluster my-cluster --name my-iam-service-account --attach-policy-arn dummyPolicy_

**Comment by VishnuSharma11D00** [comment]
I am facing the same problem, why is this happening?
