### ISSUE TITLE
Link check error due to too many redirect/request

### ISSUE THREAD

**Issue by sayboras** [weaveworks/eksctl#2088]
**What happened?**
Link check github action error 

**What you expected to happen?**
Github action link check should be successful

Occasionally, the below issue happens

https://github.com/weaveworks/eksctl/pull/2084/checks?check_run_id=621818814
https://github.com/weaveworks/eksctl/runs/621864468
https://github.com/weaveworks/eksctl/pull/2093/checks?check_run_id=621990410

![image](https://user-images.githubusercontent.com/9019229/80356149-62bcf000-88bc-11ea-9875-063502f3b9ce.png)

**Comment by sayboras** [comment]
As contributor might not have permission to re-run the failed job, one new git push is required to re-run the job.

**Comment by sayboras** [comment]
Not important as this issue is less likeylky to happen after the PR https://github.com/weaveworks/eksctl/pull/2093 is merged, which will reduce the number of unneccessary checks. Thanks to @martina-if @dholbach :tada: 

I just take a look at the upstream tool, seems like redirecting issue is also happening https://github.com/raviqqe/liche/issues/32

**Comment by dholbach** [comment]
Maybe let's just exclude `weave.works` in the link-checking for now.

**Comment by sayboras** [comment]
@dholbach thanks for your input, just raise one PR for the same https://github.com/weaveworks/eksctl/pull/2114
