### ISSUE TITLE
availabilityZones config is documented in the schema but unrecognized by the eksctl

### ISSUE THREAD

**Issue by trauts2** [weaveworks/eksctl#2099]
**What happened?**
A description of actual behavior (with error messages).

The schema at https://eksctl.io/usage/schema/ lists a configuration for availabilityZones.  However when I specify this, the eksctl tool complains about a syntax error.

![image](https://user-images.githubusercontent.com/4002664/80380997-e4356380-8865-11ea-9497-296e69ab44f8.png)

This is btw an attempt to get around the dreaded "does not currently have sufficient capacity to support the cluster" error.  It seems that the command line accepts specifying zones, but this doesn't work when I try via the config file.

**What you expected to happen?**

Availability zones specified would be used.

**How to reproduce it?**
Include the steps to reproduce the bug

Here's the top bit of my config file

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  us-east-1a
  us-east-1b
  us-east-1d
metadata:
  name: test-eks-spotinst1
  region: us-east-1
  version: '1.15'

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

macos.  

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
$ kubectl version
```

$ eksctl version
0.17.0

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

See image attached

**Comment by cPu1** [comment]
That is not the correct syntax for specifying a list in YAML. You need:

```yaml
availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1d"]
```

or

```yaml
availabilityZones:
- "us-east-1a"
- "us-east-1b"
- "us-east-1d"
```

**Comment by trauts2** [comment]
You're right.  Thanks!
