### ISSUE TITLE
bad output keys can result in eks.GetOutput blocking

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#21]
It was observed that it blocked once, needs more testing to verify why.

https://github.com/weaveworks/eksctl/blob/0a39d1a2c1d107e1da90c27889d43bddba42ab3a/pkg/eks/cfn.go#L41

https://github.com/weaveworks/eksctl/blob/0a39d1a2c1d107e1da90c27889d43bddba42ab3a/pkg/eks/cfn.go#L355

**Comment by archisgore** [comment]
I bet both of these will be fixed by: #85 . In both the cases, the blocks are happening when attempting to write to the channel.

**Comment by errordeveloper** [comment]
@archisgore I think you are right, and as of #94 we can safely close this.
