### ISSUE TITLE
add support for eksctl to tag CFTs it creates

### ISSUE THREAD

**Issue by niroowns** [weaveworks/eksctl#2106]
As part of our governance requirements, we need the ability to tag all CFTs we create.  It would be helpful if eksctl gives us the ability to tag all of the corresponding CFTs it creates including (control plane resource cft stack, un-managed worker node resource cft stack, service account 2 IAM resource cft stack, etc).

eksctl manifest should support tags at each of the above resource definitions that get inherited to the cft resource itself.

**Comment by vespian** [comment]
We run into the same issue. Any chance to get this going?

**Comment by rndstr** [comment]
This should already be possible by specifying `metadata.tags` in the clusterconfig:
```
metadata:
  name: my-cluster
  region: ap-northeast-1
  tags:
    name: value
    name: value
```

 These tags will be used for each CFT eksctl creates:
https://github.com/weaveworks/eksctl/blob/92402ecac8b5a03d505014542e53a98354f751a7/pkg/cfn/manager/api.go#L76-L94
