### ISSUE TITLE
Ability to set metricsBindAddress for kube-proxy in Cluster YAML

### ISSUE THREAD

**Issue by stateisbad** [weaveworks/eksctl#2107]
Apologies if this feature already exists, but it'd be nice if we could set the `metricsBindAddress` for `kube-proxy` in the cluster YAML used when building a cluster.

For instance, `kops` allows you to specify
```
spec:
  kubeProxy:
    metricsBindAddress: 0.0.0.0
```
It seems as though with `eksctl` we currently need to manually, or via some other sort of programmatic method, change this value after the fact.

Any guidance or feedback is much appreciated. Thanks for all your hard work on this piece of software.

**Comment by stateisbad** [comment]
Hello. Does anyone have any objections to a feature like this?

**Comment by yossicohn-hs** [comment]
> Apologies if this feature already exists, but it'd be nice if we could set the `metricsBindAddress` for `kube-proxy` in the cluster YAML used when building a cluster.
> 
> For instance, `kops` allows you to specify
> 
> ```
> spec:
>   kubeProxy:
>     metricsBindAddress: 0.0.0.0
> ```
> 
> It seems as though with `eksctl` we currently need to manually, or via some other sort of programmatic method, change this value after the fact.
> 
> Any guidance or feedback is much appreciated. Thanks for all your hard work on this piece of software.
 
@stateisbad did you find any workaround on this?

**Comment by yossicohn** [comment]
> Apologies if this feature already exists, but it'd be nice if we could set the `metricsBindAddress` for `kube-proxy` in the cluster YAML used when building a cluster.
> 
> For instance, `kops` allows you to specify
> 
> ```
> spec:
>   kubeProxy:
>     metricsBindAddress: 0.0.0.0
> ```
> 
> It seems as though with `eksctl` we currently need to manually, or via some other sort of programmatic method, change this value after the fact.
> 
> Any guidance or feedback is much appreciated. Thanks for all your hard work on this piece of software.

@stateisbad  did you find any workaround on this?
