### ISSUE TITLE
Add ability to create clusters without public subnets

### ISSUE THREAD

**Issue by opensourceonly** [weaveworks/eksctl#2113]
**Why do you want this feature?**
This is needed for some cases where we do not want any ALBs deployed and restrict access from internet. 

**What feature/behavior/change do you want?**
eksctl needs to support the creation of clusters without the creation of any public subnets.
This needs to be happen using a file (cluster.yaml) . At the moment we can create only using subnets in a given VPC that is specified in the cluster.yaml file.

Something like 
eksctl create cluster -f cluster_privatesubnetsonly.yaml

**Comment by opensourceonly** [comment]
@martina-if  any estimated dates for this feature to be made available in place ?

**Comment by martina-if** [comment]
@opensourceonly I can't give a date at the moment but this is something we would like to get to soon.

**Comment by opensourceonly** [comment]
@martina-if Thank you , sounds like a plan !

**Comment by martina-if** [comment]
Hi @opensourceonly to clarify your use case, you are referring to the case when eksctl also creates the VPC, right? Not when the user supplies an existing VPC, right?

**Comment by agbanagba** [comment]
Hi @martina-if. By default, `eksctl` creates both public and private subnets and the only way to work with **only** private subnets is to create it before hand within an existing vpc and supply to the cluster yaml file. There is no way currently to pass in a flag on the cli or in the ClusterConfig to specify creation of only private subnets without it existing in a vpc.

**Comment by opensourceonly** [comment]
@martina-if  yes you are correct. We do expect that eksctl also creates the VPC

**Comment by opensourceonly** [comment]
@martina-if  any rough estimates on when this can be in place ?

**Comment by martina-if** [comment]
Might be useful to also track #1765

**Comment by martina-if** [comment]
@opensourceonly is the feature described in #1765 something that would be useful for your use case?

**Comment by opensourceonly** [comment]
Hi @martina-if is this solved ?

**Comment by martina-if** [comment]
Hi @opensourceonly , the feature that I think can help your use case is described in #1765 and implemented in #2384. Does that help?

**Comment by opensourceonly** [comment]
@martina-if  thank you for the update. in this case, do you know if this still supports the outbound connection to an on-prem data center while using a transit gateway ?

**Comment by martina-if** [comment]
@opensourceonly , I am not sure, I think it should work but I think you should try it to be sure :)
