### ISSUE TITLE
How to create an EKS cluster with a custom service-node-port-range?

### ISSUE THREAD

**Issue by bjethwan** [weaveworks/eksctl#2119]
How to create an EKS cluster with a custom service-node-port-range?

Basically I want to extend the default range (i.e. 30000-32676) by another 10k.

If it's not possible today, can we expect this in the future, I mean is that technically even possible for EKS to take some limited kube-apiserver extraArgs?

**Comment by sayboras** [comment]
@bjethwan correct me if I am wrong. This param will be used in kube-apiserver, which is part of control plane, AFAIK EKS doesn't allow to you change any settings related to control plane.

**Comment by bjethwan** [comment]
@sayboras That's right, it's a param used in kube-apiserver. I believe this would eventually be reaching out to kube-proxies.
Expanding node-port range is often required. One of the examples would be when we use a self-managed API gateway. I am not sure if this is even possible in aws, if not I would raise a request with aws eks team instead. Let me know.

**Comment by sayboras** [comment]
@bjethwan you can raise a rewquest to aws eks team. One work around can be found [here](https://stackoverflow.com/questions/55821856/can-i-use-eks-nodeport-service-with-port-80-and-443), not sure if it's useful in your use case.
