### ISSUE TITLE
Unable to apply kubeletExtraConfig allowedUnsafeSysctls

### ISSUE THREAD

**Issue by msebbar** [weaveworks/eksctl#2128]
**What happened?**
Impossible to apply kubeletExtraConfig allowedUnsafeSysctls, tried

```
kubeletExtraConfig:
  allowedUnsafeSysctls: ["net.core.somaxconn"]
```
and
```
kubeletExtraConfig:
  allowedUnsafeSysctls: 
    - "net.core.somaxconn"
```

gives the error
`[✖]  validating generated KubeletConfiguration object: error unmarshaling JSON: while decoding JSON: json: unknown field "allowedUnsafeSysctls"`

however, other configs such as

```
        featureGates:
            DynamicKubeletConfig: true
```
works correctly.

**What you expected to happen?**
The creation of the nodegroup with kubeletExtraConfig allowedUnsafeSysctls.

**How to reproduce it?**
Create a config file for eksctl with allowedUnsafeSysctls kubeletExtraConfig

**Anything else we need to know?**

**Versions**
```
$ eksctl version -> 0.15.0
$ kubectl version -> 1.14
```

**Logs**
```
[ℹ]  building nodegroup stack "cluster-dev-nodegroup-ng1-workers-1a"
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=eu-west-1 --cluster=cluster-dev --name=<name>' for each of the failed nodegroup
[✖]  validating generated KubeletConfiguration object: error unmarshaling JSON: while decoding JSON: json: unknown field "allowedUnsafeSysctls"
Error: failed to create nodegroups for cluster "cluster-dev"
```

**Comment by agbanagba** [comment]
Hi, 

I want to take a look at this and investigate further if no one's looking at it.

Thanks

**Comment by agbanagba** [comment]
The upstream dependency of the kubelet configuration used to validate the `kubeletExtraConfig` from the eksctl yaml config, introduced AllowedUnsafeSysctls in v0.16.4 and v0.15.11 is currently used.

	k8s.io/kubelet => k8s.io/kubelet v0.15.11

_Upstream Versions_

**v0.15.11**
https://github.com/kubernetes/kubelet/blob/c66062efc14df7c05eb6edef4799d004360c1d79/config/v1beta1/types.go#L720-L721

**v0.16.4**
https://github.com/kubernetes/kubelet/blob/46717a26a0c9c343486bbdc955811dce897f9bf1/config/v1beta1/types.go#L740-L746

@martina-if @sayboras 
What's required to update the version of `k8s.io/kubelet`? If we update the version, do we also need to update the version all k8s components used in the project?

**Comment by martina-if** [comment]
Hi @agbanagba I am not sure if updating that requires more updates. If you want you can try and hopefully it will be a matter of just updating that one?

**Comment by agbanagba** [comment]
@martina-if this PR #2179 should resolve this issue.

**Comment by sayboras** [comment]
> What's required to update the version of k8s.io/kubelet? If we update the version, do we also need to update the version all k8s components used in the project?

@agbanagba sorry somehow I missed your above mention. In my opinion, upgrading with the same version makes it easier for maintaining. And mostly change one dependency version will lead to another one (or you need to use replace directive). Kindly note that all kube modules are coming from same giant upstream path https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io :cry:

**Comment by agbanagba** [comment]
@sayboras sure that makes a lot of sense. When your change goes in, this should be resolved.

Thanks

**Comment by michaelbeaumont** [comment]
@agbanagba the PR has been merged, please try out the latest version of master if you get a chance!

**Comment by agbanagba** [comment]
@michaelbeaumont Thanks

**Comment by msebbar** [comment]
@michaelbeaumont thanks
