### ISSUE TITLE
--watch flag for 'cluster delete'

### ISSUE THREAD

**Issue by paulbsch** [weaveworks/eksctl#213]
**Why do you want this feature?**
It would be helpful to be able see/monitor the results of 'cluster delete' on the command line.

**What feature/behavior/change do you want?**
Currently, 'cluster delete' immediately exits after sending the delete commands upstream.  I'm proposing a --watch flag that could be set to true/false.  Then eksctl could be directed to watch/monitor the cluster deletion until it finishes/fails.

Currently, the default behavior on cluster creation is essentially "--watch=true".  It might also make sense to make "--watch=true" the default on delete?

**Comment by richardcase** [comment]
@paulbsch - sounds like a reasonable idea for delete. I wonder of `--wait` may be better?

**Comment by paulbsch** [comment]
@richardcase I'm indifferent as to what the flag is called.  Whatever works.

**Comment by Lazyshot** [comment]
`--wait` was added in #262
