### ISSUE TITLE
build: To build on checkout merge for PR

### ISSUE THREAD

**Issue by sayboras** [weaveworks/eksctl#2132]
## Description
I notice that the PR build is on the branch only, so there is no very low guarantee that it will not break once merged. Moreover, it might take some extra times for contributor to keep rebasing, as well reviewer to verify the changes carefully.

Understand that team @martina-if @cPu1 is taking steps to make development cycle faster by relaxing rebase condition, it will be better if the PR build can be done on the merge between source branch and the upstream branch. This approach is quite common in other CI such as travis or github action.

https://docs.travis-ci.com/user/pull-requests/
> Travis CI builds a pull request when it is first opened, and whenever commits are added to the pull request. Rather than build the commits that have been pushed to the branch the pull request is from, we build the merge between the source branch and the upstream branch.

## Approach
If I am not wrong, circleCI doesn't offer this feature ootb, we can have a little script to checkout _+:refs/pull/(*/merge)_ as opposed to _+:refs/pull/(*/head)_

**Comment by michaelbeaumont** [comment]
@sayboras hi! is this not already being done effectively since "Require branches to be up to date before merging" is enabled for the repo?

**Comment by sayboras** [comment]
> hi! is this not already being done effectively since "Require branches to be up to date before merging" is enabled for the repo?

@michaelbeaumont I think that option in github is just a validation, which will force author to make sure that PR is having all changes from master. If the author _**performs**_ the necessary, the build will kick off with (master + changes in PR).

**Comment by michaelbeaumont** [comment]
@sayboras we decided to squash merge more PRs. This should allow us to have the GH restriction enabled (enforcing checks up to date), allow for easily updating PRs with the Update branch button, keep a clean history and keep the build system simple.
