### ISSUE TITLE
--node-volume-size flag for create cluster

### ISSUE THREAD

**Issue by paulbsch** [weaveworks/eksctl#214]
**Why do you want this feature?**
It is currently not possible to set the volume size used for the nodes.  It defaults to 20GB and it is only possible to modify the volume sizes after creation using AWS tools.

**What feature/behavior/change do you want?**
A --node-volume-size flag that can be used to set larger node volume size on cluster creation.

**Comment by dholbach** [comment]
Thanks for sending in this request!

**Comment by richardcase** [comment]
@paulbsch - would you expect it to accept an integer value that represents GBs? For example, `--node-volume-size=50` would be use to create a volume size of 50GB.

**Comment by paulbsch** [comment]
@richardcase Yep.  Exactly.
