### ISSUE TITLE
latest_release tag is pointing to the release candidate for linux

### ISSUE THREAD

**Issue by cpaika** [weaveworks/eksctl#2145]
**What happened?**
We consume the latest_release of eksctl in our cluster deployment pipelines, so we stay up to date.  We download it directly from this URL: https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_Linux_amd64.tar.gz

It looks like currently, the latest_release of eksctl_Linux_amd64 is pointing to the release candidate `eksctl 0.19.0-rc.0`.
However, when we get the `latest_release` of the mac version, we get eksctl `0.18.0`.

Using the release candidate, we are getting errors on cluster creation due to a ServiceRole not being able to be assumed by the Control Plane.

**What you expected to happen?**
We expect that the latest_release tag points to the latest stable release of eksctl, in this case thats 0.18.0.

**How to reproduce it?**
* Download eksctl from https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_Linux_amd64.tar.gz
* Unzip
* Run ./eksctl version

So wondering what the discrepency is between the versions, or if there is a better tag we should be referring to to consume the latest stable version of eksctl

**Comment by montanaflynn** [comment]
Same with installing using homebrew:

```sh
> brew tap weaveworks/tap                                                                                                                                             1950ms < Thu May  7 12:23:01 2020

> brew upgrade eksctl && brew link --overwrite eksctl
Updating Homebrew...
Warning: weaveworks/tap/eksctl 0.18.0 already installed
Warning: Already linked: /usr/local/Cellar/eksctl/0.18.0

From https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html#installing-eksctl

> The GitTag version should be at least 0.19.0. If not, check your terminal output for any installation or upgrade errors, or manually download an archive of the release from https://github.com/weaveworks/eksctl/releases/download/0.19.0/eksctl_Darwin_amd64.tar.gz, extract eksctl, and then execute it.

**Comment by michaelbeaumont** [comment]
@cpaika For the latest stable release, please use [`latest`](https://github.com/weaveworks/eksctl/releases/tag/0.18.0)

**Comment by michaelbeaumont** [comment]
@montanaflynn Can you try installing with homebrew adding the `--HEAD` switch?

**Comment by montanaflynn** [comment]
@michaelbeaumont yeah that worked but I first had to unlink and reinstall since `--HEAD` doesn't work with `brew upgrade`:

```
brew unlink eksctl
brew install --HEAD eksctl
```

I think the problem is the disparity between the AWS eks documentation and the state of `eksctl`:

https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html#installing-eksctl

The homebrew instructions install 1.18 and link to the 1.19 release is broken.

**Comment by michaelbeaumont** [comment]
Agreed, that's an issue. We're going to release `0.19.0` today so it should be solved soon enough.

**Comment by cpaika** [comment]
@michaelbeaumont Thanks!
