### ISSUE TITLE
Updating control plane from 1.15 to 1.16 results in a timeout error

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#2150]
The default timeout for `eksctl update cluster` is set to 25 minutes, however, updating the control plane from 1.15 to 1.16 took longer than that in at least three of my tests, and as a result, the command timed out.

**Comment by cPu1** [comment]
Fixed in #2151

**Comment by autarchprinceps** [comment]
@cPu1 It seems to me, like this was made part of 0.19.0 release, going by #2171 
but I can definitively confirm, that it is just as 100% broken for us with the release version, as it was with the RC versions.
