### ISSUE TITLE
eksctl to launch cluster with pre-existing VPC, Subnets, Service IAM role in private networkingm without IG and public subnets

### ISSUE THREAD

**Issue by nitinkansal1984** [weaveworks/eksctl#2161]
Please [search existing issues (open & closed)](https://github.com/weaveworks/eksctl/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if there is a similar one. If there is, add comments or vote where appropriate.

If you did not find a similar issue or if it did not help then ask for help in our [slack channel](https://weave-community.slack.com/messages/eksctl/)

**What help do you need?**
Describe the type of help you need
eksctl launch cluster issue.
eksctl to launch cluster with pre-existing VPC, Subnets, Service IAM role in private networkingm without IG and public subnets
I tried but it reported 
"Cannot create cluster 'my-test' because us-east-1e, the targeted availability zone, does not currently have sufficient capacity to support the cluster
But when I mentioned availability zones in config file then it reported below error:
Subnet Id is required (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; 
Can someone please provide me config.yaml for my scenrio? I have service IAM role created before hand and wanted to use that, I have 2 private subnets and availability zones which I wanted to use for EKS. I wanted to launch it with private networking enabled and public disabled,

**Comment by martina-if** [comment]
Hi @nitinkansal1984,

I recommend you use another region, `us-east-1` is known for having capacity issues. Once you choose the region you want to use you need to create the VPC and the subnets for the appropriate availability zones. You can check some examples here: 
  - https://eksctl.io/examples/reusing-iam-and-vpc/
  - https://github.com/weaveworks/eksctl/tree/master/examples

Hope that helps! You can always reach us and other community users in [slack](https://weave-community.slack.com/archives/CAYBZBWGL)
