### ISSUE TITLE
Add unit and integration tests for `eksctl version`

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#2163]

**Comment by bitcodr** [comment]
@martina-if  Hi, I wanna try to contribute on this project, can you please assign this issue to me? and do you mean unit test for this path  `eksctl/cmd/eksctl/version.go` ?

**Comment by martina-if** [comment]
Hi @bitcodr , great news that you want to contribute! :heart: 

I just realized there are a bunch of unit tests already, so perhaps we could have a short integration test in `integration/tests/crud/creategetdelete_test.go` that makes sure that the output of the command `eksctl version` is the correct string.

If you want more (or other more exciting) issues that could be good to start look also at the label "low hanging fruit". We will try to go through existing issues and label more of these soon.
