### ISSUE TITLE
Investigate how to generate schema docs automatically

### ISSUE THREAD

**Issue by kalbir** [weaveworks/eksctl#2166]
As part of [improving the schema documentation](https://github.com/weaveworks/eksctl/issues/1472) we want to find out how we can generate the documentation automatically. 

For this we should:
- [x] Understand some of the main options
- [x] Have an idea of how and how easy they would be to implement
- [x] Give an example of how it could be used in eksctl to generate the schema documentation.
- [x] Give an example where we specify more detailed information on how to use the config field (like e.g. [skaffold](https://skaffold.dev/docs/references/yaml/)) 
  - An [`example` for a field in the config schema](https://github.com/GoogleContainerTools/skaffold/blob/f30af02c5862ddc32c3609d300dbc920621ca55f/pkg/skaffold/schema/latest/config.go#L157)

Tracking implementation in https://github.com/weaveworks/eksctl/issues/2258
Tracking adding the documentation https://github.com/weaveworks/eksctl/issues/1472

**Comment by michaelbeaumont** [comment]
For skaffold, they've implemented their own solution:
1. for [parsing the go files](https://github.com/GoogleContainerTools/skaffold/blob/master/hack/schemas/main.go) where the schema is declared and generating the json schema from the structs and the comments on the fields.
2. for [converting the JSON schemas to HTML](https://github.com/GoogleContainerTools/skaffold/blob/master/docs/content/en/docs/references/yaml/main.js)

**Comment by michaelbeaumont** [comment]
It looks like we use https://github.com/alecthomas/jsonschema already to generate the schema, we just need to supplement the fields with more information and then just basically pretty print the json schema

**Comment by martina-if** [comment]
MBOI #2053

**Comment by michaelbeaumont** [comment]
Closing this because investigation is over:
Implementation in #2258 and https://github.com/weaveworks/eksctl/issues/1472
