### ISSUE TITLE
Cannot create clusters on regions other than US-WEST-2, US-EAST-1 and EU-WEST-1

### ISSUE THREAD

**Issue by redborian** [weaveworks/eksctl#217]
**What happened?**
User should be able to create clusters in all the regions supported by AWS EKS

**What you expected to happen?**
There is a validation rule in create.go file that restricts the region to US-WEST-2, US-EAST-1 or EU-WEST-1.

**How to reproduce it?**
Run `eksctl create cluster --region us-east-2`

**Anything else we need to know?**
OS is windows. I am using the downloaded binary. AWS is default profile.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
2018-09-18T14:41:02-07:00 [ℹ]  versionInfo = map[string]string{"gitTag":"0.1.0", "builtAt":"2018-08-02T13:58:30Z", "gitCommit":"dca39f69e893b89d67156635c483b3f3e8236407"}
$ uname -a
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: getting credentials: exec: exec: "heptio-authenticator-aws": executable file not found in %PATH%
```
Also include your version of `heptio-authenticator-aws`

**Logs**
2018-09-18T14:44:24-07:00 [✖]  --region=us-east-2 is not supported only us-west-2 and us-east-1 are supported

**Comment by richardcase** [comment]
Hi @redborian - the regions where EKS is currently supported are the same regions eksctl supports. Currently the `us-east-2 (Ohio)` region isn't supported by EKS and therefore not allowed in eksctl.

As new regions are EKS enabled we will update eksctl.

Are you happy for us to close this issue? 

<img width="210" alt="screen shot 2018-09-19 at 08 51 05" src="https://user-images.githubusercontent.com/198425/45738809-4be6ef80-bbe9-11e8-9608-48057bec00df.png">

**Comment by redborian** [comment]
Thanks for your response @richardcase . Instead of hard-coding the currently available EKS regions, is there a way to get them through an API?

**Comment by redborian** [comment]
Thanks @richardcase . I will close this issue.

**Comment by Emlin-Freeda** [comment]
hi, which version of github is supported by us-west-2?
