### ISSUE TITLE
`eksctl delete cluster` should delete cluster and all associated resources

### ISSUE THREAD

**Issue by kalbir** [weaveworks/eksctl#2172]
**Why do you want this feature?**
There are [numerous issues](https://github.com/weaveworks/eksctl/labels/area%2Fdeletions) that track cases where someone has run `eksctl delete cluster` and it has not resulted in the cluster and all of the resources created by `eksctl` being deleted.

This means that people are sometimes left with surprise bills, which is a really bad outcome. It also slows people down when they have to go and investigate why a particular cluster did not delete. 

Some specific examples: 
closed issues
- https://github.com/weaveworks/eksctl/issues/755
- https://github.com/weaveworks/eksctl/issues/1856
- https://github.com/weaveworks/eksctl/issues/1325
- https://github.com/weaveworks/eksctl/issues/536
- https://github.com/weaveworks/eksctl/issues/1849
- https://github.com/weaveworks/eksctl/issues/1653

(more under the [area/deletions](https://github.com/weaveworks/eksctl/labels/area%2Fdeletions) label)

**What feature/behavior/change do you want?**

Rather that trying to chase after all of the cases, is there some pattern we could introduce that aimed for an eventually consistent delete? i.e. could we retry deletions or target specific areas in a particular order to ensure that all of the resources will eventually get deleted.

**Comment by aclevername** [comment]
https://github.com/weaveworks/eksctl/issues/1653 can get removed from the "open issues" section as the OIDC provider does not get deleted during `eksctl delete cluster`. The two remaining NG/ENI issue are getting worked on #536

**Comment by Himangini** [comment]
Closing this off since all the related issues mentioned above are completed
