### ISSUE TITLE
Use eksctl commands (e.g. update core-dns) on non-eksctl created clusters

### ISSUE THREAD

**Issue by kalbir** [weaveworks/eksctl#2174]
**Why do you want this feature?**
`eksctl` has some commands that make it easy to do things on clusters. So regardless of whether you created the cluster with `eksctl` or some other method, it could save yout time if you could use one of those commands on your cluster.

Examples that come to mind are:
- `eksctl utils update-coredns`
- `eksctl create iamidentitymapping`
- `eksctl create fargateprofile` 
- `eksctl upgrade nodegroup` (https://github.com/weaveworks/eksctl/issues/2698)

**What feature/behavior/change do you want?**

My initial thought is that you could pass some identifier for the cluster to eksctl (e.g. name and region) that will identify a unique cluster. `eksctl` could then look up that cluster and apply the correct command to it. So on the surface of things, eksctl would not change from a user perspective. 

This would mean that `eksctl get clusters` could also show _all_ the clusters that you have in your account, and indicate whether they were created by `eksctl` or not.

Then if you tried a command on a non-eksctl cluster that we could not complete, you'd get a message telling you why you couldn't do that (e.g. `delete cluster`).

**Comment by aclevername** [comment]
Thanks for opening the issue @kalbir. You raise some excellent points around the current user experience when using eksctl against clusters that weren't created with eksctl. I've opened two recent PRs to try and improve the current experience https://github.com/weaveworks/eksctl/pull/2779 and https://github.com/weaveworks/eksctl/pull/2775. However these PRs only adress `eksctl get clusters` and `eksctl create iamserviceaccount`. As you point out there are many commands where eksctl doesn't work. 

Your suggestion around changing it so that the UX seems reasonable to me. To recap the outcome of running a command against a non-eksctl created cluster would be either:
1. It works as expected
2. Where it doesn't work, it provides a good UX why, e.g. 
```bash
$ eksctl delete cluster --name cluster-created-in-console
[ℹ]  eksctl version 0.30.0
[ℹ]  Cannot delete cluster that was not created via eksctl (no associated CloudFormation stacks found)
```

It might be that over time we try to remove more occurrences of 2. and make eksctl smarter. For example at the moment it all of its interaction with creating clusters is through CloudFormation, meaning commands like `eksctl delete cluster` don't work as if you created the cluster manually it has no CloudFormation stack to delete. This could be overcome by making eksctl more aware of alternative methods of interacting with clusters.

**Comment by aclevername** [comment]
I'm working my way through the commands to see what needs to change (will update this comment as I go along):

## Works
1. `eksctl get clusters` #2779
1. `eksctl create iamserviceaccount` #2775

## Needs adjusting
1. `eksctl delete cluster`

**Comment by aclevername** [comment]
Split into sub-issues:
https://github.com/weaveworks/eksctl/issues/2808
https://github.com/weaveworks/eksctl/issues/2809
https://github.com/weaveworks/eksctl/issues/2810
https://github.com/weaveworks/eksctl/issues/2811
https://github.com/weaveworks/eksctl/issues/2812

**Comment by aclevername** [comment]
Update list as of 15/01/2021
## Works
1. `eksctl get clusters` #2779
1. `eksctl create iamserviceaccount` #2775
1. `eksctl create iamidentitymapping`
1. `eksctl delete iamserviceaccount`
1. `eksctl delete iamidentitymapping`
1. `eksctl enable profile`
1. `eksctl enable repo`
1. `eksctl get cluster`
1. `eksctl utils associate-iam-oidc-provider`
1. `eksctl utils describe-stacks` (not applicable)
1. `eksctl utils install-vpc-controllers`
1. `eksctl utils nodegroup-health`
1. `eksctl utils set-public-access-cidrs`
1. `eksctl utils update-cluster-endpoints`
1. `eksctl utils update-cluster-logging`
1. `eksctl utils write-kubeconfig`
1. `eksctl utils update-coredns`
1. `eksctl utils update-aws-node`
1. `eksctl utils update-kube-proxy`
1. `eksctl delete nodegroup` https://github.com/weaveworks/eksctl/issues/2809
1. `eksctl drain nodegroup` https://github.com/weaveworks/eksctl/issues/2809
1. `eksctl get nodegroup` https://github.com/weaveworks/eksctl/issues/2809
1. `eksctl delete cluster` https://github.com/weaveworks/eksctl/pull/2969
1. `eksctl upgrade cluster` https://github.com/weaveworks/eksctl/pull/2815
1. `eksctl upgrade nodegroup` https://github.com/weaveworks/eksctl/pull/2953


## Needs adjusting
1. `eksctl create fargateprofile` Pending https://github.com/weaveworks/eksctl/issues/2808
1. `eksctl create nodegroup` Not implemented. 
1. `eksctl delete fargateprofile` Pending https://github.com/weaveworks/eksctl/issues/2808
1. `eksctl scale nodegroup`
1. `eksctl set labels`
1. `eksctl unset labels`

**Comment by jmolero-cortical** [comment]
Hi @aclevername thanks for you effort. At least in my case, the option 'eksctl upgrade nodegroup' is not working:

`% eksctl version
0.36.0`

`% eksctl upgrade nodegroup --name=NG-test  --cluster=testcluster   --kubernetes-version 1.18  --launch-template-version 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d8c2b3]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).upgradeAndWait(0xc0006379e0, 0x7ffeefbffb60, 0x13, 0x7ffeefbffba5, 0x4, 0x7ffeefbffbc4, 0x1, 0x0, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/actions/nodegroup/upgrade.go:60 +0x753
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).Upgrade(0xc0006379e0, 0x7ffeefbffb60, 0x13, 0x7ffeefbffba5, 0x4, 0x7ffeefbffbc4, 0x1, 0x0, 0xc0001ca8b0, 0xc000240d90)
	github.com/weaveworks/eksctl/pkg/actions/nodegroup/upgrade.go:38 +0x3e6
github.com/weaveworks/eksctl/pkg/ctl/upgrade.upgradeNodeGroup(0xc0006274a0, 0x7ffeefbffb60, 0x13, 0x7ffeefbffba5, 0x4, 0x7ffeefbffbc4, 0x1, 0x0, 0x1179565, 0xc0000d8400)
	github.com/weaveworks/eksctl/pkg/ctl/upgrade/nodegroup.go:86 +0x311
github.com/weaveworks/eksctl/pkg/ctl/upgrade.upgradeNodeGroupCmd.func1(0xc0000da000, 0xc00009cc60, 0x0, 0x6, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/ctl/upgrade/nodegroup.go:27 +0xef
github.com/spf13/cobra.(*Command).execute(0xc0000da000, 0xc00009cc00, 0x6, 0x6, 0xc0000da000, 0xc00009cc00)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000844840, 0xc00064db10, 0x1, 0xc0008e9f70)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	github.com/weaveworks/eksctl/cmd/eksctl/main.go:76 +0x3ec`

**Comment by aclevername** [comment]
> Hi @aclevername thanks for you effort. At least in my case, the option 'eksctl upgrade nodegroup' is not working:
> 
> 
> 
> `% eksctl version
> 
> 0.36.0`
> 
> 
> 
> `% eksctl upgrade nodegroup --name=NG-test  --cluster=testcluster   --kubernetes-version 1.18  --launch-template-version 2
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> 
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d8c2b3]
> 
> 
> 
> goroutine 1 [running]:
> 
> github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).upgradeAndWait(0xc0006379e0, 0x7ffeefbffb60, 0x13, 0x7ffeefbffba5, 0x4, 0x7ffeefbffbc4, 0x1, 0x0, 0x0, 0x0)
> 
> 	github.com/weaveworks/eksctl/pkg/actions/nodegroup/upgrade.go:60 +0x753
> 
> github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).Upgrade(0xc0006379e0, 0x7ffeefbffb60, 0x13, 0x7ffeefbffba5, 0x4, 0x7ffeefbffbc4, 0x1, 0x0, 0xc0001ca8b0, 0xc000240d90)
> 
> 	github.com/weaveworks/eksctl/pkg/actions/nodegroup/upgrade.go:38 +0x3e6
> 
> github.com/weaveworks/eksctl/pkg/ctl/upgrade.upgradeNodeGroup(0xc0006274a0, 0x7ffeefbffb60, 0x13, 0x7ffeefbffba5, 0x4, 0x7ffeefbffbc4, 0x1, 0x0, 0x1179565, 0xc0000d8400)
> 
> 	github.com/weaveworks/eksctl/pkg/ctl/upgrade/nodegroup.go:86 +0x311
> 
> github.com/weaveworks/eksctl/pkg/ctl/upgrade.upgradeNodeGroupCmd.func1(0xc0000da000, 0xc00009cc60, 0x0, 0x6, 0x0, 0x0)
> 
> 	github.com/weaveworks/eksctl/pkg/ctl/upgrade/nodegroup.go:27 +0xef
> 
> github.com/spf13/cobra.(*Command).execute(0xc0000da000, 0xc00009cc00, 0x6, 0x6, 0xc0000da000, 0xc00009cc00)
> 
> 	github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
> 
> github.com/spf13/cobra.(*Command).ExecuteC(0xc000844840, 0xc00064db10, 0x1, 0xc0008e9f70)
> 
> 	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
> 
> github.com/spf13/cobra.(*Command).Execute(...)
> 
> 	github.com/spf13/cobra@v1.1.1/command.go:895
> 
> main.main()
> 
> 	github.com/weaveworks/eksctl/cmd/eksctl/main.go:76 +0x3ec`
> 
> 

Thanks for reporting the issue! Can you create a new bug report issue with the config file/cluster details? Thanks

**Comment by Callisto13** [comment]
From `0.40.0-rc.0` you should be able to use any eksctl command on any EKS cluster. Docs will be updated by the end of the week.

**Comment by kalbir** [comment]
Nice work! Very pleased this has been shipped ☺️

**Comment by YYSU** [comment]
Can't wait to see this !

**Comment by aclevername** [comment]
> From `0.40.0` you should be able to use any eksctl command on any EKS cluster. Docs will be updated by the end of the week.

Docs will be out with this weeks release, I'm going to close this issue now as the work is done! 😄
