### ISSUE TITLE
Add ability to create EKS clusters in GovCloud regions

### ISSUE THREAD

**Issue by andarob** [weaveworks/eksctl#2189]
**Why do you want this feature?**
EKS recently became available in GovCloud regions. I would like the ability to create clusters in those regions just like I do in other regions.

https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-eks-now-available-in-the-aws-govcloud-us-regions/

**What feature/behavior/change do you want?**
Currently face an error when using it with us-gov-west-1
```
Error: --region=us-gov-west-1 is not supported - use one of: us-west-1, us-west-2, us-east-1, us-east-2, ca-central-1, eu-west-1, eu-west-2, eu-west-3, eu-north-1, eu-central-1, ap-northeast-1, ap-northeast-2, ap-southeast-1, ap-southeast-2, ap-south-1, ap-east-1, me-south-1, sa-east-1, cn-northwest-1, cn-north-1
```
Preferably we would be able to use eksctl among all available regions.

https://github.com/weaveworks/eksctl/blob/master/pkg/apis/eksctl.io/v1alpha5/types.go

**Comment by cPu1** [comment]
Released in https://github.com/weaveworks/eksctl/releases/tag/0.20.0

**Comment by hectoralicea** [comment]
I'm trying to use this feature and I'm getting the following error:
```
[✖]  AWS::EC2::InternetGateway/InternetGateway: CREATE_FAILED – "API: ec2:CreateInternetGateway You are not authorized to perform this operation. Encoded authorization failure message:
[✖]  AWS::EC2::VPC/VPC: CREATE_FAILED – "API: ec2:CreateVpc You are not authorized to perform this operation.
```
I'm using an existing subnet that's private.  Why is it trying to create an internet gateway which should not really be used in a gov region, and why is it trying to create a VPC, when I'm pointing to an existing subnet, already?

Following are my options settings.

```
eksctl create cluster \
	--name=${AWS_EKS_CLUSTER_NAME} \
	--version=${AWS_EKS_CLUSTER_VERSION} \
	--kubeconfig $(pwd)/${ENVIROINMENT}/config \
	--nodegroup-name=${AWS_EKS_NODEGROUP_NAME} \
	--node-private-networking \
	--node-type=t3.large \
	--nodes=3 \
	--nodes-min=3 \
	--nodes-max=12 \
	--region=${AWS_EKS_REGION} \
	--vpc-private-subnets=${AWS_EKS_VPC_PRIVATE_SUBNETS} \
```
