### ISSUE TITLE
Add ability to delete clusters without deleting VPC and Subnets

### ISSUE THREAD

**Issue by opensourceonly** [weaveworks/eksctl#2198]
We need eksctl to provide the ability to delete clusters without deleting VPC and Subnets.
In some organisations, deleting a VPC will delete the transit gateway attachments for instance which are often be managed by central teams. Every time, we delete a cluster it should be a supported way from eksctl to be able to reuse the existing VPC and Subnets

**Comment by sayboras** [comment]
Just want to share my experience and opinion, I could be wrong as well :)

I think that eksctl's main goal is to help any users to _quickly_ bring up kube cluster without the need of understaind required underlying AWS infrastructure. Creating VPC as part of eksctl is one of steps toward that goal. This embedded VPC was crafted specifically for EKS only, and might not fulfill general use case. Hence, I am not sure how much value we have to just retain it upon cluster deletion.

Coming back to your use case, seems like you are expecting VPC and EKS cluster to have different life cycles, then it's better to manage VPC outside of eksctl stack as per [docs](https://eksctl.io/usage/vpc-networking/#use-existing-vpc-any-custom-configuration)

**Comment by kalbir** [comment]
Yes, great response @sayboras -- that's how we see it, for more complex cases like the one described by @opensourceonly we would recommend creating your own VPC and managing it outside of eksctl. We do have a number of issues open to improve the options around VPC and subnet creation but I don't think this is one of the core cases we will support.
