### ISSUE TITLE
Create an cluster with k8s 1.16

### ISSUE THREAD

**Issue by ArturChe** [weaveworks/eksctl#2202]
**What help do you need?**
How can I specify the k8s version using -f key while cluster creation? Right now the combination of _-f_ and _--version_ flags are not supported. Or how can I upgrade the non-managed node groups from "1.15" to "1.16"?

**Comment by sayboras** [comment]
@ArturChe please find below the details:

1. You can use metadata in config file to specify the version. Please refer to https://github.com/weaveworks/eksctl/issues/1938
2. You can use `eksctl update` CLI. Please refer to https://eksctl.io/usage/cluster-upgrade/ for more details.

Hope it helps.

**Comment by ArturChe** [comment]
Thanks!
