### ISSUE TITLE
Command to list supported regions

### ISSUE THREAD

**Issue by richardcase** [weaveworks/eksctl#222]
**Why do you want this feature?**
It would be good to have an eksctl command that lists the EKS supported regions. Something like `eksctk utils list-available-regions`. 

**What feature/behavior/change do you want?**
This should list out the regions where eks is cupported

This is a result of discussion in #217

**Comment by bowlesns** [comment]
I'll take this. Thanks.

**Comment by richardcase** [comment]
Great, thanks @bowlesns

**Comment by philoserf** [comment]
There isn't an API from AWS to provide this information today. The project would need to maintain a list of regions until an API is available. It looks like today AWS keeps a list of available regions in two separate documents in the user guide at [awsdocs/amazon-eks-user-guide](https://github.com/awsdocs/amazon-eks-user-guide/tree/master/doc_source)

Is this a responsibility the project team wants to take on?

**Comment by redborian** [comment]
There is already a hard-coded list of supported regions in `eksctl`. The team already has the responsibility of keeping that hard-coded list up-to-date.
It would be awesome if you can somehow expose them to the user.

**Comment by richardcase** [comment]
> It would be awesome if you can somehow expose them to the user. 

I know that @bowlesns has been working on this.

**Comment by errordeveloper** [comment]
I think this was important when only a few regions were supported, it seems like we don't really need it any more as EKS is in most regions now.
