### ISSUE TITLE
Spot termination behaviour

### ISSUE THREAD

**Issue by frejonb** [weaveworks/eksctl#2224]
**What help do you need?**
Is there a way to configure the shutdown behavior of spot node groups? I see that the created launch template doesn't include the shutdown behaviour. Is there a way to influence this? or does it require a new feature?

**Comment by michaelbeaumont** [comment]
At the moment it's not possible. @cPu1 @martina-if  correct me if I'm wrong

**Comment by martina-if** [comment]
Hi @frejonb, I have not used Spot instances much myself but I recommend you check the [spot-termination-handler](https://github.com/pusher/k8s-spot-termination-handler) and ask on slack since there are some users there with a lot of experience with it.

**Comment by michaelbeaumont** [comment]
Duplicate of https://github.com/weaveworks/eksctl/issues/199#issuecomment-767962571
