### ISSUE TITLE
Investigate moving eks addons from static files to helm charts

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#2245]
Proposed by @sayboras on [slack](https://weave-community.slack.com/archives/CAYBZBWGL/p1590500489032800) we should consider using https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni instead of the static files embedded in the eksctl binary.

Ideally we would use helm via a library and not having to shell out to invoke it.

**Comment by TBBle** [comment]
Similar thing would apply to coredns, and (if a chart existed) kube-proxy. It would dovetail nicely with https://github.com/aws/containers-roadmap/issues/252 so we wouldn't even have to 'adopt' the existing objects when building a new cluster.
