### ISSUE TITLE
Eksctl add new nodegroup error

### ISSUE THREAD

**Issue by moretti-truelogic** [weaveworks/eksctl#2250]
I am trying to add a nodegroup to a cluster, but i receives this error:

[ℹ] nodegroup "dev2" will use "ami-02a6406871cd90718" [AmazonLinux2/1.12]
[✖] found mis-configured subnets ["subnet-0b045bfcb789c9efb" "subnet-0d06e5bed3cb4aa6f" "subnet-0fafa28e9f7813232"]. Expected public subnets with property "MapPublicIpOnLaunch" enabled. Without it new nodes won't get an IP assigned
Error: subnets for one or more new nodegroups don't meet requirements. To fix this, please run eksctl utils update-legacy-subnet-settings --cluster sandbox-STAGE

**subnets ["subnet-0b045bfcb789c9efb" "subnet-0d06e5bed3cb4aa6f" "subnet-0fafa28e9f7813232"]. Expected public subnets with property "MapPublicIpOnLaunch" enabled. Without it new nodes won't get an IP assigned**

Somebody know how we can fix it?

**Comment by michaelbeaumont** [comment]
Did you try the suggested fix? For more information, see the IMPORTANT note at https://eksctl.io/usage/vpc-networking/#vpc-networking

**Comment by moretti-truelogic** [comment]
THis is a Prod Cluster, if i run this command how it will impact in the server?

**Comment by michaelbeaumont** [comment]
The command ensures that [`MapPublicIpOnLaunch`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html#cfn-ec2-subnet-mappubliciponlaunch) is enabled for your public subnets

**Comment by moretti-truelogic** [comment]
I will have downtime?

**Comment by michaelbeaumont** [comment]
Please check the AWS docs I linked for its semantics and behavior to decide if it's something you're comfortable enabling.
How exactly it will impact your specific cluster is of course impossible to say with 100% certainty, although it's not intended to actually change any behavior, as explained in the eksctl docs.

**Comment by moretti-truelogic** [comment]
I will check it, I will let you know. Thanks @michaelbeaumont

**Comment by shaikatz** [comment]
@michaelbeaumont , I'm having the same issue.
But, I'm using privateNetworking for my node group, why they need public IP assigned at all?

**Comment by shaikatz** [comment]
@michaelbeaumont 

I'm getting the same error when trying to create node group in *internal* subnets.

Using the portal I can create the node group without any issues.

Why **mapPublicIpOnLaunch** is a requirement for privateNetworking node groups?

**Comment by wijde** [comment]
> I will check it, I will let you know. Thanks @michaelbeaumont
Hi!
I wanted to ask, after executing this command: eksctl utils update-legacy-subnet-settings --cluster
did you have any problems?
