### ISSUE TITLE
eksctl get nodegroup omits most nodegroup data

### ISSUE THREAD

**Issue by JoshuaFox** [weaveworks/eksctl#2255]
`eksctl get nodegroup --name  one-node-group  --cluster clus-bumping  --region=us-east-2 
--output json` gives thin data about the nodegroup.  See example below.

It omits many details about NodeGroups, such as those configured by these options: `--tags --region --version --config-file   --node-volume-size --node-volume-type --max-pods-per-node --ssh-access  --node-ami --node-ami-family --node-private-networking --node-security-groups --node-labels --node-zones --managed --asg-access --external-dns-access --full-ecr-access --appmesh-access --alb-ingress-access`

As one example, volume-size is omitted. I can see in the EBS console that size is 33 GB as specified, but this fact is not in `eksctl` output.

`kubectl describe node` provides some info, but  I need info on the node  group, which is  is not the same as a node. Also, for example, the exact volume size, 33 GB, is not part of `kubectl` output.

Using eksctl version 0.18.0.

```
[
    {
        "StackName": "eksctl-cluster1-nodegroup-one-node-group",
        "Cluster": "cluster1",
        "Name": "one-node-group",
        "MaxSize": 1,
        "MinSize": 1,
        "DesiredCapacity": 1,
        "InstanceType": "t2.small",
        "ImageID": "",
        "CreationTime": "2020-05-27T07:18:32.496Z",
        "NodeInstanceRoleARN": ""
    }
] 
```

**Comment by martina-if** [comment]
Hi @JoshuaFox, thank you for reporting this. This command prints only some information, not the cluster config used to create the nodegroups/cluster but I see this is a useful use case for you.

I think this could be tracked as part of https://github.com/weaveworks/eksctl/issues/642 so I will close this and track it as a feature request in the mentioned issue.

**Comment by JoshuaFox** [comment]
@martina-if   How do you recommend getting info on a node group? Do you recommend using some other tool like AWS APIs?  Feel free to answer on #642 if you prefer.

**Comment by martina-if** [comment]
Hi @JoshuaFox , one can use the AWS cli, console, or `kubectl`. I see the value in retrieving even more information with `eksctl get` subcommands. Right now this is not something that is prioritized but PRs from external contributors are very welcome :)

**Comment by JoshuaFox** [comment]
@martina-if  Thank you. The EKS portion fo the AWK SDK for Go gave me what I needed to[ clone clusters.](https://github.com/doitintl/clustercloner). I guess that the   `kubectl` would not give node-level details and the AWS cli would give information on the underlying VMs, which is closely related to information on nodes but not quite the same.
