### ISSUE TITLE
generate profile git-url parameters does not exist

### ISSUE THREAD

**Issue by Booyaka27** [weaveworks/eksctl#2260]
Hi,

in the quickstart, I'm followiiing the advanced part, and trying to use 
`EKSCTL_EXPERIMENTAL=true eksctl generate profile \
        --cluster wonderful-wardrobe-1565767990 \
        --git-url https://github.com/weaveworks/eks-quickstart-app-dev.git \
        --profile-path ~/dev/flux-get-started/cluster-config`

but --git-url command not exist, it works for eksctl enable but not generate profile.

regarding this: https://eksctl.io/gitops-quickstart/

**Comment by kalbir** [comment]
Ah yes, thank you @Booyaka27, we've changed the flags for `generate profile` but not updated that bit of the docs. If you have version `0.20.0` you can use `--profile-source`.

<img width="1118" alt="Screenshot 2020-05-28 at 17 26 08" src="https://user-images.githubusercontent.com/3952074/83167799-7c926280-a108-11ea-9f6a-e9c2f2707b9f.png">

We'll fix this in the docs as well.

**Comment by martina-if** [comment]
Hi @Booyaka27 the site has been updated now, please reopen the ticket if you still encounter issues! Thanks for reporting!
