### ISSUE TITLE
Gitops: Add configuration for known_hosts and repositories.yaml

### ISSUE THREAD

**Issue by MMartyn** [weaveworks/eksctl#2262]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
When setting up gitops via the cli I have to go back add my own repositories secret and ssh-config configmaps. It might be nice to allow those to be to passed into the cli like I am able to do with the charts.

**What feature/behavior/change do you want?**
I am not sure what the proper implementation should be. I can see why it would have been left out as you would have something in the cluster that isn't in git, although we are currently doing that with the aws-auth. For my purposes, the ability to specify a configmap name and secret name would suffice, as I could provision the secret/configmap outside of this run.

**Comment by Callisto13** [comment]
Closing due to https://github.com/weaveworks/eksctl/issues/2963
