### ISSUE TITLE
Failed to add cluster information in kubeconfig file

### ISSUE THREAD

**Issue by tahirali-endurance** [weaveworks/eksctl#2270]
**What happened?**
Error: writing kubeconfig: flock: failed to obtain exclusive lock existing kubeconfig file: open /root/.kube/config: no such file or directory

**What you expected to happen?**
The kubeconfig file is created if not exists with cluster context.

**How to reproduce it?**
```bash
eksctl utils write-kubeconfig --cluster=<name>
```

**Anything else we need to know?**
May be the recent change in eksctl about file locking on on kubeconfig is causing this effect. If the kubeconfig file does not exists and eksctl tries lock on non existing file is probably the reason of this issue. Referring the git commit: https://github.com/weaveworks/eksctl/commit/7af34089c1393b987666e6debfa8d777edde772b#diff-811c261701d0690beed656bfd959b131R142

**Versions**
```
$ eksctl version
0.21.0-rc.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

[ℹ]  eksctl version 0.21.0-rc.0
[ℹ]  using region us-east-1
Error: writing kubeconfig: flock: failed to obtain exclusive lock existing kubeconfig file: open /root/.kube/config: no such file or directory

**Comment by tahirali-endurance** [comment]
We used to create kubeconfig file from eksctl even if the file does not exist. Is there a recent change in this behavior?

**Comment by michaelbeaumont** [comment]
It's a bug that was introduced. As you can see, I've already opened a PR to fix it.
