### ISSUE TITLE
include/exclude rules misbehaved and deleted all nodegroups

### ISSUE THREAD

**Issue by AndrewFarley** [weaveworks/eksctl#2276]
**What happened?**
When performing regular maintenance and rotation/upgrades on a cluster I was in the process of rotating nodegroups once at a time, when eksctl decided to "delete" all nodegroups unexpectedly.

**What you expected to happen?**
When I give inclusive/exclusive rules it follows the expected and documented use-case.  Admittedly, I should have every single time ran without `--approve` just to verify and validate what it would do.  While that seems overly cautious, in the future I will run without approve and will intentionally add --exclude rules for every other nodegroup just for paranoia's sake.  This absolutely can not happen to a client of mine or anyone's again.  I believe this to be a bug in the inclusive/exclusive logic.

**How to reproduce it?**
I don't know how to recommend how to reproduce this, but I can confirm my eksctl repeatedly had this problem for a while.  Right now if I want to use an inclusive rule only (which would normally by default exclude everything else) it does not do this.  It grabs all nodegroups.  (See below)

This was my usage path, copy/pasted from my terminal...

```bash
# Created a new nodegroup named 'k8s-1a-m5ad-xlarge-primary' to replace an existing one 'k8s-1a-m5ad-xlarge'
eksctl create nodegroup --config-file=cluster.yaml --include "k8s-1a-m5ad-xlarge-primary"
[ℹ]  1 nodegroup (k8s-1a-m5ad-xlarge-primary) was included (based on the include/exclude rules)
# Deleted JUST the old one...
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1a-m5ad-xlarge" --approve
[ℹ]  1 nodegroup (k8s-1a-m5ad-xlarge) was included (based on the include/exclude rules)
# Created another new node group to replace one in the 1b AZ
eksctl create nodegroup --config-file=cluster.yaml --include "k8s-1b-m5ad-xlarge-primary"
[ℹ]  1 nodegroup (k8s-1b-m5ad-xlarge-primary) was included (based on the include/exclude rules)
# Deleted the old nodegroup
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1b-m5ad-xlarge" --approve
[ℹ]  1 nodegroup (k8s-1b-m5ad-xlarge) was included (based on the include/exclude rules)
# Created a third nodegroup
eksctl create nodegroup --config-file=cluster.yaml --include "k8s-1c-m5ad-xlarge-primary"
[ℹ]  1 nodegroup (k8s-1c-m5ad-xlarge-primary) was included (based on the include/exclude rules)
# Deleted the old nodegroup
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1c-m5ad-xlarge" --approve
[ℹ]  1 nodegroup (k8s-1c-m5ad-xlarge) was included (based on the include/exclude rules)
# Now, on the following node-group I didn't care about needing it highly available since it was a special-purpose nodegroup with no "live" resources on it...
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1a-highmem" --approve
[ℹ]  4 nodegroups (k8s-1a-highmem, k8s-1a-m5ad-xlarge-primary, k8s-1b-m5ad-xlarge-primary, k8s-1c-m5ad-xlarge-primary) were included (based on the include/exclude rules)
```

And right now, no matter what I do, the old logic of single-inclusive being exclusive by default automatically seems to include all items...

```bash
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1c-m5ad-xlarge"
[ℹ]  4 nodegroups (k8s-1a-r5a-2xlarge-highmem, k8s-1b-m5ad-xlarge-primary, k8s-1c-m5ad-xlarge, k8s-1c-m5ad-xlarge-primary) were included (based on the include/exclude rules)
```

So to make things work properly if I want to rotate/delete a nodegroup right now I have to...

```bash
eksctl delete nodegroup --config-file=./cluster.yaml  --include "k8s-1c-m5ad-xlarge" --exclude "k8s-1a-r5a-2xlarge-highmem" --exclude "k8s-1b-m5ad-xlarge-primary" --exclude "k8s-1c-m5ad-xlarge-primary"
[ℹ]  1 nodegroup (k8s-1c-m5ad-xlarge) was included (based on the include/exclude rules)
```

**Anything else we need to know?**
This has severely put a bad taste in my mouth for this tool.  This caused a brief outage of my customer just now.  

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.18.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Log**
Debug Log: https://gist.github.com/AndrewFarley/17a5c403b954ea84f1ae9dee956544c0
Config File: https://gist.github.com/AndrewFarley/7497aed22915210e0df4c975828ecb6b

**Comment by martina-if** [comment]
Hi @AndrewFarley, thank you for reporting this, it sounds very annoying that some nodegroups were unexpectedly deleted.

For the completeness of the example so we can understand what happened, can you post the list of the nodegroups present in the file and in the cluster before the first command was run?
