### ISSUE TITLE
Hanging Application Load Balancers after deleting the cluster

### ISSUE THREAD

**Issue by xinbinhuang** [weaveworks/eksctl#2278]
**What happened?**

I launched a EKS with Fargate, and deploy Ingress objects with Applicationg Load Balancer (ALB) 
 onto the cluter. After I delete the cluster, the ALB did not delete.

**What you expected to happen?**
The ALB will be deleted when we delete the cluster.

**How to reproduce it?**
Include the steps to reproduce the bug

**Anything else we need to know?**
WSL2; Binary Installtion; with default profile

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.20.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by martina-if** [comment]
Hi @xinbinhuang thank you for reporting this. eksctl has some issues regarding deletions. Those are being tracked here #536. We added some extra information in that issue and we will close this one.
