### ISSUE TITLE
Migrate to IMDS2

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#2285]
- Migrate to IMDSv2
- Possibly providing a new utils subcommand that checks if a cluster is using  IMDSv1 for worker nodes

**Comment by michaelbeaumont** [comment]
Please also check if then https://github.com/weaveworks/eksctl/issues/1979#issuecomment-629962708 can be closed

**Comment by michaelbeaumont** [comment]
Closed by

**Comment by michaelbeaumont** [comment]
Option to require added by https://github.com/weaveworks/eksctl/pull/2460
