### ISSUE TITLE
Release url giving pre-release binary

### ISSUE THREAD

**Issue by qlik-okl** [weaveworks/eksctl#2287]
**What happened?**
In our pipeline we use the documented way of getting the latest released version of eksctl by using the address
`https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz`
But to my surprise I notice that this gives me a pre-release version. That is not what I expected.
I got `0.21.0-rc.0` and I wouldn't have noticed unless it made our pipeline stumble upon https://github.com/weaveworks/eksctl/issues/2270 which I assume will be fixed before the actual release of 0.21.0

**What you expected to happen?**
Download latest release of eksctl, e.g. `0.20.0`

**How to reproduce it?**
Follow the installation instructions.

**Anything else we need to know?**

**Versions**
```
$ eksctl version
0.21.0-rc.0
```

**Comment by michaelbeaumont** [comment]
@qlik-okl Yes, that bug is already fixed as you can see in the issue. Probably an `rc.1` release could have been made. The final release will be tomorrow.

However, I can't reproduce this at all. Exactly which file are you downloading?
Where are you redirected when you navigate to [latest release](https://github.com/weaveworks/eksctl/releases/latest)?

**Comment by qlik-okl** [comment]
Thanks for fixing the defect!

Now the latest release link you referenced takes me to 0.20.0, but it didn't an hour ago.
It took me to the pre-release https://github.com/weaveworks/eksctl/releases/tag/0.21.0-rc.0 when I tried it earlier today. I do not know how github manages "latest" but it seems to work now.

/Ola


Ola Eklundh
Sr Build Engineer
Email: Support@qlik.com<mailto:Support@qlik.com>

qlik.com<http://www.qlik.com/>


The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.
________________________________

**Comment by michaelbeaumont** [comment]
OK @qlik-okl , please do make sure you aren't using the `latest_release` **tag** in your pipeline! That used to be the recommended way but it's deprecated and now incidentally points to the latest RC/release
