### ISSUE TITLE
overrideBootstrapCommand requires setting all environment variables from bootstrap.sh

### ISSUE THREAD

**Issue by rtripat** [weaveworks/eksctl#2292]
**What happened?**
overrideBootstrapCommand requires setting all environment variables from bootstrap.sh

**How to reproduce it?**
Create a cluster with `overrideBootstrapCommand` but don't set one of the env variables from default bootstrap.sh. In eksctl 0.10, env variables from default bootstrap.sh got set even if not provided in `overrideBootstrapCommand`. Starting with eksctl 0.20 (or maybe earlier), such params are not being inherited from default bootstrap.sh leading to failures.

Example: Don't set `AWS_SERVICES_DOMAIN` in overrideBootstrapCommand and create a cluster. This will lead to Nodes not joining because the pause container URI constructed will be incomplete and kubelet will fail to pull them. Like `--pod-infra-container-image=602401143452.dkr.ecr.us-east-1./eks/pause-:3.1` which gets generated [here](https://github.com/weaveworks/eksctl/blob/9951d459c0d4dbd65b9463e806288833c67e4f7d/pkg/nodebootstrap/assets/10-eksclt.al2.conf#L22)

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
0.20
```

**Comment by cPu1** [comment]
I do not think this feature was ever supported. The `overrideBootstrapCommand`, as the name indicates, overrides the default `bootstrap.{al2,ubuntu}.sh` script, so if you pass that, the supplied script should provide the behaviour of `bootstrap.{al2,ubuntu}.sh`. The environment variables (like `AWS_SERVICES_DOMAIN`) are set in the default bootstrap script, so if they're not set in the provided script, they'll be empty in the parameters passed to kubelet. 

One of commits in the PR that added the feature (https://github.com/weaveworks/eksctl/pull/522) also says that the override script should resemble the default `bootstrap.{al2,ubuntu}.sh` scripts.

>. Anyone looking to use this will need to define a shell script that would resemble
`bootstrap.{al2,ubuntu}.sh`

**Comment by rtripat** [comment]
> I do not think this feature was ever supported. The `overrideBootstrapCommand`, as the name indicates, overrides the default `bootstrap.{al2,ubuntu}.sh` script, so if you pass that, the supplied script should provide the behaviour of `bootstrap.{al2,ubuntu}.sh`. The environment variables (like `AWS_SERVICES_DOMAIN`) are set in the default bootstrap script, so if they're not set in the provided script, they'll be empty in the parameters passed to kubelet.
> 
> One of commits in the PR that added the feature (#522) also says that the override script should resemble the default `bootstrap.{al2,ubuntu}.sh` scripts.
> 
> > . Anyone looking to use this will need to define a shell script that would resemble
> > `bootstrap.{al2,ubuntu}.sh`

There is a change in behavior between 0.10 and 0.20 where setting all the env variables wasn't required in 0.10. Can you confirm this?

**Comment by cPu1** [comment]
>There is a change in behavior between 0.10 and 0.20 where setting all the env variables wasn't required in 0.10. Can you confirm this?

As I mentioned, I don't think this was ever supported. The tree for `0.10` shows that all environment variables were still set in `bootstrap.al2.sh` (and `bootstrap.ubuntu.sh`), and it was not invoked if `nodeGroup.overrideBootstrapCommand` was set: https://github.com/weaveworks/eksctl/blob/0.10.0/pkg/nodebootstrap/userdata_al2.go#L60-L64.

So if the script in `overrideBootstrapCommand` did not set those environment variables, they would end up as empty in the parameters passed to kubelet in the systemd unit file. So this behaviour hasn't changed between 0.10 and 0.20.
