### ISSUE TITLE
Creating nodegroups with kubernetes.io/role labels fails validation

### ISSUE THREAD

**Issue by DavidWittman** [weaveworks/eksctl#2296]
**What happened?**

I tried to create a nodegroup with the label `kubernetes.io/role=somerole`.

**What you expected to happen?**

My nodegroup to create

**How to reproduce it?**

Try to create a nodegroup with the `kubernetes.io/role` label, e.g.:

``` yaml
  - name: nodegroup-with-role
    labels:
      kubernetes.io/role: anything
```

**Anything else we need to know?**

Seems related to https://github.com/weaveworks/eksctl/issues/2197, specifically [this comment](https://github.com/weaveworks/eksctl/issues/2197#issuecomment-635860961) by @TBBle

**Versions**
```
$ eksctl version
0.20.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:50:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```
$ eksctl create nodegroup -f preprod.yaml
Error: unknown 'kubernetes.io' or 'k8s.io' labels were specified: [kubernetes.io/role]
```

**Comment by Vitorspk** [comment]
found same error when try to create nodeGroup using version 0.22.0

**Comment by Vitorspk** [comment]
Already test on version 0.19.0 and work.

**Comment by TBBle** [comment]
@Vitorspk What version of Kubernetes was your 0.19.0 test against? Per #2197 , kubernetes 1.16 and later would have hung as the nodes would never have started. Before 1.16, this usage was only deprecated, not blocked. eksctl now mirrors the blocking behaviour to prevent hung cluster startups.

**Comment by michaelbeaumont** [comment]
Moving discussion about this feature to https://github.com/weaveworks/eksctl/issues/2363
