### ISSUE TITLE
Migrate 'kubeconfig' tests to Ginkgo

### ISSUE THREAD

**Issue by richardcase** [weaveworks/eksctl#230]
**Why do you want this feature?**
Bring the [kubeconfig](https://github.com/weaveworks/eksctl/tree/master/pkg/utils/kubeconfig) package in line with the adopted testing approach by changing the tests to use:
- Ginkgo
- Golden Files 

For an example see the [printers](https://github.com/weaveworks/eksctl/tree/master/pkg/printers) package.

**What feature/behavior/change do you want?**
Change the tests to use Ginkgo and golden files.

related to #226

**Comment by richardcase** [comment]
Great thanks @denwwer 👍

**Comment by errordeveloper** [comment]
Closed via #238! @denwwer you should be able to claim your hacktoberfest t-shirt now!
