### ISSUE TITLE
Can't create a cluster with gitops in one command

### ISSUE THREAD

**Issue by Booyaka27** [weaveworks/eksctl#2305]
Hi, I'm trying to follow this step for configuring gitops directly from my cluster yaml file and it looks to lack a key and don't know where and how to add it ... 

Si I follow this https://eksctl.io/gitops-quickstart/#creating-a-cluster-with-gitops-in-one-command and add git repo to my yaml file, when I run it, I get this error:

</
Error: loading config file "rider.yaml": error converting YAML to JSON: yaml: line 16: did not find expected key
/>

**Comment by michaelbeaumont** [comment]
@Booyaka27 Can you please post the config file?

**Comment by Booyaka27** [comment]
@michaelbeaumont here it is

[configFile.txt.zip](https://github.com/weaveworks/eksctl/files/4756612/configFile.txt.zip)

**Comment by michaelbeaumont** [comment]
@Booyaka27 please check the formatting of the file. your `git.operator` and `git.bootstrapProfile` keys are indented further than `git.repo`.
