### ISSUE TITLE
Managed nodegroup Instance names are blank

### ISSUE THREAD

**Issue by neilharris123** [weaveworks/eksctl#2311]
From my tests, currently, it seems instances that belong to managed nodegroups are not named, and that there is also no way currently to name them.

The names of the instance are blank. 

Am I missing something obvious? Or is this a current limitation of using managed nodegroups? I would have thought they would have at least inherited from the name of the nodegroup or elsewhere?

**Comment by smrutiranjantripathy** [comment]
It is because currently managed nodegroup api call doesn't tag the asg
https://github.com/aws/containers-roadmap/issues/608

**Comment by cPu1** [comment]
Support for naming the EC2 instances for managed nodegroups is out in [0.26.0-rc.1]https://github.com/weaveworks/eksctl/releases/tag/0.26.0-rc.1).
