### ISSUE TITLE
Add option to launch all nodes into the same AZ

### ISSUE THREAD

**Issue by armandmcqueen** [weaveworks/eksctl#232]
**Why do you want this feature?**
We are running ML training workloads on EKS that are very sensitive to network latency. For performance reasons, we need our nodes to exist in a single AZ. Using `--zones` with a single AZ raises an error.

**What feature/behavior/change do you want?**
When launching a new cluster, I would like to be able to pass in a single AZ with the `--zones` option or to have a `--single-az` flag that forces nodes to launch into the same AZ. 

Any workflow that is less unwieldy than manually altering the AutoScaling group's subnet list would be helpful.

**Comment by gruebel** [comment]
Hi,
This is not possible due to API restrictions of AWS. You need to specify at least two Subnets in two different AZs.

**Comment by errordeveloper** [comment]
@armandmcqueen I'm curious to know what happens if you pass e.g. `--zones us-west-2a,us-west-2a,us-west-2a`?

@gruebel is that an EKS API requirement, or something else?

I think in the future, we should be able to allow this to happen for individual node-groups, perhaps `--single-az` would makes sense in that context. It'd be nice to allow users to have single-AZ nodegroups at the same time as nodegroups that span multiple AZs.

**Comment by errordeveloper** [comment]
We will be able to do this very easily soon (namely after #257).

**Comment by errordeveloper** [comment]
@richardcase as you are working on #281, there's now a `NodeGroup.AvailibilityZones` field that can be leveraged for this, and I think it would be sufficient to just expose it as a flag as there is plumbing already in place.

https://github.com/weaveworks/eksctl/blob/99b5d58d340660ba7299ee470888b022754a2d8e/pkg/cfn/builder/nodegroup.go#L113-L122

**Comment by errordeveloper** [comment]
This is definitely done now, and we have ironed out a bug in this week - #432.

**Comment by dnascimento** [comment]
Does it assume only one subnet per AZ? Can we deploy on multiple subnets in the same AZ?

**Comment by errordeveloper** [comment]
No, it is single subnet per AZ. If you have a particular use-case, please
open an issue with more details of that use-case.
