### ISSUE TITLE
eksctl get nodegroups reports ASG Desired Size, not CF Desired Size

### ISSUE THREAD

**Issue by TBBle** [weaveworks/eksctl#2331]
**Why do you want this feature?**

As a shorthand way of checking cluster scaling state, `eksctl get nodegroups --cluster X` is tempting.

However, it doesn't show the _current_ state, as updated by (for example) the Cluster Autoscaler.

This caught me out when I was trying to change the max size of a nodegroup with `eksctl scale nodegroup`, and you must provide the `--nodes` parameter to that, I used the value from `eksctl get nodegroups`, not realising this would scale the nodegroup back down to 1, until the Cluster Autoscaler was able to scale it back up.

This particular use-case was working around a different issue: #2332, but at the time I assumed CA had done its job between my two commands. It's only today, that when using `eksctl get nodegroups` and comparing it to `kubectl get nodes` that I realised the former never showed the effects of CA.

**What feature/behavior/change do you want?**

`eksctl get nodegroups --cluster X` should show the current capacity (the ASG Desired Size as updated by Cluster Autoscaler or other process), instead of the desired capacity (the CloudFormation value, set at original build-time to some arbitrary number, knowing that CA would fix it).

Perhaps you could argue that the fault lies in Cluster Autoscaler, as it changes the ASG and not the CloudFormation that created it, but I feel like that would be an uphill argument.

**Comment by pikeas** [comment]
Strongly agree, it's very confusing that after launching a new cluster,`eksctl get nodegroup` shows a Desired Capacity of `0`!

**Comment by TBBle** [comment]
I'd still like this improvement.

**Comment by TBBle** [comment]
I'd still like this improvement.
