### ISSUE TITLE
Failure to create instance types c5a.24xlarge or m5a.24xlarge

### ISSUE THREAD

**Issue by krzemienski** [weaveworks/eksctl#2333]
**What happened?**
Failure to deploy node group with machine type c5a.24xlarge or m5a.24xlarge.

**What you expected to happen?**
A nodegroup of c24.xlarge is deployed

**How to reproduce it?**
Try and create any cluster with c5a.24xlarge set as instance type. 

**Anything else we need to know?**
I can note that type c5ad.24xlarge DOES work though. The issue isolated to just the “a” instance types. 

Running a workstation with Ubuntu 20.04

The command will eventually time out waiting for the actual instance to start up. When you check if there is an instance in the auto scaling group there actually is! 

My stab at debugging points to an issue with the aws-node deployment and then communication back to the control plane. 

**Versions**
Please paste in the output of these commands:
Eksctl 0.21.0
Kubectl 1.18

**Comment by blakestoddard** [comment]
I noticed this today with `c5a` instances, looks like they're missing in https://github.com/weaveworks/eksctl/blob/f401b5e97f9bbbe989196a221a3237e3d64834fa/pkg/nodebootstrap/maxpods.go. I'll get a PR going to add them.
