### ISSUE TITLE
Document all config file fields

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#2340]
- [x] VPC - chetan
- [x] IAM - chetan
- [x] nodegroups - mike
- [x] fargate - martina (already there)
- [x] cloudwatch - martina (#2394)
- [x] git - martina (#2394)
- [x] one last look, optimize if possible (enums, defaults) - Mike

**Comment by michaelbeaumont** [comment]
Documentation has been greatly improved over all
