### ISSUE TITLE
Managed Node Group Stack fails while creating using eksctl

### ISSUE THREAD

**Issue by sabreeshbhatt** [weaveworks/eksctl#2352]
When trying to create a cluster with managed node group, the cluster stack gets created successfully but the managed node group stack fails every-time. The error received is that ip address cannot be auto assigned. So the only possible way right now is to create a cluster first ; then manually go and enable auto assign ip address for each subnet which the cluster is using and then finally create a managed node group.

**Comment by cPu1** [comment]
The public subnets eksctl creates do have public IP assignment (`MapPublicIpOnLaunch` ) enabled. It appears you're using an old version of eksctl. Upgrading to a more recent version of eksctl should fix the issue.

**Comment by sabreeshbhatt** [comment]
Got it!
Thanks :)
