### ISSUE TITLE
feat(nodegroup): Integrate Spot Ocean with Nodegroups

### ISSUE THREAD

**Issue by liranp** [weaveworks/eksctl#2364]
**Why do you want this feature?**
Similarly to the existing [integration with kops instance groups](https://kops.sigs.k8s.io/getting_started/spot-ocean/), we'd like to integrate [Ocean](https://spot.io/products/ocean/) by [Spot](https://spot.io/) with eksctl.

**What feature/behavior/change do you want?**
Seamlessly integration of [Ocean](https://spot.io/products/ocean/) with unmanaged nodegroups, as a drop-in replacement for AWS Auto Scaling groups.

**Pull request**
#2358

**Comment by markramm** [comment]
The feature description for this is quite short, given the quantity of code it adds to the project.   My concern here is that there is not enough user demand to justify the maintenance burden of adding Ocean support to the project.  

Given that the feature seems to just enable a commercial product, and that there is not yet evidence of community demand (there is no discussion or reactions on the issue), I don't believe that this is a good fit for eksctl at this time.

**Comment by jescarri** [comment]
We at ticketmaster run our clusters 100% on spot instances and we use spot.io, and we are in the process of using eks + eksctl.

Would be awesome if Ocean gets first class integration with eksctl.

**Comment by sstanfor** [comment]
This allows us to easily spin up / tear down cost efficient EKS cluster. It would be great to see this integrated into eksctl

**Comment by igor-feoktistov** [comment]
eksctl is a game changer for us. Looking forward to see when you merge it to main eksctl repo.

**Comment by jshrack-ssi** [comment]
While I agree this promotes a commercial product the full PR has been provided to enable the feature set and it does seem like a useful extension to eksctl. I say leave it up to the user to determine the value of the product and so long as it doesn't adversely affect the code quality or sustainability I don't see why the PR shouldn't be merged.

**Comment by mataneja** [comment]
Hi @markramm / @martina-if Can we please discuss this upstreaming issue? Spot team is happy to own the maintenance burden for all things Ocean and Spot. In fact, `kops` upstream has taken a similar approach to all partner integrations. For reference, please find the equivalent ownership here:

https://github.com/kubernetes/kops/blob/d5d08a43034dd4c7242cf1faa020cf9a8c3965e2/upup/pkg/fi/cloudup/spotinsttasks/OWNERS

and this is specific to the Spotinst provider for Kops. I would love to spend some time with you and understand what your concerns are at this time so we can come up with an action plan to address them and move things forward.

**Comment by alan-ghelardi** [comment]
+1 to include this feature in the upstream project. Ocean is widely used and having an out of the box integration with eksctl would be extremely valuable to keep a fluid GitOps workflow in the EKS/ocean management.

**Comment by joshdlee** [comment]
+1 I would love to see Ocean support @markramm

**Comment by Callisto13** [comment]
cc @mikestef9 / @tabern

**Comment by jescarri** [comment]
bumping the feature request.

**Comment by Callisto13** [comment]
@mikestef9 / @tabern could one of you summarise our decision on this please?

**Comment by jescarri** [comment]
Is there any update on this feature?

Tnx

**Comment by mataneja** [comment]
Would appreciate if someone can explain what is needed to move this forward?

**Comment by mataneja** [comment]
> eksctl is official CLI tool for EKS and will include support only for native integrations with EKS

@mikestef9 @aclevername Ocean by Spot is a native integration to EKS. Effectively, 
                Ocean ~=  EKS Managed Node Groups

Can you please help us understand where the discrepancy is?

**Comment by mataneja** [comment]
@shapirov103 Appreciate the update. We are trying to integrate with AWS native services directly. This is exactly what Ticketmaster, Nubank, NetApp and other users (per the comments above) have indicated above. We are happy to own the maintenance burden and drive the integration and future support. Having this upstream would remove the significant burden that we and our mutual users need to take on in order to support the respective products.
