### ISSUE TITLE
SourceSecurityGroupIDs doesn't work in unmanaged node group, but this is not mentioned in the config schema.

### ISSUE THREAD

**Issue by readybuilderone** [weaveworks/eksctl#2366]
In the config file schema(https://eksctl.io/usage/schema/) I found the SourceSecurityGroupIDs cloud be used for both managed node group and unmanaged nodegroup. 

However, when I tried to create unmanaged nodegroup with SourceSecurityGroupIDs, I run in to the error:
"Error: nodeGroups[0].sourceSecurityGroupIds is not supported for unmanaged nodegroups"

For double confirm, I generated the schema using command: "eksctl utils schema" and found the SourceSecurityGroupIDs cloud be used for both managed node group and unmanaged nodegroup as well. 

I did some research and found the validation in this file(https://github.com/weaveworks/eksctl/blob/a7fc5f6e8adc9e5581d7d8d128c7ed806675bb0f/pkg/apis/eksctl.io/v1alpha5/validation.go):
``` shell
	if ng.SSH != nil {
		if err := validateNodeGroupSSH(ng.SSH); err != nil {
			return err
		}
		if len(ng.SSH.SourceSecurityGroupIDs) > 0 {
			return fmt.Errorf("%s.sourceSecurityGroupIds is not supported for unmanaged nodegroups", path)
		}
	}
``` 

So I think the config schema should be wrong, the sourceSecurityGroupIds should be marked, it is not supported for unmanaged nodegroups.

**Comment by zmarouf** [comment]
Bump. What's the actual expected state? Will it be supported or should I just use a local/shared/extra attached security group for this on unmanaged nodegroups?
Thank you in advance for clearing this up! :)

**Comment by cPu1** [comment]
> Bump. What's the actual expected state? Will it be supported or should I just use a local/shared/extra attached security group for this on unmanaged nodegroups?
> Thank you in advance for clearing this up! :)

We have decided to add support for `sourceSecurityGroupIds` for unmanaged nodegroups. There's no reason not to support it. This feature can be tracked in this PR: https://github.com/weaveworks/eksctl/pull/3254

**Comment by cPu1** [comment]
The PR has been merged and it'll be out in the next release.
