### ISSUE TITLE
Running eksctl from a pod in the cluster

### ISSUE THREAD

**Issue by severi** [weaveworks/eksctl#2367]
**Why do you want this feature?**
I am using eksctl in my CI/CD pipelines. The pipeline is running on Jenkins nodes inside of the kubernetes cluster (using Jenkins kubernetes plugin). It seems that eksctl is unable to authorize it's actions towards the kubernetes API using the pod's service account. It would be great if this would be possible (and seems pretty easy to implement https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-within-a-pod).

**What feature/behavior/change do you want?**
eksctl should be able to authorize it api calls towards kubernetes using the service account, if run inside of a pod in the kubernetes cluster.

**Comment by opsroller** [comment]
This is a terrible idea, I believe what you are looking for is Flux, or ArgoCD.

**Comment by severi** [comment]
> This is a terrible idea, I believe what you are looking for is Flux, or ArgoCD.

Thanks for the constructive reply.

Unfortunately I don't see how flux or argocd would magically solve the above mentioned problem. To repeat, I am using eksctl to bind aws iam roles to kubernetes service accounts and according to the aws docs eksctl is the preferred way to do this (https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html). So in my eyes this is a valid request, though please do enlighten me if there's a better way to achieves this than eksctl.

**Comment by michaelbeaumont** [comment]
Hi @severi, how exactly would you call `eksctl` in this case?

**Comment by opsroller** [comment]
Fair enough, eksctl should use the KUBECONFIG if available. Also, if your using kubernetes for jenkins builders, you’ll need to set the appropriate service account in the podtemplate.

On that, you should separate the build steps so that you only grant the steps that use eksctl access to the builders that have access.

**Comment by severi** [comment]
> Fair enough, eksctl should use the KUBECONFIG if available. Also, if your using kubernetes for jenkins builders, you’ll need to set the appropriate service account in the podtemplate.

Exactly

> On that, you should separate the build steps so that you only grant the steps that use eksctl access to the builders that have access.

Agreed

> Hi @severi, how exactly would you call `eksctl` in this case?
> As for `flux`, as long as you're calling the AWS API, it won't be enough. But that also means `eksctl` needs to be able to call the AWS API from inside your pod.

I have created a container that has the AWS-cli and eksctl installed and use that on my `eksctl`step in the pipeline. And as mentioned above, I am also using a separate service account in this particular build step that has the sufficient permissions towards AWS.
