### ISSUE TITLE
Add possibility to add SSM agent + IAM policy (addon)

### ISSUE THREAD

**Issue by mseiwald** [weaveworks/eksctl#237]
**Why do you want this feature?**
Having SSM agent installed enables running commands and SSH-like sessions using the new SSM Session manager. This would remove the need to add SSH public keys to the instance and opening ports.

**What feature/behavior/change do you want?**
The following changes would have to be made:
* [install ssm-agent](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-manual-agent-install.html#agent-install-al) in user-data
* add IAM policy for SSM agent, it should be sufficient to add the `AmazonEC2RoleforSSM` managed policy. [docs](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-configuring-access-role.html)

**Comment by errordeveloper** [comment]
Can the agent run in a pod?

**Comment by mumoshu** [comment]
We've been installing ssm-agent in user-data in [kube-aws](https://github.com/kubernetes-incubator/kube-aws) and from my exp, I'd say it isn't an optimal solution.

The first reason comes up in my mind at the moment is that you'll need more and more binaries to be present. Enhancing eksctl every time such request arises won't work long term for project maintainers.

Plus, it does slow down node startup.

I would instead suggest documenting the process of (1)adding arbitrary tools to the official AMI using `packer` and (2)specifying the resulting AMI ID like `eksctl create cluster --node-ami AMI`.

You do need to add IAM policy for ssm-agent to work. For that, enabling `eksctl create cluster` to accept an IAM role created by the user would work. `eksctl` should not create the IAM role in that case. Instead, it should just create IAM policies and attach it to the precreated role. The attachment can be completely done in CFN templates.

WDYT?

**Comment by errordeveloper** [comment]
How about running the agent as a pod, i.e. a daemonset add-on?

**Comment by whereisaaron** [comment]
AWS in documentation says their AMI’s have the agent installed by default. It might be there and just have to be (optionally) started. Have you checked @mseiwald?

**Comment by mumoshu** [comment]
@errordeveloper Completely understood! Let's add `--allow-ssm-agent` then.

> explore option of running the SSM agent as a pod (via a daemonset or otherwise).

I've just published my working example of ssm-agent-as-daemonset at https://github.com/mumoshu/kube-ssm-agent

Other than creating a daemonset, it was just a matter of running the below to give the IAM permissions required for ssm-agent to work:

```console
$ aws iam attach-role-policy --role-name eksctl-amazing-creature-154580785-NodeInstanceRole-RXNVQC8YTLP7 --policy-arn arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
```

So, I would just add `arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM` to `PolicyARNs` when `--allow-ssm-agent` is provided.

Does that sound good to you?

**Comment by mumoshu** [comment]
With #411, you should be able to run `eksctl create cluster --node-role-policies arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM`.

**Comment by mseiwald** [comment]
@whereisaaron The EKS AMI does not include SSM agent. From what I see there are three possibilities

- Create custom AMI
- Install SSM agent during instance startup
- run SSM agent as K8s daemon set

`--node-role-policies ` helps with the setup 👍 

From my pov this can be closed.

**Comment by errordeveloper** [comment]
Please keep in miss that the flag is '--temp-node-role-policies', as it is
a temporary flag that will get moved to config file in a few releases.

**Comment by whereisaaron** [comment]
@errordeveloper a config file is good and I know @mumoshu prefers that, but there is also not much wrong IMHO with being able to set everything from a million options on the command line too. Gcloud tends to do this, and it is actually quite pleasant and fast and easy to work with and automate and version.

I'd actually prefer some sort of universal mapping between config and command line options, either from one of those uber CLI option mapping libraries or a `--set x.y.z=foo` approach like you get with `helm`; rather than taking away the command line option, just because there is an equivalent config file option. It's not critical, but that's my personal preference.

**Comment by ozbillwang** [comment]
it has been supported, the key point is to add iam policy `AmazonSSMManagedInstanceCore` to node instance profile, and I saw the latest eksctl has done that already.

**Comment by ozbillwang** [comment]
The key point is to add iam policy `AmazonSSMManagedInstanceCore` to node instance profile
