### ISSUE TITLE
Document iam.withAddonPolicies options

### ISSUE THREAD

**Issue by michaelbeaumont** [weaveworks/eksctl#2371]
There's a list of options at https://github.com/weaveworks/eksctl/blob/9bcfafe55ece4334a8cee10c6c27749959c1b021/pkg/apis/eksctl.io/v1alpha5/types.go#L887-L911 but there's no documentation on what actions they allow.

See https://github.com/weaveworks/eksctl/issues/937#issuecomment-612660226 for some background and some links to the implementation here https://github.com/weaveworks/eksctl/issues/937#issuecomment-644012513

Ideally this would be automated somehow.

**Comment by ahmetcetin** [comment]
Just trying to find out what those add on policies are for,  googling, checking here and there, really not easy to find out. Would be great to document those options. I'm a newbie in EKS, and trying to set things up properly.

**Comment by viktormohl** [comment]
Hello, the above options add the respective AWS Policies to the NodeGroup, please see the iam.go-file l. 19 and iam_helper.go l.165 (https://github.com/weaveworks/eksctl.git).

```iam.go
const (
	iamPolicyAmazonEKSClusterPolicy         = "AmazonEKSClusterPolicy"
	iamPolicyAmazonEKSVPCResourceController = "AmazonEKSVPCResourceController"

	iamPolicyAmazonEKSWorkerNodePolicy           = "AmazonEKSWorkerNodePolicy"
	iamPolicyAmazonEKSCNIPolicy                  = "AmazonEKS_CNI_Policy"
	iamPolicyAmazonEC2ContainerRegistryPowerUser = "AmazonEC2ContainerRegistryPowerUser"
	iamPolicyAmazonEC2ContainerRegistryReadOnly  = "AmazonEC2ContainerRegistryReadOnly"
	iamPolicyCloudWatchAgentServerPolicy         = "CloudWatchAgentServerPolicy"
	iamPolicyAmazonSSMManagedInstanceCore        = "AmazonSSMManagedInstanceCore"

	iamPolicyAmazonEKSFargatePodExecutionRolePolicy = "AmazonEKSFargatePodExecutionRolePolicy"
)
```

```iam_helper.go
if api.IsEnabled(iamConfig.WithAddonPolicies.CloudWatch) {
   managedPolicyNames.Insert(iamPolicyCloudWatchAgentServerPolicy)
}
```
