### ISSUE TITLE
Creating additional AZ specified managed node groups fails in a cluster with only private subnets

### ISSUE THREAD

**Issue by hiraken-w** [weaveworks/eksctl#2375]
**What happened?**

Creating additional AZ specified managed node groups fails in a cluster with only private subnets.
I got the following error message:

``` shellsession
[ℹ]  eksctl version 0.22.0
[ℹ]  using region us-west-2
[ℹ]  will use version 1.16 for new nodegroup(s) based on control plane version
Error: VPC doesn't have enough subnets for nodegroup AZs (subnets=map[string]v1alpha5.Network(nil) AZs=[]string{"us-west-2a"})
```

**What you expected to happen?**

We can create managed node groups that use specified zones without error messages.

**How to reproduce it?**

Include the steps to reproduce the bug

1. Create a cluster with only private subnets.

``` shellsession
eksctl --region us-west-2 create cluster --name [cluster name] \
    --vpc-private-subnets [private subnet(us-west-2a)],[private subnet(us-west-2b)] \
    --without-nodegroup
```

2. Create AZs specified managed node group. (using --node-zones)

``` shellsession
eksctl --region us-west-2 create nodegroup --cluster=[cluster name] \
    --name=ng \
    --nodes 1 \
    --node-private-networking \
    --node-zones us-west-2a \
    --managed
```

In this case, the following error message is output:

``` shellsession
[ℹ]  eksctl version 0.22.0
[ℹ]  using region us-west-2
[ℹ]  will use version 1.16 for new nodegroup(s) based on control plane version
Error: VPC doesn't have enough subnets for nodegroup AZs (subnets=map[string]v1alpha5.Network(nil) AZs=[]string{"us-west-2a"})
```

This error occurs in the following places:
https://github.com/weaveworks/eksctl/blob/0.22.0/pkg/ctl/create/nodegroup.go#L167-L169
https://github.com/weaveworks/eksctl/blob/0.22.0/pkg/vpc/vpc.go#L234
https://github.com/weaveworks/eksctl/blob/0.22.0/pkg/vpc/vpc.go#L393

``` golang
	if len(subnets) < numNodeGroupsAZs {
		return nil, fmt.Errorf("VPC doesn't have enough subnets for nodegroup AZs %s", makeErrorDesc())
	}
```

Public subnets are checked even though private subnets are used.

**Anything else we need to know?**

* This issue occurs even when using config file.
* This issue does not occur using self-managed node groups.

**Versions**

Please paste in the output of these commands:
``` shellsession
$ eksctl version
0.22.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:57:29Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aclevername** [comment]
Closing due to staleness. Feel free to re-open if this is still an issue.
