### ISSUE TITLE
Eksctl creating worker nodes with too much reserved memory for kubelet

### ISSUE THREAD

**Issue by avasquez614** [weaveworks/eksctl#2395]
We've been using `eksctl` for a while and it has been working wonderfully. However, a couple of months ago we've noticed that the nodes that `eksctl` was creating had too much `kubeReserved` memory. For example, just yesterday I created a 1.14 EKS cluster, with a single `m5.xlarge` worker, and this is what it has for `kubeReserved`:

```
"kubeReserved": {
    "cpu": "80m",
    "ephemeral-storage": "1Gi",
    "memory": "2662Mi"
  }
```

I had made some research before and I thought it was because of this issue with the AWS AMIs: https://github.com/awslabs/amazon-eks-ami/issues/387, but according to one of the devs that issue has already been resolved. So now I don't really know what's causing so much memory to be reserved for the kubelet. Any ideas?

**Comment by avasquez614** [comment]
By the way this is the info on the node:

```
Kernel Version:             4.14.181-140.257.amzn2.x86_64  
Kube Proxy Version:         v1.14.9-eks-49202c 
Kubelet Version:            v1.14.9-eks-49202c 
Operating System:           linux
Os Image:                   Amazon Linux 2
```

**Comment by brianpursley** [comment]
Are you thinking that the memory is calculation is wrong, or that the calculation is performing correctly, but that the amount it returns is higher than you think it should be?

I didn't do the math, but 2662Mi reserved on a 16Gi instance seems to match how the calculation is designed.

See these comments I found explaining how eksctl calculates the value:
https://github.com/weaveworks/eksctl/blob/0afe5f1ff23a87eda004662cd278a1e5d5f6b20a/pkg/nodebootstrap/reserved.go#L94-L104

And these test cases showing the calculated values for a few memory sizes.  There isn't a test case for 16Gi, but there is one for 12Gi and it reserves 2252Mi:
https://github.com/weaveworks/eksctl/blob/0afe5f1ff23a87eda004662cd278a1e5d5f6b20a/pkg/nodebootstrap/reserved_test.go#L30-L37

It looks like the algorithm eksctl uses matches what is in [amazon-eks-ami](https://github.com/awslabs/amazon-eks-ami/blob/ff690788dfaf399e6919eebb59371ee923617df4/files/bootstrap.sh#L150-L163)

**Comment by brianpursley** [comment]
Oh., I think I see what you are saying.
In the merged PR, it shows hat the reservations are reduced quite a bit. I wonder what happened to that PR because it doesn’t seem to reflect in the code.

> t3.small (2 vCPU, 2 GiB, 11 pods): 321 Mi
> t3.medium (2 vCPU, 4 GiB, 17 pods): 357 Mi
> t3.large (2 vCPU, 8 GiB, 35 pods): 465 Mi
> t3.xlarge (4 vCPU, 16 GiB, 58 pods): 603 Mi
> t3.2xlarge (8 vCPU, 32 GiB, 58 pods): 603 Mi
> m5.4xlarge (16 vCPU, 64 GiB, 234 pods): 1659 Mi
> m4.10xlarge (40 vCPU, 160 GiB, 234 pods): 1659 Mi
> m5.12xlarge (48 vCPU, 192 GiB, 234 pods): 1659 Mi
> r4.8xlarge (32 vCPU, 244 GiB, 234 pods): 1659 Mi
> m5.24xlarge (96 vCPU, 384 GiB, 737 pods): 4677 Mi

**Comment by avasquez614** [comment]
@brianpursley Oh I think I understand. Eksctl sets its own reserved memory instead of using the AMI one correct? Does eksctl needs to change then too to follow the AMI reservation or are you guys going to keep the reservation the way it is right now? I just think it's a little bit too much.

**Comment by brianpursley** [comment]
@avasquez614 yes, it appears so. I agree with you though, it looks like it doesn’t match what the ami does, so eksctl probably needs to be changed.

I’m not an eksctl dev, so I will defer to them, but I wonder if there is a way to not have to duplicate the logic because it can get out of sync like it is now.

**Comment by avasquez614** [comment]
Thanks for your help @brianpursley. Is it possible to change this ticket to a possible bug?

**Comment by brianpursley** [comment]
😆 wow, I didn’t realize my commit would tag this so much. Sorry for the noise. 

I am working on a potential PR to sync up the reserved memory calc.

**Comment by brianpursley** [comment]
@michaelbeaumont were you already working on this?
