### ISSUE TITLE
unable to create cluster using yaml file , showing error 

### ISSUE THREAD

**Issue by Abhilash-sandupatla** [weaveworks/eksctl#2396]
I have installed eksctl on my system, and craeted a Cluster1.yml file. code is fyn. But when i run t showing the below error...Please check and help me 

eksctl create cluster -f Cluster1.yml 
[ℹ]  eksctl version 0.23.0
[ℹ]  using region ap-south-1
[ℹ]  setting availability zones to [ap-south-1b ap-south-1c ap-south-1a]
[ℹ]  subnets for ap-south-1b - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for ap-south-1c - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for ap-south-1a - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng1" will use "ami-073969767527f7306" [AmazonLinux2/1.16]
[ℹ]  nodegroup "ng2" will use "ami-073969767527f7306" [AmazonLinux2/1.16]
[ℹ]  using Kubernetes version 1.16
[ℹ]  creating EKS cluster "abhicluster" in "ap-south-1" region with un-managed nodes
[ℹ]  2 nodegroups (ng1, ng2) were included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 2 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=ap-south-1 --cluster=abhicluster'
[ℹ]  CloudWatch logging will not be enabled for cluster "abhicluster" in "ap-south-1"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=ap-south-1 --cluster=abhicluster'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "abhicluster" in "ap-south-1"
[ℹ]  2 sequential tasks: { create cluster control plane "abhicluster", 2 sequential sub-tasks: { no tasks, 2 parallel sub-tasks: { create nodegroup "ng1", create nodegroup "ng2" } } }
[ℹ]  building cluster stack "eksctl-abhicluster-cluster"
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=ap-south-1 --name=abhicluster'
[✖]  creating CloudFormation stack "eksctl-abhicluster-cluster": AlreadyExistsException: Stack [eksctl-abhicluster-cluster] already exists
	status code: 400, request id: 5e68bda3-0fd2-4532-97a3-b5a9d9fa1e89
Error: failed to create cluster "abhicluster"

**Comment by sayboras** [comment]
From the first look, it seems like you already have the cluster __abhicluster__. 

```
creating CloudFormation stack "eksctl-abhicluster-cluster": AlreadyExistsException: Stack [eksctl-abhicluster-cluster] already exists
```

**Comment by michaelbeaumont** [comment]
Let us know if changing the name or deleting the old cluster doesn't resolve it!
