### ISSUE TITLE
Add Antivirus agents in Worker node

### ISSUE THREAD

**Issue by venksel** [weaveworks/eksctl#2398]
Hi Friends,
Using EKS v1.16 which was setup using eksctl.

Any insights on how to include an agent for e.g., anti-virus agent in the worker nodes so it gets auto installed in new/existing nodes as the node group scales/shrinks.

Thanks for your help in advance.

**Comment by sayboras** [comment]
I think that the above use case is not really eksctl's job :). Any additional software/application should be installed and managed separately. eksctl can provide a little bit of help with IAM permission for _common use case_ though.

Going back to your case, k8s deamonset or deployment will probably help.
