### ISSUE TITLE
update fargate profile

### ISSUE THREAD

**Issue by runningman84** [weaveworks/eksctl#2399]
**Why do you want this feature?**
I would like to update my fargate profiles because some requirements changed after the initial setup.

**What feature/behavior/change do you want?**
I would like to update an existing profile using eksctl update fargateprofile similar to update cluster.

We have a cicd pipeline which creates and updates clusters according to an env.yaml file in a central git repo. Our piplines is able to handle cluster and node upgrade but we cannot implement fargateprofile updates yet...

**Comment by martina-if** [comment]
Hi @runningman84, as far as I know the fargate profiles [are immutable by design](https://docs.aws.amazon.com/eks/latest/userguide/fargate-profile.html) so I don't think eksctl will support updates.

**Comment by runningman84** [comment]
But there could be a replace option or something like that.

**Comment by michaelbeaumont** [comment]
@runningman84 Would using `eksctl delete fargateprofile && eksctl create fargateprofile` work for your use case?

**Comment by runningman84** [comment]
yes that would work if I could specify the configfile as an option... 

My goal is to have some update and replace command which I can run in my cluster create/update ci pipeline...

it should just verify if the profiles in the yml are present or remove them and create new profiles. Right know I have to loop through all profiles verify and delete them myself and create them again using eksctl... this could be easier from my point of view...
