### ISSUE TITLE
Add YAML file option for cluster deletion

### ISSUE THREAD

**Issue by inductor** [weaveworks/eksctl#2400]
**Why do you want this feature?**
At cluster creation you can use a YAML file to make the operation simpler and declarative. However, you need to specify your cluster name and region when you want to delete them.

**What feature/behavior/change do you want?**
Add -f option for `eksctl delete cluster`

**Comment by brianpursley** [comment]
I think this is there at least in version 0.23.0.

```
$ eksctl delete cluster --help
Delete a cluster

Usage: eksctl delete cluster [flags]
...
  -f, --config-file string   load configuration from a file (or stdin if set to '-')
...
```

 I've been using it like this and it deletes my cluster, load balancer, instances, etc:
```
eksctl delete cluster -f cluster.yaml
```

**Comment by inductor** [comment]
I was on 0.23.0 and when I made this issue I couldn't do that, but maybe that was my mistake...

Thank you :)
