### ISSUE TITLE
How to use the EKS cluster without NAT Gateway

### ISSUE THREAD

**Issue by JulianWgs** [weaveworks/eksctl#2404]
I'm using EKS as a compute cluster with Dask. I'm reading and writing a lot of data to and from S3, which can get expensive with a NAT gateway enabled. No other networking is needed. Unfortunately my nodes can't connect to the cluster when I disable the NAT gateway and the creation times out.

How can I use eksctl to create a cluster for this use case without using a NAT gateway?

[Here](https://aws.amazon.com/vpc/pricing/?nc1=h_ls) is says: "To avoid the NAT Gateway Data Processing charge in this example, you could setup a Gateway Type VPC endpoint and route the traffic to/from S3 through the VPC endpoint instead of going through the NAT Gateway." I don't know how to that with eksctl.

Thanks in advance!

Best regards,
Julian

**Comment by martina-if** [comment]
Hi @JulianWgs, the enabling of the VPC endpoints is not supported in eksctl at the moment. It will be supported soon for fully private clusters. If you are interested in these please check #2384.

**Comment by JulianWgs** [comment]
Yay it has been merged. Thank you for the fast and informative answer!
