### ISSUE TITLE
Error: control plane version "1.17" is not known to this version  of eksctl

### ISSUE THREAD

**Issue by maozza** [weaveworks/eksctl#2418]
**What happened?**
When trying to run the latest eksctl:
Error: control plane version "1.17" is not known to this version of eksctl, try to upgrade eksctl first

**What you expected to happen?**
use eksctl to manage my cluster

**Versions**
Please paste in the output of these commands:
```
$ eksctl version 0.23.0
$ kubectl version v1.17.6-eks-4e7f64
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
```
eksctl get clusters -v 4
2020-07-10T17:16:59+03:00 [▶]  role ARN for the current session is "arn:aws:iam::XXXXXX:user/XXX"
NAME            REGION
k8s-test     us-east-1
```

**Comment by michaelbeaumont** [comment]
Version `0.23.0` doesn't support k8s `1.17`, it will be supported starting with the next release candidate.
