### ISSUE TITLE
Unneeded and too open inline policy attached when creating a cluster

### ISSUE THREAD

**Issue by pusherman** [weaveworks/eksctl#2435]
**What happened?**
When creating a cluster, an inline policy `PolicyNLB` is attached to the cluster that grants the cluster the following actions:
```
"elasticloadbalancing:*",
"ec2:CreateSecurityGroup",
"ec2:Describe*"
```
I believe, the needed actions in this policy are provided in the AWS managed policy `AmazonEKSClusterPolicy` and are more restrictive than the * actions in the inline policy

**What you expected to happen?**
The open custom inline policy not attached to the cluster and the AWS managed policy used instead.

**How to reproduce it?**
`eksctl create cluster --name=comsig-dev --fargate` and observe the attached policies given to the cluster service role

**Versions**
```
% eksctl version
0.20.0
% kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.6-eks-4e7f64", GitCommit:"4e7f642f9f4cbb3c39a4fc6ee84fe341a8ade94c", GitTreeState:"clean", BuildDate:"2020-06-11T13:55:35Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pusherman** [comment]
Reference:

Inline Policy
https://github.com/weaveworks/eksctl/blame/b862a38180a2bac65b8207dcf10695d19c817ff5/pkg/cfn/builder/iam.go#L88

Managed Policy
https://github.com/weaveworks/eksctl/blame/b862a38180a2bac65b8207dcf10695d19c817ff5/pkg/cfn/builder/iam.go#L80

**Comment by cPu1** [comment]
Good catch!

>I believe, the needed actions in this policy are provided in the AWS managed policy AmazonEKSClusterPolicy and are more restrictive than the * actions in the inline policy

That's correct. Thanks.
