### ISSUE TITLE
Enable EFA with eksctl

### ISSUE THREAD

**Issue by g-karthik** [weaveworks/eksctl#2447]
**Why do you want this feature?**
In order to easily train large machine learning models.

**What feature/behavior/change do you want?**
I want to easily enable Elastic Fabric Adapter (EFA) with my EKS cluster. I have `eksctl` YAML files for my cluster and nodegroup currently, and I want an easy way to edit these files to enable EFA. Perhaps a one-line addition to enable EFA.

**Comment by mikestef9** [comment]
Notes: This would require eksctl providing two additional options, one to specify the interface type of a node group, two to specify a placement group name for a node group

**Comment by jarednielsen** [comment]
Same here, training large NLP models using EKS and the communication overhead is a huge bottleneck. Would be amazing if you made this happen!

**Comment by mikestef9** [comment]
We (the EKS team) will soon be publishing a guide on how to get started with EFA on EKS to https://github.com/aws-samples. The walkthrough there will be using CloudFormation to launch worker nodes with EFA enabled, but we work on getting support into eksctl as well.

**Comment by aclevername** [comment]
https://github.com/weaveworks/eksctl/pull/2688
