### ISSUE TITLE
Support for 3 tier VPC Setup

### ISSUE THREAD

**Issue by akshayvvr** [weaveworks/eksctl#2457]
Currently the most common type of VPC Architecture is the 3 tier VPC, wherein we have 

-  Public Subnet - with Internet Gateway for public facing endpoints
-  Private Subnet- NAT Gateway for compute resources
-  Data Subnet - Without Gateway and internet access for Databases

Currently EKSCTL Supports only the first two. It'll be great if you can add support for this.

**Comment by sayboras** [comment]
In my opinion, it's unlikely to put eks worker node in what you just described as _data subnet_, hence supporting this as part of eksctl is kind of weird for me. 

Coming to back to this use case, VPC should be managed _outside_ of eksctl. Then eksctl with existing subnets feature can be used.

**Comment by michaelbeaumont** [comment]
Potentially relevant: #806

**Comment by michaelbeaumont** [comment]
@akshayvvr Can you be more specific about how exactly you imagine eksctl changing to support this setup?

**Comment by akshayvvr** [comment]
The thing is currently, eksctl supports only public and private subnets. that is working under the assumption that the subnet has either an Internet/NAT Gateway route. 

What if I want my cluster worker node to be in a subnet without Internet access. i.e a totally private subnet and all the communication happens internally within the VPC via the Amazon network. 
Instead of a 2tier VPC Support, It'll be great if EKS Can support 3Tier VPCs

> @akshayvvr Can you be more specific about how exactly you imagine `eksctl` changing to support this setup?

**Comment by cPu1** [comment]
>What if I want my cluster worker node to be in a subnet without Internet access. i.e a totally private subnet and all the communication happens internally within the VPC via the Amazon network.

This use case is addressed by the fully-private cluster feature: https://eksctl.io/usage/eks-private-cluster/

Please note that there are additional resources required for supporting fully-private clusters. If you simply try to launch worker nodes in a subnet with no outbound internet access, they will be unable to join the cluster. The fully-private cluster feature handles these details. 

>Data Subnet - Without Gateway and internet access for Databases

I'm not sure this can be categorized into "Data Subnets". There are more use cases for having subnets with no outbound internet access than just for accessing internal databases like RDS.

**Comment by connorearl** [comment]
I also need this, but for a different use case. I need nodes on a different subnet for Istio egress gateways. We don't want to open egress on our VPN to all nodes on the corporate firewall side, so I need a separate subnet just for them. #806 would fix this for me though.

**Comment by martina-if** [comment]
@connorearl, thanks for the explanation, this is really useful for us to understand the different use cases. 

Both issues are now linked so let me close this as duplicate and we can always go back here for more information.
