### ISSUE TITLE
Nodegroup not deleting properly

### ISSUE THREAD

**Issue by arkag** [weaveworks/eksctl#2467]
Please [search existing issues (open & closed)](https://github.com/weaveworks/eksctl/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if there is a similar one. If there is, add comments or vote where appropriate.

I did the above, and couldn't find a similar issue. Please link if there's a similar one I missed!

If you did not find a similar issue or if it did not help then ask for help in our [slack channel](https://weave-community.slack.com/messages/eksctl/)

I was routed here from the Slack.

**What help do you need?**
My nodegroup isn't actually being deleted despite it saying it is. Maybe I'm misunderstanding, but I wanted to delete my nodegroup for a tutorial so I wasn't being billed for it over night, and the recreate it this morning.

Output by command:

### Delete
```
➜  eks_ctfd git:(master) ✗ eksctl delete nodegroup --config-file=eks_udemy/eks-course.yaml --include=ng-1 --approve
[ℹ]  eksctl version 0.24.0
[ℹ]  using region us-east-1
[ℹ]  comparing 1 nodegroups defined in the given config ("eks_udemy/eks-course.yaml") against remote state
[ℹ]  combined include rules: ng-1
[ℹ]  1 nodegroup (ng-1) was included (based on the include/exclude rules)
[ℹ]  will drain 1 nodegroup(s) in cluster "EKS-course-cluster"
[!]  no nodes found in nodegroup "ng-1" (label selector: "alpha.eksctl.io/nodegroup-name=ng-1")
[ℹ]  will delete 1 nodegroups from cluster "EKS-course-cluster"
[ℹ]  1 task: { delete nodegroup "ng-1" [async] }
[ℹ]  will delete stack "eksctl-EKS-course-cluster-nodegroup-ng-1"
[ℹ]  will delete 1 nodegroups from auth ConfigMap in cluster "EKS-course-cluster"
[!]  removing nodegroup from auth ConfigMap: instance identity ARN "arn:aws:iam::680604548561:role/eksctl-EKS-course-cluster-nodegro-NodeInstanceRole-C9ID6FYL7A61" not found in auth ConfigMap
[✔]  deleted 1 nodegroup(s) from cluster "EKS-course-cluster"
```

### Get

```
➜  eks_ctfd git:(master) ✗ eksctl get nodegroup --cluster EKS-course-cluster


CLUSTER			NODEGROUP	CREATED			MIN SIZE	MAX SIZE	DESIRED CAPACITY	INSTANCE TYPE	IMAGE ID
EKS-course-cluster	ng-1		2020-07-22T22:12:15Z	3		5		3			t2.small	ami-01b33458af4b31b8f
```

### Create

```
➜  eks_ctfd git:(master) ✗ eksctl create nodegroup --config-file=eks_udemy/eks-course.yaml
[ℹ]  eksctl version 0.24.0
[ℹ]  using region us-east-1
[ℹ]  will use version 1.16 for new nodegroup(s) based on control plane version
[ℹ]  1 existing nodegroup(s) (ng-1) will be excluded
[ℹ]  2 sequential tasks: { fix cluster compatibility, no tasks }
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack has all required resources
[ℹ]  no tasks
[✔]  created 0 nodegroup(s) in cluster "EKS-course-cluster"
[✔]  created 0 managed nodegroup(s) in cluster "EKS-course-cluster"
[ℹ]  checking security group configuration for all nodegroups
[ℹ]  all nodegroups have up-to-date configuration
```

### YAML File

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-course-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: # use existing EC2 key
      publicKeyName: eks_ctfd
```

Thanks for the help!

**Comment by michaelbeaumont** [comment]
@arkag can you check whether the nodegroup cloudformation stack still exists? Do you get the same output if you run delete nodegroup again?
By the way, make sure to delete the entire cluster if you can to reduce costs!

**Comment by arkag** [comment]
Ah good call... Looks like it failed to delete...

![image](https://user-images.githubusercontent.com/6749810/88316884-b2516300-ccd5-11ea-97ba-ad3f3fea27a8.png)


Any idea finding why it failed to delete? It's weird that eksctl didn't detect it failed to delete.

**Comment by arkag** [comment]
Looks like the security group didn't delete... Deleting it manually worked! Interesting...

**Comment by arkag** [comment]
Anyway, this is resolved now. I assume this is the fault of AWS, not the tool.

Thanks for helping out!

**Comment by michaelbeaumont** [comment]
Great! But wait, can you check under Events for that stack what the reason it failed to delete was? (You probably have to change the stack filter from Active to Deleted)

**Comment by arkag** [comment]
```
resource sg-0049bb755ee94f247 has a dependent object (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: fc36e7db-8803-491e-ae34-749876a16eb8)

```

This occurs twice, once yesterday when I deleted it, and once today when I tried a second time.

**Comment by michaelbeaumont** [comment]
Are there any other events that mention the dependent object? If you only created and deleted using that config and didn't create any other AWS resources, there shouldn't be any dependent objects that eksctl didn't delete.

**Comment by arkag** [comment]
Nope, nothing else mentions it. Maybe just a fluke? I'm going to do this again tonight so if it fails again, we can do some debugging tomorrow :D

**Comment by arkag** [comment]
Deleting that NG for the tutorial and it's hanging. eksctl reports that it's deleted but CF says it's still in progress. The SG still hasn't finished deletion.

**Comment by michaelbeaumont** [comment]
Add `-w` to actually wait for the stack deletions

**Comment by michaelbeaumont** [comment]
@arkag Did it work? Are there any `DELETE_FAILED` events?

**Comment by michaelbeaumont** [comment]
Let us know here if you find any more information!
