### ISSUE TITLE
Specify --proxy-mode for kube-proxy

### ISSUE THREAD

**Issue by zironycho** [weaveworks/eksctl#2468]
I would like to change proxy-mode for kube-proxy.
Currently eksctl use the `iptables` for `--proxy-mode`.

**Comment by michaelbeaumont** [comment]
It's currently not supported. See the upstream AWS issue https://github.com/aws/containers-roadmap/issues/142 although it would be possible to support in eksctl (see https://github.com/aws/containers-roadmap/issues/142#issuecomment-612990747)
