### ISSUE TITLE
Istio add-on

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#248]
Just realised that this is something we've talked about with @mt-inside and @stefanprodan, but never opened an issue for it. Here is an issue to track it.

**Comment by arun-gupta** [comment]
Would love to see this add-on support. Here is how Istio is currently installed on EKS: https://aws.amazon.com/blogs/opensource/getting-started-istio-eks/

**Comment by vladfr** [comment]
@errordeveloper I'm looking at tools to bootstrap a cluster with readily available addons (like Helm and Istio) and found this issue. Is it fair to say that the add-ons discussion for `eksctl` is on hold, pending any standardization coming from upstream? 

i.e. I saw https://github.com/weaveworks/eksctl/pull/242 :)

**Comment by errordeveloper** [comment]
@vladfr yes, indeed - add-ons discussion is on hold, as it will be based on upstream spec.

**Comment by errordeveloper** [comment]
In the meantime, we might e.g. provide `eksctl utils install-helm-tiller`, to make it a little simpler for users to get going with helm (see e.g. #757).

**Comment by kalbir** [comment]
This is the kind of thing that we would like to see people implementing with [profiles](https://eksctl.io/gitops-quickstart/#enabling-a-quick-start-profile), for example this one that implements [AWS app mesh](https://github.com/weaveworks/eks-appmesh-profile).
