### ISSUE TITLE
Update Allocatables on existing nodes

### ISSUE THREAD

**Issue by marcoacarvalho** [weaveworks/eksctl#2482]
Hi,
I have the same issue described in https://github.com/weaveworks/eksctl/issues/2395 (Eksctl creating worker nodes with too much reserved memory for kubelet).
I like to know if there is a way to increase the allocatable memory on already created nodes, I'm having problems with memory pressure.

Thanks in advance

**Comment by martina-if** [comment]
Hi @marcoacarvalho as far as I know there is no way for eksctl to update them. You would need to either do it in some other way or replacing the nodes with new ones.

**Comment by marcoacarvalho** [comment]
Thanks @martina-if

**Comment by marcoacarvalho** [comment]
.
