### ISSUE TITLE
git operations don't use Windows 10 native OpenSSH agent

### ISSUE THREAD

**Issue by Legion2** [weaveworks/eksctl#2501]
**What happened?**
I run `eksctl.exe enable repo -f cluster.yaml` and get following output:
```
[!]  flux deployment was not found
[ℹ]  Generating manifests
[ℹ]  Cloning git@****.git
Cloning into 'C:\Users\Leon\AppData\Local\Temp\eksctl-install-flux-clone-347797271'...
Enter passphrase for key '/c/Users/Leon/.ssh/id_rsa': 
```
I'm prompted for my ssh passphrase.

**What you expected to happen?**
It should not ask me for my passphrase.
It should use the ssh-agent.
I'm using the native OpenSSH agent of windows and added following into my `.gitconfig`:
```ini
[core]
    sshCommand = 'C:\\Windows\\System32\\OpenSSH\\ssh.exe'
```

**How to reproduce it?**
1. Install and setup Windows 10 native OpenSSH Client
2. add your ssh keys to the ssh-agent
3. add following to `.gitconfig`:
    ```ini
    [core]
        sshCommand = 'C:\\Windows\\System32\\OpenSSH\\ssh.exe'
    ```
    So, git uses the correct ssh client (not the built-in version of Git for Windows).
4. `eksctl.exe enable repo -f cluster.yaml` (use a valid cluster.yaml)
5. ssk key from step 2 is not used

**Anything else we need to know?**
OS: Windows 10 Version 10.0.19041 Build 19041
The kubectl is installed via Docker for Windows
On windows the ssh agent does not use `SSH_AUTH_SOCK` environment variable.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.25.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.6-eks-4e7f64", GitCommit:"4e7f642f9f4cbb3c39a4fc6ee84fe341a8ade94c", GitTreeState:"clean", BuildDate:"2020-06-11T13:55:35Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aclevername** [comment]
closing as `enable repo` was deprecated and replaced with `enable flux` for flux v2 support, which I think might of addressed the issue. LMK if its still not fixed :smile:
