### ISSUE TITLE
Structured results are mixed with unstructured logs

### ISSUE THREAD

**Issue by ndegory** [weaveworks/eksctl#2509]
**What happened?**

Logs and results are mixed in the standard output, which makes it difficult to parse. In particular when JSON or YAML outputs are requested. Examples of logs are retryable errors from the AWS API.

**What you expected to happen?**

Verbose logs should be on the standard error.

**How to reproduce it?**

Run a command with the json output, and set --verbose 4. The JSON output cannot be parsed anymore.

**Anything else we need to know?**

The default verbose level (3) sometimes logs AWS messages (such as retryable errors on the cloudformation API calls). The logs are useful, but shouldn't compromise further processing of the output.

**Versions**

```
$ eksctl version
0.25.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
```

**Logs**

```
$ eksctl get nodegroups  --cluster cluster1 --output json --verbose 3 | jq 'length'
2
$ eksctl get nodegroups --cluster cluster1 --output json --verbose 4 | jq 'length'
parse error: Invalid numeric literal at line 1, column 14
```

**Comment by aclevername** [comment]
fixed by https://github.com/weaveworks/eksctl/pull/3761
