### ISSUE TITLE
Delete unnecessary code for multi-arch images

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#2538]
When launching support for ARM we added code that made sure that after creating a cluster the default addons where updated to the newest version with the multi-arch images (their label has the suffix `-eksbuild.1`). 

Once the multi-architecture images are used by EKS by default when creating clusters, that code can be removed from eksctl. 

The code is marked with a `// TODO`. Check the [ARM PR](https://github.com/weaveworks/eksctl/pull/2535) for more details.

**Comment by Callisto13** [comment]
Thanks @martina-if for making this so straightforward ❤️
