### ISSUE TITLE
Configure suspended processes in the node group configuration

### ISSUE THREAD

**Issue by hikhvar** [weaveworks/eksctl#2543]
**Why do you want this feature?**
We currently deploy a build cluster with eksctl. We scale up on outstanding build job pods with the clusterautoscaler. Our node group is a spotfleet across multiple availability zones. After scale downs of the cluster autoscaler, the AWS ASG Rebalance process might delete additional nodes. This disrupts a lot of builds. Since we do not need the balancing for the build cluster, we want to disable it in the nodegroup configuration.

**What feature/behavior/change do you want?**
I would like to configure a list of suspended processes in the nodegroup configuration.

**Comment by costela** [comment]
duplicate of #1355?

**Comment by hikhvar** [comment]
yes, will close this. Did not find it :facepalm: Sorry for the noise.
