### ISSUE TITLE
Updating cluster from 1.15 to 1.16 says Kubelet version of Fargate pods must be updated to match cluster version 1.15

### ISSUE THREAD

**Issue by sarbajitdutta** [weaveworks/eksctl#2545]
**What happened?**
Updating cluster from 1.15 to 1.16 says Kubelet version of Fargate pods must be updated to match cluster version 1.15
I have recycled all the deployments to have latest kubelet version.

**What you expected to happen?**
The cluster should update. I checked all the nodes have latest 1.15 kubelet version
```
kubectl get nodes | awk '{print $1 " : " $5}'
NAME : VERSION
fargate-ip-10-46-134-101.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-104.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-117.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-123.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-135.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-140.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-149.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-162.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-166.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-70.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-75.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-78.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-90.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-93.ec2.internal : v1.15.10-eks-094994
fargate-ip-10-46-134-95.ec2.internal : v1.15.10-eks-094994
```

**How to reproduce it?**
Try to upgrade cluster from 1.15 to 1.16 using eksctl with fargate pods.

**Anything else we need to know?**
Using AWS vended EKS.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.25.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.7-eks-bffbac", GitCommit:"bffbacfd13a805a12d10ccc0ca26205ae1ca76e9", GitTreeState:"clean", BuildDate:"2020-07-08T18:30:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-14f01f", GitCommit:"14f01fe8f04411d5e187b220034ca2117d79f7de", GitTreeState:"clean", BuildDate:"2020-05-23T21:32:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```[ℹ]  eksctl version 0.25.0
[ℹ]  using region us-east-1
[ℹ]  will upgrade cluster "reciter" control plane from current version "1.15" to "1.16"
Error: InvalidRequestException: Kubelet version of Fargate pods must be updated to match cluster version 1.15 before updating cluster version; Please recycle all offending pod replicas
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "285717e7-3b09-4e7f-8132-4d5cc46114b1"
  },
  Message_: "Kubelet version of Fargate pods must be updated to match cluster version 1.15 before updating cluster version; Please recycle all offending pod replicas"
}
```

**Comment by mikestef9** [comment]
@sarbajitdutta are you still having this issue? How long did you wait to try the upgrade again after recycling pods?

**Comment by jamesgustard** [comment]
Did you complete the prerequisites in ? https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#1-16-prerequisites
I had this error, but when I changed the kube-proxy-daemonset.yaml as suggested it worked.

**Comment by sarbajitdutta** [comment]
> @sarbajitdutta are you still having this issue? How long did you wait to try the upgrade again after recycling pods?

I was able to do the upgrade after waiting for 2 hours. It automatically solved the issue itself and was able to proceed with the upgrade.

**Comment by sarbajitdutta** [comment]
> Did you complete the prerequisites in ? https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#1-16-prerequisites
> I had this error, but when I changed the kube-proxy-daemonset.yaml as suggested it worked.

Yes I completed all the prerequisites before proceeding with the upgrade.
