### ISSUE TITLE
Custom AMI and Launch Template support for Managed Nodegroups

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#2551]
EKS now supports specifying a custom AMI and providing a launch template for managed nodegroups. This will allow eksctl to support features that weren't possible before for managed nodegroups.

Add support for missing features using the launch template capability, including the following:
- Custom AMI (`ami`)
- `instancePrefix` and `instanceName` to configure the EC2 instance name for a nodegroup
- `securityGroups.attachIDs` to add custom security groups
- `ebsOptimized`, `volumeType`, `volumeName`, `volumeEncrypted`, `volumeKmsKeyID` and `volumeIOPS`
- `maxPodsPerNode`
- `preBootstrapCommands` and `overrideBootstrapCommand`
- `disableIMDSv1`

Also add support for providing a custom launch template to create a managed nodegroup.

**Comment by inductor** [comment]
Can you provide an example of this feature please?

**Comment by michaelbeaumont** [comment]
Hi @inductor, the docs aren't available at the usual URL yet but check out https://release-0_26--eksctl.netlify.app/usage/launch-template-support/

**Comment by kevintangpn** [comment]
Hi,
I used launchTemplate to config yaml
but eksctl respose like
```
error unmarshaling JSON: while decoding JSON: json: unknown field "launchTemplate"
```

i've try sample like 
https://release-0_26--eksctl.netlify.app/usage/launch-template-support/
https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/

my eksctl version is 0.25

someone can help ? thanks.

**Comment by inductor** [comment]
@kevintangpn look at the release number. It's 0.26.

**Comment by nsaud01** [comment]
I'm getting that same error:

`Error: loading config file "devops-nodegroup.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "launchTemplate"` with eksctl v0.31.0

**Comment by nsaud01** [comment]
I see where the error was. My issue was that I was using `nodeGroups:` when it should've been `managedNodeGroups:`. Hope that helps someone.

**Comment by young-0** [comment]
> I see where the error was. My issue was that I was using `nodeGroups:` when it should've been `managedNodeGroups:`. Hope that helps someone.

I have the same issue. It worked for me. Thanks.
