### ISSUE TITLE
eksctl add rds

### ISSUE THREAD

**Issue by stevenroussey-privicy** [weaveworks/eksctl#2556]
It would be great for eksctl to add what is needed to a nodegroup to access RDS (and visa-versa).

**Comment by koslibpro** [comment]
Hi, what would the ideal option be in your opinion? Manage the RDS instance via the eksctl config file, or just set up the necessary security groups/VPC settings to be able to access it?

ps: I may be able to contribute from a development standpoint in this feature

**Comment by michaelbeaumont** [comment]
@koslib Feel free to propose something/open a PR

**Comment by daern91** [comment]
> Hi, what would the ideal option be in your opinion? Manage the RDS instance via the eksctl config file, **or just set up the necessary security groups/VPC settings to be able to access it?**
> 
> ps: I may be able to contribute from a development standpoint in this feature

Would love to have the bold part!

**Comment by nikimanoledaki** [comment]
@daern91 @koslib just chiming in to say that you are welcome to open a [feature request](https://github.com/weaveworks/eksctl/issues/new?assignees=&labels=kind%2Ffeature&template=feature_request.md&title=) or a PR with a solution, we're happy to accept those!
