### ISSUE TITLE
eksctl get clusters prints log line

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#256]
As of recent changes, we no see a log line printed above tabular output:

``` $ eksctl get clusters
2018-10-15T11:05:10+01:00 [ℹ]  using region us-west-2
NAME
fabulous-outfit-1538467450
fabulous-painting-1539188916
$
```

I think we could make this prettier, perhaps region could be a column? Bonus point would be to add `--all-regions` also.

**Comment by gotjosh** [comment]
I'll take a stab at this.

**Comment by gotjosh** [comment]
@errordeveloper what command are we running when this happens?

**Comment by errordeveloper** [comment]
The output is from 'eksctl get cluster'.

**Comment by errordeveloper** [comment]
@gotjosh did you get anywhere with this? Please hop over to slack.weave.works if you need help, we are all there :)

**Comment by gotjosh** [comment]
@errordeveloper I did manage to get an output working relatively soon. I'm not very fond of the approach (mostly due to my lack of confidence if my Go) and been meaning to write a PR with a lengthy description. 

My changes are relatively small, I'll pop on slack later on to have the chat!
