### ISSUE TITLE
Add support for c5n.metal instance type

### ISSUE THREAD

**Issue by nucleusv** [weaveworks/eksctl#2563]
Please add support for c5n.metal instance type.

Now kubelet doesn't start because of error:
F0820 13:26:23.363356   39276 server.go:156] invalid argument "" for "--max-pods" flag: strconv.ParseInt: parsing "": invalid syntax
Aug 20 13:26:28 ip-10 kubelet: --max-pods int32                                                                                            Number of Pods that can run on this Kubelet. (default 110) (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)
Aug 20 13:26:28 ip-10 kubelet: --pods-per-core int32                                                                                       Number of Pods per core that can run on this Kubelet. The total number of Pods on this Kubelet cannot exceed max-pods, so max-pods will be used if this calculation results in a larger number of Pods allowed on the Kubelet. A value of 0 disables this limit. (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)

Fix:
**cat /etc/eksctl/kubelet.local.env**
NODE_IP=ip address
INSTANCE_ID=i-034235aa84b9eb375
INSTANCE_TYPE=c5n.metal
AWS_SERVICES_DOMAIN=amazonaws.com
**MAX_PODS=737  <-- was empty**
ARCH=amd64

and in this file there is no line for c5n.metal

**cat /etc/eksctl/max_pods.map | grep c5n.metal**
**c5n.metal 737 <-- no such line**

**Comment by ricarhincapie** [comment]
Same situation with Instance Type c6i.8xlarge which won't let the kubelet start. At journalctl -u kubelet the following error is logged:
`kubelet[5953]: E0207 22:05:58.814258    5953 server.go:156] "Failed to parse kubelet flag" err="invalid argument \"\" for \"--max-pods\" flag: strconv.ParseInt: parsing \"\": invalid syntax"`

**Comment by Himangini** [comment]
@ricarhincapie can you open a new issue? Also, we welcome contributions from the community 🎉

**Comment by ricarhincapie** [comment]
As commented by @cPu1 here https://github.com/weaveworks/eksctl/issues/6269#issuecomment-1438151676, the issue is releated with using an older eksctl version. Upgrading it resolves the issue.
