### ISSUE TITLE
EC2MetadataError with eksctl version >= 0.15

### ISSUE THREAD

**Issue by kushagra391** [weaveworks/eksctl#2564]
**What happened?**

Recent eksctl versions is requiring aws credentials being explicitly exported as environment variables.

Our team uses [hologram](https://github.com/AdRoll/hologram) to manage AWS credentials. 
So, our access / secret keys aren't stored inside `~/.aws/config` on the local machine. 

I need to manually export following into my environment for` v0.26` to work.
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_SESSION_TOKEN

Curious if the later versions can run the same way as `v0.14`. I think some packages like `boto3` are able to fetch these keys automatically.

---

`v0.26` (without exporting credentials) ❌ 
```shell
eksctl --region us-west-2 get cluster
[!]  retryable error (EC2MetadataError: failed to make EC2Metadata request
	status code: 404, request id:
caused by: 404 page not found

# similar error shows up for 
eksctl create / delete cluster -f ...
```

`v0.14` (without exporting credentials) ✅  
```
eksctl --region us-west-2 get cluster
NAME				REGION
...
```

`v0.26` (after exporting credentials) ✅
```
eksctl --region us-west-2 get cluster
NAME				REGION
...
```

---

**Versions**
```shell
eksctl version (working)
0.14.0

~/eksctl version (not working)
0.26.0

kubectl version --client
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
```

Thanks !

**Comment by nitrocode** [comment]
@kushagra391 How did you downgrade eksctl back to 0.14.0 ?

**Comment by michaelbeaumont** [comment]
@kushagra391 This does seem like a regression and it may be that the AWS SDK isn't being initialized correctly in `eksctl`.

https://github.com/weaveworks/eksctl/blob/df8c63b241ad8d7a65744fdf2c3fce92c69e0e21/pkg/eks/api.go#L123

**Comment by nadenf** [comment]
@michaelbeaumont .. This should be labelled as priority/critical no ?

eksctl was unusable until I stumbled across this bug.

**Comment by michaelbeaumont** [comment]
Potentially related: https://github.com/weaveworks/eksctl/issues/2787

**Comment by michaelbeaumont** [comment]
@nitrocode @nadenf Would either of you be willing to share your `~/.aws/config` files?

**Comment by nitrocode** [comment]
```
$ cat ~/.aws/config
[default]
region=us-west-2
# output = text
cli_pager=
```

**Comment by nadenf** [comment]
```
[default]
region = us-east-1

[harana-dev]
region = us-east-1
output=text

[profile harana-dev]
region = us-east-1

[profile hyper]
region = ap-southeast-2
```

**Comment by michaelbeaumont** [comment]
I was able to reproduce this using `aws-vault` which functions like `hologram`.
The error is not unique to `eksctl`, see [this kops issue](https://github.com/kubernetes/kops/issues/10043#issuecomment-754717727) and is IMO a bug in `aws-sdk-go`.

`boto` handles this correctly as opposed to `aws-sdk-go`, [see `botocore`](https://github.com/boto/botocore/blob/38363876ac8911ae64baea506ed3116ea27069aa/botocore/utils.py#L380) where if a `404` is returned trying to fetch a token then the request to `latest/meta-data/` is simply made without that token.

`aws-sdk-go` tries to do this but it [wraps the HTTP error as an `EC2MetadataError`](https://github.com/aws/aws-sdk-go/blob/df6799b65ee6bd2203d6c3bcb2f68e43f6031c7d/aws/ec2metadata/service.go#L237). If there's a `Retryer` enabled that uses [default retry rules](https://github.com/aws/aws-sdk-go/blob/df6799b65ee6bd2203d6c3bcb2f68e43f6031c7d/aws/request/retryer.go#L170-L189) (like with `eksctl`), it fails to recognize the original error as _not retryable_ and the request for the token is continually retried, preventing the `latest/meta-data/` request from being made

**Comment by michaelbeaumont** [comment]
@nadenf @nitrocode You're welcome to try building the branch for the above PR (#3150)
