### ISSUE TITLE
IP6 support

### ISSUE THREAD

**Issue by stevenroussey-privicy** [weaveworks/eksctl#2567]
**Why do you want this feature?**
I want to support IP6

**What feature/behavior/change do you want?**
eksctl should add the needed config changes for IP/CIDR to subnets on creation, etc.

**Comment by umrikar** [comment]
Hi,
     i have single node cluster where we use weavenet as CNI, and want to know if there is some config to set ipv6 cidr,  at present we use ipv4 addreses we have one config parameter `IPALLOC_RANGE` in weavenet manifest file can we specify ipv6 CIDR here, in calico we can specify both ipv6 and ipv4 CIDRS and it supports dual stack as well

**Comment by stevenroussey-privicy** [comment]
IP6 is still a thing

**Comment by umrikar** [comment]
Hi,
        Does weanet support dual-stack (ipv4/ipv6)?
