### ISSUE TITLE
docs: vpc.subnets.private/public not documented clearly, unable to chart path forward

### ISSUE THREAD

**Issue by darkn3rd** [weaveworks/eksctl#2569]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**

I cannot discern how to use eksctl with an existing network, and eksctl is not able to auto-discovery networks when supplied a vpc-id with the networks tagged appropriately for public/private, and therefore I am blocked from using this feature.

The documentation specifically documents that vpc.subnets.private and vpc.subnets.public contain just an object `{}`.  

When running the command `eksctl utils schema`, you can also see:

```json
{
  "ClusterSubnets": {
      "properties": {
        "private": {
          "additionalProperties": {
            "$ref": "#/definitions/Network"
          },
          "type": "object",
          "default": "{}"
        },
        "public": {
          "additionalProperties": {
            "$ref": "#/definitions/Network"
          },
          "type": "object",
          "default": "{}"
        }
      }
}
```

This doesn't tell exactly how to use this.  The examples from the website also illustrate how to use command-line switches, but not equivalent examples to how to use this facility.

The use case is to use an existing VPC rather than create one automatically using `eksctl`.

**What feature/behavior/change do you want?**

I would like to either this `object` further expanded in the documentation and/or examples on how to use this.  If there's a way to have eksctl auto-discover the subnets, then that would be great as well.

**Comment by nemo83** [comment]
> Please see https://eksctl.io/examples/reusing-iam-and-vpc/ for an example of `subnets`.

As subnets are keyed by AZ, how can I setup multiple subnets for a given AZ?

**Comment by martina-if** [comment]
Hi @darkn3rd, I opened a PR that adds example config files to the docs. Do you think this helps understanding how to use the private and public subnets? https://github.com/weaveworks/eksctl/pull/2645
