### ISSUE TITLE
Different, unexpected behaviour when fetching iamserviceaccounts between eksctl versions

### ISSUE THREAD

**Issue by nemo83** [weaveworks/eksctl#2588]
## What happened and what I expected to happen

eksctl get iamserviceaccount <irsa_name> seems to behave differently across eksctl versions.

Until version 0.21 passing `<irsa_name>` to the `eksctl get iamserviceaccount` filtered the output acccordingly, in 0.25.0 and 0.26.0 the filter doesn't seem to be working anymore and the full list of IRSA is returned. 

**I am wondering if this is a desired change.**

Below example with eksctl installed w/ brew (0.25.0 and 0.26.0) and 0.21.0 (that I invoke with `./eksctl`) that was manually installed.

### Examples:

> ./eksctl version
0.21.0
> ./eksctl get iamserviceaccount cluster-autoscaler-aws-cluster-autoscaler --namespace kube-system --cluster ${CLUSTER_NAME}
NAMESPACE	NAME						ROLE ARN
kube-system	cluster-autoscaler-aws-cluster-autoscaler	arn:aws:iam::1231231231231:role/ARN-ROLE-1
> eksctl version
0.26.0
> eksctl get iamserviceaccount cluster-autoscaler-aws-cluster-autoscaler --namespace kube-system --cluster ${CLUSTER_NAME}
NAMESPACE	NAME						ROLE ARN
kube-system	cluster-autoscaler-aws-cluster-autoscaler	arn:aws:iam::1231231231231:role/ARN-ROLE-1
production	my-prod-service				arn:aws:iam::1231231231231:role/ARN-ROLE-2

**Anything else we need to know?**
I'm running on macosx

**Versions**
For eksctl please see examples above.

```
k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by michaelbeaumont** [comment]
Is this still an issue?
