### ISSUE TITLE
Error creating EKS  cluster in US gov region.

### ISSUE THREAD

**Issue by hectoralicea** [weaveworks/eksctl#2595]
**What happened?**
I'm trying to create an EKS in a gov region, using a private subnets, and an already existing VPC

**What you expected to happen?**
It should work without error.

**How to reproduce it?**
Steps to reproduce the bug.  Make sure you use an existing subnet that already exists and not exposed to the internet.
```
eksctl create cluster \
	--name=${AWS_EKS_CLUSTER_NAME} \
	--version=${AWS_EKS_CLUSTER_VERSION} \
	--kubeconfig $(pwd)/${ENVIROINMENT}/config \
	--nodegroup-name=${AWS_EKS_NODEGROUP_NAME} \
	--node-private-networking \
	--node-type=t3.large \
	--nodes=3 \
	--nodes-min=3 \
	--nodes-max=12 \
	--region=${AWS_EKS_REGION} \
	--vpc-private-subnets=${AWS_EKS_VPC_PRIVATE_SUBNETS} \
```

**Anything else we need to know?**
Running from a linux docker container, since I'm not able to run it from my Locked down Windows GFE.

I'm trying to use this feature and I'm getting the following error:
```
[✖]  AWS::EC2::InternetGateway/InternetGateway: CREATE_FAILED – "API: ec2:CreateInternetGateway You are not authorized to perform this operation. Encoded authorization failure message:
[✖]  AWS::EC2::VPC/VPC: CREATE_FAILED – "API: ec2:CreateVpc You are not authorized to perform this operation.
```
I'm using an existing subnet that's private.  Why is it trying to create an internet gateway which should not really be used in a gov region, and why is it trying to create a VPC, when I'm pointing to an existing subnet, already?

Following are my options settings.

**Versions**
Please paste in the output of these commands:
```
eksctl version
0.26.0
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by cPu1** [comment]
Can you confirm the environment variable `AWS_EKS_VPC_PRIVATE_SUBNETS` is set and contains a comma-separated list of subnet IDs? eksctl does not attempt to create a dedicated VPC if you supply your own subnets, so it appears that `AWS_EKS_VPC_PRIVATE_SUBNETS` is not set in your case.

**Comment by hectoralicea** [comment]
Yes, `export AWS_EKS_VPC_PRIVATE_SUBNETS="subnet-XXXXca57,subnet-XXXX295f"` is being set from the script file that i'm running from within the container.

The following are the full errors I'm getting.  The two in bold are the two I don't understand why its trying to execute those in a Gov Region.


[✖]  AWS::IAM::Role/ServiceRole: CREATE_FAILED – "API: iam:CreateRole User: arn:aws-us-gov:iam::257940150393:user/HAlicea is not authorized to perform: iam:CreateRole on resource: arn:aws-us-gov:iam::257940150393:role/eksctl-ferocious-party-1598716193-clus-ServiceRole-1DZNWDEADQQXP"
[✖]  AWS::EC2::EIP/NATIP: CREATE_FAILED – "API: ec2:allocateAddress You are not authorized to perform this operation. Encoded authorization failure message: f4Dbu....eMXVmUCOI"
[✖]  **AWS::EC2::InternetGateway/InternetGateway: CREATE_FAILED** – "API: ec2:CreateInternetGateway You are not authorized to perform this operation. Encoded authorization failure message: LVxvI5TO...ZNxzBpi0FA0D"
[✖]  **AWS::EC2::VPC/VPC: CREATE_FAILED – "API: ec2:CreateVpc** You are not authorized to perform this operation. Encoded authorization failure message: lmilPEiWb7sWq...YQnvc13"

**Comment by cPu1** [comment]
Can you run the command with verbose logging enabled and share the logs?

```
$ eksctl create cluster \
	--name=${AWS_EKS_CLUSTER_NAME} \
	--version=${AWS_EKS_CLUSTER_VERSION} \
	--kubeconfig $(pwd)/${ENVIRONMENT}/config \
	--nodegroup-name=${AWS_EKS_NODEGROUP_NAME} \
	--node-private-networking \
	--node-type=t3.large \
	--nodes=3 \
	--nodes-min=3 \
	--nodes-max=12 \
	--region=${AWS_EKS_REGION} \
	--vpc-private-subnets=${AWS_EKS_VPC_PRIVATE_SUBNETS} \
        -v4
```

(FYI, there's a typo in your `ENVIRONMENT` variable)

**Comment by hectoralicea** [comment]
Thank you.   Having looked at the reason why my variable  `ENVIRONMENT ` was not spelled correctly, I saw that I was not including  (e.g. via source) the ENV VARS properties file that was defining this environment.  Once I did that, I only found one likely error.   My VPC and Internet gateway errors went away.   

Now I'm only getting the following error, which I'll ask to be added to my account.

```
2020-08-31T15:42:18Z [✖]  AWS::IAM::Role/ServiceRole: CREATE_FAILED – "API: iam:CreateRole User: arn:aws-us-gov:iam::XXXXXXXXX:user/HAlicea is not authorized to perform: iam:CreateRole on resource: arn:aws-us-gov:iam::XXXXXXXXX:role/eksctl-acr-dev-eks-cluster-ServiceRole-XXXXXXXXX"
```

**Comment by cPu1** [comment]
As you noticed, this was caused by not passing any values to `--vpc-private-subnets`, and that resulted in creation of a dedicated VPC.  If you have any more questions, please open a new issue.
