### ISSUE TITLE
Clash for tag name when creating node group

### ISSUE THREAD

**Issue by vandamb** [weaveworks/eksctl#2603]
**What happened?**
When having a name tag defined in cluster.yaml file, nodegroup creation fails due to clashes with another  "name" tag applied by eksctl to the InstanceRole.

**What you expected to happen?**
I would expect eksctl to use namespaced tags (e.g. eksctl.io.name) for internal purposes, and not a general "name" tag.

**How to reproduce it?**
Inside cluster.yaml file, specify a name tag
_metadata:
    tags:
      name: eks-test_

then, create any nodegroup from the yaml file:
eksctl create ng --config-file=./cluster.yaml

**Anything else we need to know?**

**Versions**
Please paste in the output of these commands:
```
$ eksctl version: 0.26.0
$ kubectl version: Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"39a145ca3413079bcb9c80846488786fed5fe1cb", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

[ℹ]  deploying stack "eksctl-eks-test-nodegroup-workers-eks-test-reserved-m4-V1-16"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-eks-test-nodegroup-workers-eks-test-reserved-m5-V1-16"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[✖]  AWS::EC2::SecurityGroup/SG: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Role/NodeInstanceRole: CREATE_FAILED – "**Duplicate tag keys found**. Please note that Tag keys are case insensitive. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: InvalidInput; Request ID: 35e3a07c-64c9-4059-9375-bd2f172e51e2; Proxy: null)"

**Comment by amitksahu** [comment]
Can I see your cluster.yaml file , I have a similar issue

**Comment by amitksahu** [comment]
I could replicate the issue

**Comment by michaelbeaumont** [comment]
I don't think we'll change this. As far as I can tell, users can add the namespace themselves.
