### ISSUE TITLE
Arm64 build support

### ISSUE THREAD

**Issue by scottmalkie** [weaveworks/eksctl#2621]
**Why do you want this feature?**
With the GA of EKS support for Graviton2 last month, it would be nice to have the `eksctl` binary and docker image built for Arm64. As `eksctl` is 97%+ written in Go, this should be mostly a build/script/packaging change rather than substantive code changes.

**What feature/behavior/change do you want?**
- [ ] The ability to compile eksctl from source on Arm64
- [ ] Arm64 binaries generated automatically by the existing build processes
- [ ] Multi-arch images on the `weaveworks/eksctl` dockerhub

**Comment by Callisto13** [comment]
Believe this was done in https://github.com/weaveworks/eksctl/pull/2725
