### ISSUE TITLE
ability to manage control plane SG for private cluster

### ISSUE THREAD

**Issue by infa-ddeore** [weaveworks/eksctl#2627]
**Why do you want this feature?**
`eksctl create cluster` tries to connect to the control plane after it is ready and fails if control plane is **private**. Control plane SG doesn't allow 443 communication from VPC or any other CIDR by default. 
As a workaround we update the SG during cluster creation i.e. allow VPC cidr for 443 port, after this `eksctl` doesn't complain at the last stage.

**What feature/behavior/change do you want?**
allow adding rules in "Cluster security group", this will help in below connection:

"eksctl running on a VM within or peered vpc --> eks control plane private endpoint"

**Comment by chiranjib-b** [comment]
I've faced this issue as well, and it took a while for me to figure this out.
We should be allowed to add rules to the cluster/control plane security group

**Comment by michaelbeaumont** [comment]
Duplicate of https://github.com/weaveworks/eksctl/issues/1805

**Comment by michaelbeaumont** [comment]
@chiranjib-b @infa-ddeore Am I correct in thinking that #1805 would cover your use case?

**Comment by infa-ddeore** [comment]
yes, my use case will be covered in #1805
