### ISSUE TITLE
Support ALB ingress controller with Fargate

### ISSUE THREAD

**Issue by mhr3** [weaveworks/eksctl#2633]
**What happened?**
Deploying a cluster with both `--fargate` and `--alb-ingress-access` creates a cluster without ALB ingress controlller.

**Anything else we need to know?**
According to this blog post, all the setup seems pretty much the same as when not using Fargate: https://aws.amazon.com/blogs/containers/using-alb-ingress-controller-with-amazon-eks-on-fargate/

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.26.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Callisto13** [comment]
Hey @mhr3 could you confirm precisely which steps you took to deploy the controller? Were you running the commands in that doc, or just `eksctl` with those 2 flags? `--alb-ingress-access` does not deploy the controller to the cluster.

The ALB ingress controller is now deprecated, the new AWS Load Balancer Controller docs can be found [here](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html) :)

**Comment by mhr3** [comment]
I was only running eksctl.

**Comment by Callisto13** [comment]
Okay cool 😃 

Could you try following the [load balancer controller docs](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html) and let me know how that works for you?

The `--alb-ingress-access` flag (or `albIngress` in the config file) will just assign the correct policy to the node's role to allow the controller to work. It wont deploy the controller. That flag is really only useful when using a quickstart policy ([eg](https://github.com/weaveworks/eks-quickstart-app-dev)), or some other automation, but can be skipped if deploying the controller manually.
