### ISSUE TITLE
Deprecate static AMI resolver

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#2650]
Now that we have the automatic and the SSM resolvers for AMIs I think we can deprecate the static one.

- [ ] GH workflow removed

**Comment by michaelbeaumont** [comment]
Waiting for `0.33.0` #2710

**Comment by neha-viswanathan** [comment]
@michaelbeaumont @martina-if Hi! can we reopen #2661?

**Comment by cPu1** [comment]
@neha-viswanathan I have reopened it. Thanks for tracking this.
