### ISSUE TITLE
support for exsctl --version

### ISSUE THREAD

**Issue by techdragon** [weaveworks/eksctl#2653]
**Why do you want this feature?**
`eksctl` behaves differently from many other unix style command line programs by not having a `--version` flag. 

**What feature/behavior/change do you want?**
It would be good if `eksctl` had a `--version` flag so that every time I go to check the version of `eksctl` I dont have to remember it's one of the special programs that don't have the normal version flag, then remember what `eksctl` does use for getting the version. I'm not saying drop `eksctl version` i'm saying do what the `git` cli does and support both, `git version` and `git --version` both produce the git version information. Supporting `--version` would be a small but useful improvement in user experience in my opinion.

**Comment by michaelbeaumont** [comment]
Hi, we'd accept a PR adding `--version` since I don't see any disadvantages but many tools, e.g. `kubectl`, don't support `--version`. I'm going to close the issue because I don't think it's something we'll ever prioritize enough to implement.
