### ISSUE TITLE
cannot import name 'docevents' in eksctl cluster build steps

### ISSUE THREAD

**Issue by tech3371** [weaveworks/eksctl#2673]
**What happened?**
Below error appears when I spin up cluster using cluster.yaml with minimum configuration. 
```
[ℹ]  node "ip-xxx-xxx-xx-xx.eu-west-1.compute.internal" is ready
[ℹ]  node "ip-xxx-xxx-xx-xx.eu-west-1.compute.internal" is ready
[ℹ]  node "ip-xxx-xxx-xx-xx.eu-west-1.compute.internal" is ready
[ℹ]  node "ip-xxx-xxx-xx-xx.eu-west-1.compute.internal" is ready
[✖]  unable to use kubectl with the EKS cluster (check 'kubectl version'): Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python3.6/dist-packages/awscli/clidriver.py", line 36, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/local/lib/python3.6/dist-packages/awscli/help.py", line 23, in <module>
    from botocore.docs.bcdoc import docevents
ImportError: cannot import name 'docevents'
Unable to connect to the server: getting credentials: exec: exit status 1

[ℹ]  cluster should be functional despite missing (or misconfigured) client binaries
[✔]  EKS cluster "cluster" in "eu-west-1" region is ready
```

I am using these version. 
**Versions**
Please paste in the output of these commands:
```
$ eksctl version 0.19.0
$ kubectl version v1.15.11-eks-065dce
```
when ran `eksctl get clusters` it gives me that the cluster is up and running. 

I am setting up this on AWS Ubuntu 18.x EC2. Due to above error, I can't setup pods on the nodes. Any idea or help is appreciated. 
Thank you in advance!

**Comment by michaelbeaumont** [comment]
It looks like you haven't got the `aws` cli tool installed correctly. `eksctl` sets up the kubeconfig to use this tool for authentication if it finds it on `$PATH`. It looks like you may have run into [this issue](https://github.com/boto/boto3/issues/2596).

**Comment by tech3371** [comment]
Thank you for quick response!

I have aws installed and it's version is below, 
```
aws --version
aws-cli/1.18.145 Python/3.6.9 Linux/5.3.0-1034-aws botocore/1.18.4
```
On the link you shared, they talked about installing botocore version < 1.18.0, any suggestion on how to do that when installing awscli.

**Comment by michaelbeaumont** [comment]
@tech3371 What's the output of `which aws`? Just to make sure the executable that `eksctl` finds is the same one you have > 1.18.140.

**Comment by michaelbeaumont** [comment]
@tech3371 I'm going to close this issue because I don't think the problem lies with `eksctl`. Let us know here if you have more information.
