### ISSUE TITLE
can't add new node group in existing cluster

### ISSUE THREAD

**Issue by amoswang0917** [weaveworks/eksctl#2686]
Hi

I used eksctl create nodegroup -f creare-igbw-test-and-dev-all-in-one-cluster.yaml 

and then get this error

[ℹ]  eksctl version 0.28.1
[ℹ]  using region ap-northeast-1
[ℹ]  will use version 1.17 for new nodegroup(s) based on control plane version
Error: getting VPC configuration for cluster "igbw-test-and-dev-all-in-one-cluster": no output "VPC" in stack "eksctl-igbw-test-and-dev-all-in-one-cluster-nodegroup-igbw-test-and-dev-all-in-one-cluster"

so, I use this command
eksctl utils describe-stacks --name=igbw-test-and-dev-all-in-one-cluster --region=ap-northeast-1 | grep VPC

get this return:
Flag --name has been deprecated, use --cluster
  Description: "EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by eksctl]",
      ExportName: "eksctl-igbw-test-and-dev-all-in-one-cluster-cluster::VPC",
      OutputKey: "VPC",

So... I don't know how to fix this problem.
Please help me...Thanks.

**Comment by michaelbeaumont** [comment]
@amoswang0917 Can you include the config you used?

**Comment by amoswang0917** [comment]
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: igbw-test-and-dev-all-in-one-cluster
  region: ap-northeast-1

vpc:
  cidr: 10.111.0.0/16
  nat:
    gateway: HighlyAvailable

managedNodeGroups:
  - name: igbw-dev-nodegroup 
    instanceType: m5.xlarge
    privateNetworking: true 
    ssh: 
      publicKeyName: xxxxx
    volumeSize: 300
    volumeType: gp2
    minSize: 1
    maxSize: 1
    #ami: auto
    labels:
      nodegroup-type: igbw-dev-nodegroup
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true
        efs: true
        imageBuilder: true
        externalDNS: true
        certManager: true
        appMesh: true
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/igbw-dev-nodegroup: "owned"

  - name: igbw-test-nodegroup 
    instanceType: m5.xlarge
    privateNetworking: true 
    ssh: 
      publicKeyName: xxxxx
    volumeSize: 300
    volumeType: gp2
    minSize: 1
    maxSize: 1
    #ami: auto
    labels:
      nodegroup-type: igbw-test-nodegroup
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true
        efs: true
        imageBuilder: true
        externalDNS: true
        certManager: true
        appMesh: true
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/igbw-test-nodegroup: "owned"

nodeGroups:
  - name: igbw-test-and-dev-all-in-one-cluster 
    instanceType: m5.xlarge
    privateNetworking: true 
    ssh: 
      publicKeyName: xxxxx
    volumeSize: 300
    volumeType: gp2
    minSize: 2
    maxSize: 6
    ami: auto
    labels:
      nodegroup-type: igbw-test-and-dev-all-in-one-cluster
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true
        efs: true
        imageBuilder: true
        externalDNS: true
        certManager: true
        appMesh: true
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/igbw-test-and-dev-all-in-one-cluster: "owned"

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

**Comment by michaelbeaumont** [comment]
@amoswang0917 Is this error still happening? Does your cluster function otherwise normally? Does it happen with any other clusters? It looks like the `VPC` Output is being looked for in the nodegroup stack but it should be found in the _cluster_ stack.
