### ISSUE TITLE
Failed nodegroup creation causes `get nodegroup` to fail

### ISSUE THREAD

**Issue by michaelbeaumont** [weaveworks/eksctl#2687]
The same happens when failed creating the nodegroup.  if it's failed once you have to manually goto cloudformation to delete that stack. otherwise eksctl will keep looking into that failed stack which will preventing other normal operation.

```
eksctl get nodegroup --cluster abcd
Error: getting nodegroup stack summaries: mapping stack to nodegroup summary: error collecting Cloudformation outputs for stack eksctl-abcd-nodegroup-ng-workers-2: no output "InstanceRoleARN" in stack "eksctl-abcd-nodegroup-ng-workers-2"
```

_Originally posted by @chimerab in https://github.com/weaveworks/eksctl/issues/1967#issuecomment-700604257_

**Comment by michaelbeaumont** [comment]
@michaelbeaumont 

at least below two versions have same problem.

eksctl version
0.27.0
0.28.1

First I try to create nodegorup with "eksctl create nodegroup -f xxxx-ng-workers-2.yaml" the stack failed because the volume size is smaller than image. 

[ℹ]  deploying stack "eksctl-abcd-nodegroup-ng-workers-2"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-abcd-nodegroup-ng-workers-2"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::EC2::LaunchTemplate/NodeGroupLaunchTemplate: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterClusterAPI: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterCluster: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterCP: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterAPI: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterCluster: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/SSHIPv4: DELETE_IN_PROGRESS
[✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "You must use a valid fully-formed launch template. Volume of size 20GB is smaller than  snapshot 'snap-abcdef', expect size >= 80GB (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: xxxxx-xxxx-xxxx-xxxxx-xxxxxxxx; Proxy: null)"
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=ap-northeast-1 --cluster=abcd --name=<name>' for each of the failed nodegroup
[✖]  waiting for CloudFormation stack "eksctl-abcd-nodegroup-ng-workers-2": ResourceNotReady: failed waiting for successful resource state
Error: failed to create nodegroups for cluster "abcd"

After above nodegroup creation failed. the stack in cloudformation is in "ROLLBACK_COMPLETE" status. any eksctl nodegroup will not work properly until i manually delete the problematic stack. 

_Originally posted by @chimerab in https://github.com/weaveworks/eksctl/issues/1967#issuecomment-700667913_

**Comment by aclevername** [comment]
I've managed to reproduce this on `0.29.2` creating an unmanaged nodegroup:

```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: unmanaged-nodegroup
  region: us-west-2

nodeGroups:
  - name: managed-ng-2
    instanceType: t2.large
    volumeSize: 1
```

```
$ eksctl create cluster -f cluster.yaml
...
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-unmanaged-nodegroup-nodegroup-managed-ng-2"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::IAM::Role/NodeInstanceRole: DELETE_IN_PROGRESS
[!]  AWS::IAM::InstanceProfile/NodeInstanceProfile: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroup/SG: DELETE_IN_PROGRESS
[!]  AWS::EC2::LaunchTemplate/NodeGroupLaunchTemplate: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterCP: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterClusterAPI: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterClusterAPI: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupIngress/IngressInterCluster: DELETE_IN_PROGRESS
[!]  AWS::EC2::SecurityGroupEgress/EgressInterCluster: DELETE_IN_PROGRESS
[✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "You must use a valid fully-formed launch template. Volume of size 1GB is smaller than  snapshot 'snap-0e3c996524f02a160', expect size >= 4GB (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: 975cffcb-fdfe-489f-aef5-bf199493e17a; Proxy: null)"
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-west-2 --name=unmanaged-nodegroup'
[✖]  waiting for CloudFormation stack "eksctl-unmanaged-nodegroup-nodegroup-managed-ng-2": ResourceNotReady: failed waiting for successful resource state

$ eksctl get nodegroups --cluster unmanaged-nodegroup
Error: getting nodegroup stack summaries: mapping stack to nodegroup summary: error collecting Cloudformation outputs for stack eksctl-unmanaged-nodegroup-nodegroup-managed-ng-2: no output "InstanceRoleARN" in stack "eksctl-unmanaged-nodegroup-nodegroup-managed-ng-2"
```
