### ISSUE TITLE
Add --ami-id as in put parameter for eksctl command

### ISSUE THREAD

**Issue by gautamkmr** [weaveworks/eksctl#269]
**Why do you want this feature?**

If we hard code the ami-id it will be a maintenance headache. For e.g. the AMI id for gpu machine which you have today might be different tomorrow, due to various reasons like (CUDA upgrade,  or OS upgrade).  

If we want EKS user to get up-to date AMI, there should be an option to pass the ami-id as well. You can keep the default AMI-ID which you have currently but recommended way would be to get the AMI-ID from user.

**Comment by gautamkmr** [comment]
@arun-gupta

**Comment by richardcase** [comment]
@gautamkmr - we have this ability already with the `node-ami` flag:

> Advanced use cases only. If 'static' is supplied (default) then eksctl will use static AMIs; if 'auto' is supplied then eksctl will automatically set the AMI based on region/instance type; if any other value is supplied it will override the AMI to use for the nodes. Use with extreme care

.

**Comment by errordeveloper** [comment]
In other words, `--node-ami=auto --node-type=p2.xlarge` will let you use latest available GPU-optimised AMI.

**Comment by errordeveloper** [comment]
@gautamkmr can we close this?

**Comment by arun-gupta** [comment]
Sounds reasonable to me
