### ISSUE TITLE
Unable to configure kube-system/aws-node IRSA with eksctl 0.29.0.

### ISSUE THREAD

**Issue by cw-sakamoto** [weaveworks/eksctl#2700]
**What happened?**

In this [document](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-cni-walkthrough.html), the following command to configure IRSA for aws-node results in an error.

```
% eksctl create iamserviceaccount \
    --name aws-node \
    --namespace kube-system \
    --cluster mycluster \
    --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy \
    --approve \
    --override-existing-serviceaccounts
Error: <namespace>/<name> of iam.serviceAccounts[1] "kube-system/aws-node" is not unique
```

It was working in `0.28.1,` ... is it an unexpected error?

**What you expected to happen?**
- I want the same commands to work in 0.29.0.
  - If it's no longer needed in `0.29.0` withOICD, then it's fine.

**Comment by michaelbeaumont** [comment]
@cw-sakamoto please check if the service account exists already and has the corresponding annotation. 
If the cluster was created with version >= `0.28.0-rc.0` and `withOIDC` then `create iamserviceaccount` isn't necessary for `aws-node`. We'll improve the docs on this.
