### ISSUE TITLE
Kube2iam Addon

### ISSUE THREAD

**Issue by Lazyshot** [weaveworks/eksctl#271]
Looking to add a kube2iam addon that would auto create the IAM policies and install the helm chart (of course).

The only thing missing from possible full coverage would be handling trust relationships.

**Comment by GSokol** [comment]
Could you please explain the idea of this issue in more detail?

**Comment by errordeveloper** [comment]
Umbrella issue: #53
Add-ons proposal: #242

**Comment by kgoralski** [comment]
kube2iam or kiam ?

**Comment by whereisaaron** [comment]
I found this comparison useful:
https://www.bluematador.com/blog/iam-access-in-kubernetes-kube2iam-vs-kiam

Both tools need an extra policy attached to the nodegroup node role. Does `eksctl` have any option to attach a named IAM policy to the node role?

**Comment by atif1996** [comment]
Looks like when I add the kube2iam role to the node group role, it works, but I can't teardown the elks cluster without first manually removing the kube2iam role.  Would be great if eksctl allowed you to specify the name/arn of the policy to attach to the node group role.

**Comment by errordeveloper** [comment]
Have people seen this https://github.com/mikkeloscar/kube-aws-iam-controller?

**Comment by github4es** [comment]
Are there any updates on this? I need to configure the AWS ALB ingress controller and it seems I need to configure kube2iam. I used eksctl to crreate my cluster. Are there any updated steps to configure eksctl with a given role or must we euse kube2iam ?

**Comment by errordeveloper** [comment]
I think this can be close, [IAM Roles for  Service Accounts](https://eksctl.io/usage/iamserviceaccounts/) are the best recommended option.

**Comment by errordeveloper** [comment]
@martina-if please close it =)
