### ISSUE TITLE
Container image for eksctl version 0.29.2

### ISSUE THREAD

**Issue by abdennour** [weaveworks/eksctl#2716]
**Why do you want this feature?**
To run eksctl from within container

**What feature/behavior/change do you want?**
Container image with eksctl CLI defined

**Comment by abdennour** [comment]
The image will be available after a while under : https://hub.docker.com/r/abdennour/eksctl/tags
There is now pending automated build by docker hub.
Stay tuned!

**Comment by michaelbeaumont** [comment]
We already publish images at `weaveworks/eksctl`, there are also multiple community-published Images.

**Comment by abdennour** [comment]
Not sure why you closed issue before getting my approval.
But no problem, let me list the images of **0.29.2** release: 

- docker pull abdennour/eksctl:0.29.2-aws-1.18.154
- docker pull abdennour/eksctl:0.29.2-aws-1.18.154-kubectl-v1.19.2

https://hub.docker.com/r/abdennour/eksctl/tags?page=1&name=0.29.2

**Comment by michaelbeaumont** [comment]
Indeed, and thanks for contributing back to `eksctl`! Closing the issue wasn't meant to come across rude, it's just that an issue tracking an `eksctl` image for a specific release version isn't very useful. We would very much welcome PRs for improving the official image! :slightly_smiling_face:
