### ISSUE TITLE
Expand integration test coverage

### ISSUE THREAD

**Issue by michaelbeaumont** [weaveworks/eksctl#2722]
We should have another, more complete suite of tests to cover more cases/settings.

**Comment by aclevername** [comment]
I'm going to spend some time going over to see whats tested and write it up here.

@michaelbeaumont is there any areas that standout as being weakly tested?

**Comment by michaelbeaumont** [comment]
I think the impetus was something around IRSA, which I think we have no integration tests for

**Comment by aclevername** [comment]
Existing tests:

### `addons`
- testing `eksctl CRUD addon` 👍 

### `backwards_compat`
- checks that clusters created with the previous version of the CLI can be used with the current CLI
- `eksctl get/delete nodegroup`
- `eksctl utils update-legacy-subnet-settings` 👍 

### `before_active`
- checks that you can delete a cluster during cluster creation *maybe*? Seems very unclear 👎 

### `cluster_api`
- checks `eksctl CRUD cluster` of various cluster configurations 👍 

### `crud`
- `eksctl CRUD cluster` (slight duplicaton to above, delete involves more codepath as more features are enabled)
- `eksctl utils update-cluster-logging` 
- `eksctl CRUD iamserviceaccount`
- checks `coredns` works 👍 
- `eksctl CRD  iamidentitymapping`
- `eksctl scale/create/delete nodegroup` + GPU support 👍 

### `fargate`
- `eksctl CRD fargate`

### `inferentia`
### `managed`
### `quickstart_profiles`
### `quickstart_profiles_gen`
### `unowned_cluster`
### `update`
