### ISSUE TITLE
Outbound internet traffic from pod

### ISSUE THREAD

**Issue by marcotralala** [weaveworks/eksctl#2737]
**What happened?**
Trying to invoke web requests from inside of a container to an internet site, which is returning

`Invoke-WebRequest : The remote name could not be resolved: www.google.com`
`At line:1 char:1`
`Invoke-WebRequest https://www.google.com`

`     CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException`
`     FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**What you expected to happen?**
Expect it to be be returning a 200. This is happening on the EKS worker node when I invoke the same web request.

**How to reproduce it?**
`kubectl exec -it <pod-name> powershell`

Invoke-WebRequest https://www.google.com

**Anything else we need to know?**
This is happening in a pod on a windows worker node which has been created within an eks cluster with this command:
`eksctl create cluster -f cluster-spec.yaml --install-vpc-controllers`

and in yaml for windows worker node settings are

```
nodeGroups:
  - name: windows-ng
    labels: { role: workers }
    instanceType: m5.large
    minSize: 1
    privateNetworking: true
    volumeSize: 100
    amiFamily: WindowsServer2019FullContainer
```

output of below command is showing the groups for the windows node instance role:
`kubectl describe configmap aws-auth -n kube-system`
  
```
groups:
    - system:bootstrappers
    - system:nodes
    - eks:kube-proxy-windows
```

also below command is showing good settings:
`kubectl describe clusterrolebinding eks:kube-proxy-windows`

```
Role:
  Kind:  ClusterRole
  Name:  system:node-proxier
Subjects:
  Kind   Name                    Namespace
  Group  eks:kube-proxy-windows
```

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
$ kubectl version
```
0.27.0

`Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by aclevername** [comment]
Hey @marcotralala 👋 

I tried to reproduce the issue using the same config on eksctl `0.29.2` and `0.27.0`, but failed to reproduce the error.

For reference the pod I am using is taken from the docs: https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/#getting-started-deploying-a-windows-container and I was running `Invoke-WebRequest -URI https://www.google.com -UseBasicParsing` (your example excludes the `-UseBasicParsing` flag, which caused me to get a different error probably related to the container I'm running)

Can you reproduce this on the same cluster with the above pod?

**Comment by marcotralala** [comment]
Yes getting the same error with the win-webserver pod 
kubectl exec -it win-webserver-5f8678bc7c-sln47 powershell

Invoke-WebRequest : The remote name could not be resolved: 'www.google.com'

Maybe something to do with core-dns configmap that I patched to match my domain and dc ip address

**Comment by marcotralala** [comment]
Hi @aclevername ,

I have recreated the eks cluster and can now successfully initiate outbound internet traffic from the pods. I suspect the gMSA and domain join resources that I'm applying to the cluster is breaking outbound internet traffic. Also I'm patching the coredns config map to cater for the domain.  I will test this tomorrow.

**Comment by marcotralala** [comment]
OK, I have reproduced this. Outbound internet traffic in the pod is broken after I join the windows worker node to a domain using SSM to send a command: 
`$commandId = aws ssm send-command --document-name $adGroupCreateSSMdoc --targets "Key=InstanceIds, Values=i-xxxxxxxxxx" --parameters "ADSecurityGroup=$gMSAADSecurityGroup" --query "Command.CommandId" --output text`

with command document linked:

[https://github.com/aws-samples/amazon-ecs-gmsa/blob/master/cloud-formation-templates/ssm-document-adgroup-createandjoin.yaml](url)

**Comment by aclevername** [comment]
> OK, I have reproduced this. Outbound internet traffic in the pod is broken after I join the windows worker node to a domain using SSM to send a command:
> `$commandId = aws ssm send-command --document-name $adGroupCreateSSMdoc --targets "Key=InstanceIds, Values=i-xxxxxxxxxx" --parameters "ADSecurityGroup=$gMSAADSecurityGroup" --query "Command.CommandId" --output text`
> 
> with command document linked:
> 
> [https://github.com/aws-samples/amazon-ecs-gmsa/blob/master/cloud-formation-templates/ssm-document-adgroup-createandjoin.yaml](url)

Thanks for the follow up @marcotralala, do you believe this issue is fixable on eksctl's end, or is this an issue with ssm/the command being run? I'm no overly familiar with windows in this context.

**Comment by marcotralala** [comment]
This might have to do with the way eksctl creates a windows worker node. It might not be setting the correct bootstrap arguments to make AWS EKS work with a gMSA account. This is explained in this document: 

https://aws.amazon.com/blogs/containers/how-to-run-eks-windows-containers-with-group-managed-service-account-gmsa/

Another area that might have to be set correctly might be the network policy on the windows node. I see that EKSCTL is creating an L2Bridge network, which should provide access to the underlay network, but I'm not seeing the same behavior with outbound traffic on the node and within the container, so something is not right there.

If the EKSCTL create cluster command is already setting the gMSA and network options correctly, then I would say this is an AWS problem, where joining a windows worker node to a domain breaks the outbound internet traffic. This for me is a showstopper for being able to use gMSA and windows integrated auth. 

The script is not doing anything special to break outbound internet traffic. It is only adding the windows worker node to an AD security group, creating the group if it does not exist, then restarting the node. As mentioned before, outbound internet traffic is not broken on the worker node, only within the container on that node, so that means the ssm command script is not doing anything wrong as this should only impact the node.

**Comment by marcotralala** [comment]
Got further with this. The scripts that are joining to a domain are not setting the core-dns pod ips correctly. This is fixed by setting them. It is set to 172.20.0.10 but should be set to the core-dns pod ip's to resolve dns names.

Inside your application pod run the below command:
`Set-DnsClientServerAddress -InterfaceIndex 24 -ServerAddresses 172.20.0.10,<core-dns-pod1-ip>,<core-dns-pod2-ip>`

**Comment by aclevername** [comment]
> Got further with this. The scripts that are joining to a domain are not setting the core-dns pod ips correctly. This is fixed by setting them. It is set to 172.20.0.10 but should be set to the core-dns pod ip's to resolve dns names.
> 
> Inside your application pod run the below command:
> `Set-DnsClientServerAddress -InterfaceIndex 24 -ServerAddresses 172.20.0.10,<core-dns-pod1-ip>,<core-dns-pod2-ip>`

Thanks for the follow up @marcotralala , sounds like you managed to fix the issue. I'm going to close this issue as it appears nothing needs to change on the EKSCTL side.
