### ISSUE TITLE
Clean up EBS volumes in `eksctl delete cluster`

### ISSUE THREAD

**Issue by chuckwilbur** [weaveworks/eksctl#274]
**What happened?**
After using `eksctl delete cluster` to delete a cluster, multiple EBS volumes that were attached to the ec2 instances remain.

**What you expected to happen?**
When using `kops delete cluster` to delete a cluster, the EBS volumes that were attached to the ec2 instances are destroyed.

**How to reproduce it?**
Create a cluster with `eksctl create cluster`
Note in the Volumes area of the ec2 console that a number of volumes named `kubernetes-dynamic-pvc-*` have been created. In the Instances area of the ec2 console, select one of the node instances and see the Block devices entry under the description. Devices other than the root device have Delete on Termination set to false.
Delete the cluster with `eksctl delete cluster`
The non-root volumes are orphaned, their state becomes 'available'.

**Anything else we need to know?**
OS: MacOS
eksctl installed via brew
User credentials set via `export AWS_PROFILE`

Using `kops`, `create cluster` also creates EBS volumes with Delete on Termination set to false, but `kops delete cluster` cleans them up somehow. It seems `eksctl` should do the same.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
2018-10-18T14:00:11-05:00 [ℹ]  versionInfo = map[string]string{"builtAt":"2018-10-18T09:39:17Z", "gitCommit":"42472284809120503270b4401ce07ad26f52ffa4", "gitTag":"0.1.7"}
$ uname -a
Darwin cwilburmbp.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-10-01T17:47:15Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Also include your version of `heptio-authenticator-aws`
Not sure how to find this. I did a `brew upgrade eksctl-aws-iam-authenticator` this morning (18 Oct. 2018)

**Comment by errordeveloper** [comment]
This is very much related to #103. There are no blockers here, anyone can start on either of these (ideally one person working on both would be great).

**Comment by richardcase** [comment]
@Raffo - what do you think to this one?

**Comment by Raffo** [comment]
Will try to get a shot at that 😄

**Comment by errordeveloper** [comment]
I have started thinking of it, I figure I should look at kops does in order
to catch any left-over volumes or LBs, and in the process of that I wrote
#277.

**Comment by ollevche** [comment]
Hey there! Any update? Have the same issue

**Comment by Spongman** [comment]
why was this closed?

**Comment by hatimk** [comment]
Any updates on this?

**Comment by vivekkarne** [comment]
^ Addressed in #536

**Comment by rkashasl** [comment]
Any updates?

**Comment by Himangini** [comment]
> Any updates?

@rkashasl This issue has been closed a long time ago, what updates are you looking for? If you are having any issues please open a [new issue ](https://github.com/weaveworks/eksctl/issues/new/choose) with relevant details.
