### ISSUE TITLE
EKSCTL cannot add nodegroups even when I have k8s masters role

### ISSUE THREAD

**Issue by shrivastavshubham34** [weaveworks/eksctl#2745]
Hello,

```
EKSCTL version: 0.28.1
EKS version 1.15
```

EKSCTL throws me the following error every time I try to add node groups to the existing cluster.
```
SSHRIVASTAVA01-MB-2:eksctl sshrivastava$ eksctl create nodegroup --config-file=NodeGroup.yml 
[ℹ]  eksctl version 0.28.1
[ℹ]  using region us-xxxx
[ℹ]  will use version 1.15 for new nodegroup(s) based on control plane version
[ℹ]  nodegroup "xxxxxxxxx" present in the given config, but missing in the cluster
[ℹ]  nodegroup "xxxxxx" present in the cluster, but missing from the given config
[ℹ]  nodegroup "xxxxxxxxxx" present in the cluster, but missing from the given config
[ℹ]  nodegroup "xxxxxxxxxxx" present in the cluster, but missing from the given config
[ℹ]  3 existing nodegroup(s) (xx,xx,xx) will be excluded
Error: getting list of API resources for raw REST client: Unauthorized
```
Other commands like **eksctl get --** works without any issues.

I also am able to do all operations using kubectl, since I have a masters role in auth configmap

What might the issue be?

**Comment by michaelbeaumont** [comment]
Please see https://github.com/weaveworks/eksctl/issues/1356#issuecomment-686981450 and the following comments

**Comment by shrivastavshubham34** [comment]
Tried the below method but did not work,
Seems its not able to find the cluster now

![image](https://user-images.githubusercontent.com/13406071/96323984-416bcf80-0fd4-11eb-9df5-9684d5d1562a.png)

**Comment by michaelbeaumont** [comment]
@shrivastavshubham34 That may be due to the default region having changed with the profile, can you specify the region?

**Comment by shrivastavshubham34** [comment]
Nope, the cluster's in us-east-1 and EKS runs in the same region.
![image](https://user-images.githubusercontent.com/13406071/98754245-2003c680-237b-11eb-9b84-6f09a64149f8.png)

**Comment by michaelbeaumont** [comment]
I was referring to the problem you mentioned in the last comment where using the other profile and running `get nodegroups` failed to find the cluster. Is that run using the new profile? You can include the command and output as text here.

**Comment by shrivastavshubham34** [comment]
Yeah that one worked, with correct permissions, but the unauthorized error still exists.
```shell
eksctl get nodegroup --profile dev-admin --cluster=cluster-name
CLUSTER		NODEGROUP		STATUS		CREATED			MIN SIZE	MAX SIZE	DESIRED CAPACITY	INSTANCE TYPE	IMAGE ID
cluster-name	ng-capacity-optimized	DELETE_FAILED	2020-04-06T07:50:42Z	2		4		4			m5.large	ami-xxxxxxxxxxxxxxxxx
cluster-name	ngCapacityOptimized	CREATE_COMPLETE	2020-05-17T09:55:10Z	4		6		0			m5.large	ami-xxxxxxxxxxxxxxxxx
cluster-name	ngNifi			CREATE_COMPLETE	2020-05-18T08:23:18Z	1		2		0			m5.large	ami-xxxxxxxxxxxxxxxxx
```
Below command throws error:
```shell
eksctl create nodegroup --config-file=somefile.yml
[ℹ]  eksctl version 0.31.0
[ℹ]  using region us-east-1
[ℹ]  will use version 1.16 for new nodegroup(s) based on control plane version
[ℹ]  nodegroup "ngxxxxxxxxxx" present in the given config, but missing in the cluster
[ℹ]  nodegroup "ng-capacity-xxxxxxxx" present in the cluster, but missing from the given config
[ℹ]  3 existing nodegroup(s) (ng-capacity-xxxxxxxx,ngCxxxxxxx,ngNxxx) will be excluded
Error: getting list of API resources for raw REST client: Unauthorized

```

**Comment by michaelbeaumont** [comment]
Just to be clear, the last command also fails if you include `--profile dev-admin`? Can you include `-v 4`? Near the beginning, `eksctl` should print what `RoleARN` it's using. Can you confirm whether that's the correct `ARN`?

**Comment by shrivastavshubham34** [comment]
After multiple try-catches and assigning policies to my role, I get this.
```shell
[✖]  unexpected status "ROLLBACK_COMPLETE" while waiting for CloudFormation stack "eksctl-skdjksjdf-nonprod-k8s-nodegroup-ngTestShubham"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::EC2::SecurityGroup/SG: DELETE_IN_PROGRESS
[✖]  AWS::EC2::SecurityGroup/SG: CREATE_FAILED – "Resource creation cancelled"
[✖]  AWS::IAM::Role/NodeInstanceRole: CREATE_FAILED – "API: iam:CreateRole User: arn:aws:sts::1234567890:assumed-role/role_name/213821381238 is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::1234567890:role/eksctl-jdhajhsd-nonprod-k8s-nodegro-NodeInstanceRole-1hdhhhjhd"
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=us-east-1 --cluster=ashdhdf-ajsjdjd-k8s --name=<name>' for each of the failed nodegroup
[✖]  waiting for CloudFormation stack "eksctl-ajhsdjhad-nonprod-k8s-nodegroup-ngTestShubham": ResourceNotReady: failed waiting for successful resource state
```
My colleague who created the cluster can run the same commands without any profile and has the same IAM access as me in this AWS account.
Why is he able to update the cluster and I'm not? 
I have below policy same as him
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

**Comment by michaelbeaumont** [comment]
It seems like your role is unable to even `iam:CreateRole`, is the role `arn:aws:sts::1234567890:assumed-role/role_name/213821381238` the expected one?

**Comment by shrivastavshubham34** [comment]
Yup, It is, I can assign it some policies, but I want to know if EKSCTL creates a Cluster admin IAM role and assigns it to cluster creator because my colleague is able to access and make modifications to code.
He was the one who created the EKS cluster.
We both have the same policies

**Comment by michaelbeaumont** [comment]
No, `eksctl` doesn't create any roles except a role for the cluster and one for each nodegroup. The cluster creator can always access the cluster. Every other user needs to go through the configmap.
Are you saying the mentioned role has that allow everything policy attached? It appears at least that's not the case.

Can you please always include the commands you're running as well as the full output with `-v 4`?

There are two relevant switches here, `--profile` for AWS APIs as well as `--cfn-role-arn` that can be used for changing how CFN is called.

**Comment by shrivastavshubham34** [comment]
You're right, the above allow everything policy was for my IAM user not the role I was assuming.
After attaching the Admin policy the nodegroups were created successfully.

However, I'm not comfortable using AllowEverything policy and would like to know if there's some policy I can create or use that'll give me privileges to add and remove nodegroups and modify cluster.

**Comment by michaelbeaumont** [comment]
Great! I think you should be able to find everything you need to put together a policy in [the eksctl IAM policies docs](https://eksctl.io/usage/minimum-iam-policies/) as well as [the AWS docs on EKS actions](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticcontainerserviceforkubernetes.html#amazonelasticcontainerserviceforkubernetes-actions-as-permissions).

**Comment by shrivastavshubham34** [comment]
Thanks, i was able to put together a policy and now everything works fine.
Just curious, what seperates the cluster creator from other users? Why doesn't assuming same policies as cluster creator give me admin access?

**Comment by michaelbeaumont** [comment]
The AWS IAM policies govern access at a granularity of clusters, the `eks:*` actions. So you can modify the EKS configuration, add managed nodegroups, delete managed nodegroups. Actually accessing the cluster and manipulating kubernetes resources is governed by the `auth-configmap`. Here only the cluster creator automatically has full access, and IAM policies play no part. Depending on the command, `eksctl` does one or both of these things.

**Comment by michaelbeaumont** [comment]
@shrivastavshubham34 Feel free to comment with any other questions! I'll close the issue now.

**Comment by shrivastavshubham34** [comment]
Thanks for the help @michaelbeaumont , you've been a great guide!!
