### ISSUE TITLE
zsh autocomplete error when calling eksctl create nodegroup - invalid option definition

### ISSUE THREAD

**Issue by ysam12345** [weaveworks/eksctl#2747]
**What happened?**
When I type `eksctl create nodegroup [TAB]`
It shows following error
`_arguments:comparguments:319: invalid option definition: --version[Kubernetes version (valid options: 1.14, 1.15, 1.16, 1.17) [for nodegroups "auto" and "latest" can be used to automatically inherit version from the control plane or force latest]]:
`

Tested on my two macbook pro / Amazon Linux 2 EC2 Instance and saw the same error.

**What you expected to happen?**
Showing the autocomplete choices without any error.

**How to reproduce it?**
1. follow the guide to install eksctl autocompletion
https://eksctl.io/introduction/#zsh
2. using zsh and type
`eksctl create nodegroup [TAB]`

**Anything else we need to know?**
I think it's similar to this issue:
https://github.com/clap-rs/clap/issues/771
I can manually add escape character to ~/.zsh/completion/_eksctl line334
<img width="1430" alt="圖片" src="https://user-images.githubusercontent.com/28039402/96243710-aecd2f80-0fd7-11eb-8b3a-05a1ab3ca986.png">
After that, it works fine
<img width="1430" alt="圖片" src="https://user-images.githubusercontent.com/28039402/96243227-01f2b280-0fd7-11eb-89f2-8aba7a870c7b.png">

**Versions**
```
$ eksctl version
0.29.2
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
<img width="1430" alt="圖片" src="https://user-images.githubusercontent.com/28039402/96240783-edf98180-0fd3-11eb-9bea-94622a648d26.png">

**Comment by neha-viswanathan** [comment]
@michaelbeaumont @ysam12345 Tested this out, looks like this works:
```
eksctl create nodegroup =                                                                                            
zsh: do you wish to see all 1562 possibilities (391 lines)?
```

But you have to enter the `=` manually.

**Comment by ysam12345** [comment]
Created a docker image for testing this issue
Dockerfile: https://github.com/ysam12345/test-eksctl-zsh-autocomplete/blob/master/Dockerfile

### Script
```
docker run -ti --rm ysam12345/test-eksctl-zsh-autocomplete 
eksctl create nodegroup [TAB*2]
```
### Output
![image](https://user-images.githubusercontent.com/28039402/96361283-f0d0af80-1156-11eb-98f2-3da370445d7c.png)

**Comment by neha-viswanathan** [comment]
@michaelbeaumont @ysam12345 will the new release of spf13/cobra v1.10 help with this - https://github.com/spf13/cobra/pull/1070
They seem to have a newer zsh completion https://github.com/spf13/cobra/releases/tag/v1.1.0

**Comment by ysam12345** [comment]
@michaelbeaumont @neha-viswanathan Yes, I think this is work.
I changed the version of spf13/cobra from v1.0.0(Current) to v1.1.0 and rebuild eksctl. 
The result look good.
![image](https://user-images.githubusercontent.com/28039402/96365935-d1e21580-1176-11eb-89cf-1b59a56aa3da.png)

**Comment by michaelbeaumont** [comment]
@ysam12345 a PR would be very welcome!

**Comment by ysam12345** [comment]
Thanks @michaelbeaumont , I have created a pull request for this issue.

**Comment by ysam12345** [comment]
Hello @michaelbeaumont,
I closed pull request https://github.com/weaveworks/eksctl/pull/2756 because: 
1. spf13/cobra release a new version [v1.1.1](https://github.com/spf13/cobra/releases/tag/v1.1.1) and I think we should upgrade to this version.
2. I have some concern when rewriting test case to fix the problem mentioned at https://github.com/weaveworks/eksctl/pull/2756#issuecomment-715898743.
Currently I have make two version of code change to fix the test case but haven't create a pull request yet because I'm not sure which one is better solution.
#### A [ysam12345:fix_zsh_completion_and_redirect_stdErr_to_stdOut](https://github.com/weaveworks/eksctl/compare/master...ysam12345:fix_zsh_completion_and_redirect_stdErr_to_stdOut?diff=split&expand=1)
I changed string "out", returned by "execute" function in test, to contain error message from stdErr.
This does the smallest code change(17 lines) but is a little bit weird to forward stdErr to a string named "out".
#### B [ysam12345:fix_zsh_completion_and_change_err_in_test](https://github.com/weaveworks/eksctl/compare/master...ysam12345:fix_zsh_completion_and_change_err_in_test?diff=split&expand=1)
I changed error "err", returned by "execute" function in test, to have error message from stdErr when error is occur and rewrite some test case from checking message in "out" to checking message in "err"([L75-L80](https://github.com/weaveworks/eksctl/compare/master...ysam12345:fix_zsh_completion_and_change_err_in_test?diff=split&expand=1#diff-a8b292f8530a81dd03c5b869c5b00e3cce959842dbbd43993ee7364a6905dc3eL75-L80)). I also rewrite some test condition from Equal to ContainSubstring , because the message from stdErr will be single/multiple lines with  newline at the end. Also some test case [L35-R38](https://github.com/weaveworks/eksctl/compare/master...ysam12345:fix_zsh_completion_and_change_err_in_test?diff=split&expand=1#diff-3452b5c909bd1935939b8ff7a48739ced534ac55f1444dc490240a85dc040bc7L35-R38) will fail to pass lint if changed the string in fmt.Errorf to end with \n, so I can't use Equal condition except to avoid using fmt.Errorf.
Besides, I add "Error: " to test case string because the message from stdErr will be have "Error: " at the beginning of string.

I wonder which one is better idea? And any suggestion will be helpful.

Thanks!

**Comment by michaelbeaumont** [comment]
I think B is good. However, these tests need desperately to be refactored. They don't actually test the real behavior of the CLI since they mock so much, see e.g. the expected error output here:

https://github.com/weaveworks/eksctl/blob/7db9b8b7af3061361f247d7d15424ce70e1dc7e0/pkg/ctl/completion/completion_test.go#L39-L45

When I print the contents of `out` in the test I get `Run 'completion --help' for usage.`

With `eksctl completion invalid-shell` however I get as error `Error: unknown resource type "invalid-shell"` instead, I also get the usage itself printed out, not the message how to do it.

**Comment by ysam12345** [comment]
Yeah I see...... We won't see the content of `out` when we actually run the CLI with an invalid input, so the test is testing something user won't see.

I think maybe they should be rewrote to test for the actually output?

Please let me know if i understand wrong.

**Comment by michaelbeaumont** [comment]
Yes exactly, they need to be rewritten but not for your PR! :)

**Comment by ysam12345** [comment]
Maybe I can help this in the future. 🙂
So I wonder is Plan B ok for a PR to fix this issue?

Thanks.

**Comment by michaelbeaumont** [comment]
@ysam12345 Yeah go ahead with plan b!
