### ISSUE TITLE
Attach boundary to aws-node service account

### ISSUE THREAD

**Issue by woltertaal** [weaveworks/eksctl#2749]
**What happened?**
when i create a cluster with "withOIDC: true" then a service account aws-node  will be created (since 0.28??). 
But the boundary wil not be set.

The creation of the role get errors because we can only create roles with a specific boundary in our AWS account.

**What you expected to happen?**
Create a service account with the boundary that i set in de configuration.

**How to reproduce it?**
config.yaml:

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: {EKSCLUSTERNAME}
  region: eu-central-1
  version: "1.18"

vpc:
  clusterEndpoints:
    publicAccess:  false
    privateAccess: true
  securityGroup: {ADDITIONALSECURITYGROUP}
  subnets:
    private:
      eu-central-1a: { id: {SUBNETIDA} }
      eu-central-1b: { id: {SUBNETIDB} }      
      eu-central-1c: { id: {SUBNETIDC} }

iam:
  withOIDC: true
  serviceRolePermissionsBoundary: "arn:aws:iam::{ACCOUNTID}:policy/boundarypolicy"
  fargatePodExecutionRolePermissionsBoundary: "arn:aws:iam::{ACCOUNTID}:policy/boundarypolicy"
  serviceAccounts:
  - metadata:
      name: alb-ingress-controller
      namespace: kube-system
    permissionsBoundary: "arn:aws:iam::{ACCOUNTID}:policy/boundarypolicy"
    attachPolicyARNs:
    - "arn:aws:iam::{ACCOUNTID}:policy/ALBIngressControllerIAMPolicy"

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system

command:
eksctl  create cluster -f config.yaml

Eksctl version:
$ eksctl version 0.30.0-rc.1

**Comment by michaelbeaumont** [comment]
@woltertaal Which boundary would you expect to be attached to the `aws-node` service account?

**Comment by woltertaal** [comment]
this boundary: arn:aws:iam::{ACCOUNTID}:policy/boundarypolicy .

Or can i specify which boundary i want to attache to the aws-node service account?
Or can i disable the creation of the aws-node service account?

**Comment by michaelbeaumont** [comment]
Yes, so you'll need to explicitly mention the `kube-system/aws-node` account if you want to specify the boundary, which is intended to be possible but at the moment throws an error, see https://github.com/weaveworks/eksctl/pull/2750

**Comment by woltertaal** [comment]
Oke, great.

That is exactly what i was trying to do, but got the error that kube-system-aws-node wasn't unique.

Thanks for the quick response
