### ISSUE TITLE
Cannot create Windows Private Cluster Without Internet

### ISSUE THREAD

**Issue by pnmcneil** [weaveworks/eksctl#2752]
**What happened?**
When creating a private cluster, the Linux Node Group members correctly joins the cluster, but the Windows Node Group members do not join the cluster. This occurs only when internet access is removed from the private subnets the Node Groups are deployed to.

The message is a time out (after 25 minutes) stating no members joined the Windows Node Group.

`
Error: timed out (after 25m0s) waiting for at least 2 nodes to join the cluster and become ready in "disccluster-windows-ng"
`
**What you expected to happen?**
I expected the Windows Node Group members to join the cluster without internet access enabled.

**How to reproduce it?**
Include the steps to reproduce the bug.
If using a config, include it here, removing any sensitive information!

Attached the configuration file to create the cluster (replace the VPC, Subnet, Role, and SG info)
[disccluster-config-clean.txt](https://github.com/weaveworks/eksctl/files/5391936/disccluster-config-clean.txt)

To create the cluster initially, I added the default route (0.0.0.0/0) to each subnet and created the cluster and everything worked as expected. I also validated internet access worked correctly.

```
$eksctl create cluster -f disccluster-config-clean.txt --install-vpc-controllers  -v 4
$kubectl get nodes
NAME                           STATUS   ROLES    AGE   VERSION
ip-172-22-1-152.ec2.internal   Ready    <none>   57m   v1.17.11-eks-cfdc40
ip-172-22-1-92.ec2.internal    Ready    <none>   53m   v1.17.9-eks-4c6976
ip-172-22-2-117.ec2.internal   Ready    <none>   53m   v1.17.9-eks-4c6976
ip-172-22-2-178.ec2.internal   Ready    <none>   57m   v1.17.11-eks-cfdc40
```

I then deleted the cluster (eksctl delete cluster --name disccluster --region us-east-1). After everything was cleaned up, I removed just the default route. I validated no internet access. I then tried to create the cluster again (see logs attached below):

```
$eksctl create cluster -f disccluster-config-clean.txt --install-vpc-controllers  -v 4
$kubectl get nodes
NAME                           STATUS   ROLES    AGE   VERSION
ip-172-22-1-211.ec2.internal   Ready    <none>   25m   v1.17.11-eks-cfdc40
ip-172-22-2-122.ec2.internal   Ready    <none>   25m   v1.17.11-eks-cfdc40
```

The two nodes that joined are the Linux nodes. The EC2 console shows all of the instances are up and running, but they are not joining the cluster.

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

I am using Amazon Linux 2 and downloaded eksctl as stated in the instructions for installation (curl piped to tar and then moved to /usr/local/bin).

My AWS credential are defined at the CLI (environment variables) and I have the AdministratorAccess managed policy associated with my account (and no additional restrictions or SCPs applied).

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.29.2
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Internet Create Process:**
This is the output of the cluster create process with internet enabled:
[internet-enabled-cluster-create.log](https://github.com/weaveworks/eksctl/files/5392046/internet-enabled-cluster-create.log)

**No-Internet Create Process**
This is the output of the cluster create process without internet enabled:
[internet_disabled.log](https://github.com/weaveworks/eksctl/files/5392066/internet_disabled.log)

**Comment by daduskacpokus** [comment]
hi @pnmcneil 
I faced the same issue and I haven't solution yet but think I found something interesting 
[This](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html) manul says that you should 

> Deploy the VPC resource controller to your cluster using the command that corresponds to the Region that your cluster is in.
> - All Regions other than China (Beijing) and China (Ningxia)
> `kubectl apply -f https://amazon-eks.s3.us-west-2.amazonaws.com/manifests/<region-code>/vpc-resource-controller/latest/vpc-resource-controller.yaml`

So, as you can see the `vpc-resource-controller.yaml` will downloaded from s3.**us-west-2** region, which, I supposed, has no preparred endpoint in your eksctl/cloudformation stack and even if it has s3 endpoint for us-east-2 you'll got the "error pull image" issue in your k8s scheduller cos you don't have this one for ecr.api in us-east-2

**Comment by kevin-lindsay-1** [comment]
Having this same issue, and everything works if right before the VPC controllers start being added; hard to say as to the exact cause, but until I figure out a way to get past this hurdle I need to assume this is the cause.

**Comment by cPu1** [comment]
We have identified the issue and are working on a fix.
