### ISSUE TITLE
private only cluster UpdateEndpoint deadline exceeded

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#2761]
0.30.0

[✖]  waiting for requested "EndpointAccessUpdate" in cluster "eks-use1-test" to succeed: RequestCanceled: waiter context canceled
caused by: context deadline exceeded

Created cluster with no nodegroup (just basic cluster creation)

**Comment by cdenneen** [comment]
Cluster creation at 1:44, EndPoint Update submission at 1:55 if that helps with extending the timeout properly.

**Comment by timharsch** [comment]
I experienced this problem yesterday.   It took an exceedingly long time to start the cluster.   After about 20 minutes I saw the error.   I tried again without making any changes in my process.  The second run was a bit slow too but succeeded.  I chalked it up to some problem on the AWS backend and haven't seen it yet today.

**Comment by cdenneen** [comment]
This did create successful and the private endpoint was properly updated but the eksctl command just timedout but in the background it worked (so this is more of a cosmetic thing)

**Comment by karlo** [comment]
I'm having the same problem
