### ISSUE TITLE
Using --cfn-disable-rollback

### ISSUE THREAD

**Issue by crismerritt** [weaveworks/eksctl#2765]
Hello, 

I get an error when creating a node group with **eksctl create nodegroup**. It fails with following message and rolls back: `Nodegroup failed to stabilize: [{Code: NodeCreationFailure,Message: Unhealthy nodes in the kubernetes cluster... `

I would like to disable the rollback so I can inspect the node instances. I see references to an option **--cfn-disable-rollback** in the merged PR https://github.com/weaveworks/eksctl/pull/2744 from @michaelbeaumont . 

However, the **--cfn-disable-rollback option** is not recognized with eksctl version 0.30.0 installed with Homebrew on my Mac (`Error: unknown flag: --cfn-disable-rollback`).

Could someone let me know how to use this option, or let me know another way to debug my "unhealthy" nodes?

See command output below.

Thanks,
Cris

```
cris@shroom aws % eksctl create nodegroup --config-file=scitara-eksctl-managed.yaml
[ℹ]  eksctl version 0.30.0
[ℹ]  using region us-east-1
[ℹ]  will use version 1.17 for new nodegroup(s) based on control plane version
[ℹ]  nodegroup "managed-ng-m5large" present in the given config, but missing in the cluster
[ℹ]  nodegroup "ng-t3small" present in the cluster, but missing from the given config
[ℹ]  1 existing nodegroup(s) (ng-t3small) will be excluded
[ℹ]  using EC2 key pair "scitara-dev-keypair"
[!]  retryable error (Throttling: Rate exceeded
	status code: 400, request id: 55547ef9-906c-49a4-bbc7-24a56ce92717) from cloudformation/DescribeStacks - will retry after delay of 735.924236ms
[ℹ]  1 nodegroup (managed-ng-m5large) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "scitara-eks"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "managed-ng-m5large" } } }
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack has all required resources
[ℹ]  building managed nodegroup stack "eksctl-scitara-eks-nodegroup-managed-ng-m5large"
[ℹ]  deploying stack "eksctl-scitara-eks-nodegroup-managed-ng-m5large"
[✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-scitara-eks-nodegroup-managed-ng-m5large"
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[!]  AWS::EKS::Nodegroup/ManagedNodeGroup: DELETE_IN_PROGRESS
[✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Nodegroup managed-ng-m5large failed to stabilize: [{Code: NodeCreationFailure,Message: Unhealthy nodes in the kubernetes cluster,ResourceIds: [i-084e350b47330a12a, i-06afbd5f67042baf0, i-0a4655236ea85b793, i-07011f24fbdfeb501, i-03930fdeefce0927c]}]"
[ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=us-east-1 --cluster=scitara-eks --name=<name>' for each of the failed nodegroup
[✖]  waiting for CloudFormation stack "eksctl-scitara-eks-nodegroup-managed-ng-m5large": ResourceNotReady: failed waiting for successful resource state
Error: failed to create nodegroups for cluster "scitara-eks"
cris@shroom aws % eksctl create nodegroup --config-file=scitara-eksctl-managed.yaml --cfn-disable-rollback
Error: unknown flag: --cfn-disable-rollback
```

**Comment by michaelbeaumont** [comment]
Hi @crismerritt that option hasn't been released yet. If you check [the merge commit](https://github.com/weaveworks/eksctl/commit/d4b46b2c84a6175cd54d3038d8074413bdadfddc) you can see which refs contain it, at the moment only `master`.

**Comment by crismerritt** [comment]
Thanks @michaelbeaumont for your reply. 

In the absence of the disable-rollback option, any other suggestions on how to figure out why eksctl considers the nodes "unhealthy"?

**Comment by swapniljani** [comment]
I am receiving the same error for [{Code: NodeCreationFailure,Message: Unhealthy nodes in the kubernetes cluster...

@crismerritt Where you able to resolve the issue ?

**Comment by michaelbeaumont** [comment]
Hi, are either of you using `privateCluster: true`? Please see also #2735.

**Comment by crismerritt** [comment]
Thanks @michaelbeaumont, I am not using `privateCluster: true`.

I got further by adding a managed nodegroup manually in the console, which produced the same error. Then I could ssh into the node and did `sudo systemctl status kubelet`, which showed the error below. 

At that point my client asked me to postpone the upgrade, and I have not yet pursued it further.

```
Oct 23 17:10:38 ip-192-168-58-39.ec2.internal kubelet[3831]: : [plugin aws-cni does not support config version ""]
Oct 23 17:10:38 ip-192-168-58-39.ec2.internal kubelet[3831]: W1023 17:10:38.289969    3831 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d
Oct 23 17:10:41 ip-192-168-58-39.ec2.internal kubelet[3831]: E1023 17:10:41.143163    3831 kubelet.go:2193] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

**Comment by michaelbeaumont** [comment]
@crismerritt Do you know which version you created the cluster with? There's a similar issue documented in #2740 (with a fix)

**Comment by michaelbeaumont** [comment]
I'm going to close this issue as the rollback feature is in an RC and I believe your issue may be covered by the above issue (for which a fix will be released today). Report back if that next release doesn't solve things!

**Comment by crismerritt** [comment]
Thanks Mike @michaelbeaumont
