### ISSUE TITLE
eksctl support for non-eksctl created resources

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#2773]
**Why do you want this feature?**
I want to be able to leverage the utilities of eksctl without having to create clusters using eksctl. E.g. I have a cluster I created before I knew about eksctl, I want to continue using the same clusters and get all the functionality eksctl provides.

**What feature/behavior/change do you want?**
When a cluster is created in the EKS console, eksctl should still be able to recognise it and act on the cluster. For example when I run `eksctl upgrade cluster` against a cluster manually created in the EKS console I get the following:

```bash
$ eksctl upgrade cluster --name jk-console
[ℹ]  eksctl version 0.29.2
[ℹ]  using region us-west-2
Error: getting VPC configuration for cluster "jk-console": no eksctl-managed CloudFormation stacks found for "jk-console"
```

**Comment by michaelbeaumont** [comment]
Sorry Jake didn't see we had https://github.com/weaveworks/eksctl/issues/2174
