### ISSUE TITLE
Make policy/permissions on eksctl webpage more granular/minimal

### ISSUE THREAD

**Issue by peix2** [weaveworks/eksctl#2777]
**Why do you want this feature?**
Would help others without working out step by step on IAM

**What feature/behavior/change do you want?**
On eksctl webpage here: https://eksctl.io/usage/minimum-iam-policies/
we can find "minimal" set of roles/permissions to run it and create EKS cluster by ordinary IAM user. I have found this is not sufficient and probably information could be corrected by what I provide below.

LaunchTemplate.json
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:RunInstances",
                "ec2:CreateLaunchTemplate",
                "ec2:CreateLaunchTemplateVersion",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeLaunchTemplateVersions",
                "ec2:DeleteLaunchTemplate",
                "ec2:DeleteLaunchTemplateVersions"
            ],
            "Resource": "*"
        }
    ]
}

```

**Comment by michaelbeaumont** [comment]
Isn't this covered by the `AmazonEC2FullAccess` policy in the docs?

```
            "Action": "ec2:*",
```

**Comment by peix2** [comment]
Well... you are right! In my set somehow I have AmazonVPCFullAccess instead. That's probably the reason I had to create/apply those additional ones. 
So it needs to be either 
1. AmazonEC2FullAccess
or
2. AmazonVPCFullAccess + set I shared.
You might want to test and decide if you want to "shrink" it to whichever is less.
