### ISSUE TITLE
Flag for adding scheduled actions to autoscaling groups.

### ISSUE THREAD

**Issue by JayG-EBSCO** [weaveworks/eksctl#2805]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
A clear and concise description of why you want this feature. Include use-cases and any specific constraints you may have.

As part of our cloudformation based deployments for lower environments such as testing, development, we have scheduled actions that scale the ASG's up, or down, based on a schedule for when we know the clusters will not be in use. This is done to assist with costs savings.

**What feature/behavior/change do you want?**
A clear and concise description of the change you would like to see in eksctl.

Adding a flag/config file parameter that can be set as part of the node group creation logic that would allow for specifying a scheduled action for items such as the case stated above would allow it to all be handled from within Eksctl.

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by dwickr** [comment]
Can this be re-opened? I'd like this feature too.

**Comment by laurie-kepford** [comment]
I would also like this feature.  Can this be reopened?

**Comment by JayG-EBSCO** [comment]
It's a shame this hasn't been taken forward. We instead of had to rely on boto3 calls outside of our cluster build/management to handle this.
