### ISSUE TITLE
eksctl fargate support for non-eksctl clusters

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#2808]
**Why do you want this feature?**
I want to be able to use the eksctl fargate functionality against my cluster that wasn't created by eksctl

**What feature/behavior/change do you want?**
I want to be able to use the `eksctl create/delete fargateprofile` functionality against a cluster that was not created using eksctl.

Related issue: https://github.com/weaveworks/eksctl/issues/2174#issuecomment-719605816

**Comment by Callisto13** [comment]
Verified that `eksctl delete fargateprofile` already works against a console-create cluster.
