### ISSUE TITLE
eksctl set/unset labels support for non-eksctl created cluster

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#2810]
**Why do you want this feature?**
I want to be able to use eksctl to set labels on clusters/nodegroups that were not created by eksctl

**What feature/behavior/change do you want?**
`eksctl set/unset label` support for non-eksctl created clusters/nodegroup

Related issue https://github.com/weaveworks/eksctl/issues/2174#issuecomment-719605816

**Comment by KrishnaSindhur** [comment]
Can I work on this?

**Comment by Callisto13** [comment]
is getting labels also a thing here?

**Comment by aclevername** [comment]
> is getting labels also a thing here?

I did not spot that! Yes please 😄

**Comment by aclevername** [comment]
@Callisto13 could you add integration test coverage for this as part of this work?

**Comment by Callisto13** [comment]
Hmm alright but it'll cost you.
