### ISSUE TITLE
kops VPC discussion/TODOs

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#282]
- [x] user docs
- [ ] discuss if we need to check `$KOPS_STATE_STORE`
- [ ] test connectivity (nodeport, ALB ingress, kops pod to EKS pod)
- [ ] connect SGs also, so we can send traffic between the clusters
- [ ] discuss if we should do something when less then 3 subnets are available
- [ ] add an issue to discuss cluster peering add-ons (e.g. via CoreDNS)

**Comment by errordeveloper** [comment]
>  connect SGs also, so we can send traffic between the clusters

At the moment a kops cluster should be able to connect to any of the nodeports inside the VPC, as all source addresses are allowed, but we probably should allow transparent node-to-node connectivity.
If people have more specific ideas, I'm very keen to hear those!

**Comment by errordeveloper** [comment]
>  discuss if we should do something when less then 3 subnets are available

Right now, the code fails like this:

https://github.com/weaveworks/eksctl/blob/875e50daa8ec8f3229e63e285c86dd06b554c3ec/pkg/kops/kops.go#L60-L72

I believe one needs to modify their configuration to add subnets and then run `kops apply`, I am not sure if it'd make sense to try automating this or use CloudFormation to create the missing subnets... what do people think? I'm inclined to leave the code as is until users complain.

**Comment by errordeveloper** [comment]
#290 is related.

**Comment by errordeveloper** [comment]
@StevenACoffman where you get to try using the feature, this is a good place for feedback! :)

**Comment by Adverbly** [comment]
Do we need to have created our original kops cluster with networking set to weave to be able to use the from-kops arg?

**Comment by errordeveloper** [comment]
Hi, George. No, it's irrelevant what network you chose, weave was just an
example. It would be great to see a blog post or tutorial showing how
peering clusters would be done, so if you get to implementing it, let us
know!

**Comment by errordeveloper** [comment]
I am not sure if this got any traction at the end, closing for now. If anyone has feedback about this feature, they can just open a new issue.
