### ISSUE TITLE
Getting Fargate profiles should show profile statuses

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#2845]
**Why do you want this feature?**
Sometimes Fargate actions take a looong time to complete, to help with confusion it may be useful to display what state they are in.

Deletion is the worst. After running a delete command it can take up to 5 minutes for the profile to actually disappear which (if you are lazy like me and cnba to read anything or go to the console to check) can lead to this frustrating sequence of events:

```sh
# delete my extraneous profile
$ eksctl delete fargateprofile --cluster foo --name bar 

# think I'll have a look at the other profiles I have left
$ eksctl get fargateprofile --cluster foo -o yaml
...
- name: bar  # hmmm still there?
  selectors:
  - namespace: default
  subnets:
  - subnet-lolz
...

# I have no chill so try to kill it again
$ eksctl delete fargateprofile --cluster foo --name bar 
Error: failed to delete Fargate profile "bar": InvalidRequestException: Fargate Profile is currently not in Active State.
...

# rude
```

**What feature/behavior/change do you want?**
A bit more info when getting profiles:
```sh
$ eksctl get fargateprofile --cluster foo -o yaml
...
- name: bar  # hmmm still there?
  status: deleting/inactive/whatever # ah that's okay
  selectors:
  - namespace: default
  subnets:
  - subnet-lolz
...
```

**Comment by hvydya** [comment]
I'd like to work on this. Can you assign it to me?

Also I've an another suggestion. Even when cluster deletion is initiated, the cluster shows up in the `get` command, just like the fargate profile. So, showing status there too makes sense. Let me know your thoughts on this.

**Comment by Callisto13** [comment]
It's all yours @hvydya 👍 .

The cluster status _is_ shown if you inspect the individual cluster (whereas that information is not shown anywhere for fargate profiles). I can see the use in putting the cluster status in the "concise" `get` command which show all clusters; it would be useful to see the status of all at a glance... but unless we are careful, could it gradually be decided that all sorts of info would be useful in that concise overview, with the result that it becomes a lot less concise over time?

I am probably being overly-cautious 😄  but I'll open up a separate issue where we can discuss that UX.

**Comment by hvydya** [comment]
Yeah I understand your point. That's ok.

I've a query. I've made the changes and wanted to test it so, I ran `make -f Makefile.docker test`. This failed saying 
```
HINT: to fix this, run 'git commit pkg/nodebootstrap/assets.go pkg/addons/default/assets.go pkg/addons/assets.go pkg/apis/eksctl.io/v1alpha5 userdocs/src/usage/schema.json pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go pkg/eks/mocks/CloudFormationAPI.go pkg/eks/mocks/CloudTrailAPI.go pkg/eks/mocks/EC2API.go pkg/eks/mocks/EKSAPI.go pkg/eks/mocks/ELBAPI.go pkg/eks/mocks/ELBV2API.go pkg/eks/mocks/IAMAPI.go pkg/eks/mocks/SSMAPI.go pkg/eks/mocks/STSAPI.go --message "Update generated files"'
```
After this, two files were changed(pkg/apis/eksctl.io/v1alpha5/assets/schema.json, pkg/apis/eksctl.io/v1alpha5/schema.go). They were auto-generated. The hint above says I should commit them. Should I commit and push them?

**Comment by Callisto13** [comment]
Aaahh yeh that is an annoying quirk of the `make test` command. Just committing will make that error stop, no need to push anything until you are ready

**Comment by hvydya** [comment]
Ok. Raised a PR.
