### ISSUE TITLE
eksctl upgrade command hangs

### ISSUE THREAD

**Issue by nsaud01** [weaveworks/eksctl#2848]
Running an upgrade on an eks cluster works but the command seems to hang long after the upgrade is complete. Is this expected behavior? It would be nice if the command gave some indication of completion.

```
eksctl upgrade cluster --name=acme-devops --approve
[ℹ]  eksctl version 0.30.0
[ℹ]  using region us-east-2
[ℹ]  will upgrade cluster "acme-devops" control plane from current version "1.14" to "1.15"
```

**Comment by Callisto13** [comment]
Thanks for reporting this @nsaud01, we will look into it. If you come up with a fix in the meantime, we are happy to accept PRs 😄

**Comment by aclevername** [comment]
Annoyingly `1.14` is now deprecated so we can't reproduce this issue. However I do think this points out an issue in `eksctl` that sometimes we don't provide any output while a command is running, so you don't know if its hanging or not. Printing some output to indicate 1. eksctl has not handled 2. what the state of the world (e.g. cluster status) would help a lot in scenarios like this. Something similar has been done as part of https://github.com/weaveworks/eksctl/pull/2969:

```
eksctl delete cluster --name jk-console --wait
[ℹ]  eksctl version 0.36.0-dev+f1677fc1.2021-01-04T10:15:12Z
[ℹ]  using region us-west-2
[ℹ]  deleting EKS cluster "jk-console"
[ℹ]  deleted 0 Fargate profile(s)
[✔]  kubeconfig has been updated
[ℹ]  cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
[✔]  all cluster resources were deleted
[ℹ]  all nodegroups for cluster "jk-console" successfully deleted
[!]  no IAM and OIDC resources were found for "jk-console"
[ℹ]  initiated deletion of cluster "jk-console"
[ℹ]  waiting for cluster "jk-console" to be deleted, current status: "DELETING"
[ℹ]  waiting for cluster "jk-console" to be deleted, current status: "DELETING"
[ℹ]  waiting for cluster "jk-console" to be deleted, current status: "DELETING"
[ℹ]  cluster "jk-console" successfully deleted
```

I'm going to implement a similar output to the `upgrade` command as part of https://github.com/weaveworks/eksctl/pull/2953

**Comment by aclevername** [comment]
@nsaud01 in terms of the cause of the hanging, do you have the cluster config file used to create the cluster?  If so can you share please 😄

**Comment by aclevername** [comment]
@nsaud01 are you still hitting this issue?

**Comment by nsaud01** [comment]
I'm not hitting the issue after upgrading to latest. Thanks!
