### ISSUE TITLE
"create cluster" command uses latest AMI instead of recommended for managed node groups

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/eksctl#2851]
**What happened?**

Related to #2850
AWS rolled back recommended AMI in https://github.com/awslabs/amazon-eks-ami/issues/563#issuecomment-729075128
"upgrade nodegroup" tries to use this AMI, but "create cluster" still uses bugged (latest AMI).

**How to reproduce it?**

1. Create cluster with managed nodegroup via "create cluster"
2. Upgrade managed node group via "upgrade nodegroup"

**Expected result**

Cluster must be created with 1.18.8-20201007 AMI instead of 1.18.9-20201112.
Subsequent node group upgrade must not detect AMI difference.

**Anything else we need to know?**

Managed mode group uses custom launch template, but doesn't redefine AMI.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.31.0
```

**Logs**

```
[ℹ]  AWS::CloudFormation::Stack/eksctl-clustername-managed-ng-1: UPDATE_ROLLBACK_IN_PROGRESS – "The following resource(s) failed to update: [ManagedNodeGroup]. "
[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Requested Nodegroup release version 1.18.8-20201007 is invalid. Allowed release version is 1.18.9-20201112 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 903a8e21-1592-4e1b-a829-29636f01779f; Proxy: null)"
```

**Comment by artem-nefedov** [comment]
I realised that I must use `auto-ssm` AMI type.

**Comment by artem-nefedov** [comment]
Actually, it's not possible to use `ami: auto-ssm` with launch template.
However, the issue eventually went away after AWS updated something on their side.
Still, the original problem could resurface in the future.

**Comment by michaelbeaumont** [comment]
Agreed, we need to make sure `upgrade nodegroup` and `create cluster`/`nodegroup` have the same behavior here

**Comment by Unichron** [comment]
So another problem is that the AWS API itself rejects any version that is not the latest. So I guess you cannot fix this on the client side.

**Comment by brentley** [comment]
I'm seeing this problem with 0.37 of eksctl also:

[ℹ]  AWS::EKS::Nodegroup/ManagedNodeGroup: UPDATE_FAILED – "Requested Nodegroup release version 1.18.9-20210125 is invalid. Allowed release version is 1.18.9-20210127 (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: fb75890f-462f-47c0-9874-1daffd0ef118; Proxy: null)"

https://gist.github.com/brentley/4cd71d2dadc81ffc29033fb724fac10c#file-cluster-nodegroup-upgrade-error-L19

**Comment by nikimanoledaki** [comment]
This issue has been open for a while, @brentley have you experienced this issue since then?
