### ISSUE TITLE
get cluster returns null instead of empty JSON array

### ISSUE THREAD

**Issue by mishra-swati** [weaveworks/eksctl#2864]
**What happened?**
`eksctl get cluster --output json` returns `null` instead of `[]` when there are no clusters created with eksctl in the AWS account.

**What you expected to happen?**
`eksctl get cluster --output json` should return `[]`, an empty JSON array, to represent no clusters were found.

**How to reproduce it?**
1. Set up `eksctl` with an AWS account that has no EKS clusters created with eksctl
1. Run `eksctl get cluster --output json`

**Anything else we need to know?**
Version `0.31.0` was exhibiting the correct, expected behavior.

**Versions**
Please paste in the output of these commands:
`eksctl version`: `0.32.0`
`kubectl version --short --client`: `Client Version: v1.18.2`

**Logs**
```
$ eksctl get cluster -v 4 --output json
2020-11-22T18:49:10-08:00 [▶]  role ARN for the current session is *********
null%
```

**Comment by hvydya** [comment]
Hello! I'd like to work on this. Can you assign it to me?

**Comment by hvydya** [comment]
Looked at this today. Have a possible fix. Do I need to write any tests for this?

**Comment by michaelbeaumont** [comment]
@hvydya Great! Feel free to open a PR and we'll see if there's any tests missing :slightly_smiling_face:
