### ISSUE TITLE
Cannot add `t4g.medium` node group. (But `t3a.medium` works fine).

### ISSUE THREAD

**Issue by StianOvrevage** [weaveworks/eksctl#2874]
**What happened?**
[✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed."

**What you expected to happen?**
New node group.

**How to reproduce it?**
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: v3
  region: eu-west-1

nodeGroups:
  - name: t3alargev18
    labels: 
      role: workers
    instanceType: t3a.large
    desiredCapacity: 1
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

  - name: t4gmediumv18
    labels: 
      role: workers
    instanceType: t4g.medium # t4g.medium supports 17 pods per node. Ref https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt
    desiredCapacity: 3
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
```

Creation of `t3alargev18` works fine. But creation of `t4gmediumv18` fails with the above error. The same non-informative error is shown in the CloudFormation console.

If I just change the instance type to `t3a.medium` it works. Reading docs and trying to create resources manually there is no indication that `t4g.medium` should not be available in `eu-west-1` in an EKS node group (ASG).

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.32.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Callisto13** [comment]
Hi @StianOvrevage, this looks to be fixed in the next release (https://github.com/weaveworks/eksctl/pull/2856), so I will close this issue. Please re-open if you are still having problems when the new release comes out 👍

**Comment by StianOvrevage** [comment]
Awesome, thanks for the quick reply!
