### ISSUE TITLE
OnDemandPercentageAboveBaseCapacity is not honored

### ISSUE THREAD

**Issue by StianOvrevage** [weaveworks/eksctl#2875]
**What happened?**
I want to create a 100% spot node group. I get a 100% on-demand node group instead.

**How to reproduce it?**
Using the following config:

```
  - name: t3amedspotv18c
    desiredCapacity: 3
    instancesDistribution:
      maxPrice: 0.017
      onDemandBaseCapacity: 1
      OnDemandPercentageAboveBaseCapacity: 20
      instanceTypes: ["t3a.medium"]
```

Still produces a 100/0% on-demand/spot ASG:

![image](https://user-images.githubusercontent.com/6630005/100291092-200be500-2f7d-11eb-8073-36b5f18544c2.png)

I see references in the code to 100% on-demand being the default: https://github.com/weaveworks/eksctl/blob/master/pkg/apis/eksctl.io/v1alpha5/types.go#L1011

But the rest of the code looks (on the surface) to be correct: https://github.com/weaveworks/eksctl/blob/master/pkg/cfn/builder/nodegroup.go#L374

Is there some naming or something that makes this actually not get applied where/like it should?

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.32.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by michaelbeaumont** [comment]
@StianOvrevage Could you post the CFN stack for your nodegroup? `eksctl utils describe-stacks`
