### ISSUE TITLE
missing --region from nodegroup docs page

### ISSUE THREAD

**Issue by todd-dsm** [weaveworks/eksctl#2883]
**What happened?**
Built a first cluster with eksctl and without issue; got what I believe to be expected results.

Asked eksctl to describe the nodegroup from the docs:

```bash
eksctl get nodegroup --cluster=cluster-1 --name=ng-14800d04
Error: getting nodegroup stack summaries: getting nodegroup stacks: no eksctl-managed CloudFormation stacks found for "cluster-1"
```

**What you expected to happen?**
The [managing-nodegroups] page needs to be updated so the first instruction reads:

`eksctl create nodegroup --cluster=<clusterName> --region=<region> [--name=<nodegroupName>]`

**How to reproduce it?**
omit `--region` argument from the command; should fail. cost me a half-hour of head-scratching; please fix for the next person.

The command won't return an expected result without `--region`.

**Versions**

```
$ eksctl version
0.32.0
```

[managing-nodegroups]:https://eksctl.io/usage/managing-nodegroups/

**Comment by todd-dsm** [comment]
Also applies to this page:
https://eksctl.io/usage/iam-identity-mappings/

Without `--region`:
```bash
$ eksctl get iamidentitymapping --cluster=apps-dev
Error: fetching cluster status to determine operability: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: apps-dev.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "07485935-27ab-4839-a881-5ee6664cdaf3"
  },
  Message_: "No cluster found for name: apps-dev."
}
```

With `--region`:
```bash
$ eksctl get iamidentitymapping --cluster=apps-dev --region=us-west-2
ARN												USERNAME				GROUPS
arn:aws:iam::378220085327:role/eksctl-apps-dev-nodegroup-apps-de-NodeInstanceRole-EJGK73RJR99G	system:node:{{EC2PrivateDNSName}}	system:bootstrappers,system:nodes
```

**Comment by Callisto13** [comment]
Thanks @todd-dsm , I think we could also do with some better error messages in general when resources are not found. https://github.com/weaveworks/eksctl/issues/2980

**Comment by Himangini** [comment]
We need to log what region was being used whenever we run this command [investigate and make sure we always log this for all eksctl commands]. 
We also need to document [if its not mentioned already] that the command will use settings from aws config file if you have any
