### ISSUE TITLE
kubeconfig writer should merge with existing files and respect KUBECONFIG

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#29]
https://github.com/weaveworks/eksctl/blob/0a39d1a2c1d107e1da90c27889d43bddba42ab3a/cmd/eksctl/create.go#L125

**Comment by richardcase** [comment]
@errordeveloper - i can look at this. If thats ok?

**Comment by richardcase** [comment]
Are you thinking something  along these lines:
- If --kubeconfig, --auto-kubeconfig or KUBECONF env var are NOT set then the default kube config location should be use (~/.kube/conf).
- If KUBECONF is set then we use this (assuming --kubeconfig and --auto-kubeconfig aren't specified)
- if KUBECONF is set BUT --kubeconfig or --auto-kubeconfig are specified then KUBECONF is ignored
- if a kubeconfig already exists then we merge in the cluster details with the existing file and create  the relevant cluster/context/user entries.

**Comment by richardcase** [comment]
It would also be worth re-visiting the **write-kubeconfig** and **auto-kubeconfig** flags. 

I wonder if auto-kubeconfig should be set to false as a default so that if no flags are supplied it picks up the standard kubeconf location.

**Comment by errordeveloper** [comment]
@richardcase I agree, we should make `--auto-kubeconfig=flase` the default, it's a bug that it's the opposite right now.

**Comment by errordeveloper** [comment]
@richardcase I've opened #63 to fix the default `--auto-kubeconfig`.

**Comment by errordeveloper** [comment]
> If --kubeconfig, --auto-kubeconfig or KUBECONF env var are NOT set then the default kube config location should be use (~/.kube/conf).

Yes, indeed. (nit: `~/.kube/config`).

> If KUBECONF is set then we use this (assuming --kubeconfig and --auto-kubeconfig aren't specified)

Yes.

> if KUBECONF is set BUT --kubeconfig or --auto-kubeconfig are specified then KUBECONF is ignored

Yes.

> if a kubeconfig already exists then we merge in the cluster details with the existing file and create the relevant cluster/context/user entries.

Yes, and I think the user should be able to control weather `current-context` gets be updated.

**Comment by richardcase** [comment]
I've got pretty much got all of the above working. 

Good idea with the `current-context`.  Do you think if there is no existing config to set the context authomatically but if there is an existing config then you need to specify something like `--set-context`?

**Comment by errordeveloper** [comment]
> I've got pretty much got all of the above working.

Ah, excellent! In that case, please open a PR and assign it to me, I should have time to review early next week.

>  Do you think if there is no existing config to set the context automatically but if there is an existing config then you need to specify something like `--set-context`?

Exactly, but I'm not sure what the default should be.
