### ISSUE TITLE
lower minimum subnets required to 2

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#290]
**Why do you want this feature?**

The EKS docs currently suggest that minimum number of [subnets/AZs required is 2](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html#API_CreateCluster_RequestSyntax). I believe our requirement of 3 subnets/AZs was based on what docs suggested at the time (can check in docs repo).

**What feature/behavior/change do you want?**

I think it may make sense to still default two 3 AZs in all but `us-east-1` AZs. Also kops VPC feature should be easier to use, as requirement would be lowered.

**Comment by jonk** [comment]
I can take a try at this, the requirement for 3 AZs is enforced by the functions at the bottom of https://github.com/weaveworks/eksctl/blob/43771c6a224f0b8942da3bff14e8379bec255832/pkg/eks/api/vpc.go ?

**Comment by errordeveloper** [comment]
Yes, but there maybe other places, but those would be a start.
