### ISSUE TITLE
eksctl create nodegroup fails bc. of missing role

### ISSUE THREAD

**Issue by mkraemer** [weaveworks/eksctl#2926]
**What happened?**

I'm running a cluster which contains a single nodegroup and would like to create a second nodegroup in this cluster. `eksctl create nodegroup` fails with reference to a missing role:

```
 ~ eksctl get nodegroup --cluster bi-ec2
CLUSTER	NODEGROUP	STATUS		CREATED			MIN SIZE	MAX SIZE	DESIRED CAPACITY	INSTANCE TYPE	  IMAGE ID
bi-ec2	ng-...     	UPDATE_COMPLETE	2020-09-24T09:16:57Z	2		3		3			m5.large	e3ad49b70ed809
```

```
~ eksctl create nodegroup --cluster bi-ec2 --name memory-optimized --managed
[ℹ]  eksctl version 0.31.0
[ℹ]  using region eu-central-1
[ℹ]  will use version 1.18 for new nodegroup(s) based on control plane version
[ℹ]  nodegroup "memory-optimized" present in the given config, but missing in the cluster
[ℹ]  nodegroup "ng-..." present in the cluster, but missing from the given config
[ℹ]  1 existing nodegroup(s) (ng-...) will be excluded
[!]  retryable error (Throttling: Rate exceeded
	status code: 400, request id: 4ee03e25-60a8-411f-8284-868f0f887d4d) from cloudformation/DescribeStacks - will retry after delay of 587.335429ms
[ℹ]  1 nodegroup (memory-optimized) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "bi-ec2"
Error: couldn't check aws-node for annotation: error listing attached policies: NoSuchEntity: The role with name eksctl-bi-ec2-addon-iamserviceaccount-kube-s-Role1-1N805VO9LVQKL cannot be found.
	status code: 404, request id: 6a354cad-7aa7-4f99-acfb-05be0565ac3c
```

I'm not sure where the referenced role is supposed to come from, i.e. if it should exist before calling eksctl. The role name seems hard to predict, so I assume eksctl is supposed to create it :sweat_smile:

**What you expected to happen?**

A new nodegroup should be created.

**How to reproduce it?**

`eksctl create nodegroup --cluster bi-ec2 --name memory-optimized --managed` reliably triggers this error for me.

**Anything else we need to know?**

The referenced role `eksctl-bi-ec2-addon-iamserviceaccount-kube-s-Role1-1N805VO9LVQKL` is indeed not created, i.e. I'm not seeing it in the IAM console either.

I tried running `eksctl create nodegroup` using the credentials of our aws root account and I'm seeing the same behaviour, so I assume this is not related to missing permissions in my personal account.

Thanks for the support :)

**Versions**
```
 ~ eksctl version
0.31.0
```

```
 ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Debug logs (created with `eksctl create nodegroup --cluster bi-ec2 --name memory-optimized --managed --verbose 4`) can be found here: https://gist.github.com/mkraemer/0a71f6d2a4c98dff150aa3a46a74ffe4

**Comment by aclevername** [comment]
Thanks for opening the issue @mkraemer, did you create the cluster using a config file? If so you can please share. If you didn't then do you recall what flags you provided during `eksctl create cluster`? In particular wondering if `--with-oidc` was provided.

When OIDC is enabled users can take advantage of giving [AWS permissions to service accounts](https://eksctl.io/usage/iamserviceaccounts/#how-it-works). By default when OIDC is enabled we create a service account and annotate  `aws-node` service account with the role, to [enable the VPC CNI plugin](https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html). When the user doesn't enable OIDC, the `aws-node` service account doesn't get annotated with the role and the role doesn't get created.

The error output makes it look as if the `aws-node` did get annotated with a role, implying OIDC is enabled and the role should exist, but as state the role doesn't exist.

**Comment by mkraemer** [comment]
Thx for looking into this @aclevername :)

The cluster was initialized by `eksctl create cluster --name bi-ec2 --version 1.17 --region eu-central-1`, so OIDC was not explicitely enabled.

However: I tried to configure IAM roles for service accounts at a later date. Among other things, by issuing `eksctl utils associate-iam-oidc-provider --region eu-central-1 --cluster bi-ec2 --approve`. My goal was to allow access to an S3 bucket via a service account, but I haven't got this to fully work yet. Do you think this could be related? EKS is new to me, maybe I left the cluster in a somewhat chaotic state.

Let me know in case I can get you any other information :)

Also: Very open to suggestions on how to recover from this without recreating the cluster :sweat_smile:

**Comment by aclevername** [comment]
> However: I tried to configure IAM roles for service accounts at a later date. Among other things, by issuing `eksctl utils associate-iam-oidc-provider --region eu-central-1 --cluster bi-ec2 --approve`. My goal was to allow access to an S3 bucket via a service account, but I haven't got this to fully work yet. Do you think this could be related? EKS is new to me, maybe I left the cluster in a somewhat chaotic state.

It could be related. Running `eksctl utils associate-iam-oidc-provide` enables OIDC, but doesn't invoke the actions I mentioned above about creating a role and annotating the `aws-node`. Did you at any point interact with the `aws-node`? One useful output would be to get the full spec of the `aws-node` service account, so we can see how the annotation got created. Could you please provide the output to `kubectl -n kube-system  get serviceaccount aws-node -o yaml`

For what it's worth I don't believe the set of commands you've run so far should leave the cluster in a chaotic state.

**Comment by mkraemer** [comment]
> Did you at any point interact with the `aws-node`? 

No, never :)

> Could you please provide the output to `kubectl -n kube-system get serviceaccount aws-node -o yaml`

Yeah, sure:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::...:role/eksctl-bi-ec2-addon-iamserviceaccount-kube-s-Role1-1N805VO9LVQKL
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"aws-node","namespace":"kube-system"}}
  creationTimestamp: "2020-09-24T09:13:58Z"
  name: aws-node
  namespace: kube-system
  resourceVersion: "33187"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/aws-node
  uid: 2946400c-9e3f-4369-8971-0eb158eff03c
secrets:
- name: aws-node-token-pwwgh
```

**Comment by aclevername** [comment]
thanks @mkraemer, this all looks fine. I was hoping we might see some managed fields output detailing what annotated the service account 😢   I'm not sure how we could get into this situation. Do you have the logs from when you create the cluster?

> Also: Very open to suggestions on how to recover from this without recreating the cluster 😅


A workaround would be to manually create the IAMServiceaccount for the `aws-node` (invoking the action we do during cluster creation when OIDC is enabled), you can do that by running `eksctl create iamserviceaccount --override-existing-serviceaccounts --name aws-node --namespace kube-system --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy --cluster <cluster-name> --approve`

**Comment by mkraemer** [comment]
Sorry for the delay and again thanks for your help @aclevername :)

> Do you have the logs from when you create the cluster?

Unfortunately not :(

> Also could you please provide the output from aws cloudformation list-stacks --region <region> | grep eksctl ?

```
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node/3c5847c0-2808-11eb-b7d1-0a3f741aced4",
"StackName": "eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node",
"TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-load-balancer-controller/3c481b20-2808-11eb-9e07-02d46d319da4",
"StackName": "eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-load-balancer-controller",
"TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-load-balancer-controller\" [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node/800259b0-2804-11eb-8ce6-0ad75412b350",
"StackName": "eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node",
"TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-load-balancer-controller/31d5a5f0-27f8-11eb-9944-0a0cf93fecd0",
"StackName": "eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-load-balancer-controller",
"TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-load-balancer-controller\" [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node/31b91d40-27f8-11eb-bce5-0ad1bb830c16",
"StackName": "eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node",
"TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-cluster/c7a5b160-1dd0-11eb-a417-06813faea71e",
"StackName": "eksctl-bi-fargate-cluster",
"TemplateDescription": "EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-addon-iamserviceaccount-default-datalake-writer/19ca48d0-ff08-11ea-940a-0676ff393846",
"StackName": "eksctl-bi-ec2-addon-iamserviceaccount-default-datalake-writer",
"TemplateDescription": "IAM role for serviceaccount \"default/datalake-writer\" [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-addon-iamserviceaccount-default-datalake-rw-access/4577e240-ff07-11ea-9817-029e6ff6f77a",
"StackName": "eksctl-bi-ec2-addon-iamserviceaccount-default-datalake-rw-access",
"TemplateDescription": "IAM role for serviceaccount \"default/datalake-rw-access\" [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node/952a26d0-fe5e-11ea-b513-0afcd97a0332",
"StackName": "eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node",
"TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-nodegroup-ng-4a670a8a/b2135a40-fe46-11ea-90b6-0200dd77d012",
"StackName": "eksctl-bi-ec2-nodegroup-ng-4a670a8a",
"TemplateDescription": "EKS nodes (AMI family: AmazonLinux2, SSH access: false, private networking: false) [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-cluster/d4b05aa0-fe44-11ea-91c2-0ad75412b350",
"StackName": "eksctl-bi-ec2-cluster",
"TemplateDescription": "EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by eksctl]",
"StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-cluster/98f0f720-fccf-11ea-8832-023cc2de05b4",
"StackName": "eksctl-bi-cluster",
"TemplateDescription": "EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by eksctl]",
```

> A workaround would be to manually create the IAMServiceaccount for the aws-node (invoking the action we do during cluster creation when OIDC is enabled), you can do that by running eksctl create iamserviceaccount --override-existing-serviceaccounts --name aws-node --namespace kube-system --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy --cluster <cluster-name> --approve

I tried the following:

```
~ eksctl create iamserviceaccount --override-existing-serviceaccounts --name aws-node --namespace kube-system --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy --cluster bi-ec2 --approve
[ℹ]  eksctl version 0.31.0
[ℹ]  using region eu-central-1
[ℹ]  3 existing iamserviceaccount(s) (default/datalake-rw-access,default/datalake-writer,kube-system/aws-node) will be excluded
[ℹ]  1 iamserviceaccount (kube-system/aws-node) was excluded (based on the include/exclude rules)
[!]  metadata of serviceaccounts that exist in Kubernetes will be updated, as --override-existing-serviceaccounts was set
[ℹ]  no tasks
```

It seems no action was performed, right? And indeed creating the nodegroup still fails:

```
~eksctl create nodegroup --cluster bi-ec2 --name memory-optimized --managed
[ℹ]  eksctl version 0.31.0
[ℹ]  using region eu-central-1
[ℹ]  will use version 1.18 for new nodegroup(s) based on control plane version
[ℹ]  nodegroup "memory-optimized" present in the given config, but missing in the cluster
[ℹ]  nodegroup "ng-4a670a8a" present in the cluster, but missing from the given config
[ℹ]  1 existing nodegroup(s) (ng-4a670a8a) will be excluded
[!]  retryable error (Throttling: Rate exceeded
	status code: 400, request id: 48324df5-5cdd-4d27-b89e-3529a9d85c8f) from cloudformation/DescribeStacks - will retry after delay of 791.046207ms
[ℹ]  1 nodegroup (memory-optimized) was included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "bi-ec2"
Error: couldn't check aws-node for annotation: error listing attached policies: NoSuchEntity: The role with name eksctl-bi-ec2-addon-iamserviceaccount-kube-s-Role1-1N805VO9LVQKL cannot be found.
	status code: 404, request id: 1facaefd-1664-44e0-a2a1-c0a014a6942a
```

**Comment by aclevername** [comment]
> Sorry for the delay and again thanks for your help @aclevername :)
> 
> > Do you have the logs from when you create the cluster?
> 
> Unfortunately not :(
> 
> > Also could you please provide the output from aws cloudformation list-stacks --region  | grep eksctl ?
> 
> ```
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node/3c5847c0-2808-11eb-b7d1-0a3f741aced4",
> "StackName": "eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node",
> "TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-load-balancer-controller/3c481b20-2808-11eb-9e07-02d46d319da4",
> "StackName": "eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-load-balancer-controller",
> "TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-load-balancer-controller\" [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node/800259b0-2804-11eb-8ce6-0ad75412b350",
> "StackName": "eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node",
> "TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-load-balancer-controller/31d5a5f0-27f8-11eb-9944-0a0cf93fecd0",
> "StackName": "eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-load-balancer-controller",
> "TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-load-balancer-controller\" [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node/31b91d40-27f8-11eb-bce5-0ad1bb830c16",
> "StackName": "eksctl-bi-fargate-addon-iamserviceaccount-kube-system-aws-node",
> "TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-fargate-cluster/c7a5b160-1dd0-11eb-a417-06813faea71e",
> "StackName": "eksctl-bi-fargate-cluster",
> "TemplateDescription": "EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-addon-iamserviceaccount-default-datalake-writer/19ca48d0-ff08-11ea-940a-0676ff393846",
> "StackName": "eksctl-bi-ec2-addon-iamserviceaccount-default-datalake-writer",
> "TemplateDescription": "IAM role for serviceaccount \"default/datalake-writer\" [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-addon-iamserviceaccount-default-datalake-rw-access/4577e240-ff07-11ea-9817-029e6ff6f77a",
> "StackName": "eksctl-bi-ec2-addon-iamserviceaccount-default-datalake-rw-access",
> "TemplateDescription": "IAM role for serviceaccount \"default/datalake-rw-access\" [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node/952a26d0-fe5e-11ea-b513-0afcd97a0332",
> "StackName": "eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node",
> "TemplateDescription": "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-nodegroup-ng-4a670a8a/b2135a40-fe46-11ea-90b6-0200dd77d012",
> "StackName": "eksctl-bi-ec2-nodegroup-ng-4a670a8a",
> "TemplateDescription": "EKS nodes (AMI family: AmazonLinux2, SSH access: false, private networking: false) [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-cluster/d4b05aa0-fe44-11ea-91c2-0ad75412b350",
> "StackName": "eksctl-bi-ec2-cluster",
> "TemplateDescription": "EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by eksctl]",
> "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-cluster/98f0f720-fccf-11ea-8832-023cc2de05b4",
> "StackName": "eksctl-bi-cluster",
> "TemplateDescription": "EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by eksctl]",
> ```
> 
> > A workaround would be to manually create the IAMServiceaccount for the aws-node (invoking the action we do during cluster creation when OIDC is enabled), you can do that by running eksctl create iamserviceaccount --override-existing-serviceaccounts --name aws-node --namespace kube-system --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy --cluster  --approve
> 
> I tried the following:
> 
> ```
> ~ eksctl create iamserviceaccount --override-existing-serviceaccounts --name aws-node --namespace kube-system --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy --cluster bi-ec2 --approve
> [ℹ]  eksctl version 0.31.0
> [ℹ]  using region eu-central-1
> [ℹ]  3 existing iamserviceaccount(s) (default/datalake-rw-access,default/datalake-writer,kube-system/aws-node) will be excluded
> [ℹ]  1 iamserviceaccount (kube-system/aws-node) was excluded (based on the include/exclude rules)
> [!]  metadata of serviceaccounts that exist in Kubernetes will be updated, as --override-existing-serviceaccounts was set
> [ℹ]  no tasks
> ```
> 
> It seems no action was performed, right? And indeed creating the nodegroup still fails:
> 
> ```
> ~eksctl create nodegroup --cluster bi-ec2 --name memory-optimized --managed
> [ℹ]  eksctl version 0.31.0
> [ℹ]  using region eu-central-1
> [ℹ]  will use version 1.18 for new nodegroup(s) based on control plane version
> [ℹ]  nodegroup "memory-optimized" present in the given config, but missing in the cluster
> [ℹ]  nodegroup "ng-4a670a8a" present in the cluster, but missing from the given config
> [ℹ]  1 existing nodegroup(s) (ng-4a670a8a) will be excluded
> [!]  retryable error (Throttling: Rate exceeded
> 	status code: 400, request id: 48324df5-5cdd-4d27-b89e-3529a9d85c8f) from cloudformation/DescribeStacks - will retry after delay of 791.046207ms
> [ℹ]  1 nodegroup (memory-optimized) was included (based on the include/exclude rules)
> [ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "bi-ec2"
> Error: couldn't check aws-node for annotation: error listing attached policies: NoSuchEntity: The role with name eksctl-bi-ec2-addon-iamserviceaccount-kube-s-Role1-1N805VO9LVQKL cannot be found.
> 	status code: 404, request id: 1facaefd-1664-44e0-a2a1-c0a014a6942a
> ```

thanks @mkraemer 

Thats a really interesting response. So the fix didn't work because a cloudformation stack exists called `eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node`. I had assumed this didn't exist because if it does exist the role should exist, then we wouldn't be in this situation 😁  

Can you please provide the output from the following:
`aws cloudformation describe-stacks --region <region> --stack-name eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node`.

**Comment by mkraemer** [comment]
> Can you please provide the output from the following:

Sure thing :)

```
~ aws cloudformation describe-stacks --region eu-central-1 --stack-name eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node

{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node/952a26d0-fe5e-11ea-b513-0afcd97a0332",
            "StackName": "eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node",
            "Description": "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
            "CreationTime": "2020-09-24T12:07:57.147000+00:00",
            "RollbackConfiguration": {},
            "StackStatus": "CREATE_COMPLETE",
            "DisableRollback": false,
            "NotificationARNs": [],
            "Capabilities": [
                "CAPABILITY_IAM"
            ],
            "Outputs": [
                {
                    "OutputKey": "Role1",
                    "OutputValue": "arn:aws:iam::...:role/eksctl-bi-ec2-addon-iamserviceaccount-kube-s-Role1-1N805VO9LVQKL"
                }
            ],
            "Tags": [
                {
                    "Key": "alpha.eksctl.io/cluster-name",
                    "Value": "bi-ec2"
                },
                {
                    "Key": "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
                    "Value": "bi-ec2"
                },
                {
                    "Key": "alpha.eksctl.io/iamserviceaccount-name",
                    "Value": "kube-system/aws-node"
                },
                {
                    "Key": "alpha.eksctl.io/eksctl-version",
                    "Value": "0.28.0"
                }
            ],
            "EnableTerminationProtection": false,
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        }
    ]
}
```

**Comment by aclevername** [comment]
> > Can you please provide the output from the following:
> 
> Sure thing :)
> 
> ```
> ~ aws cloudformation describe-stacks --region eu-central-1 --stack-name eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node
> 
> {
>     "Stacks": [
>         {
>             "StackId": "arn:aws:cloudformation:eu-central-1:...:stack/eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node/952a26d0-fe5e-11ea-b513-0afcd97a0332",
>             "StackName": "eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node",
>             "Description": "IAM role for serviceaccount \"kube-system/aws-node\" [created and managed by eksctl]",
>             "CreationTime": "2020-09-24T12:07:57.147000+00:00",
>             "RollbackConfiguration": {},
>             "StackStatus": "CREATE_COMPLETE",
>             "DisableRollback": false,
>             "NotificationARNs": [],
>             "Capabilities": [
>                 "CAPABILITY_IAM"
>             ],
>             "Outputs": [
>                 {
>                     "OutputKey": "Role1",
>                     "OutputValue": "arn:aws:iam::...:role/eksctl-bi-ec2-addon-iamserviceaccount-kube-s-Role1-1N805VO9LVQKL"
>                 }
>             ],
>             "Tags": [
>                 {
>                     "Key": "alpha.eksctl.io/cluster-name",
>                     "Value": "bi-ec2"
>                 },
>                 {
>                     "Key": "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
>                     "Value": "bi-ec2"
>                 },
>                 {
>                     "Key": "alpha.eksctl.io/iamserviceaccount-name",
>                     "Value": "kube-system/aws-node"
>                 },
>                 {
>                     "Key": "alpha.eksctl.io/eksctl-version",
>                     "Value": "0.28.0"
>                 }
>             ],
>             "EnableTerminationProtection": false,
>             "DriftInformation": {
>                 "StackDriftStatus": "NOT_CHECKED"
>             }
>         }
>     ]
> }
> ```

thanks @mkraemer . That looks to me as if the stack is healthy and the role exists. Are you sure you can't find `eksctl-bi-ec2-addon-iamserviceaccount-kube-s-Role1-1N805VO9LVQKL` in your list of roles?

If it doesn't exist then it looks like somehow the role got deleted, to rectify this I believe you should be good to delete the stack and then re-attempt this solution 

 
> A workaround would be to manually create the IAMServiceaccount for the `aws-node` (invoking the action we do during cluster creation when OIDC is enabled), you can do that by running `eksctl create iamserviceaccount --override-existing-serviceaccounts --name aws-node --namespace kube-system --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy --cluster <cluster-name> --approve`

**Comment by mkraemer** [comment]
> Are you sure you can't find eksctl-bi-ec2-addon-iamserviceaccount-kube-s-Role1-1N805VO9LVQKL in your list of roles?

It's definitely not listed in the IAM console. Should it be listed here? I'm seeing a similarly named role though: `eksctl-bi-ec2-addon-iamserviceaccount-defaul-Role1-SJMQHXEX5EE4`. Besides that, two other roles prefixed w/ `eksctl`: `eksctl-bi-ec2-cluster-ServiceRole-ACRHIG6ME2YL` and `eksctl-bi-ec2-nodegroup-ng-4a670a-NodeInstanceRole-7Y6OJ341MVIK*`.

*But:* I just noticed it's listed the cloudformation console, in the "Resources" tab of the "eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node" stack.

Clicking the "Physical ID" link of this role then takes me to the IAM console, but all I get there is "No Entity Found".
![image](https://user-images.githubusercontent.com/1070200/102627095-fabb6280-4147-11eb-8578-ddc38ab265b9.png)
![image](https://user-images.githubusercontent.com/1070200/102627116-fee78000-4147-11eb-86fa-3adf19abc745.png)

Does that support your thesis that it got somehow deleted? I'm about 95% sure I haven't done that :sweat_smile:

> to rectify this I believe you should be good to delete the stack and then re-attempt this solution

Deleting the cloudformation stack should be possible without deleting the referenced resources, i.e. the eks cluster - right? Will try that, but not on a friday evening :sweat_smile: 

Thanks again for your support here! :)

**Comment by aclevername** [comment]
> _But:_ I just noticed it's listed the cloudformation console, in the "Resources" tab of the "eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node" stack.
> 
> Clicking the "Physical ID" link of this role then takes me to the IAM console, but all I get there is "No Entity Found".

Definitely sounds like somehow this role was deleted, and thats the cause of the create nodegroup problem

> Deleting the cloudformation stack should be possible without deleting the referenced resources, i.e. the eks cluster - right? Will try that, but not on a friday evening 😅

The stack `eksctl-bi-ec2-addon-iamserviceaccount-kube-system-aws-node` is only responsible for creating this role, so if the role doesn't exist deleting this stack should have no effective on anything else 😄

**Comment by mkraemer** [comment]
Manually deleting the stack and recreating it via `eksctl create iamserviceaccount --override-existing-serviceaccounts --name aws-node --namespace kube-system --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy --cluster bi-ec2 --approve` indeed solved the issue. `eksctl create nodegroup` now works without issue.

Thank you very much for your help @aclevername :heart:
