### ISSUE TITLE
Update cluster tags

### ISSUE THREAD

**Issue by sergioteixeiraptc** [weaveworks/eksctl#2942]
possible to update cluster tags after creation?

**Comment by Callisto13** [comment]
Hey @sergioteixeiraptc! Currently there is no way to update tags via `eksctl`, but we would be happy to consider this as a feature request 😄

**Comment by Callisto13** [comment]
Thinking about this more, we are unlikely to introduce this feature in eksctl now, but it will be available when we go to 1.0.

Tags/labels can currently be updated simply by running the `eksctl unset labels` and `eksctl set labels` commands.

**Comment by michaelbeaumont** [comment]
Duplicate of #2774
