### ISSUE TITLE
How to attach additional existing security groups to EKS cluster?

### ISSUE THREAD

**Issue by CameronMcAuley** [weaveworks/eksctl#2961]
When creating an EKS cluster via CloudFormation, I can provide an existing security group which is then displayed in `Additional Security Groups` on the AWS Console as the security group used by the **control plane**:

``` EksCluster:
Type: AWS::EKS::Cluster
Properties:
  Name: !Ref 'MyClusterName'
  ResourcesVpcConfig:
    SecurityGroupIds:
      - !Ref AdditionalEksSG
    SubnetIds:
      - !Select [0, !Ref PrivateSubnets]
      - !Select [1, !Ref PrivateSubnets]
      - !Select [0, !Ref PublicSubnets]
      - !Select [1, !Ref PublicSubnets]
  RoleArn: !GetAtt EksClusterRole.Arn
  Version: 1.18
```

However, I can not see any documentation on how this is done with eksctl. The only 'security group' related argument that I can give is `nodegroup-security-groups`, which did not work when I passed it in the command using the following (bash script). Instead of using my existing security group, an additional security group was generated:

```
eksctl create cluster \
  --name=${clusterName} \
  --region=${targetRegion} \
  --version=1.18 \
  --vpc-private-subnets=${privateSubnets} \
  --vpc-public-subnets=${publicSubnets} \
  --node-security-groups=${myExistingSecurityGroupId}
```

What am I doing wrong here?

**Comment by aclevername** [comment]
Hey @CameronMcAuley 

I think we are lacking some docs on this, I do apologise and I will take an action to improve them. The `nodegroup-security-groups` attaches additional security groups to the nodegroup, so new security groups will still be created and used along side the ones provided. It also appears that this functionality is only supported for managed nodegroups, which is why you wouldn't of seen it being used as part of your cluster as by default `eksctl create cluster` creates unmanaged nodegroups

**Comment by michaelbeaumont** [comment]
@CameronMcAuley This option isn't supported by the command line but [you can use a config file](https://eksctl.io/usage/creating-and-managing-clusters/#using-config-files) and set the [`vpc.securityGroup`](https://eksctl.io/usage/schema/#vpc-securityGroup) option to your `AdditionalEksSG` security group. Only one security group for that EKS parameter is supported by `eksctl` right now.

**Comment by CameronMcAuley** [comment]
@michaelbeaumont Thanks michael. The reason I needed to do this with the CLI command was that I wanted flexibility of automating the creation of multiple clusters with different parameters which is not very easy in YAML.

For any future viewers -- the only way I got this to work was using `sed` replacements on a template YAML file.

For example: I have a template .yaml file which have **placeholders** as follows (including a custom securityGroup):

`apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: PLACEHOLDER_CLUSTER_NAME
  region: PLACEHOLDER_REGION
  version: "1.18"

vpc:
  securityGroup: PLACEHOLDER_SECURITY_GROUP`

What I needed to do in bash was:
1) Make a copy of this template
2) Replace these PLACEHOLDERs with my custom parameters. For example:

`
# Setting variables
clusterName="myClusterName"
clusterRegion="us-west-2"
clusterSecurityGroup="sg-1234567"

# Make a copy of the template to a new .yaml file
cp config-eks-template.yaml config-eks.yaml

# Use sed to replace placeholders. '.bak' enables cross platform between linux and OSX.
sed -i.bak "s/PLACEHOLDER_CLUSTER_NAME/${clusterName}/" config-eks.yaml
sed -i.bak "s/PLACEHOLDER_REGION/${clusterRegion}/" config-eks.yaml
sed -i.bak "s/PLACEHOLDER_SECURITY_GROUP/${clusterSecurityGroup}/" config-eks.yaml

# Execute eksctl with config file
eksctl create cluster \
  --config-file "config-eks.yaml"

# Cleanup
rm config-eks.yaml config-eks.yaml.bak 
`

Hope this helps!
