### ISSUE TITLE
Eksctl gitops v1 deprecation

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#2963]
### What is this?
The `eksctl` tool provides users a handy way to [set up gitops](https://eksctl.io/usage/gitops/) in their cluster with  the`eksctl enable repo` command.

[Flux v1](https://docs.fluxcd.io/en/1.21.0/) (the gitops mechanism deployed into clusters by `eksctl`) has been [in maintenance mode](https://github.com/fluxcd/flux/issues/3320) since October 2020, and the team have been working hard on [v2](https://toolkit.fluxcd.io/), which is very exciting 🎉  . So we want to get in on that 😄 .

This means that we have [integrated Flux v2](https://github.com/weaveworks/eksctl/pull/3662) alongside the now deprecated gitops configuration as provided by `eksctl` 😎  .

As such, we plan to remove `eksctl`'s v1 integration (`eksctl enable repo`). This will include the removal of Quickstart profiles (`eksctl enable profile`), which is a feature leveraging Flux v1 mechanisms.

`enable repo`, `generate profile` and `enable profile` are now deprecated. Please use `enable flux`.

### Timeline 🕐 
The timeline for removing the option to deploy Flux v1 within `eksctl` configuration is currently planned to line up with the EOL of Flux v1 (~6 months from 12.02.21). Any changes to the `eksctl` plan will be published here. [Flux v2 now has parity with v1](https://github.com/fluxcd/flux2/issues/894), which means we will remove `eksctl` support for Flux v1 as soon as Flux v2 reaches GA. A specific date [will be announced soon](https://fluxcd.io/docs/migration/timetable/).

### I have questions, who do I go to? ❓ 
For questions about this deprecation in `eksctl` and the v2 integration please comment on this issue or the [`eksctl` v2 feature issue](https://github.com/weaveworks/eksctl/issues/2964).

For all general questions concerning `eksctl` and Flux/gitops integrations, please open an issue in this repo.

Please do not go to the Flux maintainers/community with `eksctl`-related concerns.

### I have an issue with the current gitops integration (v1) 🤯 
We are still maintaining that codepath, but at a lower priority. Critical issues and bugs will still be prioritised, while embellishments will be declined. However, we strongly recommend that you start using Flux v2 (`enable flux`).

### I am super keen, how do I start using Flux v2 right now!? 💥 
You can manually (as in nothing to do with `eksctl`) set up Flux v2 in existing clusters by following [their documentation](https://fluxcd.io/). There are also some lovely [migration guides](https://toolkit.fluxcd.io/guides/flux-v1-migration/) ✨ .

Update: from `eksctl` version `0.53.0` you can [deploy Flux v2 to your cluster](https://eksctl.io/usage/gitops-v2/) as part of an `eksctl create cluster` command. Work is still experimental and ongoing here, but we welcome feedback 😄 .

**Comment by Callisto13** [comment]
_sigh_ just be cool, stale-bot

**Comment by Callisto13** [comment]
Note: when coming round to remove v1 stuff, simply `rg "FLUX V1 DEPRECATION NOTICE"`.

**Comment by Himangini** [comment]
We need to remove all the deprecated commands as part of this.
