### ISSUE TITLE
weaveworks/eksctl latest image tag is not up to date

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#2967]
`weaveworks/eksctl:latest` Docker image is a couple of years out of date.

We should ensure that when we create a new build we tag and push a new `latest` as well as the version.

**Comment by hvydya** [comment]
Hi! I'm not really sure how the release of this repo works, but I think this might do the trick.

In `Makefile.docker`:
```make
.PHONY: eksctl-image
eksctl-image: ## Build the eksctl image that has release artefacts and no build dependencies
	docker pull $(build_image_name)
	$(docker_build) \
	  --cache-from=$(build_image_name) \
	  --tag=$(eksctl_image_name) \
          --tag=$(eksctl_image):latest
	  --build-arg=BUILD_IMAGE=$(build_image_name) \
	  $(git_toplevel)

.PHONY: eksctl-image
push-eksctl-image: eksctl-image
	docker push $(eksctl_image_name)
	docker push $(eksctl_image):latest
```

But if someone builds an older version (maybe for hotfixing) then that gets tagged as `latest`. Let me know your thoughts on this 👍 .

**Comment by Callisto13** [comment]
Thanks @hvydya !
