### ISSUE TITLE
Could you please expose EksAllAccess and IamLimitedAccess policies as individually accessible source files

### ISSUE THREAD

**Issue by amcginlay** [weaveworks/eksctl#2971]
I would like this feature so we can curl the latest version of these documents, apply the <account_id> replacements and call `aws iam create-policy` action from a simple script.

Currently it would appear that these documents are only available as sub-portions of the markdown here:
https://raw.githubusercontent.com/weaveworks/eksctl/master/userdocs/src/usage/minimum-iam-policies.md

Thanks in advance
Al

**Comment by Callisto13** [comment]
Thanks for this request @amcginlay 👍 

We are happy to accept PRs if you would like to work on this 😄  otherwise the team will get to this after the holidays.

**Comment by orsenthil** [comment]
Hi @amcginlay , @Callisto13 - This PR https://github.com/weaveworks/eksctl/pull/4001 might help address this issue.

**Comment by Callisto13** [comment]
Closing this as investigation shows it is not feasible in a useful/clean way: https://github.com/weaveworks/eksctl/pull/4001#issuecomment-884977352
