### ISSUE TITLE
Better error messages when region not set

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#2980]
**Why do you want this feature?**
Currently when you run various commands and forget to set the `--region` flag, the error is quite unhelpful

Example command:
```sh
$ eksctl get iamidentitymapping --cluster=foo
Error: fetching cluster status to determine operability: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: foo.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "07485935-27ab-4839-a881-5ee6664cdaf3"
  },
  Message_: "No cluster found for name: foo."
}
```

**What feature/behavior/change do you want?**
It would be nice to wrap some of these errors with either:

a) a hint to try again with the region set
b) more elaborate error: `No cluster found for name: foo in region: <region>`

**Comment by pradeepnnv** [comment]
I would like to work on this issue.

**Comment by Callisto13** [comment]
Go for it @pradeepnnv  👍

**Comment by pradeepnnv** [comment]
@Callisto13 , the error message "No cluster found for name: foo." is from AWS EKS API.

So I submitted a PR to update the error message in DescribeControlPlace function to include the region.

Btw, region is defaulting to us-west-2 if not set. Please review and let me know if any changes are required.

**Comment by Callisto13** [comment]
Thanks @pradeepnnv 

> the error message "No cluster found for name: foo." is from AWS EKS API.

Makes sense.

> Btw, region is defaulting to us-west-2 if not set.

Indeed, hopefully we can help out people who do not know/forget this so they do not waste time debugging. 👍
