### ISSUE TITLE
Bash completion

### ISSUE THREAD

**Issue by braderhart** [weaveworks/eksctl#299]
**Why do you want this feature?**
Bash completion is standard with kubectl and other CLI tools within the Kubernetes ecosystem

**What feature/behavior/change do you want?**
Add a `eksctl completion` CLI option to generate a Bash completion file, or include the completion file in the repo.

It looks like this should be pretty easy to add:

- https://github.com/weaveworks/eksctl/blob/master/vendor/github.com/spf13/cobra/bash_completions.go

**Comment by errordeveloper** [comment]
I'd be happy to add this, but I do see that #298 is more important right now.

**Comment by braderhart** [comment]
@errordeveloper I don't have a lot of experience with this, but I'll see if I can find some time to figure it out.

**Comment by errordeveloper** [comment]
Closed via #327.
