### ISSUE TITLE
The timeout error appeared during EKS update from 1.17 to 1.18 on v 0.35.0

### ISSUE THREAD

**Issue by ArturChe** [weaveworks/eksctl#2997]
**What happened?**
The timeout error appeared during EKS update from 1.17 to 1.18

**What you expected to happen?**
The cluster and unmanaged node group updated without error.

**How to reproduce it?**
Run `eksctl upgrade cluster` command

**Anything else we need to know?**
The EKS cluster version has been updated, but the unmanaged node group does not.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.35.0
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```
$ eksctl upgrade cluster --name prod --approve --version=1.18 --region=us-east-1
[ℹ]  eksctl version 0.35.0
[ℹ]  using region us-east-1
[ℹ]  will upgrade cluster "prod" control plane from current version "1.17" to "1.18"
Error: waiting for requested "VersionUpdate" in cluster "prod" to succeed: RequestCanceled: waiter context canceled
caused by: context deadline exceeded
```

**Comment by Callisto13** [comment]
Thanks for reporting @ArturChe 👍 

Something very similar (likely the same thing) has been reported here https://github.com/weaveworks/eksctl/issues/2848 so I will close this as a dupe. Please reopen if you discover more information which indicates this is something different.
