### ISSUE TITLE
make dependency checker do something more useful

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#30]
We can either instruct the user how to install `kubectl` and `heptio-authenticator-aws`, or install it for them. However, with OS packages we could probably consider pulling these in that way...
If we decide to install, perhaps we should install them into `~/.eksctl/bin` or something like that.
https://github.com/weaveworks/eksctl/blob/0a39d1a2c1d107e1da90c27889d43bddba42ab3a/cmd/eksctl/create.go#L155-L157

**Comment by errordeveloper** [comment]
also checkout what `jx` does and possibly refactor:

https://github.com/jstrachan/jx/blob/07efc32c555d90122f295c8f707bfcc3bba7afca/pkg/jx/cmd/common_install.go#L147:25

**Comment by richardcase** [comment]
If you go down the route of printing instructions then minikube can be used for some inspiration. See [this](https://github.com/kubernetes/minikube/blob/69fc158ce86e8fd113cd42ae616c8009454fe212/cmd/util/util.go#L188).

**Comment by richardcase** [comment]
@errordeveloper - any preference on the 2 options:
1.  Give install instructions
2. Download & install  (to ~/.eksctl/bin)

**Comment by richardcase** [comment]
@errordeveloper - any preference on what you want here? Instructions or download?

I'm torn between the 2 but from a user perspective automatically downloading and installing would be easier. Perhaps we could support both?

**Comment by errordeveloper** [comment]
As we have Homebrew installer that takes care of all dependencies for macOS users, this would only affect Linux and Windows users. I'd rather put this on hold until we have a good idea of what OS most users are running, I will post an update once I have the stats.

**Comment by errordeveloper** [comment]
We will certainly need to vary kubectl version check based cluster version..

**Comment by michaelbeaumont** [comment]
Closing, I don't think including in the code any instructions on how to install various programs (which vary wildly) is worth the cost of keeping it all up to date. A version check for `kubectl` seems out of scope as well.

If anyone is missing this or had problems because of it, please let us know.
