### ISSUE TITLE
Add rebase github action

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#3000]
I really dislike the `Update branch` button on PRs. It leaves us with a really messy commit history.

Apparently this is a common complaint: https://github.com/isaacs/github/issues/88 and https://github.com/isaacs/github/issues/1113#issuecomment-403930749

Also the `Update branch` is not accessible to the person who owns the PR.. not that I really want anyone clicking it.

What do we think about adding https://github.com/cirrus-actions/rebase? We could configure it so that the core team + the PR owner can add a `/rebase` comment to a PR and boom: lovely commit history.

**Comment by Callisto13** [comment]
wdyt @weaveworks/eksctl-reviewers ?

**Comment by aclevername** [comment]
I don't have any strong preferences either way 😄

**Comment by michaelbeaumont** [comment]
I'm fine with it but I think we should be squash + merging PRs anyway so I don't think this should affect the history very much either way

**Comment by Callisto13** [comment]
🤔  alright let's talk about enforcing that as a policy. I am concerned that it will lead to large commits which make debugging/bisecting harder in the future.
