### ISSUE TITLE
Creation of managed nodegroups with a custom ami failed

### ISSUE THREAD

**Issue by dbluxo** [weaveworks/eksctl#3002]
Hi,

I wanted to set up an EKS cluster with managed nodegroups and a custom AMI. I have proceeded according to your [example](https://github.com/weaveworks/eksctl/blob/0.35.0/examples/15-managed-nodes.yaml). Thereby I discovered a bug in the documentation. The `bootstrap.sh` script expects the cluster name as parameter, not the nodegroup name:

```
usage: ./bootstrap.sh [options] <cluster-name>
Bootstraps an instance into an EKS cluster

-h,--help print this help
--use-max-pods Sets --max-pods for the kubelet when true. (default: true)
--b64-cluster-ca The base64 encoded cluster CA content. Only valid when used with --apiserver-endpoint. Bypasses calling "aws eks describe-cluster"
--apiserver-endpoint The EKS cluster API Server endpoint. Only valid when used with --b64-cluster-ca. Bypasses calling "aws eks describe-cluster"
--kubelet-extra-args Extra arguments to add to the kubelet. Useful for adding labels or taints.
--enable-docker-bridge Restores the docker default bridge network. (default: false)
--aws-api-retry-attempts Number of retry attempts for AWS API call (DescribeCluster) (default: 3)
--docker-config-json The contents of the /etc/docker/daemon.json file. Useful if you want a custom config differing from the default one in the AMI
--dns-cluster-ip Overrides the IP address to use for DNS queries within the cluster. Defaults to 10.100.0.10 or 172.20.0.10 based on the IP address of the primary interface
```

So in the [example](https://github.com/weaveworks/eksctl/blob/0.35.0/examples/15-managed-nodes.yaml#L44) `/etc/eks/bootstrap.sh custom-ami` should be changed to `/etc/eks/bootstrap.sh cluster-15`.

Otherwise, the nodes cannot join the cluster according to your example configuration.

**Comment by Callisto13** [comment]
Thanks for catching this @dbluxo 👍 

If you want to submit a fix we are happy to accept PRs 😄
