### ISSUE TITLE
Add taint without yaml

### ISSUE THREAD

**Issue by srfaytkn** [weaveworks/eksctl#3008]
Hello, how can I add `taints` when creating a nodegroup with `eksctl create nodegroup ...`?

**Comment by Callisto13** [comment]
Hi @srfaytkn, thanks for asking.

You can add `taints` in the nodegroup config. See schema [here](https://eksctl.io/usage/schema/#nodeGroups-taints) and example file [here](https://github.com/weaveworks/eksctl/blob/master/examples/05-advanced-nodegroups.yaml#L58).

**Comment by Callisto13** [comment]
Ah sorry just saw you specifically said in your title **without yaml** 🤦‍♀️  my bad!

Taints cannot currently be set on the command line, which was a deliberate decision by the maintainers at the time https://github.com/weaveworks/eksctl/pull/1887.

As we a moving to a "config first", and perhaps a "config only" strategy, we are trying not to add any new flags at this time.
