### ISSUE TITLE
Add option to add cluster ingress rules to custom security groups

### ISSUE THREAD

**Issue by jalaziz** [weaveworks/eksctl#3015]
**Why do you want this feature?**

eksctl already supports using existing security groups and IAM roles. This is great because we have a strict naming convention and this feature allows me to create the resources that cannot be changed after the cluster is created.

However, there are two security group ingress rules that eksctl normally creates that require the EKS cluster to be created first. These rules involve the cluster security group that is created by EKS. When specifying custom security groups, these ingress rules are not added automatically and must be added manually.

**What feature/behavior/change do you want?**

It would be great if eksctl could introduce a configuration option that would add the two ingress rules to an existing security group, if provided. 

The change seems to be simply moving the following block to work with a custom `sharedNodeSecurityGroup`: https://github.com/weaveworks/eksctl/blob/master/pkg/cfn/builder/vpc.go#L411-L431

I'd be happy to look into introducing the change if this is something that makes sense for the project.

**Comment by Callisto13** [comment]
Thanks @jalaziz, this improvement makes sense to me.

If you want to PR something, that would be great 😃 . If not (or you end up not having time) let me know and the core team will handle it in the near future.

**Comment by jalaziz** [comment]
Thanks @Callisto13!

I've started a draft PR at #3027. I still need to add tests and documentation, but hopefully the direction makes sense.
