### ISSUE TITLE
create cluster error

### ISSUE THREAD

**Issue by i757** [weaveworks/eksctl#3016]
I used the command "eksctl create cluster --name=lxz --region=us-west-2" to create cluster,
but the information printed is as follows：

```sh
[ℹ]  eksctl version 0.35.0
[ℹ]  using region us-west-2
Error: checking AWS STS access – cannot get role ARN for current session: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: 0d4e1790-655d-4a90-9033-afac4ff33c6e
```

**Comment by DanielAmmar** [comment]
Can you try to `aws sts get-caller-identity` & `aws sts assume-role --role-arn...`?

Are you using SSO? if yes, I had a similar issue with eksctl and I solved it using aws2-wrap
try installing `pip install aws2-wrap==1.1.4` and running the same command with `aws2-wrap`
