### ISSUE TITLE
eksctl info command

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#3029]
**Why do you want this feature?**
Currently we ask users to provide the output from `eksctl version` and `kubectl version` when opening a bug issue. I want users to be able to easily obtain all necessary information in one command.

**What feature/behavior/change do you want?**
A command `eksctl info` that provides the `eksctl version`, `kubectl version` and the OS type. This can be expanded to show more output that we deem useful. 

```bash
$ eksctl info
eksctl version: 0.35.0
kubectl version: 1.18.2
OS: MacOS
```

Thoughts @weaveworks/eksctl-reviewers ?

**Comment by hvydya** [comment]
Hi! I'd like to work on this.

**Comment by Callisto13** [comment]
Thanks @hvydya !

**Comment by aclevername** [comment]
Hey @hvydya, just wanted to check in to see if your still working on this :smile:
