### ISSUE TITLE
I should be able to create a new release by clicking one thing

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#3032]
Exactly what it sounds like.

Automate all the things.

**Comment by aclevername** [comment]
🔥

**Comment by michaelbeaumont** [comment]
Thoughts:

* Github Action + `on: workflow_dispatch`
* Push a tag `git tag {release_candidate,release} --force && git push tags --force`

Either one would handle finding the correct tag and pushing it, triggering the RC/release build

**Comment by Callisto13** [comment]
note: should also including running integration tests, iow completely turning our 11 step process into 1.

**Comment by michaelbeaumont** [comment]
Give us a break stalebot!

**Comment by Callisto13** [comment]
Stalebot has zero chill

**Comment by Callisto13** [comment]
Think we are done with this now
