### ISSUE TITLE
Create a new nodegroup with private network

### ISSUE THREAD

**Issue by chmodrs** [weaveworks/eksctl#3039]
Hi,

I have an existing eks cluster running in production, but when i created, i dont't think about the ebs size and now i need to migrate to new nodegroup with a smaller ebs volume size and gp3 volumes.

I created initial nodegroup with `--node-private-networking --ssh-access --ssh-public-key` flags, but now when i will create a new nodegroup, i receive the follow error: `Error: unknown flag: --node-private-networking --ssh-access`.

Anyone can help me with this problem?

Thanks!!

eksctl version: 0.34.0

Kubernetes Version: v1.18.8-eks-7c9bda

**Comment by Callisto13** [comment]
🤔  That's... odd.

Could you paste in the full command you are running, not just the flags?

**Comment by chmodrs** [comment]
Hi @Callisto13!

Follow the full command:

eksctl create nodegroup --cluster CLUSTER_NAME --node-type t3a.medium --node-ami auto --max-pods-per-node 100 --node-private-networking --ssh-access=true --ssh-public-key=eks-prod --node-volume-size 30gb --node-volume-type gp3

**Comment by cPu1** [comment]
@chmodrs there are two issues with the command:
1. The value for ` --node-volume-size` should be just `30` without the unit.
2. `gp3` volumes are not supported yet: https://github.com/weaveworks/eksctl/issues/2891

Also, it looks like you didn't paste the same command for which you got the `unknown flag` error.

**Comment by chmodrs** [comment]
@cPu1 

the same way, the error "Error: unknown flag: --node-private-networking --ssh-access" ocurred, even that remove --node-volume-size and --node-volume-type

**Comment by Callisto13** [comment]
@chmodrs could you confirm that other commands are working as expected? `eksctl get cluster --name CLUSTER_NAME` ?

**Comment by chmodrs** [comment]
@Callisto13 yes

$ eksctl get cluster --name cluster
NAME	VERSION	STATUS	CREATED			VPC			SUBNETS																	SECURITYGROUPS
cluster	1.18	ACTIVE	2020-11-13T21:19:44Z	vpc-06s83cef8cd998a50	subnet-09425718f761dd0f1,subnet-066a44fb2ea831b77,subnet-048f01ed392f7b710,subnet-08afe280c17e1e8c6,subnet-0c64a88f782297c9d,subnet-0dfcbaf88b87d6d1a	sg-02729f7a7833a894b

If i tried to create a new nodegroup without --node-private-networking and --ssh-access=true --ssh-public-key flags, works fine and nodegroup will be created, inclusind with gp3 volume type (i already tested that). Just with private networking flags doesn't work :(

**Comment by Callisto13** [comment]
Super weird. I can copy and paste that command (without the `--node-volume-x` flags ) and it doesn't complain on v0.34.0 for me 🤔 .

It does seem to a problem with the binary, which I honestly can't explain. You can either re-install a new copy of 0.34.0, or grab the latest release.

**Comment by Callisto13** [comment]
Actually @chmodrs are you putting quotes anywhere in your command? I can reproduce the error if i do:

```sh
eksctl create nodegroup \
  --cluster CLUSTER_NAME \
  --node-type t3a.medium \
  --node-ami auto \
  --max-pods-per-node 100 \
  "--node-private-networking --ssh-access=true" \
  --ssh-public-key=eks-prod \
  --node-volume-size 30
```

**Comment by chmodrs** [comment]
Hi.

I was trying to create in macos using 0.34 version, i change to another machine running Ubuntu Desktoo with ekctl running in 0.35.0 version and all works fine (including gp3 ebs), probably some problem in my machine or until in macos version.

Thanks everyone!

**Comment by Callisto13** [comment]
Glad it all worked out :)
