### ISSUE TITLE
eksctl get cluster timeout 

### ISSUE THREAD

**Issue by MAXI0008** [weaveworks/eksctl#3051]
I am trying to use eksctl to manage a fully private K8s cluster. 

I created a fully private cluster by following https://eksctl.io/usage/eks-private-cluster/ 

To manage the cluster, I created a bastion host inside a public subnet of the cluster VPC, by following the instruction from here: https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html#private-access (Amazon EC2 bastion host)

Inside the bastion host, I am trying to use eksctl, however, the `eksctl get cluster` command give me this error:

```
[!]  retryable error (RequestError: send request failed
caused by: Post "https://cloudformation.ap-southeast-1.amazonaws.com/": dial tcp 192.168.122.87:443: i/o timeout) from cloudformation/ListStacks - will retry after delay of 33.086873ms
[!]  retryable error (RequestError: send request failed
caused by: Post "https://cloudformation.ap-southeast-1.amazonaws.com/": dial tcp 192.168.184.109:443: i/o timeout) from cloudformation/ListStacks - will retry after delay of 110.548272ms
```

I suspect this issue may be with the network configuration, but I am not sure how to tackle this issue.

By the way, I suggest that the eksctl documentation on the fully-private cluster could be more complete. If there is a suggested solution for managing the fully-private cluster, or state clearer about what resources does the eksctl created, that would be better.

**Comment by michaelbeaumont** [comment]
@MAXI0008 Hi, can you please include more information about the configuration of the bastion host?
