### ISSUE TITLE
Add support for Flatcar Container Linux --node-ami-family

### ISSUE THREAD

**Issue by marga-kinvolk** [weaveworks/eksctl#3070]
**What feature/behavior/change do you want?**
I'd like `--node-ami-family` to support Flatcar as a valid family. Ideally, `FlatcarStable` and `FlatcarBeta`, but we could just go with the stable one.

**Why do you want this feature?**
Flatcar Container Linux is a container optimized OS. It's a drop-in replacement for CoreOS. Many previous users of CoreOS have switched to Flatcar and we know that a bunch of them are already using it or want to use it on EKS.

There was a PR back in December 2019 to add this support, but it was rejected on February 2020: https://github.com/weaveworks/eksctl/pull/1634

Since then, CoreOS has reached end of life, which caused the user base of Flatcar to increase significantly and we know of several users that are using it on EKS, plus more people that are asking us to help them get started with running it on EKS. Thus, I think it might be time to reconsider adding this support.

We're willing to do the necessary work to add the feature to eksctl, assuming you're willing to accept the feature.

Thanks!

---

**Community Note:**
- Please vote on this issue by adding a 👍 reaction to the original issue to help the maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

**Comment by Callisto13** [comment]
Thanks for requesting this feature @marga-kinvolk 😃  !

The team will discuss and get back to you 👍

**Comment by marga-kinvolk** [comment]
Claudia, I understand that there's a worry that there's "significant overhead" to maintaining this. Could you let us know what the overhead is, and whether there's a way that we could help alleviate it?

As I mentioned, we're willing to put in the work to make this happen :)

**Comment by Callisto13** [comment]
Hey @marga-kinvolk!

It's not so much a worry as a consideration of future effort around ensuring that the family's bootstrap script, userdata, service file continue to "work" with any version changes (or general upstream changes).

I am going to leave the voting to run a little longer, and if we do move forward we will be more than happy for you PR to this in 😉 .

**Comment by Callisto13** [comment]
@mikestef9 / @tabern could you summarise a response to this please?
