### ISSUE TITLE
[Security] Project change management

### ISSUE THREAD

**Issue by 0test0** [weaveworks/eksctl#3075]
Hello, 

Apologies if this is not the appropriate channel to contact you on this topic!
We are very interested in using this project, but due to the highly regulated industry we operate in, we need to ensure any project we use pass a security evaluation.

We've noticed the `master` branch and latest `release-0.35` do not have code reviews enforced, using required_pull_request_reviews, as specified in https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-branch-protection:
"required_pull_request_reviews	Required. Require at least one approving review on a pull request, before merging. Set to null to disable".
As a reference:
* https://api.github.com/repos/weaveworks/eksctl/branches/release-0.35
* https://api.github.com/repos/weaveworks/eksctl/branches/master

Could you please let us know if the above configuration is intentional and if so, do you have any controls in place for changes introduced in the project to be reviewed by a maintainer?
If not, do you have plans or would be in favour of enforcing code reviews to prevent malicious code or weaknesses to be introduced?

Thank you in advance!

**Comment by Callisto13** [comment]
Hi @0test0, thanks for asking this 👍 .

I checked out our branch protection rules, and we do required that PRs to `master` and `release-0.*` receive at least 1 Owner approval before merging. (We are currently discussing bumping that up to 2.) We could consider adding `Require review from Code Owners` to those protections.
