### ISSUE TITLE
eksctl scale nodegroup support for non-eksctl clusters

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#3079]
**What feature/behavior/change do you want?**
I want to be able to create nodegroups in clusters that were not created via eksctl

**Why do you want this feature?**
So that I can use eksctl to manage my nodegroup scaling

# Questions:
1. The scope of this depends on https://github.com/weaveworks/eksctl/issues/3077. It might be just scaling nodegroups diretly via eks api, or also with a combination of cloudformation

**Comment by Callisto13** [comment]
This was marked as done but not closed, is there anything left to do here?
