### ISSUE TITLE
Error: invalid Kubernetes version: strconv.ParseUint: parsing "": invalid syntax

### ISSUE THREAD

**Issue by cipriantarta** [weaveworks/eksctl#3092]
**What were you trying to accomplish?**

I'm trying to upgrade one of the managed node groups with the following command
`eksctl -p *** upgrade nodegroup -f eksctl/dev.yaml --cluster *** system`
(Note, stars for actual names due to privacy reasons)

**What happened?**

Nothing happens, but the error in the title is returned.

**How to reproduce it?**

Just running the above command reproduces it 100% of the time.
**Logs**

**Anything else we need to know?**

**Versions**

```
❯ eksctl version
0.36.0

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-15T11:35:50Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

My guess is that it has something to do with the minor version being `18+`?

**Comment by aclevername** [comment]
@cipriantarta thanks for reporting this. It appears to be a bug introduced as part of recent work on the upgrade command. Previously the `--kubernetes-version` flag  was optional, this accidentally became mandatory as part of https://github.com/weaveworks/eksctl/pull/2953. I'll ensure this gets fixed ASAP.

I think a workaround for now will be to provide the `--kubernetes-version` flag with your current nodegroup version as the value. Can you try that and see if that works for the meantime? Thanks

**Comment by cipriantarta** [comment]
@aclevername The workaround works. Thanks!

**Comment by aclevername** [comment]
Fixed in https://github.com/weaveworks/eksctl/releases/tag/0.36.1
