### ISSUE TITLE
Reduce length of CI runs

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#3095]
Our CircleCI `test-and-build` takes roughly 15mins to run. This means that each time a PR is merged, it takes atleast 15mins for the next PR to get merged as it needs to be rebased with master and then re-run through CI. Lets try and reduce how long `test-and-build` takes

**Comment by michaelbeaumont** [comment]
Down to just under 10 mins

**Comment by michaelbeaumont** [comment]
More improvements:
#3202 
#3112

**Comment by aclevername** [comment]
I think CircleCI is now becoming a factor, times used to be under 10 mins consistently since the changes above but recently its been between 12-20 minutes

https://github.com/weaveworks/eksctl/pull/3230/checks?check_run_id=1856204643
https://github.com/weaveworks/eksctl/pull/3222/checks?check_run_id=1854644447

**Comment by michaelbeaumont** [comment]
I think it's "Saving cache" step that can take over 6 minutes if something has changed in the dependencies
