### ISSUE TITLE
Manage additional ServiceAccount fields with iam.serviceAccounts

### ISSUE THREAD

**Issue by michaelbeaumont** [weaveworks/eksctl#3128]
This issue is meant to serve as a place for discussion around which arbitrary fields on `ServiceAccount` resources should be exposed in the `eksctl` config

Existing issues:

* [`automountServiceAccountToken`](https://github.com/weaveworks/eksctl/issues/2604)
* [`imagePullSecrets`](https://github.com/weaveworks/eksctl/issues/3108)

**Comment by aclevername** [comment]
A possible alternative solution is for eksctl to not be responsible for the creation/management of service accounts  #3042 #1698. This way the user can create and configure the service account using there normal method for handing k8s resources and can use the eksctl to either:
- Create & apply the annotation to the service account
- Create the role only, with a static name, and provide that to the user to add to the k8s resource themselves (suits the GitOps model)
