### ISSUE TITLE
Proactively track AMIs and supported regions

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#314]
We currently updates AMIs reactively (`make update-ami`), and same goes for region updates (but we don't even have a tool for that).

We could automate AMI updates via daily/weekly CI job, or even subscribe a Lambda to the SNS topic.
Checking supported regions would be a little different though, we could consider that AMIs become available in regions as EKS gets rolled out, but it maybe not the most reliable way to do it. One option that comes to mind is to try calling the API in each of the regions and use response code to decide if that region supports the API or not.

**Comment by martina-if** [comment]
closed in favor of #2650
