### ISSUE TITLE
managednodes - private network

### ISSUE THREAD

**Issue by sergioteixeiraptc** [weaveworks/eksctl#3147]
hello guys

having an issue creating private managed node groups
failed to run Kubelet: could not init cloud provider "aws": error finding instance Post https://ec2.eu-west-1.amazonaws.com/: dial tcp timeout on the node

only happens if i enable privateNetworking: true

**Comment by michaelbeaumont** [comment]
Hi, you'll need to include your entire config/CLI command.

**Comment by sergioteixeiraptc** [comment]
`apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ops
  region: eu-west-1
  version: "1.18"
privateCluster:
  enabled: true

iam:
  withOIDC: true

vpc:
  id: "vpc-0c9556dfe00b0a131"
  securityGroup: "sg-0c3f6006d5f88803f"
  sharedNodeSecurityGroup: "sg-0c3f6006d5f88803f"
  cidr: "10.70.0.0/16"
  subnets:
    private:
      eu-west-1a:
        id: "subnet-0209fa2ac9e625c5b"
        cidr: "10.70.12.0/22"

      eu-west-1b:
        id: "subnet-074e3522a4d857698"
        cidr: "10.70.16.0/22"

      eu-west-1c:
        id: "subnet-06440bc032626b5bd"
        cidr: "10.70.20.0/22"

managedNodeGroups:
  - name: managed-ng-private
    instanceType: m5.large
    # launch nodegroup in private subnets
    privateNetworking: true
    ssh:
      publicKeyName: sre
`

**Comment by michaelbeaumont** [comment]
@sergioteixeiraptc Do your subnets have a route to a NAT Gateway?

**Comment by sergioteixeiraptc** [comment]
yes
