### ISSUE TITLE
Support EC2 Auto Scaling Capacity Rebalancing

### ISSUE THREAD

**Issue by hans72118** [weaveworks/eksctl#3148]
Request to support EC2 auto scaling capacity rebalancing.

https://docs.aws.amazon.com/autoscaling/ec2/userguide/capacity-rebalance.html

AWS::AutoScaling::AutoScalingGroup
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html

**Comment by Callisto13** [comment]
Thanks for this request @hans72118 👍 

If you'd like to handle this, we are happy to accept PRs 😃

**Comment by aclevername** [comment]
Might be possible to add support for managed, needs further investigation
