### ISSUE TITLE
Missing albIngress IAM Permissions for targetGroup reconcile

### ISSUE THREAD

**Issue by acaire** [weaveworks/eksctl#3199]
Hi, we're using eksctl `0.36.1` - I'm not sure if it was intentional but #2914 (released in [0.35.0](https://github.com/weaveworks/eksctl/releases/tag/0.35.0)) removed some IAM permissions, pertinent to assigning targets to our targetgroups.

The two permissions we needed to fix the issue on our side were `ec2:DescribeInstanceStatus` and `tag:GetResources` apparent by these logs:
```
# ec2:DescribeInstanceStatus
E0203 01:28:16.699654       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile targetGroups due to failed to reconcile targetGroup targets due to Unable to DescribeInstanceStatus on i-12345678901234567: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: abcdefghi-jklm-nopq-rstu-vwxyzabcdefg"  "controller"="alb-ingress-controller" "request"={"Namespace":"helloworld","Name":"helloworld"}
```
and

```
# tag:GetResources
E0203 04:15:01.384907       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to GC targetGroups due to failed to get targetGroups due to AccessDeniedException: User: arn:aws:sts::123456789012:assumed-role/my-cool-role/i-123456789012345678 is not authorized to perform: tag:GetResources\n\tstatus code: 400, request id: abcdefghi-jklm-nopq-rstu-vwxyzabcdefg"  "controller"="alb-ingress-controller" "request"={"Namespace":"helloworld","Name":"helloworld"}
```

The full AWS IAM action reference differences between `0.34.0` and `0.35.0` are highlighted in this vimdiff for your convenience:

![image](https://user-images.githubusercontent.com/797119/106699725-5ff6e480-661e-11eb-955c-b6736c9882d4.png)

Or available in text form [in this gist](https://gist.github.com/acaire/e4965883571ace458b9a20fca0834d56)

**Comment by Callisto13** [comment]
Hi @acaire thanks for reporting this. The updated ALB (now AWS Load Balancer Controller)  policies which went into that change were copied straight from AWS's [new policy doc](https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/main/docs/install/iam_policy.json), and I can see that those permissions were removed there so I didn't accidentally miss some 😄 .

Can I just confirm that you are talking about the [AWS LBC TargetGroupBinding CR](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/targetgroupbinding/targetgroupbinding/)? Are you doing any non-standard magic with this? I ask because, since the policies were copied directly from the AWS one, I am surprised that TRB things don't "just work"/we haven't heard more people struggling with it.

**Comment by acaire** [comment]
Ah interesting! Quite possibly magic on our side then, appreciate the insight thanks @Callisto13! Let me investigate further and I'll circle back with my findings.

**Comment by acaire** [comment]
Thanks @Callisto13 - After investigating it's purely due to the fact we're still running aws-alb-ingress-controller v1, and the new IAM policy you referenced only works for v2 as per: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1302#issuecomment-717643215

Happy to close off this issue as we've mitigated it on our side, but more folks might be burnt by it (https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1647#issuecomment-742610750)  so just wanted to raise it.

**Comment by Callisto13** [comment]
Thanks for digging into this @acaire, and yes it is very useful to have this ticket here in case others are affected 🙏 . Out of interest, are you using our app-dev quickstart profile to deploy the LBC or doing it manually?

**Comment by acaire** [comment]
@Callisto13 ahh yes, we're managing it through other automation, so for all intents and purposes, manually 🙂

**Comment by Callisto13** [comment]
Okay cool 🙂 . The new ALB policies can be added via IRSA or on the node. The `albIngress` policy adds it to the node as an inline policy to be helpful when using the quickstart profiles, but if you are doing stuff with other automation you have the option of using IRSA instead ([eksctl docs for IRSA](https://eksctl.io/usage/iamserviceaccounts)).

I am gonna close this now, please reopen if eksctl is gives you more trouble with this 😄 .
