### ISSUE TITLE
Set appropriate name to ASG created by managed nodegroup

### ISSUE THREAD

**Issue by tommy-sho** [weaveworks/eksctl#3203]
**What feature/behavior/change do you want?**

Set meaning full Auto Scaling Group name to ASG created by managed nodegroup.

**Why do you want this feature?**

when I created ASG with self managed node group, eksctl adds same name of nodegroup to ASG. (like nodegroup-1-XXX)
But when I created ASG with self managed node group, eksctl adds non-meaning name to ASG. (like eks-XXXXXXX)

I expected to be added same name as nodegroup to ASG. Is there any plan to fix this? or is it reasonable behavior?
if someone knows how to set name to ASG, help me.

Thanks.

**Comment by michaelbeaumont** [comment]
@tommy-sho Unfortunately, `eksctl` has no control over this, the ASG is created internally by AWS.
