### ISSUE TITLE
How to configure ports 6783 and 6784 with NodeGroup SG?

### ISSUE THREAD

**Issue by darnone** [weaveworks/eksctl#3213]
. 

**What help do you need?**

**Comment by darnone** [comment]
I am sorry. It looks like my write up didn't take so I will try again.

I have a question around the step "edit instance security group to allow UDP, TCP on 6873, 6874 ports".  For AWS EKS, those rules go in the security group with the name of eksctl-<clustername>-cluster-ClusterSharedNodeSecurityGroup. See attached image:
![weavenet-ports](https://user-images.githubusercontent.com/6305538/106964174-b5f78500-670f-11eb-8c5e-e6239c1a28c4.png)

My question is what security group ID is the source security group ID. The instructions I have come across say "The source field should reference the security group ID of the node group".  My node group has 2 security group IDs - one is for remote ssh access and the other is the cluster security group ID eks-cluster-sg-<clustrname>-1234567891.  So if the SG if for  eks-cluster-sg-<clustrname>-1234567891 is say  sg-05bb03a93b47ad49a and the SG ID of   eksctl-<clustername>-cluster-ClusterSharedNodeSecurityGroup is say sg-00f68631e37b6ae43, which of these should be the source ID of the Weavenet ports?  (these are made up ids) Any info to clear this up is deeply appreciated.

What I am trying to accomplish is to configure the Weavenet CNI ports in my EKS cluster. My lab environment has everything open but that won't be the case in my company's official account.  So the help i am looking for is to explicitly identify with security group ID is the source. - David

**Comment by cPu1** [comment]
>What I am trying to accomplish is to configure the Weavenet CNI ports in my EKS cluster. My lab environment has everything open but that won't be the case in my company's official account. So the help i am looking for is to explicitly identify with security group ID is the source.

Hi @darnone , to enable all nodegroups to communicate with each other on Weave Net ports, the `ClusterSharedNodeSecurityGroup`'s must include the `ClusterSharedNodeSecurityGroup` as source for both rules. In your attached screenshot, the source should be the `eksctl--cluster-ClusterSharedNodeSecurityGroup` itself.  However, in the default setup, eksctl allows communication between nodegroups on all ports, so this step is not required when using a cluster provisioned via eksctl.

**Comment by darnone** [comment]
@cPu1, thanks for answering. That is what I was looking for. So the ports are necessary for worker node to worker node communication as opposed to cluster to nodegroup. That's why it points to itself and worker instances then have the same security group added.  Make sense. It might be worthwhile to add that info to the install and configure do page. "edit instance security group to allow UDP, TCP on 6873, 6874 ports" is a little vague.  Thanks! - David

**Comment by cPu1** [comment]
> So the ports are necessary for worker node to worker node communication as opposed to cluster to nodegroup. That's why it points to itself and worker instances then have the same security group added. Make sense.

That's correct. 

>It might be worthwhile to add that info to the install and configure do page. "edit instance security group to allow UDP, TCP on 6873, 6874 ports" is a little vague.

Agreed. I'll raise it with the Weave Net team. Thanks!

**Comment by darnone** [comment]
Just one more clarification. Is it for node to node communication or nodegroup to nodegroup communication or both. If I understand this correctly we can close this. Thanks for answering.

**Comment by cPu1** [comment]
The `ClusterSharedNodeSecurityGroup` is added to all nodegroups created via eksctl, so it essentially enables node to node communication, including across nodegroups because the backing nodes / EC2 instances have the same security group attached.

**Comment by cPu1** [comment]
Closing the issue, please feel free to open a new issue if you have any more questions.
