### ISSUE TITLE
Cluster created with eksctl, does not maintain FQDN for node hostname label.

### ISSUE THREAD

**Issue by yudaykiran** [weaveworks/eksctl#322]
**What happened?**
Using eksctl version 0.1.11 with Ubuntu images and I am seeing the following discrepancy.
- When I do a `kubectl get nodes`, it gives me the FQDN of the node (Ex: ip-192-168-32-21.us-west-2.compute.internal).
- When I do `kubectl get nodes --show-labels`, I am seeing that the label associated with the hostname is  ip-192-168-32-21, but not the complete FQDN.

**What you expected to happen?**
 FQDN could have been consistently maintained for the node's hostname label too.

**How to reproduce it?**
- Create cluster using eksctl 0.1.11 with node-family as Ubuntu
- Get the node name using `kubectl get nodes`
- Set it as a nodeSelector for your deployments.
- You pods are stuck in pending state as `kubectl get nodes` has FQDN whereas the actual `hostname` label for the node is trimmed down.

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
```
2018-11-26T08:42:25Z [ℹ]  versionInfo = map[string]string{"builtAt":"2018-11-09T16:23:05Z", "gitCommit":"191474b2b0a6e6856b5f9c652c38b5f2f01bf7c9", "gitTag":"0.1.11"}
```
$ uname -a
```
Linux ubuntu-xenial 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Also include your version of `heptio-authenticator-aws`

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by mumoshu** [comment]
Maybe this is an Ubuntu-specific issue? I'm seeing correct values being populated for my AL2-based nodes:

```console
$ k get no --show-labels
NAME                                           STATUS    ROLES     AGE       VERSION   LABELS
ip-192-168-23-135.us-west-2.compute.internal   Ready     <none>    3d        v1.11.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2c,kubernetes.io/hostname=ip-192-168-23-135.us-west-2.compute.internal
```

**Comment by errordeveloper** [comment]
Closing as Ubuntu support is lagging behind - still no 1.11 or 1.12 AMIs.
