### ISSUE TITLE
Launch Template of managed node group created by eksctl doesn't have specified instance type

### ISSUE THREAD

**Issue by imbohyun1** [weaveworks/eksctl#3220]
**What were you trying to accomplish?**

Creating managed node group with ClusterConfig(no launch template) via eksctl. 

**What happened?**

When creating the managed node group on AWS console without launch template setting, it creates launch template, managed node group and other related resources. If look at the launch template, it has instance type setting such as 't3.small' or 'c5.large', which I indicated one as instance type on console.

But when creating the managed node group via eksctl without launch template setting, eksctl creates launch template, managed node group and other related resources, just like AWS console does, but it didn't specify the instance type on launch template. It only has overrides instance type setting on ASG of managed node group.

Also checked the code of eksctl,
when defining LaunchTemplate in CloudFormation Stack, I could confirm that the instance type was not included (based on 'pkg/cfn/builder/managed_nodegroup.go' and 'pkg/cfn/builder/managed_launch_template.go').

I think it has to operate same way with AWS console.

**How to reproduce it?**

```
$ eksctl create nodegroup -f ./managed-ng-1.yml

# managed-ng-1.yml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: calico
  region: ap-northeast-2

managedNodeGroups:

  - name: managed-ng-1
    instanceType: c5.large
    desiredCapacity: 1
    volumeSize: 20
    volumeType: gp2
...
```

**Anything else we need to know?**

**Versions**

```
eksctl version 0.33.0

**Comment by cPu1** [comment]
Hi @imbohyun1, eksctl sets the instance types in the `CreateNodegroup` API call, and not in the eksctl-generated launch template. This is a design decision that allows setting multiple instance types for a nodegroup, and not a bug in eksctl. Hope that helps. Please feel free to open a new issue if you have any more questions.
