### ISSUE TITLE
Environment Variables in Eksctl

### ISSUE THREAD

**Issue by darnone** [weaveworks/eksctl#3235]
Is it possible to reference environment variables in eksctl?  I am writing a bash script to deploy a cluster and I am trying to figure out how to reference environment variables in eksctl.  Is this possible?  If so, a how-to or example would be useful.

- David

**Comment by darnone** [comment]
I am talking about in am eksctl configuration file.

- David

**Comment by michaelbeaumont** [comment]
Hi, I think the best option is just to call `envsubst` on your template before calling `eksctl`

**Comment by darnone** [comment]
Yes I saw your answer on Slack (I think that was you).  Exactly what I was looking for and works like a charm.3
