### ISSUE TITLE
Add docs for non-eksctl created clusters support

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#3249]
We've expanded eksctl to support interacting with clusters it didn't create, lets document this.

Related issue: https://github.com/weaveworks/eksctl/issues/2174

**Comment by jlbutler** [comment]
I can pick this up! Note we've made similar updates to the EKS User Guide already, and will keep these synced up moving forward.

**Comment by Callisto13** [comment]
@jlbutler we've added some things for the interim 👍

**Comment by jlbutler** [comment]
@Callisto13 thank you so much! I owe you one, or a few. Looks great!
