### ISSUE TITLE
Update Kubicorn Logger to kris-nova/logger

### ISSUE THREAD

**Issue by christopherhein** [weaveworks/eksctl#325]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
@kris-nova has broken the logger out to make it easier to consume, this will also allow us to turn off the timestamps making the logger feel more natural as a CLI logger

**What feature/behavior/change do you want?**
Update `kubicorn/logger` references to `kris-nova/logger`

**Comment by luxas** [comment]
:+1: to this. However, FYI now that we have https://github.com/kubernetes/klog, we hope to make it usable for reuse for the whole k8s community. Just mentioning in case you hadn't seen it.

**Comment by kris-nova** [comment]
Klog looks nice but I love the simplicity of this one as it doesn’t require a lot of dependencies. Also I feel like changing loggers should be a different issue - we already have this one and if we want to change can we start a separate thread for that? 

No bias here 😁

**Comment by luxas** [comment]
Oh yeah, I just happened to see this, and it was more as an FYI instead of action item, I don't feel strongly either way here :smile:
