### ISSUE TITLE
add IAM group support for iamidentitymapping

### ISSUE THREAD

**Issue by Morriz** [weaveworks/eksctl#3282]
**What feature/behavior/change do you want?**

IAM group support to not have to add individuals as admins to a cluster.

**Why do you want this feature?**

Less management, more automation.

**Comment by Callisto13** [comment]
Hi @Morriz, thank for making this request 👍 

To help us understand and prioritise this feature, could you provided a bit more information? For example:
- Describe the UX you would like to see
- Explain what workaround (if any) you currently have to make in absence of this feature
- Provide any links to APIs, Docs etc in AWS

Please check out our [issue guide](https://github.com/weaveworks/eksctl/blob/main/CONTRIBUTING.md#opening-issues) for more suggestions. 😃

**Comment by Morriz** [comment]
> * Describe the UX you would like to see

```
# $arn is a group arn like arn:aws:iam::01234567890:group/DevOps
eksctl create iamidentitymapping --cluster $CLUSTER_NAME --arn $arn --group system:masters --username admin --region $AWS_REGION
```
> * Explain what workaround (if any) you currently have to make in absence of this feature

Adding users by ID which is not a good approach.

**Comment by aclevername** [comment]
Closing. We are expecting an new [API from AWS to handle cluster permissions](https://github.com/aws/containers-roadmap/issues/185#issuecomment-706636321), so we could implement this feature but it would likely be replaced very soon by this new API. I think it makes sense to halt any new development on `iamidentitymappings` functionality
