### ISSUE TITLE
CloudFormation Service Role support

### ISSUE THREAD

**Issue by mumoshu** [weaveworks/eksctl#329]
Hey! Thanks for maintaining an awesome project.

I'm raising this issue according to my experience in an another project, and what I believe needed by certain users.

**Why do you want this feature?**

`eksctl` as of today requires an admin-like IAM priv to create a cluster/cfn stack.

This doesn't work in certain organizations with tighter security requirements.

An example would be that there is an IAM role for admins but it has source IP restriction to prevent malicious user w/ stolen AWS creds to do bad things.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": [
                        "MYIP",
                    ]
                }
            }
        },
```

**What feature/behavior/change do you want?**

Add a dedicated flag to tell cfn to use a [service role](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-servicerole.html), either `eksctl create cluster --cloudformation-service-role` or `--cfn-service-role`(which one do you prefer?).

As a sidenote, this is different from #122. #122 is for EKS, while this is for CFN, used by stack creation/update/deletion.

In kube-aws, the exact the same way did work as you can see in https://github.com/kubernetes-incubator/kube-aws/pull/1113/files#diff-6f90e92944e47c5a9899723462d5880bR149.

**Comment by errordeveloper** [comment]
So this is about using a role that is different from the one that user has in general?

I am not sure about adding this, if it's something that can be achieved via `~/.aws/config` file.

In my understanding it's possible to do the same like this:
```
[profile production-admin]
role_arn = arn:aws:iam::123456789012:role/ProductionAdminRole
source_profile = default
```
I may be wrong, I've not used a complex setup where this may be required.

**Comment by mumoshu** [comment]
@errordeveloper Hey!

> So this is about using a role that is different from the one that user has in general?

Yes.

> In my understanding it's possible to do the same like this:

No. A service role is basically used by an AWS service to switch to the role, even though human operations aren't allowed to do so.

Let's say you want to restrict important operations only to CloudFormation. For example, you'll firstly remove `iam:*` and/or `*:Delete*` permissions from the role used directly by human operators. Then, you'll create the `ProductionAdminRole` with all the permissions, while setting its trust policy(not an iam policy) to something like:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "cloudformation.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Using this `ProductionAdmin` role as a CloudFormation role allows you to restrict IAM related operations and all the Delete operations only via CloudFormation. This way, your operators are freed from mistakenly deleting resources or breaking IAM resources.

**Comment by mumoshu** [comment]
FWIW this is where you configure the trust policy in the console.

![image](https://user-images.githubusercontent.com/22009/49630093-fb38a300-fa2f-11e8-81e5-cc85c4ab3936.png)

**Comment by errordeveloper** [comment]
Thanks, this is much clearer now. I also can see that in #330 this is achieved by calling `SetRoleARN` call on `cloudformation.CreateStackInput`, which I overlooked first time around and assumed it was on the session object.
Once the stack was created, and it needs to be updated or deleted, will the role used during creation take effect or we need to make sure to set the correct role?

**Comment by mumoshu** [comment]
Ah, good point! You do need it while updating and destroying as well. I'll update my PR later.

**Comment by mumoshu** [comment]
Done. I'd appreciate it if you could review the PR once again.
