### ISSUE TITLE
About the featureGate "DynamicKubeletConfig" in userdoc "Customizing kubelet configuration"

### ISSUE THREAD

**Issue by hiraken-w** [weaveworks/eksctl#3291]
In the userdoc "Customizing kubelet configuration", as an example of featureGates, the DynamicKubeletConfig configuration is described.

[eksctl/customizing-the-kubelet.md at main · weaveworks/eksctl](https://github.com/weaveworks/eksctl/blob/a0f22d59960d4a7287aeb8ea59bb80e58e7d0325/userdocs/src/usage/customizing-the-kubelet.md)

```
        featureGates:
            DynamicKubeletConfig: true
            RotateKubeletServerCertificate: true # has to be enabled, otherwise it will be disabled
```

If we follow this example, the featuregates will be added to kubelet.yaml correctly.
However, in order to actually use DynamicKubeletConfig, the kubelet argument needs to be added.

[Reconfigure a Node's Kubelet in a Live Cluster | Kubernetes](https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/)

> For each node that you're reconfiguring, you must set the kubelet --dynamic-config-dir flag to a writable directory.

Some users may misunderstand that DynamicKubeletConfig can be used only by setting kubelet.yaml.
Therefore, I believe that it is better to change the DynamicKubeletConfig to another featureGate in the example.

(Actually, DynamicKubeletConfig has a default value of true in 1.11 and higher versions.)
[Feature Gates | Kubernetes](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)

Related issues are as follows.

[Setting DynamicKubeletConfig=true in the node group config doesn't appear to work · Issue #1838 · weaveworks/eksctl](https://github.com/weaveworks/eksctl/issues/1838)

**Comment by michaelbeaumont** [comment]
Closed by #3292
