### ISSUE TITLE
eksctl create cluster does not recognize field wellKnownPolicies

### ISSUE THREAD

**Issue by CxSamer-Habash** [weaveworks/eksctl#3293]
I am being testing the wellKnownPolicies from yesterday in my yaml file and did not succeeded to initiate to create a cluster , the error that I am facing is : 
The command that I ran is :  ~$ eksctl create cluster -f eks-create-template-multi-nodegroup.yaml --kubeconfig kubeconfig_name

Output Error:
"Error: loading config file "yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "wellKnownPolicies"

I have taken at last as an example the yaml file of the serviceaccount : https://github.com/weaveworks/eksctl/blob/main/examples/13-iamserviceaccounts.yaml

And just rerun it to be sure that I am not messing up, unfortunately it is giving me always that it does NOT recognize the field "wellKnownPolicies " .

I am using eksctl version downloaded binary  : 0.36.0
kubectl version : Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Shell: zsh
OS: ubuntu 20.04

Can you please advise?

**Comment by CxSamer-Habash** [comment]
I have upgraded eksctl version to the latest which is 0.38.0, and it worked like a charm.
I guess the previous version had a problem

**Comment by Callisto13** [comment]
Hi @CxSamer-Habash thanks for opening this issue.

The `wellKownIssues` option was new for version 0.38.0, so it should not work with 0.36.0. When using example files, it is a safer bet to go off the branch for the release you are on instead of main 😃 .
