### ISSUE TITLE
feat: Target Group ARNs for Node Groups

### ISSUE THREAD

**Issue by mumoshu** [weaveworks/eksctl#331]
**Why do you want this feature?**

I occasionally blue-green deploy Kubernetes clusters to make the blast radius/possible downtime of my services hosted on Kubernetes minimum.

It basically works by node groups from multiple Kubernetes clusters being associated to a shared target group that is associated to a ALB(=a single, multi-cluster ALB). The ALB services north-east traffic from users to the services on Kubernetes clusters.

I'm also a GitOps person. That is, I want to codify association of node groups to target groups.

More context can be seen from my tweets https://twitter.com/mumoshu/status/1068778865785360384

**What feature/behavior/change do you want?**

I'd suggest adding `eksctl create nodegroup --target-group-arns ARN1,ARN2,...` after #257

**Comment by whereisaaron** [comment]
Yes please! Just realised we don't have this!

I guess we can manually add target groups to the ASGs in the meantime. Feels icky though 😸

**Comment by whereisaaron** [comment]
Until we have support for ELBv2 Target Groups with `eksctl` I have been using a script to attach Target Groups to the ASG for each `eksctl` Node Group.

I've been using the below approach to identify the ASGs, which might be useful to others, or you might have a better approach. This way relies on assumptions about the tags that `eksctl` adds.

```bash
# Find the AutoScalingGroup name, based on eksctl naming pattern for cluster and nodegroup

EKSCTL_STACK_NAME="eksctl-${CLUSTER_NAME}-nodegroup-${NODEGROUP_NAME}"

ASG_NAME=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[?contains(Tags[?Key=='aws:cloudformation:stack-name'].Value, '${EKSCTL_STACK_NAME}')].[AutoScalingGroupName]" --output text)
```
