### ISSUE TITLE
Nodegroup deletion stucked

### ISSUE THREAD

**Issue by acastillo5690** [weaveworks/eksctl#3349]
I have created an EKS cluster and nodegroup using a cloudformation template that I have created, but in the creation process there was an error:
Nodegroup ng-eks-A failed to stabilize: [{Code: AccessDenied,Message: The aws-auth ConfigMap in your cluster is invalid }]

After that, I tried to delete the nodegroup but it was unsuccessful, I have applied a configmap to authorize my user and it applied correctly (apparently) but still I am not able to delete it. What can I do to delete the nodegroup and the cluster?
<img width="783" alt="evidence" src="https://user-images.githubusercontent.com/26907596/109000698-cf428000-7682-11eb-8605-49ef201003bd.PNG">

**Comment by aclevername** [comment]
> I have created an EKS cluster and nodegroup using a cloudformation template that I have created, but in the creation process there was an error:
> Nodegroup ng-eks-A failed to stabilize: [{Code: AccessDenied,Message: The aws-auth ConfigMap in your cluster is invalid }]
> 
> After that, I tried to delete the nodegroup but it was unsuccessful, I have applied a configmap to authorize my user and it applied correctly (apparently) but still I am not able to delete it. What can I do to delete the nodegroup and the cluster?
> <img alt="evidence" width="783" src="https://user-images.githubusercontent.com/26907596/109000698-cf428000-7682-11eb-8605-49ef201003bd.PNG">

Thanks for opening the issue, just to clarify did you create this with eksctl? If so please provide the cluster config, command run and log output please :smile:

**Comment by cPu1** [comment]
>I have created an EKS cluster and nodegroup using a cloudformation template that I have created, but in the creation process there was an error:

For clarification, did you use eksctl to create the cluster and nodegroup, or did you manually create the CloudFormation stack using your own template? Regardless of which method you used, did you manually modify the `aws-auth` ConfigMap?
