### ISSUE TITLE
upgrade nodegroup stuck due to pods not draining

### ISSUE THREAD

**Issue by DanArlowski** [weaveworks/eksctl#3397]
**What were you trying to accomplish?**
updating ManagedNodeGroup to a new K8s version
```bash
eksctl upgrade nodegroup --name=<group> --cluster=<name> --kubernetes-version=1.19
```

**What happened?**
One of the nodes did not update, and  the command timed out:
```
Error: error updating nodegroup stack: waiting for CloudFormation stack "StackName": RequestCanceled: waiter context canceled
caused by: context deadline exceeded
```

**How to reproduce it?**
The timeout happened because one of the pods denied eviction due to it doing so will violate its disruption budget, but that is not specific and might also happen by denying of afinity/antiafinity, etc

**Anything else we need to know?**

the command did not return that one of the pod is stucking the update rolling, and just timed-out with one of the pods not deploying, even the cloudformation stack was stating update in progress, which might've caused it to wait as i know it looks at the stack status to know where we're at.

I think it should jump as an error, instead of debugging manually, not sure how it can be achieved in the current way things are done.
I found the cause due to manually trying to drain the stuck node.

**Versions**

```
$ eksctl version
0.39.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aclevername** [comment]
@DanArlowski thanks for opening the issue. Can you provide the full log output?

The upgrade of a managed nodegroup is handled by EKS, so we can't really control how it handles a failed drain. It might be that we can attempt to drain the nodegroup first before triggering the upgrade, that might lead to a better UX.

> I think it should jump as an error, instead of debugging manually, not sure how it can be achieved in the current way things are done.

Sorry I don't quite follow, could you expand upon this? Thanks.

**Comment by DanArlowski** [comment]
> @DanArlowski thanks for opening the issue. Can you provide the full log output?

am sorry, but can-not as i did not save it, and run it without verbose.

I can tell you that by the looks of it eksctl did it work appropriately, and failed due to a node not evicting, and timed-out as the output does not pass to the stack.

> The upgrade of a managed nodegroup is handled by EKS, so we can't really control how it handles a failed drain. It might be that we can attempt to drain the nodegroup first before triggering the upgrade, that might lead to a better UX.

we cant do that actually, as i think the stack is for the full managed-node-group, so draining each one before its turn is impossible, we also cant drain them all due to obvious reasons (ex. what if we got only one managed node group for the whole cluster?)

I really am unfamilliar about passing data to/from CF, so i am unable to come up with a viable solution for the error, but i guess im not the only one encountered it and i couldn't find any issues on it


> Sorry I don't quite follow, could you expand upon this? Thanks.

what I meant is that i Had to manually debug and find the cause, as i got no output from the eksctl util.
