### ISSUE TITLE
Create handy tool to generate release and issue metrics

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#3420]
Right now Claudia runs some sketchy scripts whenever folks want details on how many releases we do per timeframe, how many issues we open/close per timeframe etc.

Let's write something in \<language of choice\> which is more robust and simple enough for anyone to run.

**Comment by Callisto13** [comment]
Nope. The tool is still me

**Comment by aclevername** [comment]
> Nope. The tool is still me

Confirmation you are in fact a tool.

**Comment by Himangini** [comment]
Closing this since this is no longer relevant.
