### ISSUE TITLE
eksctl create nodegroup fails with specified private subnets different from EKS private ENI's subnects

### ISSUE THREAD

**Issue by duttab49** [weaveworks/eksctl#3432]
In the following yaml -

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1234
  region: us-east-1
  version: "1.18"

vpc:
  id: vpc-123456789
  subnets:
   public:
      public-one:
          id: subnet-1
      public-two:
          id: subnet-2
      public-three:
          id: subnet-3
   private:
      private-one:
          id: subnet-4
      private-two:
          id: subnet-5
      private-three:
          id: subnet-6

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 50
    desiredCapacity: 2
    subnets:
      - subnet-7
      - subnet-8
      - subnet-9

NOTE - The subnets (subnet-7, subnet-8, subnet-9)  provided for managed node group is different from the private subnets specified for cluster VPC (subnet-4, subnet-5, subnet-6). 

We wanted to have smaller subnets for  EKS created ENI's based on the below link -
_**https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html**_

"**Make sure that the subnets that you specify during cluster creation have enough available IP addresses for the Amazon EKS created network interfaces. We recommend creating small (/29), dedicated subnets for Amazon EKS created network interfaces, and only specifying these subnets as part of cluster creation. Other resources, such as nodes and load balancers, should be launched in separate subnets from the subnets specified during cluster creation.**

Separate subnet for EKS managed ENIs and separate for worker node and  internal ALB  "

**What were you trying to accomplish?**

**What happened?**

The eksctl node group creation fails with below error message - 

[✖]  **VPC doesn't have subnet with name subnet-7**(allSubnets=v1alpha5.AZSubnetMapping{"us-east-1a":v1alpha5.AZSubnetSpec{ID:"subnet-4", AZ:"us-east-1a", CIDR:(*ipnet.IPNet)(0xc000a0b1a0)}, "us-east-1b":v1alpha5.AZSubnetSpec{ID:"subnet-5", AZ:"us-east-1b", CIDR:(*ipnet.IPNet)(0xc000a0b140)}, "us-east-1c":v1alpha5.AZSubnetSpec{ID:"subnet-6", AZ:"us-east-1c", CIDR:(*ipnet.IPNet)(0xc000a0b200)}} AZs=[]string(nil) subnets=[]string{"subnet-7", "subnet-8", "subnet-9"})
Error: failed to create nodegroups for cluster "cluster-123456789"

It does not recognize the worker node subnect-7 even with correct tagging -
Name - kubernetes.io/cluster/cluster-123456789 | value - shared

 privateNetworking: true is also set.
-- | --

**How to reproduce it?**

**Logs**

**Anything else we need to know?**

**Versions**

```
$ eksctl version 
0.40.0

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Nickolaitc** [comment]
I am actually seeing similar behavior.

`vpc:
  id: "vpc-#####"
  subnets:
    private:
      us-east-1a:
          id: "subnet-#####"
      us-east-1b:
          id: "subnet-#####"
    public:
      us-east-1d:
          id: "subnet-#####"
      us-east-1e:
          id: "subnet-#####"`
          
          
 The output I get:
 
 2021-03-12 12:10:02 [✖]  couldn't find private subnets: mapping doesn't have subnet with AZ us-east-1: (allSubnets=v1alpha5.AZSubnetMapping{"us-east-1a":v1alpha5.AZSubnetSpec{ID:"subnet-######", AZ:"us-east-1a", CIDR:(*ipnet.IPNet)(0xc00072aa20)}, "us-east-1b":v1alpha5.AZSubnetSpec{ID:"subnet-##########", AZ:"us-east-1b", CIDR:(*ipnet.IPNet)(0xc00072aa80)}, "us-east-1d":v1alpha5.AZSubnetSpec{ID:"subnet-#######", AZ:"us-east-1d", CIDR:(*ipnet.IPNet)(0xc00072ab40)}, "us-east-1e":v1alpha5.AZSubnetSpec{ID:"subnet-######", AZ:"us-east-1e", CIDR:(*ipnet.IPNet)(0xc00072aae0)}} AZs=[]string{"us-east-1"} subnets=[]string(nil))

**Comment by michaelbeaumont** [comment]
Likely the same request as https://github.com/weaveworks/eksctl/issues/3191#issuecomment-797450936 @patstrom

**Comment by patstrom** [comment]
Yeah it looks like the same. How do we wish to proceed? Move the discussion to this issue? Create a new one?

**Comment by duttab49** [comment]
Hi @patstrom , we have a use case, where we want to create a worker node and internal ALB in separate subnets that vpc subnects.
We expect this fix to be available in the coming eksctl version. 
Currently, we have eksctl version 0.40

**Comment by patstrom** [comment]
@michaelbeaumont How do you want to proceed with this? Do you think it is worth "solving" in the first place? I think (as mentioned in [my comment in the other issue)(https://github.com/weaveworks/eksctl/issues/3191#issuecomment-797463007) it would be worthwhile to separate the concepts of control plane subnet and node group subnets but I am unsure what exactly that would entail. Should I create a separate discussion issue about this? Or will I be wasting my time?

**Comment by duttab49** [comment]
@michaelbeaumont @patstrom I see the issue is closed without any resolution. Please check.
We need the solution in eksctl.

**Comment by meetshah15** [comment]
I'm running into the same problem. Is there any resolution to this issue?
`couldn't find public subnets: mapping doesn't have enough subnets: (allSubnets=v1alpha5.AZSubnetMapping{"us-east-1b":v1alpha5.AZSubnetSpec{ID:"####, AZ:"us-east-1b", CIDR:(*ipnet.IPNet)(0xc000d3c2d0)}, "us-east-1d":v1alpha5.AZSubnetSpec{ID:"####", AZ:"us-east-1d", CIDR:(*ipnet.IPNet)(0xc000d3c240)}} AZs=[]string{"us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d", "us-east-1e", "us-east-1f"} subnets=[]string(nil))`
