### ISSUE TITLE
Add taints to managed nodegroup

### ISSUE THREAD

**Issue by DekusDenial** [weaveworks/eksctl#3433]
**What feature/behavior/change do you want?**

I would like to apply taints to managed nodegroup the same way it does today for self-managed nodegroup. And I understand from the eksctl docs that this is not yet supported, but I would like to create an official request if not yet already.

**Why do you want this feature?**

I have self managed nodegroups today that are tainted to reserve for specific kind of workload along with managed nodegroup for  other workload on the cluster. I would like to unify the upgrade process for all nodegroups. Today we perform upgrade slightly differently for different kind of nodegroup, which we hope to further simplify.

**Comment by Callisto13** [comment]
Note: this work is blocked on upstream EKS APIs

**Comment by cPu1** [comment]
We'll begin work on this soon.
