### ISSUE TITLE
Use PermissionBoundaries with IAMServiceAccount command without config file

### ISSUE THREAD

**Issue by RamazanKara** [weaveworks/eksctl#3435]
**What feature/behavior/change do you want?**
I need permissionboundaries on the IAMServiceAccount Command or a similar substitute. I have a governed AWS Account which forces me to use roles only with permissionboundaries.

**Why do you want this feature?**
To create IAM Service Accounts on my governed AWS Account.

I know there is a feature in 0.39 that does this. But I can not find a documentation on how to use it with IAM Service Account command. Setting the flag with --permissionsboundary does not work.

**Comment by RamazanKara** [comment]
I have found out how to do it with a config file. So I changed the title to make it available as a parameter for the iamserviceaccount command.

**Comment by Callisto13** [comment]
Hi @RamazanKara thanks for opening this issue.

Eksctl deliberately does not have `1:1` mapping of `config:flag` options as a way to encourage people to use config instead of flags. Add this flag is therefore not something we want to do.
