### ISSUE TITLE
Support for Creating EKS Kubernetes v1.11 Clusters

### ISSUE THREAD

**Issue by buzzsurfr** [weaveworks/eksctl#344]
**Why do you want this feature?**
AWS launched [support for v1.11 in EKS](https://aws.amazon.com/blogs/compute/making-cluster-updates-easy-with-amazon-eks/) (along with cluster upgrades). We use eksctl for workshops and want to keep our workshop up-to-date with the latest EKS version.

**What feature/behavior/change do you want?**
- Change references from 1.10.3 (or 1.10.11) to 1.11.5.
- Update the image to use the v1.11.5 AMI.
- ~Add a new command to upgrade an existing eks cluster.~

**Comment by christopherhein** [comment]
Thanks @buzzsurfr I'm going to split this into two issues to make tracking easier. This one will be for adding support for `1.11`.
