### ISSUE TITLE
AWS Outpost support for eksctl

### ISSUE THREAD

**Issue by santosh07bec** [weaveworks/eksctl#3441]
AWS Supports creating EKS Worker nodes on AWS Outpost, however eksctl doesn't support that yet. I think it will be good to add this capability into eksctl.

**Comment by Callisto13** [comment]
Hey @santosh07bec thanks for this request, we will look into how eksctl can best support this. 👍

**Comment by FireballDWF** [comment]
@Callisto13 I'm the AWS ProServe Global lead for Outposts, with fulltime access to an Outpost that I can use for testing.  The changes which are needed is when creating a subnet, need to supply the OutpostArn attribute to the CreateSubnet API.  And when calling RunInstances, CreateVolumes, or LaunchTemplates APIs, need to specify gp2 ebs volumes types (or let it default, just don't specify gp3 (as it does now), which is not available on Outposts).  If have any questions, feel free to use  me as your Outpost expert.  And I'm willing to do testing for this feature.

**Comment by FireballDWF** [comment]
It would also be nice to support a command line parameter of the equivalent of the config file attribute nodeGroup:volumeType for people looking to automate without having to generate a config file.

**Comment by FireballDWF** [comment]
Alternatively for testing, if you want to do it yourself, I can help you get access to the Outpost Test Lab on a 1 scheduled week at a time basis.

**Comment by Callisto13** [comment]
Thanks @FireballDWF your help would be great 😀 .

We have a product meeting today and I will put this on the agenda.

> It would also be nice to support a command line parameter of the equivalent of the config file attribute nodeGroup:volumeType

This should already exist on `create cluster/nodegroup` commands as `--node-volume-type`.

**Comment by FireballDWF** [comment]
Ok, I see --node-volume-type now was actually in the --help output, my mind had just skipped over it.  Thank you.

I don't see a option to specify pre-existing subnets like a nodegroup equivalent of the create clusters --vpc-private-subnets so does that already exist?  Or is it on your roadmap/todo list, or should I submit an issue to request it?

**Comment by Callisto13** [comment]
As a config file is preferred, we deliberately don't expose a lot of configuration via flags. Check out the config [schema](https://eksctl.io/usage/schema/) and the [VPC docs](https://eksctl.io/usage/vpc-networking/#vpc-networking).

**Comment by santosh07bec** [comment]
I do not see any support for Outpost in eksctl yet. Can this issue be re-opened to add Outpost capabilities in eksctl?

**Comment by chainhead** [comment]
In the meantime, here is a [blog post](https://aws.amazon.com/blogs/containers/deploying-containerized-application-on-aws-outposts-with-amazon-eks/) that shows a bunch of `eksctl` commands to launch a worker node on Outposts.
