### ISSUE TITLE
Nodegroup creation failed

### ISSUE THREAD

**Issue by mohantangirala** [weaveworks/eksctl#3477]
Hello, 

My eksctl version is 0.41.0

Taken the sample config file from the https://eksctl.io/usage/creating-and-managing-clusters/.
With managed node groups and custom subnets (which have internet access)
when creating the cluster , it failed with 
```
error 2021-03-24 23:04:35 [✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Nodegroup jupiter-ng-1 failed to stabilize: [{Code: NodeCreationFailure,Message: Instances failed to join the kubernetes cluster,ResourceIds: [i-resid]}]"
```
When created the cluster with out node group, it created properly with out no issues, 
When trying to add a new node group again the same error appears,

**Comment by aclevername** [comment]
Thanks for opening the issue @mohantangirala. Can you provide the cluster config used and the full eksctl output? Thanks.

**Comment by Callisto13** [comment]
@aclevername when we get to the bottom of this can we remember to update the issue name with the cause? Should make search-ability and troubleshooting in the future easier.

**Comment by karlmutch** [comment]
I am seeing something very similar with 0.43.0.  I see the node groups being created and the CloudFormation console also shows then present.  However the EKS console does not display the node groups.  Also any nodes that area created are however visible in the EC2 console and kubectl of course sees them.

This is fine except it seems to trip up the Kubernetes 1.19 autoscaler which fails to create nodes successfully when new pods arrive.

I am going to test with eksctl 0.44.0 and will paste any info into this ticket I can after reproducing the issue.

**Comment by karlmutch** [comment]
I am seeing something very similar with 0.43.0. But in my case I see the node groups being created and the CloudFormation console also shows then present. However the EKS console does not display the node groups. Also any nodes that area created are however visible in the EC2 console and kubectl of course sees them.

This is fine except it seems to trip up the Kubernetes 1.19 autoscaler which fails to create nodes successfully when new pods arrive.

I am going to test with eksctl 0.44.0 and will paste any info into this ticket I can after reproducing the issue.

**Comment by Callisto13** [comment]
@karlmutch It seems like you are seeing something else, but I am not sure anything is wrong. Can you confirm whether you saw the same `failed to stabilize` error as the OP?

From what I can see from your output, the eksctl command succeeded and the nodes joined the cluster. Can you confirm that you have created _unmanagaed_ nodegroups? If so, these will not show up in the `aws eks list` output, nor on some areas of the console. Can you confirm that your cluster is working and that apps are deployable?

**Comment by karlmutch** [comment]
@Callisto13 I did eventually figure out how to see the group.  I was using GPU instances and AWS did not have capacity to fulfill the request and things were never completing as far as EKS was concerned and so were invisible.  I switch to Ohio and was able to start clusters successfully. Thanks for the message.
