### ISSUE TITLE
eksctl download instructions broken?

### ISSUE THREAD

**Issue by arun-gupta** [weaveworks/eksctl#35]
Following the download instructions from https://eksctl.io/, and got the following error:

```
~ $ curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

**Comment by errordeveloper** [comment]
The binaries weren't available, but they are now :)

**Comment by ChandraSM1990** [comment]
curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
Try this command, seems like the path has changed.
