### ISSUE TITLE
capacity-optimized-prioritized isn't supported by eksctl yet even though it's a valid option for EC2 Spot Instances

### ISSUE THREAD

**Issue by lloydchang** [weaveworks/eksctl#3516]
`capacity-optimized-prioritized` isn't supported by `eksctl` yet even though it's a valid option for EC2 Spot Instances according to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-fleet-configuration-strategies.html
> Alternatively, you can use the `capacity-optimized-prioritized` allocation strategy and then set the order of instance types to use from highest to lowest priority. You can set the same priority for different instance types. EC2 implements the instance type priorities on a best-effort basis, but optimizes for capacity first. This is a good option for workloads where the possibility of disruption must be minimized, but also the preference for certain instance types matters. Using priorities is supported only if your fleet uses a launch template. Note that when you set the priority for `capacity-optimized-prioritized`, the same priority is also applied to your On-Demand Instances if the `AllocationStrategy` is set to `prioritized`.

It appears that `eksctl` https://github.com/weaveworks/eksctl/pull/1883 and https://github.com/weaveworks/eksctl/pull/1883/files#diff-7b28fc939dfa83d6e1aae36e225442c39303a854ec900682e7c5515a7d29edecR182
are missing `capacity-optimized-prioritized`.

**Comment by cPu1** [comment]
Closed by https://github.com/weaveworks/eksctl/pull/3519
