### ISSUE TITLE
unknown flag: --version

### ISSUE THREAD

**Issue by jorgeluishdez** [weaveworks/eksctl#352]
**What happened?**
When I tried running eksctl specifying --version flag, the command return that the flag is unknown

**What you expected to happen?**
I expect the creation of the cluster using the specified EKS version on --version flag

**How to reproduce it?**
eksctl create cluster --version=1.11  --name=my-eks-cluster --ssh-public-key=region-ssh-key-used --region=us-west-2 --nodes=3  --node-type=t3.large --node-ami=ami-094fa4044a2a3cf52 --kubeconfig=./config-my-eks-cluster.yaml

**Anything else we need to know?**
Running on OSX High Sierra 10.13.6

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
versionInfo = map[string]string{"gitTag":"0.1.11", "builtAt":"2018-11-09T16:15:40Z", "gitCommit":"191474b2b0a6e6856b5f9c652c38b5f2f01bf7c9"}

$ uname -a
Darwin 8c85907cb454.ant.amazon.com 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64

$ kubectl version
Client Version: v1.11.5

**Comment by errordeveloper** [comment]
0.1.12 is out, please update the binary and try again.
