### ISSUE TITLE
instanceSelector should ignore unavailable instanceTypes

### ISSUE THREAD

**Issue by kr3cj** [weaveworks/eksctl#3531]
The new [instanceSelector](https://github.com/weaveworks/eksctl/pull/3498) feature looks awesome and has the potential to simplify our eks config yaml as well as make it more intuitive and increase supportability.

**What feature/behavior/change do you want?**
I was testing the new [`instanceSelector`](https://github.com/weaveworks/eksctl/issues/3461) feature available in [`eksctl 0.44.0-rc.0`](https://github.com/weaveworks/eksctl/releases/tag/0.44.0-rc.0) in EKS using Kubernetes version `1.19` on cluster in `us-east-1` using platform version `eks.2`. When requesting `instanceTypes` that support a certain vCPUs/memory/gpu filters, I expect it to only return `instanceTypes` that are available for all of the availability zones requested in my nodegroup. While this has worked in most cases, I found at least one that does not work.

Consider the below eksctl yaml snippet for a `managedNodeGroup` and running `eksctl create nodegroup...`:

```sh
managedNodeGroups:
  - name: my-node-group
    availabilityZones:
      - us-east-1a
      - us-east-1b
      - us-east-1d
    instanceSelector:
      vCPUs: 4
      memory: "16"
    spot: true
```

The nodegroup fails to spin up due to this CloudFormation error: `Your requested instance type (d3en.xlarge) is not supported in your requested Availability Zone (us-east-1a). Please retry your request by not specifying an Availability Zone or choosing us-east-1b, us-east-1c, us-east-1d`.

**Why do you want this feature?**
I want this feature so that I can have confidence that using instanceSelector will work reliably for my environment. I don't want to worry about new conditions that may prevent cluster-autoscaler from spinning up more nodes. This could result in CloudFormation or ASG errors that affect my cluster's ability to meet increased demand. Conditions such as [new `instanceTypes`](https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-amazon-ec2-d3-and-d3en-the-next-generation-of-dense-hdd-storage-instances/) being released for a region that are not yet released in all availability zones.

**Deliverable**
AWS Support suggested that I raise an issue directly on the [AWS Instance Selector github page](https://github.com/aws/amazon-ec2-instance-selector/issues) to request appropriate functionality since my understanding is that tool powers this feature for `eksctl`. ~I will do that (issue creation pending) but~ wanted to create an issue here for two reasons: raise awareness for any others running into the same issue and in case a fix for that tool requires refactoring on the `eksctl` side.

**Comment by cPu1** [comment]
Thanks for the great feedback! The `ec2-instance-selector` library, which eksctl delegates to, does support specifying a set of availability zones to check EC2 capacity offered in specific AZs. However, eksctl currently does not pass this information. We'll start working on it soon.

**Comment by elementalvoid** [comment]
👋 Would it be possible to expose the allow-list and/or deny-list feature of the library while changes are being made?

We've performed some profiling of different instance classes with our workloads and found that certain ones aren't something we want to adopt in production (`t3` specifically). They'd be _great_ for staging/dev environments but for production, we try to stick with other instance classes.

However, the current design of the instance selector usage doesn't allow for this level of choice and users will end up selecting _all_ instance classes.

```
      --allow-list string                 List of allowed instance types to select from w/ regex syntax (Example: m[3-5]\.*)
      --deny-list string                  List of instance types which should be excluded w/ regex syntax (Example: m[1-2]\.*)
```

Something like:
```yaml
managedNodeGroups:
  - name: my-node-group
    instanceSelector:
      vCPUs: 4
      memory: "16"
      allow: "[cm]5\.*"
```
Or
```yaml
managedNodeGroups:
  - name: my-node-group
    instanceSelector:
      vCPUs: 4
      memory: "16"
      deny: "t\.*"
```
