### ISSUE TITLE
(Future) Breaking: overrideBootstrapCommand soon to be required with Custom AMIs for AL2 and Ubuntu unmanaged nodegroups

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#3563]
# Note 1: Future change is described below, no action required from users yet
# Note 2: This is an announcement thread, not a "problem with `overrideBootstrapCommand`" thread. Please do NOT spam this thread with problems you are having. Please open a new issue with your specific failure.

## Do I need to read this issue/Will this change affect me?

![Inception Template (1)](https://user-images.githubusercontent.com/8898786/127893505-d16658d3-54f7-4aa7-93b8-6d83c1029172.jpg)

## TLDR:
From `eksctl` version `0.47.0` onwards all AL2 and Ubuntu **unmanaged** nodes will be bootstrapped using the AMI provided bootstrapping script.

For most people, this change should not be noticeable: you don't need to take any action. For those using custom AL2/Ubuntu AMIs, you will soon (BUT NOT YET) need to provide some extra configuration. To give users more time to move over to this new requirement, the legacy codepath will still be present and followed when providing a custom AMI. When enough time has passed (release date TBD), this legacy path will be removed. When that happens, it means that when using a Custom AMI, it will be required to set the `overrideBootstrapCommand` in order for the nodes to successfully join the cluster.

In all other cases, this change should not have any effect.

## What's happening?

We  recently merged [some work](https://github.com/weaveworks/eksctl/pull/3564) to remove the custom bootstrapping scripts which `eksctl` drops on **AmazonLinux2** and **Ubuntu** machines so that they can join the k8s cluster. From version `0.47.0`, all `eksctl` nodes will be bootstrapped using the `bootstrap.sh` script provided by standard (non-custom) EKS AMIs (mostly, there are still some odd "wrapper" scripts there to tidy things up).

A side effect of this improvement is that (in the near future) an `overrideBootstrapCommand` will be required when creating **un**managed nodegroups with **custom AL2/Ubuntu amis**. In previous `eksctl` versions this was not necessary, since `eksctl` would simply send everything it needed to the node, bootstrapping nodes with custom and non-custom AMIs alike. Now that `eksctl` delegates to the built-in `/etc/eks/bootstrap.sh` on standard public images, any node which does not have that file on disk will fail to join the cluster.

The solution will be to provide an `overrideBootstrapCommand` when setting a Custom AMI for **un**managed nodegroups. This is already standard practice when using Custom AMIs to create managed nodegroups via `eksctl`.

**For now all users who are providing custom AL2/Ubuntu AMIs do not need to do anything: a custom AMI would follow the legacy codepath. This issue will be updated once we have a date for the removal of the legacy path, at which point an `overrideBootstrapCommand` will be required.**

## Who will this affect?

The future removal of the legacy path around this change will only affect those using **custom** AL2 or Ubuntu AMIs to create **unmanaged** nodegroups.

The experience of creating:
- managed nodegroups
- unmanaged nodegroups based on other AMI Families
- **any nodegroup** with **standard** public AMIs
 
will not change.

## Why change things?

Maintaining our own set of bootstrapping code has become a tiresome burden, especially when the upstream AMIs add more things which we needed to consciously step over. Some recent clashes with the GPU AMIs made us want to sort this out fairly quickly. More context can be found [here](https://github.com/weaveworks/eksctl/issues/3464), [here](https://github.com/weaveworks/eksctl/issues/3446) and [here](https://github.com/weaveworks/eksctl/pull/3492).

## When will the legacy path be removed?

This is currently under discussion and this issue will be updated when a firm date/release number is set. Once a decision is made and a release announced, from then on any nodegroups created with custom AL2 or Ubuntu AMIs will need to have `overrideBootstrapCommand`s set. Again, this will only affect the use of **custom AL2/Ubuntu AMIs**. Nothing else will change or be noticeable.

## How can I avoid getting caught out by this change?

Documentation (including example configuration) will be written in advance of the legacy path going away. Until then, the [managed nodegroup examples](https://github.com/weaveworks/eksctl/blob/main/examples/15-managed-nodes.yaml#L38-L45) can serve as an accurate blueprint of the upcoming unmanaged nodegroup UX.

## I have questions...

Please ask away on this issue 😄 

--------------------------

## Community note

If you will be affected by this change (ie, if you routinely use Custom AL2/Ubuntu AMIs for self-managed nodegroups), please add a 👍  to this description so we can get an idea of numbers. Thanks 😄 .

**Comment by dbluxo** [comment]
Hi @Callisto13, should this already work? Today I created a new unmanaged nodegroup with custom AMI (based on Amazon EKS optimized Amazon Linux AMI with the ID: ami-07edd1ff4d841185c) with eksctl version 0.49.0 and unlike usual I added an `overrideBootstrapCommand` in my eksctl config:

```
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh <cluster-name>
```

1. In the logs of eksctl appears this message anyway?:

```
2021-05-17 14:05:07 [!]  Custom AMI detected for nodegroup core-eu-central-1a-green, using legacy nodebootstrap mechanism. Please refer to https://github.com/weaveworks/eksctl/issues/3563 for upcoming breaking changes
```

2. If I provide an `overrideBootstrapCommand` for the unmanaged nodegroups, then they cannot join the cluster. 

As of `/var/log/cloud-init-output.log`:

```
Cloud-init v. 19.3-43.amzn2 running 'modules:config' at Mon, 17 May 2021 12:08:52 +0000. Up 17.33 seconds.
Loaded plugins: priorities, update-motd, versionlock
No packages needed for security; 0 packages available
No packages marked for update
Cloud-init v. 19.3-43.amzn2 running 'modules:final' at Mon, 17 May 2021 12:09:03 +0000. Up 27.78 seconds.
Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /etc/systemd/system/kubelet.service.
Job for kubelet.service failed because a configured resource limit was exceeded. See "systemctl status kubelet.service" and "journalctl -xe" for details.
Exited with error on line 414
May 17 12:09:09 cloud-init[4423]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
May 17 12:09:10 cloud-init[4423]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
May 17 12:09:10 cloud-init[4423]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Cloud-init v. 19.3-43.amzn2 finished at Mon, 17 May 2021 12:09:10 +0000. Datasource DataSourceEc2.  Up 34.83 seconds
```

As of `systemctl status kubelet.service`:

```
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-eksctl.al2.conf, 10-kubelet-args.conf
   Active: activating (auto-restart) (Result: resources) since Mon 2021-05-17 12:12:29 UTC; 4s ago
     Docs: https://github.com/kubernetes/kubernetes

May 17 12:12:29 ip-00-000-000-000.eu-central-1.compute.internal systemd[1]: Failed to start Kubernetes Kubelet.
May 17 12:12:29 ip-00-000-000-000.eu-central-1.compute.internal systemd[1]: Unit kubelet.service entered failed state.
May 17 12:12:29 ip-00-000-000-000.eu-central-1.compute.internal systemd[1]: kubelet.service failed.
May 17 12:12:29 ip-00-000-000-000.eu-central-1.compute.internal systemd[1]: Starting Kubernetes Kubelet..
```

Without specifying `overrideBootstrapCommand` everything works as expected.

But probably I just misunderstood this issue here?

**Comment by MartinEmrich** [comment]
Hi! Just testing 0.51.0-rc0.... I get this message, but I have no custom AMI. (just `ami: auto` which AFAIK should use the newest appropriate AWS-provided AMI). Will this affect me?

**Comment by Callisto13** [comment]
Sorry for the slow response folks, I have been away for a while.

@dbluxo the legacy codepath will still be present for a while longer: ie, you don't _yet_ need to provide an `overrideBootstrapCommand` when using a custom AMI, currently just non-custom AMIs are on the new codepath. Looking back the wording is not clear, I will update the notice above. Sorry for the confusion 😅 .

@MartinEmrich I don't _think_ it will affect you, as you will be sent down the legacy codepath which does still work. We are doing a check to see whether a custom ami has been set, and if I had to guess it looks like we are doing that check a little too soon. I will look into it asap and find a better way. (I believe `auto` is selected by default, so you should be able to omit that line if you want.)

**Comment by steffakasid** [comment]
Hi,

I've added to my unmanaged nodegroup:
```
overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh <cluster-name>
```
As we're using a custom AMI (which is basically based on the offical EKS AMIs we just need to add a few things for compliance reasons). In fact the nodes were not able to join the cluster.

I receive the following error:
`Error: timed out (after 25m0s) waiting for at least 1 nodes to join the cluster and become ready in "bizhub-1a-green"`

After removing the overrideBootstrapCommand everything works again.

Regards
Steffen

**Comment by cPu1** [comment]
> Hi,
> 
> I've added to my unmanaged nodegroup:
> 
> ```
> overrideBootstrapCommand: |
>       #!/bin/bash
>       /etc/eks/bootstrap.sh <cluster-name>
> ```
> 
> As we're using a custom AMI (which is basically based on the offical EKS AMIs we just need to add a few things for compliance reasons). In fact the nodes were not able to join the cluster.
> 
> I receive the following error:
> `Error: timed out (after 25m0s) waiting for at least 1 nodes to join the cluster and become ready in "bizhub-1a-green"`
> 
> After removing the overrideBootstrapCommand everything works again.
> 
> Regards
> Steffen

Hi @steffakasid, Is that the entirety of your `overrideBootstrapCommand` config? Can you help us debug your issue by enabling SSH and checking the logs in one of your instances in the nodegroup? 

Additionally, can you try using [managed nodegroups](https://eksctl.io/usage/eks-managed-nodes/) with your custom AMI and  the same `overrideBootstrapCommand`, and see if it works?

**Comment by dbluxo** [comment]
@cPu1 I have already posted some logs above: https://github.com/weaveworks/eksctl/issues/3563#issuecomment-842290454 With managed nodegroups it works (same AMI).

**Comment by Callisto13** [comment]
@dbluxo @steffakasid neither of you need to add the `overrideBootstrapCommand` _yet_. This notice is for a future breaking change, not a current one.

**Comment by steffakasid** [comment]
Thanks a lot for clarifying @Callisto13

**Comment by mpitt** [comment]
Hi, on https://eksctl.io/usage/custom-ami-support/ it says:

> From eksctl version 0.52.0 unmanaged nodegroups created with custom AmazonLinux2 or custom Ubuntu images will need to have the overrideBootstrapCommand configuration option set.

I'm using version 0.53.0, not specifying `overrideBootstrapCommand` and I still get the message "Custom AMI detected [...] using legacy nodebootstrap mechanism", I assume the breaking change has been postponed. If that's the case, can the documentation be updated to reflect this?

**Comment by Callisto13** [comment]
@mpitt yep I will fix that, knew I had forgotten something 🤦‍♀️ . You will see `"Custom AMI detected [...] using legacy nodebootstrap mechanism"` whenever you set `nodeGroups[].ami:` to be `ami-xxxx` (ie setting the ID).

**Comment by vishalbollu** [comment]
In the past I've been burnt by the `ami: auto`. As you've mentioned in the ticket, sometimes AWS would push new versions of AMIs which resulted in new nodes initializing with the new AMI and not joining cluster. 

As a way to avoid this issue, I maintain a snapshot of AWS AMIs (EKS optimized AMI and EKS optimized accelerated AMI) that I've tested and set the ami to AMIs from that snapshot when spinning up an eks cluster. I updated the AMI snapshot periodically and test before releasing. 

Recently I've gotten the warning described in this ticket `Custom AMI detected for nodegroup ...` on version 0.50. 

Based on the `Who does this affect?` section it sounds like this shouldn't affect me because I am using the public standard AMIs, but I just wanted to doublecheck.

**Comment by Callisto13** [comment]
Hey @vishalbollu thanks for asking. This change will affect you since as far as eksctl knows you _are_ using a custom AMI.

But you do raise an interesting point: AWS does once in a while push a dodgy image which stops nodes coming up cleanly, and the obvious solution is to either get the ID of the last image that worked and set that as the `ami`, or maintain a snapshot of a good version as a backup. So in doing this change we now remove that easy workaround; users would also have to provide an `overrideBootstrapCommand` as well.
This is already the case for managed nodes: if AWS publish a bad AMI and users want to use a last known good one, they have to set both `ami` and `overrideBootstrapCommand` (or just wait for AWS to fix the issue). Because of this (and because we are soon to make managed nodes the default and prioritise them above unmanaged) we are unlikely to add a special case for one off "not really custom but pinning" AMI id setting, but I will definitely bring it up to the team for wider discussion.

**Comment by mmerkes** [comment]
For users that use a custom AMI but don't change how the bootstrapping process works from the existing AL2 AMIs, is there a way to tell eksctl "just bootstrap me like you would if I didn't specify a custom AMI"?

**Comment by cPu1** [comment]
> For users that use a custom AMI but don't change how the bootstrapping process works from the existing AL2 AMIs, is there a way to tell eksctl "just bootstrap me like you would if I didn't specify a custom AMI"?

When a custom AMI is supplied, eksctl does not perform any checks on whether the AMI is an official EKS AL2 AMI with all the bootstrap scripts in the right location, which is why it requires you to pass the bootstrap command for custom AMIs. But if you're building your AMI on top of the EKS AL2 AMI, you can use managed nodegroups and supply a minimal override bootstrap command, as in:

```yaml
managedNodeGroups:
- name: custom-ami
  ami: ami-custom
  overrideBootstrapCommand: |
    #!/bin/bash
    /etc/eks/bootstrap.sh <cluster-name>
```

**Comment by mr-karan** [comment]
Can the maintainers please tell what should we add to the cluster-config.yml under `overrideBootstrapCommand` if we're using Custom AMI and we want the same exact behavior of whatever happening now?

**Comment by cPu1** [comment]
> Can the maintainers please tell what should we add to the cluster-config.yml under `overrideBootstrapCommand` if we're using Custom AMI and we want the same exact behavior of whatever happening now?

I posted a working config just above your comment: https://github.com/weaveworks/eksctl/issues/3563#issuecomment-888089036

**Comment by mr-karan** [comment]
Yep saw that. Just to confirm, will this work for unmanaged node groups too? Thanks!

**Comment by cPu1** [comment]
> Yep saw that. Just to confirm, will this work for unmanaged node groups too? Thanks!

As I mentioned in my comment, managed nodegroups now have almost complete feature parity with unmanaged nodegroups. What features of unmanaged nodegroups are you using that's preventing you from migrating to managed nodegroups?

**Comment by Callisto13** [comment]
@cPu1 what do you think about creating a separate pinned thread about migrating to Managed ngs, and linking it here, just so folks don't get confused about what this thread is about?

**Comment by yakexi007** [comment]
when our team use a custom AMI, it  join the cluster to time out,  we ssh this node, find kubelet can't start and the error message
![image](https://user-images.githubusercontent.com/7007290/127736612-688393af-c6b3-4f9d-b66e-a831236230dd.png)
![image](https://user-images.githubusercontent.com/7007290/127736756-8d68045c-fe28-4287-8fd4-b09fec8717c5.png)
![image](https://user-images.githubusercontent.com/7007290/127736764-1db116ce-7496-41f5-b46c-00cf61ebdbfe.png)

**Comment by Callisto13** [comment]
@yakexi007 this looks like an unrelated issue, please can you open a new ticket providing all the information requested in the template.

**Comment by yakexi007** [comment]
ok, thank you

**Comment by alpana17** [comment]
Hi,
I am trying to create nodegroup with AL2 custom AMI by using the command (eksctl create nodegroup --cluster alp-cluster-121 --name alp-cluster-121-nodegroup --node-ami ami-099908d57c2742e91 --ssh-public-key alsingha-sa-east-1 --region sa-east-1) and I get the error
Error: couldn't create cluster provider from options: managedNodeGroups[0].overrideBootstrapCommand is required when using a custom AMI (managedNodeGroups[0].ami)


I tried to create nodegroup using cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: alp-cluster-121-north-virginia
  region: us-east-1

managedNodeGroups:
  - name: alp-cluster-121-custom
    ami: ami-07af0e585ffd35bff
    ssh:
      publicKeyName: alsingha-north-virginia
    disableIMDSv1: true
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh managed-cluster --alp-cluster-121-north-virginia
      
      
The nodes are created but they fail to join cluster. Do I need to create bootstrap.sh file in my custom AMI?
overrideBootstrapCommand: |
    #!/bin/bash
    /etc/eks/bootstrap.sh <cluster-name>

**Comment by Callisto13** [comment]
@alpana17, the argument to `/etc/eks/bootstrap.sh` needs to be the name of your cluster; in this case:
```yaml
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh alp-cluster-121-north-virginia
```
If you continue to have problems, please open a new issue.

**Comment by alpana17** [comment]
Do I need to create bootstrap.sh in my AMI?

**Comment by Raaj27** [comment]
Hi,
Is there any config changes when we are using only private subnets other than privatenetworking enabled to true.
Thanks

**Comment by Callisto13** [comment]
@Raaj27 no. Whatever else you do now when using custom AMIs for unmanaged nodes remains the same. This change only add the requirement of adding the `overrideBootstrapCommand` when using a custom AMI for unmanaged nodes.

**Comment by Raaj27** [comment]
@Callisto13 
ok. Thanks.

**Comment by AqsaMemon** [comment]
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: snap
  region: us-east-2
  version: "1.21"
managedNodeGroups:
  - name: ide
    instanceType: m6i.xlarge
    minSize: 2
    maxSize: 3
    disableIMDSv1: false
    volumeType: gp3
    volumeIOPS: 6000
    volumeThroughput: 500
    ebsOptimized: true
    ami: ami-0ad574da759c55c17
    overrideBootstrapCommand: |
       #!/bin/bash
       /etc/eks/bootstrap.sh snap
```
I am getting the same issue. Can anyone help what I am missing? Thanks

**Comment by AqsaMemon** [comment]
ami and bootstrap command is giving me error. failed to create cluster. Please help

**Comment by Skarlso** [comment]
@AqsaMemon What's your error?

**Comment by AqsaMemon** [comment]
**@Skarlso** node creation failure. failed to create cluster
```
unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-snap-nodegroup-snap-ide"
2022-03-01 19:28:27 [ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
2022-03-01 19:28:27 [✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Resource handler returned message: \"[Issue(Code=NodeCreationFailure, Message=Unhealthy nodes in the kubernetes cluster, ResourceIds=[i-071e9c535789b9bda, i-06d747bd302c9e276])] (Service: null, Status Code: 0, Request ID: null, Extended Request ID: null)\" (RequestToken: 3b5d5fc0-e93f-7285-3977-8a4c67a5fa9b, HandlerErrorCode: GeneralServiceException)"
2022-03-01 19:28:27 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2022-03-01 19:28:27 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-2 --name=snap'
2022-03-01 19:28:27 [✖]  waiting for CloudFormation stack "eksctl-snap-nodegroup-snap-ide": ResourceNotReady: failed waiting for successful resource state

**Comment by Skarlso** [comment]
Can you please take a look at the launchtemplate and see what kind of user-data is passed in and paste that here? Maybe there is something wrong with the overwriteCommand. Your config looks okay to me so far.

**Comment by Skarlso** [comment]
Ah, also, you can try to catch early problems during bootstrap by adding this: `set -ex` to the bootstrap script. So:

```bash
#!/bin/bash
set -ex

/etc/eks/bootstrap.sh snap
```

**Comment by AqsaMemon** [comment]
I am trying to install gitpod self hosted on eks. I am following this link : [](https://github.com/gitpod-io/gitpod-eks-guide). I am working on eks-cluster.yaml file :[](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/eks-cluster.yaml).
I do not see any launch template.
I am missing something basic or conceptual.

**Comment by Skarlso** [comment]
This is just an announcement, if anyone still has problems with bootstrapping, please open a separate issue with details! :) Thank you!
