### ISSUE TITLE
Deleting addon IAM policies in a managed nodegroup via a config file does not work

### ISSUE THREAD

**Issue by dafelipe130** [weaveworks/eksctl#3565]
**What were you trying to accomplish?**

Given an existing managed node group with some canned IAM addon policies attached and a config file with some of those addon policies removed, issuing an `eksctl upgrade nodegroup -f config-file-with-removed-add-on-policy` will update the CFN stack and in turn update the node instance role to remove the undesired IAM inline policies 

**What happened?**
It did not remove the policies in the instance role

**How to reproduce it?**

1. Create a cluster and a managed nodegroup with some IAM addon policies. All through a config file.
2. In the config file, remove some of the addon policies
3. Execute `eksctl upgrade nodegroup -f config-file-with-removed-add-on-policy`

**Logs**

**Anything else we need to know?**

**Versions**

```
dfelipe:lab dfelipe$ eksctl version
0.38.0
dfelipe:lab dfelipe$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
dfelipe:lab dfelipe$
```

**Comment by cPu1** [comment]
`eksctl upgrade nodegroup` upgrades a nodegroup to the latest AMI version, it does not update any other fields changed in the config as nodegroups are immutable. You'll have to create a new nodegroup using the new config and [delete the old one](https://eksctl.io/usage/managing-nodegroups/#deleting-and-draining).

**Comment by cPu1** [comment]
If you have any more questions, please feel free to open a new issue.
