### ISSUE TITLE
Unowned cluster test fails when deleting the cluster

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#3566]
Logs:

```
[12] 2021-04-13 05:02:52 [✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: DELETE_FAILED – "Nodegroup mng-2 failed to stabilize: [{Code: AccessDenied,Message: Amazon EKS is unable to communicate with your cluster, and can no longer manage your worker nodes.,}]"
```

**Comment by aclevername** [comment]
@cPu1 commenting out the KMS encryption seems to stop the tests from failing. I've ran the suite in isolation 5 times without it and they are all green:
https://github.com/weaveworks/eksctl/actions/runs/747929533
https://github.com/weaveworks/eksctl/actions/runs/747928994
https://github.com/weaveworks/eksctl/actions/runs/747928557
https://github.com/weaveworks/eksctl/actions/runs/747576853
https://github.com/weaveworks/eksctl/actions/runs/745224370

Either the KMS encyption is causing the problem, or the removal of the large time-gap between creating & delete the nodegroups is stopping some flake from occurring.
