### ISSUE TITLE
Skip add-on compatibility checks during creation of ARM nodegroups

### ISSUE THREAD

**Issue by ggml1** [weaveworks/eksctl#3569]
**Why do you want this feature?**

When trying to create nodegroups with ARM instances, we faced an error message which did not allow us to continue.

> 2021-04-13 12:32:02 [✖]  to create an ARM nodegroup kube-proxy, coredns and aws-node addons should be up to date. Please use `eksctl utils update-coredns`, `eksctl utils update-kube-proxy` and `eksctl utils update-aws-node` before proceeding.

But our addons were already updated and would support ARM instances with no problems (we were already running them with ARM nodes in other cluster). Still, we had to run the update utils in order to proceed. Running them is not ideal in our case because it would override specific configurations we had on the deployment resources of some addons, which would cause issues in our cluster. 

**What feature/behavior/change do you want?**

Due to this, it would be cool if there was a way of skipping this add-on compatibility check when creating nodegroups, and therefore leaving this responsibility to the user. I think this could be done by passing a flag to the `create nodegroup` command.

**Comment by aclevername** [comment]
Thanks for opening the issue @ggml1, sounds reasonable to me.
