### ISSUE TITLE
Allow Tags propagation to volume level in EKS

### ISSUE THREAD

**Issue by saleem-mirza** [weaveworks/eksctl#3584]
**What feature/behavior/change do you want?**

Currently, eksctl does not propagate tags to inner resources such as ec2 volumes etc. Requesting to propagate custom tags to Volume level in EKS at time of creation and also updating existing cluster.

**Why do you want this feature?**

Custom tags are crucial to manage and maintain infrastructure resources. AWS requires adding custom tags to resources for their MAP qualification program.

**Comment by Callisto13** [comment]
Thanks for requesting this @saleem-mirza. The team will look into implementation soon. In the meantime if you'd like to work on this yourself we are happy to accept PRs 😀

**Comment by saleem-mirza** [comment]
@Callisto13 I'll be submitting a PR soon.

**Comment by saleem-mirza** [comment]
@Callisto13 https://github.com/weaveworks/eksctl/pull/3639
