### ISSUE TITLE
Error retrieving node groups with v0.45.0

### ISSUE THREAD

**Issue by karrth** [weaveworks/eksctl#3597]
Using eksctl v0.45.0, I am unable to retrieve node groups from our cluster.  I had a co-worker duplicate the error.  All of our clusters are on v1.18.  I noticed release 0.45.0-rc.1 (#3526) made EKS version 1.19 the default, but I don't see any options to specify the version of the cluster.  Once I downgraded to v0.44.0, the command worked as expected.

```
$ eksctl get nodegroups --cluster=<cluster name>
2021-04-16 14:48:53 [ℹ]  eksctl version 0.45.0
2021-04-16 14:48:53 [ℹ]  using region us-west-2

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).GetAll(0xc0005b84e0, 0xc000568af8, 0x0, 0xc0005b84e0, 0x0, 0x3012582)
	github.com/weaveworks/eksctl/pkg/actions/nodegroup/get.go:49 +0x807
github.com/weaveworks/eksctl/pkg/ctl/get.doGetNodeGroup(0xc000be1600, 0xc000bdddd0, 0xc00071fd70, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/ctl/get/nodegroup.go:77 +0x25c
github.com/weaveworks/eksctl/pkg/ctl/get.getNodeGroupCmd.func1(0xc000d8ac80, 0xc000880e70, 0x0, 0x1, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/ctl/get/nodegroup.go:31 +0x9b
github.com/spf13/cobra.(*Command).execute(0xc000d8ac80, 0xc000880e50, 0x1, 0x1, 0xc000d8ac80, 0xc000880e50)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000bd8780, 0xc000880d80, 0x1, 0xc000e3ff70)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	github.com/weaveworks/eksctl/cmd/eksctl/main.go:76 +0x41b
```

Please let me know if there's other information I can gather to help diagnose the issue.

**Comment by aclevername** [comment]
@karrth thanks for opening the issue. We did make some minor changes to how we get nodegroup, could you describe what nodegroup you have and provide the output from the previous version of eksctl? Thanks

**Comment by karrth** [comment]
The nodegroups are a mix of managed and self-managed, with a mix of instances across `us-west-2a, b, c`.  The output with v0.44.0 looks as expected (the list of group is trimmed):

```
eksctl get nodegroup --cluster=dev-resources-cluster
2021-04-16 16:04:28 [ℹ]  eksctl version 0.44.0
2021-04-16 16:04:28 [ℹ]  using region us-west-2

CLUSTER			NODEGROUP			STATUS		CREATED			MIN SIZE	MAX SIZE	DESIRED CAPACITY	INSTANCE TYPE	IMAGE ID		ASG NAME
<clustername>	<groupname>		CREATE_COMPLETE	2020-11-19T20:02:34Z	1		12		1			m5.2xlarge	ami-####	eksctl-<clustername>-nodegroup-<groupname>
```

Can you expand on what information you're looking for in "describe what nodegroup you have" ?

**Comment by aclevername** [comment]
@karrth sorry I wasn't clear; could you provide your full output from eksctl get nodegroups? I'm hoping for some hints on how to reproduce this on our end as our tests are passing currently. 

Also could you provide the output for the command that fails with the '-v 5' flag to see more verbose logs

**Comment by karrth** [comment]
I've validated v0.46.0-rc.0 resolves the issue - do you still want me to pull that information?

**Comment by aclevername** [comment]
> I've validated v0.46.0-rc.0 resolves the issue - do you still want me to pull that information?

yes please, thanks.
