### ISSUE TITLE
Add support for EKS in Frankfurt, Singapore, Sydney, and Tokyo AWS Regions

### ISSUE THREAD

**Issue by jhedev** [weaveworks/eksctl#360]
**Why do you want this feature?**
EKS is now available in new regions [0]. eksctl should support creating clusters there.

**What feature/behavior/change do you want?**
Support creating clusters in the new regions

[0] https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-eks-available-in-frankfurt-singapore-sydney-and-tokyo-regions/

**Comment by rudybutter** [comment]
Would love this, can’t wait to get started in Frankfurt

**Comment by jhedev** [comment]
Me too :D

**Comment by errordeveloper** [comment]
Thanks for the heads-up, looks like we have a PR already: https://github.com/weaveworks/eksctl/pull/359. Thanks to @toricls!

**Comment by jhedev** [comment]
That was quick. Thanks!

**Comment by rudybutter** [comment]
Didn't expect it this quick, thanks a lot
