### ISSUE TITLE
StackName comes up blank

### ISSUE THREAD

**Issue by hendoncr** [weaveworks/eksctl#3606]
When running the following command, eksctl get nodegroup --cluster -o json, "StackName" comes up blank. It works when I change eksctl from 0.45.0 to 0.44.0
@brentley

**Comment by brentley** [comment]
For context, we use "StackName" in eksworkshop, and this ends up breaking parts of the workshop.

**Comment by Callisto13** [comment]
Interesting, thanks for reporting @brentley 👍  I imagine something small was overlooked, hopefully we should find it soon.

**Comment by aclevername** [comment]
I had no idea we event reported the stack name in the output!

Out of curiosity how does this get used in the workshop @brentley ? We changed the logic in `get nodegroups` to not use the cloudformation stack as the source of truth for the state of the nodegroup as it gets out of sync quickly due to autoscaling.

**Comment by aclevername** [comment]
@nikimanoledaki this PR broke it https://github.com/weaveworks/eksctl/pull/3543/files. We switched from looking up the Cloudformation stack to talking to the EKS api directly. This mean't we no longer generated the stack name

**Comment by brentley** [comment]
>Out of curiosity how does this get used in the workshop @brentley

We currently use it to figure out the IAM role name attached to the instances so we can add policies to them as needed throughout the workshop. I see the role arn has been added, so we could probably swap over to using that, but would prefer to have some "overlap" time to make that transition if possible.

**Comment by aclevername** [comment]
this should be fixed in the next release, likely `0.51.0-rc.0` this Friday
