### ISSUE TITLE
Parallel managed nodegroup upgrades

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#3613]
EKS is introducing new fields to configure how a nodegroup handles parallel upgrades.

- [x] **Create Nodegroup**

Let's add this to the config and set these fields during `create nodegroup`.

- [x] **Update Nodegroup**

These values can also be updated after the nodegroup is created via the `update-nodegroup-config` API call. We don't have an obvious eksctl command that this change could be made in. 

We can either:
~1. Add new flags to `eksctl upgrade nodegroup`, so you can change the configuration via that command. Slightly confusing since `updateConfig` is actually "updating" the config, not upgrading it.~

**2. Introduce a new `eksctl update nodegroup` command, slightly confusing as its only applicable for this small spec of information.**

~3. Intro a new `eksctl utils update-nodegroup-config`, a better name but some `utils` command.~

**Comment by aclevername** [comment]
@Callisto13 is there a aws-container-roadmap issue for this?

**Comment by Callisto13** [comment]
I'm told not

**Comment by aclevername** [comment]
@Callisto13 to document `eksctl edit` (or something like that) migration path
