### ISSUE TITLE
Is there any way I can update the instance type of a node group without recreating the node group?

### ISSUE THREAD

**Issue by KagurazakaNyaa** [weaveworks/eksctl#3621]
**What help do you need?**

I am trying to find a way to update the instance type of a node group without recreating it to avoid reconfiguration of various permissions.
But I found in the EKS document about node group configuration that only the instance type can be specified when it is created.
I also checked the documentation on eksctl.io. The above command to update the node group does not seem to specify the parameters of the configuration file, so the instance type of the node group cannot be passed in.
After searching the issues of this project using the "nodegroup" keyword, I did not find any helpful information for this issue.
Is there any other way I can update the instance type of the node group without re-creating it (for newly created nodes later)?

**Comment by Callisto13** [comment]
Hi @KagurazakaNyaa thanks for asking.

Currently there are not many ways you can alter the nodegroup without recreating it (especially changing the instance type, which would always result in a new instance/node) . The `update` command only upgrades the version of k8s (and that is just for managed nodegroups).

We are currently discussing how we can build some reconciliation into eksctl, which would allow us to automate changes like these and ensure ng configuration is maintained during update recreations, but we are still quite a long way off this.
