### ISSUE TITLE
Add ability to auto-install image automation controllers

### ISSUE THREAD

**Issue by davisford** [weaveworks/eksctl#3638]
**What feature/behavior/change do you want?**
When you install flux using the yaml spec under the `gitops` section, it works well, but it does not install the [image automation controllers](https://fluxcd.io/docs/components/image/) and there does not appear to be a way to specify it in the current spec?

The flux binary has the `--components-extra strings               list of components in addition to those supplied or defaulted, accepts comma-separated values` flag that allows you to specify that it install the image automation controllers.

**Why do you want this feature?**

Avoids having to run a manual step after the cluster comes up to install the image automation controllers

**Comment by aclevername** [comment]
Hey @davisford thanks for opening the issue. This sounds related to https://github.com/weaveworks/eksctl/issues/3238, we are aware that we don't expose all the configuration and should be working on adding support for all (or perhaps just arbitrary) flags in the near future :smile:

**Comment by Callisto13** [comment]
This will be available in the next release `0.53.0`.
