### ISSUE TITLE
Latest release binary link no longer exists

### ISSUE THREAD

**Issue by mrichman** [weaveworks/eksctl#364]
As of today, this URL no longer exists: https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_linux_amd64.tar.gz

I have some deployment scripts that rely on this location being available to download.

**Comment by errordeveloper** [comment]
I am not sure what has gone wrong, I've fixed this manually for now, and will make it a priority to fix early next week.

**Comment by errordeveloper** [comment]
Looks like the GitHub CND thrown 502 at us [while we were uploading the assets](https://circleci.com/gh/weaveworks/eksctl/1589):
```
   • RELEASING TO GITHUB      
      • creating or updating release repo=weaveworks/eksctl tag=latest_release
      • release updated           url=https://github.com/weaveworks/eksctl/releases/tag/latest_release
      • uploading to release      file=dist/eksctl_Linux_amd64.tar.gz name=eksctl_Linux_amd64.tar.gz
      • uploading to release      file=dist/eksctl_checksums.txt name=eksctl_checksums.txt
      • uploading to release      file=dist/eksctl_Windows_amd64.zip name=eksctl_Windows_amd64.zip
      • uploading to release      file=dist/eksctl_Darwin_amd64.tar.gz name=eksctl_Darwin_amd64.tar.gz
   ⨯ release failed after 29.00s error=POST https://uploads.github.com/repos/weaveworks/eksctl/releases/14663416/assets?name=eksctl_Linux_amd64.tar.gz: 502 Error uploading asset []
make: *** [release] Error 1
```
We should make goreleaser retry, it's unfortunate that it doesn't do it already.

**Comment by errordeveloper** [comment]
Closing in favour of #368.
