### ISSUE TITLE
Node kubectl unable to start due to incorrect Taints Argument

### ISSUE THREAD

**Issue by FabioSchmidberger** [weaveworks/eksctl#3654]
**What were you trying to accomplish?**

We tried to create a new nodegroup that was supposed to be added to the cluster.

The nodegroup had the config:

``` 
taints:
      controller: "true:NoSchedule"
```

**What happened?**

The new nodegroup was created but failed to connect to the k8s cluster due to an invalid argument. An invalid `:` is at the beginning of the `--register-with-taints` argument.

**How to reproduce it?**

Create a nodegroup with the following taints config using kubectl v0.47.0. (Tested on kubernetes 1.19)

``` 
taints:
      controller: "true:NoSchedule"
```

**Logs**

```
F0502 21:07:37.221415    8139 server.go:156] invalid argument "controllers=:true:NoSchedule" for "--register-with-taints" flag: invalid taint spec: controllers=:true:NoSchedule

``` 

**Anything else we need to know?**

The problem is only observed on v0.47.0. It works with eksctl v0.46.0.

This behavior is tested in: https://github.com/weaveworks/eksctl/blob/fc1f3b4b5ed6364777ad9d8160af9be241dd2319/pkg/nodebootstrap/ubuntu_test.go#L120

The case of `{"foo": "bar"}` is covered, but `{"foo": "true:bar"}` is not tested.

**Versions**

```
$ eksctl version
0.47.0

```
@Legion2

**Comment by Callisto13** [comment]
Thanks for reporting this @FabioSchmidberger, we'll get a fix out asap. You are welcome to open a PR if you'd like to 👍

**Comment by agoloAbbas** [comment]
this issue is happening with using 0.4.8.0 and eks 1.18
```
.... kubelet[7509] invalid argument "pool=:preemptible-standard:NoExecute" for "--register-with-taints" flag: invalid taint spec: pool=:preemptible-standard:NoExecute
```
I used 0.45.0 and it works fine
