### ISSUE TITLE
Automate the creation of Linux bastion host

### ISSUE THREAD

**Issue by tanvp112** [weaveworks/eksctl#3658]
**What feature/behavior/change do you want?**

Incorporate the Linux bastion host CF template into eksctl to enable 1 step provision for a fully functional EKS cluster with private control plan and node groups.

CF Template: https://aws.amazon.com/quickstart/architecture/linux-bastion/

**Why do you want this feature?**

Currently this is a 2 step processes. On top of that, it is possible that the issue of adding (443) rules to cluster SG may be resolved in the bastion CF template by referring the cluster SG created by eksctl. No manual creation of additional SG or hunting for the cluster SG to add the rule.

Thanks!

**Comment by Callisto13** [comment]
Hi @tanvp112  thanks for asking.

After some discussion, the team has decided that this is not the right direction to take `eksctl` in. We do however want to make it easier for people to make their `eksctl` clusters work with custom networking solutions. Could you please let us know what is currently difficult/impossible for you?

**Comment by Callisto13** [comment]
Tagging in @aclevername incase anything comes up while I am away

**Comment by tanvp112** [comment]
hi @Callisto13, @aclevername, 

I don't have difficulty to deploy the bastion host. Just that since eksctl already created the cluster efficiently using CF, I wonder why eksctl does not want to automate this if vpc.clusterEndpoints.privateAccess: true. I am fine if this is not the right thing for eksctl to do, but can you please share with us the reason?

@Callisto13, by design we always use aws vpc cni, we only use calico outside aws. Since eksctl is an eks tools, does it make much sense for eksctl to support custom network solution?

Thanks!

**Comment by cwwarren** [comment]
There are many options when running a private control plane including SSH bastions, EC2 self-managed VPNs and AWS managed VPNs, none of which is a clear winner and all of which have tradeoffs depending on network architecture and environment.

Maybe an alternative to this ticket is the ability to add custom CloudFormation to be deployed during cluster creation, either with defined inputs or a big red warning label that says it's unstable and may break between `eksctl` minor versions.

**Comment by tanvp112** [comment]
Bastion host is the most economical and we can apply lots of security checks on the host itself. And there's already a standard aws CF for it. A eksctl switch that would deploy this CF along during new cluster provision will be handy. It's ok if this suggestion is turned down, no issue. But I am curious why eksctl team think this is not a right direction... maybe there's a better idea or gotcha somewhere? Happy to learn about if anyone care to share.
