### ISSUE TITLE
Neuron device plugin use the public repo.

### ISSUE THREAD

**Issue by aws-vrnatham** [weaveworks/eksctl#3660]
**What feature/behavior/change do you want?**
Currently for neuron device plugin only us-east-1 and us-west-2 ecr repos are used. Now that a public repo is available, use that instead of region specific one

**Why do you want this feature?**
User of inf1 instances for example in china can use this.
https://github.com/aws/aws-neuron-sdk/issues/261

**Comment by aclevername** [comment]
Sounds good! thanks for opening the issue & PR @aws-vrnatham
