### ISSUE TITLE
eksctl utils update-coredns <set-image>

### ISSUE THREAD

**Issue by franklinRibe** [weaveworks/eksctl#3687]
Hello my friends,

I would like to suggest a feature that would enable us to set the image in the update default add-ons command, like **--image** for example.

Why I want this?
Ever since **_docker.io_** implemented images download limits, we have faced problems when updating our clusters. Because when we run the `eksctl utils update-coredns` command and the clusters start updating the image inside of addons using the docker hub image, and the cluster starts to download it , we get a rate limit error, so we need to download the image manually, and then push it to our ECR to then subsequently add it to addons manually. This whole process is complicated because we have many clusters in which we need to update the control planes and node groups.

**Comment by Callisto13** [comment]
Hi @franklinRibe, would you be able to provide some logs/tracing of what you are seeing?

The coredns image used is not from docker.io, but from a public AWS ECR, so we a a bit surprised that you are seeing docker rate limit errors.
