### ISSUE TITLE
--max-pods-per-node, --node-ami and --node-security-groups are not supported for managed nodegroups

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#3690]
When running `eksctl create nodegroup` we specifically disallow `--max-pods-per-node --node-ami --node-security-groups` flags in our code:
https://github.com/weaveworks/eksctl/blob/38ab603213a12014842bd55a58d93f4bb16e239b/pkg/ctl/cmdutils/nodegroup_flags.go#L62-L68

However it appears that we do use these flags config file counterparts values during the managed nodegroup creation, e.g. :

https://github.com/weaveworks/eksctl/blob/fc1f3b4b5ed6364777ad9d8160af9be241dd2319/pkg/nodebootstrap/managed.go#L46-L48

For these 3 flags, go through them individually and see if theres any reason why they can't be enabled for managed nodegroups. If they can then open a PR to enable them. If they cannot please document on this issue

**Comment by cPu1** [comment]
>--max-pods-per-node, --node-ami and --node-ami 

I believe you meant `--max-pods-per-node`, `--node-ami` and `--node-security-groups`.


AFAIK, there's no reason not to support these flags for managed nodegroups. They're all supported features.

**Comment by aclevername** [comment]
> > --max-pods-per-node, --node-ami and --node-ami
> 
> I believe you meant `--max-pods-per-node`, `--node-ami` and `--node-security-groups`.
> 
> AFAIK, there's no reason not to support these flags for managed nodegroups. They're all supported features.

oops yes, thanks will update.
