### ISSUE TITLE
Change `eksctl create nodegroup/cluster` to create a managed nodegroup by default

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#3692]
Investigation story: https://github.com/weaveworks/eksctl/issues/3640

**What feature/behavior/change do you want?**
Currently any imperative commands default to creating unmanaged nodegroups, and are specfficaly set to managed via the `--managed` flag. Lets change it so that `--managed=true` is the default. This applies to `eksctl create nodegroup` and `eksctl create cluster` (this by default creates 1 unmanaged ng)

**Why do you want this feature?**
EKS managed nodegroups have started to reach feature parity with unmanaged and provide a better UX for upgrades, lets make it the default.

## Breaking change

This behaviour is a *breaking change*. Anybody with any automation setup to imperatively create nodegroups and who don't specifically set `--managed=false` will see a change in behaviour. Given that the majority of eksctl commands are run with a config file, the impact of this change is likely to be small, but we should try to guide the user to understand the changes. The following flags only work with `unmanaged` nodegroups:
```
 --instance-prefix
 --instance-name
 --disable-pod-imds # Pending outcome of https://github.com/weaveworks/eksctl/issues/3695
 --node-ami-family # only certain arguments
```
 If any of these flags are provided and managed is true (the default) we should add a hint to the user to let them know about the change, and suggest appending the `--managed=false` flag. This should limit the confusion caused by the change.

Blocked on completion of: https://github.com/weaveworks/eksctl/issues/3690 https://github.com/weaveworks/eksctl/issues/3691 https://github.com/weaveworks/eksctl/issues/3695 https://github.com/weaveworks/eksctl/issues/3709

**Comment by aclevername** [comment]
@cPu1 is there any precedence for this sort of breaking change in the past? Wondering whats the best method for communicating this to the community. Although admittedly I think this will have a rather small impact since it only effects imperative commands

**Comment by Callisto13** [comment]
Deprecate max pods.

Potentially blocked by getting inferentia on managed
