### ISSUE TITLE
drain nodegroup on deletion

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#370]
After #369 lands we should add drain capability on deletion, to cater for upgrades nicely (#100, #357, #348). It seems plausible to add `--drain` and keep on by default.

**Comment by mumoshu** [comment]
@errordeveloper `--drain` sounds great if what it does is basically calling `kubectl drain` for each node in the nodegroup being deleted!

Adding a node-drainer addon just makes the flag optional, and may also adds the possibility to handle instance termination external to eksctl, like spot instance termination. Am I correct?

**Comment by errordeveloper** [comment]
Looks like we could try using [`github.com/kubernetes/autoscaler/cluster-autoscaler/utils/drain`](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/drain/drain.go) package, or otherwise we can refactor [kubectl code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/drain/drain.go) into a library that we can then call.

**Comment by errordeveloper** [comment]
I've started working on https://github.com/kubernetes/kubernetes/pull/72827.

**Comment by errordeveloper** [comment]
To facilitate for upgrades, I will try and get this implemented before I finish [kubernetes/kubernetes#72827](https://github.com/kubernetes/kubernetes/pull/72827).

**Comment by whereisaaron** [comment]
Discussion and builds of automatic node draining for ASG in-scaling and Spot Fleet shutdowns, similar to `kube-aws` https://github.com/awslabs/amazon-eks-ami/issues/66

**Comment by errordeveloper** [comment]
@whereisaaron that seems to be more related to #586, don't you think?

**Comment by whereisaaron** [comment]
Oh yes, didn’t spot it. Moved it over.
