### ISSUE TITLE
Add/Remove policy for FargatePodExecutionRole

### ISSUE THREAD

**Issue by tanvp112** [weaveworks/eksctl#3705]
**What feature/behavior/change do you want?**

Currently, cluster provisioned with fargateProfiles and later on manually enabled with Fargate logging; when come to eksctl delete cluster:

stack's status of nodegroup named ... is **DELETE_FAILED**

This is because the FargatePodExecutionRole cannot be deleted when the logging policy is still attached to it.

It will be great if there is similar mechanism like wellKnownPolicies that can be attached to FargatePodExecutionRole during eksctl create cluster; and automatically detach and removal during eksctl delete cluster.

**Why do you want this feature?**

End to end cluster automation with eksctl

**Comment by jonathanfoster** [comment]
@tanvp112, @Callisto13 I just ran into this issue myself. I'd like to enable Fargate logging, but I have to manually add the logging policy. I agree it would be a nice feature if we could attach a policy to the FargatePodExecutionRole. Did anyone ever look further into this?
