### ISSUE TITLE
managed inferentia nodes

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#3729]
does it work with eksctl? If not lets! Do we test it in our integraiton tests? If not lets!

**Comment by cPu1** [comment]
I can confirm that Inferentia works with managed nodegroups.

**Comment by aclevername** [comment]
@cPu1 do you think its worth updating the integration tests to test this or nah?

**Comment by cPu1** [comment]
> @cPu1 do you think its worth updating the integration tests to test this or nah?

I think we should. This [change](https://github.com/weaveworks/eksctl/pull/3897) automatically makes the Inferentia tests use managed nodegroups. I'm contemplating adding tests for unmanaged nodegroups now.

**Comment by cPu1** [comment]
https://github.com/weaveworks/eksctl/pull/3897 adds tests for both managed and unmanaged nodegroups.
