### ISSUE TITLE
Throttle errors go to stdout even when eksctl output is set to json format

### ISSUE THREAD

**Issue by benwaffle** [weaveworks/eksctl#3730]
**What were you trying to accomplish?**
parse the output of `eksctl get iamserviceaccount --name cluster-autoscaler-aws-cluster-autoscaler -o json --cluster $CLUSTER_NAME`

**What happened?**
The API call was throttled
```
2021-05-18 19:27:29 [!]  retryable error (Throttling: Rate exceeded
	status code: 400, request id: 52123a59-f709-4984-b22b-30112345661) from cloudformation/DescribeStacks - will retry after delay of 8.060901573s
```
this error message went to stdout, so I cannot use `jq` to parse the output.

I would have expected the error message to go to stderr, and after a retry the JSON would go to stdout for `jq` to parse.

**How to reproduce it?**
1. Run `eksctl get iamserviceaccount --name cluster-autoscaler-aws-cluster-autoscaler -o json --cluster $CLUSTER_NAME | jq .`. Not sure why but I always get a throttling error.

**Logs**
Nothing useful, besides
```
2021-05-18 19:31:53 [!]  retryable error (Throttling: Rate exceeded
	status code: 400, request id: 52123a59-f709-4984-b22b-30112345661) from cloudformation/DescribeStacks - will retry after delay of 5.918149619s
```

**Anything else we need to know?**

OS: macOS
binary: from homebrew
AWS credentials: default profile, with session token

**Versions**

```
❯ eksctl version
0.47.0
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aclevername** [comment]
ah this is annoying! Thanks for raising the issue @benwaffle , we will take a look :smile:

**Comment by ayeks** [comment]
Hey,

thanks for your work! It looks to me that the issue with errors in the JSON output resurfaced. Is anyone else seeing this problem for `eksctl get nodegroup --cluster k8s -o json`?

```json
eksctl get nodegroup --cluster k8s -o json
2021-10-04 13:24:11 [!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: ...) from cloudformation/ListStacks - will retry after delay of 971.707182ms
2021-10-04 13:24:12 [!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: ...) from cloudformation/ListStacks - will retry after delay of 880.446137ms
[
    {
        "StackName": "eksctl-k8s-nodegroup-ng-generic",
        "Cluster": "k8s",
        "Name": "ng-generic",
        "Status": "ACTIVE",
        "MaxSize": 5,
        "MinSize": 3,
        "DesiredCapacity": 3,
        "InstanceType": "m5.large",
        "ImageID": "AL2_x86_64",
        "CreationTime": "2021-09-16T11:21:07.246Z",
        "NodeInstanceRoleARN": "....",
        "AutoScalingGroupName": "eks-ng-generic-.....",
        "Version": "1.21"
    },
    {
        "StackName": "eksctl-k8s-nodegroup-ng-generic-m5a",
        "Cluster": "k8s",
        "Name": "ng-generic-m5a",
        "Status": "ACTIVE",
        "MaxSize": 5,
        "MinSize": 3,
        "DesiredCapacity": 3,
        "InstanceType": "m5a.large",
        "ImageID": "AL2_x86_64",
        "CreationTime": "2021-10-04T08:57:53.556Z",
        "NodeInstanceRoleARN": "...",
        "AutoScalingGroupName": "eks-ng-generic-m5a-...",
        "Version": "1.21"
    }
```

**Versions**:
```bash
$ eksctl version
0.68.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by benwaffle** [comment]
i'm on 0.68.0 and the errors are still going to stderr as expected

**Comment by aclevername** [comment]
> Hey,
> 
> thanks for your work! It looks to me that the issue with errors in the JSON output resurfaced. Is anyone else seeing this problem for `eksctl get nodegroup --cluster k8s -o json`?
> 
> ```json
> eksctl get nodegroup --cluster k8s -o json
> 2021-10-04 13:24:11 [!]  retryable error (Throttling: Rate exceeded
>         status code: 400, request id: ...) from cloudformation/ListStacks - will retry after delay of 971.707182ms
> 2021-10-04 13:24:12 [!]  retryable error (Throttling: Rate exceeded
>         status code: 400, request id: ...) from cloudformation/ListStacks - will retry after delay of 880.446137ms
> [
>     {
>         "StackName": "eksctl-k8s-nodegroup-ng-generic",
>         "Cluster": "k8s",
>         "Name": "ng-generic",
>         "Status": "ACTIVE",
>         "MaxSize": 5,
>         "MinSize": 3,
>         "DesiredCapacity": 3,
>         "InstanceType": "m5.large",
>         "ImageID": "AL2_x86_64",
>         "CreationTime": "2021-09-16T11:21:07.246Z",
>         "NodeInstanceRoleARN": "....",
>         "AutoScalingGroupName": "eks-ng-generic-.....",
>         "Version": "1.21"
>     },
>     {
>         "StackName": "eksctl-k8s-nodegroup-ng-generic-m5a",
>         "Cluster": "k8s",
>         "Name": "ng-generic-m5a",
>         "Status": "ACTIVE",
>         "MaxSize": 5,
>         "MinSize": 3,
>         "DesiredCapacity": 3,
>         "InstanceType": "m5a.large",
>         "ImageID": "AL2_x86_64",
>         "CreationTime": "2021-10-04T08:57:53.556Z",
>         "NodeInstanceRoleARN": "...",
>         "AutoScalingGroupName": "eks-ng-generic-m5a-...",
>         "Version": "1.21"
>     }
> ```
> 
> **Versions**:
> 
> ```shell
> $ eksctl version
> 0.68.0
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
> ```

if you filter to only see `stdout` you shouldn't see the error anymore
