### ISSUE TITLE
`eksctl upgrade nodegroup --config-file...` ignores `releaseVersion` from config-file

### ISSUE THREAD

**Issue by kr3cj** [weaveworks/eksctl#3747]
The new [releaseVersion parameter in managedNodeGroups](https://github.com/weaveworks/eksctl/pull/3544) is awesome. It allows us to have more fine grained control over eks ami release versions and a more predictable/reliable upgrade process.

However, we noticed that when one calls `eksctl upgrade nodegroup --config-file my-file.yaml --cluster my-cluster`, it ignores any `releaseVersion` parameter from the config-file and grabs the latest ami instead. I do see that we can explicitly pass in `--release-version` as a CLI argument. But to bring `upgrade nodegroup` more in line with `create nodegroup` behavior, it would be great if it checked for and respected any `releaseVersion` parameter  from the config-file automatically. This way, I wouldn't have to manually specify it via `eksctl upgrade nodegroup --release-version...` and we could keep track and control of the desired release version through code.

Example config-file:

```
...
managedNodeGroups:
- name: my-node-group
  releaseVersion: 1.19.6-20210504
...
```

```
$ eksctl 0.49.0
$ kubectl version 1.19.11
```

References:
* https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateNodegroupVersion.html#API_UpdateNodegroupVersion_RequestSyntax

**Comment by cPu1** [comment]
It's not just the `releaseVersion` field that's ignored, the `upgrade nodegroup` command does not work with a config file at all. The reason being that eksctl does not support upgrading all nodegroups specified in a config file, and it'd be a confusing UX to support passing `--config-file` and `--name` simultaneously to specify the nodegroup to update from a config file. Although you did find a bug with the command where it's accepting the `--config-file / -f` option when it shouldn't be.

**Comment by kr3cj** [comment]
Thanks for the background info, @cPu1.

> eksctl does not support upgrading all nodegroups specified in a config file

Does that mean there is no intent to support that?

In any case, it looks like `eksctl` will soon support reading the config-file on `update nodegroup` commands. I'm not sure if that's different than `upgrade nodegroup` commands though. See https://github.com/weaveworks/eksctl/pull/3914

**Comment by nikimanoledaki** [comment]
That is correct @kr3cj! :)

Thanks again for opening this issue and finding this bug. Since we don't have plans on supporting a config file for `upgrade nodegroup` as of right now, this issue will be closed once the `--config-file` flag is removed.
