### ISSUE TITLE
Support for AWS CNI custom CIDR Ranges?

### ISSUE THREAD

**Issue by steffakasid** [weaveworks/eksctl#3780]
**What help do you need?**

Is there a way to configure custom subnets used by AWS CNI? I'm trying to setup the following: https://aws.amazon.com/premiumsupport/knowledge-center/eks-multiple-cidr-ranges/

But I don't like the fully manual way ;)

**Comment by Callisto13** [comment]
Hey @steffakasid are these the things you are after?
- [docs](https://eksctl.io/usage/vpc-networking/#change-vpc-cidr)
- [example yaml](https://github.com/weaveworks/eksctl/blob/main/examples/24-nodegroup-subnets.yaml)

**Comment by steffakasid** [comment]
Unfortunately not. As I understand the subnets settings are mostly for placing the nodes. But what I would like to do:

- Place all Nodes in [subnet1, subnet2, subnet3]
- Use [subnet4, subnet5, subnet6] for all PODs (assigned via AWS CNI)

Or did I miss understood something?

**Comment by Callisto13** [comment]
Aaah I see now, sorry I spaced on CNI. AFAIK eksctl does not expose a way to configure that right now

**Comment by steffakasid** [comment]
Ok thanks a lot. I found this: https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni

I think that will do fine with our automation.

Regards
Steffen
