### ISSUE TITLE
update defense in depth link that is from 2007

### ISSUE THREAD

**Issue by Morriz** [weaveworks/eksctl#3786]
as the title says, in your docs you see it:

https://eksctl.io/usage/kms-encryption/

Wouldn't you rather point to more up to date information?

**Comment by rverma-nsl** [comment]
Wouldn't it be nice if eksctl take care of bootstrapping the kms key too? That will also simplify the policy on the key side.

**Comment by Callisto13** [comment]
@Morriz do you have a link to an up to date doc?

**Comment by Morriz** [comment]
@Callisto13 maybe that is just not the data people need anymore and you wish to stay in context? Not up to me to write about that. I would stray from posting (links to) generic information/documentation...
