### ISSUE TITLE
Creating windows node group is removing Security group outbound rule 0.0.0.0/0 

### ISSUE THREAD

**Issue by vvazharksi** [weaveworks/eksctl#3788]
Hi, 

When using eksctl for creation of windows node group, the security group outbound rule 0.0.0.0/0 is getting removed and deployment stuck until I add it manually back. 

My cluster is fully private, I am noticing this behaviour when I specify the privateNetworking: true flag for the Windows node group. 

I believe that this is not expected behaviour any idea what might be causing this or how I can fix it ? 

Thank you!

**Comment by Callisto13** [comment]
Hi @vvazharksi, thanks for asking. Could you please supply your full cluster config (any sensitive info redacted), thanks!
