### ISSUE TITLE
Kubernetes v1.16 End of Support (September 27th, 2021)

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#3794]
Corresponding AWS ticket coming soon.

**Comment by chickenbeef** [comment]
AWS ticket created:

https://github.com/aws/containers-roadmap/issues/1423

**Comment by aclevername** [comment]
Pushed back to September 27, 2021, updating title.

**Comment by aclevername** [comment]
will be shipping in this weeks release ahead of the deprecation occurring on Monday 27th September
