### ISSUE TITLE
eksctl version 0.52.0 eks cluster update fails with CloudFormation throttle error. 

### ISSUE THREAD

**Issue by JosephOmo** [weaveworks/eksctl#3805]
<!--
We noticed that when we ran eksctl command to update our eks cluster from version 1.19 to 1.20 we are receiving CloudFormation API throttling error: 
❯ eksctl upgrade cluster --name example --approve 
2021-06-04 11:28:50 [ℹ] eksctl version 0.52.0 
2021-06-04 11:28:50 [ℹ] using region eu-central-1 
2021-06-04 11:28:51 [!] retryable error (Throttling: Rate exceeded 
status code: 400, request id: 80-5xxx2-4ef1-xx-18304888) from cloudformation/DescribeStacks - will retry after delay of 5.305030667s 
2021-06-04 11:28:57 [ℹ] will upgrade cluster "example" control plane from current version "1.19" to "1.20" 
Error: ResourceInUseException: Cannot VersionUpdate because cluster example currently has an update in progress 
{ 
RespMetadata: { 
StatusCode: 409, 
RequestID: "80-5xxx2-4ef1-xx-18304888" 
}, 
ClusterName: "example", 
Message_: "Cannot VersionUpdate because cluster example currently has an update in progress" 
}
We were able to get around this issue by using aws cli command and by upgrading our eksctl version to the latest (0.53.0).
$ eksctl version: 0.52.0

```

**Comment by JosephOmo** [comment]
<!--
We noticed that when we ran eksctl command to update our eks cluster from version 1.19 to 1.20 we are receiving CloudFormation API throttling error: 
❯ eksctl upgrade cluster --name example --approve 
2021-06-04 11:28:50 [ℹ] eksctl version 0.52.0 
2021-06-04 11:28:50 [ℹ] using region eu-central-1 
2021-06-04 11:28:51 [!] retryable error (Throttling: Rate exceeded 
status code: 400, request id: 80-5xxx2-4ef1-xx-18304888) from cloudformation/DescribeStacks - will retry after delay of 5.305030667s 
2021-06-04 11:28:57 [ℹ] will upgrade cluster "example" control plane from current version "1.19" to "1.20" 
Error: ResourceInUseException: Cannot VersionUpdate because cluster example currently has an update in progress 
{ 
RespMetadata: { 
StatusCode: 409, 
RequestID: "80-5xxx2-4ef1-xx-18304888" 
}, 
ClusterName: "example", 
Message_: "Cannot VersionUpdate because cluster example currently has an update in progress" 
}
We were able to get around this issue by using aws cli command and by upgrading our eksctl version to the latest (0.53.0).
$ eksctl version: 0.52.0

```

**Comment by nikimanoledaki** [comment]
Hi, thanks for raising a new bug. Could you please provide more info about this bug by following the [bug reporting template](https://github.com/weaveworks/eksctl/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.md&title=) to help us understand and reproduce the issue? Thanks.
