### ISSUE TITLE
eksctl doesn't recognise update_complete cloudformation status

### ISSUE THREAD

**Issue by timothyaws** [weaveworks/eksctl#3819]
**What were you trying to accomplish?**

eksctl create cluster
**What happened?**

Just after the cloudformation template to create the cluster enters a create_complete state, a changeset is applied to the cluster template, which completes it and leaves the stack in an update_complete status, which eksctl does not recognise and becomes stuck. Issue location here https://github.com/weaveworks/eksctl/blob/8ab886b8752038a3ee521aa30dc356468211c6f0/pkg/cfn/waiter/stack.go#L43-L70
**How to reproduce it?**

Run the eksctl create cluster command
Update the stack immediately after it enters a create complete state

**Logs**

**Anything else we need to know?**

**Versions**

```
$ eksctl version
0.52.0
$ kubectl version
n/a
```

**Comment by Callisto13** [comment]
Thanks for reporting @timothyaws, we will schedule it for work soon. If you'd like to PR the fix yourself, please go ahead 👍
