### ISSUE TITLE
Cluster Autoscaler Deployment Considerations

### ISSUE THREAD

**Issue by patstrom** [weaveworks/eksctl#3835]
**What feature/behavior/change do you want?**

The [recommended way](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html#ca-deployment-considerations) to deploy nodegroups is to isolate them to a single AZ and enable the `--balance-similar-node-groups` for the cluster autoscaler.

I think it would be nice if eksctl could aid in this by having some sort of `tripletNodegroup` construct (that's obviously a bad name, but still) where you could specify everything about a nodegroup (AMI, annotations, taints, labels, security groups etc...) except the specific AZ (and thus subnet) and have eksctl automatically create 3 separate nodegroups, one in each AZ, with the requested configuration.

Essentially, it would be neat if you could treat it as a single nodegroup in a `cluster.yaml` when it comes to configuration but then have it being mapped to the "best practices" of one nodegroup in each available AZ.

I suppose this kind of ties into https://github.com/weaveworks/eksctl/issues/3824 as well for the network configuration of it all.

**Why do you want this feature?**

Without this feature I would just copy-paste the same nodegroup 3 times and then manually edit the network information to have them run in the correct AZ & subnet. This would help out in reducing boilerplate.

**Comment by gohmc** [comment]
Good idea. Just to share, there's a new scaler on the horizon: [Karpenter](https://github.com/awslabs/karpenter). Tested on EKS, the speed to provision a node is quite impressive.
