### ISSUE TITLE
why people should use eksctl instead of aws cdk-eks

### ISSUE THREAD

**Issue by binchenX** [weaveworks/eksctl#3839]
**What help do you need?**

**Need some option/suggestion about why we should stick to eksctl, instead of using aws cdk-eks to create the cluster.**

## Context
Current we are using eksctl to create/manage eks clusters (~20 cluster at the moment in a very big cooperation, and expect to grow to 50 or 100 in 1-2 years) but there are some pushing/trend to use aws cdk to the create the cluster.

I can see clearly the advantage of aws cdk vs cloudformation; but not entirely how to articulate the pros and cons when comparing aws cdk-eks vs eksctl.  

My current take is that eksctl follow the principle of "doing one thing and do it well", and that's what I like about eksctl and why eksctl was choose as the tool to create the cluster in the first place. And the other side of the coin is: eksctl is for eks *only*. 

aws cdk-eks is part of the big aws cdk ecosystem. It means people can argue the benefit of using "single stuff (aka cdk) to take care of all the infrastructure ", especially in cooperation environment where there are other infra need to be taken care of.  Another "edge" of cdk is it is backed by AWS, for better for worse. 

So, those are my superficial comparison of cdk vs eksctl.  And at the moment, I'm still lean on eksctl. What would you say to people who are current using eksctl but are evaluating whether they should move to cdk-eks?

Thanks.

**Comment by tanvp112** [comment]
A plain cluster is nothing useful, eksctl does not only create a cluster, it comes with best practices for tagging, annotation, addon, policies etc... all of these are done in a declarative manner. Try do the same with CDK in imperative manner... even if it does work (put aside maintenance first), won't it be just another eksctl? 

If hybrid cloud is really a concern, terraform is the right way to go. But none will be able to go as deep as eksctl for EKS - "doing one thing and do it well", totally agreed. eksctl has contributed a lot to AWS EKS popularity today for its simplicity and effectiveness, truly a good job done by the folks here.

**Comment by chrisdrobison** [comment]
I agree to a point with what @tanvp112 has said. One thing to consider with the CDK is that it's scope goes beyond just infrastructure. For example, with EKS a plain cluster is not a completely setup cluster for out company. For us we have to deploy Dynatrace, Splunk, metrics server, etc operators/deployments to the server after it is up for it to be considered complete. There are also roles and service accounts that need to get put out there. Sure eksctl does some of this but you'll still need something else if your clusters need other things. CDK is designed to encompass the whole thing: deploy the cluster and deploy to the cluster because it frankly part of just setting it up.

**Comment by Fantaztig** [comment]
Sorry but I can't really agree with @tanvp112 here, starting with calling eksctl declarative when it is really the imperative nature of a cli that makes me want to use something like cdk in the first place.
Maybe things have changed over the last 6 months but it seems I can do everything with either eksctl and cdk in quite the same way. Having the configuration written down as code in cdk seems a big plus for me, especially when managing multiple clusters (where do you keep your state with eksctl?).
I was hoping eksctl brought some fancy additional features to the table but there is not much, at least from what I saw at glance. Only real advantage I see so far is the integrated authentication that makes accessing a cluster easier.
Just as @chrisdrobison  pointed out anything beyond cluster management needs to be done with other tools anyways and I would currently not vote for cdk8s at this point in time.
Please enlighten me if I missed something ;)

**Comment by Fantaztig** [comment]
I see, for simple projects this might be suitable. But as soon as you turn the complexity up a notch you will have to configure most of the options yourself either way. E.g. I don't want to create a new VPC with subnets as the subnets are shared or prepared through IaC already. In such cases having 60 lines of yaml for the cluster alone or 200 for the whole infra including vpcs, subnets, etc. doesn't make too much difference imho.
Referring to infrastructure state, as long as I don't explicitly copy the default values into my config yaml I have no real control over the resources created. Sure they are contained in a Cfn stack but this is hard to review e.g. in git.

**Comment by Skarlso** [comment]
@Fantaztig Then I suggest you use whatever tool you deem necessary for this situation. For plenty of other users, eksctl seems to work fine. :)

>In such cases having 60 lines of yaml for the cluster alone or 200 for the whole infra including vpcs, subnets, etc. doesn't make too much difference imho.

I'm not sure I get this one. I mean, 60 lines of yaml beat 200 lines of... what code? I think. Easier to maintain too. Besides, I doubt that 200 lines is enough including all the management stuff, and security groups, connections, enis, ASG configs, addons... etc. Not to mention things like, IAM roles, Karpenter support, eks anywhere...

>Referring to infrastructure state, as long as I don't explicitly copy the default values into my config yaml I have no real control over the resources created. Sure they are contained in a Cfn stack but this is hard to review e.g. in git.

What default values are you referring to? Do you mean names, policies and such? You can get the template for sure, but I'm still not following what state you would like to explicitly manage that you can't right now?

It's true that some things you can't normally update. eksctl is not great in apply style of definition, it was never meant to work like terraform or even flux. Although! You can use flux, and there are certainly ways that you can use eksctl declaratively like outputting generated config objects.

**Comment by Fantaztig** [comment]
@Skarlso  Yess, I guess thats a good conclusion after all. :) 
At the time of writing I was a bit bummed out about the fact that eksctl was praised to be **the** declarative tool for eks management, when I could not apply some of the changes I made in the config file without trying 4 different commands.
But then again, as you said, this is not terraform, so I have to learn the way of eksctl to appreciate its benefits.
Flux integration really sounds like something I may want to take a look at.
Cheers!
