### ISSUE TITLE
eksctl 0.53.0 delete cluster does not remove config of deleted cluster from .kube/config

### ISSUE THREAD

**Issue by tanvp112** [weaveworks/eksctl#3841]
**What were you trying to accomplish?**

Prior to 0.53.0 when a cluster is deleted, the config for the deleted cluster is removed from .kube/config by eksctl.

**What happened?**

Config for deleted cluster remains in .kube/config

**How to reproduce it?**

eksctl create cluster
kubectl get nodes
eksctl delete cluster --name <created cluster>
kubectl get nodes => will report error since the cluster is no longer exist but still remains in .kube/config

Possibly a regression of #558

**Comment by Callisto13** [comment]
Thanks for reporting @tanvp112, the team will get on it asap but feel free to submit a fix if you like 👍

**Comment by tanvp112** [comment]
Noted the issue was resolved with version 0.54. Thanks!
