### ISSUE TITLE
requires to input MFA token code everytime  

### ISSUE THREAD

**Issue by binchenX** [weaveworks/eksctl#3842]
**What were you trying to accomplish?**

We are using cross account assume role to get access the eks cluster but when using eksctl each time it is promoted to input the MFA token.

```
eksctl get clusters --verbose=4 
Assume Role MFA token code: xxxx
2021-06-14 15:25:10 [▶]  role ARN for the current session is "arn:aws:sts::xxxx:assumed-role/AdminUserRole/xxxxx"
2021-06-14 15:25:10 [ℹ]  eksctl version 0.53.0
2021-06-14 15:25:10 [ℹ]  using region ap-southeast-2
```

While using `aws eks` command, the MFA token is cached.

configs
```
cat ~/.aws/config
[default]
role_arn = arn:aws:iam::targetAccount:role/AdminUserRole
mfa_serial = arn:aws:iam::userAccount:mfa/user1
region = ap-southeast-2
source_profile = cns-non-prod

cat ~/.aws/credentials

[cns-non-prod]
aws_access_key_id=xx
aws_secret_access_key=xxx
region = ap-southeast-2
```

**What happened?**

Need to type MFA token each time.

**How to reproduce it?**

**Logs**

**Anything else we need to know?**

**Versions**

```
$ eksctl version
0.53.0

$ kubectl version
```

**Comment by Callisto13** [comment]
Hi @binchenX thanks for asking.

Eksctl does not do any authentication itself, it simply delegates.

When I auth with `aws configure` i end up with the following:

```sh
$ cat ~/.aws/credentials
[default]
aws_access_key_id = xxx
aws_secret_access_key = xxx
```

or when I auth with `gsts` I get:

```sh
$ cat ~/.aws/credentials
[default]
aws_access_key_id=xxx
aws_role_arn=xxx
aws_secret_access_key=xxx
aws_session_expiration=2021-06-22T17:56:06.000Z
aws_session_token=xxx
```

and both work for me.

It could be that having `~/.aws/config` is muddling what the delegated-to authenticator picks up. Could you try moving/deleting/emptying it?

**Comment by binchenX** [comment]
For other information, I think the "problem" is due to ekstctl didn't do any caching of the token. It would requires some effort to implement it.  

https://github.com/aws/aws-sdk-go/issues/1329
