### ISSUE TITLE
Error: getting list of API resources for raw REST client

### ISSUE THREAD

**Issue by SnowBiz** [weaveworks/eksctl#3860]
Receiving certificate error when using eksctl.
x509: certificate signed by unknown authority

```
eksctl create nodegroup -f cluster.yaml
2021-06-15 14:40:01 [ℹ]  eksctl version 0.53.0
2021-06-15 14:40:01 [ℹ]  using region us-east-1
2021-06-15 14:40:02 [ℹ]  will use latest version (1.20) for new nodegroup(s)
2021-06-15 14:40:02 [!]  will use version 1.20 for new nodegroup(s), while control plane version is 1.19; to automatically inherit the version use "--version=auto"
Error: getting list of API resources for raw REST client: Get "https://##################.sk1.us-east-1.eks.amazonaws.com/api?timeout=32s": x509: certificate signed by unknown authority
```

I am already specifying a certificate bundle for the aws cli using the `AWS_CA_BUNDLE` environment variable.
The above operation is not appearing to respect that.

I have not been able to find anything specific to the cli in the documentation on using cert bundle for eksctl to get around this.

**Comment by Callisto13** [comment]
Hi @SnowBiz thanks for asking.

Can you confirm how you are authenticating? Eksctl does not do any authentication itself, it simply delegates to whatever you have going on locally.

**Comment by SnowBiz** [comment]
I am authenticating via the AWS CLI. When using the AWS CLI I can either set the AWS_CA_BUNDLE with my certificate bundle or pass --no-verify-ssl on the command I am using. However, since Eksctl appears to work as a pass through to the AWS CLI it does not appear to have a way to use the same certificate bundle or an equivalent flag to '--no-verify-ssl' which causes self signed certificate errors.

**Comment by aclevername** [comment]
> I am authenticating via the AWS CLI. When using the AWS CLI directly, I can either set the "AWS_CA_BUNDLE" environment variable with my certificate bundle path or pass --no-verify-ssl on the command I am using. However, since Eksctl appears to work as a pass through to the AWS CLI it does not appear to be utilizing the same certificate bundle or have an equivalent flag to '--no-verify-ssl' to ignore SSL validation, which in turn causes self signed certificate errors.

It looks to me that the AWS-SDK-GO that we use under the hood to start a session should be picking up this environment variable https://github.com/aws/aws-sdk-go/search?q=AWS_CA_BUNDLE

Are you still having the issue?
