### ISSUE TITLE
eksctl cannot find existing aws subnets error

### ISSUE THREAD

**Issue by papillon88** [weaveworks/eksctl#3865]
### **Steps to replicate issue**
**1)** I created a VPC as mentioned in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-public-private-vpc.html
At the end of the activity I had below VPC config in my AWS -
_vpc cidr_ : 192.168.0.0/16
_subnet cidr :_
![image](https://user-images.githubusercontent.com/11804111/122327953-bfce9780-cefc-11eb-974d-9de1765cfe98.png)

**2)** I create a new cluster using below command -
`eksctl create cluster --name simple-app-eks-cluster 
    --version 1.18 
    --region us-east-1 
    --nodegroup-name ng-1 
    --node-type t2.small 
    --nodes 2 
    --nodes-min 1 
    --nodes-max 4 
    --ssh-access 
    --ssh-public-key key1 
	--zones us-east-1a,us-east-1b 
    --managed`
    A new cluster gets created in my aws account with new VPC and subnets. I then delete this cluster and all provisioned resources are delete in aws. good so far. 

**3)** I now use below command/s to again create a cluster but this time using the existing VPCs and subnets created in **1)**.
**command variation 1:**
`eksctl create cluster --name mycluster1 --vpc-cidr="192.168.0.0/16" --vpc-public-subnets="subnet-08b78fe05e78818b7" --dry-run -v 5 `
**command variation 2:**
`eksctl create cluster --name mycluster1 --vpc-public-subnets="subnet-08b78fe05e78818b7" --dry-run -v 5 `

_Both commands fail with below error :_
```
2021-06-16 23:35:31 []  no region specified in flags or config, setting to us-west-2                                                
2021-06-16 23:35:32 []  role ARN for the current session is "arn:aws:iam::############:user/xxxxxxxxxxx"                           
**Error: InvalidSubnetID.NotFound: The subnet ID 'subnet-08b78fe05e78818b7' does not exist**                                             
        status code: 400, request id: eec2c7ef-8cfb-4628-b19c-4ae70da9dec9   
```

I even tried tagging each subnet in AWS as mentioned in :
https://eksctl.io/usage/vpc-networking/
But everytime I get error if I force eksctl to reuse exisitng VPCs instead of creating new ones. 

Please help with why eksctl isnt able to reuse the existing subnets and VPCs for cluster creation but is able to create new subnet and VPCs  if --vpc-public-subnets OR --vpc-private-subnets flags are removed from the command.

**Comment by Callisto13** [comment]
Hi @papillon88, could you try those commands again setting `--region us-east-1` (which I believe is where you created them originally)? Subnets are regional resources, so this may be why eksctl is having trouble finding them.

**Comment by papillon88** [comment]
thanks. Its worked.
`eksctl create cluster --name mycluster1 --region=us-east-1 --vpc-public-subnets="subnet-08c25c5a949df7cd9" --dry-run -v 5`
