### ISSUE TITLE
CircleCI vs Github Actions

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#3869]
There can only be one.

This task is to investigate which thing we want to run our CI. Pros/Cons of both and a recommendation please

**Comment by aclevername** [comment]
https://medium.com/instrument-stories/using-github-actions-and-circleci-b0a30c0a2608
https://www.devopsauthority.tech/2021/02/08/github-actions-vs-circleci-comparing-ci-cd-platforms/

Doing some reading there seems to be very little in between the two in terms of functionality. Github Actions is missing 1 big feature which is to ssh onto a failed job, this works for circle (although I've found it to be a bit buggy in the past). However I haven't personally felt the need to do this for quite a few months, so its not a sore point for us AFAIK.

We currently use Github Actions for running labelling/lint/tests checks against PRs and haven't really had any problems with them, with the exception of Github outages.

We use CircleCI for releasing eksctl. Looking at our [configuration](https://github.com/weaveworks/eksctl/blob/main/.circleci/config.yml), we don't seem to really be using any feature specific to CircleCI, this job could easily be moved over to Github Actions.

## Pros of Github Actions
- Integrated into Github. One place to view your code, PRs, issue and CI runs.
- Simple workflow layout. Comparing our [eksctl CircleCI job for releasing](https://github.com/weaveworks/eksctl/blob/main/.circleci/config.yml) vs how we use [Github Actions to release in profiles](https://github.com/weaveworks/profiles/blob/main/.github/workflows/release.yaml), it seems much easier to read Github Actions.
- Used by other weaveworks projects, e.g. https://github.com/fluxcd/flux2/
## Cons of Github Actions
- No native functionality for SSHing onto failed runs

---

## Pros of CircleCI
- SSH onto failed runs

## Cons of CircleCI
- Confusing Dashboard. The layout to see whats running for what repo is quite messy when compared to Github Actions.
- More complex to write workflows

## Conclusion

There is very little between the two. The fact Github Actions means I don't have to leave Github, and is used by other weaveworks projects makes it the obvious choice to use.

**Comment by Callisto13** [comment]
cc @mnowster

**Comment by mnowster** [comment]
is there a con of GithubActions about running them locally? I've heard from other teams there's some difficulties there, or it's extra slow.

**Comment by mnowster** [comment]
how about parallelisation of tests? anything about configurability of the size of machines these things run on?

**Comment by mnowster** [comment]
I wouldn't close this just yet :) sorry I'm a bit delayed in getting back to it. 

And thinking out loud.

**Comment by aclevername** [comment]
> is there a con of GithubActions about running them locally? I've heard from other teams there's some difficulties there, or it's extra slow.

yes running them locally is painful. But you generally don't have to do that very often



> how about parallelisation of tests? anything about configurability of the size of machines these things run on?

We run stuff in parallel on github actions and it seems to be fine. I don't think you can configure the machine sizes in github actions, but its generally always been quite fast anyway (and was historically faster than CircleCI, although that might of changed now we upgraded our plan)



> I wouldn't close this just yet :) sorry I'm a bit delayed in getting back to it.
> 
> And thinking out loud.

Understood :ok_hand: FYI I did chat to the team at standup around my findings, and there were no objects to the outcome of just sticking with github actions :smile:

**Comment by mnowster** [comment]
@aclevername you put a pro for GH actions that it's used by another project, this is also true for circleci, it's used by wks. 

Editor point; where possible avoid words like obvious. We're looking at both of them to understand. If it was obvious, i wouldn't be asking for help and information.

Can you help me to understand more about the running locally? What about it is painful? What are some ways around it/what are options to resolve that?

**Comment by aclevername** [comment]
> @aclevername you put a pro for GH actions that it's used by another project, this is also true for circleci, it's used by wks.


Thats true, in the context of our team its been very valuable to copy things from https://github.com/fluxcd/source-controller and https://github.com/fluxcd/flux2/ as they are very simliar (CLIs, controllers etc). They have also even published re-usable Github Actions that we've been able to consume, e.g. [installing flux](https://github.com/fluxcd/flux2/tree/main/action)

> Editor point; where possible avoid words like obvious. We're looking at both of them to understand. If it was obvious, i wouldn't be asking for help and information.

:ok_hand: I've definitely let my biases get through on this :smile: 
 
> Can you help me to understand more about the running locally? What about it is painful? What are some ways around it/what are options to resolve that?

In order to run a github action workflow locally you have to use a community built tool called [act](https://github.com/nektos/act). Part of its pain is that to actually reproduce what happens in github actions, you have to pull a full ubuntu image, which is quite large. Actually running the workflow doesn't always seem to "just work". A certain amount of fiddling is always needed from my experience. I cant vouch for what its like with CircleCI as I haven't tried it.
