### ISSUE TITLE
Support for CloudFormation Assume Role

### ISSUE THREAD

**Issue by cluggas** [weaveworks/eksctl#3872]
**What feature/behavior/change do you want?**
When creating a CloudFormation Stack via `eksctl create cluster` I would like to be able to supply the ARN of a role that I want CloudFormation to assume when creating the resource in the stack.

This is similar to the `--role-arn` argument that is supported on the `aws cloudformation deploy` CLI command.

When set, this role appears on the Stack Info tab of the Cloudformation console
![Screenshot 2021-06-17 at 15 01 19](https://user-images.githubusercontent.com/273631/122411915-0e237b00-cf7d-11eb-9aa8-0e2526a2d0d0.png)

**Why do you want this feature?**
Our business security policies require us to disconnect the role that creates the stack from the role that creates the resources inside the stack, and CliudFormation does support that. Eksctl does not appear to at the moment.

**Comment by Callisto13** [comment]
Hi @cluggas thanks for asking.

The team will chat about this and get back to you. If you'd like to implement something yourself, we are happy to accept PRs 😃 .

**Comment by cPu1** [comment]
@cluggas, eksctl does provide a `cfn-role-arn` option that specifies the IAM role CloudFormation should use to call AWS APIs. Please give it a try and let us know if you have any questions.
