### ISSUE TITLE
A Network Load Balancer is never created in Fargate mode

### ISSUE THREAD

**Issue by victor-sudakov** [weaveworks/eksctl#3874]
I have successfully created an EKS Fargate-based cluster with the command
```
eksctl create cluster --name test2 --region us-east-2 --version 1.20 --fargate --vpc-cidr 172.29.0.0/16 --zones us-east-2a,us-east-2b,us-east-2c
eksctl utils associate-iam-oidc-provider --cluster test2 --approve
```

I can add pods, deployments and NodePort services to it so it's operational.

**Problem description.**

When I add a LoadBalancer type service, its EXTERNAL-IP is forever stuck in the pending state, the last event in `describe` is always "Ensuring load balancer" but no Load Balancer is ever created (I checked in the EC2 console, there is none). 
```
$ kubectl get svc
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
koshka       NodePort       10.100.158.116   <none>        80:31399/TCP   90s
koshkaext    LoadBalancer   10.100.43.238    <pending>     80:31190/TCP   70s
kubernetes   ClusterIP      10.100.0.1       <none>        443/TCP        39m
```

**What I expected** 

According to Amazon docs at https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html I expect a Network Load Balancer to be created for me automatically.

What am I missing? Have I (or eksctl itself) forgotten to add some roles and permissions? I'm attaching the service definition but it's really vanilla.
[koshka-lb.yaml.txt](https://github.com/weaveworks/eksctl/files/6674494/koshka-lb.yaml.txt)

**Comment by victor-sudakov** [comment]
And it remains in this state forever

```
$ kubectl describe svc koshkaext
Name:                     koshkaext
Namespace:                default
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
                          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
                          service.beta.kubernetes.io/aws-load-balancer-type: external
Selector:                 app=koshka
Type:                     LoadBalancer
IP Families:              <none>
IP:                       10.100.124.194
IPs:                      10.100.124.194
Port:                     web  80/TCP
TargetPort:               80/TCP
NodePort:                 web  32608/TCP
Endpoints:                172.29.132.153:80,172.29.167.150:80,172.29.185.164:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age    From                Message
  ----    ------                ----   ----                -------
  Normal  EnsuringLoadBalancer  2m39s  service-controller  Ensuring load balancer
```

**Comment by victor-sudakov** [comment]
Interesting, I've created a non-Fargate cluster (thought Fargate was the culprit)
```
$ eksctl create cluster --name test3 --region us-east-2 --with-oidc --ssh-access --ssh-public-key XXXXXXXXXXXXXX --vpc-cidr 172.28.0.0/16 --zones us-east-2a,us-east-2b,us-east-2c  --version 1.20  --auto-kubeconfig  --managed
```
and have the same problem:

```
$ kubectl get svc
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
koshka       NodePort       10.100.166.42    <none>        80:31138/TCP   14m
koshkaext    LoadBalancer   10.100.203.255   <pending>     80:31156/TCP   14m
kubernetes   ClusterIP      10.100.0.1       <none>        443/TCP        66m
$ kubectl describe svc koshkaext
Name:                     koshkaext
Namespace:                default
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
                          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
                          service.beta.kubernetes.io/aws-load-balancer-type: external
Selector:                 app=koshka
Type:                     LoadBalancer
IP Families:              <none>
IP:                       10.100.203.255
IPs:                      10.100.203.255
Port:                     web  80/TCP
TargetPort:               80/TCP
NodePort:                 web  31156/TCP
Endpoints:                172.28.12.95:80,172.28.14.142:80,172.28.63.32:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  14m   service-controller  Ensuring load balancer
```
What gives?

**Comment by gohmc** [comment]
From your screenshot, you need to install aws load balancer controller in order to use of [NLB "IP"](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/nlb/#ip-mode) type. IP mode is not supported using the in-tree LB controller.

If you only want NLB (instance mode) you don't need to install the aws lb controller, just remember to provision your node group with [addon policy "albIngress"](https://eksctl.io/usage/iam-policies/).

**Comment by victor-sudakov** [comment]
> From your screenshot, you need to install aws load balancer controller in order to use of [NLB "IP"](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/nlb/#ip-mode) type. IP mode is not supported using the in-tree LB controller.

I tried installing  the aws load balancer controller on a Fargate cluster from a Kubernetes manifest as specified in https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html . The  resulting aws load balancer controller requires a cert-manager, but the cert-manager would not start in a Fargate cluster because of the taints:
```
Name:           cert-manager-68ff46b886-w7nt7                                                                                         
Namespace:      cert-manager
[,,,]
0/5 nodes are available: 5 node(s) had taint {eks.amazonaws.com/compute-type: fargate}, that the pod didn't tolerate.
```

So I stumbled at that point and never went further with the aws load balancer controller.

> If you only want NLB (instance mode) you don't need to install the aws lb controller, just remember to provision your node group with [addon policy "albIngress"](https://eksctl.io/usage/iam-policies/).

_Instance target mode supports pods running on AWS EC2 instances._ 

I would like to use a totally-Fargate cluster so the  NLB "IP" type seems to be my only option? And this option is not viable because of the non-functional cert-manager.

What I would like to achieve is a Fargate-based cluster where I could easily expose a deployment to the Internet.

**Comment by gohmc** [comment]
AWS LB controller does not require cert-manager to operate. Where did you get that from? Use the latest eksctl released and try the minimum steps:

Create a Fargate only cluster: _eksctl create cluster --fargate --with-oidc --name mycluster --region xx-xxxxx-x_

Follow the steps here to [install AWS LB controller](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html). Region and VPC ID are mandatory during the helm installation.

By default the cluster you created above will run deployment in "kube-system" and "default" namespace on Fargate. You should be able to expose your service externally using AWS LB with IP mode now.

**Comment by victor-sudakov** [comment]
> AWS LB controller does not require cert-manager to operate. Where did you get that from?

I got it from https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html . I went the "Kubernetes manifest" way, not the "Heml V3" way in Step 5. It says _Install cert-manager to inject certificate configuration into the webhooks._  and there is a manifest for that.

> Follow the steps here to [install AWS LB controller](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html).

That's the document I was using. Thanks for the hint, I'll use Helm this time (instead of manifest) and see if it makes any difference.

> By default the cluster you created above will run deployment in "kube-system" and "default" namespace on Fargate. You should be able to expose your service externally using AWS LB with IP mode now.

A couple of short questions if you don't mind.

1. Which is the preferred/recommended LB type now, "instance mode" or "IP mode" from the point of view of high availability?
2. With a Fargate cluster, is the "IP Mode" load balancer my only option, correct?
3. Is there still a good reason to run an EC2-instance based cluster with its additional complexity and administrative overhead?

**Comment by gohmc** [comment]
Watch out the [different](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2083).

You achieve HA by running pods span across AZs, LB mode is how traffic flow to your pod, either thru any of the worker node or straight to the pod IP.

Yes.

Common argument is be able to cross platform by running upstream Kubernetes on any IaaS, if your revenue justified the overhead.

**Comment by victor-sudakov** [comment]
> Watch out the [different](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2083).

Thanks! I've also come across [this issue](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1606) after searching. So thank you again for your advice about using Helm, I have a working cluster now.

> You achieve HA by running pods span across AZs, LB mode is how traffic flow to your pod, either thru any of the worker node or straight to the pod IP.

I asked this question because I had noticed that it takes a considerable time (in minutes) for a LB target group to be reconfigured to new IPs after a `kubectl rollout restart deployment/XX`. The test service is inaccessible from the Internet for 1-2 minutes after `kubectl` reports the rollout is over. Maybe an "instance mode" LB would allow faster rollouts?

 
> Common argument is be able to cross platform by running upstream Kubernetes on any IaaS, if your revenue justified the overhead.

I see.

**Comment by gohmc** [comment]
Either mode won't allow faster rollout. You can use PodDisruptionBudget to improve availability during update.

By the way, if there's no further question about eksctl for LB with Fargate you should probably close this issue.

**Comment by victor-sudakov** [comment]
> By the way, if there's no further question about eksctl for LB with Fargate you should probably close this issue.

Closing, Thanks a lot for your help!

**Comment by victor-sudakov** [comment]
> Either mode won't allow faster rollout. You can use PodDisruptionBudget to improve availability during update.

I'll check it out as soon as 1.21 is available for EKS!
