### ISSUE TITLE
AWS-eks-custom-ami-managed-node-group-bootstrap-file-not-exists

### ISSUE THREAD

**Issue by tppalani** [weaveworks/eksctl#3876]
**I'm Trying to use my custom AMI image for EKS managed Node group, below are the steps performed during EKS node group creation.

1. bootstrap_user_data file has been created and its converted to base64 format as per the standard.

`#!/bin/bash
set -ex
B64_CLUSTER_CA= <My eks cluster Certificate authority value>
API_SERVER_URL= <My EKS cluster API server URl>
/etc/eks/bootstrap.sh <cluster-name> --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL  `

2. cat bootstrap_user_data | base64

3. Launch template created via custom-configuration.json file with below data

`cat config_custom_ami.json
{
  "LaunchTemplateData": {
  "EbsOptimized": false,
  "ImageId": "ami-0e00c1f097aff7fe8",
  "InstanceType": "t3.small",
  "UserData": "bootstrap_user_data",
    "SecurityGroupIds": [
     "sg-0e9b58499f42bcd4b"
   ]
 }
}`

4. Security group has been selected EKS cluster security group it was created automatically while creating EKS cluster first time.

5. creating launch template using eksctl command

`aws ec2 create-launch-template  --region eu-central-1  --launch-template-name my-template-name   --version-description "first version "  --cli-input-json file://custom.config.json`

6. creating node group using eksctl command

`aws eks create-nodegroup --region eu-central-1 --cluster-name my-cluster  --nodegroup-name my-node-group   --subnets subnet-<subnet1> subnet-<subnet2>  --node-role 'arn:aws:iam::123456789:role/EKSNODEGROUP'   --launch-template name=my-template-name`

7.After executing node group creation command it was taking 20 min to create node group at the same time desired VM is created as part of auto scaling group but nodes group not able to join to the cluster after 20 min.

8.Connect to your Amazon EKS worker node instance with SSH and check kubelet agent logs

`ssh -i my.key ec2-user@1.2.3.4
sudo -i
cd /etc/eks/bootstrap.sh 
-bash: cd: /etc/eks: No such file or directory`

could you please some one help why my bootstrap.sh file not exists inside the /etc/eks location in other hand in AWS console launch template - Advanced tab - i can able to see my user data in decoded format.

**

**Comment by Callisto13** [comment]
Hi @tppalani thanks for asking.

Can I confirm which cli tool you are using: from the snippets you have provided it looks like you are running `aws eks` which is _not_ the `eksctl` CLI. Are you using the AWS CLI or `eksctl` for these operations? You can also check out our [docs here](https://eksctl.io/).

**Comment by tppalani** [comment]
@Callisto13 thanks for the response. 

See first in used aws console to create launch template then using aws console I created node group. 

Then I tried awscli as well to perform all the steps. 

Then finally when I logged into worker node then I verified path /etc/eks directory not exist.

**Comment by Callisto13** [comment]
Thanks for confirming @tppalani.

`awscli` is a different tool, so you may want to try asking in that project repo ([this one I think](https://github.com/aws/aws-cli)).  If you do use `eksctl` and have any problems, we are always happy to help.
