### ISSUE TITLE
No cluster add-on flags for additional nodegroups creation.

### ISSUE THREAD

**Issue by milkowski** [weaveworks/eksctl#388]
During nodegroup creation on `eksctl v0.1.16` there is no possibility to define add-on flags: `--asg-access --external-dns-access --full-ecr-access` and they are not inferred form existing setup. Consequently ability to manage Route53/ECR/ASG resources will be lost if initial nodegroup is deleted because of insufficient IAM rights for newly created one.

**Comment by errordeveloper** [comment]
Thanks for reporting this, I will make sure to address it as part of #361. Currently those add-on flags are scoped to the cluster, and that's incorrect.
