### ISSUE TITLE
Ability to set tags when using eksctl utils associate-iam-oidc-provider

### ISSUE THREAD

**Issue by mooperd** [weaveworks/eksctl#3884]
`eksctl utils associate-iam-oidc-provider` creates rather anonymous identity providers within AWS. It would be great if these resources could be created with some kind of tag so we can keep track of what they are being used for.

**Comment by cPu1** [comment]
You're right, unlike many other resources, eksctl does not tag OIDC provider resources. I have run into this myself while trying to debug orphan OIDC provider resources which had no information about the cluster they were created for. At the very least, eksctl should tag OIDC provider resources with the cluster information, like it does for other resources. The title of your issue suggests that you're asking for adding custom tags to OIDC provider resources. Is that what you're looking for, or would default eksctl tags like `alpha.eksctl.io/cluster-name: <cluster-name>` suffice?

**Comment by mooperd** [comment]
I think the default eksctl tags would suffice.

**Comment by tanvp112** [comment]
@cPu1, is it possible to include OIDC as one of the resource that will be tagged using --tags?

**Comment by cPu1** [comment]
> @cPu1, is it possible to include OIDC as one of the resource that will be tagged using --tags?

@tanvp112, we have pushed a change that tags OIDC resources with the cluster information. Can you help us understand your use-case as to why the default cluster tags won't suffice?

**Comment by tanvp112** [comment]
My post was at the time when oidc was not tagged, i was just thinking if the --tags would tag oidc as well? By the way, by using --tags flag would it attempt to tag oidc twice?

**Comment by cPu1** [comment]
> My post was at the time when oidc was not tagged, i was just thinking if the --tags would tag oidc as well? 

`--tags` would not tag OIDC as it does not propagate all the way down to OIDC resources. 

>by using --tags flag would it attempt to tag oidc twice

It wouldn't.
