### ISSUE TITLE
Fix Config file schema docs page horizontal scroll

### ISSUE THREAD

**Issue by rothgar** [weaveworks/eksctl#3891]
It's impossible to view the site config name, description, and default value without scrolling. It's very frustrating.

Can we update the `md-content` in the material theme so it is wide enough to view the content without scrolling? I think I found the file that needs to be customized but I haven't figured out how to customize it yet.
https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/layout/_content.scss

Here's a gif showing what I would like
![eksctl-docs](https://user-images.githubusercontent.com/371796/123141396-3263d980-d40d-11eb-9b86-0b15f35786b8.gif)

**Comment by Himangini** [comment]
@rothgar thanks for creating this issue, good spot 👍🏻  I have added a PR that fixes this.
