### ISSUE TITLE
Better Handling of imageGCHighThresholdPercent and imageGCLowThresholdPercent kubeletExtraConfig fields

### ISSUE THREAD

**Issue by KyleMasterson** [weaveworks/eksctl#3892]
**What feature/behavior/change do you want?**

Automatic adjustment of high and low image garbage collection thresholds based on setting one or the other. For example, if we have set `imageGCHighThresholdPercent: 70` then `imageGCLowThresholdPercent` could be set to the same value.

**Why do you want this feature?**

When using an eksctl configuration file, to specify image cache garbage collection thresholds, we currently need to specify both the high and low values:

```
nodeGroups:
  - name: ng-1
    kubeletExtraConfig:
        imageGCHighThresholdPercent: 70
        imageGCLowThresholdPercent: 50
```

Which itself is not inherently an issue, however, if you are only attempting to set one of these values and you end up setting low > high or vice versa, it's not clear why the nodes will fail to join the cluster. For this reason, it would be much more convenient for the thresholds to automatically adjust to allow this NodeGroup to join the cluster.

Alternatively, making this explicitly clear in documentation and providing a useful error message would also satisfy my ask here, as my primary gripe was the difficulty I faced when attempting to set only the `imageGCHighThresholdPercent`, and the lack of information I faced around why the nodes appeared to not join the cluster for any discernible reason.

**Comment by Callisto13** [comment]
Thanks for asking @KyleMasterson 👍 

The `kubeletExtraConfig` setting are not "read" by `eksctl`, ie they are passed directly into the userdata and we don't check what is set. So this means users are responsible for all their values in the same way that they would be were they not using EKS/`eksctl`.

As you suggested we can add more docs around setting any kubelet config, and link to the relevant kube pages. We wont be able to provide an error message at `create` time, as again we don't read these values.

Getting bootstrap errors back to the user on why their nodes do not join is interesting to think about. Technically by the point the bootstrapping is failing it is "out of `eksctl`'s hands", so to speak, so as it stands users have to SSH onto the node and read various logs. I am not sure if there is a way for `eksctl` to pull those logs down for users (even if there were, which logs would we choose?) but it worth thinking about how we can help users a bit more.

**Comment by KyleMasterson** [comment]
Thanks for your response @Callisto13, that all makes complete sense.

Probably a much larger ask than what I was originally getting at, but you raise an interesting point around pulling logs to help users. It would be great if there was a means for `eksctl` to provide some dumps of common log locations that would normally only be accessible through `ssh` (i.e. `/var/log/messages`) when the timeout is hit waiting for nodes to become ready in the cluster.
