### ISSUE TITLE
Cannot fetch nodegroups

### ISSUE THREAD

**Issue by benwaffle** [weaveworks/eksctl#3894]
**What were you trying to accomplish?**
I was trying to get the NodeInstanceRoleARN to set up IAM roles. I had just create this cluster.

**What happened?**

```
❯ eksctl get nodegroup --cluster ${CLUSTER_NAME} -n workers-lg
2021-06-23 18:24:16 [ℹ]  eksctl version 0.54.0
2021-06-23 18:24:16 [ℹ]  using region us-east-1
Error: getting nodegroup's kubernetes version: failed to list nodes: no nodes were found
```

**How to reproduce it?**

1. Create a cluster with unmanaged node groups, defined in a ClusterConfig
2. Use `eksctl create cluster -f cluster.yaml` to do so
3. Run `eksctl get nodegroup --cluster ${CLUSTER_NAME}` to fetch nodegroup info

I think this part of the config should be enough: https://gist.github.com/283b3decf7e1dc88e09c89d876d05aad

**Logs**

https://gist.github.com/d9a9c32e80df6dcb7df7c0d787631c22

**Anything else we need to know?**

macOS, installed eksctl 0.54.0 from brew

**Versions**

```
❯ eksctl version
0.54.0
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-cf75c9", GitCommit:"cf75c9601ec63a63ba54c1c47caa9945af1f3a81", GitTreeState:"clean", BuildDate:"2021-02-13T00:14:16Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.16) exceeds the supported minor version skew of +/-1
```

**Comment by nikimanoledaki** [comment]
Hi, thanks for opening an issue about this! For unmanaged nodegroups, `get` uses the k8s client to get the nodegroup's k8s version. It could be that the nodes were not ready yet in the cluster if you had just created the cluster 🤔 Do you get this error even after the nodes are ready?

**Comment by benwaffle** [comment]
Some of my nodegroups are set to a minimum of 0 nodes because I only want to spin them up when needed

**Comment by friedrich-at-adobe** [comment]
Getting this same error after upgrading 0.53.0 to 0.54.0
I don't use managed nodegroups
https://gist.github.com/friedrich-at-adobe/8f873a641f0e713cba491709511e6113

**Comment by nikimanoledaki** [comment]
I see, could you tell me what you do to set your nodes to 0? do you do `eksctl scale nodegroup --nodes 0` or something else?

**Comment by friedrich-at-adobe** [comment]
Correct, I have nodegroups set to zero as well.

**Comment by nikimanoledaki** [comment]
We will be releasing later today with a fix for this but feel free to reopen this issue if the problem hasn't been solved for you! 😊

**Comment by benwaffle** [comment]
Amazing, thanks for fixing it so quickly!

**Comment by shiranpoz** [comment]
It might be me but i seem to be hitting this in 0.57.0

**Comment by benwaffle** [comment]
Can confirm it's fixed for me in 0.58.0, have not tested 0.57

**Comment by vflaux** [comment]
Still occurs in 0.69.0.
The nodes from a my new nodegroup cannot join the cluster due to authorization issues (that's another issue) and eksctl then cannot retrieve the version from the Node object in the cluster.
If the desired capacity of the asg is 0, eksctl skip the retrieval of this info. It should be safe to ignore the error if there is no nodes even if the desired capacity is > 0.

**Comment by metasim** [comment]
I'm getting it in version `0.86.0`.

**Comment by Skarlso** [comment]
@metasim hi!

Seems to work for me with latest eksctl.

```
2022-03-10 10:09:53 [ℹ]  kubectl command should work with "/Users/skarlso/.kube/config", try 'kubectl get nodes'
2022-03-10 10:09:53 [✔]  EKS cluster "test-unmanaged-get-ng-1" in "us-west-2" region is ready
➜  simple-cluster eksctl get nodegroup --cluster test-unmanaged-get-ng-1 --name ng-1
2022-03-10 10:11:16 [ℹ]  eksctl version 0.87.0-dev+fe181389.2022-03-04T19:10:32Z
2022-03-10 10:11:16 [ℹ]  using region us-west-2
CLUSTER                 NODEGROUP       STATUS          CREATED                 MIN SIZE        MAX SIZE        DESIRED CAPACITY     INSTANCE TYPE    IMAGE ID                ASG NAME                                                                TYPE
test-unmanaged-get-ng-1 ng-1            CREATE_COMPLETE 2022-03-10T09:05:26Z    1               2               1                    m5.large ami-01ae27c716d8b85f7   eksctl-test-unmanaged-get-ng-1-nodegroup-ng-1-NodeGroup-116XP8G4ZRTKR   unmanaged
➜  simple-cluster
```

If you have any more detail, please open an issue. We normally don't monitor closed issues. Thank you!

**Comment by Sasuke0713** [comment]
The reason you guys are having issues is because you are likely not authenticating to the cluster with the role that is in your `kube-context`  if your context is setup like so.

```
...
users:
- name: arn:aws:eks:us-east-1:xxxxxxxxxxx:cluster/<cluster>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - <cluster>
      - --role
      - arn:aws:iam::xxxxxxxxxxxx:role/eks-admin
      command: aws
      env:
      - name: AWS_PROFILE
        value: <cluster>-admin
```

So setup your config file like:
```
[profile <cluster>-admin]
source_profile = dev-admin
role_arn       = arn:aws:iam::xxxxxxxxxxx:role/eks-admin
```

Run `AWS_PROFILE=<cluster>-admin eksctl get nodegroup --cluster <cluster>`.

Or simply use an `aws sts assume-role --profile <cluster>-admin --role-arn arn:aws:iam::xxxxxxxxxxx:role/eks-admin --role-session-name $(whoami)` cli command
