### ISSUE TITLE
auth errors ignored in wait loop

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#390]
An auth error in wait loop can lead to `eksctl create` hanging.

```
 [0] >> ./eksctl create cluster -f ./examples/05-two-nodegroups.yaml
[ℹ]  using region eu-north-1
[ℹ]  setting availability zones to [eu-north-1b eu-north-1a eu-north-1c]
[ℹ]  subnets for eu-north-1b - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for eu-north-1a - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for eu-north-1c - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng1-public" will use "ami-082e6cf1c07e60241" [AmazonLinux2/1.11]
[ℹ]  nodegroup "ng2-private" will use "ami-082e6cf1c07e60241" [AmazonLinux2/1.11]
[ℹ]  creating EKS cluster "cluster-5" in "eu-north-1" region
[ℹ]  will create a CloudFormation stack for cluster itself and 2 nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=eu-north-1 --name=cluster-5'
[ℹ]  creating cluster stack "eksctl-cluster-5-cluster"
[ℹ]  creating nodegroup stack "eksctl-cluster-5-nodegroup-ng2-private"
[ℹ]  creating nodegroup stack "eksctl-cluster-5-nodegroup-ng1-public"


^C
 [130] >>  ./eksctl delete cluster --name=cluster-5 --region=eu-north-1
[✖]  checking AWS STS access – cannot get role ARN for current session: ExpiredToken: The security token included in the request isexpired
        status code: 403, request id: 731a2707-0f98-11e9-b189-1dd306f0167a
 [1] >>
```

**Comment by errordeveloper** [comment]
Should be able to use `ctl.NewClientSet` to refresh the token.

**Comment by errordeveloper** [comment]
I believe this is mostly to do with this:

https://github.com/weaveworks/eksctl/blob/21f56c257a55b8e57d1340b1778c70dc3e4fd9c4/pkg/cfn/manager/waiters.go#L28-L37

There are a few occurrences of similar construct, I believe.

The idea is that we try and hope that errors are of temporary nature, which does make sense in case when we have briefly lost internet connection. So we should probably try to inspect this error and look at what it is, the SDK has a way to march errors (see [`github.com/aws/aws-sdk-go/aws/awserr`](https://docs.aws.amazon.com/sdk-for-go/api/aws/awserr/)).

**Comment by martina-if** [comment]
I spent a day looking into different ways to achieve this and it doesn't seem a trivial problem to solve.

The main problem is that the aws sdk doesn't support this today. There is an interface called `credentials.Provider` that is meant to support the refresh of the token but today, the implementation of that interface that is being used in the `session` is the `StaticCredentialsFromCreds` which doesn't reload the credentials from the file. See https://github.com/aws/aws-sdk-go/issues/1993

Kops seems to have the same issue: https://github.com/kubernetes/kops/issues/5130

I think we should track the aws-sdk issue and upgrade when/if they do something about it.

**Comment by errordeveloper** [comment]
@martina-if thanks a lot! This is very useful to know where limitations of the SDK are in this area.

I think the main question is, as we moved on to using a logging retryer - does anything get printed to the user when auth errors occur? Main it'd be great to establish this. If we are not clear, perhaps we should just log a warning on any error instead of simply ignoring the error we get back?

**Comment by martina-if** [comment]
Yes we print something today:

```[!]  retryable error (ExpiredToken: The security token included in the request is expired
	status code: 403, request id: b5339318-8daf-11e9-8fd2-13bbf4ce59d2) from cloudformation/DescribeStacks - will retry after delay of 42ms
[!]  retryable error (ExpiredToken: The security token included in the request is expired
	status code: 403, request id: d6ae2220-8daf-11e9-a780-f7500396568b) from cloudformation/DescribeStacks - will retry after delay of 116ms
[!]  retryable error (ExpiredToken: The security token included in the request is expired
```

**Comment by errordeveloper** [comment]
Ok, I think this good enough to close the issue, don't you think?

**Comment by martina-if** [comment]
yeah, there doesn't seem to be much we can do about it so close it.
