### ISSUE TITLE
Documentation indicates an incorrect upgrade order (Control Plane, Addons, Nodes)

### ISSUE THREAD

**Issue by Kausheel** [weaveworks/eksctl#3904]
On the "Cluster Upgrades" documentation page, the order of upgrades is listed as:

1) Upgrade the Control Plane version.
2) Update the default Addons.
3) Upgrade the Node Groups.

https://eksctl.io/usage/cluster-upgrade/

However, this is inconsistent with the recommendations from the upstream Kubernetes.io documentation, and the EKS documentation:

https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/
https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html#updating-kube-proxy-add-on (Under the heading "Updating the kube-proxy add-on manually" there is a recommendation to upgrade the Nodes first.)

Both of the above pages indicate that the recommended upgrade order is:

1) Upgrade the Control Plane version.
2) Upgrade the Node Groups.
3) Update the default Addons.

If the order in the EKSCTL documentation is deliberate, then it would be worth mentioning the justification for why this is a requirement when using EKSCTL.

**Comment by nikimanoledaki** [comment]
Thanks for pointing this out @Kausheel! I will try to get some context about the upgrade ordering and get back to you.
