### ISSUE TITLE
The aws-ebs-csi-driver Helm chart incompatible with eksctl or AWS documentation? (invalid ownership metadata)

### ISSUE THREAD

**Issue by victor-sudakov** [weaveworks/eksctl#3912]
I'm trying to add EBS volume support to an EKS v1.20 cluster as specified in https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

After eksctl has created the cluster and IAM roles for me, I try to install the Helm chart as specified in the docs:

```
$ helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
$ helm repo update
$ helm upgrade -install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver  --namespace kube-system   --set enableVolumeResizing=true   --set enableVolumeSnapshot=true   --set serviceAccount.controller.create=true   --set serviceAccount.controller.name=ebs-csi-controller-sa

```
and get the following error:

```
Release "aws-ebs-csi-driver" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "ebs-csi-controller-sa" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "eksctl"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-ebs-csi-driver"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"

```

I'm attaching the YAML file used to create the EKS cluster (pretty vanilla).
[fargate_clusterconfig.yaml.txt](https://github.com/weaveworks/eksctl/files/6732396/fargate_clusterconfig.yaml.txt)

**Comment by ndegory** [comment]
@victor-sudakov if you create the service account for the controller with `eksctl create iamserviceaccount` (or with a config file), do not ask helm to create that same service account. use `--set serviceAccount.controller.create=false`. The documentation is incorrect.

**Comment by victor-sudakov** [comment]
>The documentation is incorrect.

It's remarkable that https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html has `serviceAccount.controller.create=true` while https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html has `controller.serviceAccount.create=false`. It's "false" this time, but note the different order: serviceAccount.controller.create vs controller.serviceAccount.create. It this intentional?

**Comment by aclevername** [comment]
> > The documentation is incorrect.
> 
> It's remarkable that https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html has `serviceAccount.controller.create=true` while https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html has `controller.serviceAccount.create=false`. It's "false" this time, but note the different order: serviceAccount.controller.create vs controller.serviceAccount.create. It this intentional?

We don't own these docs I'm afraid. However they are public if you would like to suggest a change https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/efs-csi.md

Closing as this isn't an eksctl issue, but rather an AWS docs issue.
