### ISSUE TITLE
Getting error message "only one argument is allowed to be used as a name" 

### ISSUE THREAD

**Issue by geoano** [weaveworks/eksctl#3913]
**What help do you need?**

Getting all the time error message which says **"only one argument is allowed to be used as a name"** when using eksctl to deploy a cluster into an existing VPC. The following code is used:

`eksctl create cluster –name= demo-eks --vpc-private-subnets= subnet-0d418554a3ebbfa1a, subnet-07ce12f7a7af9d632 --vpc-public-subnets= subnet-07a93b45f12e21028, subnet-00d13850c4bb3b92e –version= 1.20`

What can be the problem? Meanwhile, when it seems to be working when when I remove the --vpc-private-subnets and --vpc-public-subnets flags

**Comment by Callisto13** [comment]
I think the problem may be the spacing between flags and arguments, can you try again with this:

```
eksctl create cluster –name=demo-eks --vpc-private-subnets=subnet-0d418554a3ebbfa1a,subnet-07ce12f7a7af9d632 --vpc-public-subnets=subnet-07a93b45f12e21028,subnet-00d13850c4bb3b92e –version=1.20
```

**Comment by NaiveAp** [comment]
@geoano Also pass version flag like **--version** along with @Callisto13 suggestion.

**Comment by oxr463** [comment]
For me, it was the multiple tags (`--tags`), separated by spaces.

**Comment by Callisto13** [comment]
Closing this as there is nothing to fix on `eksctl`'s side.

Users can of course continue to help each other out by posting the things which led them to this error, the fix is always the same following the cli command pattern:

```
eksctl <verb> <noun> \
  --flag-withoutout-equals-sign arg-can-have-a-space \
  --flag-with-equals-sign=arg-cannot-have-space \
  --list-of-things-flag=comma,separated,args,no,spaces \
  <positional name arg, if required, goes last without flag>
```
