### ISSUE TITLE
aws-efs-csi-driver installation - pod remains in pending state forever

### ISSUE THREAD

**Issue by victor-sudakov** [weaveworks/eksctl#3917]
I have created a Fargate-based EKS cluster v1.20 (the eksctl config is attached), then ran the Helm chart as specified in https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html :

```
helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver/
helm repo update
helm upgrade -i aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver \
    --namespace kube-system \
    --set image.repository=602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/aws-efs-csi-driver \
    --set controller.serviceAccount.create=false \
    --set controller.serviceAccount.name=efs-csi-controller-sa
```
When I run
`kubectl get pod -n kube-system -l "app.kubernetes.io/name=aws-efs-csi-driver,app.kubernetes.io/instance=aws-efs-csi-driver"`
as recommended by the Helm message, I notice that the efs-csi-controller pods remain in the Pending state forever:

```
$ kubectl get pod -n kube-system -l "app.kubernetes.io/name=aws-efs-csi-driver,app.kubernetes.io/instance=aws-efs-csi-driver"
NAME                                 READY   STATUS    RESTARTS   AGE
efs-csi-controller-849dc8585-dknlv   0/3     Pending   0          106s
efs-csi-controller-849dc8585-qwz8g   0/3     Pending   0          106s
```
What am I doing wrong? Is efs-csi-controller not compatible with Fargate?

I'm attaching the cluster config.
[fargate_clusterconfig.yaml.txt](https://github.com/weaveworks/eksctl/files/6738681/fargate_clusterconfig.yaml.txt)

**Comment by gohmc** [comment]
Fargate does not support hostNetwork which efs-csi needed.

**Comment by victor-sudakov** [comment]
> Fargate does not support hostNetwork which efs-csi needed.

Does it mean that neither EBS nor EFS are supported on Fargate nodes? No persistent volume possible on Fargate at all?

**Comment by walkley** [comment]
EKS Fargate has already support EFS: https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-ek-on-aws-fargate-now-supports-amazon-efs-file-systems/

**Comment by victor-sudakov** [comment]
> EKS Fargate has already support EFS: https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-ek-on-aws-fargate-now-supports-amazon-efs-file-systems/

So the previous message from @gohmc was not correct?

**Comment by gohmc** [comment]
> EKS Fargate has already support EFS: https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-ek-on-aws-fargate-now-supports-amazon-efs-file-systems/

Able to mount EFS on Fargate does not equivalent to **running** EFS CSI driver on Fargate.

**Comment by aclevername** [comment]
I think this issue might be more appropriate for https://github.com/kubernetes-sigs/aws-efs-csi-driver, I don't believe its related to eksctl.

Closing.

**Comment by victor-sudakov** [comment]
> > EKS Fargate has already support EFS: https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-ek-on-aws-fargate-now-supports-amazon-efs-file-systems/
> 
> Able to mount EFS on Fargate does not equivalent to **running** EFS CSI driver on Fargate.

I think I understand. You mean that for the control-plane you still need nodegroups? A Fargate-only cluster is not feasible for the present, is that correct?
