### ISSUE TITLE
Add environment variable interpolation for ClusterConfig being passed into --config-file

### ISSUE THREAD

**Issue by nickjj** [weaveworks/eksctl#3919]
**What feature/behavior/change do you want?**

As far as I know it's not possible to use environment variables in the `ClusterConfig` that you pass to `--config-file`. I tried using both "`${FOO}`" and "`$(FOO)`" syntax and in both cases `eksctl` threw this error when I tried to apply it to the `region`:

`Error: checking AWS STS access -- cannot get role ARN for current session: MissingEndpoint: 'Endpoint' configuration is required for this service`

**Why do you want this feature?**

This came up recently while doing client work and wishing the config file were more portable. For example my personal AWS account operates out of `us-east-1` but I do client work where they run on `us-west-2`.

I wanted to define `region: "us-west-2"` as a `metadata` property in the config so that it works for them out of the box but it means when I do local testing on my account I need to remember to switch that value and then then switch it back, this is especially tedious since this config file is commit to version control.

**Proposed solution?**

It would be nice if we could do `region: "${AWS_DEFAULT_REGION:-us-west-2}"` and it would automatically grab the value from your shell's environment but fall back to a default value just like how variable interpolation works on the shell.

**Current workaround**

What I've done in the mean time is to move the region out of the config file and set it with the `--region` string. This isn't ideal because it's state I need to supply every time I run `eksctl`. Plus it's only a bandaid solution. For example on my local AWS account I may want to use 3x `t2.small` instances for testing but on my client's real cluster I may use many more servers and servers of a different type. The need is there to want to define these values dynamically through environment variables IMO.

**Comment by nikimanoledaki** [comment]
Thanks for opening this issue @nickjj, I will bring this up with the team and get back to you!

**Comment by nikimanoledaki** [comment]
Hey @nickjj, spoke to the team and we concluded that this functionality can probably be done outside of eksctl by piping the output of a bash command into eksctl. Since it would be quite a lot of work for something that can be done outside of eksctl, we won't be working on this. Thanks again for proposing this and please let us know if there's anything else!

**Comment by nickjj** [comment]
Do you mean using command line tools like `envsubst`?

Technically that does work but that command is very limited compared to supporting it directly. For example:

1. `envsubst` doesn't support variables with default values for when a value is unset. That means you can only define `${FOO}` in your config, not `${FOO:-mydefault}`. This makes it very tedious to use in the default case because now you have to define a bunch of environment variables.

2. You can no longer run the `eksctl` command directly, instead anytime you need to pass in the `--config-file` flag you need to pipe the output of `envsubst` to it, which means you need to create a custom `eksctl` binary that wraps `eksctl` to look for this flag to auto-pipe `envsubst` and then ensure this custom binary is present on every machine you run `eksctl` from, or alternatively set up aliases on every machine or remember to run this pipe sequence manually.

**Comment by Skarlso** [comment]
Hi @nickjj! While I think this is a great idea, I don't think it's the responsibility of eksctl to take care of custom config files.
You can take care of the substitution before you hand the config file over to eksctl in any way you desire. I would actually suggesting using something like go templates which would prime and populate the values you wish to edit, or kustomize or any other tool which can work with values inside yaml files.

I hope this makes sense.

All the best,
Gergely.
