### ISSUE TITLE
Regression in 0.55.0: `--spot is only valid with managed nodegroups`

### ISSUE THREAD

**Issue by nbusseneau** [weaveworks/eksctl#3929]
Hi,

We use `eksctl` on [`cilium/cilium-cli`](https://github.com/cilium/cilium-cli) for deploying an EKS cluster and running tests on it via GitHub Actions ([link](https://github.com/cilium/cilium-cli/blob/8d0139bb8af6b885da71c4c1d0e14af41f901274/.github/workflows/eks.yaml)).

First, we download the `latest` release:
```yaml
      - name: Install eksctl CLI
        run: |
          curl -LO "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz"
          sudo tar xzvfC eksctl_$(uname -s)_amd64.tar.gz /usr/bin
          rm eksctl_$(uname -s)_amd64.tar.gz
```

Then, we deploy a cluster without a nodegroup:
```yaml
      - name: Create EKS cluster without nodegroup
        run: |
          eksctl create cluster \
            --name ${{ env.clusterName }} \
            --tags "usage=${{ github.repository_owner }}-${{ github.event.repository.name }},owner=${{ steps.vars.outputs.owner }}" \
            --without-nodegroup
```

And finally, we setup a spot managed nodegroup:
```yaml
      - name: Add managed spot nodegroup
        run: |
          eksctl create nodegroup \
            --cluster ${{ env.clusterName }} \
            --nodes 2 \
            --instance-types "t3.medium,t3a.medium" \
            --node-volume-type gp3 \
            --node-volume-size 10 \
            --managed \
            --spot \
            --node-private-networking
```

Looking at [the list of scheduled runs](https://github.com/cilium/cilium-cli/actions/workflows/eks.yaml?query=event%3Aschedule) (running every 6 hours) we can see that the [last working run was on Jul 2 around 9 CEST](https://github.com/cilium/cilium-cli/actions/runs/992727965), with [the next run around 15 CEST failing](https://github.com/cilium/cilium-cli/actions/runs/993695438) at the managed spot nodegroup creation step, along with all subsequent runs:
```
Error: couldn't create node group filter from command line options: --spot is only valid with managed nodegroups (--managed)
```

Nothing changed in how we setup EKS clusters between the last working and first failing runs mentioned above.

[0.55.0](https://github.com/weaveworks/eksctl/releases/tag/0.55.0) was released on Jul 2 at 14:27 CEST. I strongly suspect a regression in 0.55.0 introducing the issue. Looking at the list of changes, I feel like #3895 might be related?

I don't have access to my work machine at present but will try the following reproduction steps on Monday:
- Download `eksctl` 0.54.0 and try to setup a spot managed nodegroup: I expect it will work.
- Download `eksctl` 0.55.0 and try to setup a spot managed nodegroup: I expect it will not work.

**Comment by dz902** [comment]
I can reproduce this with `0.55` and `0.56-rc1`. This is a fairly common command. It should not slipped under the radar for two releases.

**Comment by Callisto13** [comment]
Thanks for reporting @nbusseneau, after a quick bisect I found the change came with https://github.com/weaveworks/eksctl/pull/3887.

Fix will be along shortly 👍

**Comment by nbusseneau** [comment]
Can confirm I don't reproduce the issue with 0.54.0, but do with 0.55.0. Editing title.

**Comment by cPu1** [comment]
Closed by https://github.com/weaveworks/eksctl/pull/3930. The fix is out in https://github.com/weaveworks/eksctl/releases/tag/0.56.0-rc.1
