### ISSUE TITLE
mock cloudformation in unit tests

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#393]
Now with config file support, there are vert many ways how one can configure their cluster and it's hard to test even a small subset of potential permutation with what we have now.
Integration tests would be too expensive and time-consuming to run for all different config files, so not an option.

In theory, we could create tests that generate CloudFormation templates and verify that templates are right, however we cannot actually create nodegroup stack before cluster stack is live.
The only feasible option that comes to mind is to mock CloudFormation calls and let both stacks get created and test the outcome of that, i.e. validate how different config files affect output stack templates.

We would probably want to make `pkg/ctl/create` callable from unit tests also.

**Comment by errordeveloper** [comment]
Few options to consider:
- https://blog.gruntwork.io/open-sourcing-terratest-a-swiss-army-knife-for-testing-infrastructure-code-5d883336fcd5
- https://github.com/localstack/localstack

Also, we could try creating a smoke suite that would create VPC, IAM and all the rest, but exclude costly resources - EKS & EC2 instances. This would allow us to overcome bugs such as #496.

**Comment by michaelbeaumont** [comment]
#2722
