### ISSUE TITLE
Remove support for 1.16

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#3933]
EKS 1.16 will get removed on [July 25th](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/kubernetes-versions.md#amazon-eks-kubernetes-release-calendar), lets remove it from our documentation and remove any legacy codepaths for it.

**Comment by Callisto13** [comment]
don't we have something for this?

**Comment by Callisto13** [comment]
yeh this is a dupe https://github.com/weaveworks/eksctl/issues/3794

**Comment by aclevername** [comment]
:upside_down_face:
