### ISSUE TITLE
improve node label validation, remove type helper

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#394]
Validation should match what kubelet has:

https://github.com/kubernetes/kubernetes/blob/504466c4e67d3dd7318b567b198b651a10120fd3/cmd/kubelet/app/options/options.go#L257-L262

The helper type `api.NodeLabels` is not particularly useful, we can probably remove it.

**Comment by whereisaaron** [comment]
It would be nice to be able to set node-group taints also. E.g. this is required for keeping DaemonSets off some nodes.

**Comment by errordeveloper** [comment]
Yes, please open another issue.

**Comment by mumoshu** [comment]
Opened an another issue in #396
