### ISSUE TITLE
Regression on v0.55.0 ? eksctl create cluster not finding Nodes despite creating EC2 instances ...

### ISSUE THREAD

**Issue by grb123** [weaveworks/eksctl#3941]
Hi all, running `eksctl create cluster -f eks.yaml` with this minimal manifest;

am seeing error `"Error: getting auth ConfigMap:..usually a temporary error during hostname resolution"`.
I do see my 3 EC2I nodes actually running fine but no Nodes are found on AWS EKS Cluster console, and `kubectl get nodes` giving `No Resources`, though svc visible...
AWS CloudFormation not providing too many clues on the ;missing; Nodes and Cluster Stacks which appear compliant against respective templates...
Looking in AWS console, looks like EKS Node discovery didnt happen due to ConfigMap lookup failure - has anyone seen this one before ? Best course of action ... ?

Many Thanks... 

[eks.yaml.txt](https://github.com/weaveworks/eksctl/files/6765729/eks.yaml.txt)

**Comment by grb123** [comment]
Update: so i AutoScaled down all Worker Nodes to zero, then tried to 'manually' create a NodeGroup in AWS EKS Console but it fails. On EKS Console to create a NodeGroup, selected the (only) 'Node IAM Role'  available in dropdown, the eksctl generated one (eksctl-eks-course-cluster-nodegro-NodeInstanceRole-15FV82TMLSW29 here) but upon [Create] a console error is displayed
"Launch template eksctl-eks-course-cluster-nodegroup-ng-1 should not specify an instance profile. The noderole in your request will be used to construct an instance profile." 

Hmmm, now am confused (how should this work) :>?

**Comment by grb123** [comment]
=>eksctl version                               
0.55.0

**Comment by grb123** [comment]
Have confirmed eksctl v0.54.0 does work as advertised... possible Regression issue on v0.55.0 ??

with eksctl v0.54.0 (OK)
=>kubectl get nodes
NAME                                           STATUS    ROLES     AGE       VERSION
ip-nnn-nnn-n-nnn.eu-west-2.compute.internal    Ready     <none>    4m        v1.19.6-eks-49a6c0
ip-nnn-nnn-nn-nnn.eu-west-2.compute.internal   Ready     <none>    4m        v1.19.6-eks-49a6c0
ip-nnn-nnn-nn-nnn.eu-west-2.compute.internal   Ready     <none>    4m        v1.19.6-eks-49a6c0

**Comment by nikimanoledaki** [comment]
Hi @grb123, thank you for opening this issue! Could you provide a bit more info such as: 
- the steps to reproduce this bug
- the full logs when you encounter this issue with `-v 4` for verbosity
- the output of `kubectl version`
Any other helpful info/context would be great too. Thank you!

**Comment by grb123** [comment]
H

**Comment by cPu1** [comment]
I was unable to reproduce the issue in eksctl v0.55 with your attached config file. The cluster and nodegroup creation succeeds and I can view the nodes in `kubectl get nodes`.

**Comment by cPu1** [comment]
I can deduce from the error message that the `aws-auth` `ConfigMap` fetch failed due to a temporary hostname resolution error and that caused the nodegroups to not join the cluster. If you try recreating your cluster using eksctl v0.55, it should work.

**Comment by grb123** [comment]
Hiya, yep that's what I say to any intermediate failures as well,  "you should just work" :@P 
Seriously though, do we have any insight into...
 1. how to better capture and report the (timing out?) nature of any (dns or config map look-up?) connectivity failures in this intermittent scenario ? 
 2. how the workflow process could be improved to reduce the frequency of occurrence - in other words, if we clarify the cause, we might better be able to accommodate longer 'intermediate' interruptions in connectivity terms before we arrive at this complete failure outcome ?

I'll rerun on v0.55.0 now and capture output (-v 4) here...

**Comment by gohmc** [comment]
Could be due to t2.small is insufficient. Why not let eksctl provision a Fargate only cluster and start as low as 0.25vCPU/0.5GB.

**Comment by grb123** [comment]
Ah yep that makes sense - this activity is on a Course, currently Chapter 4, hehehe i see Fargate on EKS is Chapter13  :@P

**Comment by nikimanoledaki** [comment]
> Hmm I guess the question becomes whether or not this AWS EC2 t2.small config has resources to _consistently & reliably_ spin-up basic cluster using latest EKS builds (v0.55.0) ?

The NodeGroup size being t2.small shouldn't affect eksctl's ability to fetch the ConfigMap since that comes from the control plane, not the NodeGroup.

**Comment by grb123** [comment]
Yep, I recall this failed create cluster ran for ~25 mins + before it failed, maybe somewhere there had to resource contention, or another cause for this apparently excessive delay (an API timeout on Control Plane side>?) on this ConfigMap lookup ? Was the very first time i ran eksctl to AWS too... think need to get into habit of including v -4 on eksctl logging to capture a clearer picture !

**Comment by nikimanoledaki** [comment]
I see, yeah `-v 4` should help with logging more info about the process and debugging any potential disruption in the future!

Another thing to keep in mind is that the default timeout duration for eksctl cluster creation is 25 minutes and can be changed with `--timeout`.

It seems to me like this issue can be closed for now. If you have any other queries, feel free to open another issue or slack us at https://slack.weave.works/
