### ISSUE TITLE
"The maximum number of rules per security group has been reached"

### ISSUE THREAD

**Issue by InvisibleMan1306** [weaveworks/eksctl#3974]
When running eksctl I hit the error "The maximum number of rules per security group has been reached". This is happening since I reached the AWS limit for the number of ingress rules for my ControlPlaneSecurityGroup. I don't believe this is a bug since I just have a lot of node groups in my workflow.

**What help do you need?**
I know that I can increase the capacity of the number of ingress rules for my AWS account but I was hoping there was another workaround you can suggest. For example, I would be perfectly happy to have all my node groups use the same security group and make a single ingress into the ControlPlaneSecurityGroup.

**Comment by InvisibleMan1306** [comment]
@Callisto13 who might be the right person to reach out about this issue?

**Comment by cPu1** [comment]
@InvisibleMan1306 are you using unmanaged/self-managed nodegroups (`nodeGroups` field in ClusterConfig)? Managed Nodegroups now have almost complete feature parity with unmanaged nodegroups, so the workaround right now would be start using managed nodegroups as that doesn't create an ingress rule in the cluster's security group.

**Comment by InvisibleMan1306** [comment]
Thank you that was very helpful. I think that might resolve this issue.
