### ISSUE TITLE
Add --approve flag to eksctl delete cluster

### ISSUE THREAD

**Issue by steffakasid** [weaveworks/eksctl#3977]
**What feature/behavior/change do you want?**

Please provide a --approve flag for `eksctl delete cluster` as it is already done for `eksctl delete nodegroup`.

**Why do you want this feature?**

Otherwise it's to easy to delete a cluster by mistake.

**Comment by cPu1** [comment]
Sounds reasonable to me and it makes the UX consistent. We'll add this to our backlog.

**Comment by Callisto13** [comment]
Just a note that we should be sure to document widely in the release, as we may end up breaking things for people who script cluster deletion.

**Comment by aclevername** [comment]
> Just a note that we should be sure to document widely in the release, as we may end up breaking things for people who script cluster deletion.

yeah this is my biggest concern with this feature :/

**Comment by siddhantmaitra** [comment]
Hi, I am new to open source and  learning Go. Can I try working on this issue? I have read the contributing.md and tried setting up the project locally but getting stuck after running `make build` . I am getting: 
```
make: go-bindata: Command not found
make: *** [Makefile:178: generate-always] Error 127
```
How should I solve this error? I tried googling and decided to install  `go-bindata` with apt, but now I get the error:
```
make build
flag provided but not defined: -v
make: *** [Makefile:178: generate-always] Error 2
```
OS I am using: AntiX-19.4_x64.

**Comment by cPu1** [comment]
> Hi, I am new to open source and learning Go. Can I try working on this issue? I have read the contributing.md and tried setting up the project locally but getting stuck after running `make build` . I am getting:
> 
> ```
> make: go-bindata: Command not found
> make: *** [Makefile:178: generate-always] Error 127
> ```
> 
> How should I solve this error? I tried googling and decided to install `go-bindata` with apt, but now I get the error:
> 
> ```
> make build
> flag provided but not defined: -v
> make: *** [Makefile:178: generate-always] Error 2
> ```
> 
> OS I am using: AntiX-19.4_x64.

You'll have to run `make install-build-deps` before building to install the build dependencies.

**Comment by siddhantmaitra** [comment]
> You'll have to run `make install-build-deps` before building to install the build dependencies.

I did run `make install-build-deps` and then ran `make build`. To recheck, I cloned a fresh repo and retried, the steps, but I am still getting:
```
 make build
make: go-bindata: Command not found
make: *** [Makefile:178: generate-always] Error 127
```

Additionally after running `make install-build-deps`, I tried running  `make test`, I am getting:
```
make test
make lint
make[1]: Entering directory '/home/siddhant/Documents/code/eksctl'
golangci-lint run
make[1]: golangci-lint: Command not found
make[1]: *** [Makefile:92: lint] Error 127
make[1]: Leaving directory '/home/siddhant/Documents/code/eksctl'
make: *** [Makefile:97: test] Error 2
```

**Comment by KR411-prog** [comment]
Is this issue still open? I see a note https://github.com/weaveworks/eksctl/issues/4461 stating that  --approve flag will not be added. If it is still valid case, then can we close this issue?

**Comment by Skarlso** [comment]
@KR411-prog Yep, that's true, sadly.

**Comment by steffakasid** [comment]
#4461 only mentions --approve for nodegroups. This is already there. What I wanted to have is the --approve for delete cluster. If it will not be implemented this issue can be closed!

**Comment by Skarlso** [comment]
Huh, that's a fair point. Maybe there was some kind of mix up while investigating this setting.

**Comment by Skarlso** [comment]
I'm actually reluctant to do this, sorry. It would disrupt sooo many workflows including ours, when deleting clusters in CI and automated test environments. Sorry @steffakasid.
