### ISSUE TITLE
No nodegroups found when 'get nodegroup' for non eksctl-created node group

### ISSUE THREAD

**Issue by imbohyun1** [weaveworks/eksctl#3978]
**What help do you need?**

I have created the cluster and created the self-managed node group via CloudFormation stack. And I tried to retrieve the node group 'self-managed-ng' with eksctl and got the error `Error: No nodegroups found`.

    $ eksctl get nodegroup --cluster non-eksctl-test -v 5
    2021-07-14 23:57:47 [▶]  role ARN for the current session is "arn:aws:iam::XXXXXXXXXX:root"
    2021-07-14 23:57:47 [ℹ]  eksctl version 0.52.0
    2021-07-14 23:57:47 [ℹ]  using region ap-northeast-2 
    2021-07-14 23:57:48 [▶]  No stacks found for non-eksctl-test
    Error: No nodegroups found

I executed the command again, after I created the managed node group 'managed-ng' via EKS console. I was able to see the managed node group at this time. 

    $ eksctl get nodegroup --cluster non-eksctl-test -v 5
    2021-07-15 00:32:46 [▶]  role ARN for the current session is "arn:aws:iam::XXXXXXXXXX:root"
    2021-07-15 00:32:46 [ℹ]  eksctl version 0.52.0
    2021-07-15 00:32:46 [ℹ]  using region ap-northeast-2
    2021-07-15 00:32:46 [▶]  No stacks found for non-eksctl-test
    CLUSTER		NODEGROUP	STATUS	CREATED			MIN SIZE	MAX SIZE	DESIRED CAPACITY	INSTANCE TYPE	IMAGE ID	ASG NAME
    non-eksctl-test	managed-ng	ACTIVE	2021-07-14T14:59:38Z	1		1		1			t3.medium	AL2_x86_64	eks-d2bd52c3-e1c7-64f9-cb7f-cb2587a31c34

I could see only one node group while there were 2 node group in the cluster (1 managed-ng, 1 self-managed ng).
So eksctl doesn't support a non-eksctl-created self managed node group? or should I add some configuration(e.g. tags, labels) to nodegroup for being retrieved by eksctl?

It would be good if there is more clear description for what can it be done for each command on the document (https://eksctl.io/usage/unowned-clusters/ ). It indicates `eksctl get nodegroup` as supported commands, so it looks like I can get all my node groups including a self managed node group which was not created via eksctl.

**Comment by Callisto13** [comment]
🤔  This command should work exactly the same way as it does for nodegroups which _were_ created by eksctl: this is why the docs don't elaborate, since everything should be the same with no special behaviour. We have integration tests which verify this.

Could you confirm for me how you created things:
1. What you used/ran to create the cluster
2. What you used/ran to create the nodegroup

Thanks!

**Comment by imbohyun1** [comment]
@Callisto13 
>     1. What you used/ran to create the cluster
>     2. What you used/ran to create the nodegroup

I have created the cluster via AWS EKS console, and created the self-managed nodegroup via Cloudformation stack (followed the official document: https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html)

Actually one of my customer experienced this issue and I was easily able to replicate it.

**Comment by Callisto13** [comment]
Okay cool, I have a vague suspicion about what is going on, I will see if I can reproduce.

With clusters which are not created by `eksctl` we look for certain markers which let us guess whether the cluster or nodegroups are "owned" by `eksctl` or not. Of course users can create these things however they want, so we have to be quite broad. I would guess that this combination of console+CF has found a gap, but I will confirm once I have spun some things up.

**Comment by aclevername** [comment]
> Okay cool, I have a vague suspicion about what is going on, I will see if I can reproduce.
> 
> With clusters which are not created by `eksctl` we look for certain markers which let us guess whether the cluster or nodegroups are "owned" by `eksctl` or not. Of course users can create these things however they want, so we have to be quite broad. I would guess that this combination of console+CF has found a gap, but I will confirm once I have spun some things up.

This is correct. Eksctl will only present two types of nodegroups:
- EKS managed nodegroups
- Unmanaged nodegroups created via eksctl.

I think this behaviour is desired, as anything outside of these two nodegroup types would be hard for eksctl to detect/interpret
