### ISSUE TITLE
Document Minimal required IAM Policies for EKS Cluster Creation Upfront

### ISSUE THREAD

**Issue by orsenthil** [weaveworks/eksctl#4000]
**What were you trying to accomplish?**

I tried to follow the README.md to create a EKS cluster and I was constantly running into lack of permissions starting with 

> arn:aws:iam::account-id:user/senthil is not authorized to perform: ssm:GetParameter on resource:

And more such permissions issues.  

I realized that [Minimum IAM Policies](https://eksctl.io/usage/minimum-iam-policies/) were documented recently https://github.com/weaveworks/eksctl/pull/2267 but it should be mentioned upfront in the README.md document, so that instructions can be followed without any assumptions or troubleshooting.

**What happened?**

Unable to create a EKS Cluster, ran into permission issues, like

> arn:aws:iam::account-id:user/senthil is not authorized to perform: ssm:GetParameter on resource:

**How to reproduce it?**

1. Create a new Amazon AWS Account.
2. Create a IAM User.
3. Try to follow README.md instructions to create the EKS Cluster.
4. 
**Logs**

**Anything else we need to know?**

**Versions**

```
[~/git/eksctl]$ eksctl info
eksctl version: 0.56.0
kubectl version: v1.21.2
OS: darwin
```

**Comment by nikimanoledaki** [comment]
Hi @orsenthil, closing this issue since it has been addressed by #4001. Thank you for contributing! 🙌
