### ISSUE TITLE
Support Amazon Kubernetes 1.21

### ISSUE THREAD

**Issue by orsenthil** [weaveworks/eksctl#4002]
**What feature/behavior/change do you want?**
Add support for Kubernetes 1.21

**Why do you want this feature?**

Amazon EKS supports Kubernetes 1.21 now - https://aws.amazon.com/blogs/containers/amazon-eks-1-21-released/ 

But when I tried to get 1.21 cluster, it was not supported with eksctl yet

Error: invalid version, supported values: 1.16, 1.17, 1.18, 1.19, 1.20

**Comment by orsenthil** [comment]
cc: @rothgar

**Comment by aclevername** [comment]
We shipped support earlier this week, have you tried with the latest version?

https://github.com/weaveworks/eksctl/releases/tag/0.58.0-rc.0

**Comment by orsenthil** [comment]
Thank you. I will try it. I didn't try the recent tagged RC from yesterday. This might not be a bug.

**Comment by rothgar** [comment]
I ran a basic cluster creation command it it worked for me. :+1: 

```bash
eksctl create cluster --version 1.21 --managed 
```

**Comment by orsenthil** [comment]
I was able to deploy k8s version 1.21 with the binary from master

```$ ./eksctl create cluster -f ~/eksctl-containerd.yaml
2021-07-21 16:38:19 [ℹ]  eksctl version 0.59.0-dev+4ec09aca.2021-07-21T16:36:41Z
...
2021-07-21 16:38:21 [ℹ]  using Kubernetes version 1.21
```
I will close this ticket. 

--- 

Is it worth giving a option to build eksctl using `make binary` method? The README.md list many options, but build from source was not, and perhaps that led to this mistake.

**Comment by aclevername** [comment]
> I was able to deploy k8s version 1.21 with the binary from master
> 
> ```
> 2021-07-21 16:38:19 [ℹ]  eksctl version 0.59.0-dev+4ec09aca.2021-07-21T16:36:41Z
> ...
> 2021-07-21 16:38:21 [ℹ]  using Kubernetes version 1.21
> ```
> 
> I will close this ticket.
> 
> Is it worth giving a option to build eksctl using `make binary` method? The README.md list many options, but build from source was not, and perhaps that led to this mistake.

We generally don't recommend manually building the binary but instead downloading the latest relase. However we do document how to build the binary via `make build` in the contributing guide https://github.com/weaveworks/eksctl/blob/main/CONTRIBUTING.md#building-eksctl
