### ISSUE TITLE
certificate signed by unknown authority from cloudformation/ListStacks

### ISSUE THREAD

**Issue by ifelsefi** [weaveworks/eksctl#4019]
Hi

I have MITM firewall in between my laptop and AWS.  I am not able to run eksctl:

```
[~]$ eksctl get cluster
2021-07-23 15:01:17 [ℹ]  eksctl version 0.58.0
2021-07-23 15:01:17 [ℹ]  using region us-east-2
2021-07-23 15:01:17 [!]  retryable error (RequestError: send request failed
caused by: Post "https://cloudformation.us-east-2.amazonaws.com/": x509: certificate signed by unknown authority) from cloudformation/ListStacks - will retry after delay of 47.3015ms
```

With aws cli v2 I am able to get around this using `export AWS_CA_BUNDLE=/path/to/self_signed_fw_cert`.  I have the certificate installed in my OSX trusted keystore but eksctl does not care.  

Does eksctl have a variable to use this self-signed certificate as aws permits?   I also tried `export KUBECONFIG_USE_SYSTEM_CA=true` which does not help.

Thanks,
Doug

**Comment by cPu1** [comment]
eksctl uses the AWS SDK, which does honour the `AWS_CA_BUNDLE` environment variable to specify a custom CA bundle for TLS requests. Can you ensure this env var is being set for `eksctl get cluster`? If it's still not working, can you rerun the command with verbose logging enabled (passing `-v5`) and share the logs, redacting any sensitive information?

**Comment by ifelsefi** [comment]
User error.
