### ISSUE TITLE
[Improvement] Use new Cloudformation support for cluster logging, tagging, endpoint access control, public access CIDRs

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#4027]
**What feature/behavior/change do you want?**
Currently eksctl hit the EKS API directly for managing cluster logging, tagging and endpoint access control. This is because Cloudformation doesn't support configuring this, until now. EKS have started adding support for it https://github.com/aws/containers-roadmap/issues/506 https://github.com/aws/containers-roadmap/issues/242 . Once support is released lets change our `eksctl create cluster` code to use this instead, reducing the number of API calls we make :smile: 

**Why do you want this feature?**
Less API calls, less code!

**Comment by cPu1** [comment]
Not stale, this feature will be out soon.

**Comment by Himangini** [comment]
Need updating current tests as well

**Comment by cPu1** [comment]
In addition to these features, public access CIDRs is now also supported in CloudFormation. I have updated the title to reflect that.
