### ISSUE TITLE
Possibility to set preBootstrapCommands when using custom ami with managed nodegroups

### ISSUE THREAD

**Issue by kishoregv** [weaveworks/eksctl#4032]
**What feature/behavior/change do you want?**

When pinning AMI for a managed nodegroup, currently eksctl ignores preBootstrapCommands. It would nice to have preBoostrapCommands.

AWS [blog](https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/) talks about the workflow with eksctl, but eksctl does not respect preBootstrapCommands when using custom AMI.

![image](https://user-images.githubusercontent.com/1823272/127633255-bc580729-da78-4214-adb4-3c7c2399889e.png)

**Why do you want this feature?**

This will allow us to do additional configuration before bootstrapping.

**Comment by niroowns** [comment]
Is this a bug? eksctl docs/examples state this is possible:

https://github.com/weaveworks/eksctl/blob/51b66753f000e0c6881c0883b55524ab27d09754/examples/05-advanced-nodegroups.yaml#L64

https://eksctl.io/usage/schema/#managedNodeGroups-preBootstrapCommands

**Comment by tanvp112** [comment]
the example from aws blog is not valid; overrideBootstrapCommand is not a sub-key of preBootstrapCommands.

**Comment by cPu1** [comment]
> Is this a bug? eksctl docs/examples state this is possible:
> 
> https://github.com/weaveworks/eksctl/blob/51b66753f000e0c6881c0883b55524ab27d09754/examples/15-managed-nodes.yaml#L47
> 
> https://eksctl.io/usage/schema/#managedNodeGroups-preBootstrapCommands
> 
> Tracking the code base, it appears that makeCustomAMIUserData (https://github.com/weaveworks/eksctl/blob/main/pkg/nodebootstrap/managed_al2.go#L38) only respects the OverrideBootstrapCommand function (not preBootstrap):
> https://github.com/weaveworks/eksctl/blob/main/pkg/nodebootstrap/managed_al2.go#L86-L90

You're right, `preBootstrapCommands` is being ignored when a custom AMI is supplied. This is a bug and we're going to look into it. 

@kishoregv, additionally, as @tanvp112 noted, the example in the AWS blog post is incorrect, `overrideBootstrapCommand` is a top-level field of nodegroup.

**Comment by kishoregv** [comment]
> @kishoregv, additionally, as @tanvp112 noted, the example in the AWS blog post is incorrect, overrideBootstrapCommand is a top-level field of nodegroup.

Agree, did not go with it literally I have considered the indentation issue in my test. I should have already called it out in my issue report.
Thanks
