### ISSUE TITLE
eksctl AMI autoresolver error: Error: invalid AMI "auto" (managedNodeGroups[0].ami)

### ISSUE THREAD

**Issue by Thomas999999** [weaveworks/eksctl#4039]
Hi,

created cluster since years with --node-ami auto like this:
_eksctl create cluster --name eks120 --region eu-west-1 --tags "instance_group_01=data_intelligence,pqp_testnumber=eks120,shutdown_status=true,sec-by-def-network-exception=SSH" --version 1.20 --nodegroup-name workers --node-type m4.4xlarge --nodes 4 --nodes-min 0 --nodes-max 10 --ssh-access --asg-access --node-volume-size 128 --node-volume-type gp2 --vpc-public-subnets subnet-0d64ed5c0e6008c70,subnet-0249675a88d9c714b --ssh-public-key SLV_keypair_IRE --node-ami-family AmazonLinux2 **--node-ami auto** --auto-kubeconfig_

But now getting the following error:
Error: invalid AMI "auto" (managedNodeGroups[0].ami)

[root@ip-192-168-11-17 ~]# eksctl version
0.59.0

Has something changed here?
Currently we cannot create clusters in our environment.

Thanks,
Thomas

**Comment by cPu1** [comment]
Hi @Thomas999999, eksctl, as of 0.58, [creates managed nodegroups when a config file isn't specified](https://eksctl.io/usage/managed-nodegroups-announcement/). Managed nodegroups do not support setting `--node-ami` to `auto` because that's the default behaviour. To fix this, you can remove the `node-ami` option or pass `--managed=false` to use unmanaged nodegroups.

**Comment by Thomas999999** [comment]
Thanks :-)

I only checked https://eksctl.io/usage/custom-ami-support/ and there was no mentioning that since 0.58 node-ami auto must not be set in specific cases...maybe you can add this ?...but I'm fine now and you may also close this ticket, Thanks ! :-)

**Comment by cPu1** [comment]
> Thanks :-)
> 
> I only checked https://eksctl.io/usage/custom-ami-support/ and there was no mentioning that since 0.58 node-ami auto must not be set in specific cases...maybe you can add this ?...but I'm fine now and you may also close this ticket, Thanks ! :-)

Good point, noted!
