### ISSUE TITLE
Support IP address prefixes from vpc-cni 1.9.0

### ISSUE THREAD

**Issue by aidan-mundy** [weaveworks/eksctl#4048]
**What feature/behavior/change do you want?**
As of vpc-cni version 1.9.0, EKS now supports much larger pod capacities per node with some additional configuration. The documentation for this new functionality is [here](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html). It would be extremely helpful to have support for this functionality natively in eksctl. Some entries will be needed in the schema, a change to cluster creation will be required (and a potentially a new command for enabling this feature in existing clusters), and some additional logic will be needed to detect which node groups can support the higher pod counts as this only works on nitro instances running AL2. I would suggest that enabling the feature should also automatically determine the correct number of pods per node using the new logic present in that documentation. 

**Why do you want this feature?**
The additional pods per node afforded by this update enable more dense packing on each node. Nodes like t3.micro that could previously only support 4 pods can now support 34. (an 8 fold increase!) This is a massive improvement to the capabilities of EKS and makes the price/performance much more competitive with the other cloud providers offering managed Kubernetes. It is inconvenient (albeit not really a big deal) to take the extra steps of running the additional commands needed to enable the feature, and it would be nice to have it all wrapped into eksctl. 

I am extremely busy with work at the moment, but I may take a look at implementing this if no one else is able to pick it up.

**Comment by Callisto13** [comment]
Thanks for this request @aidan-mundy 👍 

Definitely looks cool, the team will discuss how best to implement. Likely the first step would be a proposal, and if you do find time please feel free to get started on that 😄

**Comment by aidan-mundy** [comment]
Haven't had time for a proposal yet, but this definitely should not be closed.

**Comment by aidan-mundy** [comment]
😒 Is there any way to keep the stale bot from popping up? This is a legit feature that shouldn't be hidden whether or not there is constant discussion about it.

**Comment by Himangini** [comment]
Added a spike to determine the work needed.

**Comment by Skarlso** [comment]
@aidan-mundy Just to clarify. We can't do anything until a Go SDK issue is solved. This one: https://github.com/aws/aws-sdk-go/issues/4159

Until that is done, `eksctl` can't pass anything to vpc-cni. :/

**Comment by dougbyrne** [comment]
The [AWS docs you linked](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html) show that the ENV vars are set with kubectl, not an AWS API. Is it an SDK issue if the API doesn't exist?

**Comment by Skarlso** [comment]
To clarify, we can't pass in any kind of environment property from our side. It is an SDK issue as in if the ability would ever exist, then the SDK needs to expose it and THEN we can do something from eksctl's side.

**Comment by Skarlso** [comment]
Oh my Gods. Actually, I think we can do this.

**Comment by Skarlso** [comment]
Okay, sorry folks, I think we might be able to pull this off. We do have some code we use to patch `aws-node` already. We can update that patch to add the Environment property here: https://github.com/weaveworks/eksctl/blob/main/pkg/actions/addon/create.go#L156

**Comment by Skarlso** [comment]
Ahh no :( That just gets reverted anyways once the addon is installed. :((( Sorry. :((

**Comment by dougbyrne** [comment]
Yeah, if you do a `forced` install/update of the plugin, the config will be reset. If you were to apply the patch after the plugin action is done, it should stick. The plugin actions are async, so you'd need some kind of waiter. I'm doing these actions manually currently.

The other part of this is the increased pod counts. Even if the config isn't managed by eksctl, it would be nice to have the config detected and have the appropriate pod count limit set.

**Comment by Himangini** [comment]
> @aidan-mundy Just to clarify. We can't do anything until a Go SDK issue is solved. This one: [aws/aws-sdk#286](https://github.com/aws/aws-sdk/issues/286)
> 
> Until that is done, `eksctl` can't pass anything to vpc-cni. :/

AWS made a decision [here](https://github.com/aws/aws-sdk/issues/286#issuecomment-1221157480) not supporting this. Closing this issue since we rely upon upstream support to deliver this.
