### ISSUE TITLE
Node Groups should not label their security groups with kubernetes.io/cluster/$name

### ISSUE THREAD

**Issue by ellistarn** [weaveworks/eksctl#4054]
**What were you trying to accomplish?**
I'm trying to integrate EKSCTL Clusters, NLB Controller, and Karpenter.

**What happened?**

I discovered recently that eksctl creates a security group with the tag `kubernetes.io/cluster/$cluster-name` for node groups (note, this doesn't happen for managed node groups). This is in addition to the security group created by the EKS CreateCluster API, which also uses this tag. My understanding is that semantically, any security group with this tag will allow nodes to communicate with the API Server. 

However, this results in multiple security groups having this tag. The NLB controller requires that nodes only have 1 security group. Karpenter discovers security groups that have this tag, and launches instances with these security groups. This creates a combined effect where Karpenter doesn't work with NLB and EKS CTL node groups.

**How to reproduce it?**

```
eksctl create cluster \
--name ${CLUSTER_NAME} \
--version 1.18 \
--region ${AWS_DEFAULT_REGION} \
--node-type m5.large \
--nodes 1 \
--nodes-min 1 \
--nodes-max 10
```
**Logs**

```
{"level":"error","ts":1628025858.7978263,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-kit-examplea-fefdbc8d8f","namespace":"kit","error":"expect exactly one securityGroup tagged with kubernetes.io/cluster/kit-management-cluster for eni eni-05c4b5d8deba8abe8, got: [sg-07dd7b7bd52a6911f sg-0dd66a817537d3411]"}
```

**Anything else we need to know?**

I think the right path forward is to remove this security group (or at least the tag) for eksctl node groups. Instead, we should use the security group created by EKS to communicate with the masters. What are your thoughts?

**Versions**

```
$ eksctl info
```

**Comment by ellistarn** [comment]
Discussed with @cPu1 over slack.

**Comment by cPu1** [comment]
I can confirm that eksctl creates a security group tagged with `kubernetes.io/cluster/$cluster-name` for unmanaged nodegroups. We're spread thin right now but this will be next on our list. Thanks for opening an issue, Ellis.

**Comment by tanvp112** [comment]
@cPu1, is there a fix (use only the security group created by EKS) for this anytime soon? This flaw is causing issue in the cluster.

**Comment by Skarlso** [comment]
@tanvp112 sorry for the wait, I'll look into this next thing tomorrow. :)

**Comment by tanvp112** [comment]
Hi @Skarlso, thanks and any update on this?

**Comment by cPu1** [comment]
> Hi @Skarlso, thanks and any update on this?

Hi @tanvp112, we've added this to our backlog and will start working on it soon.

**Comment by cPu1** [comment]
>However, this results in multiple security groups having this tag.

eksctl does attach two security groups to unmanaged nodegroups, however, only one of them has the `kubernetes.io/cluster/$cluster-name` tag. Unmanaged nodegroups do not use the default SG created by EKS for backwards compatibility reasons.

**Comment by cPu1** [comment]
> @cPu1, is there a fix (use only the security group created by EKS) for this anytime soon? This flaw is causing issue in the cluster.

Are you facing issues with the NLB? Can you elaborate what issues you are facing? Are you also using Karpenter?

**Comment by ellistarn** [comment]
I just synced up with the NLB folks. We agreed that eksctl should not be creating additional security groups for self-managed node groups, and instead rely on the one that is created for control plane communication. 

NLB Controller is looking into relaxing the single-security group requirement, but in the mean time, we should get this fixed in eksctl ASAP.

**Comment by Skarlso** [comment]
Hey @ellistarn.

Something that Chetan brought up, did you saw this: I created a cluster with two nodegroups as well, but I only seen one SG with this label. 

I used the above command that you provided but can only see the `owned` tag on ONE of the sgs.

**Comment by Skarlso** [comment]
Going to need some extra information on your environment and setup.

**Comment by cPu1** [comment]
> I just synced up with the NLB folks. We agreed that eksctl should not be creating additional security groups for self-managed node groups, and instead rely on the one that is created for control plane communication.
> 
> NLB Controller is [looking into](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2367) relaxing the single-security group requirement, but in the mean time, we should get this fixed in eksctl ASAP.

This issue is more related to integrating Karpenter with eksctl. In a standard eksctl cluster with both self-managed and managed nodegroups, the NLB controller works fine as the instances provisioned by eksctl have only one security group with the `kubernetes.io/cluster/<cluster_name>` tag. The issue with the NLB controller occurs when Karpenter provisions instances by attaching multiple security groups that have the same `kubernetes.io/cluster/<cluster_name>` tag. This is due to how Karpenter discovers security groups to attach by looking up SGs in the VPC that have the cluster tag. In an eksctl-created cluster that has self-managed nodegroups, this can result in Karpenter-provisioned instances to have multiple SGs.

**Comment by cPu1** [comment]
To elaborate more on why we can't make this change right away. Today, eksctl provides two fields for self-managed nodegroups `securityGroups.withLocal` and `securityGroups.withShared` to configure attaching security groups.
1. `withLocal` attaches a nodegroup-local SG that has the cluster tag and is allow-listed by the control plane SG.
1. `withShared` attaches a shared SG that allows ingress traffic from nodes having that SG. 

Both fields are enabled by default, allowing nodes in different nodegroups to communicate with each other.

eksctl also lets you disable attaching a shared SG (`withShared: false`), which allows creating nodes that are isolated from nodes in other nodegroups, providing a stricter security boundary between workloads in different nodegroups. To allow Karpenter to discover only one SG with the cluster tag, we'd have to skip creation of the nodegroup-local SG (that has the cluster tag) and attach the default EKS security group to all nodegroups. This would break the existing behaviour for `withShared: false` as now nodes in different nodegroups will be able to communicate with each other.

**Comment by cPu1** [comment]
Since making this change would break nodegroup isolation, we decided not to go ahead with this breaking change that has security implications. We might revisit or approach it differently later if we find that the current SG tagging behaviour needs to be changed.

**Comment by ricardorqr** [comment]
Any update on this problem?
