### ISSUE TITLE
Add NAT IP note to "Use private subnets for initial nodegroup"

### ISSUE THREAD

**Issue by peterfication** [weaveworks/eksctl#4066]
In the [VPC networking guide in section "Use private subnets for initial nodegroup"](https://eksctl.io/usage/vpc-networking/#use-private-subnets-for-initial-nodegroup), it doesn't mention anything about which external IPs will be used.

Having a note there like

> This will also result in egress/outgoing traffic to go through the NAT and using the Elastic IP of the NAT instead of the IP of each individual node.

would have helped me. I found it out eventually but I think the docs don't mention anything about it.

wdyt?

**Comment by Callisto13** [comment]
Sounds reasonable to me 👍  good spot. 

If you'd like to submit a PR go for it, otherwise the team will schedule it for work 😄

**Comment by peterfication** [comment]
I submitted a PR 👍
