### ISSUE TITLE
kube-proxy update fails on eks with 1.20 / eksctl 0.60.0 in eu-central-1

### ISSUE THREAD

**Issue by steveizzle** [weaveworks/eksctl#4078]
**What were you trying to accomplish?**
Update kube-proxy on an eks cluster with k8s 1.20 (platform version independent, was tested with eks.1 and eks.2) in eu-central-1

**What happened?**
Kube-proxy pods fails to pull image 602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.20.7-eksbuild.2

**How to reproduce it?**
eksctl utils update-kube-proxy --cluster eks-test --approve

**Logs**

```
Normal   Pulling    16s (x3 over 55s)  kubelet            Pulling image "602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.20.7-eksbuild.2"
  Warning  Failed     16s (x3 over 55s)  kubelet            Failed to pull image "602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.20.7-eksbuild.2": rpc error: code = Unknown desc = Error response from daemon: manifest for 602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.20.7-eksbuild.2 not found: manifest unknown: Requested image not found
  Warning  Failed     16s (x3 over 55s)  kubelet            Error: ErrImagePull
  Normal   BackOff    3s (x3 over 55s)   kubelet            Back-off pulling image "602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.20.7-eksbuild.2"
  Warning  Failed     3s (x3 over 55s)   kubelet            Error: ImagePullBackOf
```

**Anything else we need to know?**
darwin / installation over brew

After Downgrading to 0.59.0 kube-proxy updates are working with `602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.20.7-eksbuild.1`

**Versions**
eksctl version: 0.60.0
kubectl version: v1.21.0
OS: darwin

**Comment by Callisto13** [comment]
👍 thanks for reporting @steveizzle

**Comment by aclevername** [comment]
I managed to reproduce this on `1.20`. Using `eksbuild.2` is what caused the problem, using `eksbuild.1` resolved it.
