### ISSUE TITLE
Remove deprecated `update cluster stack` command

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#4079]
```
eksctl utils update-cluster-stack            DEPRECATED: Use 'eksctl update cluster' instead
```

This has been marked as deprecated for a while, probably we can kill it now

**Comment by nickmancari** [comment]
I would like to take a crack at this if possible. It'd be my pleasure to contribute.

**Comment by Callisto13** [comment]
🙌  awesome! It's all yours, let us know if you need any help 🚀

**Comment by nickmancari** [comment]
I have submitted the PR but I am unable to add a label to it.
