### ISSUE TITLE
kube-proxy addon breaks prometheus metrics.

### ISSUE THREAD

**Issue by andrew-pickin-epi** [weaveworks/eksctl#4081]
Using eksctl kube-proxy addon sets `config.metricsBindAddress: 127.0.0.1:10249` in `kube-proxy-config` `configMap`.

Prometheus is the de facto standard for monitoring kubernetes and requires this setting to be `0.0.0.0:<port>`.

There is no way to alter this permanently. 

It is possible that this change may be applied and the consequences not seen for some time as the problem only manifests on kube-proxy pods restarting. So it is possible, as happened with us, that upgrade appears fine on test cluster only to break later on production, 

There is on way to remove this addon that does not cause downtime, and significant remedial action.

--
This is really pretty bad, as this is the accepted way to upgrade a production eks cluster, it breaks stuff and there is no way to safely roll it back. 

Either provide a way of being able to safely change configuration, or provide a workable default.

**Comment by aclevername** [comment]
Thanks for opening the issue @andrew-pickin-epi

Are you using the EKS addons `eksctl create/get/delete addons` or the legacy addons `eksctl utils update-kube-proxy`? See https://github.com/weaveworks/eksctl/issues/4080
 
Whats preventing you from being able to safely change the configuration yourself manually?

**Comment by andrew-pickin-epi** [comment]
> Thanks for opening the issue @andrew-pickin-epi
> 
> Are you using the EKS addons `eksctl create/get/delete addons` or the legacy addons `eksctl utils update-kube-proxy`? See #4080

This issue relates to new addons. 

> Whats preventing you from being able to safely change the configuration yourself manually?

Changing the value (even with `--server-side`) only changes the value briefly. After a few minutes the value is reset. Subsequent kube-proxy restart pod are thus broken

**Comment by artem-nefedov** [comment]
We've encountered this as well.
I would also love to have a way to expose kube-proxy metrics, but it looks like this is a limitation of EKS addons themselves, and eksctl probably can't do anything about it.

**Comment by aclevername** [comment]
EKS addons are releasing a feature soon to allow you to disable the EKS management of the addon after installing it, specifically to allow you to modify the addon as you see fit. See https://github.com/weaveworks/eksctl/issues/3998

Would that resolve your issue?

**Comment by andrew-pickin-epi** [comment]
We were previously using `eksctl utils update-kube-proxy` (and coredns) to successfully mange the update. 
Moving to the new addon if fine if it just manages the image update, but we desire fine grain controller of these components' settings. 

I don't see how disabling the addon helps - other that it would have given us an option to revert a broken cluster.

What do we use to update the kube-proxy when upgrading kubernetes version?  AWS's documentation suggest to use eksctl addons but this breaks one's configuraiton. In the general case there needs to be a way of saying "don't manage this setting", in the specific case - acknowledge that the world uses prometheus and put in a sensible default for this particular value.

**Comment by aclevername** [comment]
> I don't see how disabling the addon helps - other that it would have given us an option to revert a broken cluster.

This isn't to `disable` (I read that as delete) an addon, its to disable EKS from actively managing the addon

> In the general case there needs to be a way of saying "don't manage this setting", in the specific case - acknowledge that the world uses prometheus and put in a sensible default for this particular value.

This is what it achieves AFAIK.

> What do we use to update the kube-proxy when upgrading kubernetes version? AWS's documentation suggest to use eksctl addons but this breaks one's configuraiton. 

This is less clear to me, I don't know how EKS expect you to update an addon after you've disabled the EKS management of the addon. Worth asking in https://github.com/aws/containers-roadmap/issues/1415

**Comment by andrew-pickin-epi** [comment]
#3998 appears to just be a way of moving to "self-managed" once you're have been using the addon. 
Great this gives us a way of fixing our broken clusters! 
It's "delete but keep my pods and settings" - which it should be doing when you delete. I have no idea what use-case the current `delete addon` is satisfying! Other than leaving one's cluster fubar.

However, this makes the whole `eksctl addon` move to be a retrograde step.
Previoulsy `eksctl utils` give me a way of managing the upgrade process without having to fully manage myself.
I didn't need to worry (too much) about what image each bit needed in a new release. I could write SOP that looked much the same every upgrade. Life was good. With fully self-managed I have to do a lot more work in managing an upgrade, it's more work and probably needs the attention of more, and more senior engineers.

But this is probaly beside the point. Please someone fix the default for this one setting.

**Comment by aclevername** [comment]
> But this is probaly beside the point. Please someone fix the default for this one setting.

Unfortunately this is out of our control, I'd recommend giving the feedback to the AWS directly so they can pass it on to the EKS Addons team
