### ISSUE TITLE
Can't access the slack group

### ISSUE THREAD

**Issue by smeyerhot** [weaveworks/eksctl#4097]
**What help do you need?**

I am unable to access the slack group

**Comment by aclevername** [comment]
Hi @smeyerhot, could you expand a bit more on the problem your having?

**Comment by gaetansnl** [comment]
@aclevername I think we have the same issue, we get blank page when we try to join the slack group
![image](https://user-images.githubusercontent.com/8348807/129606862-1694c90e-988c-445f-8fa8-3e5855e5c060.png)
![image](https://user-images.githubusercontent.com/8348807/129606975-ec8b95bc-d793-40fb-828b-700dfdb32638.png)

**Comment by cPu1** [comment]
@smeyerhot, are you using the correct URL? The Weave Users community Slack URL is https://weave-community.slack.com.

@gaetansnl, what happens when you click on the <kbd>Login here</kbd> link?

**Comment by gaetansnl** [comment]
@cPu1 I get slack login screen but can't register or get an invite

**Comment by Callisto13** [comment]
Are people still experiencing this problem? I just tried both URLs mentioned in this thread and it seems to be fine:

https://slack.weave.works/
![Screenshot 2021-08-19 at 09 40 34](https://user-images.githubusercontent.com/8898786/130037395-957f0be2-cdd2-4835-b712-58cacc8b5021.png)


https://weave-community.slack.com/
![Screenshot 2021-08-19 at 09 40 44](https://user-images.githubusercontent.com/8898786/130037417-7574218e-efe3-4d90-86dc-845c2ff61e48.png)

**Comment by gaetansnl** [comment]
@Callisto13 It works thanks !
