### ISSUE TITLE
How do I set up kubeReserve in a managed nodegroup?

### ISSUE THREAD

**Issue by cw-sakamoto** [weaveworks/eksctl#4102]
**What help do you need?**

In managed nodegroup, kubeletExtraConfig is not available and kubeReserve cannot be configured(https://eksctl.io/usage/eks-managed-nodes/).

Therefore, I tried to rewrite kubelet config in prebootstrap as shown below, but it seems to be overwritten by the process after `prebootstrap`.

```
  - 'cat /etc/kubernetes/kubelet/kubelet-config.json | jq ".kubeReserved.cpu |= \"300m\"" | jq ".kubeReserved.\"ephemeral-storage\" |= \"2Gi\"" | jq ".kubeReserved.memory |= \"1024Mi\"" | jq ". |= .+ {\"allowedUnsafeSysctls\": [\"net.core.somaxconn\",\"net.ipv4.tcp_tw_reuse\",\"net.ipv4.ip_local_port_range\",\"net.ipv4.tcp_max_syn_backlog\",\"net.ipv4.tcp_fin_timeout\"]}" > /tmp/kubelet-config.json'
  - 'mv /tmp/kubelet-config.json /etc/kubernetes/kubelet/kubelet-config.json'
```

I don't want to use overridebootsrap in managed nodegroup as much as possible, is there any way to configure it other than overridebootstrap?

**Comment by gohmc** [comment]
Is there any way to guaranteed `jq` will always be available? Otherwise `overrideBootstrapCommand` is the best bet to extend kubelet-extra-args.

If you are using custom AMI, there's on-going effort to correct a bug [here](https://github.com/weaveworks/eksctl/issues/4032).

**Comment by cw-sakamoto** [comment]
>Is there any way to guaranteed jq will always be available?

I don't. I think `overridebootstrap` is more reliable for sure.
