### ISSUE TITLE
update addons fails with  Error: creating ChangeSet "updating-policy" AlreadyExistsException

### ISSUE THREAD

**Issue by greenu** [weaveworks/eksctl#4110]
**What were you trying to accomplish?**

Update VPC CNI addon with
eksctl update addon

**What happened?**
Error: creating ChangeSet "updating-policy" for stack "eksctl-mycluster-addon-vpc-cni": AlreadyExistsException: ChangeSet updating-policy cannot be created due to a mismatch with existing attribute Tags

**How to reproduce it?**
Create cluster with addons. Then try to update addons.

`eksctl update addon`
This command succeeds but "eksctl-mycluster-addon-vpc-cni" stack now has failed ChangeSet "updating-policy" with error:
"The submitted information didn't contain changes. Submit different information to create a change set."

All subsequent runs of "eksctl update addon" with SAME eksctl version (nothing to update) succeed, 
but all runs of NEWER eksctl versions (real update) fail with:
`
Error: creating ChangeSet "updating-policy" for stack "eksctl-mycluster-addon-vpc-cni": AlreadyExistsException: ChangeSet updating-policy cannot be created due to a mismatch with existing attribute Tags
`
unless you manually delete failed "updating-policy". 
Update to same version creates failed change set again.

**Anything else we need to know?**
I'm pretty sure it's the same as #3604 but for addons.

**Versions**
eksctl version: 0.58.0
kubectl version: v1.20.4-dirty
OS: darwin

Also reproducible on 0.62.0

**Comment by aclevername** [comment]
Thanks for opening the issue @greenu. your right that it looks very similar to #3604, I think doing the same fix made in https://github.com/weaveworks/eksctl/pull/3605 but for addons should resolve the problem.

**Comment by aclevername** [comment]
Opened a PR to fix https://github.com/weaveworks/eksctl/pull/4116
