### ISSUE TITLE
Not able to run load

### ISSUE THREAD

**Issue by alpana17** [weaveworks/eksctl#4117]
I have a cluster with version 1.21 and 4 nodes
Out of these 4 nodes -- 2 nodes are default one (cordoned these) + 2 nodes are launched with custom AMI
![image](https://user-images.githubusercontent.com/8611615/130333600-ff72f7c1-1644-4eb6-8913-028320c53ad9.png)

I am trying to run httpd with command: 
kubectl run httpd --image=httpd

It gives me following error:
![image](https://user-images.githubusercontent.com/8611615/130333628-9ee99dda-85f8-41e6-8e3f-9a231e61072c.png)

What can be done?

**Comment by gohmc** [comment]
There's breaking change to the generator (except "create"), see [here](https://github.com/kubernetes/kubernetes/pull/87077#issuecomment-627252957) for details. See the example provided to deploy httpd. By the way, this isn't a eksctl issue.

**Comment by Callisto13** [comment]
You may want to try asking in one of the kubernetes github projects or slack groups; as @gohmc says this is not an `eksctl` issue so I am afraid we may not be able to help much.
