### ISSUE TITLE
Creating windows nodegroups in a fully private cluster 

### ISSUE THREAD

**Issue by georgio-sd** [weaveworks/eksctl#4130]
**What were you trying to accomplish?**

Create a windows nodegroup in a fully private cluster (without outbound internet access)

**What happened?**

The nodes fail to join the cluster because the bootstrap script cannot run the Get-EKSCluster command without internet access.

Usermap:
```
<powershell>
[string]$EKSBootstrapScriptFile = "$env:ProgramFiles\Amazon\EKS\Start-EKSBootstrap.ps1"
& $EKSBootstrapScriptFile -EKSClusterName "win" -KubeletExtraArgs "--node-labels=alpha.eksctl.io/cluster-name=win,alpha.eksctl.io/nodegroup-name=windows-ng --register-with-taints=" 3>&1 4>&1 5>&1 6>&1
</powershell>
```

eksctl should use these parameters to pass ClusterCA/APIServerEndpoint and bypass calling "Get-EKSCluster".
```
.PARAMETER APIServerEndpoint
The EKS cluster API Server endpoint(optional). Only valid when used with -Base64ClusterCA. Bypasses calling "Get-EKSCluster".
.PARAMETER Base64ClusterCA
The base64 encoded cluster CA content(optional). Only valid when used with -APIServerEndpoint. Bypasses calling "Get-EKSCluster".
```
The solution would be to extract ClusterCA/APIServerEndpoint on the eksctl side and inject the values into userdata.

**How to reproduce it?**

Create a windows nodegroup in a fully private cluster.

**Versions**

```
$ eksctl info
```
eksctl version: 0.62.0
kubectl version: v1.21.2-13+d2965f0db10712
OS: linux

**Comment by cPu1** [comment]
We already have a [PR](https://github.com/weaveworks/eksctl/pull/4128 ) to address this issue and it will go out in the next release.

**Comment by cPu1** [comment]
The PR has been merged, the fix will be out on Friday.
