### ISSUE TITLE
The ARN for China region in the identity mapping(aws-auth configmap ) for emr-containers service is incorrect

### ISSUE THREAD

**Issue by walkley** [weaveworks/eksctl#4162]
**What were you trying to accomplish?**

In AWS China region, create EMR on EKS virtual cluster by following [EMR on EKS User Guide](https://docs.amazonaws.cn/en_us/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-cluster-access.html), in the section "Enable cluster access for Amazon EMR on EKS", create iamidentitymapping.

**What happened?**

The command `aws emr-containers create-virtual-cluster` failed to execute, the root cause is that the ARN in aws-auth configmap is incorrect:
```
- rolearn: arn:aws:iam::0123456789:role/AWSServiceRoleForAmazonEMRContainers
  username: emr-containers
```
the prefix of rolearn should be `arn:aws-cn:iam` in China regions.

**How to reproduce it?**

```
eksctl create iamidentitymapping \
    --cluster emr-zhy1 \
    --namespace emr-eks-workshop-namespace \
    --service-name "emr-containers" \
    --region cn-northwest-1
```

**Logs**

**Anything else we need to know?**

Source code is here: https://github.com/weaveworks/eksctl/blob/main/pkg/authconfigmap/service_access.go#L78

**Versions**

```
$ eksctl info
0.6.3
```

**Comment by cPu1** [comment]
Thanks for the detailed bug report. We missed adding the partition here like we do in other places. We'll look into this.

**Comment by Himangini** [comment]
@walkley Thanks for opening the issue. Our team doesn't have access to the China region, so we are unable to test this, will it be possible for you to open a PR for the fix?

**Comment by lamricky0** [comment]
> @walkley Thanks for opening the issue. Our team doesn't have access to the China region, so we are unable to test this, will it be possible for you to open a PR for the fix?

Hi I can try creating a PR for it; however, I am not that familiar with this package. Can you point out where I can get the AWS region? I see that there is already a function to get partition from function here: https://github.com/weaveworks/eksctl/blob/92377bade971d8170995d7567beacff02ce3b789/pkg/apis/eksctl.io/v1alpha5/types.go#L392-L401

**Comment by Skarlso** [comment]
Note to eksctl team, I put this into in progress since there is work being done on it / it's waiting for something to happen.

**Comment by Cynthiacheny** [comment]
hi, team
Any update on this? Thanks

**Comment by cPu1** [comment]
> hi, team
> Any update on this? Thanks

Hi @Cynthiacheny. @lamricky0  has opened a [PR](https://github.com/weaveworks/eksctl/pull/4218) but we haven't been able to test it. Are you able to test the changes?

**Comment by cPu1** [comment]
Closed by https://github.com/weaveworks/eksctl/pull/4218
