### ISSUE TITLE
Create some architecture diagrams for "popular" eksctl commands

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#4195]
Generally a good thing to have.

Pick the top 5 or so most popular commands and create some diagrams showing how each "request" flows through the code.

_will add more detail to this later, ping me or chetan if I forget_

**Comment by aclevername** [comment]
# eksctl create cluster
![image](https://user-images.githubusercontent.com/19669095/133767149-d92f0669-18b6-4829-8712-996976781914.png)
Created using https://www.websequencediagrams.com/ and saved to my personal account (attached the raw-contents below)
raw value:
```
title eksctl create cluster
note right of eksctl: All AWS API calls use the aws-sdk-go library
eksctl -> STS API: Authenticates and establishes a session
eksctl -> CF API: creates CloudFormation stack for EKS cluster, VPC and Roles
note right of eksctl: Uses aws-iam-authenticator library to create an in-memory kubeconfig using our session
eksctl -> EKS Cluster: Creates/Modifies Kubernetes Resources
eksctl -> CF API: creates CloudFormation stack for Nodegroups
eksctl -> EKS API: Create EKS Addons
eksctl -> User Machine: Write Kubeconfig 
```

**Comment by aclevername** [comment]
@Callisto13 @cPu1 lmk if thats enough detail ^. I couldn't think of a 5th command that was unique enough to add (all our API/interesting interactions are covered by those 4 commands)

**Comment by Callisto13** [comment]
🤔 could we include the specific endpoints each thing hits? or the sdk method whatevs.

Can you open a PR with these to throw them into docs?

**Comment by aclevername** [comment]
>  could we include the specific endpoints each thing hits? or the sdk method whatevs.

thats completely hidden from us though, its all through the `aws-sdk-go` :shrug: 

> Can you open a PR with these to throw them into docs?

Sure

**Comment by aclevername** [comment]
PR https://github.com/weaveworks/eksctl/pull/4236

**Comment by Callisto13** [comment]
> Idk how useful the name of the functions will be

yeh idk either tbh

**Comment by aclevername** [comment]
> > Idk how useful the name of the functions will be
> 
> yeh idk either tbh

can we share the docs with folks interested and get feedback? See if its got enough information or not :smile: ?

**Comment by Callisto13** [comment]
yeh we can sent them the pr in the call today
