### ISSUE TITLE
New Versioning with v prefix causes problems with installing the latest version

### ISSUE THREAD

**Issue by kr3cj** [weaveworks/eksctl#4199]
It appears that `eksctl` versions now have a `v` prefix since version `v0.64.0`. This causes any `asdf` users of the [`eksctl` plugin](https://github.com/elementalvoid/asdf-eksctl) to have problems getting the latest version.

```sh
$ asdf list all eksctl
...
0.61.0-rc.0
0.61.0-rc.1
0.61.0
0.62.0-rc.0
0.62.0
0.63.0-rc.0
0.63.0-rc.1
0.63.0
v0.64.0-rc.0
v0.64.0-rc.1
v0.64.0-rc.2
v0.64.0-rc.3
v0.64.0
v0.65.0-rc.0
v0.65.0
v0.66.0-rc.0
v0.66.0

$ asdf latest eksctl 
0.63.0
```

**Comment by kr3cj** [comment]
@Himangini thanks for looking into this so quickly!

**Comment by aclevername** [comment]
@kr3cj I noticed this earlier on in the week, I think its a result of my PR to fix our release process https://github.com/weaveworks/eksctl/pull/4182

While we do still cut a `vX.Y.Z` and `X.Y.Z` tag per release, the offical "github release" now points at the `X.Y.Z` rather than the `vX.Y.Z`. I don't understand why exactly but that appears to have happened. 

I'm not familiar with "asdf", I'm assuming this means that it watches got github releases instead of just tags?

**Comment by kr3cj** [comment]
Oh, interesting. Thanks for the background info. I'm not sure of where the "right" place to fix it is, but another option would be to change the [`eksctl` plugin](https://github.com/elementalvoid/asdf-eksctl) to scrub out the prefix. I'll try that.

[`asdf`](https://github.com/asdf-vm/asdf) is just a tool we use to manage per repository binary dependencies and versioning with extensible plugins. I'm not certain of it's popularity, but it's used heavily at my current job and I find it quite helpful.

**Comment by aclevername** [comment]
> Oh, interesting. Thanks for the background info. I'm not sure of where the "right" place to fix it is, but another option would be to change the [`eksctl` plugin](https://github.com/elementalvoid/asdf-eksctl) to scrub out the prefix. I'll try that.

:+1: 

I'm going to keep this issue open for a while to see if this is causing problems for anyone else :smile:

**Comment by kr3cj** [comment]
An update to the [eksctl plugin itself](https://github.com/elementalvoid/asdf-eksctl/pull/1) has fixed this issue for me.

```sh
$ asdf plugin-update eksctl
Updating eksctl to master
From https://github.com/elementalvoid/asdf-eksctl
   97e1941..92dae0f  master     -> master
   97e1941..92dae0f  master     -> origin/master
Already on 'master'
Your branch is up to date with 'origin/master'.

$ asdf list all eksctl
...
0.63.0
0.64.0-rc.0
0.64.0-rc.1
0.64.0-rc.2
0.64.0-rc.3
0.64.0
0.65.0-rc.0
0.65.0
0.66.0-rc.0
0.66.0
0.67.0-rc.0

$ asdf latest eksctl
0.66.0
```

**Comment by aclevername** [comment]
doesn't seem to have affected anyone else, closing.
