### ISSUE TITLE
availabilityZones in cluster.yaml isn't used

### ISSUE THREAD

**Issue by guilhem** [weaveworks/eksctl#420]
**What happened?**
When creating cluster, an error occurred:
```
getting availability zones: getting availability zones for eu-central-1: UnauthorizedOperation: You are not authorized to perform this operation.
```
After more attention to [code](https://github.com/weaveworks/eksctl/blob/3b8a4d9441dc16a3d21e1d544a67f43ab6617ffe/pkg/ctl/create/cluster.go#L298), we see that availability zones in file is always ignored and replace by command line option.

**What you expected to happen?**
As we add in our `cluster.yaml`:
```yaml
availabilityZones: [“eu-central-1a”, “eu-central-1b”, “eu-central-1c”]
```
Our create should be able to create cluster without rights on right availability zones.

**How to reproduce it?**
* Remove rights to list availability zones.
* `eksctl create cluster mycluster --zones eu-central-1a,eu-central-1beu-central-1c` should work
* `eksctl create cluster -f cluster.yaml` should fail

**Versions**
eksctl v0.1.17

**Comment by errordeveloper** [comment]
Thanks for reporting this, we are still pending some additional validation on the config files, but this falls into the category of fields that should be settable but currently aren't #425.
