### ISSUE TITLE
Private EKS Cluster Node Group crashloopbackoff for the CNI pod 

### ISSUE THREAD

**Issue by gkumarchilakala** [weaveworks/eksctl#4200]
We are creating a Private eks cluster using the eksctl version 0.63.0 using the below cluster.yaml file.

During the cluster creation, the managed node group was getting deleted due the CNI pod not getting initialized properly.

Upon working on AWS Support, we identified a issue with the version of eks cni pod has issues with.

version with issues: 602401143452.dkr.ecr.us-west-1.amazonaws.com/amazon-k8s-cni:v1.7.5-eksbuild.1

The issue is that, it's not happening consistently.

**Fix:** We have updated the eks cni version to 1.9.0 and then the cni was up and running and nodegroup was successfully joined.

PS C:\Users\mmm> C:\Users\mmm\Downloads\eksctl_Windows_amd64\eksctl.exe version
0.63.0

cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod
  region: us-west-1
  version: "1.19"
  tags:
    projectcode: "xxxx"

iam:
  withOIDC: true

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"
  - "logs"

vpc:
  subnets:
    private:
      us-west-1a:
        id: subnet
      us-west-1c:
        id: subnet

managedNodeGroups:
- name: workers-prod
  instanceType: m5.large
  desiredCapacity: 2
  minSize: 2
  maxSize: 4
  privateNetworking: true
  tags:
    app: nextgen
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/nextgenprod: "owned"
  ssh:
    allow: true
    publicKeyPath: ~/.ssh/prod.pub
  iam:
    withAddonPolicies:
      cloudWatch: true
      albIngress: true
      externalDNS: true

**Comment by Himangini** [comment]
@gkumarchilakala thanks for opening the issue with amazing details. Our team will investigate this 👍🏻
