### ISSUE TITLE
[SPIKE] Tests in EKSCTL

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#4212]
There have been few discussions around improving tests and we need to come up with proposals around it.
The person who picks this spike should focus on following things

- Investigate the gaps between our tests, what's the current coverage 
- Identify areas of improvement for unit tests i.e, areas where unit tests are missing, areas where tests are written but do not essentially cover the full functionality 
- Identify areas of improvement for integration tests
    - Flakes that happen a lot
    - Missing tests or incomplete tests
    - Ideas for improvements so devs have an easier time debugging what went wrong when the tests fail 
- Suggest any other improvements for testing overall

Pairing is highly encouraged. :) 

TimeBox: 2 days

previously written doc around testing strategy: https://docs.google.com/document/d/1EwWQLdP6RHRTuT6mCyw9wnQ2-zWDHvCw3Li58UUw9jo/edit#heading=h.8dhr0r1dgs09

Outcome: Proposal doc for the team to review so that we can plan few improvements during the upcoming product planning meeting

**Comment by aclevername** [comment]
something to think about to make debugging easier https://github.com/weaveworks/eksctl/pull/3513

**Comment by nikimanoledaki** [comment]
Here is the proposal doc containing some issue areas and ideas about test coverage/quality for unit and integration tests in eksctl: https://docs.google.com/document/d/1ZVkEogWNZzOebJ0QMN6eYrVpBFs1W7EfDqqtpZ4ozRo/edit

**Comment by nikimanoledaki** [comment]
Here is the proposal doc containing some issue areas and ideas about test coverage/quality for unit and integration tests in eksctl: https://docs.google.com/document/d/1ZVkEogWNZzOebJ0QMN6eYrVpBFs1W7EfDqqtpZ4ozRo/edit

**Comment by Himangini** [comment]
Closing this now. We will continue to add further improvement discussions around testing in the Spike doc.
