### ISSUE TITLE
[SPIKE] Refactoring

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#4213]
Spike to identify issues with code quality. 
We need to highlight areas of the code base that need refactoring and some plan of how to achieve this. 

Examples of things to look for:
- Pieces which can be refactored to make them easier to test
- "God classes" which do too much which can be broken up
- Duplicate flows which can be merged or put behind interfaces

nb: a lot of areas are not covered by tests, so refactoring is risky

Timebox : 4-5 days

Outcome: Proposal doc

**Comment by Himangini** [comment]
https://github.com/weaveworks/eksctl/issues/2931

**Comment by Himangini** [comment]
Consider https://github.com/weaveworks/eksctl/issues/1653 while working on this

**Comment by cPu1** [comment]
I have opened these issues for this refactoring spike: #4616, #4635, #4627, #4565, #4655.

**Comment by Himangini** [comment]
Closing this since we have planned all the related tickets 👍
