### ISSUE TITLE
Token not reread when it expired even if it was refreshed in the background

### ISSUE THREAD

**Issue by steffakasid** [weaveworks/eksctl#4221]
**What were you trying to accomplish?**
Create a cluster while your AWS token expires.

**What happened?**

The command prints out the following error. But doesn't even recover even if the token was refreshed in background.

`2021-09-16 10:33:08 [!]  retryable error (ExpiredToken: The security token included in the request is expired 	status code: 403, request id: aacc40c7-40c5-4f93-be22-d34f12f3803f) from sts/AssumeRole - will retry after delay of 30.46631ms`

I would expect if `eksctl` finds out that the token was expired, that it just tries to reread the token from `~/.aws/credentials` and if get's a new token that it then can recover from the error.

**How to reproduce it?**
Do something long running (e.g. create a cluster) and let your AWS token expire.

**Logs**
`2021-09-16 10:33:08 [!]  retryable error (ExpiredToken: The security token included in the request is expired 	status code: 403, request id: aacc40c7-40c5-4f93-be22-d34f12f3803f) from sts/AssumeRole - will retry after delay of 30.46631ms`

**Anything else we need to know?**
We're basically following the AWS best-practice: https://aws.amazon.com/blogs/security/how-to-implement-federated-api-and-cli-access-using-saml-2-0-and-ad-fs/ and we've a max token livetime of 60min.

**Versions**
```
❯ eksctl info
eksctl version: 0.66.0
kubectl version: v1.22.1
OS: darwin
```

**Comment by aclevername** [comment]
Thanks for opening the issue @steffakasid . The error your getting back is from the https://github.com/aws/aws-sdk-go which we call to issue our AWS API calls. Looking into it, it should be that it refreshes the token every 30minutes

https://github.com/weaveworks/eksctl/blob/3a77d07920b8c8a5e8ae9c62c120a05bcdfbaa31/pkg/eks/api.go#L452

https://pkg.go.dev/github.com/aws/aws-sdk-go/aws/credentials/stscreds
```
Package stscreds are credential Providers to retrieve STS AWS credentials.

STS provides multiple ways to retrieve credentials which can be used when making future AWS service API operation calls.

The SDK will ensure that per instance of credentials.Credentials all requests to refresh the credentials will be synchronized. But, the SDK is unable to ensure synchronous usage of the AssumeRoleProvider if the value is shared between multiple Credentials, Sessions or service clients.
```

Is this issue always happening? Or is it only sometimes that the refresh fails?

**Comment by aclevername** [comment]
> Please keep the issue open, it is not resolved yet. I encountered the same issue twice trying to create a cluster through `eksctl` on us-east-2 in a fairly stock Cloud9 environment.
> 
> EDIT: Looking into my issue a little bit more, [Cloud9 uses temporary tokens with 15 minutes expiration time](https://docs.aws.amazon.com/cloud9/latest/user-guide/troubleshooting.html#troubleshooting-cli-invalid-token). With the issue described here, it seems that no refresh is requested and thus running into this lovely error. Running `aws configure` in Cloud9 with my own AccessKey and SecretKey, rerunning `eksctl create cluster` again this way seems to workaround my issue.

Thanks @Nirusu . Just to confirm, your still seeing this issue?

**Comment by Nirusu** [comment]
Yup, eksctl still does not work with Cloud9 out of the box. Tried creating two cluster, both `eksctl create cluster` commands just freeze after the first CloudFormation stack has been generated.

**Comment by Skarlso** [comment]
Unfortunately `eksctl` can't do anything with the environment and authentication in general. If it's possible to increase the token timeout then please try doing that, because `eksctl` can't really do anything with the creation time either.

Closing this for now, as there is no action from our side that we could apply. Please re-open if you think otherwise.

**Comment by russau** [comment]
@Nirusu - I see this eks workshop attaches a role to their Cloud9 instance (instead of the rotating Cloud9 credentials)

* [Create the IAM role](https://www.eksworkshop.com/020_prerequisites/iamrole/)
* [Create the IAM role](https://www.eksworkshop.com/020_prerequisites/ec2instance/)
* [Disable the managed credentials](https://www.eksworkshop.com/020_prerequisites/workspaceiam/)
