### ISSUE TITLE
Add subnets option to create fargateprofile command

### ISSUE THREAD

**Issue by jimmyraywv** [weaveworks/eksctl#4223]
**What feature/behavior/change do you want?**
Add `--subnets` flag to `eksctl create fargateprofile` to allow for specifying custom network subnets.

**Why do you want this feature?**
Right now, there are options to specify custom subnets for a Fargate profile is in the EKS console or in the `eksctl create cluster` command, or with a cluster config snippet in the `eksctl create fargateprofile -f` command. This change would allow the use of the `create fargateprofile` command without having to use a config file for custom network subnets.

**Comment by aclevername** [comment]
Thanks for opening the issue @jimmyraywv 

We try not to overload the CLI with too many flags (as we have in the past for `eksctl create cluster`) and would encourage users to use a config file. Do you find having to use the config file costly? Are you not also creating fargate profiles, that would/could be part of the config file? Trying to understand the use case 😄

**Comment by jimmyraywv** [comment]
So, the `--tags` flag is there already. Adding `--subnets` would allow the CLI, without a config file, to spec custom subnets, which is needed for EKS Custom Networking. I guess I thought subnets would be at least as important as tags for a Fargate profile. That being said, I can use the cluster config snippet to spec the Fargate profile with custom subnets, and only use the CLI for when I am OK with the non-custom default behavior.

**Comment by jimmyraywv** [comment]
I can also revert to using the AWS CLI when I want to spec custom subnets.

**Comment by Callisto13** [comment]
>  I guess I thought subnets would be at least as important as tags for a Fargate profile.

It's less about importance, than "advanced usecases". Eksctl only exposes "basic" configuration via flags (tags are pretty basic), for anything more advanced (eg subnets) a configfile must be used.

**Comment by jimmyraywv** [comment]
There seems to be a consensus to not add the flag. I worked around it.
