### ISSUE TITLE
VPC Resource controller is moving to the control plane

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4235]
TODO: add more details.

See https://github.com/aws/containers-roadmap/issues/1280#issuecomment-780734054

**Comment by aclevername** [comment]
Dupe of https://github.com/weaveworks/eksctl/issues/2401 @cPu1 ?

**Comment by cPu1** [comment]
> Dupe of #2401 @cPu1 ?

Indeed, didn't even remember creating the issue. I'll close this one and amend the description in the other issue.
