### ISSUE TITLE
eksctl require me to use public subnets

### ISSUE THREAD

**Issue by pkexcellent** [weaveworks/eksctl#4241]
Issue I met:
When I create an eks cluster by eksctl, it shows: 
```
couldn't find public subnets: mapping doesn't have enough subnets: (allSubnets=v1alpha5.AZSubnetMapping(nil) AZs=[]string{"us-east-1a", "us-east-1b", "us-east-1c"} subnets=[]string(nil))
```
I know I'm using all private subnets by purpose, I can use this to create eks successfully in aws console. Could you tell me why it need public subnets? and I can skip the public subnet requirement?

**Comment by pkexcellent** [comment]
is this the solution?
https://eksctl.io/usage/eks-private-cluster/

**Comment by cPu1** [comment]
Nodegroups are created in a public subnet by default. To create a nodegroup with private subnets only, set `privateNetworking: true` in the nodegroup config.

**Comment by pkexcellent** [comment]
Thanks, @cPu1
