### ISSUE TITLE
Skip IAM error

### ISSUE THREAD

**Issue by shyam-ks** [weaveworks/eksctl#4246]
i have a scenario where i dont have this permission in the corporate account
AccessDenied: User:is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::14xxxx758:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/9A5D3BBCxxxxxx83457726F1B with an explicit deny
        status code: 403, request id: bd8547xxxxxxxxx92b2a20b0
 and i dont want to integrate with IAM OIDC.
Is there anyway to avoid looking for this permission as i am not adding iam oidc or anyway to ignore or skip this error?

**Comment by aclevername** [comment]
Hi @shyam-ks, could you provide more context?
- What command are you running?
- Whats the config file?
- Whats the full log output?

Thanks

**Comment by shyam-ks** [comment]
> 
> 
> Hi @shyam-ks, could you provide more context?
> 
>     * What command are you running?
> 
>     * Whats the config file?
> 
>     * Whats the full log output?
> 
> 
> Thanks

I am running this cluster.yaml file

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: us-east-1
  version: "1.21"

vpc:
  id: "vpc-014xxxxb213821"  
  securityGroup: "sg-0faxxx6607e" 
  subnets:
    private:
      us-east-1b:
        id: "subnet-xx30ad061a"
      us-east-1a:
        id: "subnet-xxx42d1fab6f"
  clusterEndpoints:
    privateAccess: true
    publicAccess: false

eksctl create cluster --config-file=./cluster.yaml --without-nodegroup

it creates the cluster and it waits for the cluster end point to become private. at the end it throws the error 
AccessDenied: User:is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::14xxxx758:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/9A5D3BBCxxxxxx83457726F1B with an explicit deny
status code: 403, request id: bd8547xxxxxxxxx92b2a20b0

**Comment by cPu1** [comment]
> > Hi @shyam-ks, could you provide more context?
> > ```
> > * What command are you running?
> > 
> > * Whats the config file?
> > 
> > * Whats the full log output?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks
> 
> I am running this cluster.yaml file
> 
> apiVersion: eksctl.io/v1alpha5
> kind: ClusterConfig
> 
> metadata:
> name: test
> region: us-east-1
> version: "1.21"
> 
> vpc:
> id: "vpc-014xxxxb213821"
> securityGroup: "sg-0faxxx6607e"
> subnets:
> private:
> us-east-1b:
> id: "subnet-xx30ad061a"
> us-east-1a:
> id: "subnet-xxx42d1fab6f"
> clusterEndpoints:
> privateAccess: true
> publicAccess: false
> 
> eksctl create cluster --config-file=./cluster.yaml --without-nodegroup
> 
> it creates the cluster and it waits for the cluster end point to become private. at the end it throws the error
> AccessDenied: User:is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::14xxxx758:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/9A5D3BBCxxxxxx83457726F1B with an explicit deny
> status code: 403, request id: bd8547xxxxxxxxx92b2a20b0

Thanks, this is helpful. The error seems to originate from the addons creation code. In this case, it makes sense to ignore permission errors from the `iam:GetOpenIDConnectProvider` call and consider it as OIDC not being enabled. We'll look into this.

**Comment by shyam-ks** [comment]
> 
> 
> > I am running this cluster.yaml file
> > apiVersion: eksctl.io/v1alpha5
> > kind: ClusterConfig
> > metadata:
> > name: test
> > region: us-east-1
> > version: "1.21"
> > vpc:
> > id: "vpc-014xxxxb213821"
> > securityGroup: "sg-0faxxx6607e"
> > subnets:
> > private:
> > us-east-1b:
> > id: "subnet-xx30ad061a"
> > us-east-1a:
> > id: "subnet-xxx42d1fab6f"
> > clusterEndpoints:
> > privateAccess: true
> > publicAccess: false
> > eksctl create cluster --config-file=./cluster.yaml --without-nodegroup
> > it creates the cluster and it waits for the cluster end point to become private. at the end it throws the error
> > AccessDenied: User:is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::14xxxx758:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/9A5D3BBCxxxxxx83457726F1B with an explicit deny
> > status code: 403, request id: bd8547xxxxxxxxx92b2a20b0
> 
> Thanks, this is helpful. The error seems to originate from the addons creation code. In this case, it makes sense to ignore permission errors from the `iam:GetOpenIDConnectProvider` call and consider it as OIDC not being enabled. We'll look into this.

Is there any way to skip this error. Right now, i cannot delete the cluster because eksctl delete cluster also throws the same error

**Comment by aclevername** [comment]
> > > I am running this cluster.yaml file
> > > apiVersion: eksctl.io/v1alpha5
> > > kind: ClusterConfig
> > > metadata:
> > > name: test
> > > region: us-east-1
> > > version: "1.21"
> > > vpc:
> > > id: "vpc-014xxxxb213821"
> > > securityGroup: "sg-0faxxx6607e"
> > > subnets:
> > > private:
> > > us-east-1b:
> > > id: "subnet-xx30ad061a"
> > > us-east-1a:
> > > id: "subnet-xxx42d1fab6f"
> > > clusterEndpoints:
> > > privateAccess: true
> > > publicAccess: false
> > > eksctl create cluster --config-file=./cluster.yaml --without-nodegroup
> > > it creates the cluster and it waits for the cluster end point to become private. at the end it throws the error
> > > AccessDenied: User:is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::14xxxx758:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/9A5D3BBCxxxxxx83457726F1B with an explicit deny
> > > status code: 403, request id: bd8547xxxxxxxxx92b2a20b0
> > 
> > 
> > Thanks, this is helpful. The error seems to originate from the addons creation code. In this case, it makes sense to ignore permission errors from the `iam:GetOpenIDConnectProvider` call and consider it as OIDC not being enabled. We'll look into this.
> 
> Is there any way to skip this error. Right now, i cannot delete the cluster because eksctl delete cluster also throws the same error

Have you tried with the `--force` flag?

**Comment by shyam-ks** [comment]
> 
> 
> > > > I am running this cluster.yaml file
> > > > apiVersion: eksctl.io/v1alpha5
> > > > kind: ClusterConfig
> > > > metadata:
> > > > name: test
> > > > region: us-east-1
> > > > version: "1.21"
> > > > vpc:
> > > > id: "vpc-014xxxxb213821"
> > > > securityGroup: "sg-0faxxx6607e"
> > > > subnets:
> > > > private:
> > > > us-east-1b:
> > > > id: "subnet-xx30ad061a"
> > > > us-east-1a:
> > > > id: "subnet-xxx42d1fab6f"
> > > > clusterEndpoints:
> > > > privateAccess: true
> > > > publicAccess: false
> > > > eksctl create cluster --config-file=./cluster.yaml --without-nodegroup
> > > > it creates the cluster and it waits for the cluster end point to become private. at the end it throws the error
> > > > AccessDenied: User:is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::14xxxx758:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/9A5D3BBCxxxxxx83457726F1B with an explicit deny
> > > > status code: 403, request id: bd8547xxxxxxxxx92b2a20b0
> > > 
> > > 
> > > Thanks, this is helpful. The error seems to originate from the addons creation code. In this case, it makes sense to ignore permission errors from the `iam:GetOpenIDConnectProvider` call and consider it as OIDC not being enabled. We'll look into this.
> > 
> > 
> > Is there any way to skip this error. Right now, i cannot delete the cluster because eksctl delete cluster also throws the same error
> 
> Have you tried with the `--force` flag?

Yeah. Gives this error

eksctl delete cluster -f cluster.yaml --force
2021-09-24 09:54:03 [ℹ]  eksctl version 0.67.0
2021-09-24 09:54:03 [ℹ]  using region us-east-1
2021-09-24 09:54:03 [ℹ]  deleting EKS cluster "test"
2021-09-24 09:54:04 [ℹ]  deleted 0 Fargate profile(s)
2021-09-24 09:54:04 [ℹ]  cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
Error: AccessDenied: User: arn:aws:sts::148210619758:assumed-role/EKSCTL-IAM-Role/i-0a8bxxx3252af1c is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::1xxxxx9758:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/9A5Dxxxx83457726F1B with an explicit deny
        status code: 403, request id: 2e5f0ab5-4910-4cc3-a8c4-fe013caf3919

**Comment by aclevername** [comment]
> Thanks, this is helpful. The error seems to originate from the addons creation code. In this case, it makes sense to ignore permission errors from the `iam:GetOpenIDConnectProvider` call and consider it as OIDC not being enabled. We'll look into this.

Why do you think its related to addons? I can't see any reference in the error/config file :thinking: 

> Yeah. Gives this error
> 
> eksctl delete cluster -f cluster.yaml --force
> 2021-09-24 09:54:03 [] eksctl version 0.67.0
> 2021-09-24 09:54:03 [] using region us-east-1
> 2021-09-24 09:54:03 [] deleting EKS cluster "test"
> 2021-09-24 09:54:04 [] deleted 0 Fargate profile(s)
> 2021-09-24 09:54:04 [] cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
> Error: AccessDenied: User: arn:aws:sts::148210619758:assumed-role/EKSCTL-IAM-Role/i-0a8bxxx3252af1c is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::1xxxxx9758:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/9A5Dxxxx83457726F1B with an explicit deny
> status code: 403, request id: 2e5f0ab5-4910-4cc3-a8c4-fe013caf3919

Ah that is frustrating. It looks like the error is coming from here https://github.com/weaveworks/eksctl/blob/813cf7e22327d8e4cd290ea3ad60b72bc37f5b1a/pkg/cfn/manager/delete_tasks.go#L206.

We will have to add a fix for this. If you can't wait for a fix then I would recommend:
1. run `eksctl delete nodegroups` for any nodegroups you might have (from configfile it looks like you have none)
1. Go to cloudformation and manually delete the cluseter stack. Stack should be named `eksctl-<cluster-name>-cluster`. If you see any other stacks named `eksctl-<cluster-name>-<something-else>` delete those first, then the cluster stack.

**Comment by shyam-ks** [comment]
> 
> 
> > Thanks, this is helpful. The error seems to originate from the addons creation code. In this case, it makes sense to ignore permission errors from the `iam:GetOpenIDConnectProvider` call and consider it as OIDC not being enabled. We'll look into this.
> 
> Why do you think its related to addons? I can't see any reference in the error/config file 🤔
> 
> > Yeah. Gives this error
> > eksctl delete cluster -f cluster.yaml --force
> > 2021-09-24 09:54:03 [] eksctl version 0.67.0
> > 2021-09-24 09:54:03 [] using region us-east-1
> > 2021-09-24 09:54:03 [] deleting EKS cluster "test"
> > 2021-09-24 09:54:04 [] deleted 0 Fargate profile(s)
> > 2021-09-24 09:54:04 [] cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
> > Error: AccessDenied: User: arn:aws:sts::148210619758:assumed-role/EKSCTL-IAM-Role/i-0a8bxxx3252af1c is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::1xxxxx9758:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/9A5Dxxxx83457726F1B with an explicit deny
> > status code: 403, request id: 2e5f0ab5-4910-4cc3-a8c4-fe013caf3919
> 
> Ah that is frustrating. It looks like the error is coming from here
> 
> https://github.com/weaveworks/eksctl/blob/813cf7e22327d8e4cd290ea3ad60b72bc37f5b1a/pkg/cfn/manager/delete_tasks.go#L206
> .
> 
> We will have to add a fix for this. If you can't wait for a fix then I would recommend:
> 
>     1. run `eksctl delete nodegroups` for any nodegroups you might have (from configfile it looks like you have none)
> 
>     2. run `eksctl delete iamserviceaccount` for any iamserviceaccounts you might have (from configfile it looks like you have none)
> 
>     3. run `eksctl delete addon` for any addon you might have (from configfile it looks like you have none)
> 
>     4. Go to cloudformation and manually delete the cluster stack. Stack should be named `eksctl-<cluster-name>-cluster`. If you see any other stacks named `eksctl-<cluster-name>-<something-else>` delete those first, then the cluster stack.

i will try that. is there any timeline on when this fix will be added ? 
Thanks for the quick response

**Comment by cPu1** [comment]
>Why do you think its related to addons? I can't see any reference in the error/config file thinking

I was referring to `create cluster`. I saw a codepath that leads to the call to `CheckProviderExists`.

>i will try that. is there any timeline on when this fix will be added ?

@shyam-ks, we can't give a timeline right now but will add it to our backlog.

**Comment by shyam-ks** [comment]
> 
> 
> > Why do you think its related to addons? I can't see any reference in the error/config file thinking
> 
> I was referring to `create cluster`. I found a codepath that leads to the call to `CheckProviderExists`.
> 
> > i will try that. is there any timeline on when this fix will be added ?
> 
> @shyam-ks, we can't give a timeline right now but will add it to our backlog.

Can we add this a a bug as the cluster also cannot be created. ?
