### ISSUE TITLE
Ensure that users cannot create IPv6 Windows clusters or nodegroups

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#4264]
Part of https://github.com/weaveworks/eksctl/issues/4255

**Description**
**Scope**
**Acceptance Criteria**

**Comment by aclevername** [comment]
@nikimanoledaki windows is `unmanaged` only AFAIK https://github.com/aws/containers-roadmap/issues/584

**Comment by cPu1** [comment]
> @nikimanoledaki windows is `unmanaged` only AFAIK [aws/containers-roadmap#584](https://github.com/aws/containers-roadmap/issues/584)
> 
> think we can close this as its a no-op

That's correct. Windows is not supported in managed nodegroups.

**Comment by nikimanoledaki** [comment]
Yes! That's true, totally slipped my mind. Thanks both :)
