### ISSUE TITLE
Add warning that `vpc.autoAllocateIPv6` field will be deprecated

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#4271]
This feature will need to be deprecated after there is support for creating IPv6 clusters with EKS. In order to do that, we need to add a warning saying that the field is deprecated in favour of `vpc.ipFamily` being set to `ipv6`. 

Original PR: https://github.com/weaveworks/eksctl/pull/776

**Comment by Himangini** [comment]
This is a no-op for now. Feel free to open it again if it becomes relevant.
