### ISSUE TITLE
User can create a new cluster by defining an existing IPv6 VPC in the config

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#4275]
Part of https://github.com/weaveworks/eksctl/issues/4255

**Description**
A user should be able to create an IPv6 cluster using their own IPv6 VPC by specifying the VPC ID in their config file (example of how we currently do this).

In terms of implementation, some validation is needed for the subnets and CIDR. More information about this can be found in the [_User supplied VPC config_](https://docs.google.com/document/d/16T0DP68UgLuDFwl3PhsYz2lswyGD3QozLT4rdyhxJls/edit#heading=h.fjf2i52vv8s6) section in the technical design doc. 

**Scope**
- Use an existing VPC given its ID in a similar way to how we do that for IPv4
- As is the case with IPv4, validate that the subnet has the minimum required number of subnets, unless `privateCluster` is enabled
- If the user has set the `vpc.ipv6Cidr` optional field, validate that they also set `vpc.ipv6CidrPool`
- Validate that the VPC has an `Ipv6CidrBlockAssociationSet`, plus that the IPv6 CIDR matches `vpc.ipv6Cidr` if that was set.

**Acceptance Criteria**
Story 1
As an eksctl user who already has an IPv6 VPC,
I can set my IPv6 VPC's ID and its subnets in my configuration file,
And when I create a cluster with eksctl,
I can see that my cluster has been created using that VPC, subnets, IPv6 CIDR, and IPv4 CIDR.

Story 2
As an eksctl user who already has an IPv6 VPC,
I can set my IPv6 VPC's ID, its subnets, and its IPv6 CIDR, in my configuration file,
And when I create a cluster with eksctl,
I can see that my cluster has been created using that VPC, subnets, IPv6 CIDR, and IPv4 CIDR.

**Comment by Himangini** [comment]
@aclevername @nikimanoledaki can this ticket be closed, I can see the related PR is merged. Are we waiting for testing for this one?
