### ISSUE TITLE
User can get cluster and see that it is ipv6

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#4276]
Part of https://github.com/weaveworks/eksctl/issues/4255

**Description**
See the [Get Cluster section](https://docs.google.com/document/d/16T0DP68UgLuDFwl3PhsYz2lswyGD3QozLT4rdyhxJls/edit#heading=h.fd6v6ncp95gu) in the design doc for some notes on implementation.

**Scope**
- `eksctl get cluster` returns a field about which `ipFamily` the cluster is running with `-o yaml` or `-o json`

**Acceptance Criteria**
User Story 1
- As an eksctl user
- Who created a cluster by setting `ipFamily` to `ipv6` in my configuration file
- When I do `eksctl get cluster --name <cluster-name> -o yaml`
- And when I do `eksctl get cluster --name <cluster-name> -o json`
- I can see that my cluster has been created with IPv6

User Story 2
- As an eksctl user
- Who created a cluster without setting `ipFamily` in my configuration file
- When I do `eksctl get cluster --name <cluster-name> -o yaml`
- And when I do `eksctl get cluster --name <cluster-name> -o json`
- I can see that my cluster has been created with IPv4 by default

**Comment by Himangini** [comment]
It should also work for unowned clusters
