### ISSUE TITLE
eksctl create nodegroup always sets Cluster DNS as 10.100.0.10

### ISSUE THREAD

**Issue by ozzieba** [weaveworks/eksctl#428]
When creating a nodegroup using `eksctl create nodegroup`, the cluster config object is crated from [scratch](https://github.com/weaveworks/eksctl/blob/eebd7ae358c2eb6767c28e1ffadb4444b36b5703/pkg/ctl/create/nodegroup.go#L20), so `spec.VPC.CIDR` is not inherited. Therefore the `CLUSTER_DNS` in `kubelet.env` is always [set](https://github.com/weaveworks/eksctl/blob/eebd7ae358c2eb6767c28e1ffadb4444b36b5703/pkg/nodebootstrap/userdata.go#L92) to 10.100.0.10, even for clusters in 10.0.0.0/8.

**Comment by errordeveloper** [comment]
Long term, we should be able to read configuration in full, but I don't think that's something that we can accomplish very easily right now, we also should consider whether storing original configuration is feasible at all or not. For now, this bug needs to be fixed, and we can fix it with a partially-populated `ClusterConfig`.

**Comment by errordeveloper** [comment]
@ozzieba did you get a chance to try out latest changes?

**Comment by whereisaaron** [comment]
Could the important configuration be included in the VPC and NodeGroup CF stack Outputs? That seems pretty easy. You only have max 60 parameters/outputs per CF stack, but each can be 4096 characters.

Things you don't even need for the stack could nonetheless be specified as CF parameters and just output again unchanged. You don't necessarily need to export them (into the glonal name space), you can just pick up e.g. the VPC CIDR from the outputs of the VPC stack.

For my self-built VPCs that I deploy `eksctl` clusters into, I already use that approach. I ensure any VPC configuration needed by eksctl to create clusters/nodegroups is stored in the CF stack(s). Which I then supply as `eksctl` command line options.

```
# Get the private subnets from the Outputs of the VPC CloudFormation stack
SUBNETS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME \
  | jq -r '[ .Stacks[0].Outputs[] | select(.OutputKey | test("PrivateSubnet[123]") ) | .OutputValue ] | join(",")')
```

**Comment by errordeveloper** [comment]
> Could the important configuration be included in the VPC and NodeGroup CF stack Outputs? That seems pretty easy.

We already do this for most critical things, we also have outputs that indicate use feature of certain features, e.g. the share SG. Are you suggesting we should add something else?

> You only have max 60 parameters/outputs per CF stack, but each can be 4096 characters.

I was trying to find that information sometime ago, do you have a URL handy for future reference? I was wondering if the whole 'ClusterConfig' object could be stored as output (maybe not a good idea for other reasons, but would be good to know of at all possible). I do recall reading about the key length info, but where is the 4096 character limit documented?

**Comment by whereisaaron** [comment]
> We already do this for most critical things, we also have outputs that indicate use feature of certain features, e.g. the share SG. Are you suggesting we should add something else?

You commented you [wanted to store everything in the config somewhere](https://github.com/weaveworks/eksctl/issues/428#issuecomment-453932576). I was suggesting you include everything as part of the CF stack parameters/outputs. That is easy, and then readily available to `eksctl` and, importantly, also readily available to other non-`eksctl` user automation that might need to springboard off any of the cluster config item.

The CF limits are here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html

If that isn't suitable, you could get `eksctl` to shove the entire config into [AWS Systems Manager Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html) and the directly [import/reference parameters](https://aws.amazon.com/blogs/mt/integrating-aws-cloudformation-with-aws-systems-manager-parameter-store/) in the cluster CF stack and also node group CF stacks.

**Comment by errordeveloper** [comment]
> You commented you [wanted to store everything in the config somewhere](https://github.com/weaveworks/eksctl/issues/428#issuecomment-453932576).

Eh, who reads their own comments?! ;)

> I was suggesting you include everything as part of the CF stack parameters/outputs. That is easy, and then readily available to `eksctl` and, importantly, also readily available to other non-`eksctl` user automation that might need to springboard off any of the cluster config item.

I agree, and that what we started doing already. Not everything yet, but the key thing.

> The CF limits are here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html
> CF identifiers have shorter limits, but most string values top out at 4,096. Even the parameter description can store another 4,096 characters. You just have to watch that each whole CF template is under 51,200 characters, as otherwise you need to store the template in S3 for CF to read.

Yes, the page does say about output values per-se...

> If that isn't suitable, you could get `eksctl` to shove the entire config into [AWS Systems Manager Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html) and the directly [import/reference parameters](https://aws.amazon.com/blogs/mt/integrating-aws-cloudformation-with-aws-systems-manager-parameter-store/) in the cluster CF stack and also node group CF stacks.

Yes, that sounds like it would fit the bill, and I hope there is something like this. Thanks for sharing! I must say, however, that I may prove very challenging to introduce more AWS services with many enterprise users. There are many organisations where each service has to go through approval process, and even if it gets approved, there is still a big question of who gets full access. Something to look into, of course.

Arguably, storing all the objects in Kubernetes is almost a no brainer, and as EKS availability is out of question, I would be the best way really. Not that there aren't any reasons against it, yet seems like we could get a long way. Afterall, eventually Cluster API is the goal, and that means we will use of Kubernetes API for everything we can use it for.

**Comment by whereisaaron** [comment]
You certainly can store the config in the EKS control plane, but everything in the configuration is meta-information about the cluster, and not particularly useful to the cluster itself. Rather the config information is most useful to other CF stacks, but it is very hard for CF to access it inside an EKS cluster (barring a lambda CF custom function maybe). From an AWS perspective, CF or SSM is the most useful place to have cluster and node group stack information.

That said, if a k8s API extension to manage clusters is the goal, then I can see why you might consider in-cluster storage.

**Comment by errordeveloper** [comment]
@whereisaaron thanks, this is very helpful. Could you please open another issue to suggest any particular fields that you think must be exposed as stack outputs? I think use of Parameter Store would be a separate topic, perhaps we could consider it as an optional feature that would allow you to store metadata in Parameter Store, if e.g. you have a corporate policy to use Parameter Store for all the things.
Sidebar: once we get to full git-driven cluster management (aka gitops), you shouldn't need to actually use Kubernetes API to get your objects, you'd be looking at JSON or YAML files in git, and that's arguably even easier then making CloudFormation API calls.

**Comment by errordeveloper** [comment]
I've opened #583 for the record, so this discussion doesn't get buried. Please do open another issue if you have any specific metadata that you think has to be exposed via stack outputs, or Parameter Store exporter would ultimately suite your needs?
