### ISSUE TITLE
User can set `extraCIDRs` (for v4) on IPv6 VPC

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#4280]
Part of https://github.com/weaveworks/eksctl/issues/4255
**Description**
Users can already set `vpc.extraCIDRs` to append IPv4 CIDR ranges to the ControlPlaneSecurityGroup. Ensure that this field is also implemented for IPv6 VPCs/clusters.

**Scope**
- Ensure that `vpc.extraCIDRs` works for IPv6 VPCs

**Acceptance Criteria**
As an eksctl user,
When I set `ipFamily` to `IPv6` and I supply additional IPv4 CIDRs with `vpc.extraCIDRs` in my config file,
And I create a new IPv6 cluster,
I should be able to see these additional CIDR ranges appended to the `ControlPlaneSecurityGroup`.

**Comment by aclevername** [comment]
no-op, this happens regardless of ipfamily type. https://github.com/weaveworks/eksctl/blob/68b3417a26e653f27d5233f5cf075a135f4a0edb/pkg/cfn/builder/cluster.go#L103-L126

Already validated to ensure its valid CIDRs https://github.com/weaveworks/eksctl/blob/d29c6be884af6d73f45b78a1218155588f304f27/pkg/apis/eksctl.io/v1alpha5/validation.go#L962
