### ISSUE TITLE
User can set existing `sharedNodeSecurityGroup` on IPv6 VPC

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#4281]
Part of https://github.com/weaveworks/eksctl/issues/4255
**Description**
Similar to #4277 
Ensure that `vpc.sharedNodeSecurityGroup` also works for IPv6 VPCs.

More info in the [technical doc](https://docs.google.com/document/d/16T0DP68UgLuDFwl3PhsYz2lswyGD3QozLT4rdyhxJls/edit?pli=1#heading=h.d2gg4nuh7jap)

**Scope**
- Replicate the `vpc.sharedNodeSecurityGroup` IPv4 feature for an IPv6 VPC

**Acceptance Criteria**
As an eksctl user who has already created a `SharedNodeSecurityGroup`,
When I set `ipFamily` to `IPv6` and `sharedNodeSecurityGroup` with a SG ID in my config file,
And I create this cluster with eksctl,
I can see that my cluster has been created using that Security Group.

**Comment by aclevername** [comment]
already works regardless of ipv4/6 https://github.com/weaveworks/eksctl/blob/68b3417a26e653f27d5233f5cf075a135f4a0edb/pkg/cfn/builder/cluster.go#L129-L144
