### ISSUE TITLE
User can create managed nodegroup which is assigned an IPv6 CIDR

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#4282]
Part of https://github.com/weaveworks/eksctl/issues/4255

**Description**
Either as part of cluster creation or afterwards, a user should be able to create a managed nodegroup in an IPv6 cluster and be assigned an IPv6 CIDR.

```yaml
vpc:
  ipFamily: ipv6

managedNodeGroups:
  - name: mng1
    instanceType: m5.large
    desiredCapacity: 1
```

NOTE: check the [MaxPods](https://docs.google.com/document/d/16T0DP68UgLuDFwl3PhsYz2lswyGD3QozLT4rdyhxJls/edit?pli=1#heading=h.2200s5qytnfw) field for Managed Nodegroups. Eksctl does not set this value for managed ng unless the user has provided a value. 

**Scope**
- This is for managed nodegroups only, **not unmanaged nodegroups**.
- Update the docs

**Acceptance Criteria**
Story 1
- As an eksctl user,
- When I call _`create cluster`_ with IPv6 and managed nodegroup configuration, 
- I should be able to see that a managed nodegroup was created that is assigned an IPv6 CIDR.
- I can learn about this in the docs

Story 2
- As an eksctl user,
- When I call _`create nodegroup`_ with IPv6 and managed nodegroup configuration, 
- I should be able to see that a managed nodegroup was created that is assigned an IPv6 CIDR.

**Comment by Skarlso** [comment]
Detected a problem with a node joining a cluster. AWS was contacted about the issue. Until this is resolved, we park this item once again.

**Comment by Skarlso** [comment]
The first part, where we can add nodegroups to clusters has been verified to work by @nikimanoledaki.

Now those stories dealing with adding nodegroups are unblocked. However, we can't yet verify during cluster creation, so those are blocked.

**Comment by Skarlso** [comment]
Nodegroup creation is also blocked on another failure where coredns pods aren't getting ips assigned.

```
 Warning  FailedCreatePodSandBox  15m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "572fba9f1ad2d678f8ac027403f4e56ccf3037776dc814ad4f7e5ff81cbe59f0" network for pod "coredns │
│ -85d5b4454c-t8cp2": networkPlugin cni failed to set up pod "coredns-85d5b4454c-t8cp2_kube-system" network: add cmd: failed to assign an IP address to container                                                                                                            │
│   Warning  FailedCreatePodSandBox  5m49s (x544 over 15m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "45c2a89d65a8e19f43342990a68eb98de4fd26a653dee4e52ba55db1c1 │
│ 3b6159" network for pod "coredns-85d5b4454c-t8cp2": networkPlugin cni failed to set up pod "coredns-85d5b4454c-t8cp2_kube-system" network: add cmd: failed to assign an IP address to container                                                                            │
│   Normal   SandboxChanged          49s (x828 over 15m)    kubelet            Pod sandbox changed, it will be killed and re-created. 
```

**Comment by aclevername** [comment]
> Nodegroup creation is also blocked on another failure where coredns pods aren't getting ips assigned.
> 
> ```
>  Warning  FailedCreatePodSandBox  15m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "572fba9f1ad2d678f8ac027403f4e56ccf3037776dc814ad4f7e5ff81cbe59f0" network for pod "coredns │
> │ -85d5b4454c-t8cp2": networkPlugin cni failed to set up pod "coredns-85d5b4454c-t8cp2_kube-system" network: add cmd: failed to assign an IP address to container                                                                                                            │
> │   Warning  FailedCreatePodSandBox  5m49s (x544 over 15m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "45c2a89d65a8e19f43342990a68eb98de4fd26a653dee4e52ba55db1c1 │
> │ 3b6159" network for pod "coredns-85d5b4454c-t8cp2": networkPlugin cni failed to set up pod "coredns-85d5b4454c-t8cp2_kube-system" network: add cmd: failed to assign an IP address to container                                                                            │
> │   Normal   SandboxChanged          49s (x828 over 15m)    kubelet            Pod sandbox changed, it will be killed and re-created. 
> ```

While this issue remains, we are definitely successful in created an ipv6 managed nodegroup (full log here: https://github.com/weaveworks/eksctl/issues/4284#issuecomment-987986384). Given that I think its **OKAY** to mark this as done. Going to close, feel free to re-open if your disagree :)
