### ISSUE TITLE
User can create a private IPv6 cluster

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#4283]
Part of https://github.com/weaveworks/eksctl/issues/4255

**Description**
Private Networking will be supported in eksctl for IPv6. Users will be able to specify the same options they do for IPv4: `privateCluster.enabled` and `privateCluster.additionalEndpointServices`. 

The VPC will be configured in much the same way as the default workflow, but with any public Subnets, public Route Tables, public Route Table Associations, and Gateways (all of them) omitted. 

In the same way we do for IPv4, VPC endpoints will be set for continued access to AWS services from within the private network.

**Scope**

**Acceptance Criteria**
Story 1
As an eksctl cluster
When I set `privateCluster.enabled` to `true`,
And when I create a cluster,
I should see only private subnets
I should not see any public subnets
I should learn about this in the docs

Story 2
As an eksctl cluster
When I set `privateCluster.enabled` to `true`,
And when I set `privateCluster.additionalEndpointServices` with `"autoscaling"`,
And when I create a cluster,
I should see only private subnets
I should not see any public subnets
I should learn about this in the docs

**Comment by Himangini** [comment]
Niki to fill the validation info
