### ISSUE TITLE
There is no way to add mapRoles/mapUsers/mapAccounts to aws-auth from ClusterConfig

### ISSUE THREAD

**Issue by pkit** [weaveworks/eksctl#4312]
**What feature/behavior/change do you want?**

Right now there is no way to use GitOps flow for `aws-auth` manipulation.

**Why do you want this feature?**

All the mappings need to be updated manually by using `eksctl iamidentitymapping` commands.
Which makes GitOps flow impossible for any real-world cluster.

**Comment by doctorpangloss** [comment]
This should be reopened

**Comment by cPu1** [comment]
> This should be reopened

@doctorpangloss The EKS team is working on a new API that'll eliminate the need for manipulating `aws-auth`. We are waiting for that before adding any new features around `aws-auth`.
