### ISSUE TITLE
single zone nodegroup can not be created

### ISSUE THREAD

**Issue by prageethw** [weaveworks/eksctl#432]
**What happened?**
tried creating single zone node group on top of existing cluster, which has a nodegroup already with the same zone.

executed below

    eksctl create nodegroup \
    --cluster $NAME \
    --name $NG2_NAME \
    --node-zones $ZONE2 \
    --asg-access \
    --external-dns-access \
    --node-type ${NODE_TYPE:-t2.small} \
    --nodes ${DESIRED_NODE_COUNT:-3} \
    --nodes-max ${NODE_COUNT:-5}  \
    --nodes-min ${MIN_NODE_COUNT:-3} \
    --ssh-access --ssh-public-key ${SSH_PUBLIC_KEY:-keys/k8s-eks.pub}

**What you expected to happen?**
single zone nodegroup should be able to be created.

**How to reproduce it?**
refer above

**Anything else we need to know?**
AWS USA east 2

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.18"}
$ uname -a
Darwin mymac 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Logs**

VPC doesn't have enough subnets for nodegroup AZs (subnets=map[string]v1alpha3.Network(nil) AZs=[]string{"us-east-2b"})
[✖]  failed to create nodegroup ng2 for cluster "prageethw-1547468856"

**Comment by errordeveloper** [comment]
The release binaries are being built right now, will be available from the
usual place very soon.

**Comment by prageethw** [comment]
this issue re-appeared again with 

$ eksctl version
ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.19"}

**Comment by errordeveloper** [comment]
Do you get exactly the same error message or soemthing different?

**Comment by prageethw** [comment]
to me seems exact same msg refer below
```bash
VPC doesn't have subnets in --asg-access (subnets=map[string]v1alpha3.Network{"us-east-2b":v1alpha3.Network{ID:"subnet-0f5b41784c271b09f", CIDR:(*ipnet.IPNet)(0xc000825290)}, "us-east-2a":v1alpha3.Network{ID:"subnet-0fa03e82769fc2985", CIDR:(*ipnet.IPNet)(0xc000825320)}, "us-east-2c":v1alpha3.Network{ID:"subnet-0a9f7e4efd20afc77", CIDR:(*ipnet.IPNet)(0xc000825380)}} AZs=[]string{"--asg-access"})
[✖]  failed to create nodegroup ng2 for cluster "prageethw-1548501934"
```

**Comment by errordeveloper** [comment]
It looks like you might have something with flag syntax there, as
'--asg-access' gets picked up as a value of some flag ..

**Comment by errordeveloper** [comment]
Yeah, looks like you have effectively set AZs to '--asg-access', so eksctl
tries to look for subnets there, but there is no such AZ. Maybe we could
improve the error message somehow, it is a little raw as is.

**Comment by prageethw** [comment]
thanks @errordeveloper  you seem to be correct, it is just zones value was not getting populated and subsequent flag picked up as zones value, yeah as you said it will be good if we can make it clearer.
