### ISSUE TITLE
review issue and PR templates

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#434]
We have this right now:<pre><code>**What happened?**
A description of actual behavior (with error messages).

**What you expected to happen?**

**How to reproduce it?**
Include the steps to reproduce the bug

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
$ uname -a
$ kubectl version
```
Also include your version of `heptio-authenticator-aws`

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.
</pre></code>

It has a reference to `heptio-authenticator-aws`, which confuses some users and also can be trimmed a little bit in general.
Also issues type selection doesn't seem to set tags and same template is used, that needs to be investigated.

For PRs we have:<code><pre>### Description

Make sure to fetch public and private subnet IDs when getting all VPC info. This fixes #

### Checklist
- [ ] Code compiles correctly (i.e `make build`)
- [ ] Added tests that cover your change (if possible)
- [ ] All tests passing (i.e. `make test`)
- [ ] Added/modified documentation as required (such as the README)
- [ ] Added yourself to the `humans.txt` file
</code></pre>

This should include a comment line to state that items from the checklist can be removed when deemed non-applicable, and add an item for `make integration-test`.

**Comment by errordeveloper** [comment]
@dholbach @martina-if any thoughts on this? I also noticed that issue template selection doesn't seem to work properly, it'd be nice if labels could be added automatically...

**Comment by dholbach** [comment]
Are there commands people can just type in to get e.g. the version of heptio-authenticator-aws and all the other required info?

I thought we were applying labels when people used issue templates in Flux already, but they were buggy. Using https://github.com/weaveworks/flux/pull/2040/files#diff-74c2649c999338ed7a2833d79d4b25c3 should fix this.

**Comment by errordeveloper** [comment]
One thing we might want to do is actually drop the authenticator question.
It's often irrelevant.

**Comment by errordeveloper** [comment]
@gemagomez and I discussed this, and looks like there are few things we can improve/simplify.

**Comment by michaelbeaumont** [comment]
It looks to me like Martina's PR addressed everything here. The labels are added automatically.
There's no information about what was discussed and can be improved/simplified.
