### ISSUE TITLE
Unable to update shared Security group after the cluster creation. 

### ISSUE THREAD

**Issue by sharoncr1** [weaveworks/eksctl#4350]
**What feature/behavior/change do you want?**
I need an option to update existing cluster parameters using some command like eksctl update cluster. I know this command already exists but deprecated and makes no effect for the changes. 

**Why do you want this feature?**
Atleast some of the cluster configs needs to be mutable and hence configurable on the go. For example, we may need to change the tags on the EKS at some point. In my case, I wanted to change `sharedNodeSecurityGroup` for the cluster since I am new to EKS and I used to use KOPS earlier where it already had a single Security group for the complete set of nodes. 

After realising that eksctl creates dedicated SGs for each nodegroup, I added `managedNodeGroups.securityGroups.withLocal=false` in my cluster config yaml and tried applying by deleting and recreating the nodegroup. But it didn't make any difference and I think this is because by cluster config is not yet updated even after trying cluster update command.

**Comment by cPu1** [comment]
>Is there a way for not having a dedicated SG for each Nodegroup ?

eksctl attaches only one SG (`ClusterSecurityGroupId`) to managed nodegroups by default. 

>That was my expectation when I set managedNodeGroups.securityGroups.withLocal=false.

`withLocal: false` does exactly that, it does not attach a dedicated security group to the nodegroup, however, it has no effect on managed nodegroups as that's the default behaviour. Can you confirm you're using managed nodegroups (`managedNodeGroups` field) and not unmanaged nodegroups (`nodeGroups` field)?

>And also I am bit annoyed with the way I need to make changes to the ManagedNodegroups. If I made a change, however trivial it be, like adding a new label, I need to delete the nodegroup using eksctl, then the CloudFormation stack in AWS and then creating the nodegroup again using eksctl.

This is true for some commands, but for labels, you can use `eksctl set labels` on an existing nodegroup.

**Comment by sharoncr1** [comment]
@cPu1 Thanks for your response. It cleared some of my concerns about dynamically managing the nodegroups using eksctl.

> eksctl attaches only one SG (ClusterSecurityGroupId) to managed nodegroups by default.

@cPu1 Sorry, I didn't get which property you meant by `ClusterSecurityGroupId`. I am referencing https://eksctl.io/usage/schema/ and I don't see `ClusterSecurityGroupId` in it. Did you mean `vpc.securityGroup`? 

> withLocal: false does exactly that, it does not attach a dedicated security group to the nodegroup, however, it has no effect on managed nodegroups as that's the default behaviour

Does it mean `managedNodeGroups` will always have a dedicated security group attached and we can't override that behaviour using `withLocal: false` ? If yes, why don't we remove that from the config schema to avoid confusions in the future and also call that out on https://eksctl.io/usage/eks-managed-nodes/#feature-parity-with-unmanaged-nodegroups

To give more context and clarity, my cluster config looks like following and I still have three SGs attached to my nodes : 
`
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dev
  region: us-east-1
  version: "1.21"
  tags:
    'customer': 'internal'
    'cost-center': 'overhead'
    'env-type': 'dev'
vpc:
 id: vpc-abcdefg
 sharedNodeSecurityGroup: sg-05689bcb0b532d8cf
 subnets:
  public:
      .............
  private:
      .............
managedNodeGroups:
  - name: nodes
    amiFamily: AmazonLinux2
    instanceType: m5.large
    MaxSize: 4
    minSize: 1
    volumeSize: 50
    privateNetworking: true
    ssh:
      allow: true 
    .
    . 
    iam:
      instanceRoleARN: arn:aws:iam::123456789098:role/k8s_nodes
    securityGroups:
      attachIDs:
      - sg-05689bcb0b532d8cf            #same one as sharedNodeSecurityGroup
      withLocal: false
`

**Comment by sc-juho** [comment]
As I'm coming from Terraform I was expecting that I could edit the configuration yaml and just run some kind of `eksctl apply` command and it would then to the required changes to the cluster.

I'm fine if eksctl would refuse to try to do changes which cannot be changed after the cluster creation. However if I first created a cluster without `clusterLogging` and then realised that I want to enable that I would need to both edit the cluster.yaml to reflect my desired state of the cluster and to also run the `eksctl utils update-cluster-logging`

@aclevername is there a reason why eksctl doesn't try to have such `apply` command but instead went with having separated updated commands for each updatable settings?

**Comment by aclevername** [comment]
> As I'm coming from Terraform I was expecting that I could edit the configuration yaml and just run some kind of `eksctl apply` command and it would then to the required changes to the cluster.
> 
> I'm fine if eksctl would refuse to try to do changes which cannot be changed after the cluster creation. However if I first created a cluster without `clusterLogging` and then realised that I want to enable that I would need to both edit the cluster.yaml to reflect my desired state of the cluster and to also run the `eksctl utils update-cluster-logging`
> 
> @aclevername is there a reason why eksctl doesn't try to have such `apply` command but instead went with having separated updated commands for each updatable settings?

I don't have the history of why we went for `apply` vs `update`, but the best explanation to my knowledge is that the vast majority of cluster configuration is immutable, so having it might introduce a lot of confusion about what can be changed, e.g. `eksctl apply` might only work for 10% of the config file. We have an issue to track this https://github.com/weaveworks/eksctl/issues/2774

**Comment by sharoncr1** [comment]
Any update on https://github.com/weaveworks/eksctl/issues/4350#issuecomment-957328059 :crying_cat_face:

**Comment by aclevername** [comment]
> Any update on [#4350 (comment)](https://github.com/weaveworks/eksctl/issues/4350#issuecomment-957328059) crying_cat_face

@cPu1

**Comment by cPu1** [comment]
>Does it mean managedNodeGroups will always have a dedicated security group attached and we can't override that behaviour using withLocal: false ? 

That's correct. 

> If yes, why don't we remove that from the config schema to avoid confusions in the future 

Some types are shared between managed and unmanaged nodegroups, so the resulting schema shows all fields, but the documentation for that field does mention that it's not supported for managed nodegroups: https://eksctl.io/usage/schema/#nodeGroups-securityGroups-withLocal

>and also call that out on https://eksctl.io/usage/eks-managed-nodes/#feature-parity-with-unmanaged-nodegroups

Good call, we'll update the feature parity section.

**Comment by sharoncr1** [comment]
@cPu1 Thanks. Got it.. Closing the ticket
