### ISSUE TITLE
[SPIKE] Support IP address prefixes from vpc-cni 1.9.0

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#4351]
We need to determine how should we implement the steps mentioned [here](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html)
Investigate the current implementation and come up with a way to incorporate the functionality to support IP addresses
from vpc-cni 1.9.0

Timebox: 1 day [max]

**Comment by Skarlso** [comment]
Blocked until the related go SDK issue is answered / resolved.

**Comment by Skarlso** [comment]
The decision is, apparently, that because this is a breaking change it will not be done.
