### ISSUE TITLE
Add dry-run for other commands than create

### ISSUE THREAD

**Issue by yogeek** [weaveworks/eksctl#4353]
**What feature/behavior/change do you want?**

The ["Add dry-run to all commands" issue](https://github.com/weaveworks/eksctl/issues/476) is a little bit misleading because in reality it only concerns "create" commands.

It would be useful to have `--dry-run` option also for every commands that induce a modification (upgrade nodegroups, update nodegroups, delete nodegroups, etc)

Example :
```
$ eksctl upgrade nodegroup --dry-run
$ eksctl update nodegroup --dry-run
```

**Why do you want this feature?**

Having dry-run option would allow to display a 'plan' of what is going to happen in the case of an modification (upgrade or update of nodegroups for example).
In a CI/CD pipeline, it would permit human verification before applying the modification in production, what would reduce mistakes due to incorrect configuration.

**Comment by Skarlso** [comment]
Hi. No such command. :) But to answer your question, most of the time regarding nodes, the changes applied would only be apparent once they have been applied. dry-run in these situations makes little sense. It would literally just return with the values you set.

**Comment by abentley-ssimwave** [comment]
In our use case, we are doing infrastructure-as-code, with cluster.yaml in version control.  We apply the code manually.  We would like to verify that the state in the cluster matches the state in the code. For example:
* No nodegroups present that the cluster that are not present in cluster.yaml
* No nodegroups missing from the cluster that are present in cluster.yaml

For GKE, we are able to use `terraform plan` to achieve this.  A dry-run feature in eksctl would help in EKS.

Now that managed nodegroups are a thing, this may be easier than it was before.

**Comment by cPu1** [comment]
> In our use case, we are doing infrastructure-as-code, with cluster.yaml in version control. We apply the code manually. We would like to verify that the state in the cluster matches the state in the code. For example:
> 
> * No nodegroups present that the cluster that are not present in cluster.yaml (already detectable using eksctl)
> * No nodegroups missing from the cluster that are present in cluster.yaml
> 
> For GKE, we are able to use `terraform plan` to achieve this. A dry-run feature in eksctl would help in EKS.
> 
> Now that managed nodegroups are a thing, this may be easier than it was before.

@abentley-ssimwave, thanks for sharing your use case. I have reopened the issue. We'll look into it when we have some capacity.

**Comment by abentley-ssimwave** [comment]
Please don't close.
