### ISSUE TITLE
Set `AssignIpv6AddressOnCreation` during template creation

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#4363]
This is a ticket to track a workaround in the CF template creation process for IPv6 VPCs.

Currently, `AssignIpv6AddressOnCreation` cannot be set alongside `MapPublicIpOnLaunch` at CF template create time. This means we need to add it manually by hitting the VPC API to update each public subnet after the template is created.

Let's keep this open as a reminder to check whether there's been a fix for it or not.

Commit to revert: https://github.com/weaveworks/eksctl/pull/4317/commits/827c47e4ca054a969ee8b4659e762a7af1b655d1

Note: This ticket does not block the release of IPv6 for eksctl.

**Comment by Himangini** [comment]
Not time critical, the workaround will still work even when the issue is fixed so we can do this at our pace.

**Comment by Himangini** [comment]
@nikimanoledaki are we still blocked on this? wondering if it's a good time to address this now?
