### ISSUE TITLE
Impossible to copy a generated launch configuration

### ISSUE THREAD

**Issue by aboubeta** [weaveworks/eksctl#437]
**What happened?**
After use "Copy launch configuration" from AWS web panel, the user-data is corrupted on the new launch configuration. 

`cloud-init[3842]: Jan 15 11:26:48 cloud-init[3842]: __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: '\x1f\x8b\x08\x0
0\x00\x00\x00\x00\x00\xff\xacXko\xf2:\xb6\xfe\xde_\x91\xc3~?...'`

**What you expected to happen?**
The user-data would be readable, at least for the machine

**How to reproduce it?**
* Create cluster
* Copy created launch configuration  

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.17"}
$  uname -a
Darwin XXXXXX 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
`cloud-init[3842]: Jan 15 11:26:48 cloud-init[3842]: __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: '\x1f\x8b\x08\x0
0\x00\x00\x00\x00\x00\xff\xacXko\xf2:\xb6\xfe\xde_\x91\xc3~?...'`

**Comment by aboubeta** [comment]
I want to use a new launch configuration, based on a eksctl generated one. Steps:

* Generate cluster (or nodegroup) with eksctl
* On AWS Web Console -> Launch Configurations use the button "Copy launch configuration" 
* Change the autoscaling group in order to use the new launch configuration
* Start a new instance on the autoscaling group
* The new instance fails to apply the user-data: 

`
cloud-init[3842]: Jan 15 11:26:48 cloud-init[3842]: __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: '\x1f\x8b\x08\x0 0\x00\x00\x00\x00\x00\xff\xacXko\xf2:\xb6\xfe\xde_\x91\xc3~?...'
`

**Comment by aboubeta** [comment]
We have a customised ami, wich changes very often. Usually ops guys change the launch configurations and the autoscaling groups in order to use it, and they like very much the "Web Console" :P 

Thanks anyway, I will wrote a script to make lauch configuration with a "visible" user-data

**Comment by errordeveloper** [comment]
That can be automated through an operator, you can subscribe to AMI updates and kick-off auto-updates. Just for the record, in eksctl we would rather treat nodegroup changes in an immutable fashion, i.e. create new ASG and kill the old one.

If you don't mind, I will close this issue... We can touch base on Slack.
