### ISSUE TITLE
Integration test for `eksctl enable flux` sometimes fails with a DeadlineExceeded error

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4395]
`eksctl enable flux` failed with a `DeadlineExceeded` error today: https://github.com/weaveworks/eksctl/runs/4074437257

The `flux bootstrap` command likely needs more time to complete than the default value of 5 minutes. This issue is for investigating the `DeadlineExceeded` error and increasing the timeout if required.

**Comment by cPu1** [comment]
Not stale, we might not have encountered this error since the issue was last created but the integration test code hasn't changed either to warrant closing the issue.

**Comment by Himangini** [comment]
Parking this for now since the related ticket seems to have fixed this issue as well. If the tests fail again with same error then we'll pick this up
