### ISSUE TITLE
Assign node public IPs from Elastic IP pool

### ISSUE THREAD

**Issue by aparamon** [weaveworks/eksctl#440]
**Why do you want this feature?**
Currently, worker node EC2 instances are (by default) created with dynamic/volatile public IPs. This is often sub-optimal:
1. Worker nodes may have to access private/out-of-AWS resources (most notably: private Docker registries) protected by white-list firewall rules.
Worker nodes are expected to have specific public IPs.
2. Accessing NodePort services from outside.
Having predictable public node IPs eliminates need for proxies.

**What feature/behavior/change do you want?**
Provide an option to assign worker nodes public IPs from [AWS Elastic IP](https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html) pool.

One possible implementation outlined in
https://github.com/kubernetes/kops/issues/3182#issuecomment-450398991

**Comment by aparamon** [comment]
@errordeveloper Thank you for your prompt reply!

Indeed, it is possible to associate Elastic IPs manually, but that would have to be done after every scaling/node creation operation. Also, it doesn't seem straightforward:
https://stackoverflow.com/questions/54202575/associate-elastic-ips-with-eks-worker-nodes
A room for some automation!

NLB does solve the problem 2. accessing the services from outside, but not 1. accessing private resources behind white-list firewalls.

**Comment by errordeveloper** [comment]
> Indeed, it is possible to associate Elastic IPs manually, but that would have to be done after every scaling/node creation operation.

So you are saying that you'd like an EIP for each node in a given nodegroup?

> NLB does solve the problem 2. accessing the services from outside, but not 1. accessing private resources behind white-listing firewalls.

Is that for egress? If you use `--private-node-networking`, you will get an EIP which is there for the NAT gateway. And we always have that there, but it only gets used by nodes that are in the private subnets.
I suppose that might work? I understand that maybe somewhat suboptimal.

In any case, if allocating an EIP as part of ASG config is what you want, that can be done easily.

Regarding my suggestion about operator, I mean something that would attach pre-allocated EIPs whenever you create a service which specifies the EIP via an annotation.

**Comment by aparamon** [comment]
> So you are saying that you'd like an EIP for each node in a given nodegroup?

That's how I do currently. It works reliably albeit wasteful on EIPs.

> Is that for egress? If you use `--private-node-networking`, you will get an EIP which is there for the NAT gateway. And we always have that there, but it only gets used by nodes that are in the private subnets.
> I suppose that might work? I understand that maybe somewhat suboptimal.

If all worker nodes do share the same public EIP, that *should* work (at least for outcoming traffic; I'm not sure how NAT will actually resolve incoming traffic from public EIP to worker node NodePorts though). But I'm missing the actual configuration; could you please provide the command that specifies and attaches the EIP?

> In any case, if allocating an EIP as part of ASG config is what you want, that can be done easily.
> 
> Regarding my suggestion about operator, I mean something that would attach pre-allocated EIPs whenever you create a service which specifies the EIP via an annotation.

I think I'm missing the actual details :-) I.e. what is ASG config and what annotations should be placed on what objects?

**Comment by errordeveloper** [comment]
@aparamon I've updated my comment before I noticed your reply, you might want to re-read it. I gathered that there is no actual option for allocating EIPs as part of ASG (surprisingly).

**Comment by aparamon** [comment]
Exactly: [AWS::AutoScaling::LaunchConfiguration](https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html) is missing that.
Method proposed in https://github.com/kubernetes/kops/issues/3182#issuecomment-450398991 hooks into instance userdata.

**Comment by errordeveloper** [comment]
> If all worker nodes do share the same public EIP, that should work (at least for outcoming traffic; I'm not sure how NAT will actually resolve incoming traffic from public EIP to worker node NodePorts though).

I think you'd be looking to use two things:

1. NAT gateway for egress
2. NLB for ingress, which means either EIP per-service, or EIP for service that handles routing to more services internally (if you don't have too many EIPs to spare)

> But I'm missing the actual configuration; could you please provide the command that specifies and attaches the EIP?

We don't have an option to pass pre-allocated EIP just yet, but it can be easily added.

With regards to NLB, see [Kubernetes docs](https://kubernetes.io/docs/concepts/services-networking/service/#network-load-balancer-support-on-aws-alpha). I am not quite sure if they allow you to attach a pre-allocated IP or not exactly.


> Method proposed in kubernetes/kops#3182 (comment) hooks into instance userdata.

We cannot do this, as one of the main design principle is to keep node bootstrap scrip as simple as possible with least number of input variables. The ideal place to do this would be in something like cluster autoscaler or a standalone operator. Hope this makes sense, also it'd mean you could actually re-use this in any Kubernetes cluster on EC2.

**Comment by errordeveloper** [comment]
@aparamon I've sent you a DM on Kubernetes Slack, perhaps better to chat in real time.

**Comment by aparamon** [comment]
Indeed, hooking instance userdata is hackey; let's consider another possibility!

Currently, a [NAT Gateway](https://docs.aws.amazon.com/en_us/vpc/latest/userguide/vpc-nat-gateway.html) for private networks is created and assigned freshly-acquired Elastic IP unconditionally:
https://github.com/weaveworks/eksctl/blob/ac0bbad34031a7f4292304eb44f653631c62392d/pkg/cfn/builder/vpc.go#L63-L83

An option to supplying existing EIP for the NAT Gateway will solve current issue.
Opting NAT Gateway out altogether seems actually useful too, as NAT Gateway incurs additional cost and is not required on default settings (without `--private-node-networking`). [EKS Getting Started Guide](https://docs.aws.amazon.com/en_us/eks/latest/userguide/getting-started.html) doesn't mention NAT Gateway.

What about introducing config parameter `--nat-gateway=VALUE` (default `true`) with the following options:
* `false`: do not create NAT Gateway
* `true`: allocate Elastic IP and use it to create NAT Gateway
* `IP address` or `Elastic IP id`: use this allocated Elastic IP to create NAT Gateway
?

Potential extensions include multiple NAT Gateways, see
https://github.com/weaveworks/eksctl/issues/392

**Comment by mumoshu** [comment]
Hey! Just my two cents but `--nat-gateway-eip=EIP_ALLOCATION_ID` a.k.a:

```yaml
natGateway:
  eip: <EIP_ALLOC_ID>
```

or

```yaml
natGatewayEIP: <EIP_ALLOC_ID>
```

seem to make sense to me in eksctl.

Otherwise, I believe you can use pre-created VPC and subnets, NAT gateways so that you can provide those to eksctl with `eksctl create cluster --vpc-public-subnets <subnet ids separated by commans> --vpc-private-subnets <subnet ids separated by commans>`

For more sources of inspirations, I'd suggest looking into how this has been supported in an another tool.

A managed subnet with pre-created EIP:

https://github.com/kubernetes-incubator/kube-aws/blob/c50c2a030b47043f2064054248b0b0347abd283b/builtin/files/cluster.yaml.tmpl#L970-L976

A managed subnet with pre-created NGW(w/ or w/o EIP. It doesn't matter to the tool):

https://github.com/kubernetes-incubator/kube-aws/blob/c50c2a030b47043f2064054248b0b0347abd283b/builtin/files/cluster.yaml.tmpl#L951-L957

**Comment by mumoshu** [comment]
I believe I understand the use-case that requires what's originally requested in this issue.

You basically need a reliable way to assign EIPs before kubelet talks to the apiserver, in order to build an ingress/egress gateway limited to have a specific set of EIPs.

It is used so that:

- Your customer is able to configure their infrastructure so that they can accept ingress traffic only from those EIPs (The counter-part is the egress gateway w/ EIPs running on the eksctl-managed nodepool)
- Your customer is able to configure their infrastructure so that they can allow egress traffic only to those EIPs (The counter-part is the ingress gateway w/ EIPs running on the eksctl-managed nodepool)

I think I have the same feeling as @errordeveloper here

> The ideal place to do this would be in something like cluster autoscaler or a standalone operator

The only workable solution I have found so far is to use userdata or custom systemd unit, so that you can attach an EIP before kubelet starts talking to the apiserver.

https://github.com/kubernetes-incubator/kube-aws/issues/219

I haven't tried it myself yet but an k8s operator or a daemonset may be used instead if and only if you can reliably update the node IP address stored in K8S. Would assigning EIPs and then restarting every kubelet from the operator/daemonset work...?

**Comment by mumoshu** [comment]
Regardless of the above, If you don't need so many EIPs, or are ok with creating one nodegroup per EIP, what @errordeveloper had summarized above would work best:

> NAT gateway for egress
> NLB for ingress, which means either EIP per-service, or EIP for service that handles routing to more services internally (if you don't have too many EIPs to spare)

**Comment by aparamon** [comment]
@mumoshu Thanks for your comments!

Having individual node EIPs assigned *before* kubelet starts communicating apiserver is not a requirement, fortunately. It is only required that pods use IP from specific pre-defined pool when talking to the outside world, e.g. private Docker repositories.

So "NAT gateway for egress, NLB for ingress" sounds most simple and natural.

**Comment by mumoshu** [comment]
@aparamon Thanks for claryfying!

Yes, "NAT gateway for egress, NLB for ingress" would allow you to prepare EIP before your pods start, which does solve your issue and making the extreme case I've summarized irrelevant.

Nice to see you found a simpler solution for your issue!

**Comment by aparamon** [comment]
Upon `cluster delete`, It's important to make sure EIP is not released if it was not acquired when creating NAT Gateway.

**Comment by aparamon** [comment]
Some considerations on

2. Accessing NodePort services from outside.

One option that is generally working with `eksctl` out-of-the-box is [LoadBalancer services](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer). An AWS [Load Balancer](https://docs.aws.amazon.com/en_us/elasticloadbalancing/latest/classic/introduction.html) is created for every k8s service and is reachable from outside by reported ExternalIP (something like `a218ece131a4011e9a0160683d1063c6-1044786145.eu-central-1.elb.amazonaws.com`).
However, if services are expected to be allocated on specific IP/DNS, it becomes harder to set up. Also, the dynamism of Load Balancers makes it harder to control inbound access rules.

But there is another, apparently simpler alternative: [NodePort services](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport)!
It is possible to do the following:
1. Create a node group in public subnets.
(`-N=1` is sensible).
2. Make the nodes dedicated load balancers:
`kubectl taint node -l alpha.eksctl.io/nodegroup-name=<group-name>
dedicated=foo:NoSchedule dedicated=foo:NoExecute`
3. Allow all traffic from public subnets to private subnets (so dedicated load balancer nodes can access other worker nodes).
4. Allow incoming traffic to public subnets (open ports 30000-32767).
5. Assign Elastic IPs to dedicated load balancer instances.

Now you can access the services by `<EIP>:<NodePort>`!

What do you think of automating it? Maybe something like
`eksctl create lb-nodegroup -N=2 --eip=<EIP>,<EIP>`
or just
`eksctl create lb-nodegroup`
to allocate EIPs automatically, consistently with NAT Gateway?

It is possible to further refine the scheme, by creating dedicated "load balancer" subnets initially, along with current private and public subnets.

**Comment by aparamon** [comment]
Apparently, most of above is covered by https://github.com/weaveworks/eksctl/issues/419, https://github.com/weaveworks/eksctl/issues/448, and https://github.com/weaveworks/eksctl/issues/396. The only remaining part is assignment of EIPs.

**Comment by aparamon** [comment]
@mumoshu The daemonset idea looks appealing!

I'm not sure about `eksctl.io/waiting-for-eip: true` taint though. Removing that in the end will not get apps pods scheduled, as the `eksctl.io/eip-from-pool: pool` is still there. And my initial idea was that load-balancer nodes are dedicated, so no apps pods run on them.
Am I'm missing something?

**Comment by aparamon** [comment]
Related: https://forums.aws.amazon.com/message.jspa?messageID=515725#613460 and the following comment hook into userdata.

**Comment by hden** [comment]
NAT with existing EIP looks awesome.

As for assigning EIP from a work pool, we used a lambda function to routinely scan for new nodes.
The code is available [here](https://github.com/hden/eks-static-ip) if anyone is interested.

**Comment by Jaykah** [comment]
> NAT with existing EIP looks awesome.
> 
> As for assigning EIP from a work pool, we used a lambda function to routinely scan for new nodes.
> The code is available [here](https://github.com/hden/eks-static-ip) if anyone is interested.

@hden for EKS-NODE-POOL=foo , do we just list all IPs, comma separated?

The same question goes for EKS-IP-POOL=bar

Also, I see variables INETANCE_TAG_KEY and INETANCE_TAG_VALUE - should it be INSTANCE_TAG_... instead?

Also, how do you trigger the updates through CloudWatch?

Thanks!

**Comment by hden** [comment]
@Jaykah It's it's slightly off topic for this thread, so maybe we could move discuss it [here](https://gist.github.com/hden/aa7400fb26d0e31490150eca5218e0f9)?

**Comment by werebear73** [comment]
This seems like it is still needed or has something else been done on this?

**Comment by aairbag** [comment]
i am unable to see that a resolution was reached regarding adding this feature. if that is the case, please note there is still interest in being able to assign existing EIPs to NAT gateways and re-opening this issue would be much appreciated, thanks!
