### ISSUE TITLE
In which case eksctl send stack update requests with updated stack tags

### ISSUE THREAD

**Issue by lynnnnnnluo** [weaveworks/eksctl#4400]
We recently noticed requests sent by `eksctl` to update EKS Cluster's stack tags after upgrading `eksctl` to a newer version. Ie. Stack update request updating tag from `alpha.eksctl.io/eksctl-version=0.66.0` to `alpha.eksctl.io/eksctl-version=0.70.0`.  But we don't know which `eksctl` action triggered the stack update request. We did some investigation and found a [function](https://github.com/weaveworks/eksctl/blob/18e4c0d78c36b5eda54f2442b21c1276f6144f1b/pkg/cfn/manager/cluster.go#L99) that attempts to update the stack, and we suspected it would be executed during commands like `eksctl upgrade cluster`,  `eksctl upgrade nodegroup` or `eksctl add nodegroup`. But we couldn't reproduce the CFN stack update request explicity by running these commands on clusters created by a lower version `eksctl`. 

**What help do you need?**
We want to understand which `eksctl` command triggers a cluster stack update. This could be problematic as `eksctl` currently manages cluster version out-of-band. As it described in CFN best [practices](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html), updating resources out-of-band could cause failures in stack update. Understanding when `eksctl` requests stack update will help us avoid failure cases in stack update.

**Comment by dariobritos** [comment]
What drives us to open this request is: this scenario leads to a CFN stack update, where the Cluster may have a lower version in the stack template than the real EKS Cluster version. This is a situation we want to encourage not to happen, and on an ideal scenario, to prohibit.

**Comment by cPu1** [comment]
We have a cluster compatibility check that makes sure the cluster's CloudFormation stack is compatible with new features. This check is performed when creating a new nodegroup or upgrading the EKS version. A cluster stack update can happen if the cluster was created from an older eksctl version and a newer version added or updated the CloudFormation resources used to create the cluster stack. This will also update the `alpha.eksctl.io/eksctl-version` tag to match the new version. 

>What drives us to open this request is: this scenario leads to a CFN stack update, where the Cluster may have a lower version in the stack template than the real EKS Cluster version.

You might be right. When performing the stack update, eksctl might be setting the EKS version in the CFN template to the `metadata.version` value in the supplied ClusterConfig file. The version in the config file may be older than the real EKS version and that can cause issues. 

@lynnnnnnluo do you have the change-set for the CFN stack update?

**Comment by cPu1** [comment]
> We have a cluster compatibility check that makes sure the cluster's CloudFormation stack is compatible with new features. This check is performed when creating a new nodegroup or upgrading the EKS version. A cluster stack update can happen if the cluster was created from an older eksctl version and a newer version added or updated the CloudFormation resources used to create the cluster stack. This will also update the `alpha.eksctl.io/eksctl-version` tag to match the new version.
> 
> > What drives us to open this request is: this scenario leads to a CFN stack update, where the Cluster may have a lower version in the stack template than the real EKS Cluster version.
> 
> You might be right. When performing the stack update, eksctl might be setting the EKS version in the CFN template to the `metadata.version` value (instead of the current EKS version) in the supplied ClusterConfig file. The version in the config file may be older than the real EKS version and that can cause issues.
> 
> @lynnnnnnluo do you have the change-set for the CFN stack update?


@lynnnnnnluo, @dariobritos: Does this help answer your question?

**Comment by lynnnnnnluo** [comment]
Yes, thank you for your answer.

**Comment by cPu1** [comment]
> Yes, thank you for your answer.

Great. I'll close the issue.
