### ISSUE TITLE
Calling bottle :unneeded is deprecated!

### ISSUE THREAD

**Issue by ChapChap** [weaveworks/eksctl#4404]
I use eksctl with Homebrew and there is a Warning during the upgrade procedure (brew upgrade):
My Homebrew version is:

```plaintext
Homebrew 3.3.2
Homebrew/homebrew-core (git revision 30e562cdb75; last commit 2021-11-03)
Homebrew/homebrew-cask (git revision e6ca08b2e0; last commit 2021-11-03)
```

And the warning is:

```plaintext
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the weaveworks/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap/Formula/eksctl.rb:9
```

The deprecation was introduced in [this PR](https://github.com/Homebrew/brew/pull/11239)
This PR https://github.com/weaveworks/homebrew-tap/pull/29 is the fix

**Comment by aclevername** [comment]
Thanks for issue and alerting us to the pr @ChapChap . We will take a look :smile:

**Comment by aclevername** [comment]
We've merged the changes. I'm guessing tomorrows release should fix the issue :smile: Thanks @ChapChap !
