### ISSUE TITLE
Add `kubernetes.io/role/elb:1` tag to public networks

### ISSUE THREAD

**Issue by artemyarulin** [weaveworks/eksctl#442]
eksctl already adds tags to private subnets, but doesn't do it for public subnets. If it would add `kubernetes.io/role/elb = 1` to public subnets then auto subnet discovery from ingress like `aws-alb-ingress-controller` would work from the box 

From https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/walkthrough/echoserver/#deploy-ingress-for-echoserver 
```
Adding tags to subnets for auto-discovery you must include the
following tags on desired subnets.

- kubernetes.io/cluster/$CLUSTER_NAME where $CLUSTER_NAME 
  is the same CLUSTER_NAME specified in the above step.
- kubernetes.io/role/internal-elb should be set to 1 or an empty tag
  value for internal load balancers.
- kubernetes.io/role/elb should be set to 1 or an empty tag value for
  internet-facing load balancers.
```
eksctl already does 2 from 3, would be nice to have last one covered as well.

As I can see it could be easily added in https://github.com/weaveworks/eksctl/blob/ac0bbad34031a7f4292304eb44f653631c62392d/pkg/cfn/builder/vpc.go#L18-L23

Related issue https://github.com/weaveworks/eksctl/issues/53

**Comment by errordeveloper** [comment]
Yew, looks like an easy fix. I'll open a PR shortly.

**Comment by errordeveloper** [comment]
Please note this will only be available in newly created clusters, we have `eksctl utils update-cluster-stack` that is capable of appending new resources to a stack, but it's strictly append-only.

See here: https://github.com/weaveworks/eksctl/blob/56cb79a579d4ccaf31f5acc171c20f8ddba7e74e/pkg/cfn/manager/cluster.go#L64-L73

**Comment by artemyarulin** [comment]
Thank you very much - I'll simply re-create my dev cluster 👍

**Comment by errordeveloper** [comment]
This will be available in the next release, which we've not wrapped up yet, it will likely go out tomorrow. In the meantime, perhaps you can build from master?

**Comment by artemyarulin** [comment]
Ah no, I'm not good with Go and for sure can wait, thank you :)
