### ISSUE TITLE
creation of cluster fails due to prior failed cluster creation

### ISSUE THREAD

**Issue by leongross** [weaveworks/eksctl#4438]
**What were you trying to accomplish?**

I wanted to create an eks cluster using eksctl provided a `cluster.yaml` file.

**What happened?**

The creation failed, due to the existence of already too many gateways. I deleted the some so there will be spaces for a new one.
After that I ran `eksctl cluster create -f cluster.yaml` again, and got prompted the error message shown in the `Logs` section of this Issue. Like suggested I ran `eksctl delete cluster --region=us-east-2 --name=test-cluster-1` and received the second log entry stating, that there was nothing to delete.
I am opening this issue, because I don't think that it is intended that
1. The resources in my aws account are not cleared when the creation fails
2. If the resources are not cleared, another creation process cannot be appended to the first
3. The suggested cleanup command fails

**How to reproduce it?**

0. create config file cluster.yaml:
```yaml
apiVersion: eksctl.io/v1alpha5
 kind: ClusterConfig

 metadata:
   name: test-cluster-1
   region: us-east-2

 nodeGroups:
   - name: c5a-nodes
     instanceType: c5a.2xlarge
     desiredCapacity: 2
``` 
1. `eksctl cluster create -f cluster.yaml`
2. `eksctl delete cluster --region=<YOUR-REGION> --name=test-cluster-1`
**Logs**

```
2021-11-10 09:46:13 [ℹ]  building cluster stack "eksctl-test-cluster-1-cluster"
2021-11-10 09:46:13 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2021-11-10 09:46:13 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-2 --name=test-cluster-1'
2021-11-10 09:46:13 [✖]  creating CloudFormation stack "eksctl-test-cluster-1-cluster": AlreadyExistsException: Stack [eksctl-test-cluster-1-cluster] already exists
	status code: 400, request id: 1ad96a45-3fb3-43b5-9a6d-6f91fa3368e1
```

```
Error: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: test-cluster-1.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "c4518613-8571-427d-8d92-47a67cad610b"
  },
  Message_: "No cluster found for name: test-cluster-1."
}
```

**Anything else we need to know?**

**Versions**

```
eksctl version: 0.71.0
kubectl version: v1.22.3
OS: linux
```

**Comment by Spongman** [comment]
i have the same issue. can't create _or_ delete cluster.

**Comment by kryfin** [comment]
Got the same issue, but resolve when change the default region to required region, hope it will help in the future


eksctl delete cluster --region=<YOUR-REGION> --name=test-cluster-1

**Comment by Spongman** [comment]
ugh. stalebot closing issues is a guarantee of decreased quality.
