### ISSUE TITLE
Add integration tests for running workloads on WindowsServer20H2CoreContainer

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4441]
As from the [PR ](https://github.com/weaveworks/eksctl/pull/4442/files) the section for WindowsServer20H2CoreContainer was removed, so we need to add tests for that.
We need to figure out how to make this test work, see PR description for more details

**Comment by Himangini** [comment]
@cPu1 can this be closed now?

**Comment by cPu1** [comment]
> @cPu1 can this be closed now?

No, this isn't done.
