### ISSUE TITLE
Add Integration test for eksctl associate identityprovider command

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#4443]
# Description
According to the testing spike doc, there is no integration test for `eksctl associate identityprovider` command. 

# Scope
- Validate whether this command's functionality is tested elsewhere in the integration tests or not [collect all the scattered bits in one place if possible?]
- Add integration tests to cover the functionality of this command

# Acceptance Criteria
- As a developer
- I should be able to test this command's functionality by running the integration suite.

**Comment by cPu1** [comment]
>Validate whether this command's functionality is tested elsewhere in the integration tests or not [collect all the scattered bits in one place if possible?]

This command isn't tested in any of the integration tests.
