### ISSUE TITLE
Add integration test for eksctl completion [bash, fish, powershell, zsh]

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#4446]
# Description
According to the testing spike doc, there are no integration tests for `eksctl completion` [bash, fish, powershell, zsh] commands. 

# Scope
- Validate whether this command's functionality is tested elsewhere in the integration tests or not [collect all the scattered bits in one place if possible?]
- Add integration tests to cover the functionality of this command

# Acceptance Criteria
- As a developer
- I should be able to test this command's functionality by running the integration suite.

**Comment by Himangini** [comment]
Overkillllllll, not happening bro

**Comment by reduardo7** [comment]
It's possible!

Simply add to your `~/.bashrc`(or related file) the following command:

```bash
. <(eksctl completion bash)
```

And it is working for other tools:

```bash
. <(kubectl completion bash)
. <(eksctl completion bash)
. <(helm completion bash)
. <(stern --completion bash)
. <(velero completion bash)
```

**Comment by cPu1** [comment]
> It's possible!
> 
> Simply add to your `~/.bashrc`(or related file) the following command:
> 
> ```shell
> . <(eksctl completion bash)
> ```
> 
> And it is working for other tools:
> 
> ```shell
> . <(kubectl completion bash)
> . <(eksctl completion bash)
> . <(helm completion bash)
> . <(stern --completion bash)
> . <(velero completion bash)
> ```

Of course it's possible. We already have this in our docs: https://eksctl.io/introduction/#shell-completion

This issue was for adding tests for the shell completion feature and it was decided it was too much work for little value.
