### ISSUE TITLE
Add integration test for eksctl utils schema command

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#4448]
# Description
According to the testing spike doc, there are no integration tests for `eksctl utils schema` command. 

# Scope
- Validate whether this command's functionality is tested elsewhere in the integration tests or not [collect all the scattered bits in one place if possible?]
- Add integration tests to cover the functionality of this command

# Acceptance Criteria
- As a developer
- I should be able to test this command's functionality by running the integration suite.

**Comment by Skarlso** [comment]
I don't think we need an integration test for

```go

func doSchemaCmd(cmd *cmdutils.Cmd) {
	fmt.Printf("%s", api.SchemaJSON)
}
```

**Comment by Skarlso** [comment]
Fine, you know what?! I'm gonna write one anyways. :D
