### ISSUE TITLE
Create OIDC provider for cluster if it does not exist yet

### ISSUE THREAD

**Issue by leongross** [weaveworks/eksctl#4453]
**What feature/behavior/change do you want?**
When creating an eks cluster there is no option to create an OIDC provider for that cluster as well. This is interesting when working with k8s csi storage drivers.

**Why do you want this feature?**
Here is a related issue [#1010](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1010) I resolved in the context of aws-ebs-csi-driver.

**Comment by cPu1** [comment]
You're looking for the `iam.withOIDC` field. It creates the IAM OIDC provider and also enables IAM Roles for Service Accounts for the CNI plugin. 

>This is interesting when working with k8s csi storage drivers.

eksctl also recognises the EBS CSI controller and can be configured in `iam.serviceAccounts`. A full example can be found in the examples directory: https://github.com/weaveworks/eksctl/blob/main/examples/13-iamserviceaccounts.yaml

**Comment by leongross** [comment]
@cPu1 Thank you for your fast reply. I must have overread this!
I found the toggle flag `--with-oidc` in the help for `eksctl create cluster` which seems quite right.
I did not find any documentation regarding the samples. Is it the right approach to call the example you linked like this?
```bash
$ eksctl create iamserviceaccount -f examples/13-iamserviceaccounts.yaml
```

**Comment by Skarlso** [comment]
@leongross Hi! Is this still an issue for you or have you resolved it? Do you still require an update / help with `iamserviceaccount`? Sorry, for the late response, we must have missed the ping.

**Comment by cPu1** [comment]
> @cPu1 Thank you for your fast reply. I must have overread this! I found the toggle flag `--with-oidc` in the help for `eksctl create cluster` which seems quite right. I did not find any documentation regarding the samples. Is it the right approach to call the example you linked like this?
> 
> ```shell
> $ eksctl create iamserviceaccount -f examples/13-iamserviceaccounts.yaml
> ```

Yes, that is the correct syntax. Please let us know if your issue is resolved so we can close it.

**Comment by leongross** [comment]
yes, this can be resolved
