### ISSUE TITLE
--approve flag in eksctl delete nodegroup command

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#4461]
While investigating https://github.com/weaveworks/eksctl/issues/3977 @Skarlso found that `--approve` flag in `eksctl delete nodegroup` command doesn't have the intended behaviour.
Investigate why is this so if possible and fix this behavior. 
Also, update tests and docs if required.

**Comment by Himangini** [comment]
If there's a breaking change then highlight the possible implication before merging changes

**Comment by cPu1** [comment]
Adding an `--approve` flag to `eksctl delete nodegroup` would be a significant breaking change as the default behaviour will now skip deletion, causing nodegroups to lie around in the cluster. We'll likely not go ahead with adding an `--approve` flag to `eksctl delete nodegroup`.
