### ISSUE TITLE
Remove hard-coding of version `1.10.0` as the default vpc-cni addon versions for ipv6

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#4477]
As part of https://github.com/weaveworks/eksctl/pull/4473 we added logic so that if the user provides `addon.Version = ""` for `vpc-cni`, we mutate it to `1.10.0` as this is the minmum supported version. If we had *not* done this then the version would of defaulted to whatever the EKS API has as the addon version as default, which at the time of writing is `1.7.5`, which is not supported for ipv6.

Revert this https://github.com/weaveworks/eksctl/pull/4473/commits/5150ae3904e6ac07791ca7015afefb0b234c3d25 commit when the default cluster version reaches >= 1.10.0

**Comment by Himangini** [comment]
Spike first here to investigate how much work is involved in upgrading to a higher version.
Document the findings here.

Timebox: 1-2 days.

**Comment by Skarlso** [comment]
https://github.com/weaveworks/eksctl/issues/5336 should also be fixed by this.

**Comment by Skarlso** [comment]
Funny enough, AWS still has 1.10 as a default version.
