### ISSUE TITLE
Windows Pods cannot talk to ClusterIP Service

### ISSUE THREAD

**Issue by harisokanovic** [weaveworks/eksctl#4481]
I have a networking issue in Windows workloads on my EKS cluster: Windows containers cannot open TCP connections to Service IPs, but Pod IPs function correctly. This is happening in both "WindowsServer2019FullContainer" and "WindowsServer20H2CoreContainer" (recently added) amiFamily in a Kubernetes 1.21 cluster created using eksctl.

I'm not sure if this is a configuration problem on my part or some known issue with Windows containers. Any advice is greatly appreciated. Thanks.

Steps to reproduce, files attached below:

1. Create cluster and deploy workloads:
`eksctl create cluster --config-file netbugdemo.yaml.txt --install-vpc-controllers`
`kubectl apply -f netbugdemo-pods.yaml.txt`
2. Get Pod and service IPs for the demo HTTP server:
POD_IP = `kubectl -n netbugdemo get pod -l 'app=kuard' -o jsonpath='{.items[0].status.podIP}'`
SERVICE_IP = `kubectl -n netbugdemo get service kuard -o jsonpath='{.spec.clusterIP}'`
3. List Pod names running on Linux and Windows nodes:
`kubectl -n netbugdemo get pod -l 'app=lin'`
`kubectl -n netbugdemo get pod -l 'app=win'`
4. Both IPs accessible from Linux:
`kubectl -n netbugdemo exec -it LINUX_POD_NAME -- /bin/bash`
`apt-get update`
`apt-get install curl`
`curl "http://POD_IP:8080/healthy"`
`    # 200 OK`
`curl "http://SERVICE_IP:8080/healthy"`
`    # 200 OK`
5. Service IP fails on Windows, Pod IP works, same behavior in both 2019 and 20H2:
`kubectl -n netbugdemo exec -it WINDOWS_POD_NAME -- powershell`
`Invoke-WebRequest -UseBasicParsing -Uri "http://POD_IP:8080/healthy"`
`    # 200 OK`
`Invoke-WebRequest -UseBasicParsing -Uri "http://SERVICE_IP:8080/healthy"`
`    # ERROR: Unable to connect`

~~My `eksctl version` is `0.76.0-dev+4e933746.2021-11-18T15:49:08Z` built from `main`. I'm using this unreleased build to access the recently added "WindowsServer20H2CoreContainer" amiFamily. However, this issue also appears in "2019Full".~~

Update: You can now reproduce this issue with the 0.76 release, which includes "WindowsServer20H2CoreContainer" amiFamily.

[netbugdemo-cluster.yaml.txt](https://github.com/weaveworks/eksctl/files/7571739/netbugdemo-cluster.yaml.txt)
[netbugdemo-pods.yaml.txt](https://github.com/weaveworks/eksctl/files/7571744/netbugdemo-pods.yaml.txt)

### Summary
- We need to use the steps and files provided and reproduce this error
- If we can reproduce it then work on a fix [if possible]
- This probably might be a windows thing so we need to investigate if we can actually need to fix this at all

**Comment by Himangini** [comment]
Hi @harisokanovic! Thanks for creating a help ticket. We will look into this and get back to you 👍🏻

**Comment by harisokanovic** [comment]
Hi @Himangini, do you have any suggestions on a fix or workaround?

**Comment by nikimanoledaki** [comment]
Thanks for opening this issue @harisokanovic I can confirm that I was able to reproduce this with the info provided. 

After taking apart the configuration you shared with us (very detailed, thanks! ✨) I narrowed down the problem to setting a value (any value!) for `serviceIPv4CIDR` in the config file, for Windows Pods running on Windows Nodes only. I tried with managed and unmanaged Linux Nodes and was not able to reproduce this. 

The configuration you have works if you omit setting `serviceIPv4CIDR` in the eksctl config file. :) 

I'm digging into eksctl to find out what the link is between `serviceIPv4CIDR` and Windows.

**Comment by nikimanoledaki** [comment]
I couldn't find any discrepancies in eksctl and went through the networking config again. I'd made a mistake in one of my tests, so I tried it again. Setting `serviceIPv4CIDR` to `10.100.0.0/16` (the default EKS Service IPv4 CIDR) works for Windows too! :) 

Feel free to set it to `10.100.0.0/16` or omit this field altogether if it's not needed to avoid these kinds of networking clashes. 

This field's intended usage is for specific scenarios to have fine-grained control of the networking config:

> While this worked for most cases, customers with VPCs peered to on-premise networks or other Amazon VPCs found that the EKS chosen Kubernetes service IP address range may conflict with other IP ranges in use across their network.

(from [EKS](https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-eks-supports-configurable-kubernetes-service-ip-address-range/))

I hope this helps. Feel free to reopen this issue or open a new one if you need any help.

**Comment by harisokanovic** [comment]
Thanks. I think the `10.100.0.0/16` range should work in most cases. However, are there other ranges that would work on Windows, in the event that `10.100.0.0/16` is unavailable?
