### ISSUE TITLE
Instructions for Docker Image

### ISSUE THREAD

**Issue by fabltd** [weaveworks/eksctl#4482]
Please include instructions on how to use the docker image. There is nothing here or on docker hub.

**Comment by nikimanoledaki** [comment]
Thanks @fabltd, we'll make sure to add more info about this in the eksctl docs. 👍

**Comment by nikimanoledaki** [comment]
In the meantime, here's the quickest way to pull and use the eksctl docker image:
```
docker pull weaveworks/eksctl
docker run -it weaveworks/eksctl eksctl --help
```

**Comment by fabltd** [comment]
Thanks

Is there an arm64 build (Mac Silicon)
