### ISSUE TITLE
write-kubeconfig should also write out the value of AWS_PROFILE when set via the environment

### ISSUE THREAD

**Issue by kenaniah** [weaveworks/eksctl#4483]
As you all know, when using multiple accounts or US GovCloud, it is often helpful to separate the credentials into multiple profiles to set the `AWS_PROFILE` environment variable accordingly. Fortunately, eksctl already respects the environment variable when invoking...

```bash
export AWS_PROFILE=us-govcloud
eksctl get clusters # automatically uses the "us-govcloud" profile

# Per-command invocation works as well
AWS_PROFILE=canada eksctl get clusters # automatically uses the "canada" profile (for just this invocation)
```

That said, `eksctl utils write-kubeconfig` behaves differently depending on how the profile is set:

```bash
# Using AWS_PROFILE from the env does not persist it to the kubeconfig file
AWS_PROFILE=canada eksctl utils write-kubeconfig <cluster-name> 
# Writes out AWS_DEFAULT_REGION and AWS_STS_REGIONAL_ENDPOINTS to kubeconfig file

# Passing --profile explicitly works as intended
eksctl utils write-kubeconfig <cluster-name> --profile canada 
# Writes out AWS_DEFAULT_REGION, AWS_STS_REGIONAL_ENDPOINTS, and AWS_PROFILE to kubeconfig file
```

As a user, I would expect a value for `AWS_PROFILE` to be written out the the kubeconfig in both of these cases. Could this behavior please be made consistent in an upcoming release?

eksctl info:
```
eksctl version: 0.69.0
kubectl version: v1.22.2
OS: darwin
```

**Comment by cPu1** [comment]
I can confirm that the generated kubeconfig does not contain `AWS_PROFILE` when it's passed as an environment variable. 

>As a user, I would expect a value for AWS_PROFILE to be written out the the kubeconfig in both of these cases. Could this behavior please be made consistent in an upcoming release?

We'll add this to the backlog and work on it soon.

**Comment by Skarlso** [comment]
@kenaniah Sorry for the delay. We are overwhelmed with commitments. If anyone wants to chip in we greatly appreciate PRs. :)
