### ISSUE TITLE
Add support for G5 instance class

### ISSUE THREAD

**Issue by fortejas** [weaveworks/eksctl#4503]
**Why do you want this feature?**

There's newly released [G5 Instance Types](https://aws.amazon.com/blogs/aws/new-ec2-instances-g5-with-nvidia-a10g-tensor-core-gpus/). Would be great to be able to deploy these with `eksctl`.

**Comment by isaac-ward** [comment]
Hi fortejas - was this feature implemented? I am having some trouble using g5 instances - the EC2 instances spin up but the nodes never join the cluster and become ready in the nodegroup.

Is it possible to use g5 instances currently with EKSCTL?

**Comment by fortejas** [comment]
@isaac-ward I saw the same behavior but I think https://github.com/awslabs/amazon-eks-ami/issues/806 is the more relevant issue rather than something not working with eksctl specifically
