### ISSUE TITLE
Configure DNS64 and NAT64 for IPv6 subnets

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#4505]
Part of https://github.com/weaveworks/eksctl/issues/4255

**Description**
Background info: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html#nat-gateway-nat64-dns64

DNS64 and NAT64 must be configured on all IPv6 subnets to enable communication with IPv4-only services.

**1. Enable DNS64**
Add functionality so that, when creating IPv6 subnets, all subnets  (except for fully private ones) are created with the `enableDNS64` param.

**2. Add route for NAT64**
In the current [worfklow](https://github.com/weaveworks/eksctl/blob/ipv6/pkg/cfn/builder/vpc_ipv6.go), we already create the `0.0.0.0/0` <-> NATGW route and the `::0` <-> NATGW route for all subnets. 

We only need to create a route between the NATGW and `64:ff9b::/96` in the IPv6 CIDR. 

**3. Update SG**
Modify the cluster SG and NACLs to allow egress and ingress traffic to `64:ff9b::/96` traffic.

**Scope**
- Modify subnets to enable DNS64
- Create an additional `EC2::Route` for NAT64 to translate IPv4 traffic
- Update SG role 

**Acceptance Criteria**
As an eksctl user with an IPv6 cluster,
I should be able to see that DNS64 is enabled on all my subnets,
And I should be able to see that NAT64 translates IPv4 traffic,
And I should be able to make an IPv4 request to a service running on my IPv6 cluster.

**Comment by Himangini** [comment]
NAT64 is not out yet

**Comment by Himangini** [comment]
Need to update the go formation library since we use our own fork

**Comment by aclevername** [comment]
It looks like you can enable dns64 after the subnet is created: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifySubnetAttribute.html
