### ISSUE TITLE
failed to create service account <namespace>/default: serviceaccounts "default" already exists

### ISSUE THREAD

**Issue by kahirokunn** [weaveworks/eksctl#4522]
Sometimes, in OSS helm charts, the service account name cannot be changed from the default one.
I want it to work with the default service account as well.

**Comment by Himangini** [comment]
@kahirokunn can you provide more context? Are you still facing this issue? We're happy to accept any PRs if you have a fix in mind :)
> Sometimes, in OSS helm charts, the service account name cannot be changed from the default one.
I want it to work with the default service account as well.

**Comment by kahirokunn** [comment]
Sorry, I haven't done anything to fix this.
Perhaps if you modify the create cluster to enable the override-existing-seriviceaccount option, it might work.

https://github.com/weaveworks/eksctl/pull/4523#issuecomment-1021907583
