### ISSUE TITLE
how to import values from cloudformation stack to eksctl

### ISSUE THREAD

**Issue by NJ24-LAB** [weaveworks/eksctl#4529]
i need to import values from cloudformation stack to eksctl cluster config file.

for example:

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: us-east-2

vpc:
  id: Fn::ImportValue: !Sub VPCId 
  subnets:
    private:
      us-east-2a:  Fn::ImportValue: "TestVpc-PrivateSubnet1" 
      us-east-2b:  Fn::ImportValue: "TestVpc-PrivateSubnet2" 

nodeGroups:
  - name: ng-1
    privateNetworking: true
    instanceType:
    desiredCapacity: 1
    minSize: 1
    maxSize: 2

If i import values with the above method am getting error

Error: loading config file "cluster.yaml": error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"Fn::ImportValue":"VPCId"}

Kindly help me fix this issue

**Comment by cPu1** [comment]
That's not supported. The YAML file passed to eksctl is not processed for any CloudFormation intrinsic function references. You'll have to obtain the output values yourself, e.g., using `aws cloudformation describe-stacks`, and pass the YAML to an external tool like `envsubst` before passing it to eksctl.
