### ISSUE TITLE
Cannot create managed nodegroup in private subnet

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#4530]
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jk
  region: ap-northeast-2
  version: "1.21"

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

iam:
  withOIDC: true

managedNodeGroups:
  - name: mng-1-private
    desiredCapacity: 1
    subnets:
    - subnet-0ad218f2e9514bc04
```

```
./eksctl create nodegroup -f jk-ipv6.yaml
2021-12-09 10:25:27 [ℹ]  eksctl version 0.70.0-dev+10620385.2021-12-09T10:14:07Z
2021-12-09 10:25:27 [ℹ]  using region ap-northeast-2
2021-12-09 10:25:35 [ℹ]  nodegroup "mng-1-private" will use "" [AmazonLinux2/1.21]
2021-12-09 10:25:39 [✖]  found mis-configured subnets ["subnet-0ad218f2e9514bc04"]. Expected public subnets with property "MapPublicIpOnLaunch" enabled. Without it new nodes won't get an IP assigned
Error: subnets for one or more new nodegroups don't meet requirements. To fix this, please run `eksctl utils update-legacy-subnet-settings --cluster jk`
```

`subnet-0ad218f2e9514bc04` is a private subnet, but the code seems to be treating it as a public subnet.

**Comment by Himangini** [comment]
We need to update the error message here for better UX, perhaps need to improve on the docs for this as well.

**Comment by Himangini** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-PitchBlack-60ed85b4f8399b0017862dbd/issues/weaveworks/eksctl/4530?planning-poker) with ZenHub @aclevername @cPu1 @nikimanoledaki @Skarlso

**Comment by cPu1** [comment]
This is actually a missing feature in eksctl and not necessarily a bug. When a subnet ID is specified for a nodegroup, eksctl does not try to determine whether that subnet is private or public, and infers this property from the `privateNetworking` field. In your example, eksctl infers that the subnet is public since the `privateNetworking` field is not set. I think we can improve the UX here by returning a more useful error message.

**Comment by Skarlso** [comment]
To be honest, this feels like trying to mind read. How would we know in what context the user was trying to do something. This feels like we are trying to tell the user everything that MIGHT be wrong with their setting, which is incredibly lot. In any case, I can add something like, make sure the subnet is public in case that's desired. But that's all.

**Comment by Skarlso** [comment]
Note, I have a solution, manually testing it's viable now.
