### ISSUE TITLE
should be able to specify CIDR for each subnet

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#455]
As of 0.1.19, we allow importing existing subnets and (optionally) specifying CIDRs along with the IDs. It should be possible to specify the CIDRs without the IDs, to override automated slicing of given VPC CIDR.

**Comment by martina-if** [comment]
Removed from milestone because it can be done without bumping the api version (it's a non breaking change)

**Comment by aclevername** [comment]
https://github.com/weaveworks/eksctl/pull/3229
