### ISSUE TITLE
EBS CSI Policy Addon Uses Incorrect ARN for Gov Cloud

### ISSUE THREAD

**Issue by timfallmk** [weaveworks/eksctl#4551]
The addon policy for the EBS CSI driver uses the `aws` arn to reference this policy. GovCloud `arn`'s [start with a unique string](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html). We should probably detect the expected arn from the region or profile endpoint.

![image](https://user-images.githubusercontent.com/5316117/146662594-ef837997-277b-40ea-9894-d6281b1f2da4.png)

**Comment by Skarlso** [comment]
Hi.

Luckily, this is already fixed in main, but not released yet. Maybe next week it will make it into the release. :) 

Thanks!

Related PR: https://github.com/weaveworks/eksctl/pull/4547

**Comment by timfallmk** [comment]
Thanks! Will close.

**Comment by nikimanoledaki** [comment]
As a follow-up, @Skarlso's fix to this issue was included in today's Release Candidate, which can be found here: https://github.com/weaveworks/eksctl/releases/tag/v0.78.0-rc.0

Feel free to reopen this if the issue persists (though we won't be able to get back to you until Jan 3d). 

Thanks! :)
