### ISSUE TITLE
G5.* instance not recognized as accelerated instances (does not use the EKS Accelerated AMI)

### ISSUE THREAD

**Issue by amrragab8080** [weaveworks/eksctl#4559]
If you create a nodegroup with `eksctl create nodegroup` using `--node-type g5.4xlarge` it doesnt recognize this instance family as a accelerated instance type and thus doesnt use the EKS Accelerated GPU AMI once the NV K8s device plugin is applied it fails since the nvidia-container-runtime stack is not installed on the standard EKS AMI.
```
2021/12/21 22:35:33 Loading NVML
2021/12/21 22:35:33 Failed to initialize NVML: could not load NVML library.
2021/12/21 22:35:33 If this is a GPU node, did you set the docker default runtime to `nvidia`?
2021/12/21 22:35:33 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2021/12/21 22:35:33 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
2021/12/21 22:35:33 If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
```

eksctl version: 0.75.0
kubectl version: v1.22.4
OS: darwin

**Comment by Skarlso** [comment]
https://github.com/weaveworks/eksctl/pull/4550

**Comment by Skarlso** [comment]
Hi, there is a pull request which will be merged and released after the holidays.

Thanks for your issue! :)

**Comment by cPu1** [comment]
This is closed by https://github.com/weaveworks/eksctl/pull/4550 and will be out in a new release this week.
