### ISSUE TITLE
Ability to update existing eks cluster via config file

### ISSUE THREAD

**Issue by haofeif** [weaveworks/eksctl#4586]
**What feature/behavior/change do you want?**
* I want eksctl to support `eksctl apply -f config-file.yaml`. Now it only supports create and delete. 

**Why do you want this feature?**
* I am using config file as the source of truth to deploy my eks cluster via eksctl, which is superb convenient,  just like how i deploy my Kubernetes manifest or AWS CloudFormation.  I found out that (correct me if I am wrong) once i create the EKS cluster via eksctl, I cannot make changes to the config file and deploy the changes. 
* i.e. I want to add additional fields to "addons", or I want to change the instance types of my nodes. 
I only found `eksctl create cluster` and `eksctl delete cluster`. I tried `eksctl upgrade cluster` but it does not apply the changes that I need.
That is why I am proposing to have something like `eksctl apply` function just like how kubectl does. 
* Note: I am using the latest eksctl version 0.77.0

**Comment by cPu1** [comment]
Hey @haofeif, we already have an issue open for such a feature: https://github.com/weaveworks/eksctl/issues/2774

I'm closing this as a duplicate. Please feel free to open a new issue if you have any more feature requests or questions.
