### ISSUE TITLE
`build-all-distros` job intermittently fails with a timeout error

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4589]
[This run](https://app.circleci.com/pipelines/github/weaveworks/eksctl/9922/workflows/311e014c-880b-4ad2-adcb-483eb1edf2eb/jobs/13710) failed with a timeout error:

`Timeout exceeded: try increasing it by passing --timeout option`.

This can be fixed by increasing the timeout for `golangci-lint run`.

**Comment by Himangini** [comment]
@Himangini find out why we have this job , add a ticket for this

**Comment by Skarlso** [comment]
@Himangini Why is this reopened?

**Comment by Himangini** [comment]
> @Himangini Why is this reopened?

@Skarlso I am messing with the board. don't worry about it
