### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#46]
We could probably add some unit tests, but the critical code path is reliant on AWS APIs and mocking CloudFormation is going to involve a lot of effort due to its complex nature (unless there is something ready-made we can use). Also, we would also need to mock Kubernetes somehow, there is probably prior art, but that could be very specialised. Personally, I feel that integration test is what we need the most.

**Comment by errordeveloper** [comment]
We might want to start on this before 0.1.0, but I wouldn't block 0.1.0 on lack of automated testing, unless others strongly object.

**Comment by richardcase** [comment]
@errordeveloper - happy to look at this if you want?

**Comment by Raffo** [comment]
Happy to help with the review @richardcase 😉

**Comment by errordeveloper** [comment]
Hey folks, please go ahead! Would be good to outline a short plan and
discuss it before anyone spends a lot of time on this.

**Comment by Raffo** [comment]
Sounds good to me. 

@richardcase what's your plan for that?

**Comment by richardcase** [comment]
@Raffo - i will have a look and come up with a plan.  

There are things like [localstack](https://github.com/localstack/localstack) and also the Go SDK has interfaces for the services to help build mocks, [like](https://github.com/aws/aws-sdk-go/blob/master/service/cloudformation/cloudformationiface/interface.go) this for CloudFormation (i haven't checked interfaces for the other dependent services like STS).

**Comment by Raffo** [comment]
I think the approach with interfaces would be good and that's what I've used in the past. We've used a similar approach while implementing testing for external DNS here: https://github.com/kubernetes-incubator/external-dns/blob/master/provider/aws.go#L79

**Comment by richardcase** [comment]
@Raffo @errordeveloper - what about the following initially:

- Add tests to each of the packages (like we've done with the kubeconfig change). The decision here is whether the tests for a package are contained within the package and have access to all the non-exported functions/structs/etc or if instead the tests site in a test package and test only via the exported functions/structs/etc (seeing only what the user of the package would see). I used the later for the kubeconfig tests.
- We can mock the AWS services using the interfaces and inject these mocks where required for the unit tests (this may require some refactoring).
- We create a separate integration test suite that tests against AWS (when we've worked out who can pay/sponsor). I quite like how minikube have done [this](https://github.com/kubernetes/minikube/tree/master/test/integration). We'd have to perform operations with eksctl and then check its done what we expected using the AWS sdk directly (or something else).
- Start with the `get` command
- Add code coverage output

So just standard testing.

**Comment by errordeveloper** [comment]
I would start by finding out what it takes to mock CloudFormation, as to me it seem kind of complex, but may I just don't know. In my mind integration tests (besides the question of who gets the bill) would buy as more for much less code, testing different code-path maybe be tricky, but starting by simply testing `eksctl create cluster` seems plausible to me. If you folks are quite comfortable with mocking CloudFormation, I won't oppose – right now, I am just unable to imagine how it would work (seems like it would be a lot of code)...

**Comment by richardcase** [comment]
I've started to look at this and using mockery to mock the AWS services. I've one test working now, not a lot i know but just to prove that the approach works.

Shall i create a WIP branch / PR so that you can see the progress?

**Comment by Raffo** [comment]
Nice that the first tests are now merged. Now that we have a base for the tests in place we can probably go in parallel and add more.

**Comment by richardcase** [comment]
I'll look at adding a base integration test now.

**Comment by errordeveloper** [comment]
@richardcase should we make integration tests a requirement for one of the next patch releases? Manual test would be okay for now, as long as it's well defined (not just "create a cluster and deploy some app, then check it works, run e2e suite if in doubt"). We might want to look into running conformance suite, but I think deploying some workloads would be just fine for now. My colleague @dlespiau wrote  a very nice and simple [library](https://github.com/dlespiau/kube-test-harness) that should help with this, we are using it in a few projects already. I think eventually it'd be nice to allow users to easily validate their clusters, so something like `eksctl validate [--workload-test] [--kubernetes-conformance-test] [--full-kubernetes-e2e-test] [--node-problem-detector]` should probably become a thing eventually, especially when we are gonna allow custom node AMIs etc.

**Comment by richardcase** [comment]
> should we make integration tests a requirement for one of the next patch releases?

Yes i think we should. I'll take a look at this next and will look at the package by @dlespiau. Also, what [minikube](https://github.com/kubernetes/minikube/tree/master/test/integration) do is quite good.

I really like the idea of validating clusters using eksctl and think this could come after the initial integration tests.

**Comment by richardcase** [comment]
@errordeveloper - i've started work on the integration tests. Are you happy for us to use this issue or do we want a separate one for integration tests?

**Comment by errordeveloper** [comment]
Yes, let's create a separate umbrella issue.

**Comment by richardcase** [comment]
@errordeveloper - do you think we can close this now we have #151 for the integration tests?

**Comment by errordeveloper** [comment]
@richardcase yes, but before we close this, I think it'd make sense to open another set a goal post for coverage - wdyt?

**Comment by errordeveloper** [comment]
I'd guess we start with unit tests for now. Integration coverage is harder to grasp, as you have to think of various flag combos, so I'm not sure how we would make that work in a way that doesn't require creating dozens of clusters...

90% could be a good one to aim for, but I'd also define a lower band (60%-70%?) that's more realistic near-term.

**Comment by richardcase** [comment]
Closing this issus as we have defined the testing strategy and have started to add tests. We now have new issues to improve various aspects:

- Integration tests #151
- Test coverage to 60% #166 
- Test coverage to 90% #167

**Comment by Raffo** [comment]
We probably don't need to achieve 90% or a specific number, but I believe we should keep track of the coverage anyways as it is a good indication of where the efforts should go.

**Comment by richardcase** [comment]
I agree. I have removed the 90% target issue and changed the other one to be more generic (#166). We can track coverage with coveralls.
