### ISSUE TITLE
ipv6 command line options for cluster create

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4602]
#4571 adds support for ipv6, but it still missing from `eksctl create cluster --help`

**Comment by cPu1** [comment]
You create an IPv6 cluster by setting `kubernetesNetworkConfig.ipFamily: IPv6` but this field is not exposed via a CLI option, so there's no info in `--help` about IPv6. The best way to learn more about eksctl features is https://eksctl.io right now, but I think we should also link to it in `--help`.

**Comment by matti** [comment]
yes, I am aware of the features - just pointing out that currently cluster.yml is required.

**Comment by Himangini** [comment]
This page might need some help https://eksctl.io/usage/vpc-ip-family/

**Comment by Himangini** [comment]
We have added this ticket https://github.com/weaveworks/eksctl/issues/4665 to address the improvement for `--help` ticket.
