### ISSUE TITLE
make sure we don't break docs when we merge changes to master

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#461]
When #460 got merged, we broke the config file samples in the `examples` and in `README.md`. We need to get better at this and only update docs when release is ready to use.

**Comment by mumoshu** [comment]
My quick idea towards this is add `eksctl` a command to validate a config file, like `eksctl create cluster --config-file 01-simple-cluster.yaml --dry-run`, so that it can be used to validate syntactic correctness of all the examples in CI.

**Comment by errordeveloper** [comment]
@mumoshu I see. I was more thinking about versioning the docs. We might have outgrown the current website also, which presets just what's in the readme. Something to think about, not urgent just yet - for now we just need to be careful about when we merge documentation changes.
