### ISSUE TITLE
Remove time-based (TTL) caching of cluster data

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4616]
When eksctl code needs to read the latest EKS cluster data, it relies on a TTL-based cache that is refreshed when the TTL expires. In most places, this is not required as eksctl itself makes changes to the cluster, so it knows exactly when the cluster data might change. For many commands, the need for this cache can be eliminated by obtaining the cluster data via DescribeCluster in the beginning, when the provider is created. 

The caching code is [pkg/eks/cache.go](https://github.com/weaveworks/eksctl/blob/main/pkg/eks/cache.go)

Related to #4213.

**Comment by Skarlso** [comment]
@cPu1 Interesting. When I was investigating how we could reduce the number of `DescribeStack` calls I was actually finding it nice that it doesn't always call DescribeStack. I found it convenient. Removing the cache means a full restructure of all the Can* calls and RefreshClusterStatus calls. :D

**Comment by Skarlso** [comment]
I know, I know we discussed this already. Just writing it down here too.
