### ISSUE TITLE
Refactor and centralize validation of ClusterConfig

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4627]
Validation for ClusterConfig fields is performed in multiple places and there's no centralized place for validation code, making it difficult to find out existing validations and add new validation code. Although we have been trying to add new validation code in `pkg/apis/eksctl.io/v1alpha5/validation.go`, there's still existing validation code spread across types and functions.

Related: https://github.com/weaveworks/eksctl/issues/4213

[ Edit: Niki ]

**TODOs:**

- [x] Find and list all code areas that perform some kind of validation of the `ClusterConfig`

**Comment by Himangini** [comment]
@cPu1 will add some example code for reference
We'd probably need to fix existing tests or write new ones to cover the new code.

**Comment by Himangini** [comment]
Investigate what other places of validation is there other than `pkg/apis/eksctl.io/v1alpha5/validation.go` and bring them in one place

**Comment by Skarlso** [comment]
Arguably, that file is massive and I don't think further extending it will bring much joy. :D I think we should categorise these better and use a set of files instead. But that can be a follow up ticket to this perhaps. But doing it up front will alleviate some pain in the future.

**Comment by nikimanoledaki** [comment]
@cPu1 If you could share the examples that you had in mind, that would be really helpful. Thanks :)

For me, what came to mind was [this](https://github.com/weaveworks/eksctl/blob/main/pkg/ctl/cmdutils/configfile.go).

**Comment by cPu1** [comment]
> @cPu1 If you could share the examples that you had in mind, that would be really helpful. Thanks :)
> 
> For me, what came to mind was [this](https://github.com/weaveworks/eksctl/blob/main/pkg/ctl/cmdutils/configfile.go).
> 

Yes, the loader code is one example. Another one is: https://github.com/weaveworks/eksctl/blob/main/pkg/eks/api.go#L370

**Comment by nikimanoledaki** [comment]
I've added a TODO list in the description of this ticket to capture what was discussed in today's stand up.

**Comment by nikimanoledaki** [comment]
I can start working on a PR to move `ClusterConfig` validation out of `1. pkg eks`. A separate PR could start to tackle `2.` as part of this ticket as well. However, `3. ConfigLoaderBuilder struct & commonClusterConfigLoader struct` might need more planning in order to get it right. @cPu1 WDYT?

**Comment by nikimanoledaki** [comment]
I'm starting with the 2 funcs in `pkg/eks/api.go` and go from there.

**Comment by cPu1** [comment]
Great work finding all validation code. (1) is exactly what I had in mind. Although `func errTooFewAvailabilityZones` should be replaced with the calling code (`SetAvailabilityZones`) as the function itself is merely constructing an error.

Regarding (2), I created the issue to address validation of ClusterConfig, mainly code that performs validation on ClusterConfig fields but is not called from `ValidateClusterConfig`, `ValidateNodeGroup` or `ValidateManagedNodeGroup`. 

The following examples are all for validating CLI options for a specific command:

* > func validateLoggingFlags [pkg/ctl/utils/update_cluster_logging.go](https://github.com/weaveworks/eksctl/blob/5c6580b47340ff41e8f8c3ac42e6c84a1cfdefcb/pkg/ctl/utils/update_cluster_logging.go#L55)


* > validateNonServiceOptions
ValidateAdditionalEndpointServices() [pkg/apis/eksctl.io/v1alpha5/endpoint_service.go#L36](https://github.com/weaveworks/eksctl/blob/5c6580b47340ff41e8f8c3ac42e6c84a1cfdefcb/pkg/apis/eksctl.io/v1alpha5/endpoint_service.go#L36)

* > fargate: Validate() [pkg/fargate/options.go](https://github.com/weaveworks/eksctl/blob/5c6580b47340ff41e8f8c3ac42e6c84a1cfdefcb/pkg/fargate/options.go#L13) & Validate() [pkg/fargate/create.go](https://github.com/weaveworks/eksctl/blob/5c6580b47340ff41e8f8c3ac42e6c84a1cfdefcb/pkg/fargate/create.go#L26)





For `Validate()`[pkg/utils/taints/taints.go](https://github.com/weaveworks/eksctl/blob/5c6580b47340ff41e8f8c3ac42e6c84a1cfdefcb/pkg/utils/taints/taints.go#L14), the validation code is defined in `utils/taints` because it's for validating taints and can be reused outside of validation of nodegroups. But it's still being called from `ValidateNodeGroup`. 


I found [ValidateClusterEndpointConfig](https://github.com/weaveworks/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/validation.go#L312) which is a good example of validation happening outside of the standard ClusterConfig validation functions. It's called from `doCreateCluster` and should be moved to `ValidateClusterConfig`.

**Comment by nikimanoledaki** [comment]
Thanks Chetan! :)

I've updated my comment to remove/update the functions that you mentioned.

Good catch re: `doCreateCluster`, it also does quite a bit of validation that should be moved. Adding it as another section.
