### ISSUE TITLE
Allow eksctl to tag subnets with the kubernetes.io/cluster/<name>: shared tag when building new clusters

### ISSUE THREAD

**Issue by rayterrill** [weaveworks/eksctl#4630]
**What feature/behavior/change do you want?**

**Why do you want this feature?**

This would allow eksctl to stand up clusters that can be immediately used in shared subnets without having to separately provision that tag outside of eksctl. Supports using eksctl to build short-lived or ephmeral clusters within the tool itself, vs relying on other means.

**Comment by aclevername** [comment]
Hey @rayterrill. Thanks for opening the issue. This tag seems to keep cropping up- see https://github.com/weaveworks/eksctl/issues/3341 . Originally EKS was automatically adding it to the subnets, but they removed that functionality for 1.19+. You can get this tag added by setting the `metdata.tags` field (see [comment](https://github.com/weaveworks/eksctl/issues/3341#issuecomment-786541960), however that tags all resources with it which isn't ideal. Perhaps a new `vpc.tags` or `vpc.subnets.tags` fields in the config file would be useful for tagging just the subnets, as request here https://github.com/weaveworks/eksctl/issues/3893

**Comment by rayterrill** [comment]
The vpc.tags or vpc.subnets.tags sounds most appropriate to me - would love to have the ability to keep this constrained to subnets in particular.

Nginx Ingress + AWS LB integration is my reason for this - I believe AWS's ALB controller has the ability to deduce private vs public subnets via some additional logic, but we're not seeing that for the nginx controller - the AWS LB doesnt get created without manually tagging the subnets for the cluster.

**Comment by Himangini** [comment]
Hi @rayterrill  Thanks for opening this feature request 👍 The team will review and see whether this functionality fits in with the project. In the meantime, if you would like to demonstrate a solution, please open a PR 😃 .
