### ISSUE TITLE
Allow specifying iamidentitymappings for users/groups in the eksctl config file schema

### ISSUE THREAD

**Issue by rayterrill** [weaveworks/eksctl#4631]
**What feature/behavior/change do you want?**

**Why do you want this feature?**

A very similar mechanism already appears to exist in eksctl when provisioning nodegroups - the aws-auth configmap is already being manipulated to add the nodegroup iam role. Extending this to include iamidentitymappings would allow the eksctl schema to move closer to being able to more fully describe the cluster and all the pieces needed to get it going prior to building.

**Comment by aclevername** [comment]
Hey @rayterrill , we were going to add support to this but in anticipation of a new AWS API we decided against it- see https://github.com/weaveworks/eksctl/issues/874#issuecomment-795808745. However that was quite some time ago and it doesn't seemed to have progressed. I will poke about and see if we can get an update on it, if its not coming soon then I agree its worth adding support for specifying iamidentitymappings in the config file

**Comment by rayterrill** [comment]
Sounds good @aclevername. Let me know too - happy to help add support for this if it fits in with the roadmap! Cheers!

**Comment by aclevername** [comment]
@rayterrill after chatting with some folks I think its worth doing this, lets not wait on the new AWS API.

Would you like to give it a go at implementing? If not we will add it to our backlog :smile:

**Comment by rayterrill** [comment]
Yes let me take a crack at it - Fair warning, I'm still learning go, but I've made a few other contributions to this project and a few others. If y'all are willing to continue to help me learn + stick to standards I'm def willing to give it a go. This would be a big win for us.

**Comment by aclevername** [comment]
> Yes let me take a crack at it - Fair warning, I'm still learning go, but I've made a few other contributions to this project and a few others. If y'all are willing to continue to help me learn + stick to standards I'm def willing to give it a go. This would be a big win for us.

absolutely! Give it a go, and feel free to open a draft PR. We can then help with any problems/question :smile:

**Comment by Skarlso** [comment]
@rayterrill Thanks, and of course, we'll provide information or guidelines during pr reviews on how to proceed or where to check something. Don't worry about that. :) If you have a valid PR we'll help to get along with it.

**Comment by cPu1** [comment]
> Yes let me take a crack at it - Fair warning, I'm still learning go, but I've made a few other contributions to this project and a few others. If y'all are willing to continue to help me learn + stick to standards I'm def willing to give it a go. This would be a big win for us.

@rayterrill, did you get a chance to work on this? :slightly_smiling_face:

**Comment by rayterrill** [comment]
I didn't - We ended up going in a different direction (CAPI).

**Comment by adamjohnson01** [comment]
I am happy to implement this.

**Comment by corinz** [comment]
@adamjohnson01 Any progress on this one?

**Comment by Himangini** [comment]
Opening this issue since there's a lot of interest here. 
@adamjohnson01 @corinz Please feel free to submit PRs, also let us know if you can't implement this, we will add it to our backlog 👍🏻

**Comment by corinz** [comment]
Thank you @Himangini. I cannot implement this, although I see a lot of activity on issue #185 in the last couple years. Ultimately, we can find other ways to mod `aws-auth` but it is preferable (especially if the functionality already exists) to do it with the eksctl at the time of cluster creation. And of course, the AWS API needs an update, but doesn't seem like we're gonna get that any time soon!

**Comment by adamjohnson01** [comment]
Unfortunately I have not had the time to do this but I will start working on it now.

**Comment by Himangini** [comment]
@adamjohnson01 thanks for picking this up, let us know if you need any help 👍🏻 

> Unfortunately I have not had the time to do this but I will start working on it now.

**Comment by adamjohnson01** [comment]
This has now been implemented! 🥳

**Comment by cPu1** [comment]
> This has now been implemented! partying_face

Indeed. Closed by https://github.com/weaveworks/eksctl/pull/5464.
