### ISSUE TITLE
[SPIKE] Split types StackCollection, ClusterProvider etc. and increase cohesion

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4655]
Types `StackCollection` and `ClusterProvider` have a lot of methods, many of which do not necessarily belong in them, thereby reducing cohesion and adding too many responsibilities to a single type. Both types should be split into smaller and more focused types.

Related: #4213 

As part of this spike ticket, investigate a few possible options for implementation and then we'll discuss as a team what is the best path to take.

Timebox: 2 days

**Comment by Himangini** [comment]
https://github.com/weaveworks/eksctl/issues/2931 Has lot of details around the problems with clusterProvider

**Comment by aclevername** [comment]
## StackCollection
The `StackCollection` struct is accessed through the `StackManager` interface:
```go
type StackManager interface {
	AppendNewClusterStackResource(plan, supportsManagedNodes bool) (bool, error)
	CreateStack(name string, stack builder.ResourceSet, tags, parameters map[string]string, errs chan error) error
	DeleteStackBySpec(s *Stack) (*Stack, error)
	DeleteStackBySpecSync(s *Stack, errs chan error) error
	DeleteStackSync(s *Stack) error
	DeleteTasksForDeprecatedStacks() (*tasks.TaskTree, error)
	DescribeClusterStack() (*Stack, error)
	DescribeIAMServiceAccountStacks() ([]*Stack, error)
	DescribeNodeGroupStack(nodeGroupName string) (*Stack, error)
	DescribeNodeGroupStacks() ([]*Stack, error)
	DescribeNodeGroupStacksAndResources() (map[string]StackInfo, error)
	DescribeStack(i *Stack) (*Stack, error)
	DescribeStackChangeSet(i *Stack, changeSetName string) (*ChangeSet, error)
	DescribeStackEvents(i *Stack) ([]*cloudformation.StackEvent, error)
	DescribeStacks() ([]*Stack, error)
	DoCreateStackRequest(i *Stack, templateData TemplateData, tags, parameters map[string]string, withIAM bool, withNamedIAM bool) error
	DoWaitUntilStackIsCreated(i *Stack) error
	EnsureMapPublicIPOnLaunchEnabled() error
	FixClusterCompatibility() error
	GetAutoScalingGroupName(s *Stack) (string, error)
	GetClusterStackIfExists() (*Stack, error)
	GetFargateStack() (*Stack, error)
	GetIAMAddonName(s *Stack) string
	GetIAMAddonsStacks() ([]*Stack, error)
	GetIAMServiceAccounts() ([]*v1alpha5.ClusterIAMServiceAccount, error)
	GetKarpenterStack() (*Stack, error)
	GetManagedNodeGroupTemplate(options GetNodegroupOption) (string, error)
	GetNodeGroupName(s *Stack) string
	GetNodeGroupStackType(options GetNodegroupOption) (v1alpha5.NodeGroupType, error)
	GetStackTemplate(stackName string) (string, error)
	GetUnmanagedNodeGroupSummaries(name string) ([]*NodeGroupSummary, error)
	HasClusterStackUsingCachedList(clusterStackNames []string, clusterName string) (bool, error)
	ListClusterStackNames() ([]string, error)
	ListIAMServiceAccountStacks() ([]string, error)
	ListNodeGroupStacks() ([]NodeGroupStack, error)
	ListStacks(statusFilters ...string) ([]*Stack, error)
	ListStacksMatching(nameRegex string, statusFilters ...string) ([]*Stack, error)
	LookupCloudTrailEvents(i *Stack) ([]*cloudtrail.Event, error)
	MakeChangeSetName(action string) string
	MakeClusterStackName() string
	NewClusterCompatTask() tasks.Task
	NewManagedNodeGroupTask(nodeGroups []*v1alpha5.ManagedNodeGroup, forceAddCNIPolicy bool, importer vpc.Importer) *tasks.TaskTree
	NewTaskToDeleteAddonIAM(wait bool) (*tasks.TaskTree, error)
	NewTaskToDeleteUnownedNodeGroup(clusterName, nodegroup string, eksAPI eksiface.EKSAPI, waitCondition *DeleteWaitCondition) tasks.Task
	NewTasksToCreateClusterWithNodeGroups(nodeGroups []*v1alpha5.NodeGroup, managedNodeGroups []*v1alpha5.ManagedNodeGroup, supportsManagedNodes bool, postClusterCreationTasks ...tasks.Task) *tasks.TaskTree
	NewTasksToCreateIAMServiceAccounts(serviceAccounts []*v1alpha5.ClusterIAMServiceAccount, oidc *iamoidc.OpenIDConnectManager, clientSetGetter kubernetes.ClientSetGetter) *tasks.TaskTree
	NewTasksToDeleteClusterWithNodeGroups(stack *Stack, stacks []NodeGroupStack, deleteOIDCProvider bool, oidc *iamoidc.OpenIDConnectManager, clientSetGetter kubernetes.ClientSetGetter, wait bool, cleanup func(chan error, string) error) (*tasks.TaskTree, error)
	NewTasksToDeleteIAMServiceAccounts(serviceAccounts []string, clientSetGetter kubernetes.ClientSetGetter, wait bool) (*tasks.TaskTree, error)
	NewTasksToDeleteNodeGroups(stacks []NodeGroupStack, shouldDelete func(_ string) bool, wait bool, cleanup func(chan error, string) error) (*tasks.TaskTree, error)
	NewTasksToDeleteOIDCProviderWithIAMServiceAccounts(oidc *iamoidc.OpenIDConnectManager, clientSetGetter kubernetes.ClientSetGetter) (*tasks.TaskTree, error)
	NewUnmanagedNodeGroupTask(nodeGroups []*v1alpha5.NodeGroup, forceAddCNIPolicy bool, importer vpc.Importer) *tasks.TaskTree
	RefreshFargatePodExecutionRoleARN() error
	StackStatusIsNotReady(s *Stack) bool
	StackStatusIsNotTransitional(s *Stack) bool
	UpdateNodeGroupStack(nodeGroupName, template string, wait bool) error
	UpdateStack(options UpdateStackOptions) error
}
```

This interface works quite well, and is easily mocked out throughout the codebase. However the interface itself is quite large
and can/should be split out. Grouping some of the current methods into categories:
- (17~ methods) Getting Stacks (returning the stack or information from the stack), e.g. `	DescribeNodeGroupStacks() ([]*Stack, error)`, `ListIAMServiceAccountStacks() ([]string, error)`, `DescribeStacks() ([]*Stack, error)`
- (7~ methods) Tasks for creating/deleting stacks (returning a `*tasks.TaskTree`) e.g.`NewTasksToCreateIAMServiceAccounts`, `NewTasksToDeleteIAMServiceAccounts`, `DeleteTasksForDeprecatedStacks`
- (5~ methods) Interpetting information from a stack (stack is passed in), e.g.`GetAutoScalingGroupName(s *Stack) (string, error)`, `GetIAMAddonName(s *Stack) string`, `GetNodeGroupName(s *Stack) string`
- (4~ methods) Deleting stacks directly (not via task), e.g. `DeleteStackSync(s *Stack) error`, `DeleteStackBySpec(s *Stack) (*Stack, error)`
- (3~ methods) Mutating the cluster stack, e.g. `FixClusterCompatibility() error`, `AppendNewClusterStackResource(plan, supportsManagedNodes bool) (bool, error)`, `EnsureMapPublicIPOnLaunchEnabled() error`
- miscellaneous, e.g. `RefreshFargatePodExecutionRoleARN() error`, `LookupCloudTrailEvents(i *Stack) ([]*cloudtrail.Event, error)`, `MakeClusterStackName() string`


### Proposal
I propose we move all of the following:
- Move the `Task` related methods out of here and into their respective `pkg/actions/<resource-name>` packages. Similar to how `irsa`/`addon`/`karpenter`/`fargate` all currently work
- Refactor the funcs to use consistent naming for the `Getters`, we currently have a mix of `Describe`/`Get`/`List`
- Move sthe miscellaneous funcs that aren't directly releated to a stack out of the interface (at the very least the 3 methods mentioned above)
- Unify the different `Delete` methods (@skarlso might of tried this recently?) into 1 func that has a `DeleteOpts` that allow you to customise how the deletion works (via spec/name, sync/async)
- Unify the different `CreateStack` methods (`CreateStack`, `DoWaitUntilStackIsCreated` and `DoCreateStackRequest`) into 1 func
- Unify the different `UpdateStack` methods (`UpdateNodeGroupStack`, and `UpdateStack`) into 1 func
- Remove dead funcs (already spotted `StackStatusIsNotReady`)

a rough outline of what the new interface *might* look like (just guess work):
```go
type StackManager interface {
	CreateStack(name string, stack builder.ResourceSet, tags, parameters map[string]string, errs chan error) error
	DeleteStack(d DeleteOpts) (*Stack, error)
	GetClusterStack() (*Stack, error)
	GetIAMServiceAccountStacks() ([]*Stack, error)
	GetNodeGroupStack(nodeGroupName string) (*Stack, error)
	GetNodeGroupStacks() ([]*Stack, error)
	GetNodeGroupStacksAndResources() (map[string]StackInfo, error)
	GetStack(i *Stack) (*Stack, error)
	GetStackChangeSet(i *Stack, changeSetName string) (*ChangeSet, error)
	GetStackEvents(i *Stack) ([]*cloudformation.StackEvent, error)
	GetStacks() ([]*Stack, error)
	GetAutoScalingGroupName(s *Stack) (string, error)
	GetClusterStackIfExists() (*Stack, error)
	GetFargateStack() (*Stack, error)
	GetIAMAddonName(s *Stack) string
	GetIAMAddonsStacks() ([]*Stack, error)
	GetIAMServiceAccounts() ([]*v1alpha5.ClusterIAMServiceAccount, error)
	GetKarpenterStack() (*Stack, error)
	GetManagedNodeGroupTemplate(options GetNodegroupOption) (string, error)
	GetNodeGroupName(s *Stack) string
	GetNodeGroupStackType(options GetNodegroupOption) (v1alpha5.NodeGroupType, error)
	GetStackTemplate(stackName string) (string, error)
	GetUnmanagedNodeGroupSummaries(name string) ([]*NodeGroupSummary, error)
	GetClusterStackNames() ([]string, error)
	GetIAMServiceAccountStacks() ([]string, error)
	GetNodeGroupStacks() ([]NodeGroupStack, error)
	GetStacks(statusFilters ...string) ([]*Stack, error)
	GetStacksMatching(nameRegex string, statusFilters ...string) ([]*Stack, error)
	HasClusterStackUsingCachedList(clusterStackNames []string, clusterName string) (bool, error)
	MakeChangeSetName(action string) string
	MakeClusterStackName() string
	NewClusterCompatTask() tasks.Task
	NewManagedNodeGroupTask(nodeGroups []*v1alpha5.ManagedNodeGroup, forceAddCNIPolicy bool, importer vpc.Importer) *tasks.TaskTree
	StackStatusIsNotReady(s *Stack) bool
	UpdateStack(options UpdateStackOptions) error
}
```

**Comment by nikimanoledaki** [comment]
This is a good survey, and really _any_ step towards refactoring this monster is a good start. 

You set out some good initial steps that can be taken. One suggestion on a first pass is to create a list with these action items (e.g. `move  x to y`) so that we can act on them e.g. create new tickets.

**Comment by aclevername** [comment]
> This is a good survey, and really _any_ step towards refactoring this monster is a good start.
thanks!

> You set out some good initial steps that can be taken. One suggestion that I have on a first pass is to adding those to the list and writing specific action items (e.g. `move x to y`) so that we can act on them e.g. create new tickets.

I've added some emojis to the different sections to try to make it clear what should be moved. I think rather than re-listing all the funcs to be moved, perhaps sub-tasks for tackling each file might be a easier way to split the work up?

**Comment by Skarlso** [comment]
What I would do and I think this is something that you are trying to do as well, is the following: 

- set up different providers for different things that we use that are aws specific such as: `eks` provider, `ec2` provider, `ssm` provider, etc
- make a provider for our own things as well such as cluster stack parsing, or template handling, etc
- make a root provider handler which has all the providers wired in explicitly at the begin of each route or a main route such as, instantiating the root command
- pass around this root provider

Doing this, should make mocking easy and specific. You don't have to deal with each and every provider on every turn, you could mock what you need specifically.

As you said, this is a lot of work. Figuring out which belongs where. I think you made a good effort of starting this work. :)

**Comment by Himangini** [comment]
Closing this ticket now. The next steps are to turn the proposal into actionable tickets
