### ISSUE TITLE
eksctl update iamserviceaccount changes name of IAM role

### ISSUE THREAD

**Issue by ygrosu** [weaveworks/eksctl#4657]
I created a service account and IAM role with a role name i gave (to make helm templating simpler), and everything worked smoothly.
Here is the command:
```
eksctl create iamserviceaccount --cluster=xxxxxxxx --region us-east-1    --namespace=my-namespace   \
      --name=my-sa-name   --role-name "k8s-sa-my-aws-role-name"              \
      --attach-policy-arn=arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess \
      --override-existing-serviceaccounts --approve
```

Then i wanted to add an additional policy to that aws iam role and ran this:  
```
eksctl update iamserviceaccount --cluster=xxxxxxxx --region us-east-1    --namespace=my-namespace   \  
      --name=my-sa-name              \  
      --attach-policy-arn=arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess \  
      --attach-policy-arn=arn:aws:iam::aws:policy/SomeOtherPolicy \  
      --approve
```
eksctl update iamserviceaccount parameters do not have role-name, so this breaks the SA<>IAM Role mapping.

Expected behavior:  
Either provide role name as parameter in the update iamserviceaccount command   
 OR   
take the role name from the CFN input value and keep the same role name.  

```
$ eksctl info
eksctl version: 0.79.0  
kubectl version: v1.20.4  
OS: darwin  
```

**Comment by Skarlso** [comment]
Hi! :) 

If all you need is adding a NEW account you would want to run a `create` again with the new things, instead of running `update`.

**Comment by Himangini** [comment]
We need to preserve the role name that already exists in a CF template

**Comment by Skarlso** [comment]
@ygrosu Hi!

> eksctl update iamserviceaccount parameters do not have role-name, so this breaks the SA<>IAM Role mapping.

How does it break it? Does it overwrite it? What is the error how will it look like after you run it? I tried running both commands but the annotation looks still okay. What is the outcome error?

**Comment by Skarlso** [comment]
Ah, so role gets deleted. I see now.
