### ISSUE TITLE
rename iam.withAddondPolicies.albIngress 

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4675]
>This project was formerly known as "AWS ALB Ingress Controller", we rebranded it to be "AWS Load Balancer Controller".

eksctl should reflect this change

**Comment by aclevername** [comment]
Thanks @matti ! Good spot. We should add support for both naming conventions for a while, log a warning when the old name is used and then remove the old name after a reasonable deprecation period. I'll add it to our backlog

**Comment by Himangini** [comment]
- rename `iam.withAddondPolicies.albIngress`to `iam.withAddondPolicies.loadBalancer`
- keep support for the existing setting but add a deprecation warning.
- follow up with a deprecation ticket to remove this after 6 months as per our policy
