### ISSUE TITLE
allow setting of aws ami version

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4676]
Currently:

>When setting --node-ami to an ID string, eksctl will assume that a custom AMI has been requested. For managed nodes this will mean that overrideBootstrapCommand is required. 

but if the latest AWS AMI is broken (or https://github.com/weaveworks/eksctl/issues/4674) then all cluster create / nodegroup create operations just fail

**Comment by aclevername** [comment]
@matti sorry could you expand? What command are you running? Whats the issue? What was the workaround? What would you like changed in eksctl? Thanks :smile:

**Comment by matti** [comment]
that if I specify custom ami, then I also need to specify custom overrideBootstrapCommand.

makes no sense, it should be possible to specify just the custom ami to lock down the ami version and not just use latest released which may be broken

**Comment by Himangini** [comment]
> Currently:
> 
> > When setting --node-ami to an ID string, eksctl will assume that a custom AMI has been requested. For managed nodes this will mean that overrideBootstrapCommand is required.
> 
> but if the latest AWS AMI is broken (or #4674) then all cluster create / nodegroup create operations just fail

@matti Can you please update the issue description using the standard feature request template and fill out all the sections? It helps understand better what problems you are facing and we can help resolve the issue quickly.

**Comment by matti** [comment]
@Himangini @aclevername trying harder at https://github.com/weaveworks/eksctl/issues/4693
