### ISSUE TITLE
Disable SSH access after creation of EKS Cluster

### ISSUE THREAD

**Issue by michaelweidmann** [weaveworks/eksctl#4690]
**What help do you need?**
Recently I discovered that my current cluster has SSH access enabled with an EC2 Keypair. See the following config:

```yaml
...
managedNodeGroups:
  - name: managed-nodes-eu-central-1a
    ssh:
      allow: true
      publicKeyName: "eks-node"
...
  - name: managed-nodes-eu-central-1b
    ssh:
      allow: true
      publicKeyName: "eks-node"
...
  - name: managed-nodes-eu-central-1c
    ssh:
      allow: true
      publicKeyName: "eks-node"
...
```

We planned to disable it because we do not need it and you should restrict access as much as possible.
I set `allow: false` and removed the `publicKeyName` property.

Afterwards I tried several commands to update/upgrade my cluster:

```bash
> eksctl upgrade cluster -f cluster.dev.yaml --profile MY_AWS_PROFILE --approve
2022-01-26 13:45:49 [ℹ]  eksctl version 0.79.0
2022-01-26 13:45:49 [ℹ]  using region eu-central-1
2022-01-26 13:45:49 [!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
2022-01-26 13:45:50 [ℹ]  no cluster version update required
2022-01-26 13:45:51 [ℹ]  re-building cluster stack "eksctl-br-team-emma-dev-cluster"
2022-01-26 13:45:51 [✔]  all resources in cluster stack "eksctl-br-team-emma-dev-cluster" are up-to-date
2022-01-26 13:45:51 [!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: d3130e34-7a5d-46d8-860f-d6420e8fc513) from cloudformation/DescribeStacks - will retry after delay of 7.504779918s
2022-01-26 13:45:59 [ℹ]  checking security group configuration for all nodegroups
2022-01-26 13:45:59 [ℹ]  all nodegroups have up-to-date cloudformation templates
```

```bash
> eksctl upgrade nodegroup --name managed-nodes-eu-central-1a --cluster MY_CLUSTER_NAME --profile MY_AWS_PROFILE --kubernetes-version=1.21
> eksctl upgrade nodegroup --name managed-nodes-eu-central-1b --cluster MY_CLUSTER_NAME --profile MY_AWS_PROFILE --kubernetes-version=1.21
> eksctl upgrade nodegroup --name managed-nodes-eu-central-1c --cluster MY_CLUSTER_NAME --profile MY_AWS_PROFILE --kubernetes-version=1.21
```

I do not have the output anymore, but it looked like always. It restarted each node. After all these commands, nothing changed. The Security Group is not updated and the EC2 KeyPair is still attached to the EC2 instances. Am I doing something wrong or does `eksctl` ignore the changes to the SSH property?

```bash
> eksctl version
0.79.0
```

Thanks in advance!
Michael

**Comment by cPu1** [comment]
`eksctl upgrade nodegroup` is for upgrading a nodegroup to a newer version, not for updating arbitrary nodegroup fields. Nodegroups are immutable by design, so if you need to change a field, you'll have to recreate the nodegroup.

**Comment by michaelweidmann** [comment]
What is the best way to recreate the nodegroup?

**Comment by cPu1** [comment]
> What is the best way to recreate the nodegroup?

By [deleting](https://eksctl.io/usage/managing-nodegroups/#deleting-and-draining) and recreating the nodegroup using `eksctl create nodegroup`.

**Comment by michaelweidmann** [comment]
It worked, thanks for your help 🙂
