### ISSUE TITLE
allow setting managedNodeGroups.ami without setting overrideBootstrapCommand

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4693]
**What feature/behavior/change do you want?**

Currently eksctl requires overrideBootstrapCommand if ami is specified in managedNodeGroups:

>When setting --node-ami to an ID string, eksctl will assume that a custom AMI has been requested. For managed nodes this will mean that overrideBootstrapCommand is required. For unmanaged nodes overrideBootstrapCommand is recommended for AmazonLinux2 and Ubuntu custom images.

I want this requirement to be removed.

**Why do you want this feature?**

I want to lock down my eks amazon linux ami version and not use the latest Currently as stated above, I need to set overrideBootstrapCommand which is completely unnecessary as the default overrideBootstrapCommand is okay

**Comment by cPu1** [comment]
The custom AMI feature is intended for customers that build their own AMIs, e.g., by installing additional software packages or using a different distro etc. It's not designed to lock down using a specific AMI of EKS AL2. Furthermore, relaxing the requirement for specifying `overrideBootstrapCommand` for custom AMIs will lead to hard-to-debug issues with nodes not joining the cluster. 

If you'd like to use a specific EKS AL2 AMI version, you can still do it:

```yaml

managedNodeGroups:
- name: al2
  ami: <ami>
  overrideBootstrapCommand: |
    #!/bin/bash
    /etc/eks/bootstrap.sh <cluster-name>
```

**Comment by matti** [comment]
sure, I am already setting the overrideBootstrapCommand, but I'm suggesting that because I don't need to override (and most users shouldnt?) then it should be possible to pin/lock down the ami version without this as it's a good practise.

**Comment by matti** [comment]
but like this is just a minor annoyance, I think this project has way more important things to add, so just closing this now.
