### ISSUE TITLE
Indicate whether a cluster’s existing node groups are managed or unmanaged

### ISSUE THREAD

**Issue by IanHuang-at** [weaveworks/eksctl#4695]
**What feature/behavior/change do you want?**
There should be an easy way to tell whether a cluster's node groups are managed or unmanaged. One solution would be to add a boolean flag `Managed` to the node group obj returned by `eksctl get nodegroup`

See slack thread https://weave-community.slack.com/archives/CAYBZBWGL/p1643180196379949

**Why do you want this feature?**
We have multiple EKS clusters running, some with managed node groups and some with unmanaged. We would like to differentiate between the two types so that we can take advantage of managed node group features. One example of this is upgrading AMIs:
- For managed node groups, we can use `eksctl upgrade nodegroup`
- For unmanaged node groups, we will create a new node group and delete the old one.

**Comment by cPu1** [comment]
This is a reasonable feature request. We'll add this to our backlog, but in the meantime, a workaround for identifying managed nodegroups would be to look for ASG names that have the `eks-` prefix. We will also evaluate adding a `--managed` flag to `eksctl get nodegroups` that lets you filter managed and unmanaged nodegroups.
