### ISSUE TITLE
Karpenter Install - Using account to run Helm as opposed to the original IAM user

### ISSUE THREAD

**Issue by bitva77** [weaveworks/eksctl#4697]
**What were you trying to accomplish?**

Trying to install Karpenter

**What happened?**

`Error: failed to install Karpenter: failed to install Karpenter chart: failed to install chart: failed to install CRD crds/karpenter.sh_provisioners.yaml: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:azdo-buildagents:azdo-buildagents" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
`

**How to reproduce it?**

So, we're running this from Azure DevOps.  It's a pipeline task using the AWS Shell scrip task and an AWS Service Connection to authenticate to AWS.

Using the following ClusterConfig

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: sandbox-karpenter
  region: us-west-2
  version: "1.21"
vpc:
  subnets:
    private:
      us-west-2a: {id: subnet-12345}
      us-west-2b: {id: subnet-67890}
      us-west-2c: {id: subnet-11121}}
  clusterEndpoints:
    publicAccess: false
    privateAccess: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
karpenter:
  version: '0.5.5'
iam:
  withOIDC: true
managedNodeGroups:
  - name: default
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    instanceType: m5.large
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::XXXX:policy/CUSTOM-POLICY
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
    privateNetworking: true
    disableIMDSv1: true
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh sandbox-karpenter
```

**LOGS**

```
2022-01-26 23:58:14 [ℹ]  waiting for CloudFormation stack "sandbox-karpenter-karpenter"
2022-01-26 23:58:15 [ℹ]  1 task: { 
    2 sequential sub-tasks: { 
        create IAM role for serviceaccount "karpenter/karpenter",
        create serviceaccount "karpenter/karpenter",
    } }2022-01-26 23:58:15 [ℹ]  1 task: { 
    2 sequential sub-tasks: { 
        create IAM role for serviceaccount "karpenter/karpenter",
        create serviceaccount "karpenter/karpenter",
    } }2022-01-26 23:58:15 [ℹ]  building iamserviceaccount stack "sandbox-karpenter-addon-iamserviceaccount-karpenter-karpenter"
2022-01-26 23:58:15 [ℹ]  deploying stack "sandbox-karpenter-addon-iamserviceaccount-karpenter-karpenter"
2022-01-26 23:58:15 [ℹ]  waiting for CloudFormation stack "sandbox-karpenter-addon-iamserviceaccount-karpenter-karpenter"
2022-01-26 23:58:34 [ℹ]  waiting for CloudFormation stack "sandbox-karpenter-addon-iamserviceaccount-karpenter-karpenter"
2022-01-26 23:58:49 [ℹ]  waiting for CloudFormation stack "sandbox-karpenter-addon-iamserviceaccount-karpenter-karpenter"
2022-01-26 23:58:49 [ℹ]  created namespace "karpenter"
2022-01-26 23:58:49 [ℹ]  created serviceaccount "karpenter/karpenter"
2022-01-26 23:58:49 [ℹ]  adding identity "arn:aws:iam::XXXX:role/eksctl-KarpenterNodeRole-sandbox-karpenter" to auth ConfigMap
2022-01-26 23:58:49 [ℹ]  adding Karpenter to cluster sandbox-karpenter
Error: failed to install Karpenter: failed to install Karpenter chart: failed to install chart: failed to install CRD crds/karpenter.sh_provisioners.yaml: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:azdo-buildagents:azdo-buildagents" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

I don't know where it's getting `azdo-buildagents` from.  That's the name of the Kubernetes Service Account our Azure Build Agents run under.  Why isn't it using the `awsCredentials` that we're running all of this under?  Like, the cluster get's created and is done so with the IAM user that's running `eksctl`, however, when it comes time to install Karpenter, it's like it's being run outside of that?

The problem with this is we haven't had time to add any other users to the `aws-auth` ConfigMap (like the `azdo-buildagents` user).  I know I could create proper RBAC for it but that can't happen until `eksctl` is done.

Chicken and egg problem here, no?

**Versions**

```
$ eksctl info
eksctl version: 0.80.0
kubectl version: v1.21.2
OS: linux
```

**Comment by Skarlso** [comment]
Hey @bitva77!

Thanks for reporting this. The is super weird. It should be using the current context of course.

I'll look into why that's not happening.

**Comment by Skarlso** [comment]
>Like, the cluster get's created and is done so with the IAM user that's running eksctl, however, when it comes time to install Karpenter, it's like it's being run outside of that?

This is partially true, yes. I suspect, helm is not considering this environment at all and just runs with the current session which is the session that you are using to run the whole thing.

**Comment by Skarlso** [comment]
@bitva77 Ah! 

The RBAC is configured for the service account https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/controller/rbac.yaml#L13

That's the account which will have access to install Karpenter.

**Comment by Skarlso** [comment]
Uh, maybe, we could somehow pass in the right service account 🤔

**Comment by Skarlso** [comment]
Hum, it should have used the `karpenter/karpenter` service account to create things. This is weird. I have to reproduce this first and then try to find out what's going on.

**Comment by Skarlso** [comment]
@bitva77 Do you have anything special in the bootstrap script that you are running?

**Comment by Skarlso** [comment]
I need more info, I tried reproducing this locally, but failed. I'm assuming I'm missing some configuration detail or awsCredential configuration detail.

What can be done maybe is exposing the Helm setting for Karpenter which gets the service account name and use a different service account that is set up previously.

You could also try before running this to add a role binding manually that allows the system account to create things. This isn't ideal, but I'm lacking a reproducable environment.

**Comment by Skarlso** [comment]
Actually, we found an unrelated issue which might be causing this issue as well. We are testing a solution now and if we found it, we'll release it tomorrow. I'll ping you to test it when it's done.

**Comment by bitva77** [comment]
@Skarlso appreciate it!  I'm not doing anything special in the bootstrap other than specifying the cluster name.  I'm running some more tests now and will also let you know  what else I find as well...

**Comment by bitva77** [comment]
ooff run on my box, same ClusterConfig and I cannot reproduce either.  Only when run on the Azure DevOps pipeline agent does it fail.

We're using this task:  https://docs.aws.amazon.com/vsts/latest/userguide/awsshell.html

hrmm....will keep at it.  Not sure what that task does differently than just run a shell but obviously it's messing with things.  I did have to refactor some bash script code as well due to weird things that AWS Shell does.

**Comment by Skarlso** [comment]
@bitva77 Please hold off on using Karpenter for now. We found a potential issue where it's not detecting the kube config correctly. Are there multiple clusters running in that environment by any chance? It's possible that helm right now is actually trying a different cluster than you would think it should. :)

**Comment by bitva77** [comment]
@Skarlso will do.  appreciate the work!

I still think there's something up with that task still.  If I run eksctl inline it works but within a script it's failing - so something odds going on.

We do have another cluster in this account but there's no kubeconfig for it on the agent servers so it shouldn't be getting confused.  eksctl would have access to it though (not sure that matters).

**Comment by aclevername** [comment]
@bitva77 can you try again with https://github.com/weaveworks/eksctl/releases/tag/v0.82.0-rc.0 and let us know if its fixed it :smile: thanks!

**Comment by bitva77** [comment]
Looks like that did it!  Thank you all!

**Comment by aclevername** [comment]
> Looks like that did it!  Thank you all!  

Excellent! Glad it's resolved, going to close the issue 😄

**Comment by Skarlso** [comment]
Yay! :) Awesome. Thanks for verifying! :)
