### ISSUE TITLE
eksctl get nodegroup returns 'CUSTOM' for ami id when using custom AMIs with managed nodegroups

### ISSUE THREAD

**Issue by IanHuang-at** [weaveworks/eksctl#4698]
**What were you trying to accomplish?**
Trying to get the ami id for a managed node group with a custom ami. 

**What happened?**
`eksctl get nodegroups --cluster=<> -o json` returns nodegroups with `"ImageID": "CUSTOM",`

For managed nodegroups, the aws api doesnt return an image id in most cases, but in the case where `AmiType == CUSTOM`, the ami id is provided in another field, `ReleaseVersion`.

On https://github.com/weaveworks/eksctl/blob/main/pkg/actions/nodegroup/get.go#L72 is using `Nodegroup.AmiType` but should it be `Nodegroup.ReleaseVersion`? 

See [go docs for nodegroups](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/eks@v1.18.0/types#:~:text=group.%0A%09NodegroupName%20*string-,//%20If%20the%20node%20group%20was%20deployed%20using%20a%20launch%20template,AMI%20that%20the%20node%20group%20was%20deployed%20with.%0A%09ReleaseVersion%20*string,-//%20If%20the%20node)

**How to reproduce it?**

1. Create a cluster with managed nodegroups using a custom ami
2. run eksctl get nodegroups --cluster=<> -o json

**Logs**
N/A

**Anything else we need to know?**
N/A

**Versions**

```
$ eksctl info
eksctl version: 0.76.0
kubectl version: v1.22.2
OS: darwin
```

**Comment by cPu1** [comment]
You're right that eksctl can do a better job here by returning the AMI ID for managed nodegroups using a custom AMI, instead of  `CUSTOM`. eksctl might have done this for consistency reasons because it's more work to obtain the AMI ID for nodegroups not using a custom AMI. We will add this to our backlog.
