### ISSUE TITLE
Publish eksctl config docs

### ISSUE THREAD

**Issue by alejandrox1** [weaveworks/eksctl#470]
**Why do you want this feature?**
Passing configuration to eksctl is a great idea for automating builds and communicating state. 
However, I don't see any mention anywhere in the docs or web page pointing to documentation for all available fields.
Some documentation does exist in https://godoc.org/github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha4 
but the documentation lacks a lot of details. For example, in kubeadm, their docs look like [this](https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1).

That format also makes it easy to browse through different the docs for different config version.

**What feature/behavior/change do you want?**
Add documentation for the eksctl configuration file detailing explicitly all available fields.

**Comment by alejandrox1** [comment]
Also, I would love to help out if possible 😄

**Comment by dardanbekteshi** [comment]
I agree documentation regarding using eksctl with config files is lacking.

**Comment by errordeveloper** [comment]
We do have more in [`examples/`](https://github.com/weaveworks/eksctl/tree/master/examples) since this issue was opened. And #508 is a tracking issue for more advanced examples.
