### ISSUE TITLE
Scaling nodegroup with specific instance

### ISSUE THREAD

**Issue by vitalik** [weaveworks/eksctl#4703]
I want to use eksctl to atomically  autoscale based on custom metrics...

Let's say I have a nodegroup with 3 nodes

each node runs just one pod (job)

at some moment one pod finishes work (means I no longer need 3 nodes, and can downscale to 2 nodes)

so I run `eksctl scale nodegroup --nodes=2 ...`

I assume the node that will be removed/killed is random ? is there a way to specify concrete instance-id that should be killed when I downscale nodegroup ?

**Comment by Skarlso** [comment]
Hello!

Thank you for your issue. You can find out more about how to scale here https://eksctl.io/usage/managing-nodegroups/#scaling-a-single-nodegroup.

**Comment by vitalik** [comment]
Thank you @Skarlso 
But there is nothing in docs about my question 

To be more specific - how to mark specific node to shut down when eksctl scales down?

**Comment by Skarlso** [comment]
@vitalik Oh, I see. Sorry, I misunderstood. 

You can't sadly. We do not control scaling, that's done via the ASG or the installed autoscaler. All we do is update the desired node count.

**Comment by matti** [comment]
@vitalik install cluster autoscaler and let it scale up and scale down (beware, minimum needs to be 1 for managed nodegroups (https://github.com/aws/containers-roadmap/issues/724)

these are the magic parts to get it working:

https://github.com/matti/eksler/blob/67864ad19be9c80aa4efb9b0be41f75e91d9a776/bin/eksler#L201
https://github.com/matti/eksler/blob/67864ad19be9c80aa4efb9b0be41f75e91d9a776/bin/main#L38-L41
https://github.com/matti/eksler/blob/67864ad19be9c80aa4efb9b0be41f75e91d9a776/helm/values/cluster-autoscaler-1.yml
