### ISSUE TITLE
Parallel node draining during node group deletion for Unmanaged nodegroups

### ISSUE THREAD

**Issue by hintofbasil** [weaveworks/eksctl#4705]
**What feature/behavior/change do you want?**

Add an option to drain multiple nodes in parallel when deleting a node group.

```bash
eksctl delete nodegroup --parallel-drain 5
```

When a node group is deleted using the above command five nodes should begin draining immediately.  When one of these nodes is fully drained a new node should start draining to ensure there are always five nodes draining at a time (or there are less than five nodes still needing drained).

A percentage based option could also be added (exclusive with the absolute option above).

```bash
eksctl delete nodegroup --parallel-drain-percentage 25
```

**Why do you want this feature?**

Node groups are generally immutable.  As such the standard approach for updating node groups is to create a new node group and delete the current one.  This is a fairly common operation.

In a cluster with many nodes, fairly restrictive pod disruption budgets, and the need to scale the node group using tooling such as the cluster autoscaler this process can end up taking many hours.  This delay is often due to either the cluster autoscaler having to scale up for each node drained, or specific pods taking a long time to shutdown gracefully and reach a healthy status on a new node.  Both of these problems are easily parallelisable.

With sensible pod disruption budgets there should be no extra risk to workloads running on the cluster.

### Summary
- Sounds like a reasonable request to implement for **UnManaged Nodegroups**
- Might need some investigation and testing can be realllyyyyy tricky
- We are going to implement the percentage based draining option
```bash
eksctl delete nodegroup --parallel-drain-percentage 25
```
- Tip to round down eg., 33% of 2 should be 1
- Might not need an insane amount of tests but we should do some testing to make sure everything works [perhaps manual testing the edge cases]

**Comment by hintofbasil** [comment]
This behaviour is most likely managed by AWS for managed node groups making this feature only possible for self hosted node groups currently.

**Comment by nikimanoledaki** [comment]
Thanks @hintofbasil, the team will investigate this to see if/how this can be implemented. 

Some info for when we discuss this: eksctl currently uses the Kube API to evict pods from nodes and drain the nodes [here](https://github.com/weaveworks/eksctl/blob/main/pkg/drain/nodegroup.go). Here's a link to the k8s docs on [draining nodes in parallel](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#draining-multiple-nodes-in-parallel).

**Comment by aclevername** [comment]
https://github.com/weaveworks/eksctl/pull/4966

**Comment by aclevername** [comment]
> I see this issue was scoped down to only unmanaged node groups. Was this due to a technical limitation for managed node groups? Is there any thoughts on whether this can be brought to managed node groups too in the future?

this applied to all nodegroups types in the end, the original ticket was incorrect :smile: I'll update it

**Comment by hintofbasil** [comment]
I guess I should have read the PR rather than the title change!

Thanks for the work to get this feature pushed out.
