### ISSUE TITLE
Publish docs after the release is published

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4707]
The docs are currently published when the release is triggered, but the release process can take some time to complete, and in rare cases, even fail, causing the docs to be out of sync with the release. Instead, docs should be published after the CircleCI release job is complete and the release artefacts have been uploaded.

**Comment by Himangini** [comment]
We will also work on moving the release job from circle ci @cPu1 will add a new ticket to document that 
The new ticket is a blocker for this ticket so we want to investigate first how much work is involved.
