### ISSUE TITLE
Creating cluster in existing VPC times out waiting for node to join cluster

### ISSUE THREAD

**Issue by danielchalef** [weaveworks/eksctl#472]
**What happened?**

Creating a cluster in an existing VPC with both public and private subnets times out with error: `timed out (after 20m0s) waitiing for at least 1 nodes to join the cluster`.  A node is in fact added to the cluster.

**What you expected to happen?**
Cluster creation completes successfully.

**How to reproduce it?**

Call eksctl with the following parameters:
```eksctl -v4 create cluster \
        --name=$CLUSTER_NAME \
        --region=us-west-2 \
        --vpc-cidr=172.31.0.0/16 \
        --vpc-public-subnets=subnet-XXXXX,subnet-XXXXX,subnet-XXXXX \
        --vpc-private-subnets=subnet-XXXXX,subnet-XXXXX,subnet-XXXXX \
        --nodes=1 \
        --node-type=r5.12xlarge \
        --ssh-access --ssh-public-key=XXXXX \
        --node-volume-size=200 \
        --node-volume-type=gp2 \
        --asg-access \
        --full-ecr-access \
        --node-private-networking \
        --node-ami=auto
```
**Anything else we need to know?**
eksctl binary downloaded using default install routine. Default AWS profile. MFA active on IAM account.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.19"}
$ uname -a
Linux ip-172-31-4-191 4.4.0-1070-aws #80-Ubuntu SMP Thu Oct 4 13:56:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version
No running cluster - unable to run kubectl.
```
**Logs**
See gist: [https://gist.github.com/danielchalef/5ab2d64ce61ff41d87f2a014b2fa287b](https://gist.github.com/danielchalef/5ab2d64ce61ff41d87f2a014b2fa287b)

**Comment by danielchalef** [comment]
This was due to a missing subnet route. Not a bug.

**Comment by ghoshaditya** [comment]
what routes were missing can you help? because am facing the same issue.

**Comment by aallur1** [comment]
Hi @danielchalef what was the missing subnet route that fixed this for you ? Please advise.
