### ISSUE TITLE
Add unit tests for `GetUnmanagedNodeGroupSummaries`

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4736]
`GetUnmanagedNodeGroupSummaries`, used by `get nodegroup`, has quite a lot of logic including listing CFN stacks for nodegroups, determining the nodegroup type from tags, and fetching the associated ASG and the ASG capacity values. But there are no unit tests for it, the existing unit tests mock `GetUnmanagedNodeGroupSummaries` itself, instead of the AWS API calls. 

Related to #4213

**Comment by Himangini** [comment]
Consider moving the function out of the manager package
