### ISSUE TITLE
feat: Cost forecast 

### ISSUE THREAD

**Issue by Chabane** [weaveworks/eksctl#474]
Hello !

Thank you for your wonderful work !

**Why do you want this feature?**
If I run `eksctl create cluster`, I have no idea how much it will cost me. What I suggest is to have the possibility to estimate the cost before running any command. We all know that it's not possible to have an exact value, but we can have the `minimum`

**What feature/behavior/change do you want?**
for example 
```
eksctl estimate --usage=hour --nodes-min=2 --nodes-max=3 --node-type=t3.small --node-volume-size=5 --auto-kubeconfig --region=eu-west-1 --version=1.11
```
Result:
```
Region EU (Ireland):
EKS Cluster:  $0.20 per hour
EC2 t3.small: $0.0228 per instance per hour
EBS volume: $0,00 per hour
Total: $0,2228 minimum per hour
[..]
```

Thank you for dedicating your time and energy into reading the issue.

**Comment by errordeveloper** [comment]
This sounds like an interesting feature, would you be willing to help?

**Comment by Chabane** [comment]
Glad you liked it!
I am a beginner in Golang. But If you challenge me, I can create a PR next week ʕ•ᴥ•ʔ

**Comment by errordeveloper** [comment]
Perhaps you could start with a detailed proposal PR, and jot down how this
can be designed. What do you think?

**Comment by Chabane** [comment]
You are right

The same idea as https://calculator.s3.amazonaws.com/index.html (+AWS TCO) but in automated manner. The estimation is limited to the pricing induced by a `eksctl create/scale` command + addons.

**Services involved:** 
- EC2 Instances
- EBS Volumes
- ELB
- NAT Gateway
- EKS
- Region
- +?

**API Used:**
- AWS Price List API : https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/index.json

**New command:**
`eksctl estimate (or whatever you want) `

**Parameters**: 
Usage:
- % Utilized/Month ` --usage-type=utilization --usage-value=100`  (default)
- Hours/Day  ` --usage-type=day --usage-value=24`
- Hours/Week ` --usage-type=week --usage-value=`
- Hours/Month ` --usage-type=month --usage-value=`

**Free Tier:**
- Yes/No (Yes by default) `--free-tier=no`

**Support**
- Basic (default)/Developer/Business/Enterprise `support=basic`

We can also add a parameter `--usecase`. For example: `eksctl estimate --usecase=free-website`. And we detail the recommanded configuration. I'm having fun calling that `Cloud Cost Forecast driven development` 👍 

Please feel free to correct or complete the design.

**Comment by errordeveloper** [comment]
@Chabane this sounds excellent! Would you mind opening a PR (akin to #303), and we can collaborate there?

**Comment by Chabane** [comment]
I'll open a PR basing on my fork https://github.com/Chabane/eksctl/blob/master/docs/proposal-003_cost-estimation.md

**Comment by errordeveloper** [comment]
Please do! You will need to bump the number by one, as 003 was taken by #545.

**Comment by Chabane** [comment]
PR #548
