### ISSUE TITLE
skip nodegroup resizing on min/max update through config file

### ISSUE THREAD

**Issue by pkit** [weaveworks/eksctl#4752]
**What feature/behavior/change do you want?**

Would like to have a config file flag that skips changing "desired" nodes if only min or max size was changed.

**Why do you want this feature?**
My "desired" size is managed by auto-scaler, thus I don't want `eksctl` to touch it.
Using something like: `desiredSize: "auto"` would be nice too.
When cluster is created the size would be clamped to `minSize` anyway.

**Comment by rtudo** [comment]
much required

**Comment by Skarlso** [comment]
Sounds like a reasonable thing. We'll put it into the next planning session. Thanks!
