### ISSUE TITLE
Add dry-run to all commands

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#476]
We should add `--dry-run`, which would be especially helpful to config file users, but it'd be good to make it generally useful.

For me personally, it seems that showing defaulted config would be quite useful, but I am pretty certain it won't be very friendly to most other users.

Perhaps we could do something where we show a summary of stack features, it'd be good to make it general enough, so that we could use it for `eksctl get cluster|nodegroup`, or `eksctl describe cluster|nodegroup`.

Key items to show will be:

- use of dedicated VPC vs existing one
- use of new security groups vs existing ones
- use of dedicated IAM roles vs existing ones

We should still show defaulted config, perhaps at the top of the output. It would be good to respect the format that user has used. Current debug logs use JSON as it's easy, but if user doesn't know the internals, they may get confused by seeing JSON instead of YAML.

**Comment by pawelprazak** [comment]
another interesting use case is an export functionality, where user can get all templates/manifests and version them in git and apply them manually if they want

**Comment by sbernheim** [comment]
@gemagomez - Shutterstock asked for a dryrun feature as well, and I was surprised to hear that it's not already implemented.  @errordeveloper confirmed that it is not implemented for createCluster and most other actions.

This feature is generally useful for automated dev/unit/functional testing.  It's a fairly standard feature for this sort of tool.

**Comment by mrPsycho** [comment]
it will help to configure policies like:
* PolicyNLB
* PolicyCloudWatchMetrics 
and some additional, which sometimes are needed to be more strict, than allowing to all resources.

**Comment by alimeerutech** [comment]
+1

**Comment by mattvonrocketstein** [comment]
> another interesting use case is an export functionality, where user can get all templates/manifests and version them in git and apply them manually if they want

I'm also interested in this functionality, and the related issue https://github.com/weaveworks/eksctl/issues/1888 was closed so I guess this is the best place to discuss.

It's possible to just grab these templates back from cloudformation after eksctl creates them, but for node groups the template has a huge block of b64 embedded.  So I checked in the code base for a obvious templates/user-data.sh file, but only found a collection of related code in pkg/nodebootstrap/userdata_al2.go  (no template).

Thus it seems without a dry-run, even if we accept the "pull cloudformation templates from AWS" solution, the only simple option for showing the user-data template is to actually apply changes and pull the template from the debugger.

**Comment by Callisto13** [comment]
Dry run now available, see docs: https://eksctl.io/usage/dry-run/

**Comment by cPu1** [comment]
> @Callisto13 `dry-run` does not seem to be available on all commands. `eksctl upgrade nodegroup` for example does not have this option.
> 
> Can you reopen or do i have to open a new issue ?
> 
> ```
> eksctl create nodegroup --help | grep dry 
>  --dry-run                      Dry-run mode that skips nodegroup creation and outputs a ClusterConfig
> 
> $ eksctl upgrade nodegroup --help | grep dry
> <nothing>
> $ eksctl update nodegroup --help | grep dry 
> <nothing>
> ```

@yogeek Please open a new issue detailing the behaviour you want from `eksctl upgrade nodegroup --dry-run`. The existing dry-run implementation only addresses `create cluster` and `create nodegroup`.
