### ISSUE TITLE
Make sure Karpenter version is as specified in ClusterConfig

### ISSUE THREAD

**Issue by bitva77** [weaveworks/eksctl#4763]
Last week I setup an EKS cluster and specified:

```
karpenter:
  version: '0.5.5'
```

today I change it to:

```
karpenter:
  version: '0.6.1'
```

and I run an `eksctl upgrade` but Karpenter isn't upgraded.  Assuming it's run just once during `eksctl create`.  It would be cool if during an upgrade it would upgrade Karpenter too.

**Comment by Skarlso** [comment]
Hi!

We don't support upgrading Karpenter ATM. It requires a completely new Helm Install and Helm Update, which eksctl doesn't do. `eksctl` provides an easy getting started for Karpenter, but doesn't manage it, if that makes sense. You can use helm to upgrade it though, it should have added it as a repository.

**Comment by cPu1** [comment]
`eksctl upgrade` is for upgrading a cluster's control plane version, it does not look at any other fields changed in the ClusterConfig. Additionally, Karpenter support in eksctl is not meant to be a replacement for the [Karpenter Helm chart](https://karpenter.sh/v0.6.0/getting-started/#install-karpenter-helm-chart). If you want to upgrade Karpenter, you can use Helm directly.

**Comment by bitva77** [comment]
Gotcha.  Thanks!
