### ISSUE TITLE
ssh-ed25519 keys wrongly assumed as unsupported

### ISSUE THREAD

**Issue by tsunamaru** [weaveworks/eksctl#4779]
**What were you trying to accomplish?**
Create cluster with ssh-ed25519 key for ssh access.

**What happened?**
`Error: computing fingerprint for key "~/.ssh/some-ed25519-key.pub": error computing fingerprint for SSH public key: unexpected type of SSH key ("ssh.ed25519PublicKey"); AWS can only import RSA keys`

**How to reproduce it?**
Just try to create any cluster with ed25519 key.

**Anything else we need to know?**
AWS can import ed25519 from EC2 Console:
![image](https://user-images.githubusercontent.com/37580200/153652144-1c2109cb-7a86-40fc-b20d-a724e91c4024.png)

**Versions**
```
$ eksctl info
eksctl version: 0.82.0
kubectl version: v1.21.9
OS: windows
```

#### Summary
- So we need to investigate whether this error is coming from in eksctl
- we need to fix eksctl side so that users can use the ssh key type ssh-ed25519

**Comment by aclevername** [comment]
thanks for opening the issue @tsunamaru . Looks like this is related to the kops package we use to generate fingerprints. Working on a fix :smile:

**Comment by aclevername** [comment]
Fix will be out in 0.85.0-rc.0 later today :smile:

**Comment by cPu1** [comment]
> I can confirm for ssh keys of the type ed25519 this bug still persists:
> 
> ```
> 2022-06-29 13:23:10 [ℹ]  will use version 1.19 for new nodegroup(s) based on control plane version
> 2022-06-29 13:23:10 [ℹ]  nodegroup "<redacted>" will use "" [AmazonLinux2/1.19]
> Error: computing fingerprint for key "<redacted>": error computing fingerprint for SSH public key: unexpected type of SSH key ("ssh.ed25519PublicKey"); AWS can only import RSA keys
> ```

@4thel00z, are you using the latest version of eksctl? The fix was out in 0.86.

**Comment by 4thel00z** [comment]
@cPu1 thanks for the quick reply. Yes, I am using a newer version:

```
$ eksctl version
0.103.0
```

**Comment by cPu1** [comment]
> @cPu1 thanks for the quick reply. Yes, I am using a newer version:
> 
> ```
> $ eksctl version
> 0.103.0
> ```

@4thel00z, I tried using an ed25519 SSH key with `create nodegroup` and it worked. Which command is failing for you? Can you share the steps you used to generate the key-pair?

**Comment by 4thel00z** [comment]
I generated the ssh key using:
```
ssh-keygen -o -t ed25519 -f 4thel00z
```

Here is the ssh package from my system:
```
apt list ssh
Listing... Done
ssh/impish-updates,impish-updates 1:8.4p1-6ubuntu2.1 all
```

**Comment by cPu1** [comment]
> I generated the ssh key using:
> 
> ```
> ssh-keygen -o -t ed25519 -f 4thel00z
> ```
> 
> Here is the ssh package from my system:
> 
> ```
> apt list ssh
> Listing... Done
> ssh/impish-updates,impish-updates 1:8.4p1-6ubuntu2.1 all
> ```

Thanks for providing more details. I'm reopening the issue for investigation.

**Comment by Himangini** [comment]
@4thel00z Which command is failing for you?
