### ISSUE TITLE
Upgrading worker nodegroup

### ISSUE THREAD

**Issue by michaelgeorgeattard** [weaveworks/eksctl#478]
I am trying to upgrade nodegroup from `1.10` to `1.11`.

Unfortunately `eksctl get nodegroup --cluster "cluster-name"` is giving me `No nodegroups found`.
`eksctl get cluster` is giving me the cluster name I'm using in the command above.

I am currently running version `0.1.19`.

Any idea what could be happening?

**Comment by errordeveloper** [comment]
Could you please provide the output of `eksctl get cluster` and `eksctl get nodegroup --cluster <name> --verbose=4`?

**Comment by michaelgeorgeattard** [comment]
`eksctl get cluster`:

```
2019-01-31T10:25:30+01:00 []  role ARN for the current session is "arn:aws:iam::xxx:user/xxx"
NAME            REGION
foo-bar        eu-west-1
```

`eksctl get nodegroup --cluster foo-bar --verbose=4`

```
2019-01-31T10:27:09+01:00 []  role ARN for the current session is "arn:aws:iam::xxx:user/xxx"
2019-01-31T10:27:09+01:00 []  nodegroups = []
No nodegroups found
```

`CloudFormation entries for eu-west-1`:

```
eksctl-foo-bar-nodegroup-0
eksctl-foo-bar-cluster
```

**Comment by errordeveloper** [comment]
Ok, perhaps the cluster was created by a very old version of eksctl. The
easiest thing to do would be to create new nodegroup, then drain the old
one using kubectl and delete it using CloudFormation console.

**Comment by michaelgeorgeattard** [comment]
Ok, would `eksctl create nodegroup` CloudFormation template contain the latest AMI for my Kubernetes version?

Side question, can I use `eksctl create nodegroup` to mix and match instance types? Ex. Nodegroup A contains `m5.large` while Nodegroup B contains `m5.xlarge` for example.

**Comment by errordeveloper** [comment]
> Ok, would `eksctl create nodegroup` CloudFormation template contain the latest AMI for my Kubernetes version?

Yes, but it doesn't auto-detect the version, so you need to pass '--version=1.10'.

> Side question, can I use `eksctl create nodegroup` to mix and match instance types? Ex. Nodegroup A contains `m5.large` while Nodegroup B contains `m5.xlarge` for example.

Yes, exactly and you can use automatic nodegroup name labels or set labels of your own choosing.

**Comment by errordeveloper** [comment]
@michaelgeorgeattard I'm going to close this, but if you think there is an action-item please open another issue.
