### ISSUE TITLE
"eksctl update addon -f config.yaml" throws InvalidParameter (empty stack name)

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/eksctl#4821]
**What happened?**

Calling `eksctl update addon` causes InvalidParameter error. This is a regression issue in v0.84.0 (not reproduced with v0.83.0). 

**How to reproduce it?**

1. Create cluster from a manifest with the following section:

```yaml
addons:
- name: vpc-cni
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  version: latest
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
```

2. Call `eksctl update addon -f cluster.yaml`, where "cluster.yaml" is the same manifest (no changes in content).

**Logs**

```
[ℹ]  Kubernetes version "1.21" in use by cluster "cluster-name"
[ℹ]  updating policies
Error: creating ChangeSet "updating-policy-33bdc757-49cf-4ae3-9305-060cf71858c3" for stack "": InvalidParameter: 1 validation error(s) found.
 - minimum field size of 1, CreateChangeSetInput.StackName.
```

**Anything else we need to know?**

**Versions**

```
[ℹ]  eksctl version 0.84.0
```

**Comment by ArturChe** [comment]
I have faced the same issue! And was able to update it using command line args.

**Comment by aclevername** [comment]
Thanks for opening the issue! This looks like a possible regression in the latest release. Can you reproduce this on `0.83.0` or `0.82.0` @artem-nefedov @ArturChe ?

**Comment by artem-nefedov** [comment]
@aclevername I already noted in the description that it's not reproduced on
0.83.0

**Comment by aclevername** [comment]
> @aclevername I already noted in the description that it's not reproduced on 0.83.0

:facepalm: sorry my bad! Thanks. We will investigate :smile:

**Comment by aclevername** [comment]
Fix will be out in 0.85.0-rc.0 later today :smile:

**Comment by Legion2** [comment]
I have this issue with eksctl version `0.86.0`
```
2022-03-03 22:32:43 [ℹ]  waiting for CloudFormation changeset "updating-policy-f671057e-65b5-4626-8699-0722de54b7e2" for stack "***"
2022-03-03 22:32:43 [!]  error executing Cloudformation changeSet updating-policy-f671057e-65b5-4626-8699-0722de54b7e2 in stack . Check the Cloudformation console for further details
Error: executing CloudFormation ChangeSet "updating-policy-f671057e-65b5-4626-8699-0722de54b7e2" for stack "": InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ExecuteChangeSetInput.StackName.
```
Note: I only replace the stack name once, the second `stack ""` was already empty

**Comment by Legion2** [comment]
With `0.85.0-rc.0` and `0.85.0` the same problem

**Comment by Skarlso** [comment]
Fix incoming
