### ISSUE TITLE
cryptic error when creating a nodegroup in cluster without public subnets

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#483]
If I have a cluster that doesn't have dedicated VPC and only has public subnets, I will get this:
```
 [130] >> ./eksctl create nodegroup --cluster=test-cluster-b-5 --region=eu-north-1
[ℹ]  using region eu-north-1
[ℹ]  nodegroup "ng-fcc874f0" will use "ami-06ee67302ab7cf838" [AmazonLinux2/1.11]
[ℹ]  will create a Cloudformation stack for nodegroup ng-fcc874f0 in cluster test-cluster-b-5
[ℹ]  creating nodegroup stack "eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0"
[✖]  unexpected status "ROLLBACK_COMPLETE" while waiting for CloudFormation stack "eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0" to reach "CREATE_COMPLETE" status
[ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
[ℹ]  AWS::CloudFormation::Stack/eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0: ROLLBACK_COMPLETE
[ℹ]  AWS::CloudFormation::Stack/eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0: ROLLBACK_IN_PROGRESS – "No export named eksctl-test-cluster-b-5-cluster::SubnetsPublic found. Rollback requested by user."
[ℹ]  AWS::CloudFormation::Stack/eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0: CREATE_IN_PROGRESS – "User Initiated"
[ℹ]  1 error(s) occurred and nodegroup hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete nodegroup ng-fcc874f0 --region=eu-north-1 --name=test-cluster-b-5'
[✖]  waiting for CloudFormation stack "eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0" to reach "CREATE_COMPLETE" status: ResourceNotReady: failed waiting for successful resource state
[✖]  failed to create nodegroup ng-fcc874f0 for cluster "test-cluster-b-5"
```

We could detect this condition earlier, and make error message more meaningful.

Namely, we could tell the user that they cannot create a  public nodegroup and should use `-P`.

**Comment by whereisaaron** [comment]
@errordeveloper I got this error because I forgot to specify the config file. When a cluster is created using a config file it would be nice to be able to resist changes that will cause drift from the config file. Maybe by checking an export on the cluster stack and warning the user or requiring a forcing option, if this is a config file cluster. Please protect me from myself, in other words 😄

**Comment by glerman** [comment]
Your post helped me dubug my failing nodegroup creation command. Thanks!

**Comment by ricardorqr** [comment]
> dedicated VPC

What causes this problem? I didn't get your post.

**Comment by ricardorqr** [comment]
> If I have a cluster that doesn't have dedicated VPC and only has public subnets, I will get this:
> 
> ```
>  [130] >> ./eksctl create nodegroup --cluster=test-cluster-b-5 --region=eu-north-1
> [ℹ]  using region eu-north-1
> [ℹ]  nodegroup "ng-fcc874f0" will use "ami-06ee67302ab7cf838" [AmazonLinux2/1.11]
> [ℹ]  will create a Cloudformation stack for nodegroup ng-fcc874f0 in cluster test-cluster-b-5
> [ℹ]  creating nodegroup stack "eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0"
> [✖]  unexpected status "ROLLBACK_COMPLETE" while waiting for CloudFormation stack "eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0" to reach "CREATE_COMPLETE" status
> [ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
> [ℹ]  AWS::CloudFormation::Stack/eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0: ROLLBACK_COMPLETE
> [ℹ]  AWS::CloudFormation::Stack/eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0: ROLLBACK_IN_PROGRESS – "No export named eksctl-test-cluster-b-5-cluster::SubnetsPublic found. Rollback requested by user."
> [ℹ]  AWS::CloudFormation::Stack/eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0: CREATE_IN_PROGRESS – "User Initiated"
> [ℹ]  1 error(s) occurred and nodegroup hasn't been created properly, you may wish to check CloudFormation console
> [ℹ]  to cleanup resources, run 'eksctl delete nodegroup ng-fcc874f0 --region=eu-north-1 --name=test-cluster-b-5'
> [✖]  waiting for CloudFormation stack "eksctl-test-cluster-b-5-nodegroup-ng-fcc874f0" to reach "CREATE_COMPLETE" status: ResourceNotReady: failed waiting for successful resource state
> [✖]  failed to create nodegroup ng-fcc874f0 for cluster "test-cluster-b-5"
> ```
> 
> We could detect this condition earlier, and make error message more meaningful.
> 
> Namely, we could tell the user that they cannot create a public nodegroup and should use `-P`.

What causes this problem? I didn't get your post.
