### ISSUE TITLE
eksctl create cluster with karpenter section fails

### ISSUE THREAD

**Issue by youwalther65** [weaveworks/eksctl#4859]
**What were you trying to accomplish?**
$ eksctl delete cluster -f eksctl-ipv6.yaml

**What happened?**
Hem installation of karpenter Helm chart failed

2022-02-28 13:46:28 [ℹ]  waiting for CloudFormation stack "eksctl-my-ipv6-cluster-karpenter"
2022-02-28 13:46:28 [ℹ]  1 task: { create IAM role for serviceaccount "karpenter/karpenter" }
2022-02-28 13:46:28 [ℹ]  1 task: { create IAM role for serviceaccount "karpenter/karpenter" }
2022-02-28 13:46:28 [ℹ]  building iamserviceaccount stack "eksctl-my-ipv6-cluster-addon-iamserviceaccount-karpenter-karpenter"
2022-02-28 13:46:28 [ℹ]  deploying stack "eksctl-my-ipv6-cluster-addon-iamserviceaccount-karpenter-karpenter"
2022-02-28 13:46:28 [ℹ]  waiting for CloudFormation stack "eksctl-my-ipv6-cluster-addon-iamserviceaccount-karpenter-karpenter"
2022-02-28 13:46:47 [ℹ]  waiting for CloudFormation stack "eksctl-my-ipv6-cluster-addon-iamserviceaccount-karpenter-karpenter"
2022-02-28 13:47:07 [ℹ]  waiting for CloudFormation stack "eksctl-my-ipv6-cluster-addon-iamserviceaccount-karpenter-karpenter"
2022-02-28 13:47:07 [ℹ]  adding identity "arn:aws:iam::618668373247:role/eksctl-KarpenterNodeRole-my-ipv6-cluster" to auth ConfigMap
2022-02-28 13:47:07 [ℹ]  adding Karpenter to cluster my-ipv6-cluster
Error: failed to install Karpenter: failed to install Karpenter chart: failed to install chart: timed out waiting for the condition

**How to reproduce it?**

$ **cat eksctl-ipv6.yaml**
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-ipv6-cluster
  version: "1.21"
  region: eu-west-1

kubernetesNetworkConfig:
  ipFamily: IPv6

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: false

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: v1.10.2-eksbuild.1 # optional
  - name: coredns
    version: v1.8.4-eksbuild.1 # optional
  - name: kube-proxy
    version: v1.21.2-eksbuild.2 # optional

karpenter:
  version: '0.6.3'
  createServiceAccount: true # default is false

managedNodeGroups:
  - name: x86-al2-on-demand-xl
    amiFamily: AmazonLinux2
    instanceTypes: [ "m6i.xlarge", "m6a.xlarge" ]
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 100
    volumeType: gp3
    volumeEncrypted: true
    privateNetworking: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::618668373247:policy/AmazonEKS_CNI_IPv6_Policy
    updateConfig:
      maxUnavailablePercentage: 33
    labels:
      os-distribution: amazon-linux-2

**Logs**
$ **helm list -n karpenter**
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS  CHART           APP VERSION
karpenter       karpenter       1               2022-02-28 13:47:10.6086826 +0100 CET   failed  karpenter-0.6.3 0.6.3

$ helm status karpenter -n karpenter
NAME: karpenter
LAST DEPLOYED: Mon Feb 28 13:47:10 2022
NAMESPACE: karpenter
STATUS: failed
REVISION: 1
TEST SUITE: None

$ **k get all -n karpenter**
NAME                             READY   STATUS             RESTARTS   AGE
pod/karpenter-5487d89b58-dhsjk   0/2     CrashLoopBackOff   14         13m

NAME                TYPE        CLUSTER-IP             EXTERNAL-IP   PORT(S)            AGE
service/karpenter   ClusterIP   fd6a:8c65:2b91::1476   <none>        8080/TCP,443/TCP   13m

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/karpenter   0/1     1            0           13m

NAME                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/karpenter-5487d89b58   1         1         0       13m

$ **k logs -n karpenter karpenter-5487d89b58-dhsjk -c controller**
panic: "" not a valid CLUSTER_ENDPOINT URL; CLUSTER_NAME is required

goroutine 1 [running]:
github.com/aws/karpenter/pkg/utils/options.MustParse()
        github.com/aws/karpenter/pkg/utils/options/options.go:48 +0x52e
main.init()
        github.com/aws/karpenter/cmd/controller/main.go:55 +0x53

$ **helm get values karpenter -n karpenter**
USER-SUPPLIED VALUES:
aws:
  defaultInstanceProfile: eksctl-KarpenterNodeInstanceProfile-my-ipv6-cluster
controller:
  clusterEndpoint: https://0624220F4195626209180ACB2F50100F.sk1.eu-west-1.eks.amazonaws.com
  clusterName: my-ipv6-cluster
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::618668373247:role/eksctl-my-ipv6-cluster-iamservice-role
  create: true

**Anything else we need to know?**
I know that Karpenter not yet officially supports IPv6. But there are workarounds in the provisioner config to do so. But at least Helm installlation shoudl succedd given that cluster endpoint and name are set for Helm

**Versions**
$ **eksctl version**
0.85.0

$ **eksctl info**
eksctl version: 0.85.0
kubectl version: v1.21.3
OS: linux

**Comment by Skarlso** [comment]
@youwalther65 Hi. The fix has been release in 0.86.0-rc. Would you mind please trying that? Thanks!

**Comment by youwalther65** [comment]
Thanks, this has helped, RC works !
