### ISSUE TITLE
releases are tagged sometimes with v prefix and sometimes without 

### ISSUE THREAD

**Issue by pre** [weaveworks/eksctl#4861]
I came here to open an issue as asked by @Skarlso https://github.com/weaveworks/eksctl/issues/4858#issuecomment-1054290170

> for example v0.85.0 vs 0.86.0

> This kind of releasing breaks tools like asdf - this old issue: https://github.com/weaveworks/eksctl/issues/4199 is now broken again

Related issues:
* https://github.com/weaveworks/eksctl/issues/4199
* https://github.com/weaveworks/eksctl/issues/4328
* https://github.com/weaveworks/eksctl/issues/4858

**Comment by aclevername** [comment]
thanks @pre , I'm going to re-open #4858 and close this, as I think more clarity is needed and that issue has the context.
