### ISSUE TITLE
Refactor code to use ValidateClusterConfig

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#4862]
### Description
Follow up from https://github.com/weaveworks/eksctl/issues/4627, https://github.com/weaveworks/eksctl/issues/4627#issuecomment-1044849491
Code areas that should be refactored to use `ValidateClusterConfig`

### 1. `doCreateCluster` in `pkg/ctl/create/cluster.go`
- [ ] [L143-L222](https://github.com/weaveworks/eksctl/blob/5c6580b47340ff41e8f8c3ac42e6c84a1cfdefcb/pkg/ctl/create/cluster.go#L143-L222)

We need to backfill tests here

### 2 `NewCTL` in `pkg/ctl/cmdutils/cmd.go`
- [ ] `NewCTL` [pkg/ctl/cmdutils/cmd.go](https://github.com/weaveworks/eksctl/blob/4388c8d14bde1e0f3cf663b2360d8744bd2e4184/pkg/ctl/cmdutils/cmd.go#L36)

We need to add tests or backfill tests here

### 3. `commonClusterConfigLoader` struct

[commonClusterConfigLoader](https://github.com/weaveworks/eksctl/blob/main/pkg/ctl/cmdutils/configfile.go) is a struct that is quite pervasive in `pkg/ctl`. It might require a larger refactoring solution and effort that is solely focused on that.

Used for validation in multiple `ctl/` packages by a large number of commands, such as:
- [ ] pkg/ctl/cmdutils/kms.go - `utils enable-secrets-encryption`
- [ ] pkg/ctl/cmdutils/scale.go - `scale nodegroup`
- [ ] pkg/ctl/cmdutils/fargate.go - `create fargate`, `delete fargate`
- [ ] pkg/ctl/cmdutils/addon.go - `create addon`, `upgrade addon`, `delete addon`
- [ ] pkg/ctl/cmdutils/gitops.go - `enable flux`
- [ ] pkg/ctl/disassociate/identity_provider.go - `get identityprovider`
- [ ] pkg/ctl/get/identityprovider.go - `disassociate identityprovider`
- [ ] pkg/ctl/associate/identity_provider.go - `associate identityprovider`

### 4. `ConfigLoaderBuilder` struct 

[ConfigLoaderBuilder](https://github.com/weaveworks/eksctl/blob/main/pkg/ctl/cmdutils/builder.go) is used to perform validations by the following commands in `ctl/`:
- [ ] `create cluster`, `get cluster`
- [ ] `create nodegroup`, `update nodegroup`, `get nodegroup`, `delete nodegroup`
- [ ] `utils update-cluster-logging`, `utils update-cluster-endpoints`, `utils associate-iam-oidc-provider`, `utils set-public-access-cidrs`
- [ ] `create iamserviceaccount`, `get iamserviceaccount`, `delete iamserviceaccount`
- [ ] `get labels`, `set labels`

### 5. `pkg/actions/nodegroup/create.go`
 [pkg/actions/nodegroup/create.go](https://github.com/weaveworks/eksctl/blob/5c6580b47340ff41e8f8c3ac42e6c84a1cfdefcb/pkg/actions/nodegroup/create.go)
- [ ] `ValidateLegacySubnetsForNodeGroups`
- [ ] `CanUseForPrivateNodeGroups()`
- [ ] `HasSufficientSubnets()`

**Comment by cPu1** [comment]
Great work, @nikimanoledaki. I just have a few points to note. 

Not everything in this list can/should go in `ValidateClusterConfig`. Some of the functions here interface with AWS APIs while `ValidateClusterConfig` is free of calls to external services. Additionally, the checks performed for some commands, like `create cluster` are applicable only to that command, so moving those checks to `ValidateClusterConfig` will result in them also running for `create nodegroup` etc.

**Comment by nikimanoledaki** [comment]
I completely agree with you! :) The list was made as a result of the previous ticket, which aimed to find all areas where "standard" validation code was not used. We need to see where we go from here. 

What the code areas listed above have in common is the following:
* 4/5 are in `pkg/ctl` (!) 
* they repeat a lot of validation that is done in other `ctl`s/packages/`ValidateClusterConfig`
* they mix validation of CLI params values and config file values
* they don't use `ValidateClusterConfig` 
* perhaps most importantly, **are largely untested**
* some set defaults as well as performing validation
* like you said: many even make calls to AWS APIs :) 

As you said during the PL last week, while it's good to first list out all the code areas, we need to see how to deal with each of these areas afterward. This should be done while keeping in mind that each `ctl` also has its own unique requirements. IMO a bit more design and planning is required, so perhaps this ticket is best treated as a spike to begin with.

**Comment by Himangini** [comment]
@Himangini and @nikimanoledaki to pair and break this ticket further down
