### ISSUE TITLE
Using AMI and overridebootstrap with create cluster fails

### ISSUE THREAD

**Issue by AqsaMemon** [weaveworks/eksctl#4868]
@alpana17, the argument to `/etc/eks/bootstrap.sh` needs to be the name of your cluster; in this case:
```yaml
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh alp-cluster-121-north-virginia
```
If you continue to have problems, please open a new issue.

_Originally posted by @Callisto13 in https://github.com/weaveworks/eksctl/issues/3563#issuecomment-903133321_

**Comment by Skarlso** [comment]
**@Skarlso** I am trying to install gitpod self hosted on eks. I am following this link :[https://github.com/gitpod-io/gitpod-eks-guide](https://github.com/gitpod-io/gitpod-eks-guide). I am working on eks-cluster.yaml file :[https://github.com/gitpod-io/gitpod-eks-guide/blob/main/eks-cluster.yaml](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/eks-cluster.yaml).
I did not make install yet. 
i tried command: eksctl create cluster -f test-managed-ami-example.yaml. Cluster is created when I don't use ami. As soon as I add ami and override bootstrap, it gives me error: failed to create cluster
I am missing something basic or conceptual.
Also I am using eksctl version 0.84.0 . 
I see in other forums they are using older version. Could that be a problem?
Here is the user data from launch template
```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary=9c9d686fab1e3599b7e29e4014bc8493b49be094cbd6b0a7199db7f962d4

--9c9d686fab1e3599b7e29e4014bc8493b49be094cbd6b0a7199db7f962d4
Content-Type: text/x-shellscript
Content-Type: charset="us-ascii"

#!/bin/bash
/etc/eks/bootstrap.sh snap --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup=services,eks.amazonaws.com/nodegroup-image=ami-0ad574da759c55c17'

--9c9d686fab1e3599b7e29e4014bc8493b49be094cbd6b0a7199db7f962d4--
```

**Comment by Skarlso** [comment]
Copied over. Continuing here.

**Comment by Skarlso** [comment]
I think this is not eksctl specific. You are trying to use a bootstrap script which is not what they are defining in their configuration example. Their AMI is probably something specific to this installation. Please try the eksctl configuration they are providing for installing gitpod here: https://github.com/gitpod-io/gitpod-eks-guide/blob/main/eks-cluster.yaml

**Comment by Himangini** [comment]
Dupe here https://github.com/weaveworks/eksctl/issues/4852
