### ISSUE TITLE
eksctl mapping for the ami id in different location

### ISSUE THREAD

**Issue by aravindsuram** [weaveworks/eksctl#4872]
**What were you trying to accomplish?**

**What happened?**

**How to reproduce it?**

**Logs**

**Anything else we need to know?**

**Versions**

```
$ eksctl info
```

**Comment by cPu1** [comment]
@aravindsuram, can you add some details to the issue? It's unclear what you're trying to achieve from the issue title. Do you mean you want to use an AMI ID that's in a region different from where you're creating a cluster? If so, that's not possible.
