### ISSUE TITLE
0.83->0.85: eksctl get clusters shows different status for "EKSCTL CREATED"

### ISSUE THREAD

**Issue by rwillmer** [weaveworks/eksctl#4888]
**What were you trying to accomplish?**

I wanted to list the current set of clusters, so I ran 
```$ eksctl get clusters```

**What happened?**

Using 0.83, the list of clusters was given, and the correct status of "True" was given in the "EKSCTL CREATED" column

I then updated eksctl to 0.85, and repeated the command. Now the incorrect status of "False" was given for the same clusters.

**How to reproduce it?**

Create a cluster using an old version of eksctl. Verify that "eksctl get clusters" shows that "EKSCTL CREATED" status as True using eksctl 0.83.

Now try "eksctl get clusters" with eksctl 0.85 and see that status turn to False

**Logs**

The verbose command adds no new information.

**Anything else we need to know?**

I upgraded eksctl using brew on OSX.

**Versions**

```
$ eksctl info
```

```
% eksctl info
eksctl version: 0.85.0
kubectl version: v1.22.4
OS: darwin
```

**Comment by Skarlso** [comment]
Yep, I saw that... 

```
 eksctl get cluster --profile skarlso
2022-03-03 13:14:07 [ℹ]  eksctl version 0.87.0-dev+7fed41bd.2022-03-03T12:51:13Z
2022-03-03 13:14:07 [ℹ]  using region us-west-2
NAME                    REGION          EKSCTL CREATED
nm-windows-cluster      us-west-2       False
test-kube-config-9      us-west-2       False
```

**Comment by nikimanoledaki** [comment]
Can confirm this bug :/ cc @Himangini

**Comment by cPu1** [comment]
A [PR](https://github.com/weaveworks/eksctl/pull/4911) has been opened to fix the issue, it'll be out in the next releaes.
