### ISSUE TITLE
`availabilityZones` parsing broken after upgrading to eksctl 0.86.0

### ISSUE THREAD

**Issue by guessi** [weaveworks/eksctl#4891]
**What were you trying to accomplish?**
Create a new cluster with `eksctl 0.86.0`

**What happened?**
Defined `availabilityZones` in ClusterConfig but it randomly generated subnets but not honor the YAML setting.

**How to reproduce it?**
Create a minimal ClusterConfig (see blow) then execute the command as `eksctl create cluster -f ./experimental.yaml --dry-run` and you should see bouncing `availabilityZones` being generated. Tried to search root cause from commit history, seems like it's related to #4735 and #4837.

Additional note, `eksctl create cluster --nodes=us-east-1a,us-east-1b ...` works as expected with no issue.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/984415/156624034-2a8d9767-c55e-4c62-9d8d-252bb3b16f7c.png">

**Logs**

Testing input:
```
$ cat ./experimental.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: experimental
  region: us-east-1

availabilityZones:
- us-east-1a
- us-east-1b
```

Tool version:
```
$ eksctl version
0.86.0
```

Unexpected results:
```
 $ for i in $(seq 1 3); do (echo "[[ Round ${i} ]]";eksctl create cluster -f ./experimental.yaml --dry-run | grep 'availabilityZones' -A 2; echo); done
[[ Round 1 ]]
availabilityZones:
- us-east-1b
- us-east-1f

[[ Round 2 ]]
availabilityZones:
- us-east-1b
- us-east-1d

[[ Round 3 ]]
availabilityZones:
- us-east-1c
- us-east-1e
```

**Anything else we need to know?**

It's was worked as expected before `0.85.0`

Tool version:
```
$ ./eksctl-v0.85.0 version
0.85.0
```

Results:
```
$ for i in $(seq 1 3); do (echo "[[ Round ${i} ]]";./eksctl-v0.85.0 create cluster -f ./experimental.yaml --dry-run | grep 'availabilityZones' -A 2; echo); done
[[ Round 1 ]]
availabilityZones:
- us-east-1a
- us-east-1b

[[ Round 2 ]]
availabilityZones:
- us-east-1a
- us-east-1b

[[ Round 3 ]]
availabilityZones:
- us-east-1a
- us-east-1b
```

**Versions**

```
$ eksctl info
eksctl version: 0.86.0
kubectl version: v1.23.4
OS: darwin
```

**Comment by guessi** [comment]
possibly caused by https://github.com/weaveworks/eksctl/pull/4828

**Comment by guessi** [comment]
Can be reproduced by command line input as well.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/984415/156625308-cba3ab61-673a-4759-9553-761a7e9407bb.png">

**Comment by Skarlso** [comment]
Hum, that is odd. I'll take a look!

**Comment by Skarlso** [comment]
Interesting, my commit just checks if the node-zones are defined or not and if yes, they should be part of the zones. But that is only if you are using not configuration! So that's probably not related. In fact, I'll try to test with a previous version, see if that works.

**Comment by Skarlso** [comment]
Oh you already did check. Nice.

**Comment by Skarlso** [comment]
I undid my changes and it still keeps doing that, so that's probably not it. Looking for something else.

**Comment by Skarlso** [comment]
Found the problem. We'll deal with it tomorrow. Thank you for this nice catch!!

**Comment by guessi** [comment]
@Skarlso just some notes as FYIs.

- I have used the same YAML config for quite a long time (thanks for your hard work), it was worked fine before `0.86.0`.
- I've tried `us-(east|west)-[12]`, same result.
- Tried with flag `--zones` (no YAML involved), no problem.
- Tried with flag `--node-zones` (no YAML involved), bouncing.

**Comment by guessi** [comment]
Test with CLI:

```
$ eksctl create cluster --without-nodegroup --zones us-east-1a,us-east-1b --node-zones us-east-1a,us-east-1b --name experimental --dry-run | head -4
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1a
- us-east-1b
```
```
$ eksctl create cluster --without-nodegroup --zones us-east-1a,us-east-1b --name experimental --dry-run | head -4
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1a
- us-east-1b
```
```
$ eksctl create cluster --without-nodegroup --node-zones us-east-1a,us-east-1b --name experimental --dry-run | head -4
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1c
- us-east-1d ##### Unexpected
```

**Comment by Skarlso** [comment]
@guessi Yeah, the validation got refactored and somewhere in there is a bug around the azs. @nikimanoledaki Is the expert in the area, she'll know what to do. ;) Thank you for the detailed description. :))

**Comment by guessi** [comment]
@Skarlso good to know there's an undergoing process to fix it. 👍 looking forward for 0.87.0+ release.

btw, it's just IMHO, I would suggest to have a known issue section on release page to avoid ppl created cluster/node in unexpected AZs, since not all instance types are available across AZs.

**Comment by nikimanoledaki** [comment]
Thanks for finding this quickly and for opening a really well-documented bug issue @guessi, we really appreciate it! 

We'll be shipping a fix in today's RC of `0.87.0` :)

**Comment by guessi** [comment]
@nikimanoledaki thanks for speedy update 👍

**Comment by guessi** [comment]
```
% ./eksctl-0.87.0-rc.0 version
0.87.0-rc.0
```

```
% ./eksctl-0.87.0-rc.0 create cluster --without-nodegroup --name experimental --dry-run | head -4
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1e
- us-east-1d

# Expected
```

```
% ./eksctl-0.87.0-rc.0 create cluster --without-nodegroup --name experimental --zones us-east-1a,us-east-1b --dry-run | head -4
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1a
- us-east-1b

# Expected
```

```
% ./eksctl-0.87.0-rc.0 create cluster --without-nodegroup --name experimental --zones us-east-1a,us-east-1b --node-zones us-east-1a,us-east-1b --dry-run | head -4
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1a
- us-east-1b

# Expected
```

```
% ./eksctl-0.87.0-rc.0 create cluster --without-nodegroup --name experimental --node-zones us-east-1a,us-east-1b --dry-run | head -4
Error: validation for --zones and --node-zones failed: zones must be defined if node-zones is provided and must be a superset of node-zones

# Expected
```

Confirmed fixed, thanks 💯
