### ISSUE TITLE
How to downgrade Kubernetes version 1.21 -> 1.19 to allow fargate-profiles?

### ISSUE THREAD

**Issue by ecc256** [weaveworks/eksctl#4907]
[managing-fargate-profiles](https://eksctl.io/usage/fargate-support/#managing-fargate-profiles) has a note:
> Note
> This operation is only supported on clusters that run on the **EKS platform version eks.5 or higher**.
> If the existing was created with a version of eksctl prior to 0.11.0, you will need to run eksctl update cluster before creating the Fargate profile.

From [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html):
The highest "Amazon EKS platform version" is **eks.4** for "Kubernetes version 1.21.5.
**eks.5** is available in Kubernetes version 1.19 and below (as of now).

Could update instructions to explain how to downgrade Kubernetes version 1.21 -> 1.19, please?

**Comment by cPu1** [comment]
>This operation is only supported on clusters that run on the EKS platform version eks.5 or higher.

This note is incomplete, that platform version requirement is for EKS 1.14, not for EKS versions 1.15 and above. You will be able to use Fargate profiles on EKS 1.21. We'll update the doc.
