### ISSUE TITLE
stack troubleshooter  should do a better job

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#491]
Based on what @kelseyhightower [pointed out](https://twitter.com/kelseyhightower/status/1090495903297728513):

 - it can hide too many non critical message (user can view those with `eksctl utils describe-stacks`, if they wish to do so)
- common errors can be recognised and summaries in a simpler way, e.g: limits, validation errors, etc

**Comment by errordeveloper** [comment]
Common examples:
- `2019-04-02T05:26:51Z [✖]  AWS::EC2::EIP/NATIP: CREATE_FAILED – "The maximum number of addresses has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: AddressLimitExceeded; Request ID: 6db57162-60f3-45cc-aad6-d0ea321116e1)"`
- number of VPCs

**Comment by errordeveloper** [comment]
See also: https://github.com/weaveworks/eksctl/issues/560, #https://github.com/weaveworks/eksctl/issues/792.

**Comment by errordeveloper** [comment]
@mhausenblas would you be interested to have a go at addressing some of these cases, e.g. VPC limits and instance type cases?

**Comment by murali-reddy** [comment]
@errordeveloper I am not very clear what is the suggested improvement.

> common errors can be recognised and summaries in a simpler way, e.g: limits, validation errors, etc

Are you suggesting that, eksctl should give more user-friendly (for those who does not know cloudformation etc) and more exact error message without going through `eksctl utils describe-stacks`?

**Comment by errordeveloper** [comment]
@murali-reddy yes, exactly.

So, for example, if we are not in verbose mode, and we have detected the following event:

```
[✖]  AWS::EC2::EIP/NATIP: CREATE_FAILED – "The maximum number of addresses has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: AddressLimitExceeded; Request ID: 6db57162-60f3-45cc-aad6-d0ea321116e1)"
```

We should just print something like this instead:
```
[✖] Unable to create cluster "<name>" in "<region>" as the limit of Elastic IPs (EIPs) was reached, at least one EIP is required for NAT gateway
```

We can also suggest disabling NAT gateway (which is now possible), but let's start simple for now. As that will need to be a link to the docs that haven't landed yet.

**Comment by errordeveloper** [comment]
I just noticed this:
```
[✖]  AWS::EC2::VPC/VPC: CREATE_FAILED – "The maximum number of VPCs has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: VpcLimitExceeded; Request ID: e0ad4fcd-d892-49ec-b074-9bb7f111439f)"
[✖]  AWS::EC2::InternetGateway/InternetGateway: CREATE_FAILED – "The maximum number of internet gateways has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: InternetGatewayLimitExceeded; Request ID: 4438845d-4764-41f9-941a-f85a13cee4c0)"
```
So it's possible to hit some of these limits at the same time, I though you'd only get to know about whichever you hit first... Something to keep in mind, we certainly want to tell users about all limits they hit.
