### ISSUE TITLE
Create Bottlerocket Managed Nodegroup from cli options with GPU AMI types

### ISSUE THREAD

**Issue by kdaula** [weaveworks/eksctl#4916]
story https://github.com/weaveworks/eksctl/issues/4916#issuecomment-1068977544

---
Create Bottlerocket nodegroup from cli options with GPU AMI types `BOTTLEROCKET_x86_64_NVIDIA` and `BOTTLEROCKET_ARM_64_NVIDIA` 
This is an extension to #4863 , and will be in-line with option 3 in [comment](https://github.com/weaveworks/eksctl/issues/4863#issuecomment-1055609051)

**Comment by Himangini** [comment]
thanks for opening the issue @kdaula 👍🏻

**Comment by Himangini** [comment]
@aclevername will fill out the feature request template

**Comment by aclevername** [comment]
summarising the above into a story

### Description
We currently only support creating unmanaged Bottlerocket GPU nodes, this story is for creating managed Bottlerocket GPU nodes.

To create other existing GPU managed nodegroups today eksctl specifies the relevant [AMIType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html#cfn-eks-nodegroup-amitype) in the cloudformation template too indicate its a GPU nodes. For example a GPU AL2 managed nodegroup will set AMIType to `AL2_x86_64_GPU`.

EKS are introducing two new AMITypes to support creating managed Bottlerocket GPU nodes, `BOTTLEROCKET_x86_64_NVIDIA` and `BOTTLEROCKET_ARM_64_NVIDIA`. We need to add support for this in eksctl

### Scope
When a user attempts to create a managed Bottlerocket nodegroup on a GPU instance type we should set the AMI type to  `BOTTLEROCKET_x86_64_NVIDIA` or `BOTTLEROCKET_ARM_64_NVIDIA` depending on if its x86 or ARM.

### User story
As a user of eksctl I want to be able to created managed Bottlerocket GPU nodes

### Acceptance Criteria


Given an existing EKS cluster
When I run `eksctl create nodegroup --node-ami-family bottlerocket --instance-type p2.xlarge` (or equivalent config file)
Then it should created a managed nodegroup, with the AMI family set to `BOTTLEROCKET_x86_64_NVIDIA`

Given an existing EKS cluster
When I run `eksctl create nodegroup --node-ami-family bottlerocket --instance-type r6g.medium` (or equivalent config file) (`r6*` is a ARM instance)
Then it should created a managed nodegroup, with the AMI family set to `BOTTLEROCKET_ARM_64_NVIDIA`


### Technical Notes

**Comment by Himangini** [comment]
@kdaula can you give us any updates around ETAs for AMI types please? 

> draft #5059
> 
> waiting for the AMI types to be released to test

**Comment by Skarlso** [comment]
Opened https://github.com/aws/aws-sdk-go-v2/issues/1719 to add support to V2.

**Comment by Skarlso** [comment]
Ah, found it! 🎉
