### ISSUE TITLE
Nodegroup listing stopped working after adding/removing other nodegroups

### ISSUE THREAD

**Issue by metasim** [weaveworks/eksctl#4917]
**What were you trying to accomplish?**

List nodegroups.

Running `eksctl get nodegroups --cluster my-cluster --region=us-east-1` results in:

    Error: getting nodegroup's kubernetes version: failed to list nodes: no nodes were found

**What happened?**
After adding and deleting some existing nodegroups, listing them stopped working.

**How to reproduce it?**

Outside of my environment, I don't know.

**Logs**

<details>
<pre>
2022-03-08 13:34:12 [▶]  role ARN for the current session is "arn:aws:iam::12345678:user/sfitch"
2022-03-08 13:34:12 [ℹ]  eksctl version 0.86.0
2022-03-08 13:34:12 [ℹ]  using region us-east-1
2022-03-08 13:34:13 [▶]  cluster = {
  Arn: "arn:aws:eks:us-east-1:12345678:cluster/my-cluster",
  CertificateAuthority: {
    Data: "..."
  },
  CreatedAt: 2019-12-18 15:02:43.537 +0000 UTC,
  Endpoint: "https://987654.yl4.us-east-1.eks.amazonaws.com",
  Identity: {
    Oidc: {
      Issuer: "https://oidc.eks.us-east-1.amazonaws.com/id/987654"
    }
  },
  KubernetesNetworkConfig: {
    IpFamily: "ipv4",
    ServiceIpv4Cidr: "10.100.0.0/16"
  },
  Logging: {
    ClusterLogging: [{
        Enabled: true,
        Types: [
          "api",
          "audit",
          "authenticator",
          "controllerManager",
          "scheduler"
        ]
      }]
  },
  Name: "my-cluster",
  PlatformVersion: "eks.3",
  ResourcesVpcConfig: {
    ClusterSecurityGroupId: "sg-0cd1de1985d2bd764",
    EndpointPrivateAccess: false,
    EndpointPublicAccess: true,
    PublicAccessCidrs: ["0.0.0.0/0"],
    SecurityGroupIds: ["sg-05c5663e6e05c80a0"],
    SubnetIds: [
      "subnet-0ce56934a5fff6f57",
      "subnet-0db1562797f080b15",
      "subnet-02a1d4b15b26ce533",
      "subnet-09fc3a33dbd535832",
      "subnet-05e842f30fc34902a",
      "subnet-0648eda3a2227bd8a",
      "subnet-0279bc452d174625f",
      "subnet-0ebb91ad566bd1041"
    ],
    VpcId: "vpc-0db787c2545d4b844"
  },
  RoleArn: "arn:aws:iam::12345678:role/eksctl-my-cluster-cluster-ServiceRole-MMSHW2FMOIDC",
  Status: "ACTIVE",
  Tags: {

  },
  Version: "1.20"
}
2022-03-08 13:34:13 [!]  retryable error (Throttling: Rate exceeded
	status code: 400, request id: f05cb45a-061c-4865-8b28-8924718dc882) from cloudformation/DescribeStacks - will retry after delay of 9.581088485s
2022-03-08 13:34:23 [!]  stack's status of nodegroup named eksctl-my-cluster-nodegroup-compute-cpu is DELETE_FAILED
2022-03-08 13:34:23 [!]  stack's status of nodegroup named eksctl-my-cluster-nodegroup-compute-gpu is DELETE_FAILED
2022-03-08 13:34:23 [▶]  nodegroups = [{
  Capabilities: ["CAPABILITY_IAM"],
  CreationTime: 2022-03-08 16:43:52.663 +0000 UTC,
  Description: "EKS nodes (AMI family: AmazonLinux2, SSH access: false, private networking: true) [created and managed by eksctl]",
  DisableRollback: false,
  DriftInformation: {
    StackDriftStatus: "NOT_CHECKED"
  },
  EnableTerminationProtection: false,
  Outputs: [
    {
      OutputKey: "FeaturePrivateNetworking",
      OutputValue: "true"
    },
    {
      ExportName: "eksctl-my-cluster-nodegroup-compute-gpu-2::InstanceRoleARN",
      OutputKey: "InstanceRoleARN",
      OutputValue: "arn:aws:iam::12345678:role/eksctl-my-cluster-nodegroup-notebo-NodeInstanceRole-1GX7QBR0QKHWD"
    },
    {
      OutputKey: "FeatureLocalSecurityGroup",
      OutputValue: "true"
    },
    {
      ExportName: "eksctl-my-cluster-nodegroup-compute-gpu-2::InstanceProfileARN",
      OutputKey: "InstanceProfileARN",
      OutputValue: "arn:aws:iam::12345678:instance-profile/eksctl-my-cluster-nodegroup-compute-gpu-2-NodeInstanceProfile-OPBWQ827PXCQ"
    },
    {
      OutputKey: "FeatureSharedSecurityGroup",
      OutputValue: "true"
    }
  ],
  RollbackConfiguration: {

  },
  StackId: "arn:aws:cloudformation:us-east-1:12345678:stack/eksctl-my-cluster-nodegroup-compute-gpu-2/eff07dc0-9efe-11ec-a972-0a493d282551",
  StackName: "eksctl-my-cluster-nodegroup-compute-gpu-2",
  StackStatus: "CREATE_COMPLETE",
  Tags: [
    {
      Key: "k8s.io/cluster-autoscaler/node-template/label/infra.example.io/role",
      Value: "compute-gpu"
    },
    {
      Key: "k8s.io/cluster-autoscaler/node-template/label/nvidia.com/gpu",
      Value: "true"
    },
    {
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "my-cluster"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-type",
      Value: "unmanaged"
    },
    {
      Key: "k8s.io/cluster-autoscaler/node-template/taint/infra.example.io/compute-gpu",
      Value: "true:NoSchedule"
    },
    {
      Key: "k8s.io/cluster-autoscaler/enabled",
      Value: "true"
    },
    {
      Key: "eksctl.io/v1alpha2/nodegroup-name",
      Value: "compute-gpu-2"
    },
    {
      Key: "k8s.io/cluster-autoscaler/my-cluster",
      Value: "owned"
    },
    {
      Key: "alpha.eksctl.io/cluster-name",
      Value: "my-cluster"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-name",
      Value: "compute-gpu-2"
    },
    {
      Key: "infra.example.io/role",
      Value: "compute-gpu"
    },
    {
      Key: "k8s.io/cluster-autoscaler/node-template/taint/dedicated",
      Value: "nvidia.com/gpu=true"
    },
    {
      Key: "alpha.eksctl.io/eksctl-version",
      Value: "0.82.0"
    },
    {
      Key: "infra.example.io/env",
      Value: "rpod"
    }
  ]
} {
  Capabilities: ["CAPABILITY_IAM"],
  CreationTime: 2022-03-08 16:43:52.642 +0000 UTC,
  Description: "EKS nodes (AMI family: AmazonLinux2, SSH access: false, private networking: true) [created and managed by eksctl]",
  DisableRollback: false,
  DriftInformation: {
    StackDriftStatus: "NOT_CHECKED"
  },
  EnableTerminationProtection: false,
  Outputs: [
    {
      OutputKey: "FeaturePrivateNetworking",
      OutputValue: "true"
    },
    {
      ExportName: "eksctl-my-cluster-nodegroup-compute-cpu-2::InstanceRoleARN",
      OutputKey: "InstanceRoleARN",
      OutputValue: "arn:aws:iam::12345678:role/eksctl-my-cluster-nodegroup-notebo-NodeInstanceRole-HF56OCJYPZKS"
    },
    {
      OutputKey: "FeatureLocalSecurityGroup",
      OutputValue: "true"
    },
    {
      ExportName: "eksctl-my-cluster-nodegroup-compute-cpu-2::InstanceProfileARN",
      OutputKey: "InstanceProfileARN",
      OutputValue: "arn:aws:iam::12345678:instance-profile/eksctl-my-cluster-nodegroup-compute-cpu-2-NodeInstanceProfile-TYJ7Z6190FU4"
    },
    {
      OutputKey: "FeatureSharedSecurityGroup",
      OutputValue: "true"
    }
  ],
  RollbackConfiguration: {

  },
  StackId: "arn:aws:cloudformation:us-east-1:12345678:stack/eksctl-my-cluster-nodegroup-compute-cpu-2/efee33d0-9efe-11ec-ada4-12303de40525",
  StackName: "eksctl-my-cluster-nodegroup-compute-cpu-2",
  StackStatus: "CREATE_COMPLETE",
  Tags: [
    {
      Key: "k8s.io/cluster-autoscaler/node-template/taint/hub.jupyter.org/dedicated",
      Value: "user:NoSchedule"
    },
    {
      Key: "k8s.io/cluster-autoscaler/my-cluster",
      Value: "owned"
    },
    {
      Key: "alpha.eksctl.io/cluster-name",
      Value: "my-cluster"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-name",
      Value: "compute-cpu-2"
    },
    {
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "my-cluster"
    },
    {
      Key: "infra.example.io/role",
      Value: "compute-cpu"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-type",
      Value: "unmanaged"
    },
    {
      Key: "k8s.io/cluster-autoscaler/enabled",
      Value: "true"
    },
    {
      Key: "alpha.eksctl.io/eksctl-version",
      Value: "0.82.0"
    },
    {
      Key: "infra.example.io/env",
      Value: "prod"
    },
    {
      Key: "eksctl.io/v1alpha2/nodegroup-name",
      Value: "compute-cpu-2"
    },
    {
      Key: "k8s.io/cluster-autoscaler/node-template/label/hub.jupyter.org/node-purpose",
      Value: "user"
    }
  ]
} {
  Capabilities: ["CAPABILITY_IAM"],
  CreationTime: 2022-03-08 16:43:52.56 +0000 UTC,
  Description: "EKS nodes (AMI family: AmazonLinux2, SSH access: false, private networking: true) [created and managed by eksctl]",
  DisableRollback: false,
  DriftInformation: {
    StackDriftStatus: "NOT_CHECKED"
  },
  EnableTerminationProtection: false,
  Outputs: [
    {
      OutputKey: "FeaturePrivateNetworking",
      OutputValue: "true"
    },
    {
      ExportName: "eksctl-my-cluster-nodegroup-infra-system::InstanceRoleARN",
      OutputKey: "InstanceRoleARN",
      OutputValue: "arn:aws:iam::12345678:role/eksctl-my-cluster-nodegroup-eartha-NodeInstanceRole-H85TOXPD9SO7"
    },
    {
      OutputKey: "FeatureLocalSecurityGroup",
      OutputValue: "true"
    },
    {
      ExportName: "eksctl-my-cluster-nodegroup-infra-system::InstanceProfileARN",
      OutputKey: "InstanceProfileARN",
      OutputValue: "arn:aws:iam::12345678:instance-profile/eksctl-my-cluster-nodegroup-infra-system-NodeInstanceProfile-M439JWB0PNL"
    },
    {
      OutputKey: "FeatureSharedSecurityGroup",
      OutputValue: "true"
    }
  ],
  RollbackConfiguration: {

  },
  StackId: "arn:aws:cloudformation:us-east-1:12345678:stack/eksctl-my-cluster-nodegroup-infra-system/efd94c40-9efe-11ec-b1cd-0e14a0d8b9ad",
  StackName: "eksctl-my-cluster-nodegroup-infra-system",
  StackStatus: "CREATE_COMPLETE",
  Tags: [
    {
      Key: "k8s.io/cluster-autoscaler/my-cluster",
      Value: "owned"
    },
    {
      Key: "alpha.eksctl.io/cluster-name",
      Value: "my-cluster"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-name",
      Value: "infra-system"
    },
    {
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "my-cluster"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-type",
      Value: "unmanaged"
    },
    {
      Key: "k8s.io/cluster-autoscaler/enabled",
      Value: "true"
    },
    {
      Key: "alpha.eksctl.io/eksctl-version",
      Value: "0.82.0"
    },
    {
      Key: "eksctl.io/v1alpha2/nodegroup-name",
      Value: "infra-system"
    }
  ]
} {
  Capabilities: ["CAPABILITY_IAM"],
  CreationTime: 2021-04-27 20:37:53.088 +0000 UTC,
  Description: "EKS nodes (AMI family: AmazonLinux2, SSH access: false, private networking: true) [created and managed by eksctl]",
  DisableRollback: false,
  DriftInformation: {
    StackDriftStatus: "NOT_CHECKED"
  },
  EnableTerminationProtection: false,
  Outputs: [
    {
      OutputKey: "FeaturePrivateNetworking",
      OutputValue: "true"
    },
    {
      ExportName: "eksctl-my-cluster-nodegroup-infra-system-2::InstanceRoleARN",
      OutputKey: "InstanceRoleARN",
      OutputValue: "arn:aws:iam::12345678:role/eksctl-my-cluster-nodegroup-eartha-NodeInstanceRole-1FKD8BX9WKNR7"
    },
    {
      OutputKey: "FeatureLocalSecurityGroup",
      OutputValue: "true"
    },
    {
      ExportName: "eksctl-my-cluster-nodegroup-infra-system-2::InstanceProfileARN",
      OutputKey: "InstanceProfileARN",
      OutputValue: "arn:aws:iam::12345678:instance-profile/eksctl-my-cluster-nodegroup-infra-system-2-NodeInstanceProfile-JT29Z5HGAGV0"
    },
    {
      OutputKey: "FeatureSharedSecurityGroup",
      OutputValue: "true"
    }
  ],
  RollbackConfiguration: {

  },
  StackId: "arn:aws:cloudformation:us-east-1:12345678:stack/eksctl-my-cluster-nodegroup-infra-system-2/707e8720-a798-11eb-8f19-125ba4d329dd",
  StackName: "eksctl-my-cluster-nodegroup-infra-system-2",
  StackStatus: "CREATE_COMPLETE",
  Tags: [
    {
      Key: "k8s.io/cluster-autoscaler/my-cluster",
      Value: "owned"
    },
    {
      Key: "alpha.eksctl.io/cluster-name",
      Value: "my-cluster"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-name",
      Value: "infra-system-2"
    },
    {
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "my-cluster"
    },
    {
      Key: "alpha.eksctl.io/nodegroup-type",
      Value: "unmanaged"
    },
    {
      Key: "infra.example.io/role",
      Value: "infra-system"
    },
    {
      Key: "k8s.io/cluster-autoscaler/enabled",
      Value: "true"
    },
    {
      Key: "alpha.eksctl.io/eksctl-version",
      Value: "0.44.0"
    },
    {
      Key: "infra.example.io/env",
      Value: "prod"
    },
    {
      Key: "eksctl.io/v1alpha2/nodegroup-name",
      Value: "infra-system-2"
    }
  ]
}]

</pre>
</details>

**Anything else we need to know?**

MacOS Monterey on Apple Silicon via `brew`

**Versions**
```
$ eksctl info
eksctl version: 0.86.0
kubectl version: v1.23.3
OS: darwin
```

**Comment by nikimanoledaki** [comment]
Hi @metasim, thanks for opening this issue. 

Currently eksctl finds the nodegroup by searching for the label `alpha.eksctl.io/nodegroup-name=<nodegroup-name>`. We should change the label's key to `eks.amazonaws.com/nodegroup`.

**Comment by Skarlso** [comment]
This would be backwards compatible, right? We just add it to a list of labels we can use to locate resources?

**Comment by cPu1** [comment]
>After adding and deleting some existing nodegroups, listing them stopped working.

@metasim how did you add new nodegroups? Was it via eksctl or some other tool?

**Comment by nikimanoledaki** [comment]
Hi again @metasim, as well as the info requested by @cPu1 in the comment above, could you also please provide any eksctl config file that you used to create the cluster and nodegroups, with any sensitive info redacted? That way we can reproduce this error. Thank you!

**Comment by metasim** [comment]
Note: The cluster already existed; I ran `eksctl create nodegroup -f cluster.yaml` to add new nodegroups.

**Comment by metasim** [comment]
> I'm juggling two issues which are really similar in nature.

We've all been there! 😄

**Comment by Skarlso** [comment]
Indeed! :D 

Can you do me a favour please and check the node in amazon console that it has some eksctl labels? If it doesn't that's the problem. :)

**Comment by metasim** [comment]
@Skarlso 
This work?

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/131013/158887713-b56b3247-72d7-4525-8bed-81d446081d8f.png">

**Comment by Skarlso** [comment]
Yeah, that actually looks okay. Dang. :/ I have to continue investigating what's wrong. :(

Thank you! :)

**Comment by Skarlso** [comment]
Hi, sorry, I was out with covid.

@metasim this is still a thing, right?

**Comment by Skarlso** [comment]
I have unable to reproduce this. :/ Waiting for some comment if this still is an issue.

**Comment by metasim** [comment]
@Skarlso Appears to be working now. Maybe something on the AWS side of things? Thanks for looking into this.

**Comment by Skarlso** [comment]
Possible, yeah. Super cool that it works. :) Thank you for confirming! :)
