### ISSUE TITLE
Does eksctl support customizing env variables for aws-node and worker nodes?

### ISSUE THREAD

**Issue by hq6** [weaveworks/eksctl#4919]
In my environment, I need to specify the HTTP_PROXY environment variable to make EKS work correctly due to lack of outbound internet and lack of permissions to write into route tables.

Is there a mechanism to inject extra environment variables into the daemonset aws-node?
Also, there is a mechanism to run custom scripts to set up env variables on unmanaged node groups?

**Comment by Skarlso** [comment]
Hi @hq6

You could use the bootstrap command to define any environment properties. For that though you would have to define a bootstrap override. Currently, there is no other way to push environment properties to aws-node. There is an existing issue in the aws-go-sdk for this here: https://github.com/aws/aws-sdk-go/issues/4159

**Comment by hq6** [comment]
Thanks for the pointer! I can try with the bootstrap override for the unmanaged node groups.

For the aws-node issue, since it's blocked on the dependency issue, should I keep this issue open or close it?

**Comment by Skarlso** [comment]
@hq6 Yeah, it's worth having it around to increase visibility! :)

**Comment by Himangini** [comment]
Closing this since the linked aws-go-sdk issue is closed.
