### ISSUE TITLE
Allow adding a post-bootstrap command that is run after the main bootstrap script.

### ISSUE THREAD

**Issue by hq6** [weaveworks/eksctl#4924]
**What feature/behavior/change do you want?**

I want to be able to append an arbitrary (ideally inline) bash script to the UserData that is part of the LaunchTemplates for unmanaged node groups. For example, this could be an option under each nodeGroup:

```
nodeGroups:
 - name: ng-1
    postBootStrap: |
    #!/bin/bash
    
    HTTP_PROXY="https://my_proxy"
    systemctl restart kubelet

```

**Why do you want this feature?**

I want to use eksctl to create a cluster in an environment without outbound internet access. In such an environment, everything goes through a Squid proxy, so I need to be able to tell kubelet and docker about the proxy.

I could do this with a managed node group and a custom launch template, but that would require fully managing my own launch template, which I would prefer to avoid if I can.

**Comment by Skarlso** [comment]
Hi!

Is there a reason why you aren't using `overrideBootstrapCommand`?

**Comment by hq6** [comment]
I missed it when I was looking at the schema.

I think I can use [preBootstrapCommands](https://eksctl.io/usage/schema/#nodeGroups-preBootstrapCommands) for this.

**Comment by hq6** [comment]
Actually, looking more carefully, I think these are insufficient.

The problem is that the command I was going to add post-bootstrap requires reading the value of `API_SERVER_URL`, which is set by `eksctl`. 
If I use preBootstrapCommands or overrideBootstrapCommand, it's not clear how I can get access to the value of this variable.

**Comment by Skarlso** [comment]
Hmm, I see no immediate reason why to NOT have a post bootstrap script. 🤔 And it even looks like it would be relatively easy to implement.

I have to discuss this with the team, but this might be doable if there are no security concerns or things like, easy to mess up everything. :)

**Comment by Skarlso** [comment]
BTW, that would mean that you would HAVE to define the override as well. We don't control the bootstrapping normally, which means, we don't really have a hook unless we execute the bootstrapping.

**Comment by Skarlso** [comment]
Oh, and of course this is only for unmanaged nodegroups.

**Comment by hq6** [comment]
Sorry I think I'm now a bit confused about exactly which part of the UserData in each LaunchTemplate for the unmanaged node groups is considered "bootstrapping" and is overriden by overriding the bootstrap.

Is it the part after the `API_SERVER_URL` is written to a file or something else?

If it's afterwards, then it's possible that postBootstrap would be equivalent to overriding the bootstrap command.

**Comment by Skarlso** [comment]
Well, a postBoostrap would literally just be slapped after the bootstrap script. So if there is anything that you can do in the overridBootstrap that has the same effect then an postBootstrap doesn't make sense, yes. :/

**Comment by Skarlso** [comment]
`API_SERVER_URL` is just passed to the EKS bootstrap script such as:

```
echo "eksctl: running /etc/eks/bootstrap"
/etc/eks/bootstrap.sh "${CLUSTER_NAME}" \
  --apiserver-endpoint "${API_SERVER_URL}" \
  --b64-cluster-ca "${B64_CLUSTER_CA}" \
  --dns-cluster-ip "${CLUSTER_DNS}" \
  --kubelet-extra-args "${KUBELET_EXTRA_ARGS}" \
  --container-runtime "${CONTAINER_RUNTIME}"
```

**Comment by hq6** [comment]
Okay, I think I have a better sense of where I'd been confused before. Just to check my understanding, here's the whole `UserData` block:
```
#cloud-config
packages: null
runcmd:
- - /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
- - /var/lib/cloud/scripts/eksctl/bootstrap.al2.sh
write_files:
- content: '{}'
  owner: root:root
  path: /etc/eksctl/kubelet-extra.json
  permissions: "0644"
- content: |-
    CLUSTER_DNS=172.20.0.10
    CONTAINER_RUNTIME=dockerd
    CLUSTER_NAME=tidb-eks-cluster
    API_SERVER_URL= // Redacted
    B64_CLUSTER_CA= // Redacted
    NODE_LABELS=alpha.eksctl.io/cluster-name=tidb-eks-cluster,alpha.eksctl.io/nodegroup-name=tidb-1b
    NODE_TAINTS=dedicated=tidb:NoSchedule
  owner: root:root
  path: /etc/eksctl/kubelet.env
  permissions: "0644"
- content: |
    #!/bin/bash

    set -o errexit
    set -o pipefail
    set -o nounset

    source /etc/eksctl/kubelet.env # file written by bootstrapper

    # Use IMDSv2 to get metadata
    TOKEN="$(curl --silent -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 600" http://169.254.169.254/latest/api/token)"
    function get_metadata() {
      curl --silent -H "X-aws-ec2-metadata-token: $TOKEN" "http://169.254.169.254/latest/meta-data/$1"
    }

    API_SERVER_URL="${API_SERVER_URL}"
    B64_CLUSTER_CA="${B64_CLUSTER_CA}"
    INSTANCE_ID="$(get_metadata instance-id)"
    INSTANCE_LIFECYCLE="$(get_metadata instance-life-cycle)"
    CLUSTER_DNS="${CLUSTER_DNS:-}"
    NODE_TAINTS="${NODE_TAINTS:-}"
    MAX_PODS="${MAX_PODS:-}"
    NODE_LABELS="${NODE_LABELS},node-lifecycle=${INSTANCE_LIFECYCLE},alpha.eksctl.io/instance-id=${INSTANCE_ID}"

    KUBELET_ARGS=("--node-labels=${NODE_LABELS}")
    [[ -n "${NODE_TAINTS}" ]] && KUBELET_ARGS+=("--register-with-taints=${NODE_TAINTS}")
    # --max-pods as a CLI argument is deprecated, this is a workaround until we deprecate support for maxPodsPerNode
    [[ -n "${MAX_PODS}" ]] && KUBELET_ARGS+=("--max-pods=${MAX_PODS}")
    KUBELET_EXTRA_ARGS="${KUBELET_ARGS[@]}"

    CLUSTER_NAME="${CLUSTER_NAME}"
    KUBELET_CONFIG='/etc/kubernetes/kubelet/kubelet-config.json'
    KUBELET_EXTRA_CONFIG='/etc/eksctl/kubelet-extra.json'
    TMP_KUBE_CONF='/tmp/kubelet-conf.json'
    CONTAINER_RUNTIME="${CONTAINER_RUNTIME:-dockerd}" # default for al2 just in case, not used in ubuntu
  owner: root:root
  path: /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
  permissions: "0755"
- content: |
    #!/bin/bash

    set -o errexit
    set -o pipefail
    set -o nounset

    source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh

    echo "eksctl: running /etc/eks/bootstrap"
    /etc/eks/bootstrap.sh "${CLUSTER_NAME}" \
      --apiserver-endpoint "${API_SERVER_URL}" \
      --b64-cluster-ca "${B64_CLUSTER_CA}" \
      --dns-cluster-ip "${CLUSTER_DNS}" \
      --kubelet-extra-args "${KUBELET_EXTRA_ARGS}" \
      --container-runtime "${CONTAINER_RUNTIME}"

    echo "eksctl: merging user options into kubelet-config.json"
    trap 'rm -f ${TMP_KUBE_CONF}' EXIT
    jq -s '.[0] * .[1]' "${KUBELET_CONFIG}" "${KUBELET_EXTRA_CONFIG}" > "${TMP_KUBE_CONF}"
    mv "${TMP_KUBE_CONF}" "${KUBELET_CONFIG}"

    systemctl daemon-reload
    echo "eksctl: restarting kubelet-eks"
    systemctl restart kubelet
    echo "eksctl: done"
  owner: root:root
  path: /var/lib/cloud/scripts/eksctl/bootstrap.al2.sh
  permissions: "0755"
```

overrideBootstrap replaces the contents of the script ` /etc/eks/bootstrap.sh`.
preBootStrap, when given, runs immediately before ` /etc/eks/bootstrap.sh`, but after `/etc/eksctl/kubelet.env` is written.

Is this correct, or are each of these in a different place than I'm guessing?

**Comment by hq6** [comment]
If the above was correct, I was originally envisioning a `postBootstrap` option running immediately after  the invocation of `/etc/eks/bootstrap.sh`, which would imply I could specify it without needing to override the bootstrap, as you mentioned was required [here](https://github.com/weaveworks/eksctl/issues/4924#issuecomment-1066412006).

**Comment by Skarlso** [comment]
Aha, aha. I see. Yeah, makes sense. 🤔

I think it's a reasonable thing to add. Yeah, we might be okay by not defining the override. I'm just wondering what our hook is here then. We literally just clobber this together as a list of scripts. If you leave out the bootstrap part, then what's "post" in that context if that makes sense?

```go
	for _, command := range b.ng.PreBootstrapCommands {
		config.AddShellCommand(command)
	}

	if b.ng.OverrideBootstrapCommand != nil {
		config.AddShellCommand(*b.ng.OverrideBootstrapCommand)
	} else {
		if api.IsEnabled(b.ng.EFAEnabled) {
			scripts = append(scripts, script{name: "efa.al2.sh", contents: assets.EfaAl2Sh})
		}
		scripts = append(scripts, script{name: "bootstrap.legacy.al2.sh", contents: bootstrapLegacyAl2Sh})
	}

	if err = addFilesAndScripts(config, files, scripts); err != nil {
		return "", err
	}

```

It's just a list of scripts and files.

**Comment by Skarlso** [comment]
Which is what I meant by, we have to define the bootstrap then, because otherwise it's just a script in the list of scripts and it would be considered as a pre... because it's just a list.

**Comment by Skarlso** [comment]
We can do that in the code, of course. I'm not saying the USER has to define it. But we will have to override it if post is defined.

Something similar is done in the terraform EKS provider.

```bash
#!/bin/bash
set -ex

${pre_bootstrap_user_data ~}

# Custom user data template provided for rendering
B64_CLUSTER_CA=${cluster_auth_base64}
API_SERVER_URL=${cluster_endpoint}
/etc/eks/bootstrap.sh ${cluster_name} ${bootstrap_extra_args} --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL
${post_bootstrap_user_data ~}
```

**Comment by hq6** [comment]
To be explicit, the code that sets up user data when bootstrap is not
overridden is a completely different code path?

**Comment by Skarlso** [comment]
Nope, we always define userData, just in different ways in different scenarios.

Whether or not you define override, the path is the same, just with an `if ng.OverrideBootstrapCommand != nil {` in between.

**Comment by Skarlso** [comment]
And I'm saying that it is technically possible, just be aware that in the background it will be overwritten. :D We are talking about the same thing here. I'm just saying that we will have to define it in the code because otherwise there is no concept of `post` because there is no hook of any kind. It's just a list of scripts. :)

**Comment by Skarlso** [comment]
So basically, if `post` is defined, we will, in the background, create an override and append the post script to it. Otherwise, it's just a script that runs before the override. Similar to what terraform does in terms of `post`.

**Comment by hq6** [comment]
That makes sense, thanks!
