### ISSUE TITLE
kube-proxy stuck on ImagePullBackOff - Requested image not found

### ISSUE THREAD

**Issue by NadavkOptimalQ** [weaveworks/eksctl#4929]
**What were you trying to accomplish?**
I tried adding a new node pool with ARM nodes.

**What happened?**
The node is stuck on status NotReady with this error 
`container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized`

I was trying to fix this issue and I ran 
```
eksctl utils update-aws-node
eksctl utils update-coredns
eksctl utils update-kube-proxy
```

I looked at the pods on kube-system and found that two kube-proxy pods (one from the new nodepool and one from an old nodepool with regular linux nodes) are both stuck on ErrImagePull with this error:
```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  18m                  default-scheduler  Successfully assigned kube-system/kube-proxy-h4np6 to XXX.XXX.eu-west-1.compute.internal
  Normal   Pulling    16m (x4 over 18m)    kubelet            Pulling image "602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.21.5-eksbuild.2"
  Warning  Failed     16m (x4 over 18m)    kubelet            Failed to pull image "602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.21.5-eksbuild.2": rpc error: code = Unknown desc = Error response from daemon: manifest for 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.21.5-eksbuild.2 not found: manifest unknown: Requested image not found
  Warning  Failed     16m (x4 over 18m)    kubelet            Error: ErrImagePull
  Warning  Failed     16m (x6 over 18m)    kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m2s (x64 over 18m)  kubelet            Back-off pulling image "602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.21.5-eksbuild.2"
```

**How to reproduce it?**
Not really sure

**Anything else we need to know?**
The new node pool is on version v1.21.5-eks-9017834
The old node pool is on version v1.21.2-eks-55daa9d

There are two nodes in the old node pool. One is fine with the kube-proxy using image v1.21.2-eksbuild.2

**Versions**
```
eksctl version: 0.60.0
kubectl version: v1.22.4
OS: darwin
```

**Comment by nikimanoledaki** [comment]
> I tried adding a new node pool with ARM nodes.

Hi @NadavkOptimalQ, how did you try to achieve this? Could you please share any steps or config file used to do this so that we can try to reproduce the error? Thank you!

**Comment by yechiel-optimalq** [comment]
the issue seems to be that eksctl is setting the kube-proxy version to be kube-proxy:v1.21.5-eksbuild.2... 
Updating the cluster from the GUI (adding the kube-proxy addon) set the image to be 1.21.2-eksbuild.2 and then it actually works..

**Comment by tanvp112** [comment]
> eksctl version: 0.60.0

Suggest you try again with the latest eksctl version.

**Comment by Skarlso** [comment]
These two versions are definitely trouble: 
```
eksctl version: 0.60.0
kubectl version: v1.22.4
```

Please try the latest as suggested by the previous comment.
