### ISSUE TITLE
Incorrect DNS setup

### ISSUE THREAD

**Issue by gitnik** [weaveworks/eksctl#493]
**What happened?**
When starting a container on a freshly created cluster, the DNS setup seems not to be working. There are different nameservers being used in different pods

```
[ec2-user@host]$ cat /etc/resolv.conf
options timeout:2 attempts:5
; generated by /usr/sbin/dhclient-script
search eu-central-1.compute.internal us-west-2.compute.internal
nameserver 192.168.0.2
```

This works fine and I am able to normally connect to the internet:
```
[ec2-user@host]$ ping google.com
PING google.com (172.217.22.46) 56(84) bytes of data.
```

When I now create a container via kubectl:
`kubectl run -ti --image chickenmaru/nettools test`

and execute the same commands, I get the following:
```
bash-4.3# cat /etc/resolv.conf
nameserver 10.100.0.10
search kube-system.svc.cluster.local svc.cluster.local cluster.local eu-central-1.compute.internal us-west-2.compute.internal
options ndots:5
bash-4.3# ping google.com
ping: unknown host google.com
```

Weirdly enough, the pod that were created by k8s itself (like kube-proxy), have the following resolve file:
```
nameserver 192.168.0.2
search eu-central-1.compute.internal us-west-2.compute.internal
options timeout:2 attempts:5
```

At first I thought I had run into [this issue ](https://github.com/docker/libnetwork/issues/2187), but I am using AL2.

Here's the config I use to create the cluster:
```yaml
apiVersion: eksctl.io/v1alpha3
kind: ClusterConfig

metadata:
  name: production
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    allowSSH: true
```

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.19"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

I also found this issue and I'm not sure if I'm experiencing the same problem: https://github.com/weaveworks/eksctl/issues/428

Any help would be appreciated

**Comment by gitnik** [comment]
Alright big surprise: Just minutes after complaining I find the solution.
Setting `sharedSecurityGroup: true` fixed the issue for me. Even though this is then technically not a bug I still feel there's some improvements to be made here in terms of documentation. What's the use case of not sharing a security group and thus having non working DNS in the cluster?

**Comment by errordeveloper** [comment]
hi @gitnik 

> Setting `sharedSecurityGroup: true` fixed the issue for me.

It is supposed to be enabled by default, but it's not when you use config file with 0.1.19. We've fixed it for 0.1.20, which is due in the next few days.

> Even though this is then technically not a bug I still feel there's some improvements to be made here in terms of documentation.

We generally need create some more config file examples and document certain behaviours better, however this was unintentional.

> What's the use case of not sharing a security group and thus having non working DNS in the cluster?

The use-case is that some folks may wish to opt-out from this and isolate a nodegroup from everything else. Those would be the kind of users who know what they are doing and would be taking care of enable DNS or making their apps work without DNS as such (you can use service discovery APIs directly, if you wish to). However, this is a niche use-case.

So to summaries - this is a known issue with 0.1.19 that was fixed in master, and it only affects those using  config file, it's to do with defaulting logic for config file.

**Comment by errordeveloper** [comment]
Closing in favour of https://github.com/weaveworks/eksctl/issues/496.

**Comment by gitnik** [comment]
Hey, thanks a lot for the insight! Glad to hear this is already fixed :) Thanks for your efforts in making EKS more approachable!
