### ISSUE TITLE
Requesting Info for Flux docs - `eksctl` manager

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/eksctl#4931]
Greetings, we are supporting Flux+EKS users and have found the effects of the Server-Side Apply behavior have different implications depending on which version of `eksctl` was used to create the cluster.

I would like to make sure that it is documented somewhere prominently, which version the `eksctl` CLI started using the `eksctl` manager in managedFields. This is the first version that will not experience the issue we observed. You may be aware of the issue regarding server-side apply that breaking change which has been (finalized? hopefully) as of Flux 0.26.x-0.27.x, ref: https://fluxcd.io/docs/faq/#why-are-kubectl-edits-rolled-back-by-flux

Maybe it isn't a change in eksctl at all, but that certain clusters simply pre-dated server-side apply. I don't know enough about eksctl to answer this definitively yet, or point at the specific "red line" which demarcates who will experience this issue and who will not. The best guess I have right now is, clusters which ran Kubernetes earlier than v1.18 and have annotations that were applied then, will experience this issue, since that pre-dates the General Availability of server-side apply (and so those fields can't have had a manager other than `kubectl`.)

The problem experienced is that older clusters which were created before Server-side Apply, are dropping their annotations after an upgrade to Flux 0.26 or Flux 0.27+ – this is by design, any annotations or drift with the `kubectl` manager are reverted as drift.

User was testing a Flux upgrade on a newly provisioned EKS staging cluster, but a production target cluster was older and provisioned by an older version of eksctl. I looked for an issue that mentioned server-side apply but didn't find one right away. (We are certain that the problem does not persist on new clusters provisioned by the latest version of eksctl.)

Can someone provide insight about whether `eksctl` has changed its behavior in this regard at any point, (or is it only the Kubernetes API who I should be pointing the finger at here?)

**Comment by aclevername** [comment]
Hey @kingdonb :wave: thanks for opening the issue.

> Can someone provide insight about whether eksctl has changed its behavior in this regard at any point, (or is it only the Kubernetes API who I should be pointing the finger at here?)



I've gone through the code (as well as looking at older eksctl tags) and can't find anywhere we consciously add the managed field tag for eksctl. I can see that we have some code for [removing it from `ServiceAccounts`](https://github.com/weaveworks/eksctl/blob/3bc088df6e8e0f59ceeaed7ccccb544f42e21855/pkg/actions/addon/create.go#L136) that are created by eksctl, so perhaps all eksctl created resources were at some point in time having this field set. Creating a new cluster and running various eksctl commands to create/update resources:
- `eksctl utils update-coredns`
- `eksctl create iamserviceaccount`

none of these resources have the managed field tags before or after. I'm assuming your assumption about this only applying to long-lived k8s clusters from pre v1.18 is a reasonable guess
