### ISSUE TITLE
No export named eksctl-sandbox-cluster::ClusterSecurityGroupId found. Rollback requested by user.

### ISSUE THREAD

**Issue by zvazquez** [weaveworks/eksctl#4940]
**What were you trying to accomplish?**
Add a manage nodegroup to an existing EKS cluster

**What happened?**
While trying to add the manage nodegroup, the cloudformation process fails with the following error:

`No export named eksctl-sandbox-cluster::ClusterSecurityGroupId found. Rollback requested by user.`

**How to reproduce it?**
`eksctl create nodegroup --config-file=sandbox-mng.yaml`

sandbox-mng.yaml:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: sandbox
  region: us
vpc:
  id: "vpc-0a5c50557bccc602b"
  securityGroup: "sg-0e104430610614c93"
  subnets:
    private:
      us-west-2b:
        id: "subnet-2b"
      us-west-2c:
        id: "subnet-2c"
      us-west-2d:
        id: "subnet-2d"
    public:
      us-west-2b:
        id: "subnet-2bp"
      us-west-2c:
        id: "subnet-2cp
      us-west-2d:
        id: "subnet-2dp"
managedNodeGroups:
  - name: sandbox-2
    privateNetworking: false
    availabilityZones: [2b, 2c, 2d]
    instanceType: m5.4xlarge
    maxSize: 12
    minSize: 3
    desiredCapacity: 3
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    volumeKmsKeyID: key
    iam:
      withAddonPolicies:
        autoScaler: true


```

**Logs**
```
eksctl get clusters -v 4 --region=us 
2022-03-11 15:51:03 [▶]  role ARN for the current session is user
2022-03-11 15:51:03 [ℹ]  eksctl version 0.87.0
2022-03-11 15:51:03 [ℹ]  using region us
NAME    REGION          EKSCTL CREATED
sandbox us       False
```

```
eksctl create nodegroup --config-file=sandbox-mng.yaml 
2022-03-11 15:40:58 [ℹ]  eksctl version 0.87.0
2022-03-11 15:40:58 [ℹ]  using region us
2022-03-11 15:40:58 [ℹ]  will use version 1.20 for new nodegroup(s) based on control plane version
I0311 15:41:01.145336    1432 request.go:668] Waited for 1.0032706s due to client-side throttling, not priority and fairness, request: GET:https://D2AA4068A645A7D1855AC74387E9C5A8.sk1.us.eks.amazonaws.com/apis/acme.cert-manager.io/v1?timeout=32s
I0311 15:41:11.145325    1432 request.go:668] Waited for 11.0012962s due to client-side throttling, not priority and fairness, request: GET:https://D2AA4068A645A7D1855AC74387E9C5A8.sk1.us.eks.amazonaws.com/apis/vpcresources.k8s.aws/v1beta1?timeout=32s
2022-03-11 15:41:15 [ℹ]  nodegroup "sandbox-2" will use "" [AmazonLinux2/1.20]
2022-03-11 15:41:17 [ℹ]  3 existing nodegroup(s) (sandbox-west2b-2,sandbox-west2c-2,sandbox-west2d-2) will be excluded
2022-03-11 15:41:17 [ℹ]  1 nodegroup (sandbox-2) was included (based on the include/exclude rules)
2022-03-11 15:41:17 [ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "sandbox"
2022-03-11 15:41:17 [ℹ]
2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "sandbox-2" } }
}
2022-03-11 15:41:17 [ℹ]  checking cluster stack for missing resources
2022-03-11 15:41:18 [ℹ]  cluster stack is missing resources for Managed Nodegroups
2022-03-11 15:41:18 [ℹ]  adding missing resources to cluster stack
2022-03-11 15:41:19 [!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 93cc787e-1963-4aaa-9b4a-155afa772dfd) from cloudformation/DescribeStacks - will retry after delay of 6.153000628s
2022-03-11 15:41:26 [ℹ]  re-building cluster stack "eksctl-sandbox-cluster"
2022-03-11 15:41:26 [✔]  all resources in cluster stack "eksctl-sandbox-cluster" are up-to-date
2022-03-11 15:41:27 [ℹ]  building managed nodegroup stack "eksctl-sandbox-nodegroup-sandbox-2"
2022-03-11 15:41:27 [ℹ]  deploying stack "eksctl-sandbox-nodegroup-sandbox-2"
2022-03-11 15:41:27 [ℹ]  waiting for CloudFormation stack "eksctl-sandbox-nodegroup-sandbox-2"
2022-03-11 15:41:44 [ℹ]  waiting for CloudFormation stack "eksctl-sandbox-nodegroup-sandbox-2"
2022-03-11 15:41:45 [✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-sandbox-nodegroup-sandbox-2"
2022-03-11 15:41:45 [ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
2022-03-11 15:41:45 [ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
2022-03-11 15:41:45 [ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=us-west-2 --cluster=sandbox --name=<name>' for each of the failed nodegroup
2022-03-11 15:41:45 [✖]  waiting for CloudFormation stack "eksctl-sandbox-nodegroup-sandbox-2": ResourceNotReady: failed waiting for successful resource state
Error: failed to create nodegroups for cluster "sandbox"
```

**Anything else we need to know?**
A cluster created using the console where we are trying to add manage nodegroups, the existing nodegroups are unmanage and we did not have any problem to install them.

**Versions**

```
eksctl version: 0.87.0
kubectl version: v1.20.4
OS: linux
```

**Comment by tanvp112** [comment]
> unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-sandbox-nodegroup-sandbox-2"

What's the error detail reported at CloudFormation console?

**Comment by dvkvarma** [comment]
I'm also running into the same error after upgrading eksctl to 0.88 version.

Below is error from cloud formation console.

`No export named eksctl-<cluster-name>-cluster::ClusterSecurityGroupId found. Rollback requested by user.`

**Comment by zvazquez** [comment]
The error in Cloudformation is what I mentioned on my original message

No export named eksctl-sandbox-cluster::ClusterSecurityGroupId found. Rollback requested by user.

Nothing else.

**Comment by Skarlso** [comment]
Hey @zvazquez!

This is still a relevant issue, right?

**Comment by zvazquez** [comment]
Hi,

Still is, we have survived with unmanage node groups, but we really would like to move to managed node groups.

Let me know if I should provide any information.

Thanks,

Zareh

**Comment by Skarlso** [comment]
Thank you, Zareh, for confirming!

We'll investigate this.

**Comment by Skarlso** [comment]
Also, just to confirm. You did add all the necessary tags and labels to the security group that are described here? https://eksctl.io/usage/unowned-clusters/

**Comment by Skarlso** [comment]
BTW, I assume this is reducted and not the actual value here? 
```
metadata:
  name: sandbox
  region: us
```

And that the security group is in the same region in which you are trying to create the cluster in?

**Comment by ricardorqr** [comment]
> **What were you trying to accomplish?** Add a manage nodegroup to an existing EKS cluster
> 
> **What happened?** While trying to add the manage nodegroup, the cloudformation process fails with the following error:
> 
> `No export named eksctl-sandbox-cluster::ClusterSecurityGroupId found. Rollback requested by user.`
> 
> **How to reproduce it?** `eksctl create nodegroup --config-file=sandbox-mng.yaml`
> 
> sandbox-mng.yaml:
> 
> ```
> apiVersion: eksctl.io/v1alpha5
> kind: ClusterConfig
> metadata:
>   name: sandbox
>   region: us
> vpc:
>   id: "vpc-0a5c50557bccc602b"
>   securityGroup: "sg-0e104430610614c93"
>   subnets:
>     private:
>       us-west-2b:
>         id: "subnet-2b"
>       us-west-2c:
>         id: "subnet-2c"
>       us-west-2d:
>         id: "subnet-2d"
>     public:
>       us-west-2b:
>         id: "subnet-2bp"
>       us-west-2c:
>         id: "subnet-2cp
>       us-west-2d:
>         id: "subnet-2dp"
> managedNodeGroups:
>   - name: sandbox-2
>     privateNetworking: false
>     availabilityZones: [2b, 2c, 2d]
>     instanceType: m5.4xlarge
>     maxSize: 12
>     minSize: 3
>     desiredCapacity: 3
>     volumeSize: 100
>     volumeType: gp2
>     volumeEncrypted: true
>     volumeKmsKeyID: key
>     iam:
>       withAddonPolicies:
>         autoScaler: true
> ```
> 
> **Logs**
> 
> ```
> eksctl get clusters -v 4 --region=us 
> 2022-03-11 15:51:03 [▶]  role ARN for the current session is user
> 2022-03-11 15:51:03 [ℹ]  eksctl version 0.87.0
> 2022-03-11 15:51:03 [ℹ]  using region us
> NAME    REGION          EKSCTL CREATED
> sandbox us       False
> ```
> 
> ```
> eksctl create nodegroup --config-file=sandbox-mng.yaml 
> 2022-03-11 15:40:58 [ℹ]  eksctl version 0.87.0
> 2022-03-11 15:40:58 [ℹ]  using region us
> 2022-03-11 15:40:58 [ℹ]  will use version 1.20 for new nodegroup(s) based on control plane version
> I0311 15:41:01.145336    1432 request.go:668] Waited for 1.0032706s due to client-side throttling, not priority and fairness, request: GET:https://D2AA4068A645A7D1855AC74387E9C5A8.sk1.us.eks.amazonaws.com/apis/acme.cert-manager.io/v1?timeout=32s
> I0311 15:41:11.145325    1432 request.go:668] Waited for 11.0012962s due to client-side throttling, not priority and fairness, request: GET:https://D2AA4068A645A7D1855AC74387E9C5A8.sk1.us.eks.amazonaws.com/apis/vpcresources.k8s.aws/v1beta1?timeout=32s
> 2022-03-11 15:41:15 [ℹ]  nodegroup "sandbox-2" will use "" [AmazonLinux2/1.20]
> 2022-03-11 15:41:17 [ℹ]  3 existing nodegroup(s) (sandbox-west2b-2,sandbox-west2c-2,sandbox-west2d-2) will be excluded
> 2022-03-11 15:41:17 [ℹ]  1 nodegroup (sandbox-2) was included (based on the include/exclude rules)
> 2022-03-11 15:41:17 [ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "sandbox"
> 2022-03-11 15:41:17 [ℹ]
> 2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "sandbox-2" } }
> }
> 2022-03-11 15:41:17 [ℹ]  checking cluster stack for missing resources
> 2022-03-11 15:41:18 [ℹ]  cluster stack is missing resources for Managed Nodegroups
> 2022-03-11 15:41:18 [ℹ]  adding missing resources to cluster stack
> 2022-03-11 15:41:19 [!]  retryable error (Throttling: Rate exceeded
>         status code: 400, request id: 93cc787e-1963-4aaa-9b4a-155afa772dfd) from cloudformation/DescribeStacks - will retry after delay of 6.153000628s
> 2022-03-11 15:41:26 [ℹ]  re-building cluster stack "eksctl-sandbox-cluster"
> 2022-03-11 15:41:26 [✔]  all resources in cluster stack "eksctl-sandbox-cluster" are up-to-date
> 2022-03-11 15:41:27 [ℹ]  building managed nodegroup stack "eksctl-sandbox-nodegroup-sandbox-2"
> 2022-03-11 15:41:27 [ℹ]  deploying stack "eksctl-sandbox-nodegroup-sandbox-2"
> 2022-03-11 15:41:27 [ℹ]  waiting for CloudFormation stack "eksctl-sandbox-nodegroup-sandbox-2"
> 2022-03-11 15:41:44 [ℹ]  waiting for CloudFormation stack "eksctl-sandbox-nodegroup-sandbox-2"
> 2022-03-11 15:41:45 [✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-sandbox-nodegroup-sandbox-2"
> 2022-03-11 15:41:45 [ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
> 2022-03-11 15:41:45 [ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
> 2022-03-11 15:41:45 [ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=us-west-2 --cluster=sandbox --name=<name>' for each of the failed nodegroup
> 2022-03-11 15:41:45 [✖]  waiting for CloudFormation stack "eksctl-sandbox-nodegroup-sandbox-2": ResourceNotReady: failed waiting for successful resource state
> Error: failed to create nodegroups for cluster "sandbox"
> ```
> 
> **Anything else we need to know?** A cluster created using the console where we are trying to add manage nodegroups, the existing nodegroups are unmanage and we did not have any problem to install them.
> 
> **Versions**
> 
> ```
> eksctl version: 0.87.0
> kubectl version: v1.20.4
> OS: linux
> ```

Have you solved this problem?

**Comment by Skarlso** [comment]
There was no response to any of my questions so no. We have not. And I'm no longer working on eksctl.
