### ISSUE TITLE
Fix Slack notifications for releases

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4944]
The release jobs were migrated from CircleCI to GitHub Actions but the functionality to send Slack notifications upon completion of the jobs is still missing.

**Comment by aclevername** [comment]
The credential is in the repo already, we just have to add the slack messages back into the github actions

**Comment by Himangini** [comment]
We should add the slack notifications to the build all distros jobs as well.

**Comment by Himangini** [comment]
PS you can use the eksctl-ci repository for reference
