### ISSUE TITLE
how can i attach existing role for cluster role

### ISSUE THREAD

**Issue by junghoon15** [weaveworks/eksctl#4954]
As i mentioned in title, is there any possible way to attach existing role i just created to cluster while using `eksctl create cluster` command?

i tried using below command in `cluster.yaml` file but still cluster is created with auto generated role like
`arn:aws:iam::[USER]:role/eksctl-[CLUSER_NAME]-cluster-ServiceRole-randomcode`

![스크린샷 2022-03-15 오후 5 39 08](https://user-images.githubusercontent.com/54789523/158338633-bfdad1ff-a82e-4eff-8392-4eb006925915.png)

**Comment by Skarlso** [comment]
@junghoon15 Hi. Your config is correct, but note that it's called `serviceRoleARN` and not `serviceRoleArn`.

**Comment by Skarlso** [comment]
https://eksctl.io/usage/schema/ -- take a look at the config schema for the correct spelling. :)

**Comment by junghoon15** [comment]
@Skarlso wow...i was using `instanceRoleARN` in nodeGroups while `serviceRoleArn` in iam. you just save my time !! thx a lot
