### ISSUE TITLE
[Task] Extend the integration tests with testing overrideBootstrapCommand and custom AMI features

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#4972]
### Summary

Right now, we don't have any integration tests which test custom AMIs and using overrideBootstrapCommand feature. This is not so good, because we have no idea when these introduce a failure such as, the node not being able to join the cluster any longer.

### Technical Notes

This requires us creating and maintaining a custom AMI that the tests can use. But this isn't such a problem because we could also use AMIs produced by AWS. The important part is to just `set` it. However, that obviously won't test features such as, what if I don't have ANY bootstrap scripts? Overwriting it through our config should still make the node work, since we are setting the required user-data.

**Comment by aclevername** [comment]
A story for tests :see_no_evil: this is a chore! :grin:

**Comment by Skarlso** [comment]
It didn't have a CHORE template. :D

**Comment by aclevername** [comment]
@Himangini SOS :joy: we should add a chore template
