### ISSUE TITLE
[Bug] eksctl nodegroup create exits with 0 when nodegroup has failed to create

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4977]
### What were you trying to accomplish?

run eksctl nodegroup create after first failed due to aws internals

### What happened?

>$ eksctl nodegroup create failingnodegroup

this fails for example with

>AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Resource handler returned message: "[Issue(Code=NodeCreationFailure, Message=Instances failed to join the kubernetes cluster, ResourceIds=[i-00521e6fb963853bf])] (Service: null, Status Code: 0, Request ID: null, Extended Request ID: null)" (RequestToken: 378e75a7-0279-4aa6-6a3e-35a25227f0ac, HandlerErrorCode: GeneralServiceException)"

and exits with error level 1

**when** running the the command again

>$ eksctl nodegroup create ...

>1 existing nodegroup(s) (failingnodegroup)

eksctl reports that the nodegroup has been created (it is not) and exits with 0

eksctl 0.87.0

**Comment by pkit** [comment]
+1 here.
Nodegroup creation failed because of AWS quota limit, when quota was increased `eksctl create nodegroup` happily exists although the CF stack is in failed rollback state.
I think in light of my previous issue #4941 something needs to be done about the whole cloud formation strategy.
