### ISSUE TITLE
[Bug] remoteNodegroups contains failed stacks that are not nodegroups

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4978]
### What happened?

>$ eksctl nodegroup create failingnodegroup

which fails due to aws internal, then run it again

>$ eksctl nodegroup create ...

and eksctl says that nodegroup is existing

>1 existing nodegroup(s) (failingnodegroup)

but only the failed (rollbacked) stack exists and the nodegroup does not exist in EKS.

prob due to filtering somewhere in https://github.com/weaveworks/eksctl/blob/7a59b2869bd57b6ddf1e7c00c899fd1f5b1cda8c/pkg/ctl/cmdutils/filter/nodegroup_filter.go#L123

**Comment by Himangini** [comment]
Hi @matti. Thanks for reporting this bug 👍 If you have a fix in mind, we are happy to accept PRs, otherwise the core team will get to it soon.

**Comment by matti** [comment]
@Himangini sorry I'm not familiar enough with the codebase to make a fix. I'm currently workarounding this by deleting the failed stacks.
