### ISSUE TITLE
[Bug] eksctl delete cluster exits when cluster is still being deleted

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4979]
### What were you trying to accomplish?

eksctl delete cluster kluster

### What happened?

```
$ eksctl delete cluster --region=eu-north-1 --name=north-1
2022-03-20 17:16:23 [ℹ]  eksctl version 0.87.0
2022-03-20 17:16:23 [ℹ]  using region eu-north-1
2022-03-20 17:16:24 [ℹ]  deleting EKS cluster "north-1"
2022-03-20 17:16:24 [ℹ]  deleted 0 Fargate profile(s)
2022-03-20 17:16:25 [✔]  kubeconfig has been updated
2022-03-20 17:16:25 [ℹ]  cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
2022-03-20 17:16:26 [ℹ]  1 task: { delete cluster control plane "north-1" [async] }
2022-03-20 17:16:26 [ℹ]  will delete stack "eksctl-north-1-cluster"
2022-03-20 17:16:26 [✔]  all cluster resources were deleted

$ echo $?
0
```

however, the stack / cluster has not been deleted because of cloudformation says:

>ControlPlane | DELETE_FAILED | Cannot delete because cluster north-1 currently has an update in progress (Service: Eks, Status Code: 409, Request ID: 79312daf-acf0-4f92-8d17-133d16c32ff9)

and it *looks* like it has been DELETE_IN_PROGRESS for 1h+ now. 

yes, this is an AWS issue, but shouldn't eksctl delete cluster return after everything has been cleaned?

eksctl 0.87.0

**Comment by matti** [comment]
And, the cluster is still listed in the AWS EKS UI.

**Comment by matti** [comment]
And `eksctl get` still returns it:

```
$ eksctl get cluster --region=eu-north-1 --name=north-1
2022-03-20 17:26:36 [ℹ]  eksctl version 0.87.0
2022-03-20 17:26:36 [ℹ]  using region eu-north-1
NAME	VERSION	STATUS	CREATED			VPC			SUBNETS									SECURITYGROUPS		PROVIDER
north-1	1.21	ACTIVE	2022-03-20T10:23:24Z	vpc-028e2ebf6137fc642	subnet-02bc2ed66e1b59564,subnet-0391cadc5e4871e63,subnet-070dff97cebb6a7f3,subnet-09b746d38264fabd2,subnet-0a6a7a2dfb06bbded,subnet-0e0066d28ba6b61cd	sg-07b4bfc10dc8fdf79	EKS
```

**Comment by matti** [comment]
after two hours the stack went to DELETE_FAILED state and I had to re-issue stack delete.

so the eksctl "[✔]  all cluster resources were deleted" is misleading

**Comment by Skarlso** [comment]
To truly have everything deleted including the stack run:

```
eksctl delete cluster -f config --wait --force
```

This will wait for a stack to complete deletion and go to the next item when there is an error like, cluster doesn't exist, but the stack does and you want to delete it.

**Comment by matti** [comment]
hmm, why would anybody want to run `eksctl delete cluster` without `--wait --force` ?

**Comment by matti** [comment]
why is there no `--force` for `eksctl delete nodegroup`, only `--wait`
