### ISSUE TITLE
[Feature] Change `overrideBootstrapCommand` semantics to preserve environmental variables

### ISSUE THREAD

**Issue by hq6** [weaveworks/eksctl#4991]
### What feature/behavior/change do you want?

Recently, I've been experimenting with `overrideBootstrapCommand` and discovered that specifying this option for a `nodeGroup` completely replaces the userData.

When I do not specify `overrideBootstrapCommand` for a node group, the node's userData writes three files and then executes all the latter two.
 * `/etc/eksctl/kubelet.env`
 * `/var/lib/cloud/scripts/eksctl/bootstrap.helper.sh`
 * `/var/lib/cloud/scripts/eksctl/bootstrap.al2.sh`.

When I do specify `overrideBootstrapCommand`, the node's userData writes no files, and directly executes the override. That means the override has no access to variables normally written to the first two of the above files, such as the following:
```
    NODE_LABELS=alpha.eksctl.io/nodegroup-name=pd-1c,alpha.eksctl.io/cluster-name=tidb-eks-cluster
    NODE_TAINTS=dedicated=pd:NoSchedule
    CLUSTER_DNS=172.20.0.10
    CONTAINER_RUNTIME=dockerd
    CLUSTER_NAME=tidb-eks-cluster
    API_SERVER_URL=https://AE907FC5AD70A58F52F01AF04F60D28D.gr7.us-west-2.eks.amazonaws.com
```

The behavior I want is: When I specify `overrideBootstrapCommand`, the first two files are written, and the third file is replaced by the commands in the override. It can be written a file or inlined, but I'd like access to the contents of the first two files.

### Why do you want this feature?

This is another, possibly simpler way to solve the problem I described in #4924 without schema changes.
By specifying copy-pasting the contents of `/var/lib/cloud/scripts/eksctl/bootstrap.al2.sh` into my overrideBootstrapCommand and then adding to it, I can get the same effect of being able to run custom code in the LaunchTemplate without losing all the useful variables.

I believe the proposed schema change is relatively harmless with respect to backward compatibility because existing users of the `overrideBootstrapCommand` can entirely ignore the two files if they do not need them.

**Comment by Skarlso** [comment]
This will change once https://github.com/weaveworks/eksctl/pull/4968 is merged. Please read the description of that PR and corresponding announcement and tickets. :)

**Comment by hq6** [comment]
This has been fixed.

**Comment by Skarlso** [comment]
Yay, thanks!
