### ISSUE TITLE
Eliminating usage of `aws/aws-sdk-go` (v1) STS is blocked on `sigs.k8s.io/aws-iam-authenticator/pkg/token`

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4993]
As part of migrating to AWS SDK v2 (#4877), eksctl will migrate the usage of all AWS SDK v1 clients to AWS SDK v2. The dependency `sigs.k8s.io/aws-iam-authenticator/pkg/token`, however, is still using the STS v1 client, preventing us from eliminating all usages of AWS SDK v1. We can work around this by providing a wrapper implementation that satisfies the `stsiface.STS` interface and uses the v2 client for the implementation.

**Comment by Skarlso** [comment]
Even if we do provide a wrapper implementation the dependency will not go away completely, since the implementation will have to import input and return types. :( :sadpanda:
