### ISSUE TITLE
Avoid maintaining a script for generating interfaces from structs

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4994]
https://github.com/weaveworks/eksctl/pull/4926 added a program for fixing interfaces generated from structs by the ifacemaker tool. This issue is to find a path forward so that we don't have to maintain this code in eksctl, potentially by contributing a fix upstream to ifacemaker.

**Comment by Himangini** [comment]
In case the upstream PR doesnt go through, we should make sure our side of things are well tested and we should add tests for it

**Comment by Skarlso** [comment]
Once the PR lands, we can remove the script and change generate script to look like this:

```bash
"./ifacemaker" -f "${AWS_SDK_DIR}/*.go" -s Client -i "${INTERFACE_NAME}" -p awsapi \
    -y "${INTERFACE_NAME} provides an interface to the AWS ${INTERFACE_NAME} service." \
    -c "Code generated by ifacemaker; DO NOT EDIT." \
    -m "${PACKAGE_NAME}" > "../${SERVICE_NAME}.go"
```

And everything should work. :)
