### ISSUE TITLE
Scrape and convert existing Kops cluster api for subnets, security groups, instance groups

### ISSUE THREAD

**Issue by StevenACoffman** [weaveworks/eksctl#50]
I'm not sure if this is out of scope of this project, but I'd love to be able to convert our existing kops clusters to EKS without the manual work.

Thanks!

**Comment by errordeveloper** [comment]
This sounds great, potentially more easily achiveble then using any random pre-ey VPC.

**Comment by errordeveloper** [comment]
We could re-use kops code too.
