### ISSUE TITLE
feat: Instance ID Node Label

### ISSUE THREAD

**Issue by mumoshu** [weaveworks/eksctl#500]
**Why do you want this feature?**

#411 (via #237) allows us to deploy AWS SSM agents as a daemonset, so that we can use Sessions Manager to open terminal sessions into nodes, as an alternative to SSH.

You need to run `start-session` providing the EC2 instance ID of the node:

```console
$ aws ssm start-session --target i-04ffadbaae98a5bd0
```

But there's no straightforward way to obtain the instance of a specific Kubernetes node. One way would be to query it by runnign `aws ec2 describe-instances --filter ...`, but I want something easier.

**What feature/behavior/change do you want?**

Let's enhance `eksctl` so that every node has its instance ID in a dedicated node label, which can is shown on `kubectl get node --show-labels`:

```
$ kubectl get node --show-labels
NAME                                                 STATUS    ROLES     AGE       VERSION   LABELS
ip-192-168-119-97.ap-northeast-1.compute.internal    Ready     <none>    16h       v1.11.5   alpha.eksctl.io/cluster-name=mycluster1,alpha.eksctl.io/nodegroup-name=nodegroup1,alpha.eksctl.io/instance-id=i-04ffadbaae98a5bd0,...(snip)
```

Implementation-wise, I'd just add a key-value to `kubelet`'s `--node-labels` flag:

```
--node-labels alpha.eksctl.io/instance-id=$(curl http://169.254.169.254/latest/meta-data/ instance-id)
```

**Comment by errordeveloper** [comment]
Yes, I think it maybe a good idea. However, I believe there is now a mode where instance ID can be use as node name. I'd consider making that the default, unless there're any major issues with. That would be generally much nicer, as `ip-192-168-119-97.ap-northeast-1.compute.internal` kind of names never made much sense to anyone, they only were used due to limitations in Kubernetes. Let's look into it!

**Comment by mumoshu** [comment]
> kind of names never made much sense to anyone

Agreed :)

I can't find the concrete step to use instance IDs as node names though. Looking into these upstream issues - would there be any chance that the configuration switch for that isn't implemented yet?

https://github.com/kubernetes/kubernetes/issues/11883
https://github.com/kubernetes/kubernetes/issues/54482

**Comment by errordeveloper** [comment]
It's possible that I have missrembered a SIG discussion, perhaps we should ask @nckturner @d-nishi and @christopherhein  to confirm

**Comment by mumoshu** [comment]
@errordeveloper Thanks for confirming :)

@nckturner @d-nishi @christopherhein Would you mind informing me about the state of "EC2 instance ID as the node name"?

My observation says it is planned but not implemented yet:

- The current restriction of "private DNS name as the node name" is [noted to be subject to change](https://github.com/kubernetes/cloud-provider-aws#proper-node-names) in the out-of-tree aws-cloud-provider. But I see there's no change relevant to that yet.
- [kubelet must also be enhanced to accept a user-provided node name even when a cloud-provider is enabled](https://github.com/kubernetes/kubernetes/issues/54482#issuecomment-375704624). I see no relevant change to kubelet though.

**Comment by mumoshu** [comment]
@christopherhein Thanks for the response.

The oldest issue regarding this I think was written by @justinsb is https://github.com/kubernetes/kubernetes/issues/11883. Perhaps it can be said as the origination?

Anyway, seeing it has been closed due to inactivity, we may need a dedicated person to work on it.

**Comment by mumoshu** [comment]
Opened #509 to track the instance-id-as-node-name feature.
