### ISSUE TITLE
Create cluster config file from CLI

### ISSUE THREAD

**Issue by ddollar** [weaveworks/eksctl#5021]
### What feature/behavior/change do you want?

The ability to create a full cluster config file from the CLI. One could specify a few `--options` and `--dumpconfig` and the entire state of the CLI's default configuration plus the options specified would be dumped to stdout.

`eksctl cluster create --name foo --region us-east-1 --dumpconfig > cluster.yaml`

### Why do you want this feature?

I have been fighting with one of these configs all day and it's not readily apparent how CLI config options map to config attributes.

**Comment by ddollar** [comment]
Nevermind, just found `--dry-run`

**Comment by aclevername** [comment]
@ddollar have you tried the dry-run feature? https://eksctl.io/usage/dry-run/
