### ISSUE TITLE
[Bug] Fix Slack notifications for releases

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#5027]
Failed run for [RC](https://github.com/weaveworks/eksctl/actions/runs/2064350007) :sob:

Related ticket: https://github.com/weaveworks/eksctl/issues/4944
Seems like the notifications added as part of this ticket aren't working as expected and are failing with the error 

```
Error: Error: An API error occurred: not_authed
Error: An API error occurred: not_authed
```

_Edit_: In addition, start publishing in `aws-dev` channel as well.

**Comment by Himangini** [comment]
We also stopped publishing success release messages on `aws-dev` channel which was missed in the related ticket. As part of this one we should add it back

**Comment by Skarlso** [comment]
The slack notification is working as it can be seen here: 
https://github.com/weaveworks/eksctl/runs/5767330437?check_suite_focus=true

It might have been some kind of fluke. The error suggests that the token wasn't sent along.
<img width="566" alt="Screenshot 2022-03-31 at 10 02 08" src="https://user-images.githubusercontent.com/182850/161007011-b962201a-4bdf-452c-95c1-8d904f4580c3.png">

I suggest closing this for now and then re-opening if it occurs again. I don't see any problems with the config or the setup. ¯\\\_(ツ)\_/¯.

**Comment by Himangini** [comment]
@Skarlso we need to add the notifications to `aws-dev` channel too. These need to work for releases so we need to make sure slack notifications are sent for releases, not just test runs.

**Comment by Skarlso** [comment]
>we need to add the notifications to aws-dev channel too.

This was an addition on the comments, not part of the original description. :)

>These need to work for releases so we need to make sure slack notifications are sent for releases, not just test runs.

It's practically irrelevant from where this has run because the configuration is the same. The point of the test was to see if the token is there or not and it's being used correctly which is what the test was for. 

In any case, I guess this needs to be edited to include sending notification on an additional channel, and once we do a release we'll be able to test this. Until then, this is blocked.

**Comment by Skarlso** [comment]
Huh, the action doesn't allow for a list of channel names... What a bummer.

**Comment by Skarlso** [comment]
For what it's worth, I opened: https://github.com/actions-ecosystem/action-slack-notifier/issues/334

And will be implementing it shortly. Let's hope it gets merged, otherwise, I will just duplicate the action for now ¯\\\_(ツ)\_/¯

**Comment by Himangini** [comment]
Another run for Release 0.90 [failed](https://github.com/weaveworks/eksctl/actions/runs/2076720034) with the same error
```
Error: Error: An API error occurred: not_authed
Error: An API error occurred: not_authed
```

**Comment by Skarlso** [comment]
The channel update is not yet done.
