### ISSUE TITLE
[Bug] "-o json" of "eksctl get iamidentitymapping" will return 2 lines of log to make json parser failed

### ISSUE THREAD

**Issue by charlie-fox** [weaveworks/eksctl#5038]
### What were you trying to accomplish?

```
eksctl get iamidentitymapping --cluster my-cluster-name -o json --region my-region
```

### What happened?

0.89.0

Besides the json response which is expected, it would also return 2 lines of log, for example:
```
2022-03-31 14:59:54 [ℹ]  eksctl version 0.89.0
2022-03-31 14:59:54 [ℹ]  using region us-west-2
```
Some tools is using the json output to parse aws_auth information, it would make them failed.

For example, in a very popular 3rd party eksclt terraform provider (https://github.com/mumoshu/terraform-provider-eksctl)

in this place, it would return

```
Error: creating cluster: can not get iamidentitymapping from eks cluster: parse iamidentitymapping : invalid character '-' after top-level value
```

### How to reproduce it?

Just run `eksctl get iamidentitymapping --cluster my-cluster-name -o json --region my-region`
you may find the extra 2 log lines in  output

**Logs**

```
2022-03-31 14:59:54 [ℹ]  eksctl version 0.89.0
2022-03-31 14:59:54 [ℹ]  using region us-west-2
[
   xxxx real json output 
]
```

**Anything else we need to know?**

Linux / MacOs

**Versions**

```
$ eksctl info
eksctl version: 0.89.0
kubectl version: v1.23.1
OS: darwin
```

**Comment by charlie-fox** [comment]
in 0.79.0, no such extra log line, will return pure json output

**Comment by cPu1** [comment]
Thanks for the detailed issue. I can confirm it's a regression and will break tools that parse the output. We're going to prioritize working on this issue.

**Comment by tanvp112** [comment]
You can use `-v 0` to suppress log output, example ` eksctl get iamidentitymapping --region <region> --cluster <cluster> -o json -v 0` will only print the json data.

**Comment by samroy92** [comment]
I have been having this same issue, I downgraded my eksctl version arbitrarily to 0.77.0 and it fixed this error for me. Versions 0.90,0.89, and 0.88 are all affected in my testing.

Here is the primary error:
`Error: reading cluster: reading aws-auth via eksctl get iamidentitymaping: can not get iamidentitymapping from eks cluster: parse iamidentitymapping : invalid character '-' after top-level value`

I am using MacOS with homebrew, to downgrade the version I found a previous commit of the brew formula and used this command (v0.77.0):
curl https://raw.githubusercontent.com/Homebrew/homebrew-core/19e81b3c456c0afb8abede830e38bad28be44b09/Formula/eksctl.rb > $(find $(brew --repository) -name eksctl.rb) && brew reinstall eksctl

This works as a workaround for the JSON parse issue. Related: https://github.com/mumoshu/terraform-provider-eksctl/issues/62

**Comment by Skarlso** [comment]
Huh, I thought we fixed this... 🤔

**Comment by charlie-fox** [comment]
Thanks team. 
Yes, `eksctl get iamidentitymapping --region <region> --cluster <cluster> -o json -v 0` can be workaround way, but for the scenario t use -o json, people usually expect a structured result and do parsing on it.   default  structured output is better

**Comment by cPu1** [comment]
> Huh, I thought we fixed this... thinking

It got introduced by https://github.com/weaveworks/eksctl/pull/4791 and we haven't fixed it since.

**Comment by cPu1** [comment]
> I have been having this same issue, I downgraded my eksctl version arbitrarily to 0.77.0 and it fixed this error for me. Versions 0.90,0.89, and 0.88 are all affected in my testing.
> 
> Here is the primary error: `Error: reading cluster: reading aws-auth via eksctl get iamidentitymaping: can not get iamidentitymapping from eks cluster: parse iamidentitymapping : invalid character '-' after top-level value`
> 
> I am using MacOS with homebrew, to downgrade the version I found a previous commit of the brew formula and used this command (v0.77.0): `curl https://raw.githubusercontent.com/Homebrew/homebrew-core/19e81b3c456c0afb8abede830e38bad28be44b09/Formula/eksctl.rb > $(find $(brew --repository) -name eksctl.rb) && brew reinstall eksctl`
> 
> This works as a workaround for the JSON parse issue. Related: [mumoshu/terraform-provider-eksctl#62](https://github.com/mumoshu/terraform-provider-eksctl/issues/62)

Thanks for the details. We are aware and have added this to our backlog. We will prioritise working on this issue.

**Comment by cPu1** [comment]
After looking into this more, eksctl's behaviour is correct here. Although the behaviour has changed a bit, the extra log lines are written to stderr, but the JSON-formatted output is still written to stdout. Any tool that parses output from a command should read that data from stdout. `terraform-provider-eksctl` is failing because it's trying to parse output collected from both stdout and stderr.

>Thanks team.
Yes, eksctl get iamidentitymapping --region <region> --cluster <cluster> -o json -v 0 can be workaround way, but for the scenario t use -o json, people usually expect a structured result and do parsing on it. default structured output is better

@charlie-fox, the output eksctl writes to stdout is still structured and most tools that read structured output only from stdout, like jq, will work with eksctl-piped output.

**Comment by charlie-fox** [comment]
well noted, thank you team!
