### ISSUE TITLE
eksctl does not support kubernetes version 1.22

### ISSUE THREAD

**Issue by Thomas999999** [weaveworks/eksctl#5063]
Dear Support,

since today AWS has released 1.22 kubernetes version for EKS, but latest version of eksctl does not support 1.22:

[ec2-user@ip-192-168-4-4 bin]$ cat eksctl_create.sh
eksctl create cluster --managed=false --name aws-d021970122 --region eu-west-1 --tags "instance_group_01=data_intelligence,pqp_testnumber=d021970122,shutdown_status=true,sec-by-def-network-exception=SSH" --**version 1.22** --nodegroup-name workers --node-type m4.4xlarge --nodes 4 --nodes-min 0 --nodes-max 10 --ssh-access --asg-access --node-volume-size 128 --node-volume-type gp2 --vpc-public-subnets subnet-0e27223f8babe99f4,subnet-056060693978732df --ssh-public-key SLV_keypair_IRE --node-ami-family AmazonLinux2 --auto-kubeconfig
[ec2-user@ip-192-168-4-4 bin]$ ./eksctl_create.sh
2022-04-05 07:30:05 [ℹ]  eksctl version 0.90.0
2022-04-05 07:30:05 [ℹ]  using region eu-west-1
**Error: invalid version, supported values: 1.18, 1.19, 1.20, 1.21**

When will 1.22 be supported?

Kind Regards,
Thomas

**Comment by Skarlso** [comment]
Hi. :) 

Follow the PR here :) https://github.com/weaveworks/eksctl/pull/4915

**Comment by aclevername** [comment]
Release is out :smile: https://github.com/weaveworks/eksctl/releases/tag/v0.92.0-rc.0

**Comment by Thomas999999** [comment]
I see only the prerelease and the normal download links does not provide v0.92.0:

[ec2-user@ip-192-168-14-227 ~]$ curl --silent --location https://github.com/weaveworks/eksctl/releases/download/v0.92.0/eksctl_Linux_amd64.tar.gz | tar xz -C /tmp

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

######

 curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp 

ends with v.091.0

how long does it take for normal release?

**Comment by Skarlso** [comment]
```
[ec2-user@ip-192-168-14-227 ~]$ curl --silent --location https://github.com/weaveworks/eksctl/releases/download/v0.92.0/eksctl_Linux_amd64.tar.gz | tar xz -C /tmp

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

If you remove `--silent` you will notice that, that link is actually incorrect. It's `https://github.com/weaveworks/eksctl/releases/download/0.92.0/eksctl_Linux_amd64.tar.gz`.

Notice that the version is not `v0.92.0` but `0.92.0`.

**Comment by Skarlso** [comment]
Right, so, how this works is that we promote an RC before we do a full release. Do get the RC download the following tag:

`https://github.com/weaveworks/eksctl/releases/download/v0.92.0-rc.0/eksctl_Linux_amd64.tar.gz`. This includes the support for 1.22. The next week will promote this RC to a full release if nothing breaking was detected during that time.
