### ISSUE TITLE
[Feature] Update ginkgo to v2

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#5077]
It's high time we update ginkgo

### What feature/behavior/change do you want?

I would like to be able to use the latest ginkgo version to run tests.

### Why do you want this feature?

Ginkgo has been updated to v2 ages ago. It's time we try to keep up. Also released some nice assertions and Expects.

**Comment by Himangini** [comment]
- We will need to make sure we aren't using any deprecated behavior.
- Might need to check gomega too
