### ISSUE TITLE
[Doc] Update the migration announcement to include private nodegroups 

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#5085]
It might not be perfectly clear that you need to private the api endpoint and the CA certificate if your nodegorup is private or can't join the cluster for some reason.

**Comment by cPu1** [comment]
To be more specific, for nodegroups that have no outbound internet access, you'll need to supply `--apiserver-endpoint` and `--b64-cluster-ca` to the bootstrap script. I have also left this a comment on the PR.

**Comment by Skarlso** [comment]
I think that's what I said, didn't I? :D
