### ISSUE TITLE
[Task] Replace usage of `context.TODO()` with an appropriate `Context` 

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#5093]
As part of the migration to aws-sdk-go-v2, it was decided to propagate `Context` from the top-level commands to all AWS API calls. To avoid scope creep, `context.TODO()` was used at the top-level and propagated to all AWS API calls. This issue is for revisiting usages of `context.TODO()` in all top-level commands and finding out an appropriate `Context` to use where possible. 

`create fargateprofile` (`pkg/fargate/create.go`) is one of the examples where the wait timeout for Fargate profile creation can be encapsulated in a timeout-based Context.

**Comment by Himangini** [comment]
@cPu1 to add some example places where we need to pass appropriate context instead of TODO
