### ISSUE TITLE
Error: loading config file "eksworkshop.yaml": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1alpha5.ClusterConfig[Help] 

### ISSUE THREAD

**Issue by surapurajureshmi** [weaveworks/eksctl#5097]

**Comment by surapurajureshmi** [comment]
Error: loading config file "eksworkshop.yaml": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1alpha5.ClusterConfig

**Comment by Skarlso** [comment]
hello. :))

Did something went wrong when filling out the ticket? I'm guessing you missed some details? :)

Please provide at least the config file you are trying to parse. :)

Thank you!

**Comment by Skarlso** [comment]
Hello,

This looks like was opened in error. :) I'm going to close for now, but please feel free to re-open if you happened to have more information on the issue. :) Thank you!
