### ISSUE TITLE
[Error: loading config file "eksworkshop.yaml": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1alpha5.ClusterConfigHelp] 

### ISSUE THREAD

**Issue by surapurajureshmi** [weaveworks/eksctl#5098]

**Comment by surapurajureshmi** [comment]
Error: loading config file "eksworkshop.yaml": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1alpha5.ClusterConfig

**Comment by surapurajureshmi** [comment]
Error: loading config file "eksworkshop.yaml": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1alpha5.ClusterConfig

**Comment by Skarlso** [comment]
Please try and submit a full ticket. :) I'm going to close this because it's borderline spamming now. :)
