### ISSUE TITLE
[Spike] Come up with a plan to track Karpenter version changes

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#5106]
### Description
Slack context [here](https://weaveworks.slack.com/archives/C01C7FH7EPQ/p1648633346041349)
We need to come up with a policy to track and keep up to date with the Karpenter version changes. Atm we have pinned the version to specific minor but there are issues from community for new versions

### Timebox
1-2 days

### Outcome
- Document the proposal for tracking karpenter version changes here on the ticket
- Get the plan agreed with the team + AWS

**Comment by Skarlso** [comment]
## Proposal

### Automation on `eksctl` side

We set up a pull model based on releases and check for released minor versions every day. If we find that a new minor version has been released compared to the previous version, we create an issue in `eksctl` to update the support. This ticket can be worked on by the team, checked if any code change is required, or just increased the supported minor version.

### Automation on `karpenter` side

Karpenter sets up a push model in their repository based on the release trigger and opens an issue in the eksctl repository if there is a minor version upgrade compared to the previous version. This is nice because we don't have to continuously pull every day to check if there is a new version available.

**Comment by josefaworks** [comment]
I'd prefer to automate it on the karpenter side if that's possible. I'll raise in the sync today and see if its possible from the karpenter side. If not, then from the eksctl side is a good back up option

**Comment by Skarlso** [comment]
Sounds good! Thanks Josefa!

**Comment by Himangini** [comment]
@akestner @matthewdepietro Let us know your thoughts on this proposal please 👍🏻
