### ISSUE TITLE
[Bug] Error: couldn't find private subnets: mapping doesn't have enough subnets...

### ISSUE THREAD

**Issue by wkhatch** [weaveworks/eksctl#5107]
Trying to spin up a cluster with two managed node groups; private and public, and keep hitting these errors. I'm using a manifest, and I've adjusted the availability zones several times, and nothing seems to get rid of this error. As a result, I end up with a cluster with everything but the two node groups. I'd like to understand what's going wrong, and more importantly, how to get past this. 

Here's the error:
`2022-04-12 01:00:25 [✖]  couldn't find private subnets: mapping doesn't have enough subnets: (allSubnets=v1alpha5.AZSubnetMapping{"us-east-1c":v1alpha5.AZSubnetSpec{ID:"subnet-03e5f8a23cef64d0a", AZ:"us-east-1c", CIDR:(*ipnet.IPNet)(0xc000e3db30)}, "us-east-1d":v1alpha5.AZSubnetSpec{ID:"subnet-0e71d7d267e8b985d", AZ:"us-east-1d", CIDR:(*ipnet.IPNet)(0xc000e3dbc0)}} AZs=[]string{"us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d", "us-east-1f"} subnets=[]string(nil))`

I'm in us-east-1, and have tried excluding 1e, as that always seems to cause a problem for some reason. Then dialed it back to just three, two; I don't know what else to do.

**Comment by Skarlso** [comment]
Hi!

Can you please share your config / command you are using? Thanks!

**Comment by wkhatch** [comment]
Gah, sorry. I guess it was later than I thought... 

`apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod-lora-cluster
  region: us-east-1

vpc:
  cidr: 10.4.0.0/16

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: s3-reader
        labels: { aws-usage: 'lora-apps-prod' }
      attachPolicyARNs:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: eks-image-builder
        namespace: kube-system
      wellKnownPolicies:
        imageBuilder: true
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        efsCSIController: true
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
    - metadata:
        name: external-dns
        namespace: kube-system
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: cert-manager
        namespace: cert-manager
      wellKnownPolicies:
        certManager: true
    - metadata:
        name: elb-manager
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
        labels: { aws-usage: 'cluster-ops' }
      wellKnownPolicies:
        autoScaler: true
    - metadata:
        name: autoscaler-service
        namespace: kube-system
      attachPolicy: # inline policy can be defined along with `attachPolicyARNs`
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'autoscaling:DescribeAutoScalingGroups'
              - 'autoscaling:DescribeAutoScalingInstances'
              - 'autoscaling:DescribeLaunchConfigurations'
              - 'autoscaling:DescribeTags'
              - 'autoscaling:SetDesiredCapacity'
              - 'autoscaling:TerminateInstanceInAutoScalingGroup'
              - 'ec2:DescribeLaunchTemplateVersions'
            Resource: '*'

managedNodeGroups:
  - name: iotr-nodes-prod-public
    instanceType: m5d.xlarge
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: 'true'
      k8s.io/cluster-autoscaler/prod-lora-cluster: 'owned'
    desiredCapacity: 2
    availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c']
    ssh:
      allow: true
      publicKeyName: iotr-eks
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        albingress: true
        cloudWatch: true
        externalDNS: true
        certManager: true
        efs: true
  - name: iotr-nodes-prod-private
    instanceType: m5d.xlarge
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: 'true'
      k8s.io/cluster-autoscaler/prod-lora-cluster: 'owned'
    desiredCapacity: 3
    privateNetworking: true
    availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c']
    ssh:
      allow: true
      publicKeyName: iotr-eks
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        albingress: true
        cloudWatch: true
        externalDNS: true
        certManager: true
        efs: true

addons:
  - name: vpc-cni # no version is specified so it deploys the default version
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest # auto discovers the latest available
  - name: kube-proxy
    version: latest

availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c']
`

**Comment by Skarlso** [comment]
Interesting. You appear to have more AZs than subnets. That's why you are getting this error. It looks like you defined the AZs, yet `eksctl` somehow added a couple more? I can see that the AZ list is:

```
"us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d", "us-east-1f"
```

But you defined it to be:

```yaml
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c']
```

So, where the heck did the rest come from? :D There is something funky happening here. :)

**Comment by wkhatch** [comment]
removing the availabilityZones attribute in each of the managedNodeGroups, and then specifying the top level availabilityZones with: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d', 'us-east-1f'] results in this:

```
2022-04-12 14:53:20 [✖]  AWS::EC2::InternetGateway/InternetGateway: CREATE_FAILED – "Resource creation cancelled"
2022-04-12 14:53:20 [✖]  AWS::EC2::NatGateway/NATGateway: CREATE_FAILED – "Resource creation cancelled"
2022-04-12 14:53:20 [✖]  AWS::EKS::Cluster/ControlPlane: CREATE_FAILED – "Resource handler returned message: \"Cannot create cluster 'prod-lora-cluster' because us-east-1e, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f (Service: Eks, Status Code: 400, Request ID: 78a217a0-28ad-494f-9c9a-8034d6da4422)\" (RequestToken: 6ed503cd-3232-1b3d-fb45-c77baaee8a91, HandlerErrorCode: InvalidRequest)"
```

Why would it select the one excluded availabilityZone, us-east-1e as the target in this case? I'm thinking at this point I should just build this out by hand and bail on eksctl, even though that means a lot more work for setting up the add ons and policies. Or, maybe create the node groups using kubectl? I'll try a few more things, and if nobody can suggest a way to make this work, revert to that as a last resort.

**Comment by Skarlso** [comment]
There is definitely something funky going on which is worth investing. For now, because of low capacity and holidays coming up, you'll probably have to wait a bit until we have the capacity to deal with things. Please bare with me while I try to figure out what's wrong.

In the meantime, would you mind trying this pr https://github.com/weaveworks/eksctl/issues/5110?

I doubt it's related... But you never know.

This specifically only selects availability zone type zones. Although it looks from the logs like that's not your problem here.

**Comment by Skarlso** [comment]
Also, did you change in the above example the node group azs as well?

Also, would you mind testing in us-west-2 as well please?

**Comment by Skarlso** [comment]
BTW... which version of `eksctl` are you using? A few months ago we had a problem with selecting azs which was fixed later on.
