### ISSUE TITLE
[Help] Is there a way to encrypt the log groups created by eksctl

### ISSUE THREAD

**Issue by steffakasid** [weaveworks/eksctl#5111]
We use `cloudWatch.clusterLogging.enableTypes` to configure the logging to cloudwatch. Unfortunately the loggroups aren't encrypted via KMS. Is there a way to do this with eksctl or would this be a feature request?

**Comment by cPu1** [comment]
Encrypting the log groups in CloudWatch Logs is not supported in eksctl. The CloudWatch Logs log groups for logs sent by the control plane are created by EKS itself and the API offers no control over the KMS settings for the created log groups. eksctl can consider associating a KMS key with the log groups after they're created by EKS, but there's no correct timing to do this and the log group will always end up with some unencrypted logs.

**Comment by steffakasid** [comment]
Ok understood. Thanks for your reply.
