### ISSUE TITLE
[Bug] Authenticator update breaks mod changes

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#5140]
https://github.com/weaveworks/eksctl/pull/5105

aws-iam-authenticator updated their version of client-go. Helm did the same to later version. These collide and aren't compatible in other parts.

Pinning the version isn't working because helm needs a higher version and the higher version has breaking changes compared to the lower version that authenticator needs.

We'll have to either wait and hope that authenticator catches up, or we can remove authenticator and put it into tools only so it doesn't clutter the mod file.

We remove the need for authenticator code once we switched over to use a different method to generate tokens.

**Comment by Skarlso** [comment]
Eventually, we'll have to do something about this. But for now, we have to keep authenticator at 0.5.5 otherwise, things start to break. :/

**Comment by Skarlso** [comment]
Ok, I think I figured out how to do this. Actually, since we no longer use aws-iam-authenticator in the code ( thank all the Gods for that ) we are going to install it in a different way. So we no longer have to have it in our code. :)

**Comment by Skarlso** [comment]
I know we use the tools approach for this one, but honestly, it's not working out.

**Comment by Skarlso** [comment]
Actually! Even better. We already install it using curl anyways. :D

**Comment by Himangini** [comment]
Closing this since related PR is merged
