### ISSUE TITLE
I am not able to install Brew properly on Amazon linux Centos any help?

### ISSUE THREAD

**Issue by maheshdivan** [weaveworks/eksctl#516]
Please [search existing issues (open & closed)](https://github.com/weaveworks/eksctl/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if there is a similar one. If there is, add comments or vote where appropriate.

If you did not find a similar issue or if it did not help then ask for help in our [slack channel](https://weave-community.slack.com/messages/eksctl/)

**What help do you need?**
Describe the type of help you need

**Comment by errordeveloper** [comment]
Hi, are you trying to use Homebrew on Linux? That's not currently supported, you should use one of the Linux binaries that we provide. We also have #215 for tracking status of native Linux packages.
