### ISSUE TITLE
kubectl logs -f gets "Authorization error"

### ISSUE THREAD

**Issue by khteh** [weaveworks/eksctl#519]
Please [search existing issues (open & closed)](https://github.com/weaveworks/eksctl/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if there is a similar one. If there is, add comments or vote where appropriate.

If you did not find a similar issue or if it did not help then ask for help in our [slack channel](https://weave-community.slack.com/messages/eksctl/)

**What help do you need?**
Describe the type of help you need
I recently created a cluster on EKS with eksctl. kubectl logs -f mypod-0 bumps into Authorization error:

```
Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)
```
Any advice and insight is appreciated

**Comment by errordeveloper** [comment]
Does `kubectl get pods` work?

**Comment by errordeveloper** [comment]
Closing due to the lack of context.

**Comment by anil4u-04** [comment]
Hi we are facing this issue, and yes `kubectl get pods` works. Can someone please help on this. Thanks

**Comment by fredalbino** [comment]
also facing this issue. can we get some clarification on this please? Thanks!

**Comment by anil4u-04** [comment]
Sorry for the late update, I was facing the issue because of there was some issue in the was-auth configmap , after it is rectified the issue got solved. 

it may help someone to check.
