### ISSUE TITLE
Avoid writing ClusterConfig to temp files in integration tests

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#5202]
Some of the integration tests write the ClusterConfig to temp files and pass them to eksctl via `--config-file`.This is not required as eksctl accepts ClusterConfig from standard input by specifying `--config-file=-`. The goal of this issue is to find integration tests that write ClusterConfig to temp files before passing them to eksctl command invocations, and change them to supply ClusterConfig to eksctl as a stream of bytes via stdin.

**Comment by Skarlso** [comment]
For however picks this up, please do it after https://github.com/weaveworks/eksctl/issues/5099 to avoid conflicts. :)
