### ISSUE TITLE
[Task] Stop using `s` as an indicator that we are returning a list

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#5219]
For example:

```go
	DescribeNodeGroupStack(ctx context.Context, nodeGroupName string) (*Stack, error)
	DescribeNodeGroupStacks(ctx context.Context) ([]*Stack, error)
```

This is super annoying and actually caused a bug to happen: https://github.com/weaveworks/eksctl/issues/5217

It's because our unit tests were mocking the wrong function since the author missed the `s`:

```go
fakeStackManager.DescribeNodeGroupStackReturns(nil, fmt.Errorf("error describing cloudformation stack"))
```

This should have been

```
fakeStackManager.DescribeNodeGroupStacksReturns(nil, fmt.Errorf("error describing cloudformation stack"))
```

It would have been more visible if the extension would say `List` instead of an additional `s`.

The test is passing because the mock was happily providing a canned `nil, nil` as a return.

This also suggests that we should more often verify if the mock was called with the right parameters.

**Comment by CrisNevares** [comment]
@Skarlso fyi -- I just created issue #5544 that sounds like it might be related to this (sorta similar behavior to #5217)
