### ISSUE TITLE
`update nodegroup` does not wait for the update operation to complete

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#5250]
`eksctl update nodegroup` allows updating the nodegroup config for managed nodegroups but it does not wait for the operation to complete, nor does it support the `wait` flag. Most commands in eksctl support the `wait` flag for operations that can take some time to complete and some also have it enabled by default.

**Comment by nikimanoledaki** [comment]
WDYT about making `--wait` a `General` flag and make sure it's added to all commands? I have a feeling it's probably not just `update nodegroup`. :)

**Comment by chrisjohnson00** [comment]
@nikimanoledaki  or @Skarlso would this by chance have any impact on https://github.com/weaveworks/eksctl/issues/384?  I've noticed Issue 384 happens around the default 25 min timeout.

**Comment by cPu1** [comment]
> @nikimanoledaki or @Skarlso would this by chance have any impact on #384? I've noticed Issue 384 happens around the default 25 min timeout.

This does not affect `create nodegroup`. I have responded to your comment in that issue: https://github.com/weaveworks/eksctl/issues/384#issuecomment-1161419197
