### ISSUE TITLE
[Bug] `eksctl utils write-config` breaks in `kubectl` 1.24 when `aws-iam-authenticator` absent

### ISSUE THREAD

**Issue by jglick** [weaveworks/eksctl#5257]
See https://github.com/weaveworks/eksctl/issues/5240#issuecomment-1126344991 & https://github.com/aws/aws-cli/issues/6920 for context. As recommended in https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html I am not running `aws-iam-authenticator`. Evidently https://github.com/weaveworks/eksctl/blob/637d454ef59305b4af6633ff939674eff1f408c2/pkg/utils/kubeconfig/kubeconfig.go#L161-L166 should be extended to https://github.com/weaveworks/eksctl/blob/637d454ef59305b4af6633ff939674eff1f408c2/pkg/utils/kubeconfig/kubeconfig.go#L185 https://github.com/weaveworks/eksctl/blob/637d454ef59305b4af6633ff939674eff1f408c2/pkg/utils/kubeconfig/kubeconfig.go#L32-L36

### What were you trying to accomplish?

Use `eksctl utils write-config` (or actually just use the config generated by `eksctl create cluster`).

### What happened?

Config is written, but then `kubectl` operations fail with

```
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

### How to reproduce it?

**Versions**

```console
$ eksctl info
eksctl version: 0.97.0
kubectl version: v4.5.4
OS: linux
$ which aws-iam-authenticator
$ aws --version
aws-cli/2.6.4 Python/3.9.11 Linux/5.13.0-40-generic exe/x86_64.ubuntu.21 prompt/off
$ kubectl version --client
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-04T02:28:17Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
```

**Comment by gohmc** [comment]
Change from `client.authentication.k8s.io/v1alpha1` to `client.authentication.k8s.io/v1beta1` should work.
