### ISSUE TITLE
[Bug] Need to update/upgrade/re-install  eksctl binary in order to create EKS cluster with latest version of k8s

### ISSUE THREAD

**Issue by goswamig** [weaveworks/eksctl#5275]
### What were you trying to accomplish?
I was trying to launch EKS cluster with k8s version 1.20 but my eksctl command
```
Error: invalid version, supported values: 1.15, 1.16, 1.17, 1.18, 1.19, 1.20
```
even though EKS supports 
1.22.6  1.21.9  1.20.15.  1.19.16
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

https://github.com/weaveworks/eksctl/blob/9cb6f07748cd378317a8707f6fbf49395fac9b38/pkg/apis/eksctl.io/v1alpha5/types.go#L476

### What happened?
Cluster creation failed 

### How to reproduce it?
Run eksctl create command with old binary of eksctl 

### Expected behaviour. 
Instead of forcing user to update the eksctl binary, eksctl [code](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) should retrieve the latest version of support k8s in EKS and create cluster accordingly. 

this will delight user and user might not have to update the eksctl binary evertime.

**Comment by Skarlso** [comment]
Thank you for your issue!

The reason we do this and not automatically set supported versions is that things can change from version to version. And sometimes we do extra stuff based on what version we have or what version is the default. We also gradually stop supporting some versions that might still be listed and could create an invalid cluster.

I hope this clarifies things. :)
