### ISSUE TITLE
[Bug] propagateASGTags causing failed nodegroups

### ISSUE THREAD

**Issue by corinz** [weaveworks/eksctl#5285]
Hello, I am executing a cluster creation with the new `propagateASGTags` option. I am running eksctl v0.97.0 and my cluster.yaml config looks like this:

``` yaml
  - name: Airflow-Tasks-NodeGroup
    tags:
      Name: EKS Managed Airflow Tasks
      Datadog Monitoring: "true"
    propagateASGTags: true
    spot: true
    instanceTypes: ["m4.xlarge","m5.xlarge","m5d.xlarge","m5a.xlarge","m5n.xlarge"]
    amiFamily: AmazonLinux2
    privateNetworking: true
    desiredCapacity: 0
    minSize: 0
    maxSize: 3
    volumeSize: 80
    labels:
      mycluster.airflow: "true"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
    taints:
      - key: airflow
        value: "true"
        effect: NoSchedule
```

This is the error I receive from failed node group cloud formation stacks. After executing several times with the same failure, and then removing the option, I had a successful execution. 

I am assuming that there is a bit of misunderstanding as to the full functionality of `propagateASGTags` on my behalf with potential improvements or a bug. 

### What happened?
When implementing `propagateASGTags` cluster creation fails.

**Logs**
```
2022-05-17 20:47:35 [ℹ]  daemonset "kube-system/aws-node" restarted
2022-05-17 20:47:35 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2022-05-17 20:47:35 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=my-cluster'
2022-05-17 20:47:35 [✖]  couldn't get managed nodegroup details for nodegroup "Airflow-Tasks-NodeGroup": ResourceNotFoundException: No node group found for name: Airflow-Tasks-NodeGroup.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "9b0f71be-f983-460c-8020-b787d33c6668"
  },
  ClusterName: "my-cluster",
  Message_: "No node group found for name: Airflow-Tasks-NodeGroup.",
  NodegroupName: "Airflow-Tasks-NodeGroup"
}
```

### How to reproduce it?
1. Use the managed nodegroup settings above2. 
2. `eksctl create cluster -f cluster.yaml --kubeconfig ./kubeconfig`

**Anything else we need to know?**
Running on a mac. Just ran a `brew upgrade eksctl` to version v0.97.0

**Versions**
```
$ eksctl info
eksctl version: 0.97.0
kubectl version: v1.23.4
OS: darwin
```
Thank you in advance!

**Comment by Skarlso** [comment]
Hello.

Could you show me the full output of the logs please?

I'm interested to see if the task was scheduled to run in parallel or not. It might have happened before the nodegroup was created.

**Comment by cPu1** [comment]
Thanks for the detailed issue. This is a bug with the task creation code in eksctl, it does not wait for the nodegroup creation to complete before propagating tags to the ASG. We'll look into it.

**Comment by Skarlso** [comment]
@corinz Hi. Please try this release https://github.com/weaveworks/eksctl/releases/tag/v0.99.0-rc.0. This is the one containing this fix. Thanks.
