### ISSUE TITLE
[Feature] Cloudformation template export

### ISSUE THREAD

**Issue by corinz** [weaveworks/eksctl#5291]
### What feature/behavior/change do you want?
The ability to dump the cloudformation template with the CLI without creating the cluster. This was already requested in issue #956.
`eksctl create cluster -f cluster.yaml --output-template > cloudformation.json`
or using some combination of `--dry-run` and other flag

### Why do you want this feature?
I want to make modifications to the eks cluster and vpc after they have been deployed. The changes will add logging and monitoring. I am doing this is another IaC program, and it creates a condition where I need to order my deletion and creation of resources. Vertical integration of eks resources and dependencies is what I'm shooting for. If I can export the CF template, I can make changes to it, and add dependent templates.

Exporting the template has the most flexibility for users but adding child/dependent stacks to the eksctl cluster creation so that I can run some compliance/security configs, would also solve this dilemma. 

Also, this feature would allow me to version control my cloudformation template, that way I am not dependent on eksctl API/spec. If so, git diff could be reflected on at the cloudformation resource level instead of at the eksctl config level. Let me know your thoughts!

**Comment by Skarlso** [comment]
Hi. So, for the record, eksctl doesn't JUST use cloudformation. It also creates some additional things such as addons, and IAM roles and endpoint configurations, etc. These all would not be in the template but the reference to them probably would be or would depend on them.

Meaning the generated template on its own, would probably be useless / wouldn't work at all, or in worst case, it would work, but would result in a broken cluster.

**Comment by corinz** [comment]
@Skarlso Thanks for the quick reply. I see. What else is eksctl using, for the examples you named?

**Comment by Skarlso** [comment]
For example, iam roles and service accounts are created with a different stack. Nodegroups are created with a different stack. Anything basically outside of the control plane is either a different stack or an API call.
