### ISSUE TITLE
[Help] How do I specify `hugepages-2Mi` when creating a nodegroup?

### ISSUE THREAD

**Issue by neowulf** [weaveworks/eksctl#5300]
### What help do you need?

I'd like to create a nodegroup which has `hugepages-2Mi` enabled. On the pod itself, I see the following:
```
$ grep Hugepagesize /proc/meminfo
Hugepagesize:     2048 kB
```

However, on the node details, I see `hugepages-2Mi` to be `0`.

https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/

**Comment by Skarlso** [comment]
Hi!

You could try defining kubelet extra config. https://eksctl.io/usage/customizing-the-kubelet/#customizing-kubelet-configuration_1
