### ISSUE TITLE
[Spike] Increase the coverage of cluster create 

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#5315]
### Description

https://github.com/weaveworks/eksctl/issues/5015 started with refactors and adding a happy path scenario to cluster create as a unit test.

Now it's time to increase that coverage by adding error cases, Karpenter install, nodegroups, etc.

This spike is to come up with a list/plan of places to improve the code coverage for create cluster command. We need to find our what areas are lacking tests and how complicated these areas are to be able to write tests for

### Timebox
2-3 days

### Outcome
List of areas for create cluster command to add/improve test coverage and complexity estimations of these areas
Document the outcome here

**Comment by Himangini** [comment]
Closing this off since we have added tickets for this
