### ISSUE TITLE
[Task] Automate release process and remove redundant manual steps

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#5317]
Today, upon triggering the release and release candidate workflows, the workflow creates a commit after updating the pre-release ID and opens a PR against the release branch with the `/trigger-release` label. This PR needs to be manually merged to trigger the actual release.

The additional steps of creating, approving and merging the release PR are not required. Instead, the release workflows can push the tag directly after supplying the release version to eksctl as a linker flag, triggering the actual release workflow.

**Comment by Himangini** [comment]
PS this will also involve updating the handbook for the release steps.
