### ISSUE TITLE
 parsing kubectl version string  (upstream error: error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by SaadAlajlan** [weaveworks/eksctl#5318]
I tried eksctl create cluster --name hello --region=us-west-2 and got this error.

![image](https://user-images.githubusercontent.com/38673587/170250670-446c31ed-d1df-4bd2-9da5-5513a228f4f7.png)

**Comment by Skarlso** [comment]
Hello, there are already some things that are fix and one pending which also fixes this.
https://github.com/weaveworks/eksctl/pull/5288
https://github.com/weaveworks/eksctl/pull/5287

Please try main or please wait for another release.

**Comment by Himangini** [comment]
@SaadAlajlan are you still experiencing this issue with the latest release or can this be closed off now?

**Comment by SaadAlajlan** [comment]
The last try was today 12:50AM 
![Screenshot 2022-05-31 190856](https://user-images.githubusercontent.com/38673587/171221107-0297c02a-e61c-4fae-9778-558b96b0a0ee.jpg)
![Screenshot 2022-05-31 190949](https://user-images.githubusercontent.com/38673587/171221161-7ace48c4-9c3f-4ab3-aa3c-da97d57df926.jpg)
![Screenshot 2022-05-31 191049](https://user-images.githubusercontent.com/38673587/171221195-9071d53f-f093-4dd1-b9d6-abf330cbdfd9.jpg)

**Comment by Himangini** [comment]
We have released [v0.100.0](https://github.com/weaveworks/eksctl/releases/tag/v0.100.0) should fix this issue.

**Comment by nevotheless** [comment]
I also have this issue with version `0.107.0-dev+b204c3ce.2022-07-29T12:46:37Z`.
