### ISSUE TITLE
[Feature] Add P4de.24xlarge to the list of supported instances when setting efaEnabled: true

### ISSUE THREAD

**Issue by amrragab8080** [weaveworks/eksctl#5329]
We just announced P4de instances and we need eksctl workflow when setting efaEnabled: true to support p4de.24xlarge in the EFA plugin and to install the nvidia daemonset. 
https://github.com/weaveworks/eksctl/blob/8ab886b8752038a3ee521aa30dc356468211c6f0/pkg/addons/assets/efa-device-plugin.yaml#L41-L70

https://aws.amazon.com/about-aws/whats-new/2022/05/amazon-ec2-p4de-gpu-instances-ml-training-hpc/

**Comment by nikimanoledaki** [comment]
Thank you for flagging this, this should be prioritised from our side.

**Comment by cPu1** [comment]
@amrragab8080, we have opened a [PR](https://github.com/weaveworks/eksctl/pull/5330) to add p4de instance types to the EFA plugin. We're also waiting on https://github.com/weaveworks/eksctl/pull/5274#issuecomment-1137099803 to add more EFA instance types to the list.
