### ISSUE TITLE
[Bug] Updating aws-node with utils installs not the recommended version

### ISSUE THREAD

**Issue by steveizzle** [weaveworks/eksctl#5336]
### What were you trying to accomplish?

Updating aws-node to the newest recommended version with the use of `eksctl utils update-aws-node `

### What happened?

Version v1.9.3 gets installed, instead of the recommended version 1.11.0 (https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-add-on)

When manually fixing the image i ran into another problem which seems to be related to the missing new env variables ENABLE_IPv6 and ENABLE_IPv4 which were introduced in the newer versions of aws-node (https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.10/config/master/aws-k8s-cni.yaml). In the reference manifest IPv4 is enabled by default. It seems like both parameters have to be set explicitly.

IPv4 as default would be fine for me, but it seems there is more logic needed if that should be configurable.

### How to reproduce it?

`eksctl utils update-aws-node `

**Logs**

Updating the Image without the new env variables:
```
{"level":"error","ts":"2022-05-27T14:04:19.289Z","caller":"ipamd/ipamd.go:406","msg":"IPv4 and IPv6 are both disabled. One of them have to be enabled"}
```

**Anything else we need to know?**

least available eksctl on mac

**Versions**
```
$ eksctl info
eksctl version: 0.83.0
kubectl version: v1.23.2
OS: darwin
```

**Comment by Skarlso** [comment]
Hi!

aws-node version is backed into eskctl here: https://github.com/weaveworks/eksctl/blob/main/pkg/addons/default/assets/aws-node.yaml

We can try and update it. Usually, we don't out of compatibility reasons. Or because it breaks something.

**Comment by Skarlso** [comment]
Yeah. :/ That is problematic indeed.
