### ISSUE TITLE
[Feature] Quality of life improvments for new users applying taints

### ISSUE THREAD

**Issue by pptb-aws** [weaveworks/eksctl#5338]
### What feature/behavior/change do you want?

First, have the error message when the effect of a taint is not valid, print out the valid list of taint options.

Current error message:
```
Error: couldn't create cluster provider from options: invalid taint effect: NO_SCHEDULE, unsupported taint effect
```

Purposed error message:
```
Error: couldn't create cluster provider from options: invalid taint effect: NO_SCHEDULE, unsupported taint effect. Valid taint effects are: NoSchedule, NoExecute, and PreferNoSchedule
```

Second, it would be beneficial if eksctl documentation noted that it is case sensitive.  If possible, having eksctl check for erroneous capitalization, such as writing Taints instead of taints, would be helpful to new users as eksctl still runs with no warning if Taints is used, but it will not read the section.

Finally, adding a specific section for the use of taints to the [documenation](https://eksctl.io/usage/managing-nodegroups/) would also be beneficial to new users.  Additionally, another copy of [this example](https://github.com/weaveworks/eksctl/blob/main/examples/05-advanced-nodegroups.yaml) paired down and specifically labeled as something like nodegroup-with-taints, would be helpful for new users finding an example of applying taints.

### Why do you want this feature?

I had significant issues when attempting to apply taint to a managed nodegroup using eksctl due to a lack of clear documentation regarding how to apply this, and specific around the values that are allowed in the taint effect section.  The purpose of this request is to provide a clearer error message and some additional documentation around this feature.

**Comment by cPu1** [comment]
eksctl assumes the user has some knowledge of Kubernetes. The list of supported taints is exactly the same as the Kubernetes API server accepts (and kubectl). 

> First, have the error message when the effect of a taint is not valid, print out the valid list of taint options.

Good suggestion, we do this for some other fields that take an enumeration.

> Second, it would be beneficial if eksctl documentation noted that it is case sensitive. 

Almost all field names and values are case-sensitive in eksctl as eksctl uses the same Kubernetes-style object naming conventions. 

> If possible, having eksctl check for erroneous capitalization, such as writing Taints instead of taints

This is a little out of scope for eksctl but we do provide the [ClusterConfig schema](https://eksctl.io/usage/schema/). 

> Additionally, another copy of [this example](https://github.com/weaveworks/eksctl/blob/main/examples/05-advanced-nodegroups.yaml) paired down and specifically labeled as something like nodegroup-with-taints

Noted, we'll add this and the other suggestion to our backlog.
