### ISSUE TITLE
[Feature] Config Schema needs to honor all command flags

### ISSUE THREAD

**Issue by awsjake** [weaveworks/eksctl#5358]
### What feature/behavior/change do you want?

Include command line flags into config schema parameters.
Example, there is not a parameter for disabling the kube-config update.
`--write-kubeconfig=false`

### Why do you want this feature?

Several AWS accounts do not have internet access.  Using `eksctl apply -f filename.yaml` does not allow the passing of additional arguments or flags when using a config file.  Some AWS customers are running their `kubectl` and `eksctl` tools from instances within the VPC and within the same subnets where EKS is running, so they also do not have internet access.   

These tools reach out to run `aws eks` commands to update the kube-config.  There is not a PrivateLink/VPC Endpoint for this API, which makes `eksctl` fail to complete successfully.

**Comment by Skarlso** [comment]
Hey. Thanks for the issue. I think it's a reasonable request. Will discuss with the team.

**Comment by Skarlso** [comment]
Hello @awsjake. 

So, this is actually working: `eksctl create clsuter -f cluster-config.yaml --write-kubeconfig=false`. 

Did you try a different command? `eksctl apply` is not a thing. :)

**Comment by awsjake** [comment]
I mistyped.  I did intend to write `eksctl create cluster -f`.
Can you share what version of eksctl this works with?  I am running v0.82.0.

**Comment by Skarlso** [comment]
It's working on the latest which is 0.100.0. But I expect it to work on other versions as well. 🤔 in any case, latest worked.
