### ISSUE TITLE
clean nodegroup deletion

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#536]
As mentioned earlier in  https://github.com/weaveworks/eksctl/pull/523#issuecomment-461623452, we need to devise a better strategy for nodegroup deletion, which should also help us with #103 and #274 (as well as other related issues).

So we should try implementing the following strategy:

* for all nodegroups
  * taint the node and drain pods
* delete all daemonsets
* for all nodegroups
  * scale nodes to zero
  * delete dangling ENIs
  * look for ELBs, ALBs and EBS volumes and delete those
    * also ALBs created through `Ingress`
* delete each nodegroup stack
* delete cluster stack

We may do something different for deleting individual nodegroups, e.g. only scale drain, taint and down, but we do need to implement this first, as deletion is an important aspect of user experience.

related: #2278, #2172

**Comment by errordeveloper** [comment]
Maybe related to https://github.com/aws/amazon-vpc-cni-k8s/issues/69.

**Comment by errordeveloper** [comment]
Fixing this would pave the road towards fixing other issue with deletions.

**Comment by gemagomez** [comment]
@2opremio is this finished?

**Comment by 2opremio** [comment]
Nope, I fixed #103 in a different way and haven't tackled #274 yet for which we may follow a different approach.

**Comment by programmer04** [comment]
The deletion of entries in DNS (automatically with cluster) created by [ExternalDNS](https://github.com/kubernetes-sigs/external-dns) (deployed in a specific cluster) would be useful too.

Probably `eksctl` would be able to clean only entries created in [Route 53](https://aws.amazon.com/route53/). Every entry in [Route 53](https://aws.amazon.com/route53/) created automatically by Kubernetes with [ExternalDNS](https://github.com/kubernetes-sigs/external-dns) has some metadata in `TXT` record which gives the possibility of tracking e.g.
```
"heritage=external-dns,external-dns/owner=test-cluster,external-dns/resource=ingress/default/app-ingress"
```

Probably the simplest solution is to remove with the cluster all entries from [Route 53](https://aws.amazon.com/route53/) which match below condition
```
heritage == external-dns && external-dns/owner == NAME_OF_DELETED_CLUSTER
```


Behaviour for `eksctl 0.23.0` with [ExternalDNS](https://github.com/kubernetes-sigs/external-dns):
- `AWS ALB` created by [AWS ALB Ingress Controller](https://github.com/kubernetes-sigs/aws-alb-ingress-controller) and populated DNS entries are not deleted (entire cluster deletion fails)
- `AWS ELB` created by applying `kind: Service` with `spec.type: LoadBalancer` is deleted, but entries populated in [Route 53](https://aws.amazon.com/route53/) stays (entire cluster reports to be successfully deleted)

Do you have any plan how to approach these issues? I'll be happy to help 😃

**Comment by nikimanoledaki** [comment]
What was left to do was draining the nodegroups and deleting the daemonsets. This was addressed so this issue can be closed now.
