### ISSUE TITLE
[Task] remove usages of aws-sdk-go v1 where possible

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#5364]
We still have a couple of places where we use sdk v1 but don't have to. Places where `aws.String` is used for example. We should clean those up.

### Scope update

In this particular issue we will remove as much of the clutter as possible, replacing sdk v1 dependencies in places where it is relatively easy to do so and where the code between v1 and v2 hasn't suffered major refactorings. We'll also remove dependencies that are redundant or no longer used. See the commits in [this PR](https://github.com/weaveworks/eksctl/pull/5753/commits) as reference.

**Comment by johnwesley** [comment]
Is this a `good first issue` candidate?

**Comment by Skarlso** [comment]
@johnwesley Yes! :) Feel free to pick it up. Please note though that there are some places where it's a bit wonky. For example, when we create sessions. It might work though. :D Not sure. :) But most places can easily be just replaced.

**Comment by johnwesley** [comment]
@Skarlso would you please label https://github.com/weaveworks/eksctl/pull/5400 a WIP?

**Comment by Skarlso** [comment]
@johnwesley Hello. We don't have a WIP label. :) You can just say in the title `[WIP]` or create a Draft PR. :) That will be fine. :)

**Comment by TiberiuGC** [comment]
There's plenty examples where migrating from `v1` to `v2` is not as trivial as merely updating the dependencies (e.g. modules like `client` , `session` , `credentials` , `endpoints` , `request`, etc.). Some code has been considerably refactored between `v1` and `v2`, so it needs careful consideration. 

Although it may not cover all the mentioned modules/dependencies, a guide on migration can be found [here](https://aws.github.io/aws-sdk-go-v2/docs/migrating/).

**Comment by TiberiuGC** [comment]
@johnwesley - as I was digging through all dependencies I opened [this PR](https://github.com/weaveworks/eksctl/pull/5753) to remove a bunch of clutter. I will update the scope of this ticket and close it once I get this PR merged.

Afterwards, I will try to split the remaining work in individual tickets. I've already [created one](https://github.com/weaveworks/eksctl/issues/5765) that targets the `session` package. Feel free to pick it up if you'd like to!
