### ISSUE TITLE
Instances created flagged by AWS Security Hub as not using Instance Metadata Service Version 2 (IMDSv2)

### ISSUE THREAD

**Issue by devops-cafex** [weaveworks/eksctl#5366]
[AWS Security Hub](https://aws.amazon.com/security-hub/) Flags a high Severity issue for instances created for EKS nodegroups 

```
This control checks whether your Amazon Elastic Compute Cloud (Amazon EC2) instance metadata version is configured with Instance Metadata Service Version 2 (IMDSv2). The control passes if HttpTokens is set to required for IMDSv2. The control fails if HttpTokens is set to optional.
```

They provide the following to remediate

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-8-remediation

**Comment by Skarlso** [comment]
Thank you for bringing this to our attention. We will look into it!

**Comment by Skarlso** [comment]
@devops-cafex 
You can use the following setting to disable v1:

```yaml
    # forces the use of IMDSv2 tokens
    disableIMDSv1: true
```

when creating new nodegroups. Please be advised that this does not work for existing nodegroups. You have to create new ones.

**Comment by devops-cafex** [comment]
Perfect, thank you 👍
