### ISSUE TITLE
[Feature] EFA managed nodegroup to use existing security group

### ISSUE THREAD

**Issue by nayanen** [weaveworks/eksctl#5382]
### What feature/behavior/change do you want?

Make use of existing security group while creating managed nodegroups and efaEnabled is set to TRUE. 

### Why do you want this feature?

The Key requirements for EFA networking are creating the EFA specific security groups and placements groups as well launching the nodegroup in a single Available Zone. While creating the managed nodegroups efaEnabled it does create a new security group and does not provide option to use an existing security group.

**Comment by cPu1** [comment]
There's `nodeGroup.securityGroups.attachIDs` that lets you specify existing security groups for your nodegroups. Does that work for your use case or do you not want the security group rules added by eksctl when EFA is enabled?

**Comment by nayanen** [comment]
Yes , would like to add the security group rules while adding by eksctl when EFA is enabled?
