### ISSUE TITLE
[Bug] RBAC Permissions for Persistent Volume Claims

### ISSUE THREAD

**Issue by Gaby-Soto** [weaveworks/eksctl#5397]
### What were you trying to accomplish?

In Spark 3.1, we can mount a dynamically-created persistent volume claim per executor by using OnDemand as a claim name and storageClass and sizeLimit options using:
```
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.claimName=OnDemand
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.storageClass=gp
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.sizeLimit=499Gi
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.mount.path=/data
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.mount.readOnly=false
```

### What happened?

When EBS is dynamically mounted to the executors with EMR on EKS, it fails.
Error message as follows: 
```
Forbidden! Configured service account doesn't have access. Service account may have been revoked. persistentvolumeclaims is forbidden. User "system:serviceaccount:emr:emr-containers-sa-spark-client-XXXXXXXXXX-xxxxxxx" cannot create resource "persistentvolumeclaims" in API group "" in namespace "namespace"
```
This is due to the "emr-containers" role, not having the necessary permissions namely:
```
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - create
  - delete
```
This role is created during the cluster setup using the following command: 
```
eksctl create iamidentitymapping \
    --cluster my_eks_cluster \
    --namespace kubernetes_namespace \
    --service-name "emr-containers"
```

### How to reproduce it?

1. Follow the documentation [here](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up.html) to create an EMR on EKS virtual cluster (**NOTE**: Enable [cluster access for Amazon EMR on EKS](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-cluster-access.html) using eksctl, not manually)
2. Follow only this page of the workshop [here](https://www.eksworkshop.com/beginner/170_statefulset/ebs_csi_driver/)
3.  Submit a job with the following configurations included:
```
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.claimName=OnDemand
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.storageClass=gp
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.sizeLimit=498Gi
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.mount.path=/data
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.mount.readOnly=false
```
4. In the driver logs for the job you'll see the error mentioned above.

**Logs**

```
Forbidden! Configured service account doesn't have access. Service account may have been revoked. persistentvolumeclaims is forbidden. User "system:serviceaccount:emr:emr-containers-sa-spark-client-XXXXXXXXXX-xxxxxxx" cannot create resource "persistentvolumeclaims" in API group "" in namespace "namespace"
```

**Anything else we need to know?**

**Versions**

```
veksctl version: 0.60.0
kubectl version: v1.21.2-13+d2965f0db10712
OS: linux
```

**Comment by melodyyangaws** [comment]
Your storage class name could be different while replicating the steps. Please change the Spark config to a correct name based on  the output of your command `kubectl get sc`. For example:
```
spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.storageClass=gp2
```

**Comment by chachampis** [comment]
I have the same problem, even though I have used the correct storageClass name (gp2). In my case, the user mentioned in the error message is "system:serviceaccount:emr:emr-containers-sa-spark-**driver**-XXXXXXXXXX-xxxxxxx" (I am trying to provision storage for the executor pods).
This serviceaccount gets its permissions from `emr-containers-role-spark-driver` role, through a rolebinding. I tried editing the role to give it permissions to create persistentvolumeclaims but then jobs do not start at all. Running `aws emr-containers list-job-runs` says (details removed for brevity):

`{
    "jobRuns": [
        {
            "state": "FAILED",
            "stateDetails": "Cluster xxxxxxxxx does not have sufficient permissions.",
            "failureReason": "CLUSTER_UNAVAILABLE",
        },
`

**Comment by melodyyangaws** [comment]
> I have the same problem, even though I have used the correct storageClass name (gp2). In my case, the user mentioned in the error message is "system:serviceaccount:emr:emr-containers-sa-spark-**driver**-XXXXXXXXXX-xxxxxxx" (I am trying to provision storage for the executor pods). This serviceaccount gets its permissions from `emr-containers-role-spark-driver` role, through a rolebinding. I tried editing the role to give it permissions to create persistentvolumeclaims but then jobs do not start at all. Running `aws emr-containers list-job-runs` says (details removed for brevity):
> 
> `{ "jobRuns": [ { "state": "FAILED", "stateDetails": "Cluster xxxxxxxxx does not have sufficient permissions.", "failureReason": "CLUSTER_UNAVAILABLE", }, `

To manually fix it, you have to add the permission to  the main role `emr-container` first. Adding the corresponding permissions to Spark driver roles as suggested by error messages, it will not help unless the “emr-containers” primary role has included the required permissions.

**Comment by Himangini** [comment]
Closing this issue since the PR related to this is merged and released.
