### ISSUE TITLE
ensure new nodegroups inherit version from cluster stack

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#540]
We need to make sure we create new nodegroups using AMI that matches version of the control plane. We should also check existing nodegroups and warn the user if any drift is detected.

**Comment by whereisaaron** [comment]
Matched versions are ideal, but I think nodes can usually differ from the control plane by up to one minor version. E.g. 1.11.x nodes should work with 1.12.x control plane and vice versa. Otherwise upgrades wouldn’t be possible.

**Comment by errordeveloper** [comment]
@whereisaaron yes, indeed, but it's still a bug that needs addressing.

**Comment by errordeveloper** [comment]
Closing via #571.
