### ISSUE TITLE
error when creating EKS cluster in existing VPC's private subnet. EKS cluster stack exports private subnet while worker-nodes stack trying to import public subnet details.

### ISSUE THREAD

**Issue by sabhizer** [weaveworks/eksctl#543]
**What happened?**
eksctl create cluster --name=test3 --version=1.11 --vpc-private-subnets=subnet-0f6a14473fb6420bb,subnet-02bc1b3308890637c --node-volume-size=100 --node-ami-family=AmazonLinux2 --node-type=t3.medium --nodes=2 --nodes-min=2 --nodes-max=6 --asg-access  --tags environment=eksctl --region=us-east-1

Output 
Error
[✖]  waiting for CloudFormation stack "eksctl-test3-nodegroup-ng-175c3070" to reach "CREATE_COMPLETE" status: ResourceNotReady: failed waiting for successful resource state
[✖]  failed to create cluster "test3"

Checked the CLoudformation template for cluster and node-group

On Cluster template
"Outputs":{
    "SubnetsPrivate": {
      "Export": {
        "Name": {
          "Fn::Sub": "${AWS::StackName}::SubnetsPrivate"
        }
      },

While on worker template
        "VPCZoneIdentifier": {
          "Fn::Split": [
            ",",
            {
              "Fn::ImportValue": "eksctl-k8s-mgt-moni-cluster::SubnetsPublic"
            }
          ]
        }
      },

**What you expected to happen?**
Cluster to get created

**How to reproduce it?**
Include the steps to reproduce the bug

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.21"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mumoshu** [comment]
@sabhizer Hey! Would passing `--node-private-networking` solves your issue?

**Comment by errordeveloper** [comment]
Yes, as @mumoshu pointed out, please try `--node-private-networking`.

**Comment by sabhizer** [comment]
It works. Thanks.
