### ISSUE TITLE
[Feature]  Allow tag propagation to launched EC2 instances using `propagateASGTags`

### ISSUE THREAD

**Issue by youwalther65** [weaveworks/eksctl#5443]
### What feature/behavior/change do you want?
I propose to enhance the recently introduced tag propagation feature for ASG "propagateASGTags: true" to allow tag propagation to launched EC2 instances as well by setting "Tag new instances = yes", Currently only  "Tag new instances = no" is implemented.

### Why do you want this feature?
Using this tag as an AWS  "cost allocation tag" allows cost transparency by tagging all relevant EC2 instances of an EKS cluster and making it visible in Cost Explorer, CUR etc.

**Comment by youwalther65** [comment]
This can be closed because this issue provides the answers needed and proposes to update documentation regarding this. [https://github.com/weaveworks/eksctl/issues/5420#issuecomment-1205159412](url)

**Comment by Himangini** [comment]
> This can be closed because this issue provides the answers needed and proposes to update documentation regarding this. [https://github.com/weaveworks/eksctl/issues/5420#issuecomment-1205159412](url)

The link doesn't seem to be working, 
Correct link here  - https://github.com/weaveworks/eksctl/issues/5420#issuecomment-1205159412
Closing this issue 👍🏻
