### ISSUE TITLE
t4g not supported.

### ISSUE THREAD

**Issue by bil9000** [weaveworks/eksctl#5456]
In the documentation on this page: 
https://eksctl.io/usage/arm-support/
It says that t4g is supported as an instance type.  This seems to be incorrect ask the command fails for t4g and the AWS documentation does not mention t4g as supported.
That said: I <3 eksctl, thank you for building this.

**Comment by bil9000** [comment]
User error.  Sorry. :(

**Comment by Skarlso** [comment]
The best kind of error from a maintainer's perspective. :D
