### ISSUE TITLE
trying to create a cluster with existing role

### ISSUE THREAD

**Issue by snata71** [weaveworks/eksctl#5470]
Even though i am using 
iam:
   serviceRoleArn:  aws::***********************role/<role name>**********, but it is not using that particular role, but it creates a new role and creates the cluster and node group.  if there is no permission to create the role, the stack fails with unexpected error.   is there any workaround for this.

**Comment by snata71** [comment]
> Hi @snata71, the casing is incorrect for `serviceRoleArn`, it should be `serviceRoleARN`. Fields in ClusterConfig are case-sensitive.

Thank you, That worked

**Comment by cPu1** [comment]
> > Hi @snata71, the casing is incorrect for `serviceRoleArn`, it should be `serviceRoleARN`. Fields in ClusterConfig are case-sensitive.
> 
> Thank you, That worked

Great! Please feel free to open a new issue if you have more questions.
