### ISSUE TITLE
Does eksctl has release page mentioning the features that comes with the release or a roadmap page ?

### ISSUE THREAD

**Issue by shyam-ks** [weaveworks/eksctl#5473]
Does eksctl has release page mentioning the features that comes with the release or a roadmap page ?

**Comment by cPu1** [comment]
Yes, we have a page for releases: https://github.com/weaveworks/eksctl/releases. We don't have a public roadmap page though but you can search by labels in issues.

**Comment by Himangini** [comment]
@shyam-ks is there anything particular you are looking for?
