### ISSUE TITLE
[Feature] add support to enable/disable nvidia plugin in config file schema

### ISSUE THREAD

**Issue by TheRealGoku** [weaveworks/eksctl#5489]
eksctl supports nvidia daemonset driver installation by identifying node group instance type used in eksctl cluster config file or command line creation https://eksctl.io/usage/gpu-support/

Some users may not want the driver manifest installed by the eksctl, As of today(6th July 2022) I could see option to disable it only via cmd arguments, it would be good user experience if this settings is incorporated in the config file schema https://eksctl.io/usage/schema/

If implemented, no further extra caution needed in pipeline build arguments to take care of it separately.

community@: Please reply under this thread if you found a way to add this in schema. and also hit a thumbs up if you are encountering this issue

**Comment by vsnishad** [comment]
I second this as well. Thanks for looking into it!

**Comment by Himangini** [comment]
Thanks for your request, after discussing with the team we decided we won't be implementing this functionality anytime soon. The workaround exists and it's a bit complicated to find the right place in the schema to incorporate these settings. However, we are happy to accept PRs if you have a solution in mind.

**Comment by storyalex** [comment]
Hello! I have node groups that are transient but scheduled that would benefit greatly from this improvement.
