### ISSUE TITLE
allow user to patch or delete default storage class

### ISSUE THREAD

**Issue by whereisaaron** [weaveworks/eksctl#549]
**What happened?**
I create a cluster with [`--storage-class=false`](https://github.com/weaveworks/eksctl/issues/175), yet the created cluster still had a `gp2` storage class created.
```
$ kubectl get storageclasses
NAME            PROVISIONER             AGE
gp2 (default)   kubernetes.io/aws-ebs   21h
```
I created this cluster with no nodegroup and added and removed nodegroups, could the `StorageClass` have been created during those changes. `--storage-class` is only a cluster argument right, I don't need to add it for nodegroups too?

**What you expected to happen?**
No `StorageClass`

**How to reproduce it?**
Include the steps to reproduce the bug

```
eksctl create cluster \
  --name=$CLUSTER_NAME \
  --region=$AWS_DEFAULT_REGION \
  --profile=$AWS_PROFILE \
  --node-private-networking \
  --vpc-private-subnets=$SUBNETS \
  --without-nodegroup \
  --storage-class=false \
  --asg-access \
  --timeout=30m0s
```

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.21"}
$ uname -a
Linux 4.4.0-17763-Microsoft #253-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

#175 #224

**Comment by errordeveloper** [comment]
The default storage class is only optional in 1.10, as of 1.11 it's present out of the box.

https://github.com/weaveworks/eksctl/blob/e8db88c8c75910a6fdb2b5e33fbc7eb4b79ebe4a/pkg/ctl/create/cluster.go#L534-L544

**Comment by errordeveloper** [comment]
> `--storage-class` is only a cluster argument right, I don't need to add it for nodegroups too?

Yes, it's cluster-wide. I don't know if possible, but would certainly make sense to have, storage classes that are available only on certain nodegroups. But that's irrelevant when default storage class is concerned, as it's meant to be available globally.

**Comment by whereisaaron** [comment]
Thanks @errordeveloper. Why is it not optional in 1.11? Does AWS create it? It is inconvenient because it is marked as default, so it is a blocker for the roll-out process. It is no problem to delete it, but it is more convenient if it is just never created 😄

**Comment by errordeveloper** [comment]
Yes, EKS creates it for you. I am curious, why exactly is it a blocker?

**Comment by whereisaaron** [comment]
Just that when I try to create the real default StorageClass, that is an error because a default one already exists. So I have to patch or remove the EKS one first. No big deal though, easily done.

I guess you could either get the `--storage-class=false` option to delete it. Or just remove the option or make it an error for 1.11+ deployments.

**Comment by whereisaaron** [comment]
The `gp2` StorageClass that EKS makes is not great, since it has `volumeBindingMode: Immediate`, so the PV chooses the AZ rather than letting the Pod scheduler choose (`volumeBindingMode: volumeBindingMode: WaitForFirstConsumer`). Another reason to delete it 😄

**Comment by errordeveloper** [comment]
Thanks for sharing the info! It does make sense, I am curious if it's
possible to update the object? I heard it is a little tricky to delete
these, haven't dealt with it myself...

**Comment by whereisaaron** [comment]
Deleting StorageClasses in no problem, provided you haven't created PVs for that use that StorageClass. So it is easy to delete as soon as you create the cluster.

Adding and removing the default annotation is also no problem. It is not even required to have any default StorageClass. And even if you have used `gp2` you can switch the default StorageClass to something else:
```
kubectl patch storageclass gp2 -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
kubectl patch storageclass efs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

**Comment by errordeveloper** [comment]
As per #1029, it seems most plausible to remove the flag as it stand now. To solve this issue, I think best course of action will be to add config field that lets user either delete the default storage class or patch it. I'll change the title of the issue to make that clear.

/cc @kalbir

**Comment by costela** [comment]
Just to add to the list of use-cases for this feature: the `gp2` storage class is currently created with `allowVolumeExpansion: false` for new clusters. Seems like a nice candidate for frequent patching.

As a more general solution maybe it would be appropriate to supply kind-agnostic patching for any resources which might be created by AWS itself?
