### ISSUE TITLE
[Bug] URL for eksctl latest release seems incorrect

### ISSUE THREAD

**Issue by shashlight** [weaveworks/eksctl#5507]
I'm running Ubuntu 22.04 on my AWS EC2. And when I tried to install using the standard instruction in the Readme, I'm getting an error that the file is not in gzip format. But, the issue, I believe is that the URL is not reachable from EC2.

url --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp

gzip: stdin: not in gzip format
tar: Child returned status 1

Also, getting not found, when using curl

curl "https://github.com/weaverworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz"
Not Found

I have no issues in installing AWS cli via URL.

Can the release team advise?

**Comment by Nareshfreak** [comment]
iam also getting the same issue....

**Comment by Nareshfreak** [comment]
> Maybe it was a temporary issue, but it lasted for more than 90 minutes. Now, I can download and install eksctl.

where did you download the eksctl file from ??
please share the link
