### ISSUE TITLE
[Bug] `eksctl get iamidentitymapping` hangs forever when kubectl is not installed

### ISSUE THREAD

**Issue by isimluk** [weaveworks/eksctl#5512]
### What were you trying to accomplish?
I am trying to make cft usable for eks (as an interim before the real fix https://github.com/aws/containers-roadmap/issues/185)

### What happened?
 - I opened the AWS Cloud Shell
 - I installed eksctl
 - I run `eksctl get iamidentitymapping --cluster $CLUSTER_NAME --region=$OTHER_REGION`
 - hang forever

### How to reproduce it?
Open AWS cloudshell or any other env that does not have kubeclt installed.
```
curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin
eksctl get iamidentitymapping --cluster $CLUSTER_NAME --region=$OTHER_REGION
```

**Logs**
No longs were printed out. Unable to Ctrl-C.

**Versions**
eksctl version: 0.105.0

**Comment by cPu1** [comment]
Can you rerun the command with verbose logging enabled (passing `-v4`) and paste the output, redacting any sensitive information? Are you able to connect to the cluster using other Kubernetes clients? Are you able to successfully issue commands using the AWS CLI in the same environment? How was the cluster created?

The title of the issue says that this happens when kubectl is not installed, but eksctl does not rely on kubectl to communicate with the API server.

**Comment by isimluk** [comment]
Thank You for your help @cPu1. I am closing this issue as there the hang seems to be unrelated to eksct.

When I removed the kubectl from the cloudshell env, I was no longer able to reproduce this issue. When I tried to reproduce this in some other region, I have seen cloud shell hang in the middle of eksctl print-out, so the initial reproducer was perhaps not fault of the eksctl.

Thank You and osrry for the noise.

**Comment by cPu1** [comment]
> Thank You for your help @cPu1. I am closing this issue as there the hang seems to be unrelated to eksct.
> 
> When I removed the kubectl from the cloudshell env, I was no longer able to reproduce this issue. When I tried to reproduce this in some other region, I have seen cloud shell hang in the middle of eksctl print-out, so the initial reproducer was perhaps not fault of the eksctl.
> 
> Thank You and osrry for the noise.

No worries :slightly_smiling_face:. It was likely an issue with connectivity to the API server.
