### ISSUE TITLE
[Task] Remove support for EKS 1.19

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#5521]
### Description
As per the calendar for [Amazon EKS end of support](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) August 1, 2022 is the end of support for Kubernetes version 1.19 

We need to remove support for 1.19 and modify any relevant docs wherever possible.
Reference PR - see [here](https://github.com/weaveworks/eksctl/pull/5073)

**Comment by neha-viswanathan** [comment]
@Himangini I can work on this.

**Comment by cPu1** [comment]
> @Himangini I can work on this.

Please feel free to pick it up. I'll note that this is a time-bound task, so it'd be ideal to have a PR ready by the end of next week. It should be straightforward though.

**Comment by Himangini** [comment]
> @Himangini I can work on this.

Thanks Neha. 🎉 We're happy to accept PRs. Feel free to reach out to us if you need any help
