### ISSUE TITLE
When creating a cluster using a config file, provide the ability to skip nodegroup creation

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/eksctl#555]
**Why do you want this feature?**
I want the ability to selectively create nodegroups using the same configuration file I use to create my cluster at a later time.

**What feature/behavior/change do you want?**
--without-nodegroup skips initial nodegroup creation but I need the ability to skip all nodegroups in my configuration file.

**Comment by D3nn** [comment]
Looks like this one was done in [PR #406](https://github.com/weaveworks/eksctl/pull/406).  Closing.

**Comment by errordeveloper** [comment]
Yes, looking at #406 now, I think it's actually sufficient to begin with. We can add a filter flag later.

**Comment by D3nn** [comment]
Found an issue where the node groups *are* being created.  Re-opening.
