### ISSUE TITLE
Applying Tags to Log Groups

### ISSUE THREAD

**Issue by JayG-EBSCO** [weaveworks/eksctl#5551]
### What help do you need?

We are using a config file with eksctl 0.95.0 to build our clusters. As part of such, we are enabling all cloudwatch logging for a cluster. When the build occurs, the tags we pass to the cluster are added to the cluster itself, but the log group does not get tagged.

I've looked through the config file schema and have not seen any option to pass tags to the log groups like we would to the cluster, or our autoscaling groups.

Is there a way we can pass the cluster tags to the log groups as well with eksctl during the build, and ideally, an update process?

**Comment by cPu1** [comment]
>I've looked through the config file schema and have not seen any option to pass tags to the log groups like we would to the cluster, or our autoscaling groups.

There's no field / CLI option to propagate tags to the CloudWatch log group. 

>Is there a way we can pass the cluster tags to the log groups as well with eksctl during the build, and ideally, an update process?

This is not supported, and not something we're planning to support. The CloudWatch Logs log group is created by EKS which offers no control over its creation. If you're looking to identify log groups associated with a cluster, the log group name's format is `/aws/eks/<cluster>/cluster`.

**Comment by JayG-EBSCO** [comment]
Thanks for the quick reply. Looks like we'll be writing some automation for it then.
