### ISSUE TITLE
[Task] Update Karpenter to v0.13.2

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#5562]
### Description

Atm, we have Karpenter versioned pinned to 0.9.0. Upgrade this version to [0.13.2](https://github.com/aws/karpenter/releases/tag/v0.13.2)

Previous Reference ticket: #5023 

Edit 18-08-2022:
AWS notified us of a new stable release of v0.15.0 yesterday so we'll be updating the minimum supported version to `0.15.0`

**Comment by Pitta** [comment]
May as well make it `0.15.0` since it seems like they solved for the CoreDNS problems with bootstrapping.

IMO this is a major useability hurdle for EKS + Karpenter, and tracking the newer versions is a must.

**Comment by Himangini** [comment]
> May as well make it `0.15.0` since it seems like they solved for the CoreDNS problems with bootstrapping.
> 
> IMO this is a major useability hurdle for EKS + Karpenter, and tracking the newer versions is a must.

@Pitta Yup that's the plan, we already have a PR for this. 🎉

**Comment by mbevc1** [comment]
We have 0.16.1 now as well
