### ISSUE TITLE
Update "get nodegroup" to show volume size(s)

### ISSUE THREAD

**Issue by paulbsch** [weaveworks/eksctl#559]
**Why do you want this feature?**
It would be helpful to see volume information when listing nodegroups.

**What feature/behavior/change do you want?**
When running "eksctl get nodegroup", it would be nice if it also displayed to volume size(s).  (Some folks might want to also see the volume types?)

**Comment by errordeveloper** [comment]
Thanks for suggesting this, seems like plausible feature. I wonder if is this something that `kubectl describe node` shows clearly enough, or not at all?
