### ISSUE TITLE
[Task] Upgrade `k8s.io/kubernetes` dependency

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/eksctl#5608]
https://github.com/weaveworks/eksctl/pull/5604 upgraded the `k8s.io/kubernetes` dependency from 1.19, which is no longer supported by EKS, to 1.20.

This ticket is to decide if we want to keep the version pinned at all. If we do, then which one? 

If we do want to pin it, one option is to keep it the same as eksctl's default k8s version (currently 1.22).

### Note
It is not possible to only pin `k8s.io/kubernetes` as it is not intended to be used that way. If doing this, other `k8s.io/xyz` subcomponents have to be pinned as well, like this, which is what we do currently: https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-505632294 
This script is helpful for doing this for a given k8s version: https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-521493597

**Comment by Himangini** [comment]
As discussed in planning we will pin the `k8s.io/kubernetes` dependency to `1.22` as part of this ticket.
