### ISSUE TITLE
Add support for kubernetes version 1.23

### ISSUE THREAD

**Issue by Thomas999999** [weaveworks/eksctl#5617]
Hi,
AWS released 1.23 for EKS cluster but the latest version of eksctl does not support 1.23, but we need it urgently:

[36m2022-08-15 10:35:42 [ℹ]  eksctl version 0.108.0
null_resource.terraform_eks (remote-exec): [0m[36m2022-08-15 10:35:42 [ℹ]  using region eu-west-1
null_resource.terraform_eks (remote-exec): [0mError: invalid version, supported values: 1.19, 1.20, 1.21, 1.22

Thanks

**Comment by vikas027** [comment]
> We have added support for [v1.23](https://github.com/weaveworks/eksctl/releases/tag/v0.109.0-rc.0)

Just tried it, works like a charm.
