### ISSUE TITLE
[Bug] EKSCTL doesn't recognise new nodegroup after failing to create one with bad configuration

### ISSUE THREAD

**Issue by andrei-dascalu** [weaveworks/eksctl#5630]
### What were you trying to accomplish?

Create an IPv6 cluster

### What happened?

In my config.yaml, I had added a simple nodeGroup (which is unmanaged). Cluster creation stops with Eksctl saying

```
022-08-16 19:52:08 [✖]  unmanaged nodegroups are not supported with IPv6 clusters
```

Following this, I tried to fix the config by changing to managedNodeGroups and running `upgrade`, however on upgrade eksctl claimed everything is fine

```
2022-08-16 19:55:27 [✔]  all resources in cluster stack "eksctl-ae-eks-experimental-cluster" are up-to-date
```

### How to reproduce it?

Setup config.yaml with ipv6 cluster and `nodeGroups`. After failure, update `nodeGroups` to `managedNodeGroups`.

**Logs**

**Anything else we need to know?**

Eksctl `0.108.0-dev+728d4ad1.2022-08-12T13:07:50Z` on MacOS installed via `brew`

```
eksctl version: 0.108.0-dev+728d4ad1.2022-08-12T13:07:50Z
kubectl version: v1.24.3
OS: darwin
```

**Comment by cPu1** [comment]
`eksctl upgrade cluster` upgrades the control plane to a newer version, it does not attempt to create any new nodegroups defined in the ClusterConfig. To add new nodegroups, you'll have to run `eksctl create nodegroup`.

**Comment by andrei-dascalu** [comment]
@cPu1 hi, thanks for the reply. I don't quite understand then how it's supposed to work with config.yaml

Config.yaml is supposed to provide a declarative way of configuring a cluster, right? If my first attempt fails, I would expect my second attempt (with a fixed configuration) to have a different result.

**Comment by matti** [comment]
@andrei-dascalu your assumption is right, but eksctl seems to be designed in many ways so that a "happy path" run works like that, but every other case needs understanding what went wrong and how to fix it. eg. eksctl != terraform.
