### ISSUE TITLE
eksctl create iamserviceaccount returns error only one argument is allowed to be used as a name

### ISSUE THREAD

**Issue by andsus** [weaveworks/eksctl#5631]
Steps:
1. eksctl version
0.108.0
2. eksctl create iamserviceaccount ––cluster=celestials ––name=prodcatalog-envoy-proxies ––namespace=prodcatalog-ns ––attach-policy-arn=arn:aws:iam:116666666666:policy/ProdEnvoyNamespaceIAMPolicy ––override-existing-serviceaccounts --approve
2022-08-16 10:38:26 [✖]  only one argument is allowed to be used as a name

**Comment by cPu1** [comment]
```eksctl create iamserviceaccount ––cluster=celestials 
```

The `cluster` argument here is using en dash (`–`) instead of hyphens (`-`), causing eksctl to interpret it as a name argument. It appears the the command was copied from somewhere with formatting. The correct syntax is:

```
eksctl create iamserviceaccount --cluster=celestials --name=prodcatalog-envoy-proxies --namespace=prodcatalog-ns --attach-policy-arn=arn:aws:iam:116666666666:policy/ProdEnvoyNamespaceIAMPolicy --override-existing-serviceaccounts --approve
```

**Comment by Bhavyasri05** [comment]
eksctl create iamserviceaccount \ --name ebs-csi-controller-sa \ --namespace kube-system \ --cluster eks2 \ --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \ --approve \ --role-only \ --role-name AmazonEKS_EBS_CSI_DriverRole \ --region us-east-1
2023-07-05 18:26:34 [✖]  only one argument is allowed to be used as a name
