### ISSUE TITLE
[Feature] Wildcard support in Amazon EKS Fargate Profile Selectors

### ISSUE THREAD

**Issue by tanvp112** [weaveworks/eksctl#5647]
Please consider supporting this new feature: https://aws.amazon.com/about-aws/whats-new/2022/08/wildcard-support-amazon-eks-fargate-profile-selectors/

**Comment by TiberiuGC** [comment]
Hi @tanvp112! Thanks for opening this feature request 👍 The team will review and see whether this functionality fits in with the project. In the meantime, if you would like to demonstrate a solution, feel free to open a PR at any time 😃.
