### ISSUE TITLE
[Bug] Error: could not create fargate profiles: failed to create Fargate profile "fp-default" on EKS cluster

### ISSUE THREAD

**Issue by prasobhen** [weaveworks/eksctl#5652]
Fargate profile is already its trying to create again after EKS cluster upgrade from 1.21 to 1.22

EKSCTL_VERSION=0.107.0

creating Fargate profile "fp-default" on EKS cluster "xxx-xxx-xx-eks"
2022-08-29T06:58:39.6404332Z Error: could not create fargate profiles: failed to create Fargate profile "fp-default" on EKS cluster "xxx-xxx-xx-eks": failed to create Fargate profile "fp-default": operation error EKS: CreateFargateProfile, https response error StatusCode: 409, RequestID: 69f8ee49-a113-46bd-9abc-97c5a9fcb0a9, api error ResourceInUseException: A Fargate Profile already exists with this name in this cluster.

**Comment by prasobhen** [comment]
Some one please check this error

**Comment by cPu1** [comment]
@prasobhen, can you share your ClusterConfig file? This does look like a bug. We'll investigate the issue and get back to you soon.

**Comment by prasobhen** [comment]
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: xxx-xxx-xx-eks  # EKS Cluster Name
  region: eu-central-1
  version: "1.22"
  tags:
    project: xxx
    environment: xxx
    map-migrated: d-server-xxxxxxxx
vpc:
  id: "vpc-xxxxxx"      # VPC ID created with Terraform. ID got from Terraform output
  # publicAccessCIDRs: ["1.1.1.1/32", "2.2.2.0/24"] #If Azure DevOps CIDR range is known
  subnets:
    private:
      eu-central-1a:
          id: "subnet-xxxxx"    # Subnet created and properly tagged with Terraform. ID got from Terraform output
      eu-central-1b:
          id: "subnet-xxxxx"    # Subnet created and properly tagged with Terraform. ID got from Terraform output
      eu-central-1c:
          id: "subnet-xxxxx"    # Subnet created and properly tagged with Terraform. ID got from Terraform output
identityProviders:
  - name: eks-oidc-config
    type: oidc
    issuerUrl: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_xxxxx"
    clientId: "xxxxxxxx"
    usernameClaim: email
    groupsClaim: "cognito:groups"
    groupsPrefix: "gid:"
fargateProfiles: # creating Fargate profiles for each workload
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be scheduled onto Fargate:
      - namespace: kube-system

**Comment by jeraldsm** [comment]
Hi @Himangini 

We tried upgrading eksctl version from 0.96.0 to the latest one which is 0.128.0, and the issue is still happening..

`2022-XX-XX ... Error: could not create fargate profiles: ..., https response error StatusCode: 409, RequestID: ..., api error ResourceInUseException: A Fargate Profile already exists with this name in this cluster.
`
