### ISSUE TITLE
Create ipv6 subnets for created VPC 

### ISSUE THREAD

**Issue by VincentCouzij** [weaveworks/eksctl#566]
**Why do you want this feature?**
To be able to create dualstack load balancers in the created VPC (Our api needs to be accessible via ipv6). I am currently adding the IPv6 CIDR's to the subnets manually but would like this process automated with eksctl.

**What feature/behavior/change do you want?**
Options for adding IPv6 CIDR's to vpc/subnets and route table setup for ipv6 to the internet gateway.

**Comment by errordeveloper** [comment]
Hi @VincentCouzij! To be clear, this won't enable IPv6 for pods, just for ELB/ALB?

**Comment by VincentCouzij** [comment]
@errordeveloper Yes only for the created VPC so ELB and ALB's can use dualstack.

**Comment by errordeveloper** [comment]
Thanks! Am I understanding correctly that you'd be looking to have IPv6 enabled for the set of subnets eksctl currently creates (not separate set of subnets)? And would be okay to keep IPv6  disabled for the EC2 instances?

Out of curiosity - would you be looking to use Kubernetes with IPv6 also, or ingress is all that matters?

**Comment by VincentCouzij** [comment]
Yes add ipv6 CIDR to each created subnet in the default setup. In our setup EC2 instances don't need their own ipv6 address. All traffic is routed through ALB's.

For now it's just ingress.

**Comment by errordeveloper** [comment]
I'm going to start looking into this and will open WIP PR once I have something going.

**Comment by errordeveloper** [comment]
@VincentCouzij see #776, it appears to work, but I will need to review a few things and write some tests. Feel free to reach out on slack if you have time to test it.
