### ISSUE TITLE
[Bug] Warnings issued when running eksctl create cluster --fargate

### ISSUE THREAD

**Issue by Eternal21** [weaveworks/eksctl#5671]
### What were you trying to accomplish?
Create a Fargate backed EKS cluster using the following command:
`eksctl create cluster --name test --region us-east-1 --fargate`

### What happened?
The cluster was created successfully, but I noticed two warning messages in the output:
```
2022-09-04 17:05:48 [ℹ]  created Fargate profile "fp-default" on EKS cluster "test"

W0904 17:06:18.724822  189208 warnings.go:70] 
spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: 
beta.kubernetes.io/os is deprecated since v1.14; use "kubernetes.io/os" instead 
    
W0904 17:06:18.726396  189208 warnings.go:70] 
spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[1].key: 
beta.kubernetes.io/arch is deprecated since v1.14; use "kubernetes.io/arch" instead 

2022-09-04 17:06:18 [ℹ]  "coredns" is now schedulable onto Fargate
```

I did not see any warnings when running the same command without the `--fargate` flag.

### How to reproduce it?
Run the following command and observe the output (may take up to 20 minutes to complete):
`eksctl create cluster --name test --region us-east-1 --fargate`

**Versions**
```
eksctl version: 0.109.0
kubectl version: v1.24.3
OS: windows
```

**Comment by Aminechakr** [comment]
Facing some issues when upgrading my CoreDNS file using rewrite plugin : 

`spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[1].key: beta.kubernetes.io/arch is deprecated since v1.14; use "kubernetes.io/arch" instead `

**Comment by aakilin** [comment]
@Aminechakr I faced the same warning
