### ISSUE TITLE
[Bug] auth ConfigMap role entry deleted when a node group deleted - even if used by another group

### ISSUE THREAD

**Issue by nandanrao** [weaveworks/eksctl#5690]
Happy to try to reproduce this from scratch if this doesn't jive, but just wanted to start the conversation because it seemed pretty clear what was happening on our cluster: 

1. Create a node group with: 

```yaml
iam: 
    instanceRoleARN: "arn:aws:iam::XXX:role/foo"
```

2. Node group is created an (seemingly new feature?) auth ConfigMap is updated (mapRoles)

3. Everything happy. 

5. Create a new nodegroup, same iam instancerole. 

6. Delete the old nodegroup. Upon deletion, it _deletes_ the role from the auth ConfigMap. Even though this is still used by the new nodegroup.

**Comment by dingxiong** [comment]
hello, we faced the same issue. Could someone reopen it and fix it?
