### ISSUE TITLE
[Feature] Remove update-maxpods from Makefile

### ISSUE THREAD

**Issue by Gearheads** [weaveworks/eksctl#5691]
### What feature/behavior/change do you want?

Hello, I have noticed that the file `maxpods_generate.go` has been removed, so I was wondering if this `make` command should be removed or changed in some way?
https://github.com/weaveworks/eksctl/blob/main/Makefile#L163
```
### Update maxpods.go from AWS
.PHONY: update-maxpods
update-maxpods: ## Re-download the max pods info from AWS and regenerate the maxpods.go file
	@cd pkg/nodebootstrap && go run maxpods_generate.go
```

### Why do you want this feature?

I noticed when running the command locally, I receive the following error message, which is why I was not sure if this `make` command is still valid?
```
% make update-maxpods
stat maxpods_generate.go: no such file or directory
make: *** [update-maxpods] Error 1
```

Any information, or help, would be greatly appreciated. 😄

**Comment by cPu1** [comment]
@Gearheads, you're right, that Makefile rule is no longer relevant and should be removed. Do you want to open a PR with the changes?

**Comment by Gearheads** [comment]
> @Gearheads, you're right, that Makefile rule is no longer relevant and should be removed. Do you want to open a PR with the changes?

@cPu1, yes, I would be happy to create a PR and help out. 😄
