### ISSUE TITLE
Provide an ability to PRESERVE configuration changes when updating EKS managed add-ons

### ISSUE THREAD

**Issue by sriramranganathan** [weaveworks/eksctl#5692]
EKS add-ons recently made a change to the EKS API to allow customers to retain their configuration changes made to the add-ons during add-on upgrade. Previously, this was not supported.

EKSCTL supports a --force flag when updating an addon which converts a self managed add-on to a EKS managed add-on. Does this also overwrite any custom configurations that the customer may have made to the add-ons? If so, this is equivalent to the OVERWRITE option that is supported by EKS API. 

**Feature Request:**
Provide an option for customers to retain their config changes during add-on upgrade. Please refer to the below doc that shows the options available for resolveConflict flag including the PRESERVE option

**Comment by Himangini** [comment]
We'll spike on this first 
Outcome: Proposal doc
Timebox: 1-2 days
