### ISSUE TITLE
Specifying EIP with NAT gateway

### ISSUE THREAD

**Issue by mooperd** [weaveworks/eksctl#5694]
Hello,

I see there has been some activity around this topic but it does not seem to have been implemented. We're looking for a way to assign a preallocated EIP to an NAT GW. Can anyone suggest how this can be accomplished or a workaround?

Thanks,

Andrew

**Comment by cPu1** [comment]
That is not supported. If you need that level of control, we recommend creating the VPC resources beforehand and supplying them to eksctl.
