### ISSUE TITLE
[Bug] build all distros github action is failing

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#5699]
Hello 👋 

The `build all distros` github action is failing a lot https://github.com/weaveworks/eksctl/actions/workflows/build-all-distros-nightly.yaml

For some reason I keep getting github notifications for it 😆 not sure how to turn it off.... but fixing it should solve it 😉

**Comment by aclevername** [comment]
it appears to be failing again https://github.com/weaveworks/eksctl/actions/runs/3233421827
![Screenshot 2022-10-12 at 10 58 23](https://user-images.githubusercontent.com/19669095/195313072-4d83dd73-2369-4fb1-81ae-4133ae072399.png)

I also seem to be the person that gets notifications for it 🤔 for some reason I'm the author of the trigger despite it being a scheduled run
![Screenshot 2022-10-12 at 10 59 40](https://user-images.githubusercontent.com/19669095/195313260-bf83003b-9cd3-46b7-8681-dd4cdc21eb3e.png)

**Comment by aclevername** [comment]
@TiberiuGC can we re-open this?

**Comment by aclevername** [comment]
The workflow is failing again, and I'm still getting notification 😞 https://github.com/weaveworks/eksctl/actions/runs/3468945297

@Himangini  @TiberiuGC @Skarlso can we re-open this issue until it gets addressed please? I wasn't sure what the state of this issue is as it got closed without any update.

**Comment by aclevername** [comment]
thanks for checking in @cPu1 😄 

>  Have you received any notifications during that period?

I got todays failure as a notification, and then none since the oct 18th. I mainly just was hoping there was a way to de-author me from the workflow so I don't get the notifications 😁

**Comment by michaelbeaumont** [comment]
I'm gonna chime in here and +1 the notification thing except for https://github.com/weaveworks/eksctl/actions/workflows/update-generated.yaml :wink: maybe it can be removed completely

**Comment by aclevername** [comment]
Appears to be failing again

![Screenshot 2023-01-10 at 10 11 21](https://user-images.githubusercontent.com/19669095/211523198-e287a335-7c89-4471-bb5b-1ba5ba8aa265.png)
