### ISSUE TITLE
Add option to disable hyper-threading

### ISSUE THREAD

**Issue by paulbsch** [weaveworks/eksctl#570]
**Why do you want this feature?**
Currently, hyper-threading is enabled by default.  When running high performance computing (HPC) workloads, it is preferable to have hyper-threading disabled.

Please visit this link for more details:
https://aws.amazon.com/blogs/compute/disabling-intel-hyper-threading-technology-on-amazon-linux/

I'm currently using "overrideBootstrapCommand" in my nodegroup configuration to turn this off.  This is a messy solution.  Also, it currently isn't possible to use this method when adding nodegroups from the command line.

**What feature/behavior/change do you want?**
A command line option and YAML config option to disable hyper-threading.  This option would execute the necessary commands while bootstraping.  (See the above link for a simple script which disables hyper-threading)

**Comment by errordeveloper** [comment]
You could disable it with a custom AMI, otherwise you could run a driver workload, or use an init container in your workload that makes sure hyper-threading is disabled. It might make sense to discuss as a more general feature proposal for Kubernetes, but I'm not so sure it makes sense to make an explicit feature of eksctl.

**Comment by paulbsch** [comment]
It needs to be disabled before the kubelet starts.   So I don't see how a driver workload or an init container could work.  It's an OS level change, so I'm not sure how this could be a k8s feature.
A custom AMI would work, I thought of that, but that seems like a bit of overkill for a tweak such as this.

**Comment by errordeveloper** [comment]
Perhaps we could consider adding pre-bootstrap script, so you could use that instead of maintaining `overrideBootstrapCommand`. There is now support for adding nodegroups with config file (see #553).

**Comment by paulbsch** [comment]
Allowing a pre-bootstrap script would be great.  I'm sure others could benefit from that type of feature too.  (WRT #553, awesome!)

**Comment by errordeveloper** [comment]
Yeah, seems like we won't really need post-bootstrap, as you could always
make pre-bootstrap register a systemd unit or something else to run later,
or resort to overriding the whole thing.

**Comment by errordeveloper** [comment]
`preBootstrapCommand` will be available in 0.1.23, which is already making its way through CI.
