### ISSUE TITLE
[Bug] Getting Checksum mismatch while building eksctl

### ISSUE THREAD

**Issue by singhbhaskar** [weaveworks/eksctl#5703]
### What were you trying to accomplish?
I have cloned eksctl main branch and trying to build eksctl locally.

### What happened?
While building eksct I ran the command: `make install-build-deps` and I am getting the follow error message:
```
go: downloading github.com/blizzy78/varnamelen v0.6.1
verifying github.com/blizzy78/varnamelen@v0.6.1: checksum mismatch
        downloaded: h1:iYAU/3A6cpfRm2ZI0P/lece4jsc7GEbzsxTu+vBCChQ=
        go.sum:     h1:kttPCLzXFa+0nt++Cw9fb7GrSSM4KkyIAoX/vXsbuqA=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
make: *** [install-build-deps] Error 1
```
I have tried multiple times to run the command but was getting the same issue agian.

### How to reproduce it?
To reproduce this issue clone main branch and run `make install-build-deps`.

**Comment by TiberiuGC** [comment]
Hi @singhbhaskar, what `go version` are you using? Could you try upgrading it?

**Comment by TiberiuGC** [comment]
Could you try using latest code? Deps to that specific module have been updated, maybe it solves the problem for you.

**Comment by TiberiuGC** [comment]
Hi @singhbhaskar, have you been able to run make `install-build-deps` since my last message?
