### ISSUE TITLE
[Feature] Make HttpPutResponseHopLimit configurable

### ISSUE THREAD

**Issue by bitva77** [weaveworks/eksctl#5718]
So, when disabling IMDSv1 (enforcing v2) and running cluster-autoscaler and when you run a 3rd party CNI (like Cilium) your hop count to the meta data service is 3, not 2.  This may not be true for every CNI but seems to be for Cilium at least (possibly others).

Would be nice to be able to configure HttpPutResponseHopLimit to match.  I don't think this is a unique combination of things to run.  IMDSv1 is becoming a standard thing to disable these days.  cluster-autoscaler is like what makes EKS so cool to begin with.  And not everyone can run the aws-cni because of IP exhaustion issues.

The only way around this I see is to provide a custom launch template.  But that's kind of a lot to manage just to say "allow 3 hops".

Just a suggestion

https://github.com/weaveworks/eksctl/blob/07d2f09ae2190bb54ffa9631d299783fc9ef2fbf/pkg/cfn/builder/nodegroup.go#L439

**Comment by nikita-b** [comment]
Hello, we also, need to have custom hop, because we use DIND and hop from container is 3 :(

Is it planned?
