### ISSUE TITLE
Flag to pass a role for CloudFormation

### ISSUE THREAD

**Issue by olipachi** [weaveworks/eksctl#572]
I would very much like to see is a --role flag to pass a role arn for CloudFormation to assume, behaving exactly as it does in the AWS CloudFormation CLI. 

At my employer, we pass a role for CloudFormation to assume, which has more permissions than our developer roles. Since eksctl looks at my current federated role, the CloudFormation calls it makes under the hood fail. 

Currently, I'm unable to use eksctl because of the lack of this feature.

**Comment by nia2k7** [comment]
+1

**Comment by errordeveloper** [comment]
Hi @olipachi! We already have this with `--cfn-role-arn`. Please let me know if that is somehow insufficient, or perhaps you found it difficult to discover?

**Comment by olipachi** [comment]
Nope, that's exactly what I needed. 

It wasn't hard to discover, I just didn't see it in the readme section anywhere. Should've went to the cli help in the first place. My mistake. :) 

Thank you!
