### ISSUE TITLE
Make eksctl command output configurable

### ISSUE THREAD

**Issue by jack-evans** [weaveworks/eksctl#5738]
### What feature/behavior/change do you want?

I have been trying to wrap the `eksctl` command interface in my own golang CLI tool however one of the issues is that eksctl always prints out to stdout, e.g. [here](https://github.com/weaveworks/eksctl/blob/main/pkg/ctl/get/cluster.go#L112).

What this means is I have to do something like the following:
```golang
func captureOutputFromCobraCommand(ctx context.Context, f func(ctx context.Context) error, b io.Writer) error {
	old := os.Stdout

	r, w, err := os.Pipe()
	if err != nil {
		return err
	}
	os.Stdout = w

	if err := f(ctx); err != nil {
		return err
	}

	w.Close()
	os.Stdout = old

	_, err = io.Copy(b, r)
	if err != nil {
		return err
	}

	return nil
}

func main() {
        flagGrouping := cmdutils.NewGrouping()
	c := get.Command(flagGrouping)
	c.SetArgs([]string{"cluster", "--name", "test-cluster", "--output", "json"})

	buf := bytes.NewBufferString("")
	if err := captureOutputFromCobraCommand(ctx, c.ExecuteContext, buf); err != nil {
		panic(err)
	}

        // parse json and then do something else with it
}
```

I have tried `c.SetOut()` with a bytes.buffer and calling the command directly but the bytes array is still empty after. 

The `captureOutputFromCobraCommand` function is not thread-safe due to the `os.Stdout` global reference, meaning we have to be careful about how we utilise the command. It would be great if eksctl allowed the support of defining a custom output within the code so from a library perspective it is useable.

### Why do you want this feature?

This is so I and other users as a library avoid the use of non-thread-safe code that could catch us out in future.

**Comment by jack-evans** [comment]
Yeah that's sounds reasonable to me!

**Comment by hassaanakram** [comment]
Hi @TiberiuGC, I'd like to work on this improvement. 

I have gone through the code to see how it may be implemented. While most of the places where output is printed to the Stdout, it is fairly straightforward to change it to ```cmd.CobraCommand.OutOrStdout()```  and it should get us our required results. However, in [pkg/ctl/get/clusters.go](https://github.com/weaveworks/eksctl/blob/main/pkg/ctl/get/cluster.go#L112 ), [pkg/actions/nodegroup/create.go](https://github.com/weaveworks/eksctl/blob/797927954887ac4a5b78349f40265c762f595f5a/pkg/actions/nodegroup/create.go#L142) the ```cmd``` struct is not being passed. To change this, we can either pass an additional ```io.Writer``` param or propagate a ```*cmdutils.Cmd``` struct. 

What would you suggest?

Thanks!

**Comment by TiberiuGC** [comment]
Hi @hassaanakram , thanks a lot for offering to work on this ticket! 🚀 🔥 

So, for your first example ([pkg/ctl/get/clusters.go](https://github.com/weaveworks/eksctl/blob/main/pkg/ctl/get/cluster.go#L112)), as it is part of the `ctl` package, I'd simply suggest to propagate `*cmdutils.Cmd`.
For the second example ([pkg/actions/nodegroup/create.go](https://github.com/weaveworks/eksctl/blob/797927954887ac4a5b78349f40265c762f595f5a/pkg/actions/nodegroup/create.go#L142)), as we're in a different package, I would probably pass an additional `io.Writer` param. Perhaps make a small change to the [CreateOpts](https://github.com/weaveworks/eksctl/blob/797927954887ac4a5b78349f40265c762f595f5a/pkg/actions/nodegroup/create.go#L27) struct, along the lines below (feel free to pick better names if you have any suggestion).

```
type CreateOpts struct {
	...
	DryRunSettings            DryRunSettings
	...
}

type DryRunSettings struct {
	DryRun bool
	Writer io.Writer
} 
```

**Comment by hassaanakram** [comment]
Hey @TiberiuGC I'm finally free and can take up this ticket. 
I've made the changes as discussed and can accomplish what @jack-evans was trying to do without having to explicitly capture output from Stdout and simply using cmd.Setout(buf).

I'm thinking about the unit tests for this change. Do you have any suggestions? 

Thanks.

**Comment by TiberiuGC** [comment]
@hassaanakram I would not bother too much with unit testing this change for now. We currently have some tech debt tickets around unit testing the `ctl` package which I think are a prerequisite anyway.
