### ISSUE TITLE
Worker nodes not getting attached to the EKS cluster, getting timedout

### ISSUE THREAD

**Issue by ghoshaditya** [weaveworks/eksctl#574]
I am using a minimal cluster config, with an existing VPC and both private and public subnets.
But once the worker nodes are up, they do not join the cluster and i get a timeout.
Any reason ?

**Comment by errordeveloper** [comment]
It's hard to say what could be the issue, have you looked at kubelet logs? (You will need to enable SSH for that).

**Comment by errordeveloper** [comment]
Closing as there is no enough context and the issue is several month old - a lot has changed.
