### ISSUE TITLE
[Bug] eksctl gives AccessDenied while aws cli works fine

### ISSUE THREAD

**Issue by fabiokr** [weaveworks/eksctl#5755]
### What were you trying to accomplish?

I want to list clusters with `eksctl get clusters`

### What happened?

I'm getting this.

```
eksctl get clusters --verbose=4
2022-10-05 14:57:38 [▶]  role ARN for the current session is "arn:aws:iam::***:user/myuser"
Error: failed to list cluster stacks in region "us-east-1": operation error CloudFormation: ListStacks, https response error StatusCode: 403, RequestID: 69420e82-1c33-4758-abdc-2cfa814215f5, api error AccessDenied: User: arn:aws:iam::***:user/myuser is not authorized to perform: cloudformation:ListStacks on resource: arn:aws:cloudformation:us-east-1:***:stack/*/* with an explicit deny in an identity-based policy
```

### How to reproduce it?

My AWS user is in an IAM group which requires MFA to execute actions. I initially set the required credentials:

```
export AWS_DEFAULT_PROFILE=myuser
export AWS_PROFILE=myuser
export AWS_ACCESS_KEY_ID=mykey
export AWS_SECRET_ACCESS_KEY=mysecret
export AWS_SESSION_TOKEN=mytoken // comes from calling aws sts get-session-token

aws eks list-clusters
{
    "clusters": [
        "cluster-one"
    ]
}
```

`aws` cli calls work fine. `eksctl` don't. I recently upgraded from `eksctl` `0.80.0` to `0.113.0`.

**Versions**
```
eksctl version: 0.113.0
kubectl version: v1.21.2
OS: linux
```

**Comment by cPu1** [comment]
`eksctl get clusters` does not directly map to `aws eks list-clusters`, it also performs a call to `cloudformation:ListStacks` to determine which clusters were created by eksctl, so you'll need permissions for that. This is the expected behaviour and not a bug.

**Comment by fabiokr** [comment]
Hi, thanks for getting back. The `eksctl get clusters` and `aws eks list-clusters` comparison was actually just to show that calls to `aws` are working fine, but the ones with `eksctl` are not. The IAM role allows access to everything, but requires MFA. My guess is that maybe `eksctl` is not forwarding `AWS_SESSION_TOKEN` somehow. By rolling back to `eksctl` version `0.80.0` everything works as expected.
