### ISSUE TITLE
[Bug] Incorrect user data passed to Bottlerocket managed nodegroups

### ISSUE THREAD

**Issue by arnaldo2792** [weaveworks/eksctl#5756]
### What were you trying to accomplish?
I'm trying to create a Bottlerocket managed node group using a custom AMI with ipv6 support

### What happened?
Now that `overrideBootstrapCommand` is required, I believe that `eksctl` (or whatever under the hood) is creating launch templates with `MIME` formatted user data, which isn't supported by Bottlerocket.

### How to reproduce it?
Attempt to create a Bottlerocket managed node group with a custom AMI, and set `overrideBootstrapCommand` to an empty string. The resultant launch template includes the following base64 string:

```json
{ 
   "UserData": "TUlNRS1WZXJzaW9uOiAxLjANCkNvbnRlbnQtVHlwZTogbXVsdGlwYXJ0L21peGVkOyBib3VuZGFyeT05ZTk1NGVmMGIzYjJiYWVkZDdjNmI1MDMyYzg3OWM5YzI3ZjRlZThmMDZmYzU2MmIwN2UyZjM4MzdmZjkNCg0KLS05ZTk1NGVmMGIzYjJiYWVkZDdjNmI1MDMyYzg3OWM5YzI3ZjRlZThmMDZmYzU2MmIwN2UyZjM4MzdmZjkNCkNvbnRlbnQtVHlwZTogdGV4dC94LXNoZWxsc2NyaXB0DQpDb250ZW50LVR5cGU6IGNoYXJzZXQ9InVzLWFzY2lpIg0KDQoNCi0tOWU5NTRlZjBiM2IyYmFlZGQ3YzZiNTAzMmM4NzljOWMyN2Y0ZWU4ZjA2ZmM1NjJiMDdlMmYzODM3ZmY5LS0NCg=="
}
```

Which results in:

```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary=9e954ef0b3b2baedd7c6b5032c879c9c27f4ee8f06fc562b07e2f3837ff9

--9e954ef0b3b2baedd7c6b5032c879c9c27f4ee8f06fc562b07e2f3837ff9
Content-Type: text/x-shellscript
Content-Type: charset="us-ascii"


--9e954ef0b3b2baedd7c6b5032c879c9c27f4ee8f06fc562b07e2f3837ff9--
```

**Versions**
```bash
~ ❯ eksctl info
eksctl version: 0.115.0-dev+0eb05920f.2022-10-03T16:52:29Z
kubectl version: v1.20.4-eks-6b7464
OS: linux
```

**Comment by Himangini** [comment]
thanks for reporting this, we'll aim to resolve this soon.

**Comment by yuxiang-zhang** [comment]
I did some diggings around this issue:

1. Managed nodegroup creation with Bottlerocket AMI and `overrideBootstrapCommand` seems to be supported after issue #3033 was closed. More specifically, a config file that creates a managed nodegroup with 
    1. custom `ami` ID of a Bottlerocket AMI
    2. `overrideBootstrapCommand` in TOML format
2. As of 00f47703e4d8311518507d0f2dff42b59fb3c465, I saw a similar error as discussed here https://github.com/weaveworks/eksctl/issues/5167#issuecomment-1110891641. More specifically: `Error: overrideBootstrapCommand is not supported for Bottlerocket nodegroups (path=nodeGroups[0].overrideBootstrapCommand)` when attempting to use the config file mentioned above. To my understanding, the solution in #5167 did not fix it entirely/correctly, see below. 
3. Now as shown below, these code invalidates the support mentioned in 1. https://github.com/weaveworks/eksctl/blob/7e4a880af51ec842c93660aad951beb3f2004dac/pkg/apis/eksctl.io/v1alpha5/validation.go#L1142-L1156 https://github.com/weaveworks/eksctl/blob/7e4a880af51ec842c93660aad951beb3f2004dac/pkg/apis/eksctl.io/v1alpha5/validation.go#L1196-L1198
    1. Related, a similar code segment for Nodegroup is in https://github.com/weaveworks/eksctl/blob/7e4a880af51ec842c93660aad951beb3f2004dac/pkg/apis/eksctl.io/v1alpha5/validation.go#L819-L826
4. That being said, the problem that caused the issue listed on this page is from the fact that the `amiFamily` is not set in the config file and is then set to a default value `"AmazonLinux2"` in https://github.com/weaveworks/eksctl/blob/7e4a880af51ec842c93660aad951beb3f2004dac/pkg/apis/eksctl.io/v1alpha5/defaults.go#L124. As a result, the logs now outputs 
    `[ℹ]  nodegroup "foo" will use "ami-0b9c77221154d512b" [AmazonLinux2/1.23]`
 regardless of the real `amiFamily` of the custom `ami` (which should be `[Bottlerocket/1.23]` here).
1. I see that in issue #3709, you are supporting Bottlerocket managed nodegroup by setting only `amiFamily` to `Bottlerocket`.  

I think the fix needs to include:
1. setting `amiFamily` to `Bottlerocket` in the config file mentioned in 1 (does this have to be done manually?)
2. and remove the unsupported error as mentioned in 2 and 3.
