### ISSUE TITLE
AWS Change to IAM Role Trust Policy Evaluation

### ISSUE THREAD

**Issue by albertschwarzkopf** [weaveworks/eksctl#5766]
Hi all,

AWS will change the following behavior in "IAM Role Trust Policy Evaluation":

https://aws.amazon.com/de/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/

Nodegroups and their iam roles which are created with eksctl, are impacted by this change. 

Is it planned to implement the changes in eksctl in next releases?

**Comment by TiberiuGC** [comment]
Hi @albertschwarzkopf , thanks for bringing this to our attention! Since you seem to have a good understanding of this change, could your perhaps write up a _practical_, as _detailed_ as possible, example where we'd be impacted? 
Just to help me wrap my head around the topic 🙇‍♂️ .
