### ISSUE TITLE
[Bug] latest image tag is for prerelease candidate

### ISSUE THREAD

**Issue by josh-ferrell** [weaveworks/eksctl#5773]
### What were you trying to accomplish?

Using `eksctl` as a wrapper for running the binary in a container. Command below is missing some of the additional flags I use.
`docker run --rm -v $HOME/.aws:/root/.aws:Z -v $HOME/.kube:/root/.kube:Z weaveworks/eksctl:latest $@`

### What happened?

Version in container image with latest tag is prerelease candidate instead of latest release in repo

### How to reproduce it?

Pull weaveworks/eksctl:latest, run eksctl within container.

**Logs**

**Anything else we need to know?**

This may be by design but is unexpected as latest release for repository is 0.114.0

**Versions**

```
$ eksctl info
```
eksctl version: 0.115.0-dev+2e9feac.2022-10-07T12:15:53Z
kubectl version: v1.25.0
OS: linux

**Comment by TiberiuGC** [comment]
Hi @josh-ferrell! This is indeed the designed/intended behaviour, as per our docs [here](https://github.com/weaveworks/eksctl#docker). You can always workaround this by checking the latest release and pulling specifically that version.
