### ISSUE TITLE
[Bug] eksctl fails to create cluster Operation Error:  GetCallerIdentity

### ISSUE THREAD

**Issue by kart2** [weaveworks/eksctl#5779]
### What were you trying to accomplish?
eksctl create cluster

### What happened?
Error: checking AWS STS access – cannot get role ARN for current session: operation error STS: GetCallerIdentity, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: i/o timeout

**Anything else we need to know?**
Linux
Downloaded binary.
Named profile

**Versions**
eksctl version: 0.114.0
kubectl version: v1.20.0
OS: linux

**Comment by TiberiuGC** [comment]
Hey @kart2. Could you please run `aws sts get-caller-identity` and see whether the output looks correct?

**Comment by tarunaryan0707** [comment]
If you are seeing below issue during the eksctl cluster creation:

**Error: checking AWS STS access – cannot get role ARN for current session: operation error STS: GetCallerIdentity, get identity: get credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed**

Use below command to verify if access and secret keys are configured properly with appropriate roles.

[root@ip-x.x.x.x]# aws sts get-caller-identity
**Unable to locate credentials. You can configure credentials by running "aws configure".**

Correct output of the above command shows below information with format:

[root@ip-x.x.x.x]# aws sts get-caller-identity
{
    "UserId": "yyyyyyyyyyyy",
    "Account": "xxxxxxxxxxxxx",
    "Arn": "arn:aws:iam::zzzzzzzzzz:root"
}

**Comment by yp05327** [comment]
I got the same error and the output of `aws sts get-caller-identity` is correct. So what's the problem?

<img width="1695" height="366" alt="Image" src="https://github.com/user-attachments/assets/a72d1cca-38a0-43d3-9215-bccbc60e2281" />
