### ISSUE TITLE
OverrideBootstrapcommand for Windows not working on latest eksctl version 0.115

### ISSUE THREAD

**Issue by jayaragnair** [weaveworks/eksctl#5809]
When using custom windows AMI for my EKS nodegroup, im specifying the amifamily and ami id - because only then, the nodes are joining cluster. But the latest eksctl version throws the below error:

Error: could not create cluster provider from options: overrideBootstrapCommand is not supported for WindowsServer2019FullContainer nodegroups (path=nodeGroups[0].overrideBootstrapCommand

I tried with my older eksctl version 0.97, and it is working.

How can i pass user data as bootstrap command for WindowsServer2019FullContainer EKS worker nodes?.

**Comment by shavichacon** [comment]
Any update of this?

**Comment by shavichacon** [comment]
Version eksctl 0.120.0 has same issue

**Comment by itshili** [comment]
Issue not addressed yet, why is it closed?
