### ISSUE TITLE
[Help] eksctl returned AccesDenied

### ISSUE THREAD

**Issue by computerphilosopher** [weaveworks/eksctl#5831]
### What help do you need?

I want to install 'Amazon VPC CNI plugin for Kubernetes' to my eks cluster.

But I get 'AccessDenied Exception' when I run the following command. 

```sh
eksctl create iamserviceaccount \
    --name aws-node \
    --namespace kube-system \
    --cluster rum-eks-cluster \
    --role-name "AmazonEKSVPCCNIRole" \
    --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy \
    --override-existing-serviceaccounts \
    --approve \
```

```sh
2022-10-25 10:51:50 [▶]  role ARN for the current session is "arn:aws:iam::xxxxxxxxxxx:user/me"
Error: unable to describe cluster control plane: operation error EKS: DescribeCluster, https response error StatusCode: 403, RequestID: 8e10d6df-356f-4831-8cd4-7eb14d19e849, api error AccessDeniedException: User: arn:aws:iam::xxxxxxxxxxxuser/me is not authorized to perform: eks:DescribeCluster on resource: arn:aws:eks:ap-northeast-2:xxxxxxxxxxx:cluster/my-cluster with an explicit deny
```
The error message says I'm not authorized to perform 'eks: DescribeCluster'. But my IAM user has a full EKS permission. 

<img width="2601" alt="image" src="https://user-images.githubusercontent.com/26251856/197664781-c6cf17be-0e16-426b-877a-16da0d8c8aec.png">

**Comment by cPu1** [comment]
@computerphilosopher, is this resolved? If not, can you verify that the same API call works with the AWS CLI, by running `aws eks describe-cluster`. I'd also recommend using the latest version of eksctl as a similar issue was fixed recently.
