### ISSUE TITLE
Can't choose cloudformation stack name

### ISSUE THREAD

**Issue by Afikoman** [weaveworks/eksctl#5836]
When using 'eksctl create iamserviceaccount'  to create AWS role and eks service account,it triggers a creation of a clooudformation stack with the name "eksctl-<Cluster_Name>-addon-iamserviceaccount-<Namespace>-<RoleName>".
It all works fine on the first time. However, since I we can't choose the cloudformation stack name, if I delete the cluster and create a new cluster with the same name, when I'm trying to run the 'eks create iamserviceaccount' command again, it's not creating the serviceaccount on the cluster (or the role if I deleted it manually) although it doesn't exists.
Choosing the cloudformation name will allow us to re-create the eks cluster and re-run the eksctl commnad, while we'll be able to change the cloudformation stack name which will trigger the creation of the AWS role / EKS serviceaccount as expected.

**Comment by blorby** [comment]
bummer
