### ISSUE TITLE
Ensure all relevant launch template properties are being set during managed node group creation.

### ISSUE THREAD

**Issue by oleg-ku-32768** [weaveworks/eksctl#5844]
eksctl does create LT for MN and it's a really nice.
And it's somewhat useless, IMO...

How to I tell eksctl to place certain setting into template, such as **Instance Type** (IT) for example?
If it's not set in during initial create MN operation (with creating LT behind the scene), it's won't be possible to change IT later via LT version change.
The will be error like:
**"You must continue to not specify an instance type within the launch template"** :disappointed:

**Comment by TiberiuGC** [comment]
Hey @oleg-ku-32768 , could you please help me out with a some more details on the issue? Perhaps:

- what eksctl command are you talking about, where/when is the LT being created? How does eksctl create a LT? (apologies if this one is obvious, but I am fairly new into the project)
- an example of a command achieving the functionality you would like to see present.

**Comment by TiberiuGC** [comment]
@oleg-ku-32768 cheers!
 
So, essentially, these properties you're looking to have configured for the LT (e.g. `instanceType` and `volumeSize`), these can be specified at the `managedNodeGroup` level and should be picked up from there automatically. e.g.
```
managedNodeGroups:
    ...
    - name: ng-2-builders
      instanceType: m5.2xlarge
      volumeSize: 100
```

Now the created LT should have these set. By looking through the code I can confirm that `volumeSize` should work. While `instanceType` seems to have been omitted.

Can I please ask you, have you noticed other important properties missing from the LTs that are created during `eksctl create nodegroup`? Or are there other missing properties/fields in particular that you would want to see populated within the LT?

After I have a clear picture of what fields you are looking for I can double check the code and see which are already being picked up from the `managedNodeGroup` and which have been omitted.

**Comment by TiberiuGC** [comment]
> These are settable in LT:
> 
> 1. AMI ID
> 2. Instance type
> 3. Availability Zone
> 4. Key pair name
> 5. Security groups / Security group IDs: **set already, not sure, if they can be customized...**
> 6. Resource tags: Same as Security groups
> 7. Advanced details/User data: definitely needed for custom AMI

Cool, thanks a lot for these! I'll look into them individually and see which is already working and which can be supported if not.
