### ISSUE TITLE
[Bug] EKSCTL unable to update version of EKS, role does not exist or trusted entity invalid

### ISSUE THREAD

**Issue by AndrewFarley** [weaveworks/eksctl#5853]
### What were you trying to accomplish?
I recently (3 months ago) spun up a EKS 1.22 cluster with a then-updated version of EKSCTL, and now I'd like to upgrade to 1.23, but am getting errors when doing so.  I've googled around, tried various suggestions about changing role permissions, trust, etc, all to no avail.  There has been no manual edits made to anything in this account this is a clean/fresh account being done with 100% Infrastructure-as-code, so the entire pipeline of events, roles, etc on this account was created by EKSCTL (and Terraform), and thus I think it may be the responsibility of EKSCTL here. However, it could just be an AWS issue that I need to open to support against for just "random noise/weirdness".

### What happened?
When trying to upgrade I get this error..
```bash
$ eksctl upgrade cluster --name shared --version 1.23 --approve
2022-11-01 17:15:46 [ℹ]  will upgrade cluster "shared" control plane from current version "1.22" to "1.23"
Error: operation error EKS: UpdateClusterVersion, https response error StatusCode: 400, RequestID: 8cf7a3f4-4140-42ec-b1ec-a88c465817ff, InvalidRequestException: Role with arn: arn:aws:iam::219854650562:role/eksctl-shared-cluster-ServiceRole-19JYXQRJ447AV, could not be assumed because it does not exist or the trusted entity is not correct
```

This also happens on the AWS Portal...
<img width="1160" alt="Screen Shot 2022-11-01 at 5 15 11 PM" src="https://user-images.githubusercontent.com/470163/199157773-ed805b08-737c-40a4-b26a-fe8dfd41fb28.png">

For your reference here's the things you might want/need...

The role which I confirm is properly named, and has the proper permissions on it (as many of my other AWS accounts and clusters that I manage have)
<img width="732" alt="Screen Shot 2022-11-01 at 5 15 25 PM" src="https://user-images.githubusercontent.com/470163/199157877-f0754e6e-4014-49d2-bb6d-688b91b4211b.png">

And the trust is here, which looks good...
<img width="584" alt="Screen Shot 2022-11-01 at 5 27 09 PM" src="https://user-images.githubusercontent.com/470163/199158635-1acaae0f-b7e0-4e1a-b2fe-9cdc13fadc43.png">

My EKSCTL Configuration file is here
https://gist.github.com/AndrewFarley/c33f2e266736245029d231d1d2103f81

My Cloudformation stacks it created look great, and are here...
<img width="1210" alt="Screen Shot 2022-11-01 at 5 25 27 PM" src="https://user-images.githubusercontent.com/470163/199158456-2b7286c9-c039-4901-b255-ae846d91f5fd.png">

What OS are you using?
Mac OS-X, with EKSCTL from homebrew

```bash
$ eksctl info
eksctl version: 0.116.0-dev+9db3d29ea.2022-10-28T12:53:00Z
kubectl version: v1.22.2
OS: darwin
```

Any ideas?

**Comment by TiberiuGC** [comment]
Hi @AndrewFarley - just a long shot, but have you tried adding `AmazonEKSServicePolicy` to your role?

**Comment by TiberiuGC** [comment]
I've tried creating a cluster on 1.22 with a service role with same permissions/policies and upgrading to 1.23 worked just fine. 🤔

**Comment by AndrewFarley** [comment]
@TiberiuGC I did try adding that.  I saw some tutorials that said to add that, to no avail.  :(  Thanks for the idea though!

**Comment by TiberiuGC** [comment]
I've removed the label bug as I could not reproduce this on latest build.

**Comment by bakeemawaytoys** [comment]
I have run into this issue too.  There is an issue on the AWS Containers Road map project that seems to be related:
aws/containers-roadmap#1533.

**Comment by bakeemawaytoys** [comment]
I ran into this issue as well when trying to upgrade a cluster from 1.21 to 1.22.  Adding the AmazonEKSServicePolicy policy to the cluster's role fixed it for me.

**Comment by AndrewFarley** [comment]
@bakeemawaytoys This is totally the issue we are encountering, we're using a custom KMS key.  I guess the problem technically doesn't lie in EKSCTL however, so I will close this bug.  Thanks for that, and hope anyone else that runs into this please see this issue for the fix for this...

https://github.com/aws/containers-roadmap/issues/1533#issuecomment-1099143480
