### ISSUE TITLE
[Bug]  Can not create Self Managed nodegroup using EKSCTL 0.116.0

### ISSUE THREAD

**Issue by kakarotbyte** [weaveworks/eksctl#5858]
I am not able to create self managed nodes using eksctl. It tried to create Managed node group.
```bash
cat config-cluster.yaml


apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-2
  region: us-east-1
nodeGroups:
  - name: new-subnet-nodegroup
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # use existing EC2 key
      publicKeyName: xyz
    ami: ami-xyz
```

output looks as following.

```bash
eksctl create nodegroup  --profile=eks2 --config-file=config-cluster.yaml
Error: could not create cluster provider from options: nodeGroups[0].overrideBootstrapCommand is required when using a custom AMI (nodeGroups[0].ami)
```

**Comment by cPu1** [comment]
It didn't try to create a managed nodegroup. As the error states, you need to provide an `overrideBootstrapCommand` when using a custom AMI. This is a relatively new behaviour and is documented in [Nodegroup Bootstrap Override For Custom AMIs](https://eksctl.io/announcements/nodegroup-override-announcement/).

**Comment by kakarotbyte** [comment]
> It didn't try to create a managed nodegroup. As the error states, you need to provide an `overrideBootstrapCommand` when using a custom AMI. This is a relatively new behaviour and is documented in [Nodegroup Bootstrap Override For Custom AMIs](https://eksctl.io/announcements/nodegroup-override-announcement/).
> 
> I've removed the bug label as this is the expected behaviour.

@cPu1 I still believe that this is a unaccepted behavior as in the past when I used CLI or config as above I always didnt need to use `overrideBootstrapCommand`.  Also this is for **Self Managed nodes** please refer the flag `--managed=false`. 

```
eksctl create nodegroup --cluster=cluster-2 --name=al-nodes --ssh-access --managed=false --ssh-public-key=xyz --name=test-2 --node-type=m5.large --node-ami=ami-xyz --region=us-east-1
```

**Comment by cPu1** [comment]
>@cPu1 I still believe that this is a unaccepted behavior as in the past when I used CLI or config as above I always didnt need to use overrideBootstrapCommand.

@kakarotbyte, I understand this may be undesirable for some users but it is a breaking change in eksctl, documented in https://eksctl.io/announcements/nodegroup-override-announcement/. We arrived at this decision after some consideration. 

If you're using an AMI based off Amazon EKS optimized Amazon Linux, you just need to add an `overrideBootstrapCommand` in your config file, as in:

```yaml
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
      /etc/eks/bootstrap.sh ${CLUSTER_NAME} --container-runtime containerd --kubelet-extra-args "--node-labels=${NODE_LABELS}"
```

As for the CLI variant, I'm afraid there's no way to create a nodegroup with a custom AMI as there's no CLI counterpart for `overrideBootstrapCommand` and we have no plans of adding it. I'd suggest using a config file to address this issue.

**Comment by cPu1** [comment]
@kakarotbyte please feel free to open a new issue if you have more questions.
