### ISSUE TITLE
EKSCTL Failing with  AWS STS access – cannot get role ARN for current session: operation error STS: GetCallerIdentity in MACOS

### ISSUE THREAD

**Issue by AnkitBhalla22** [weaveworks/eksctl#5869]
Hi Team,

I trying to use eksctl cli to get and create cluster but when ever i try to get/create cluster the cli fails with following error:

AWS_PROFILE=dev eksctl get clusters --verbose=4
Error: checking AWS STS access – cannot get role ARN for current session: operation error STS: GetCallerIdentity, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.us-west-2.amazonaws.com/": dial tcp: lookup sts.us-west-2.amazonaws.com on 127.0.0.1:53: read udp 127.0.0.1:0->127.0.0.1:53: i/o timeout

My aws is setup properly and command: 
aws sts get-caller-identity --profile dev    
{
    "UserId": "********:ankit",
    "Account": "**********",
    "Arn": "arn:aws:sts::******:assumed-role/dev/ankit"
}
This works fine and even i get cluster list via aws cli works fine.

I have tried exporting the aws access_key , secret_key and token but still same issue.

Can someone point what can be the issue

**Comment by TiberiuGC** [comment]
Hi @AnkitBhalla22 - I'm afraid it's really difficult for me to tell what went wrong, as I can't reproduce the issue. I've tried looking for online solutions and people having similar issues usually figure out that they have certain applications interfering with their network traffic. Things like VPNs, proxy servers, etc ..
