### ISSUE TITLE
Feature Request: eksctl validate cluster 

### ISSUE THREAD

**Issue by StevenACoffman** [weaveworks/eksctl#587]
Currently, [Kops  will validate a cluster](https://github.com/kubernetes/kops/blob/master/docs/cli/kops_validate_cluster.md) and aid troubleshooting and it would be nice if eksctl provided similar functionality for EKS. It's possible we could borrow some of their code even.

### Synopsis

This commands validates the following components: 

  1. All k8s masters are running and have "Ready" status. [ Not applicable ]  
  2. All k8s nodes are running and have "Ready" status.  
  3. Component status returns healthy for all components.  
  4. All pods in the kube-system namespace are running and healthy.

```
kops validate cluster [flags]
```

### Syntax

```
  # Validate a cluster.
  # This command uses the currently selected kops cluster as
  # set by the kubectl config.
  kops validate cluster
```

### Options

```
  -h, --help            help for cluster
  -o, --output string   Output format. One of json|yaml|table. (default "table")
```

### Example
```
$ kops validate cluster --state s3://operations.foo.bar
Using cluster from kubectl context: kubernetes.foo.bar

Validating cluster kubernetes.edge.aworks.us

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-us-east-1b	Master	t2.medium	1	1	us-east-1b
master-us-east-1c	Master	t2.medium	1	1	us-east-1c
master-us-east-1d	Master	t2.medium	1	1	us-east-1d
nodes			Node	t2.medium	2	2	us-east-1b,us-east-1c,us-east-1d,us-east-1e

NODE STATUS
NAME	ROLE	READY

VALIDATION ERRORS
KIND	NAME			MESSAGE
Machine	i-00c6a0621a5d8cb27	machine "i-00c6a0621a5d8cb27" has not yet joined cluster
Machine	i-083789489a702bc52	machine "i-083789489a702bc52" has not yet joined cluster
Machine	i-087baaf52f370f95f	machine "i-087baaf52f370f95f" has not yet joined cluster
Machine	i-0b8fd5008e3e11d58	machine "i-0b8fd5008e3e11d58" has not yet joined cluster
Machine	i-0db4c6b21240085fe	machine "i-0db4c6b21240085fe" has not yet joined cluster

Validation Failed
```

**Comment by errordeveloper** [comment]
Thanks for bringing this up, I thought there was an old issue for this, but cannot find it now (maybe it was a TODO comment or something). I think it's a great idea, and 'machine not joined yet' could be of use for sure. I think #484 is related to this.

**Comment by errordeveloper** [comment]
I believe that #642 will help with this a lot. We might provide this is a part of `eksctl get`, but we will see how it goes. Additionally to config validation, I think functional tests would be nice also, we can leverage some of the same tests we use in the integration test suite.

**Comment by errordeveloper** [comment]
Old umbrella issue that was meant to cover this is #155.

**Comment by StevenACoffman** [comment]
Still an issue.
