### ISSUE TITLE
is "preBootstrapCommand" option working? 

### ISSUE THREAD

**Issue by StephenWangasg** [weaveworks/eksctl#588]
**What happened?**
I create cluster with a configuration file (refer to example https://github.com/weaveworks/eksctl/blob/master/examples/05-advanced-nodegroups.yaml)

The example used

>  preBootsrapCommands:
>       # allow docker registries to be deployed as cluster service 
>       - 'echo {\"insecure-registries\": [\"172.20.0.0/16\",\"10.100.0.0/16\"]} > /etc/docker/daemon.json'
>       - "systemctl restart docker"

However I used it does not work with ubuntu1804 AMI.

Later i found the option name in the example **preBootsrapCommands** is not the same as registered in the code pkg/apis/eksctl.io/vlalpha4/types.go

>	PreBootstrapCommands []string `json:"preBootstrapCommand,omitempty"`

So I changed the option name in my configuration file to `preBootstrapCommand`. However still not working. 

Logs are not found in /var/log/ in the EC2 related to PreBootstrapCommands

**Versions**
Please paste in the output of these commands:
```
$ eksctl version

[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.22"}

$ uname -a

Linux AIQ-Te 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by StephenWangasg** [comment]
The problem is resolved by updating eksctl to latest 0.1.23

**Comment by rade** [comment]
@errordeveloper Surely the typo in the example yaml needs fixing. I guess that's a separate issue though.

**Comment by errordeveloper** [comment]
I've updated the examples in ff940df0 and opened #591.
