### ISSUE TITLE
[Help] How to specify the cpu architecture when working with instanceType in eksctl managedNodeGroups

### ISSUE THREAD

**Issue by swananddhole** [weaveworks/eksctl#5886]
I'm creating a eks cluster using eksctl config schema with managedNodeGroups in which I'm selecting instanceType and amiFamily. Along with this I want to specify the cpu architecture also(x86_64, amd64, arm64 etc), but I don't see any way to specify it.(Maybe It's there and I'm missing it completely). I'm aware that this is possible with instanceSelector, but I don't want to use instanceSelector.
Can anyone help me out here?
Thanks

**Comment by Himangini** [comment]
@swananddhole AWS allows you to provision a variety of instance types, which provide different combinations of CPU, memory, disk, and networking. For more information about CPUs and memory options available please visit [Amazon EC2 Instance Types documentation](https://aws.amazon.com/ec2/instance-types/)
