### ISSUE TITLE
[Bug] creating cluster with --without-nodegroups and aws-ebs-csi-driver addon fails

### ISSUE THREAD

**Issue by Fantaztig** [weaveworks/eksctl#5891]
### What were you trying to accomplish?
Hi, I wanted to create a cluster with no nodegroups (managed nodegroups are defined in the config though) and the aws-ebs-csi-driver addon.
We want to create the cluster without nodes as we need to roll out calico and remove the aws-node deployment.

### What happened?
The cluster create failed with status degraded, unfortunately I don't have the exact logs anymore.

### How to reproduce it?
Create cluster using a config file containing a managed nodegroup and the aws-ebs-csi-driver addon.
Run eksctl create cluster -f config.yaml --without-nodegroups.

**Anything else we need to know?**
Using eksctl on macOS Monterey, downloaded through brew.
AWS Credentials are managed by aws-vault.

I found https://github.com/weaveworks/eksctl/pull/4629 and was wondering if maybe the check doesn't recognize the --without-nodegroups flag?

After creating the nodegroups the addon works as expected, the major issue for us is that some of the finalizing steps such as making the cluster endpoint private only are missing.

**Versions**
```
❯ eksctl info
eksctl version: 0.117.0-dev+98027776c.2022-11-04T12:59:49Z
kubectl version: v1.21.0+vmware.1-wcp
OS: darwin
```

**Comment by Himangini** [comment]
@Fantaztig can you share the config file used?
