### ISSUE TITLE
[Feature] Support Trn1 Instance Types

### ISSUE THREAD

**Issue by dewjam** [weaveworks/eksctl#5896]
### What feature/behavior/change do you want?

Eksctl currenly launches Trn1 instances types on the EKS Optimized AMI when it should launch using the "Accelerated AMI".  Additionally, Trn1 instances require the Neuron Device Plugin DaemonSet.  

eksctl should automatically discover the correct AMI for Trn1 instances and automatically install the Neuron Device Plugin when creating new clusters (similar to Inf1 instances).

### Why do you want this feature?

Trn1 ([Trainium](https://aws.amazon.com/ec2/instance-types/trn1/)) instance types are now publicly available, but they are difficult to deploy properly via eksctl.  This is mostly due to eksctl resolving to Optimized AMI instead of to the Accelerated AMI.  I want to streamline the deployment of EKS clusters with Trn1 instances, similar to how it's done with Inf1 instance types.

**Comment by dewjam** [comment]
I'm testing a fix for this now.  Hopefully a PR will be incoming today.

**Comment by dewjam** [comment]
I would really like to get this into the v0.118.0 release that is currently in rc.  Any thoughts as to whether that's possible?  (Assuming I produce a PR today?)

**Comment by Himangini** [comment]
Closed by https://github.com/weaveworks/eksctl/pull/5906
