### ISSUE TITLE
[Bug] local eksctl build panics after dependency update

### ISSUE THREAD

**Issue by dewjam** [weaveworks/eksctl#5897]
### What were you trying to accomplish?

I was attempting to build eksctl from source and test out some changes I made locally.

### What happened?

The build completes successfully, but attempting to run the eksctl binary results in a panic.

### How to reproduce it?

* Pull down the [most recent commit](https://github.com/weaveworks/eksctl/commit/acdd9baee23206496a328e61142e3d291b143c06) from the main branch
* Run `make build`
* Try to run the resulting eksctl binary:  `./eksctl`

**Logs**

```
./eksctl
panic: duplicate metrics collector registration attempted

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0001e0620?, {0xc00062cce0?, 0x1, 0x40d7bf?})
	/home/dewaard/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:403 +0x7f
k8s.io/component-base/metrics.(*kubeRegistry).MustRegister(0xc0001e0620, {0xc00062ccd0, 0x1, 0x7f6643004101?})
	/home/dewaard/go/pkg/mod/k8s.io/component-base@v0.23.12/metrics/registry.go:176 +0x88
k8s.io/legacy-cloud-providers/aws.registerMetrics.func1()
	/home/dewaard/go/pkg/mod/k8s.io/legacy-cloud-providers@v0.23.12/aws/aws_metrics.go:71 +0x62
sync.(*Once).doSlow(0xc0005bbe60?, 0xc000bff970?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
k8s.io/legacy-cloud-providers/aws.registerMetrics()
	/home/dewaard/go/pkg/mod/k8s.io/legacy-cloud-providers@v0.23.12/aws/aws_metrics.go:70 +0x31
k8s.io/legacy-cloud-providers/aws.init.0()
	/home/dewaard/go/pkg/mod/k8s.io/legacy-cloud-providers@v0.23.12/aws/aws.go:1180 +0x19
```
**Anything else we need to know?**

AL2

**Versions**

```
$ eksctl info
```
NA, fails due to panic

**Comment by dewjam** [comment]
I believe this was issue introduced in https://github.com/weaveworks/eksctl/commit/3b02914a7e05fb9ae4a88a322b67c64b1f2909b4

Checking out code from a prior commit seems to run as expected.

**Comment by cPu1** [comment]
Thanks for the detailed issue, @dewjam. This was also caught by our integration tests. A [PR](https://github.com/weaveworks/eksctl/pull/5899) has been opened with a fix. I'm removing the bug label as it's on `main` and not  in a release.
