### ISSUE TITLE
`preBootsrapCommand` should be renamed to `preBootsrapCommands`

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#591]
A typo in field name made it to 0.1.23 release, we will need to fix this as part of v1alpha5 changes. We might need to consider config fixer utility that at least can detect unknown fields or otherwise we must document API changes thoroughly.

**Comment by StevenACoffman** [comment]
Fixed in#645
I don't believe the problem was anywhere but the documentation.

**Comment by errordeveloper** [comment]
The idea is that is an array, so it should be plural.

**Comment by yanhongwang** [comment]
Hello @StevenACoffman , @errordeveloper 

But preBootsrapCommands of yaml definition can be converted to command line?
Is there any flag possible to implement preBootsrapCommands?

eksctl create nodegroup

Thanks.
