### ISSUE TITLE
Keep getting Error: unmarshalling "mapAccounts"

### ISSUE THREAD

**Issue by agitkid** [weaveworks/eksctl#5928]
I'm trying to use eksctl and "iamidentitymapping", but I keep getting the unmarshalling error:

% eksctl get iamidentitymapping --cluster our_cluster --region=us-east-1
Error: unmarshalling "mapAccounts": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go value of type string

% eksctl create iamidentitymapping --cluster our_cluster --arn our_arn_for_iam_role --username user
Error: unmarshalling "mapAccounts": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go value of type string

I read somewhere this is a result of a poorly formatted aws-auth configmap. I tested the yaml in the configmap numerous times, and the yaml passes linting.

% eksctl version
0.118.0

Any ideas what's going on? TY

**Comment by cPu1** [comment]
It looks like the `mapAccounts` field in your `aws-auth` ConfigMap is not in the right format. It should be a list of strings but your config appears to contain a list of objects. Can you post the value of the `mapAccounts` field, redacting any sensitive information?

**Comment by agitkid** [comment]
cPu1,

Thanks for your reply! Your question made me go back and look closer at the format required for mapAccounts. And that was the problem. I had this:

mapAccounts: |
  - default: 123456789123

And fixed it with this:

  - "123456789123"

Thanks. Fixed now
