### ISSUE TITLE
How to add shared security group to existing old working node

### ISSUE THREAD

**Issue by anasirvent** [weaveworks/eksctl#597]
Hello, 

I'm trying to update the worker node group in a cluster created with an old version of eksctl by creating a new one and then delete the old one.

I managed to create a new worker node updating the cluster to add the shared security group, however at the end of creation it throws the following error.

```
found 1 nodegroup(s) (0) without shared security group, cluster networking maybe be broken
it’s recommended to create new nodegroups, then delete old ones
as a temporary fix, you can patch the configuration and add each of these nodegroup(s) to “sg-xxxxxxxxxx”
```

Is there any way to add the shared security group to the old worker node group? The cluster was created without a config file.
Downtime is not an issue, but I can't lose any data from the statefulsets on the old worker node.

**Comment by errordeveloper** [comment]
Could you please post the output of `eksctl utils describe-stacks`?

**Comment by anasirvent** [comment]
Hello, 
These are the outputs of my stacks. I've masked some values.
Also I deleted the new worker node I created yesterday until I can figure out how to add the security group to the old one.

[ℹ]  stack/eksctl-myekscluster-nodegroup-0 = {
  Capabilities: ["CAPABILITY_IAM"],
  CreationTime: 2018-12-05 10:32:47.944 +0000 UTC,
  Description: "EKS nodes (AMI family: AmazonLinux2, SSH access: false, subnet topology: Public) [created and managed by eksctl]",
  DisableRollback: false,
  EnableTerminationProtection: false,
  Outputs: [{
      ExportName: "eksctl-myekscluster-nodegroup-0::InstanceRoleARN",
      OutputKey: "InstanceRoleARN",
      OutputValue: "arn:aws:iam::<account_id>:role/eksctl-myekscluster-nodegroup-0-NodeInstanceRole-1MTDTJYWF3V3M"
    }],
  RollbackConfiguration: {

  },
  StackId: "arn:aws:cloudformation:eu-west-1:<account_id>:stack/eksctl-myekscluster-nodegroup-0/1c0040b0-f879-11e8-a107-50a6863366c5",
  StackName: "eksctl-myekscluster-nodegroup-0",
  StackStatus: "CREATE_COMPLETE",
  Tags: [{
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "myekscluster"
    },{
      Key: "eksctl.cluster.k8s.io/v1alpha1/nodegroup-id",
      Value: "0"
    }]
}
[ℹ]  stack/eksctl-myekscluster-cluster = {
  Capabilities: ["CAPABILITY_IAM"],
  ChangeSetId: "arn:aws:cloudformation:eu-west-1:<account_id>:changeSet/eksctl-update-cluster-1551368023/0f307074-67aa-4a91-a2a4-386bcd11f376",
  CreationTime: 2018-12-05 10:22:02.626 +0000 UTC,
  Description: "EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by eksctl]",
  DisableRollback: false,
  EnableTerminationProtection: false,
  LastUpdatedTime: 2019-02-28 15:34:02.98 +0000 UTC,
  Outputs: [
    {
      ExportName: "eksctl-myekscluster-cluster::SubnetsPrivate",
      OutputKey: "SubnetsPrivate",
      OutputValue: "subnet-07749db7c8389bd48,subnet-0f65e3aa4296ad074,subnet-0c72ae2461e685466"
    },
    {
      ExportName: "eksctl-myekscluster-cluster::SubnetsPublic",
      OutputKey: "SubnetsPublic",
      OutputValue: "subnet-0449e877f7208e64b,subnet-0a807cf29bc6388ce,subnet-02e48a032cb2e2d2c"
    },
    {
      ExportName: "eksctl-myekscluster-cluster::ServiceRoleARN",
      OutputKey: "ServiceRoleARN",
      OutputValue: "arn:aws:iam::<account_id>:role/eksctl-myekscluster-cluster-ServiceRole-1C5LAVIG3JE2Y"
    },
    {
      ExportName: "eksctl-myekscluster-cluster::Endpoint",
      OutputKey: "Endpoint",
      OutputValue: "https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.sk1.eu-west-1.eks.amazonaws.com"
    },
    {
      ExportName: "eksctl-myekscluster-cluster::SharedNodeSecurityGroup",
      OutputKey: "SharedNodeSecurityGroup",
      OutputValue: "sg-0c12859f317d9f08d"
    },
    {
      ExportName: "eksctl-myekscluster-cluster::VPC",
      OutputKey: "VPC",
      OutputValue: "vpc-0b87e190a38cda3b7"
    },
    {
      OutputKey: "ClusterStackName",
      OutputValue: "eksctl-myekscluster-cluster"
    },
    {
      OutputKey: "CertificateAuthorityData",
      OutputValue: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNE1USXdOVEV3TWpreU1Gb1hEVEk0TVRJd01qRXdNamt5TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGd5CjA5UlZtL0VqSWJUdzFoNm5wSXVaNzAvYlAzN1VuU1UyYVFKM24wdnhRU1ZCenM3OXp4MnNJTXpQM2ZyRU1yMjMKenVQQ0R4aGVraVpCdVYyTUh5Z0Y1UTA0ZGhESDRLSEdrSlF5RmJpd01scXM4U09HV1kyRXpuRUxpSFhGcTlZVAo4d1ZHWE8zSXI0YVdOWFh5cE1Zb1pXWGNLMFJqUXEyS2xZR2R4akN5NVZsc1krQm5iYzJhQkluM1IrdnQvWXhQCkppRjRySmN1RkYwRU1lcDV1UDQxNC85Tms3d3FiVTlRQytJc3BWekp0eWFYK2hLVWNnb2VJQm00Vlllc2FKdzAKWlpKZmV6SEtQRnd5MXhYSDVYVkxVWW1DekhPcHIwcVA5Um52K09URSszd280cVZZdFVnVmZUZFhLSEdGdTBXcQo0TVlWZmJVU3QwQUFOOW84dlJNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJdjY5WEVzR1lsZ3BlOWZiR1pEQ2djVHVDbm4KOWxxVEw3cmlkQ0RjeFowSHhDb0F5YThvcEcvZWhHb09Udkkxczg5S0RCNUpsSndTdnp6WFloNmRYZER3UlFycgpmN0ZQOHA1cEdZQjZ4VzRJUWRPRzk1cTllMHZsRktJZE0weFFJSW5LSkk0WWtlc1Ria3VQYjdvWVdHSnV3ZklvCnBCTmw4Z2FQTXJaVG9ZTUlDQmNzd01CMlE0eUpKNGxpQkdNajZlVFlYbVh0anpsUXNGaXlTaHF0aGJmeGg4Y0cKNStzOGRtY2s1Ync4K0JQSDdCVFBncEkzYmlBaG0zbnBHWG91ZmFlQUNGdTN6cGtmNWhvZ3pmWmVoNmpXK3pLWQo4dXdpV2tadFpZT3cwVlFUTTRjSExseUVrSnFYREpCeGVIVGdwRWoxTmRoUnErVHNsRS9vQ2p4dFBKTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    },
    {
      ExportName: "eksctl-myekscluster-cluster::SecurityGroup",
      OutputKey: "SecurityGroup",
      OutputValue: "sg-0bbb3b58dd0e9aa7a"
    },
    {
      ExportName: "eksctl-myekscluster-cluster::ARN",
      OutputKey: "ARN",
      OutputValue: "arn:aws:eks:eu-west-1:<account_id>:cluster/myekscluster"
    }
  ],
  RollbackConfiguration: {

  },
  StackId: "arn:aws:cloudformation:eu-west-1:<account_id>:stack/eksctl-myekscluster-cluster/9b5cd870-f877-11e8-a362-0afa58e29f3e",
  StackName: "eksctl-myekscluster-cluster",
  StackStatus: "UPDATE_COMPLETE",
  Tags: [{
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "myekscluster"
    }]
}

**Comment by errordeveloper** [comment]
You can use either EC2 console or AWS CLI to patch the configuration of the security group that the nodegroup uses. You would want allow inbound traffic from the shared SG on all ports.

**Comment by maciekpapiez** [comment]
@errordeveloper Could you elaborate what the SG rules should be? I'm hitting the same issue - cluster created with a previous `eksctl` version, unable to upgrade it:

```
$ eksctl create nodegroup --cluster=eks-bravo
[ℹ]  using region eu-west-1
[ℹ]  will use version 1.10 for new nodegroup(s) based on control plane version
[ℹ]  nodegroup "ng-98ceeec7" will use "ami-06368da7f495b68e9" [AmazonLinux2/1.10]
[✖]  cluster compatibility check failed: shared node security group missing, to fix this run 'eksctl update cluster --name=eks-bravo --region=eu-west-1'
```
but...
```
$ eksctl update cluster --name=eks-bravo --region=eu-west-1
[ℹ]  using region eu-west-1
[ℹ]  re-building cluster stack "eksctl-eks-bravo-cluster"
[ℹ]  (dry-run) updating stack to add new resources [ClusterSharedNodeSecurityGroup IngressInterNodeGroupSG] and ouputs [ServiceRoleARN SharedNodeSecurityGroup]
[ℹ]  checking security group configuration for all nodegroups
[✖]  found 1 nodegroup(s) (0) without shared security group, cluster networking maybe be broken
[✖]  it's recommended to create new nodegroups, then delete old ones
[ℹ]  cluster "eks-bravo" control plane can be upgraded from current version "1.10" to "1.11"
[!]  no changes were applied, run again with '--dry-run=false' to apply the changes
```

**Comment by errordeveloper** [comment]
@maciekpapiez sorry, missed this... have you managed to get past this somehow? Generally, long term you will need to replace nodegroup when new AMI comes out.

**Comment by maciekpapiez** [comment]
Hi @errordeveloper, yes, I somehow managed to rollout the new version, unfortunately I cannot recall any more how I did it. I recall that I missed though the information about this shared security group - what it is, what it's rules should be?

**Comment by errordeveloper** [comment]
> I recall that I missed though the information about this shared security group - what it is, what it's rules should be?

@maciekpapiez shared SG allow traffic to flow between any pods on all nodes the cluster.

I believe this issue is generally resolved now.

**Comment by patrickleet** [comment]
I'm hitting this now - mine was created with an old version of eksctl as well.

When I describe the stack I don't see `SharedNodeSecurityGroup` in the output

I know it needs to be added to the cloudformation stack as an output, but not sure what it should reference.

**Comment by patrickleet** [comment]
ok I see `eksctl update cluster` adds it! nevermind!
