### ISSUE TITLE
Unable to register a kOps-provisioned cluster

### ISSUE THREAD

**Issue by diversario** [weaveworks/eksctl#5971]
### What were you trying to accomplish?

I would like to register a v1.20 cluster provisioned with kOps in EKS.

### What happened?

```
➜ eksctl register cluster --name cluster.com --provider EC2 -v10
2022-11-23 13:55:41 [▶]  role ARN for the current session is "arn:aws:sts::1111:assumed-role/rolename/username"
Error: error registering cluster: unexpected error calling DescribeCluster
```

### How to reproduce it?

Try to register a non-EKS cluster.

**Logs**

This is the only output:

```
➜ eksctl register cluster --name cluster.com --provider EC2 -v10
2022-11-23 13:55:41 [▶]  role ARN for the current session is "arn:aws:sts::1111:assumed-role/rolename/username"
Error: error registering cluster: unexpected error calling DescribeCluster
```

**Anything else we need to know?**

[This code](https://github.com/weaveworks/eksctl/blob/36b30a9e936c347ffa0a3a154eb33822acdbf5fb/pkg/connector/connector.go#L66-L77) appears to be looking for EKS clusters only, regardless of specified provider. It makes perfect sense that the command would fail when the cluster being registered is not managed by EKS.

**Versions**

```
➜ eksctl info
eksctl version: 0.120.0-dev+906c68159.2022-11-18T18:47:15Z
kubectl version: v1.20.15
OS: darwin
```

**Comment by TiberiuGC** [comment]
Hi @diversario - indeed the `DescribeCluster` command runs against EKS API. However, if you double check the code, it's written in such a way that it expects the command to fail with `ResourceNotFoundException`, in which case tries to register the cluster.

In your case, seems that `DescribeCluster` fails with some other unexpected error. I find it annoying that we don't wrap the actual error and thus we don't get any insights into why the command is actually failing. 

It would be awesome if you could clone the code and make a small change to it, i.e. replace
`errors.New("unexpected error calling DescribeCluster")`
with
`errors.Wrap(err, "unexpected error calling DescribeCluster")`
Then build eksctl locally with this change and run the register command again, see if we understand more about the error you're getting.

If you don't want to pursue these steps, I'm going to open a PR anyways to make the change to that error message. However, you'd have to wait for it to be caught in next release.

**Comment by TiberiuGC** [comment]
PR merged, this will be available later today in the RC.

**Comment by diversario** [comment]
Well, this is interesting:

```
➜ AWS_PROFILE=staging ~/Downloads/eksctl register cluster --name k8s-jfrog.staging.ue1.company-name.io --provider EC2 -v10
2022-12-02 16:30:03 [▶]  role ARN for the current session is "arn:aws:sts::XXXXXXX:assumed-role/AWSReservedSSO_Staging-Admin_91b9ecaf2edc375c/username@company.com"
Error: error registering cluster: unexpected error calling DescribeCluster: operation error EKS: DescribeCluster, https response error StatusCode: 400, RequestID: bf5373ca-cb11-41c0-a146-57ef16d0c495, api error InvalidParameterException: The name parameter contains invalid characters. It should begin with letter or digit and can have any of the following characters: the set of Unicode letters, digits, hyphens and underscores.
```

**Comment by cPu1** [comment]
> Well, this is interesting:
> 
> ```
> ➜ AWS_PROFILE=staging ~/Downloads/eksctl register cluster --name k8s-jfrog.staging.ue1.company-name.io --provider EC2 -v10
> 2022-12-02 16:30:03 [▶]  role ARN for the current session is "arn:aws:sts::XXXXXXX:assumed-role/AWSReservedSSO_Staging-Admin_91b9ecaf2edc375c/username@company.com"
> Error: error registering cluster: unexpected error calling DescribeCluster: operation error EKS: DescribeCluster, https response error StatusCode: 400, RequestID: bf5373ca-cb11-41c0-a146-57ef16d0c495, api error InvalidParameterException: The name parameter contains invalid characters. It should begin with letter or digit and can have any of the following characters: the set of Unicode letters, digits, hyphens and underscores.
> ```

@diversario, as you observed, `cluster.com` is not a valid cluster name. If you retry the operation using a valid cluster name, it should work. I'm removing the bug label as this is the expected behaviour.

**Comment by diversario** [comment]
Err, sorry, do you mean that `--name k8s-jfrog.staging.ue1.company-name.io` is invalid?

**Comment by cPu1** [comment]
> Err, sorry, do you mean that `--name k8s-jfrog.staging.ue1.company-name.io` is invalid?

It is invalid as an EKS cluster name. 

From the EKS console:
>The cluster name should begin with a letter or digit and can have any of the following characters: the set of Unicode letters, digits, hyphens and underscores.

**Comment by diversario** [comment]
> > Err, sorry, do you mean that `--name k8s-jfrog.staging.ue1.company-name.io` is invalid?
> 
> It is invalid as an EKS cluster name.
> 
> From the EKS console:
> 
> > The cluster name should begin with a letter or digit and can have any of the following characters: the set of Unicode letters, digits, hyphens and underscores.

Oooh, derp. Haven't used EKS in a long time so I didn't realize. Thanks for pointing it out!
