### ISSUE TITLE
Update managedNodeGroup subnets

### ISSUE THREAD

**Issue by liad-haber** [weaveworks/eksctl#6002]
After creating a managedNodeGroup we should have the ability to modify the subnets the managedNodeGroup uses. 
eksctl create nodegroup -f cluster.yaml  output suggest the all components are up to date(which is incorrect). 
As of now the only solution I found was deleting and recreating the managedNodeGroups which is very inconvenient. 
![image](https://user-images.githubusercontent.com/94528796/205487079-8eb1d363-5ea5-4e91-ab45-48876843c7a3.png)

**Comment by cPu1** [comment]
I'm closing the issue as this is not a valid feature request. Please feel free to open a new issue if you have more questions.
