### ISSUE TITLE
error handling on deletion should be more robust

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#602]
Just noticed that this is what happens if you try to delete a non-existing cluster
```
[ℹ]  deleting EKS cluster "test-1"
[ℹ]  1 error(s) occurred while deleting nodegroup(s)
[✖]  no eksctl-managed CloudFormation stacks found for "test-1"
[ℹ]  will retry deleting nodegroup
[ℹ]  trying to cleanup dangling network interfaces
[✖]  getting VPC configuration for cluster "test-1": no eksctl-managed CloudFormation stacks found for "test-1"
```
This is harmless, but still needs addressing. We should probably just look for a strategy similar to how kops does it, where a list of resources for deletion is compiled first, that way we can improve handling of legacy stack deletions also.

**Comment by Luke035** [comment]
I have the same error when trying to delete a cluster created through IAM role assumption

Creation 
`eksctl create cluster --profile eksctl-admin --name CLUSTER_NAME --nodes-min=1 --nodes-max=5 --node-type t2.small --node-ami=auto --region=us-east-1 `

Deletion
`eksctl delete cluster --profile eksctl-admin --name ai-test-elastic`

Error log: 
`[ℹ]  deleting EKS cluster "ai-test-elastic"
[ℹ]  1 error(s) occurred while deleting nodegroup(s)
[✖]  no eksctl-managed CloudFormation stacks found for "ai-test-elastic"
[ℹ]  will retry deleting nodegroup
[ℹ]  trying to cleanup dangling network interfaces
[✖]  getting VPC configuration for cluster "ai-test-elastic": no eksctl-managed CloudFormation stacks found for "ai-test-elastic"
`

**Comment by errordeveloper** [comment]
xref #682

**Comment by michaelbeaumont** [comment]
See #2172
