### ISSUE TITLE
[Bug] kube-proxy image version after eksctl upgrade is incorrect causing the kube-proxy to fail

### ISSUE THREAD

**Issue by mukundjalan** [weaveworks/eksctl#6027]
### What were you trying to accomplish?

I was trying to upgrade the eks cluster using the command
`eksctl upgrade cluster --name <cluster-name> --region us-east-1 --version 1.23 --approve`

### What happened?
The cluster was upgraded successfully without any other errors on the console. But the `kube-proxy` image updated in the `kube-proxy` `DaemonSet` was incorrect.

As per the AWS EKS docs here - https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html, the image to be used must have the version `v1.23.8-eksbuild.2` OR `v1.23.13-minimal-eksbuild.2`; whereas the image that was updated in my cluster was `v1.23.13-eksbuild.2`. Seems like the default-type & minimal-type versioning was mix-matched here which caused the container startup to fail due to `ImagePullBackOff` error.

As per the below image extracted from the docs referred above, the issue is only specific to k8s 1.23 because the minor version is different for default & minimal image types. Also, even though not applicable for `1.23`, the eksbuild version is different for default & minimal in few other kubernetes versions. It must also be ensured that, this specific build version must not mis-match.
![image](https://user-images.githubusercontent.com/16172176/206415669-344bcff7-584d-4443-add4-0a1857563141.png)

Although, I see from https://eksctl.io/usage/addon-upgrade/ that the 3 add-ons are added automatically & are available inside the cluster, they are not shown on the eks cluster console or through `eksctl get addons --cluster <cluster-name>` command. As a result, I cannot use the `eksctl utils update-kube-proxy --cluster=<clusterName>` command as well to get this fixed. I had to manually update the image version using kubectl to make the upgrade work.

### How to reproduce it?
Upgrade cluster to version 1.23 using `eksctl upgrade cluster` command

**Logs**
Nothing much relevant that I could see

**Anything else we need to know?**
N/A

**Versions**

```
eksctl version: 0.118.0
kubectl version: v1.20.5
OS: linux
```

**Comment by chickenbeef** [comment]
According to the EKS team, starting from 1.23.13 they will only be publishing minimal versions of the managed addon images.

This will require a change in eksctl as `describe add-ons` API cannot be relied on.

**Comment by kr3cj** [comment]
This is affecting our ability to upgrade our EKS clusters to 1.23 so I opened a support case with AWS. A [workaround exists](https://github.com/weaveworks/eksctl/issues/5972#issuecomment-1326958067) but I'm not super comfortable doing this / for very long `kubectl set image -n kube-system daemonset/kube-proxy kube-proxy=602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/eks/kube-proxy:v1.23.12-eksbuild.1`. It also looks like the [same thing might be happening in 1.24](https://github.com/weaveworks/eksctl/issues/5972#issuecomment-1327006524).

**Comment by nipr-jdoenges** [comment]
Similar issue just hit me today on a 1.21 cluster (yes, we are getting ready to upgrade to 1.22).

We don't have kube-proxy installed as a managed addon (i.e. via `eksctl create addon`), rather we manage it through the separate [default add-on updates](https://eksctl.io/usage/addon-upgrade/) commands, i.e. `eksctl utils update-kube-proxy --cluster=<clusterName>`. We got image pull backoff when the command tried to update to a newer image version that apparently isn't accessible in ecr.

As recently as yesterday, we ran the same command on the same cluster with success, leaving our image version at `602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.21.14-eksbuild.2`.
Only today did the same command try to update the image to `602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.21.14-eksbuild.3`. We are using eksctl 0.115.0.

**Comment by nipr-jdoenges** [comment]
It sounds like based on info from @chickenbeef and issue pointed to by @nhimanshujain that eksctl is opinionated toward using the default version and the discontinuation of publishing new default versions might also apply to recently released patches for pre-1.23 clusters as well?

**Comment by OverStruck** [comment]
Can confirm this issue is re-producible:

- Update control plane from 1.22 to 1.23 - all good
- Update kube-proxy
```
$ eksctl utils update-kube-proxy --cluster=<name> --approve
"kube-proxy" is now up-to-date
```

Pod status: `kube-proxy-g4xgf  0/1 ImagePullBackOff  0 40s`

```
$ k logs kube-proxy-g4xgf -n kube-system
Error from server (BadRequest): container "kube-proxy" in pod "kube-proxy-g4xgf" is waiting to start: image can't be pulled
```

```
$ k describe po kube-proxy-g4xgf -n kube-system
Events:
  Normal   Pulling    73s (x4 over 2m42s)  kubelet            Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.23.13-eksbuild.2 "
  Warning  Failed     72s (x4 over 2m42s)  kubelet            Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.23.13-eksbuild.2 ": rpc error: code = Unknown desc = Error response from daemon: manifest for 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.23.13-eksbuild.2  not found: manifest unknown: Requested image not found
  Warning  Failed     72s (x4 over 2m42s)  kubelet            Error: ErrImagePull
  Warning  Failed     58s (x6 over 2m41s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    45s (x7 over 2m41s)  kubelet            Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.23.13-eksbuild.2 "
```

Upon upgrading kube-proxy tries to use image: `v1.23.13-eksbuild.2` | Should be `v1.23.13-minimal-eksbuild.2` | Missing `minimal` string. Probably gets cut by current kubectl code

from https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html

> If you deployed a version 1.23 and later cluster, the **minimal** image type was deployed with your cluster, by default.

Current workaround works as expected:

`AWS_DEFAULT_REGION=us-west-2
KUBE_PROXY_ADDON_VERSION=v1.23.13-minimal-eksbuild.2
kubectl set image -n kube-system daemonset/kube-proxy kube-proxy=602401143452.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/eks/kube-proxy:${KUBE_PROXY_ADDON_VERSION}`

**Comment by kanor1306** [comment]
Just hit the issue metioned by @nipr-jdoenges with multiple v1.21 clusters. Self managed add on, `eksctl 0.117.0`.

Do we know whether the `eksctl` team is going to look into this or should we start looking into alternatives?

**Comment by cPu1** [comment]
> According to the EKS team, starting from 1.23.13 they will only be publishing minimal versions of the managed addon images.

This change in behaviour has broken the `eksctl utils update-kube-proxy` command because the container image eksctl uses for kube-proxy ends up with an incorrect version. 

>Do we know whether the eksctl team is going to look into this or should we start looking into alternatives?

We are going to prioritise this issue and work on it soon.

**Comment by kanor1306** [comment]
That is great to hear! thank for the response @cPu1

**Comment by nhimanshujain** [comment]
Thank you @cPu1 for acknowledging the issue!!

**Comment by jdn5126** [comment]
@cPu1 I think relying on the `aws eks describe-addon-versions` API is not recommended as the version name will not always be a 1:1 mapping with the image tag. The discrepancy will not always be the lack of `-minimal`. I am sure that eksctl wants to avoid maintaining a static list, so feel free to reach out on k8s slack and we can discuss solutions

**Comment by johnpetersjr** [comment]
Any ETA on a fix for this?  Seems like EKSCTL can no longer be used to maintain EKS nodegroups until this is solved.

**Comment by bitva77** [comment]
> Any ETA on a fix for this? Seems like EKSCTL can no longer be used to maintain EKS nodegroups until this is solved.

I got around this by doing `eksctl create addon` and `update addon` instead

**Comment by johnpetersjr** [comment]
Seems that isn't working for me @bitva77 :

$ eksctl create addon --cluster eksdev-12 --name kube-proxy
2023-01-18 09:19:34 [ℹ]  Kubernetes version "1.21" in use by cluster "eks-cluster"
2023-01-18 09:19:34 [ℹ]  Addon kube-proxy is already present in this cluster, as an EKS managed addon, and won't be re-created
$ eksctl update addon --cluster eks-cluster --name kube-proxy
2023-01-18 09:19:45 [ℹ]  Kubernetes version "1.21" in use by cluster "eks-cluster"
2023-01-18 09:19:46 [ℹ]  no new version provided, preserving existing version: v1.21.14-eksbuild.4
2023-01-18 09:19:46 [ℹ]  updating addon
Error: timed out waiting for addon "kube-proxy" to become active, status: "UPDATE_FAILED"

I spoke with AWS support yesterday, they told me to try and manually add the add-on from the console... but at the end of the day, EKSCTL tool is constantly breaking my kube-proxy daemonset by trying to update it to use the image v1.21.14-eksbuild.4 - and this does not work. I have to keep manually putting it back to v1.21.14-eksbuild.2.

**Comment by thwhk** [comment]
> Seems that isn't working for me @bitva77 :
> 
> ```
> $ eksctl create addon --cluster eks-cluster --name kube-proxy
> 2023-01-18 09:19:34 [ℹ]  Kubernetes version "1.21" in use by cluster "eks-cluster"
> 2023-01-18 09:19:34 [ℹ]  Addon kube-proxy is already present in this cluster, as an EKS managed addon, and won't be re-created
> $ eksctl update addon --cluster eks-cluster --name kube-proxy
> 2023-01-18 09:19:45 [ℹ]  Kubernetes version "1.21" in use by cluster "eks-cluster"
> 2023-01-18 09:19:46 [ℹ]  no new version provided, preserving existing version: v1.21.14-eksbuild.4
> 2023-01-18 09:19:46 [ℹ]  updating addon
> Error: timed out waiting for addon "kube-proxy" to become active, status: "UPDATE_FAILED"
> ```
> 
> I spoke with AWS support yesterday, they told me to try and manually add the add-on from the console... but at the end of the day, EKSCTL tool is constantly breaking my kube-proxy daemonset by trying to update it to use the image v1.21.14-eksbuild.4 - and this does not work. I have to keep manually putting it back to v1.21.14-eksbuild.2.
> 
> This is the error:
> 
> ```
> Events:
>   Type     Reason     Age                From               Message
>   ----     ------     ----               ----               -------
>   Normal   Scheduled  88s                default-scheduler  Successfully assigned kube-system/kube-proxy-4r7tq to ip-10-93-15-5.ec2.internal
>   Normal   Pulling    51s (x3 over 88s)  kubelet            Pulling image "602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.21.14-eksbuild.4"
>   Warning  Failed     50s (x3 over 88s)  kubelet            Failed to pull image "602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.21.14-eksbuild.4": rpc error: code = Unknown desc = Error response from daemon: manifest for 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.21.14-eksbuild.4 not found: manifest unknown: Requested image not found
>   Warning  Failed     50s (x3 over 88s)  kubelet            Error: ErrImagePull
>   Normal   BackOff    13s (x5 over 87s)  kubelet            Back-off pulling image "602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.21.14-eksbuild.4"
>   Warning  Failed     13s (x5 over 87s)  kubelet            Error: ImagePullBackOff
> ```

> eksctl update addon --cluster eks-cluster --name kube-proxy

Try to add `--version v1.21.14-eksbuild.2` in the update command to set the addon's version

**Comment by asrail** [comment]
> Similar issue just hit me today on a 1.21 cluster (yes, we are getting ready to upgrade to 1.22).
> 
> We don't have kube-proxy installed as a managed addon (i.e. via `eksctl create addon`), rather we manage it through the separate [default add-on updates](https://eksctl.io/usage/addon-upgrade/) commands, i.e. `eksctl utils update-kube-proxy --cluster=<clusterName>`. We got image pull backoff when the command tried to update to a newer image version that apparently isn't accessible in ecr.
> 
> As recently as yesterday, we ran the same command on the same cluster with success, leaving our image version at `602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.21.14-eksbuild.2`. Only today did the same command try to update the image to `602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.21.14-eksbuild.3`. We are using eksctl 0.115.0.

Same thing here. An outdated cluster upgraded to 1.21 had kube-proxy image set to v1.21.14-eksbuild.4, while it should have been v1.21.14-eksbuild.2.

**Comment by johnpetersjr** [comment]
So this works from the command line:
```
$ eksctl update addon --cluster eks-cluster --name kube-proxy --version v1.21.14-eksbuild.2 
2023-01-18 10:40:27 [ℹ]  Kubernetes version "1.21" in use by cluster "eks-cluster"
2023-01-18 10:40:28 [ℹ]  new version provided v1.21.14-eksbuild.2
2023-01-18 10:40:28 [ℹ]  updating addon
2023-01-18 10:40:39 [ℹ]  addon "kube-proxy" active
```

But the next time I try to run an *eksctl create nodegroup*, it breaks again and puts it back to the build 4.

Can someone point me to the magic documentation that shows me where in the template config file I can set the addons and version?

I'm trying this, and failing (I added the addons: section, but it seem 'version' is not being respected) :

```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "{{ eks_cluster_name }}"
  region: "us-east-1"

addons:
  - name: kube-proxy
    version: v1.21.14-eksbuild.2

managedNodeGroups:
  - name: nodgroupname
    labels:
      team: teamname
      nodegroup: ngname
      appname: eks-cluster
    launchTemplate:
      id: lt-alaunchtemplate
    iam:
      instanceRoleARN: arn:aws:iam::1111111111111:role/yahyeahyea
    minSize: 5
    desiredCapacity: 5
    maxSize: 20
    privateNetworking: true
```

**Comment by kr3cj** [comment]
> ...the next time I try to run an eksctl create nodegroup, it breaks again

Thanks for the warning @johnpetersjr. For what it's worth and for anyone else wondering about this with a setup similar to ours, I tested creating a new nodegroup in our environment using `eksctl`:
* control plane v1.24
* manually set kube-proxy image to `kube-proxy:v1.24.7-eksbuild.2` beforehand
* managing the kube-proxy addon ourselves with `eksctl utils update-kube-proxy...`

It did not revert the kube-proxy image override and things were fine for us.

**Comment by johnpetersjr** [comment]
> Thanks for the warning @johnpetersjr. For what it's worth and for anyone else wondering about this with a setup similar to ours, I tested creating a new nodegroup in our environment using `eksctl`:

I was hoping that idea would work - create a new nodegroup, and then simply run the update of the addon - but I can't even create the nodegroup using eksctl because kube-proxy won't come up in a good state:

```
2023-01-19 13:57:01 [ℹ]  will use version 1.21 for new nodegroup(s) based on control plane version
2023-01-19 13:57:05 [ℹ]  nodegroup "core-abcdefg" will use "" [AmazonLinux2/1.21]
2023-01-19 13:57:07 [ℹ]  18 existing nodegroup(s) (cde-1673901394,core-1627822822,core-1627917298,core-1629914618,core-1646575220,core-1654434016,core-1656896426,core-1672581618,core-1672581628,core-1672624834,core-1673277475,core-1673279784,core-1673467797,core-1673877743,core-1673897630,core-1673901394,core-1674056525,core-1674077074) will be excluded
2023-01-19 13:57:07 [ℹ]  1 nodegroup (core-abcdefg) was included (based on the include/exclude rules)
2023-01-19 13:57:07 [ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "eks-cluster"
2023-01-19 13:57:07 [ℹ]  
2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "core-abcdefg" } } 
}
2023-01-19 13:57:07 [ℹ]  checking cluster stack for missing resources
2023-01-19 13:57:08 [ℹ]  cluster stack has all required resources
2023-01-19 13:57:09 [ℹ]  building managed nodegroup stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 13:57:10 [ℹ]  deploying stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 13:57:10 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 13:57:40 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 13:58:26 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 13:59:23 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:00:38 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:01:36 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:03:06 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:04:13 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:05:02 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:06:17 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:07:53 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:09:38 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:11:23 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:12:19 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:14:00 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:15:40 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:17:22 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:18:09 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:19:35 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:20:24 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:21:40 [ℹ]  waiting for CloudFormation stack "eksctl-eks-cluster-nodegroup-core-abcdefg"
2023-01-19 14:21:40 [ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
2023-01-19 14:21:40 [ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=us-east-1 --cluster=eks-cluster --name=<name>' for each of the failed nodegroup
2023-01-19 14:21:40 [✖]  exceeded max wait time for StackCreateComplete waiter
```
Is anyone still running 1.21?  Maybe I just need to upgrade to a newer EKS version first?

**Comment by obiordu** [comment]
This is what worked for me:

eksctl utils update-kube-proxy --cluster=${CLUSTER_NAME} --region=${CLOUD_REGION_NAME} --approve

kubectl set image ds kube-proxy kube-proxy=602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:${kube_proxy_valid_image} -n kube-system

https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html

e.g as seen in link above for a cluster upgraded from 1.21 to 1.22, ${kube_proxy_valid_image} = v1.22.11-eksbuild.2

**Comment by pcharlan** [comment]
> We are going to prioritise this issue and work on it soon.

@cPu1, any ETA?  There are workarounds being suggested here, but if a fix to `update-kube-proxy` is imminent then that would be much preferred.  Thank you for your time.

**Comment by cPu1** [comment]
A fix is out in the latest release candidate: https://github.com/weaveworks/eksctl/releases/tag/v0.127.0-rc.0

**Comment by johnpetersjr** [comment]
> A fix is out in the latest release candidate: https://github.com/weaveworks/eksctl/releases/tag/v0.127.0-rc.0

I tested with this version, and it seems to have solved my issue with kube-proxy, thanks!

**Comment by Tarasovych** [comment]
Same issue while upgrading EKS managed node groups to 1.24. I used kube-proxy daemonset restart

**Comment by waynshang** [comment]
try use kubectl set image daemonset.apps/kube-proxy -n kube-system kube-proxy=602401143452.dkr.ecr.ap-southeast-1.amazonaws.com/eks/kube-proxy:v1.23.16-eksbuild.2
