### ISSUE TITLE
New spot allocation strategies still not supported in 0.123.0

### ISSUE THREAD

**Issue by dan-lind** [weaveworks/eksctl#6061]
After upgrading eksctl to the 0.123.0, we expected `spotAllocationStrategy: price-capacity-optimized`since to work since this PR #6038 has been merged.

However we are seeing this error message (which also doesn't reflect the updated error message from the PR)
`Error: spotAllocationStrategy should be one of: lowest-price, capacity-optimized, capacity-optimized-prioritized`

$ eksctl version
0.123.0

**Comment by TiberiuGC** [comment]
Hi @dan-lind . Yes, the PR was merged, but the changes are part of [0.124.0-rc.0.](https://github.com/weaveworks/eksctl/releases/tag/v0.124.0-rc.0) Will be in `0.124.0` after we promote the RC.

**Comment by dan-lind** [comment]
Oh, I see. Thanks!
