### ISSUE TITLE
[HELP] Not able to create managed windows node groups 

### ISSUE THREAD

**Issue by MuKuSh11** [weaveworks/eksctl#6085]
### What help do you need?
Amazon EKS now supports managed windows node group. [AWS announced ](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-eks-automated-provisioning-lifecycle-management-windows-containers/)

I am trying to provision managed windows node group for an EKS cluster using eksctl, however, I am still getting the same "Windows is not supported for managed nodegroups" error.

```
$ eksctl create nodegroup \
--cluster <cluster> \
--region <region> \
--name my-win-mng \
--node-ami-family WindowsServer2019FullContainer \
--node-type m5.large \
--nodes 1 \
--nodes-min 1 \
--nodes-max 2

> Error: couldn't create node group filter from command line options: Windows is not supported for managed nodegroups; eksctl now creates managed nodegroups by default, to use a self-managed nodegroup, pass --managed=false
```

Similarly,
```
$ eksctl create cluster --node-ami-family=WindowsServer2022FullContainer

> Error: Windows is not supported for managed nodegroups; eksctl now creates managed nodegroups by default, to use a self-managed nodegroup, pass --managed=false
```

However, when I am provisioning managed windows node group from EKS console, the node group is successfully created, the nodes are up and running.

Document https://docs.aws.amazon.com/eks/latest/userguide/create-managed-node-group.html states that """This procedure requires eksctl version 0.123.0 or later."""

I am already using eksctl version 0.123.0, still getting the issue.

```
$ eksctl version
> 0.123.0
```

Any suggestion/help is appreciated.

**Comment by TiberiuGC** [comment]
Hi @MuKuSh11 . Windows managed nodegroups support has been added into our latest release candidate [`0.124.0-rc.0`](https://github.com/weaveworks/eksctl/releases/tag/v0.124.0-rc.0). We will probably promote this to release `0.124.0` later this week.
