### ISSUE TITLE
kube-proxy startup fails due to missing kube-proxy:v1.22.15-eksbuild.2 image

### ISSUE THREAD

**Issue by dmacbride-ep** [weaveworks/eksctl#6086]
### What were you trying to accomplish?
We are trying to create a new EKS cluster with an up-to-date kube-proxy daemonset

Our automation includes, at a very high level:
* Installs `eksctl` version v0.104.0
* `eksctl create cluster --config-file=/root/bootstrap/eksctl.yaml`
* `eksctl utils update-kube-proxy --cluster cluster_name --approve`
* `eksctl utils update-coredns --cluster cluster_name --approve`
* installs a bunch of services

We test this automation several times every week.

### What happened?

Today we noticed that services in the newly-created EKS cluster were not starting. After investigating we discovered that all `kube-proxy` pods are in `ImagePullBackOff` status. This is a new issue that was observed for the first time today.

Describing one of the kube-proxy pods shows the following events:

```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  56m                  default-scheduler  Successfully assigned kube-system/kube-proxy-8wngf to ip-10-100-187-217.ca-central-1.compute.internal
  Warning  Failed     54m (x6 over 55m)    kubelet            Error: ImagePullBackOff
  Normal   Pulling    54m (x4 over 55m)    kubelet            Pulling image "602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/kube-proxy:v1.22.15-eksbuild.2"
  Warning  Failed     54m (x4 over 55m)    kubelet            Failed to pull image "602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/kube-proxy:v1.22.15-eksbuild.2": rpc error: code = Un
known desc = Error response from daemon: manifest for 602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/kube-proxy:v1.22.15-eksbuild.2 not found: manifest unknown: Requested image not fou
nd
  Warning  Failed     54m (x4 over 55m)    kubelet            Error: ErrImagePull
  Normal   BackOff    31s (x240 over 55m)  kubelet            Back-off pulling image "602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/kube-proxy:v1.22.15-eksbuild.2"
```

It appears that eksctl configured the kube-proxy container to use an image that is not currently available.

### What help do you need?
Please help to restore the missing kube-proxy image.

**Comment by dmacbride-ep** [comment]
This seems similar to older issue [1088](https://github.com/weaveworks/eksctl/issues/1088).

**Comment by dmacbride-ep** [comment]
I was able to get kube-proxy starting successfully after editing it to use image `v1.22.11-eksbuild.2` instead of `v1.22.15-eksbuild.2`, using the below command:

```
kubectl edit daemonset kube-proxy --namespace kube-system
```

**Comment by nipr-jdoenges** [comment]
This is also similar to #6027 and #5972

**Comment by TiberiuGC** [comment]
@dmacbride-ep I'll close this issue, so that we can all track progress here - https://github.com/weaveworks/eksctl/issues/6027
