### ISSUE TITLE
eksctl - managed nodegroup windows support via eksctl

### ISSUE THREAD

**Issue by Jegapriya** [weaveworks/eksctl#6099]
The above mentioned feature has been released 5 days back from the aws console. Kindly update this feature on the  eksctl as well.

eksctl create nodegroup --region ap-south-1 --cluster "xxxxx-demoEksCluster" --name "xxxxx-NewDemo-Windows" --node-type m5d.2xlarge --nodes 1 --nodes-min 1 --nodes-max 1 --node-ami-family WindowsServer2019FullContainer
Error: couldn't create node group filter from command line options: Windows is not supported for managed nodegroups; eksctl now creates managed nodegroups by default, to use a self-managed nodegroup, pass --managed=false

C:\WINDOWS\system32>eksctl version
0.123.0

eksversion: 1.23

https://github.com/aws/containers-roadmap/issues/584

**Comment by cPu1** [comment]
This feature is already out in a [release candidate](https://github.com/weaveworks/eksctl/releases/tag/v0.124.0-rc.0). It'll be graduated this Friday. You'll have to download and use [v0.124.0-rc.0](https://github.com/weaveworks/eksctl/releases/tag/v0.124.0-rc.0) to create managed Windows nodegroups in the meantime.

**Comment by cPu1** [comment]
> This feature is already out in a [release candidate](https://github.com/weaveworks/eksctl/releases/tag/v0.124.0-rc.0). It'll be graduated this Friday. You'll have to download and use [v0.124.0-rc.0](https://github.com/weaveworks/eksctl/releases/tag/v0.124.0-rc.0) to create managed Windows nodegroups in the meantime.

The release candidate has been graduated: https://github.com/weaveworks/eksctl/releases/tag/v0.124.0.
