### ISSUE TITLE
[Feature] Minimum IAM policy should give some extra optional policies, such as policy to use EBS CSI

### ISSUE THREAD

**Issue by ensean** [weaveworks/eksctl#6103]
### What feature/behavior/change do you want?

Minimum IAM policy should give optional policies to use extra features, such as EBS CSI. If the current minimum IAM policy is used, the following command from [this](https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html) guide will fail, because it can not create role

``` shell
eksctl create iamserviceaccount \
  --name ebs-csi-controller-sa \
  --namespace kube-system \
  --cluster my-cluster \
  --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
  --approve \
  --role-only \
  --role-name AmazonEKS_EBS_CSI_DriverRole
```

### Why do you want this feature?

Besides the **basic** IAM policies, add some extra policies if the user plans to use eksctl to manage EBS CSI etc.

**Comment by ensean** [comment]
emmm, seems to be my mistake ...

**Comment by tanvp112** [comment]
The error indicated that the IAM user in question does not have iam:CreateRole right.
