### ISSUE TITLE
subnet ID "subnet-11111111" is not the same as "subnet-22222222"

### ISSUE THREAD

**Issue by deckerp** [weaveworks/eksctl#6110]
I receive this error when trying to upgrade an EKS cluster from v1.21 to v1.22. This was deployed with eksctl. Upgrading using the console works just fine.

```
$eksctl upgrade cluster --config-file upgradeClusterVersion.yaml --approve
2022-12-20 22:40:06 [!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
Error: getting VPC configuration for cluster "temp-cluster": could not import subnet subnet-22222222222222222: subnet ID "subnet-11111111111111111" is not the same as "subnet-22222222222222222"

```

I have confirmed the subnets mentioned are indeed in the same AZ.

Is anyone else seeing this issue?
This is with eksctl v0.122.0/

**Comment by cPu1** [comment]
@deckerp, you'll have to share your ClusterConfig file (`upgradeClusterVersion.yaml`). Without it, we can't tell what's wrong.

**Comment by deckerp** [comment]
It basically just has the version.

```
$cat upgradeClusterVersion.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: temp-cluster
  region: us-east-1
  version: "1.22"
```

**Comment by deckerp** [comment]
I think to recreate the issue someone would have to create a cluster with more than one subnet in the same AZ and then try to do an upgrade. I was able to do the normal upgrade process by destroying our temp-cluster and recreating it with the second subnet in each AZ commented out. Everything ran as expected.

Thanks for looking and responding.

**Comment by deckerp** [comment]
I can't explain this but I have since been able to upgrade the cluster without seeing this same error. Sorry for the report. I did try a few times to reproduce and it seemed tied to multiple subnets in the same AZ.

**Comment by cneira84** [comment]
Hi. In my case, I was following the EKS deployment using VPC Sharing, and the subnets changed the logical AZ identifier when sharing. I double checked the AZ in VPC of the account that I'm using to create the cluster.
