### ISSUE TITLE
[Feature] elastic fiber adapter (efa) from the command line

### ISSUE THREAD

**Issue by vsoch** [weaveworks/eksctl#6116]
### What feature/behavior/change do you want?

It looks like I'm able to set `efaEnabled` to true using a config yaml (see here https://docs.aws.amazon.com/eks/latest/userguide/node-efa.html) and I'm hoping that this might be possible to do via the command line without that? E.g.,:

```bash
$ eksctl create cluster --name=${CLUSTER_NAME} --tags=${TAGS} \
    --region=${REGION} --version=${KUBERNETES_VERSION} --nodegroup-name=workers \
    --node-type=${MACHINE_TYPE} --nodes-min=${SIZE} --nodes-max=${SIZE} \
    --efa-enabled --color fabulous
```

And major shoutout to the color option for "fabulous!" That totally made my day :joy: 

### Why do you want this feature?

I have a tool that runs our operator easily across clouds, and we have create/destroy scripts for each. It's much easier to be able to write the command directly than be required to write a temporary yaml file to use. It's one step of indirection I'd prefer to avoid if possible. Thank you!

**Comment by Himangini** [comment]
@vsoch ty for the feature request and for the shoutout ✨ as maintainers we love community feedback and it makes our day to receive positive feedback 😄 🎉 

While I understand your feature request, we are moving towards a more declarative approach and avoiding adding new command line flags wherever possible for eksctl. If you feel strongly about this command line flag then I'd suggest submitting a PR. We love and encourage community contributions and will happily review them 👍🏻

**Comment by vsoch** [comment]
hey @Himangini ! I must admit I refactored my library to use  config yaml template when I saw the "1-5" business days, haha. I'm wondering, is there an approach that is feasible that would allow you to programatically derive the arguments from the same spec that is used to validate? E.g., I've done this in Python a few times, usually populating argparse from jsonschema. https://github.com/converged-computing/cloud-select/blob/3bc2ef2a256b8625c013e65d8e85086eafd9bdc8/cloud_select/client/__init__.py#L24.

**Comment by Himangini** [comment]
> hey @Himangini ! I must admit I refactored my library to use config yaml template when I saw the "1-5" business days, haha. I'm wondering, is there an approach that is feasible that would allow you to programatically derive the arguments from the same spec that is used to validate? E.g., I've done this in Python a few times, usually populating argparse from jsonschema. https://github.com/converged-computing/cloud-select/blob/3bc2ef2a256b8625c013e65d8e85086eafd9bdc8/cloud_select/client/__init__.py#L24.

Apologies I am currently occupied with other tasks and won't be able to help much here.

**Comment by vsoch** [comment]
ok, just nevermind then. Thanks!
