### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by gaussye** [weaveworks/eksctl#6144]
### What were you trying to accomplish?

I am trying to use eksctl utils  cmd to upgrade kube-proxy add-on on EKS(1.22). 
$ eksctl utils update-kube-proxy  --cluster=green-cluster-03 --region=ap-northeast-1  --approve
2023-01-10 12:49:52 [ℹ]  "kube-proxy" is now up-to-date
$ kubectl get pods -A
NAMESPACE     NAME                       READY   STATUS         RESTARTS   AGE
kube-system   aws-node-7c2p8             1/1     Running        0          2d23h
kube-system   aws-node-wlf27             1/1     Running        0          2d23h
kube-system   coredns-5b6d4bd6f7-5s5lj   1/1     Running        0          28h
kube-system   coredns-5b6d4bd6f7-6rpm9   1/1     Running        0          28h
kube-system   kube-proxy-2glql           0/1     ErrImagePull   0          8s
kube-system   kube-proxy-fnbzh           1/1     Running        0          3m45s

Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m58s                  default-scheduler  Successfully assigned kube-system/kube-proxy-2glql to ip-10-2-44-60.ap-northeast-1.compute.internal
  Normal   Pulling    3m26s (x4 over 4m57s)  kubelet            Pulling image "xxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/eks/kube-proxy:v1.22.16-eksbuild.3"
  Warning  Failed     3m26s (x4 over 4m57s)  kubelet            Failed to pull image "xxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/eks/kube-proxy:v1.22.16-eksbuild.3": rpc error: code = Unknown desc = Error response from daemon: manifest for xxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/eks/kube-proxy:v1.22.16-eksbuild.3 not found: manifest unknown: Requested image not found
  Warning  Failed     3m26s (x4 over 4m57s)  kubelet            Error: ErrImagePull
  Warning  Failed     3m13s (x6 over 4m56s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m2s (x7 over 4m56s)   kubelet            Back-off pulling image "xxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/eks/kube-proxy:v1.22.16-eksbuild.3"

$ eksctl info
eksctl version: 0.122.0
kubectl version: v1.21.5-eks-9017834
OS: linux

### How to reproduce it?

**Logs**

**Anything else we need to know?**

**Versions**

```
$ eksctl info
```

**Comment by cPu1** [comment]
@gaussye, this is a known issue. I'm closing this in favour of https://github.com/weaveworks/eksctl/issues/6027. Please follow https://github.com/weaveworks/eksctl/issues/6027 to track this issue.

**Comment by gaussye** [comment]
Ok. thanks.
