### ISSUE TITLE
[Feature] Include permissionBoundary for eksctl create iamserviceaccount

### ISSUE THREAD

**Issue by emboss64** [weaveworks/eksctl#6148]
### What feature/behavior/change do you want?
Recreating #5564. Currently when using the `eksctl create iamserviceaccount` there's no option to attach a permission boundary to the IAM role, feature which is available when creating service accounts through config files

Example
> eksctl create iamserviceaccount --name my-account --namespace default --cluster my-cluster **--permissionsBoundary arn:aws:iam::XXXX:policy/AA-PB-XYZ**

### Why do you want this feature?
Gain the ability to create serviceaccounts that need permission boundaries through CLI

**Comment by emboss64** [comment]
Are we the only ones using permission boundaries this way?

**Comment by pampelix** [comment]
I'm having the same issue, please consider adding this parameter.

**Comment by jonathan-innis** [comment]
This is also annoying for me as well. I'd like to be able to use the `eksctl` CLI commands to set permission boundaries on the IRSA roles ad-hoc after cluster creation but this doesn't seem to be possible at present. Instead, I guess I'll have to opt to setting up all the service account permissions ahead-of-time using ClusterConfig but this is an unnecessary annoyance.

**Comment by masudio** [comment]
causing a problem for us as well.
