### ISSUE TITLE
[Feature] eksctl should be able to pass additional optional parameter (to bootstrap script) which sets custom service CIDR when launching windows nodes

### ISSUE THREAD

**Issue by Madhunil** [weaveworks/eksctl#6151]
### Why do you want this feature?

Windows on EKS currently had a bug in custom service CIDR functionality. Service CIDR is a method of assigning IP addresses that improves the efficiency of address distribution and replaces the previous system based on Class A, Class B and Class C networks and hence it allows customers to allocate a specific IP range for the services on EKS Windows Node. 

To fix this bug, EKS windows team suggests that we pass an additional optional parameter to the current EKS windows bootstrap script.

It can be passed similar to the below usesdata

`<powershell>
[string]$EKSBootstrapScriptFile = "$env:ProgramFiles\Amazon\EKS\Start-EKSBootstrap.ps1"
& $EKSBootstrapScriptFile -EKSClusterName "service-cidr-test" -ServiceCIDR "10.0.16.0/21"
</powershell>`

### What feature/behavior/change do you want?

So as a part of this fix we require some assistance from the eksctl team. As they need to make code changes such that this additional optional parameter `-ServiceCIDR` gets passed in user data while launching Windows nodes.

Below doc contains configuration parameters for EKS windows bootstrap script where details for `-ServiceCIDR` are mentioned as well.

https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-windows-ami.html#bootstrap-script-configuration-parameters

**Comment by Himangini** [comment]
@Madhunil have you tried passing the additional param using the `overrideBootstrapCommand`? Can you share the configuration you are using if possible?
eg.,
```
overrideBootstrapCommand: |
   <powershell> [string]$EKSBootstrapScriptFile = "$env:ProgramFiles\Amazon\EKS\Start-EKSBootstrap.ps1" & $EKSBootstrapScriptFile -EKSClusterName "service-cidr-test" -ServiceCIDR "10.0.16.0/21" </powershell>
```

**Comment by Madhunil** [comment]
Hi @Himangini
While this parameter can be passed via `overrideBootstrapCommand`, If the command is not specified, eksctl generates the bootstrap command.
While Customers can always use `overrideBootstrapCommand`, we want the param to be also included in the latter case.

**Comment by Himangini** [comment]
> Hi @Himangini While this parameter can be passed via `overrideBootstrapCommand`, If the command is not specified, eksctl generates the bootstrap command. While Customers can always use `overrideBootstrapCommand`, we want the param to be also included in the latter case.

@Madhunil thanks for clarifying, we'll look into this and come up with a solution 👍🏻

**Comment by Madhunil** [comment]
Thanks for the prompt response @Himangini 

Please let me know if you need anything else from our side.
