### ISSUE TITLE
Remove 1.20 from list of supported versions in eksctl

### ISSUE THREAD

**Issue by vipin-mohan** [weaveworks/eksctl#6152]

**Comment by vipin-mohan** [comment]
We have removed 1.20 from the EKS console and EKS API (i.e., customers cannot create 1.20 clusters). We must also remove it from eksctl to ensure a consistent customer experience
https://github.com/weaveworks/eksctl/blob/e40e547126eeab7a7c71a87ecd5027da64e1ae0b/pkg/apis/eksctl.io/v1alpha5/types.go#L484-L518

**Comment by Himangini** [comment]
dupe of #5522
