### ISSUE TITLE
[Help] EKS giving API server unreachable error while creating cluster using eksctl using public + private endpoint setting

### ISSUE THREAD

**Issue by vishalrajeev** [weaveworks/eksctl#6156]
### What help do you need?
While attempting to create EKS cluster, encountered issue wherein API server became unreachable. I was using eksctl to create the cluster. Attaching the eksctl config file as well as the error log I received while creation.

On trying to delete the cluster, getting similar error:
2023-01-13 09:44:59 [ℹ]  deleting EKS cluster "<clustername>"
2023-01-13 09:45:00 [ℹ]  deleted 0 Fargate profile(s)
2023-01-13 09:45:00 [✔]  kubeconfig has been updated
2023-01-13 09:45:00 [ℹ]  cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
Error: cannot list Kubernetes Services: Get "[https://17CA52397574D6A2FDE4EFCE6D6A53EA.gr7.us-west-2.eks.amazonaws.com/api/v1/services ](https://17ca52397574d6a2fde4efce6d6a53ea.gr7.us-west-2.eks.amazonaws.com/api/v1/services)": dial tcp 192.168.232.206:443: i/o timeout
[eksctl_config.txt](https://github.com/weaveworks/eksctl/files/10412739/eksctl_config.txt)
[eksctl_logs_1.txt](https://github.com/weaveworks/eksctl/files/10412740/eksctl_logs_1.txt)
[eksctl_config.txt](https://github.com/weaveworks/eksctl/files/10412742/eksctl_config.txt)
[eksctl_logs_1.txt](https://github.com/weaveworks/eksctl/files/10412743/eksctl_logs_1.txt)

The command is being executed via Cloud9 instance in private subnet from the same VPC where EKS cluster is being provisioned
Kindly assist.

**Comment by vishalrajeev** [comment]
By mistake same set of files have been uploaded twice, ignore one of the set. Thx

**Comment by xjtupdy** [comment]
I get the same error.
Have you solved it?
