### ISSUE TITLE
[Feature] Global support for the AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by DuncanCasteleyn** [weaveworks/eksctl#6166]
### What feature/behavior/change do you want?
I use oh-my-zsh on macOs and I use the AWS plugin which has shortcut ASP to easily set the AWS profile for the shell session however i noticed I'm required to add --profile on most eksctl command executions.

I would like it if the AWS_PROFILE environment variable was always read to determine the profile and --profile to be used to override the execution once for a command (it would also ingore AWS_PROFILE when used).

### Why do you want this feature?
To make usage of profile with eksctl more efficient it would be useful that I don't have to append the --profile parameter for most command invocations.

Currently it's a bit unclear which command requires the usage of --profile and which not based on some PR request it seems write-kubeconfig supports it for example, but `eksctl get cluster` requires it,`eksctl create nodegroup --dry-run` does not even work with profiles but I can't use the dry-run command without selecting the correct profile because you need to select an existing cluster on AWS, so this is probably a bug (#6167). 

Other user(s) seem to have assumed already that this would work but this feature is not yet present, for example #5869 this user set an export AWS_PROFILE=something and assumed this would set the profile for eksctl as well.

**Comment by yuxiang-zhang** [comment]
I cannot reproduce the errors you mentioned except for the one involving `--dry-run`. Could you be more specific in the steps to reproduce? I suspect there may be incorrect credentials configuration.

**Comment by DuncanCasteleyn** [comment]
Sorry, I forgot to close this issue, but you are correct the AWS CLI was correctly handling the credentials configuration, but there was an error in the configration and eksctl could for some reason not handle this, I removed the outdated configuration that conflicted and the problem was resolved.
