### ISSUE TITLE
[Bug] create nodegroup --dry-run can't run with --profile but profile required to access existing cluster

### ISSUE THREAD

**Issue by DuncanCasteleyn** [weaveworks/eksctl#6167]
### What were you trying to accomplish?
`eksctl create nodegroup --region eu-west-1 --dry-run --cluster <redacted> --profile <redacted>`

### What happened?
I got an error that selecting a profile with --dry-run is not allowed but you need a profile because you need to be able to select an existing cluster.

### How to reproduce it?
Try to access an existing cluster with the above command that requires the usage of a profile.
I do not use the default profile, to force myself to select a profile.

**Logs**
`Error: couldn't create node group filter from command line options: cannot use --profile with --dry-run as this option cannot be represented in ClusterConfig`

**Anything else we need to know?**
I'm using eksctl on macos installed through brew, I require the usage of a profile to acces the cluster.

**Versions**
```
eksctl version: 0.125.0-dev+5ca6aa6cc.2023-01-13T10:11:35Z
kubectl version: v1.22.15
OS: darwin
```

**Comment by cPu1** [comment]
@DuncanCasteleyn, `--profile` isn't allowed with `--dry-run` because the generated ClusterConfig contains no information about the AWS profile, so eksctl can't guarantee that a subsequent run without the same `--profile` will produce the same result. Of course, this is also true when `AWS_PROFILE` is set, but by design, eksctl assumes that a subsequent `eksctl create cluster` with the generated ClusterConfig will have the same environment variables set. 

>I got an error that selecting a profile with --dry-run is not allowed but you need a profile because you need to be able to select an existing cluster.

The preferred way is to pass the `AWS_PROFILE` environment variable, as in:

```shell
$ AWS_PROFILE=profile eksctl create nodegroup --region eu-west-1 --dry-run --cluster <redacted> --profile <redacted>
```

Or have it set in your `.envrc` so you don't have to repeat it for subsequent commands.

**Comment by DuncanCasteleyn** [comment]
> @DuncanCasteleyn, `--profile` isn't allowed with `--dry-run` because the generated ClusterConfig contains no information about the AWS profile, so eksctl can't guarantee that a subsequent run without the same `--profile` will produce the same result. Of course, this is also true when `AWS_PROFILE` is set, but by design, eksctl assumes that a subsequent `eksctl create cluster` with the generated ClusterConfig will have the same environment variables set.
> 
> > I got an error that selecting a profile with --dry-run is not allowed but you need a profile because you need to be able to select an existing cluster.
> 
> The preferred way is to pass the `AWS_PROFILE` environment variable, as in:
> 
> ```shell
> $ AWS_PROFILE=profile eksctl create nodegroup --region eu-west-1 --dry-run --cluster <redacted> --profile <redacted>
> ```
> 
> Or have it set in your `.envrc` so you don't have to repeat it for subsequent commands.

Might not be a bad idea to clarify this in the docs and/or error message that AWS_PROFILE should be used?

**Comment by cPu1** [comment]
> > @DuncanCasteleyn, `--profile` isn't allowed with `--dry-run` because the generated ClusterConfig contains no information about the AWS profile, so eksctl can't guarantee that a subsequent run without the same `--profile` will produce the same result. Of course, this is also true when `AWS_PROFILE` is set, but by design, eksctl assumes that a subsequent `eksctl create cluster` with the generated ClusterConfig will have the same environment variables set.
> > > I got an error that selecting a profile with --dry-run is not allowed but you need a profile because you need to be able to select an existing cluster.
> > 
> > 
> > The preferred way is to pass the `AWS_PROFILE` environment variable, as in:
> > ```shell
> > $ AWS_PROFILE=profile eksctl create nodegroup --region eu-west-1 --dry-run --cluster <redacted> --profile <redacted>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or have it set in your `.envrc` so you don't have to repeat it for subsequent commands.
> 
> Might not be a bad idea to clarify this in the docs and/or error message that AWS_PROFILE should be used?

Good idea. We'll add this to the docs.

**Comment by rongshengfang** [comment]
> @DuncanCasteleyn, `--profile` isn't allowed with `--dry-run` because the generated ClusterConfig contains no information about the AWS profile, so eksctl can't guarantee that a subsequent run without the same `--profile` will produce the same result. Of course, this is also true when `AWS_PROFILE` is set, but by design, eksctl assumes that a subsequent `eksctl create cluster` with the generated ClusterConfig will have the same environment variables set.

@cPu1 I feel it shouldn't be `eksctl`'s but the users' responsibility to make sure the aws profile for `eksctl create cluster` is the same one used to generated the ClusterConfig via `--dry-run` previously. 

It also feels wrong to run the following command as both `AWS_PROFILE` and `--profile` would be set to the same value (I can't imagine why one would set them different):

```
$ AWS_PROFILE=profile eksctl create nodegroup --region eu-west-1 --dry-run --cluster <redacted> --profile <redacted>
```

So I think one should be able to use `--profile` with `--dry-run` without setting the `AWS_PROFILE` environment variable.

**Comment by cPu1** [comment]
>@cPu1 I feel it shouldn't be eksctl's but the users' responsibility to make sure the aws profile (via AWS_PROFILE or --profile) for eksctl create cluster is the same one used to generated the ClusterConfig via --dry-run previously.

This is a design decision and we have chosen to avoid supporting CLI options that cannot be represented in the ClusterConfig file. I understand that users can have multiple AWS profiles and would need to pass one with `--dry-run`, but since there's already a way to pass the profile with `AWS_PROFILE`, the decision was to not support `--profile` with `--dry-run`. 

> It just feels wrong imo to run the following command with both `AWS_PROFILE` and `--profile` set (they are to be set to the same value anyway):

You do not need to set both `AWS_PROFILE` and `--profile`. `--dry-run` will only permit the environment variable `AWS_PROFILE` and not the CLI option `--profile`.
