### ISSUE TITLE
Is there a way to pass ConfigurationValues for addons from command line

### ISSUE THREAD

**Issue by mukundjalan** [weaveworks/eksctl#6175]
### What help do you need?
Is there a way to pass ConfigurationValues for addons from command line?

As per https://eksctl.io/usage/addons/#working-with-configuration-values I see, I can only pass `ConfigurationValues` using config file but no guidelines on how they can be used from command line.

I haven't tried anything yet but if the same is documented, it will help me when I upgrade eksctl next month.

**Comment by cPu1** [comment]
eksctl does not support passing addon configuration values as a CLI flag. That would not be a good UX, so we have no plans of adding it in the future either. 

>I haven't tried anything yet but if the same is documented, it will help me when I upgrade eksctl next month.

I would recommend using a config file. 

I'm closing the issue, please feel free to open a new issue if you have more questions.
