### ISSUE TITLE
Add custom cloudformation resources

### ISSUE THREAD

**Issue by jacobtomlinson** [weaveworks/eksctl#619]
Once I've created a cluster with eksctl there are a bunch of extra features I want to add to make it an even better cluster. These mostly comprise of a CloudFormation to add some AWS resources and some helm charts which make use of the resources.

Examples include:
- ReadWriteMany volumes (Requires an EFS and the efs-provisioner chart)
- Kube2IAM for giving IAM roles to pods (Requires some IAM roles and the kube2iam chart)
- External DNS Support (Requires some route53 resources and the external-dns chart)
- Centrally stored logs (Requires a CloudWatch logs group and the fluentd-cloudwatch chart)

We are currently doing this with a script which uses eksctl to create the cluster and then awscli to create the CloudFormation (referencing resources created by eksctl) and then helm to install the charts.

I was wondering if there was any plan to allow you to add the custom CloudFormation resources to the one created by eksctl rather than it having to be a separate stack?

**Comment by errordeveloper** [comment]
This falls into add-ons discussion (see #53, #271, #421, and #242). We certainly would like to solve this, but it's not top priority at the moment, happy to hear more about your thoughts on this.

**Comment by michaelbeaumont** [comment]
Closing this as it falls under the aforementioned issues (#53)
