### ISSUE TITLE
[Bug] Upgrade snap base from base18 to base20

### ISSUE THREAD

**Issue by jlosito** [weaveworks/eksctl#6197]
### What were you trying to accomplish?

I noticed that the eksctl snap is using v18 as its base. Ubuntu 18 is nearing its end of standard support in April of 2023, just a couple of weeks from now. The official snap documentation states that developers should use v20 as their base. It's probably a good habit to keep everything as up-to-date as much as possible.

https://snapcraft.io/docs/base-snaps

> [core20](https://snapcraft.io/core20): built from [Ubuntu 20.04 LTS](https://releases.ubuntu.com/20.04/) and currently recommended for most projects until core22 plugins and extensions reach parity with this release.

I understand that other things take priority, as stated in the issue below. Upgrading the base might be low hanging fruit that could be accomplished. Given that, a won't fix is completely understandable.

https://github.com/weaveworks/eksctl/issues/3436

**Comment by Himangini** [comment]
@jlosito this is a lower prio for us right now however, we're happy to accept PRs 👍🏻
