### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#62]
At the moment we create clusters dedicated for single user, we need to extend this.

https://docs.aws.amazon.com/eks/latest/userguide/managing-auth.html

https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

It'd be nice to have two features:
- add any existing IAM user to a cluster
- add all admin (as in, those with Administrator policy) to a cluster when it's created (may need sync loop)

**Comment by christopherhein** [comment]
Couple things to keep in mind as we move forward the potential of using CRDs for user management in the authenticator - https://github.com/heptio/authenticator/issues/79

**Comment by errordeveloper** [comment]
xref #544
