### ISSUE TITLE
[Task] Remove Support for EKS version 1.21

### ISSUE THREAD

**Issue by Himangini** [weaveworks/eksctl#6201]
### Description
As per the calendar for [Amazon EKS end of support](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) February 16, 2023 is the end of support for Kubernetes version 1.21 

We need to remove support for 1.21 and modify any relevant docs wherever possible.
Reference PR - see [here](https://github.com/weaveworks/eksctl/pull/5073)

**Comment by rongshengfang** [comment]
@Himangini I'd like to work on this. Is it possible to assign this to me? Thanks!

**Comment by Himangini** [comment]
@rongshengfang sure go ahead. Please open a PR by next week so we can review and test properly. 🎉

**Comment by rongshengfang** [comment]
@Himangini I just submitted #6237. Could you take a look and approve the workflows for it?
