### ISSUE TITLE
[Bug] Generated FargatePodExecutionRole IAM role misses condition 

### ISSUE THREAD

**Issue by gaborho** [weaveworks/eksctl#6273]
### What were you trying to accomplish?
Trying to create a fargate profile 

### What happened?
eksctl created FargatePodExecutionRole IAM role using CF stack which is not according the documented way of AWS, and it misses condition that restricts access based on SourceArn. 
According to https://docs.aws.amazon.com/eks/latest/userguide/pod-execution-role.html#check-pod-execution-role 

_To avoid a confused deputy security problem, it's important that the role restricts access based on SourceArn_

**Versions**
eksctl version: 0.129.0-dev+34418ea8e.2023-02-07T18:38:37Z

**Comment by Himangini** [comment]
@gaborho Can you provide some context on how you are creating fargate profile so we can reproduce on our side? Are you using command line flags or config file? What errors (if ANY)  or AmazonEKSFargatePodExecutionRolePolicy do you see?

**Comment by gaborho** [comment]
@Himangini I was creating the Fargate profile with the following command: 

`docker run --rm --network host docker.artifacts.rbi.tech/weaveworks/eksctl:v0.129.0 create fargateprofile --cluster PLAY01-app-k8s --name PLAY01-gabor-test-fargate-profile --namespace foobar --region eu-central-1`

There are no errors, however in the resulting CloudFormation stack / template the AWS::IAM::Role with Logical ID FargatePodExecutionRole is missing the following Condition in the AssumeRolePolicyDocument / Statement.

```
      "Condition": {
         "ArnLike": {
            "aws:SourceArn": "arn:aws:eks:region-code:111122223333:fargateprofile/my-cluster/*"
         }
```

As mentioned in the https://docs.aws.amazon.com/eks/latest/userguide/pod-execution-role.html#check-pod-execution-role documentation, "To avoid a confused deputy security problem, it's important that the role restricts access based on SourceArn"

So in order to follow AWS best practices, eksctl should create the IAM role with the condition mentioned above.
