### ISSUE TITLE
[Feature] Require --approve flags for create and delete of clusters

### ISSUE THREAD

**Issue by RenkeNPO** [weaveworks/eksctl#6274]
### What feature/behavior/change do you want?

When creating or deleting an EKS cluster, eksctl should expect the `--approve` flag to actually execute the command, similar to upgrade commands.

### Why do you want this feature?

1) for consistency's sake. The current behavior is surprising and confusing.
2) creating and deleting clusters are the most powerful actions that the eksctl can carry out, it would make sense to make sure that they're being used intentionally on the right resources.

**Comment by cPu1** [comment]
This has been discussed before: https://github.com/weaveworks/eksctl/issues/5137. While it's not consistent with some other commands, it's unfortunately a major breaking change and will require some thought before we can consider it.

**Comment by RenkeNPO** [comment]
Thanks for the fast response. Alright. I checked the open issues before posting, but not the closed ones... and it seems there's indeed a number of them. Yes, I understand it's a breaking change, but the recurrence of the request (and frankly it's charitable to call it a feature request) would suggest that there is a significant demand for this. Seems to me that it's possible to keep an issue open even if it would only be done in a major version upgrade?
