### ISSUE TITLE
eksctl prepends eksctl to rolename causing failure

### ISSUE THREAD

**Issue by caolandix** [weaveworks/eksctl#6275]
My company has a specific path it must create roles within. cluster name and all roles must start with "project-" When I attempt to create the cluster with this command:

`eksctl create cluster --name project-eksctl-test-1 --region xx-xxx-xxx-x --with-oidc --ssh-access --ssh-public-key project-eks-test-1 --instance-types=m5.xlarge --managed`

I get back a failure that says:
is not authorized to perform: iam:CreateRole on resource: arn:aws-xx-xxx:iam::xxxxxxxxxxx:role/eksctl-project-eksctl-test-1-cluster-ServiceRole-4CJ6TL0K9WAX because no permissions boundary allows the iam:CreateRole action"

It creates the role with the prepended "eksctl-"

How do I prevent this?

**Comment by TiberiuGC** [comment]
Hi @caolandix, from what I'm seeing in our codebase, the standard convention when naming resources (e.g. [addons](https://github.com/weaveworks/eksctl/blob/ea79559c7d13d8e92ff42c0442e08856c6bcb7c9/pkg/actions/addon/addon.go#L107), [cfn stacks](https://github.com/weaveworks/eksctl/blob/ea79559c7d13d8e92ff42c0442e08856c6bcb7c9/pkg/cfn/manager/nodegroup.go#L35), [roles](https://github.com/weaveworks/eksctl/blob/ea79559c7d13d8e92ff42c0442e08856c6bcb7c9/pkg/actions/karpenter/create.go#L32), etc) is to prepend `eksctl`. Unfortunately, I don't see us either breaking this convention or there being an easy way to override this. @cPu1 @Himangini - Wdyt?
