### ISSUE TITLE
[Feature] Add a create flag for EBS CSI addon

### ISSUE THREAD

**Issue by evankanderson** [weaveworks/eksctl#6292]
### What feature/behavior/change do you want?

I would like a flag to automatically provision the EBS CSI driver which can be done through this command:

https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html#adding-ebs-csi-eks-add-on

```bash
eksctl create addon --name aws-ebs-csi-driver --cluster my-cluster --service-account-role-arn arn:aws:iam::111122223333:role/AmazonEKS_EBS_CSI_DriverRole --force
```

It looks like `eksctl` already has flags for similar add-on features like `--with-oidc` and `--alb-ingress-access`

### Why do you want this feature?

I'd like to be able to provision an EKS cluster with one command, rather than having to come back to run a second command to enable PersistentVolumes.

**Comment by cPu1** [comment]
>It looks like eksctl already has flags for similar add-on features like --with-oidc and --alb-ingress-access

The `--with-oidc` and `--alb-ingress-access` flags serve a different purpose, they do not create addons. If you need a more declarative way to create addons, you can specify them in a ClusterConfig file and pass it during cluster creation with `eksctl create cluster`, or after cluster creation with `eksctl create addons`.  We have no flags that result in creation of EKS addons, so this is not in line with the current UX and we're not going to add support for it.
