### ISSUE TITLE
[Help] How to use disassociate identity provider command

### ISSUE THREAD

**Issue by makeorinitialize** [weaveworks/eksctl#6293]
### What help do you need?
eksctl disassociate identity provider command requires that the caller passes a name. I don't know what's the right value for this.

I've tried passing the name of the cluster and the name of the provider that I can see in IAM portal and both don't seem to work.

```
eksctl disassociate identityprovider --cluster=test-dev --region=us-west-2 --name "test" --type oidc
2023-02-15 17:21:49 [✖]  operation error EKS: DescribeIdentityProviderConfig, https response error StatusCode: 404, RequestID: 88bd8113-1edb-484d-b03d-6e246b07b177, ResourceNotFoundException: No config found for cluster: test-dev, config type: oidc, config name: test
Error: one or more providers failed to associate
```

**Comment by Himangini** [comment]
@makeorinitialize from the error you posted looks like the `test` provider is not associated with your cluster `test-dev`
you can find out whether you have an existing IAM OIDC provider for your cluster by running 
`aws eks describe-cluster --name my-cluster --query "cluster.identity.oidc.issuer" --output text`

Read more: https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
https://docs.aws.amazon.com/eks/latest/userguide/authenticate-oidc-identity-provider.html
