### ISSUE TITLE
Generate config file from flags

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#633]
Some of the users mentioned (e.g. in #508) that the mapping between flags and config attributes is not clear. As we'd like to reduce the number of flags, we should provide an easy way to get config based on flags.

It could be something like `eksctl create cluster --name=test-1 --private-node-networking --dry-run-mode=render-config`.

Other people asked for `--dry-run` (e.g. #476),  but I believe we'd need more there, e.g. ability to emulate cluster and nodegroups stack creation and tracking what AWS resources those stacks would create, hence it seems plausible to have a few dry run modes.

**Comment by errordeveloper** [comment]
I'm afraid this depends on https://github.com/weaveworks/eksctl/issues/399, I'd rather not see any new features being added to `doCreateCluster`.

**Comment by pawelprazak** [comment]
I can confirm the issue with understanding config file, I had to read the source code to learn how to use it.

Allowing a dry-run/export functionality could help with trial and error loop being much faster.

**Comment by whereisaaron** [comment]
It was a little painful to convert, and some of the config file names don't really say what that are for (looking at you `withLocal` / `withShared` 😄), and I had to resort to reverse engineering the code too.

**Comment by errordeveloper** [comment]
I agree, and this is high on our priority list, but help will be welcome.
We should probably switch to gitbook for this, which should be fairly easy,
I am sure that one could start working on that in their fork to beging with.

**Comment by cPu1** [comment]
Reopening the issue as we're going to begin work on it soon. There's also an open proposal to address the dry-run feature: https://github.com/weaveworks/eksctl/pull/3107
