### ISSUE TITLE
[Feature] eksctl version 0.131.0: Error: control plane version "1.25" is not known

### ISSUE THREAD

**Issue by oleg-ku-32768** [weaveworks/eksctl#6345]
Trying to upgrade AWS EKS to 1.25
Will be nice if eksctl can support it.

**$ eksctl upgrade cluster --approve --version=1.25 --name=cluster_name**
_Error: control plane version "1.25" is not known to this version of eksctl, try to upgrade eksctl first_

**$ eksctl info**
_eksctl version: 0.131.0
kubectl version: v1.26.1
OS: linux_

**Comment by d3c1978** [comment]
Second the request. Version 0.131.0 is the latest, yet it does not support upgrading AWS eks to 1.25.

**Comment by matschaffer-roblox** [comment]
Per https://github.com/weaveworks/eksctl/issues/6337#issuecomment-1443553902 0.132 should fix this and an RC is available. I have a 1.25 cluster create running now. So far so good.

**Comment by cPu1** [comment]
> Per [#6337 (comment)](https://github.com/weaveworks/eksctl/issues/6337#issuecomment-1443553902) 0.132 should fix this and an RC is available. I have a 1.25 cluster create running now. So far so good.

That's correct. 1.25 is supported in the [latest release candidate](https://github.com/weaveworks/eksctl/releases/tag/v0.132.0-rc.0). A full release will be out this week.
