### ISSUE TITLE
improve support for custom AMIs

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#637]
As seen in #622, it's easy to set the `ami` filed without `amiFamily`, which leads to assumptions in how to bootstrap it.

We should consider (all or some of):
- check if AMI is at all present
- check if it is based on AL2 (if possible)
- warn user if it is neither AL2, nor Ubuntu
- provide a way for users to use any AMI with a custom bootstrap script

**Comment by adamjohnson01** [comment]
@errordeveloper, I am happy to help out with this if nobody it already working on it.
