### ISSUE TITLE
Make 1.25 the default Kubernetes version in eksctl

### ISSUE THREAD

**Issue by vipin-mohan** [weaveworks/eksctl#6371]

**Comment by vipin-mohan** [comment]
EKS launched support for 1.25 on February 22nd. We typically make the new version default 2 weeks after launch (to ensure it has soaked in sufficiently).

Let's plan to do this by March 9th. I'm not able to find a "due date" field for this issue. Hence adding the date as a comment.

**Comment by Himangini** [comment]
thanks @vipin-mohan 🎉  I'll get started on this soon.
