### ISSUE TITLE
[Bug] m7g and r7g are not handled by  IsARMInstanceType

### ISSUE THREAD

**Issue by pmkc** [weaveworks/eksctl#6377]
m7g and r7g are not handled by  [IsArmIsntanceType](https://github.com/weaveworks/eksctl/blob/65e9fcf79c4a2651275c3b2f1d2698d1490e493c/pkg/utils/instance/instance.go#L11),

But seem to be [supported by EKS](https://github.com/awslabs/amazon-eks-ami/pull/1166)

It might be worth matching gn?$ instead of just known instances.

**Comment by cPu1** [comment]
Support for these instance types was added recently to the CNI plugin. Thanks for flagging this, we'll work on it soon.
