### ISSUE TITLE
[Bug] CoreDNS upgrade breaks with InvalidImageName

### ISSUE THREAD

**Issue by sarasensible** [weaveworks/eksctl#6390]
### What were you trying to accomplish?

Trying to use `eksctl utils update-coredns` to upgrade to Kubernetes 1.25

### What happened?

Coredns pods failed to come up with invalidImageName
```
  Warning  InspectFailed  13s (x10 over 117s)  kubelet            Failed to apply default image tag "602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/eks/coredns:v1.9.3-eksbuild.2%!(EXTRA string=602401143452, string=us-east-2, string=amazonaws.com)": couldn't parse image reference "602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/eks/coredns:v1.9.3-eksbuild.2%!(EXTRA string=602401143452, string=us-east-2, string=amazonaws.com)": invalid reference format
```

### How to reproduce it?

Upgrade cluster to 1.25 then use `eksctl utils update-coredns` to upgrade coredns

**Logs**

**Anything else we need to know?**

Used brew to install eksctl

**Versions**

```
$ eksctl info
eksctl version: 0.132.0
kubectl version: v1.26.2
OS: darwin
```

Workaround: 
Edit the coredns deploy to have the appropriate image: `602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/coredns:v1.9.3-eksbuild.2`

**Comment by Himangini** [comment]
thanks for reporting this issue, we will get the fix out soon ✨

**Comment by afreitasdotdev** [comment]
I have been tests to upgrade my EKS cluster and I had the same issue. The mentioned solution works for me. 

Environment: 
EKS 1.25
Nodes ami: ami-0db1d52047cb9771f


Edit the deployment: 
kubectl edit deploy coredns -n kube-system -o yaml 

Thanks @sarasensible

**Comment by ryanpeach** [comment]
Same issue
