### ISSUE TITLE
[Feature] Make IMDSv2 the default

### ISSUE THREAD

**Issue by jpmcb** [weaveworks/eksctl#6398]
### What feature/behavior/change do you want?
Related to https://github.com/weaveworks/eksctl/issues/5366, we should heavily consider setting IMDSv2 _as the default_. When running the default experience, `eksctl create cluster` will create auto scaling groups that are using IMDSv1. Depending on the type of account, this will be flagged by Amazon security.

### Why do you want this feature?
As mentioned in previous issues, Amazon security will flag these as high severity vulnerabilities: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-controls-reference.html#ec2-8-remediation

Further, it's recommended to generally use IMDSv2: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

Is there a reason `eksctl` by default uses IMDSv1? If not, I'd suggest moving to the new version.

**Comment by Himangini** [comment]
We'll need to do a spike on how to best support the v2 by default. 
Timebox - 1 day

**Comment by TiberiuGC** [comment]
Spike outcomes:
- IMDSv2 is generally preferred over IMDSv1 as if addresses some of its shortcomings (e.g. improved security against SSRF attacks, fine-grained access control, flexibility in authentication configuration via session tokens)
- there may be particular situations in which users may opt for v1 (e.g. compatibility of older systems, minimal security concerns in an isolated environment), however I suspect these don't apply for the majority of the audience.
- implementation wise, we shall stick to our config file option i.e. `disableIMDSv1` as it matches [other AWS APIs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-ec2-imds.html#environments-cfg-ec2-imds.namespace). We just need to have this set to `true` by default.

**Comment by jpmcb** [comment]
The Bottlerocket team is definitely interested in this feature - please let me know if y'all need any help testing/validating!! 😄
