### ISSUE TITLE
[CRITICAL Bug] Can not work with 1.21 clusters

### ISSUE THREAD

**Issue by AndrewFarley** [weaveworks/eksctl#6399]
This is a bug, someone aggressively removed 1.21 from eksctl, which now results in the following when managing some 1.21 clusters.  In the future, please do not be so aggressive to remove old versions.  I've temporarily reverted to an old version of EKSCTL to manage this, but I shouldn't have to do that.  Can we keep support around for old versions for say, at least 3-6 months after they go EOL at least?

Thanks guys

```bash
$ eksctl create nodegroup --config-file=./prod.yaml --include "primary-on-demand-usw2a-v1"
Error: could not create cluster provider from options: invalid version, 1.21 is no longer supported, supported values: auto, default, latest, 1.22, 1.23, 1.24, 1.25
see also: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
```

**Comment by kingdonb** [comment]
FYI, Amazon supports Kubernetes minor releases for 6 months to a year longer than Kubernetes upstream does.

The Kubernetes Upstream has already moved on to 1.24, and 1.23 is EOL with no further security releases.

Thank you for the feedback; there may be a misalignment here. I have eksctl installed via `brew` and tried to pin mine to the previous version, but wasn't immediately able to figure out how to do this:

```
$ brew install eksctl
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
Warning: eksctl 0.132.0 is already installed and up-to-date.
To reinstall 0.132.0, run:
  brew reinstall eksctl

(⎈|howard-stage:simplest-commitbee):~ (macos-homebrew *|u=)$ brew install eksctl@0.131.0
Warning: No available formula with the name "eksctl@0.131.0".
==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for eksctl@0.131.0.
```

Can you give a hint how you did this? I'm not in a position to revert the update myself, and this will help whoever finds the issue next.

**Comment by yuxiang-zhang** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#available-versions 1.21 is no longer supported by EKS

**Comment by AndrewFarley** [comment]
> Can you give a hint how you did this? I'm not in a position to revert the update myself, and this will help whoever finds the issue next.

How I fixed this?  I had to go here in Github in releases and grab an old release that was the release immediately before EKSCTL had removed 1.21 support.

**Comment by AndrewFarley** [comment]
> https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#available-versions 1.21 is no longer supported by EKS

Yet, 1.21 clusters still exist.  Amazon will do a gradual process over a few months, sometimes up to 6 months long as they slowly automatically upgrade peoples clusters.  Meanwhile, during that period of 6 months for people that haven't upgraded they can no longer use the latest release of EKSCTL because of this aggressive force to remove a previous version.  Please consider changing this mindset

**Comment by Himangini** [comment]
@AndrewFarley We follow the [Amazon EKS end of support](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) calendar and open issues in `eksctl` like #6201 , #6202 in advance to let the community know this is upcoming. This is not a bug, but expected behavior in `eksctl`.

**Comment by AndrewFarley** [comment]
> @AndrewFarley We follow the [Amazon EKS end of support](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) calendar and open issues in `eksctl` like #6201 , #6202 in advance to let the community know this is upcoming. This is not a bug, but expected behavior in `eksctl`.

I understand @Himangini, I'm suggesting that in the future alter your behaviour to remove old versions perhaps 3 months after the official EOL in order to support some lagging clusters.  I believe that would deal with the straggler clusters that don't upgrade the second EOL occurs.

**Comment by Himangini** [comment]
> > @AndrewFarley We follow the [Amazon EKS end of support](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) calendar and open issues in `eksctl` like #6201 , #6202 in advance to let the community know this is upcoming. This is not a bug, but expected behavior in `eksctl`.
> 
> I understand @Himangini, I'm suggesting that in the future alter your behaviour to remove old versions perhaps 3 months after the official EOL in order to support some lagging clusters. I believe that would deal with the straggler clusters that don't upgrade the second EOL occurs.

We'll continue to follow the [Amazon EKS end of support](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) calendar. `eksctl` doesn't provide support for straggler clusters after the official EOL. Customers may wish to use older versions of `eksctl` at their discretion. Please open an AWS support ticket if you're having issues with clusters with outdated versions.

**Comment by AndrewFarley** [comment]
That's a pretty myopic and disappointing point of view

**Comment by kingdonb** [comment]
For reference, [0.131.0](https://github.com/weaveworks/eksctl/releases/tag/v0.131.0) removed support for EKS 1.21, and this was mentioned in the release notes.

The previous release is [0.130.0](https://github.com/weaveworks/eksctl/releases/tag/v0.130.0) – the current release is 0.135 last week. For additional reference, you can use brew to install old versions of a formula.

Homebrew just doesn't make it very easy, (on purpose) – you have to use `brew formula` to find out where the formula is on disk, and use git to retrieve the old version.

Here's how you can do it:

```
$ brew formula eksctl
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/eksctl.rb
$ cd /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/
$ git pull origin master
$ git log --oneline -- eksctl.rb
...
6396be4f6c3 eksctl: update 0.130.0 bottle.
$ git checkout 6396be4f6c3 -- eksctl.rb
$ brew uninstall --ignore-dependencies eksctl
$ brew install eksctl.rb
```

Thanks for the feedback!
