### ISSUE TITLE
name is not required when config is used

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#641]
We have this right now
```
Usage: eksctl delete cluster [flags]

General flags:
  -n, --name string          EKS cluster name (required)
  -r, --region string        AWS region
  -w, --wait                 wait for deletion of all resources before exiting
  -f, --config-file string   load configuration from a file 
```

We could say something like this
```
  -n, --name string          EKS cluster name (required, unless --config-file/-f is given)
```
But perhaps simpler is better
```
  -n, --name string          EKS cluster name
```
If someone doesn't pass `--name`, they will get an error anyway.

**Comment by whereisaaron** [comment]
Side comment: Some commands use `--name <cluster name>` and some `--cluster <cluster name>`. I can't tell you which because I'm endlessly confused and just guess each time 😄. Could we take a consistent approach?

**Comment by errordeveloper** [comment]
Yes, nodegroup commands take `--cluster`, because there `--name` refers to nodegroup's name. Having `--cluster-name` and `--nodegroup-name` would make it more explicit, but keeping backwards compatible flags around may become a cause for confusion. I think this is separate discussion, and I'm not so sure if it's a high priority one. I would rather make sure we have consistent support for `--config-file`, fix more pressing issue (like deletions), and get closer to `eksctl apply` and a beta API.

**Comment by lucioveloso** [comment]
I removed the `(required)` from the all cluster name help message scenarios and I made an initial PR.

Is that what you expect @errordeveloper?

**Comment by errordeveloper** [comment]
Thank you!
