### ISSUE TITLE
[Help] Skip eksctl validation

### ISSUE THREAD

**Issue by vezaynk** [weaveworks/eksctl#6454]
### What help do you need?

I'm trying to set a purposefully bad request to EKS via eksctl but it is being caught in client-side validation. It seems to be possible to disable it, but I can't figure out how.

I see a flag being set here: https://github.com/weaveworks/eksctl/blob/af3d0a0d702bb19adabe3df5705054f434dc332a/pkg/ctl/cmdutils/cmd.go#L128

How can I override it?

**Comment by cPu1** [comment]
@vezaynk that field is not configurable by any flag or ClusterConfig field. Which validation are you trying to get around? The validations exist to prevent users from creating misconfigured clusters.
