### ISSUE TITLE
improve output messages in 'eksctl update cluster'

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#646]
Right now we print this
```
[ℹ]  using region us-east-2
[ℹ]  re-building cluster stack "eksctl-sample-cluster"
[ℹ]  (dry-run) updating stack to add new resources [ClusterSharedNodeSecurityGroup IngressInterNodeGroupSG] and ouputs [ServiceRoleARN SharedNodeSecurityGroup]
[ℹ]  checking security group configuration for all nodegroups
[✖]  found 1 nodegroup(s) (0) without shared security group, cluster networking maybe be broken
[✖]  it's recommended to create new nodegroups, then delete old ones
```
1. there is typo - `ouputs`
2. it's not clear that `--dry-run=false` has to be used

And with `--dry-run=false` we print this
```
[ℹ]  using region us-east-2
[ℹ]  re-building cluster stack "eksctl-sample-cluster"
[ℹ]  updating stack to add new resources [ClusterSharedNodeSecurityGroup IngressInterNodeGroupSG] and ouputs [ServiceRoleARN SharedNodeSecurityGroup]
[ℹ]  checking security group configuration for all nodegroups
[✖]  found 1 nodegroup(s) (0) without shared security group, cluster networking maybe be broken
[✖]  it's recommended to create new nodegroups, then delete old ones
```
Which also doesn't make it clear if all is well at the end and if shared SG gets added or what happens really.

**Comment by venkyvb** [comment]
@errordeveloper Is this issue still open? If yes, I would like to work on this.

**Comment by errordeveloper** [comment]
Hi! Yes, please do feel free to start on this, and open a WIP PR, so you
can get feedback early enough :)

**Comment by venkyvb** [comment]
Re 1) This can easily be corrected
Re 2) From the code it seems like --dry-run is now deprecated and --approve is to be used. 

Also when I analyze the usage of the --dry-run seems like this is just used in the output and it doesn't seem to control the StackResource creation itself. Proposal would be to remove this flag in the output itself.

**Comment by michaelbeaumont** [comment]
Closing, quite old, see also #476
