### ISSUE TITLE
new documentation 

### ISSUE THREAD

**Issue by Kiran3002** [weaveworks/eksctl#6466]

**Comment by Kiran3002** [comment]
https://docs.google.com/document/d/1mEpiK45M8hYkzlgLJ7SKrbON3Sjejz5z/edit?usp=drivesdk&ouid=101513486375632796726&rtpof=true&sd=true

**Comment by cPu1** [comment]
@Kiran3002, I don't think you meant to include a Google Docs link here. I'm closing the issue, please feel free to open a new issue with more details, redacting any private information.
