### ISSUE TITLE
support cluster name as argument

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#65]
it's too easy to forget to specify `--cluster-name <name>` and type `eksctl create cluster <name>` instead, we should probably support simple argument mode, because `kops` and `kubicorn` support this also.

**Comment by christopherhein** [comment]
What do you think about also changing it to `—name` to be consistent with the `aws eks` cli?

**Comment by errordeveloper** [comment]
Turns out `kops` also uses `--name`, so we should certainly use the same too. Adding this to beta milestone.
