### ISSUE TITLE
[Help] bootstrapping flux on cluster create fails with wrong flux version 

### ISSUE THREAD

**Issue by chris-saunders-vmware** [weaveworks/eksctl#6562]
getting this error when trying to add flux to my cluster via eksctl
"running pre-flight checks
Error: running Flux pre-flight checks: found flux version 0.13.2, eksctl requires >= 0.13.3"

I'm not specifying version, where does eksctl pull this from?

`gitops:`
  flux:
    gitProvider: github      # required. options are github, gitlab or git
    flags:                   # required. arbitrary map[string]string for all flux args.
    # these args are not controlled by eksctl. see https://fluxcd.io/docs/get-started/ for all available flags
      owner: "user"
      repository: "aws-workshop-module1"
      private: "false"
      personal: "true"
      branch: "main"
      namespace: "flux-system"
      path: "clusters/development3"
      read-write-key: "true"``

**Comment by Himangini** [comment]
@chris-saunders-vmware the latest [release](https://github.com/weaveworks/eksctl/releases/tag/v0.139.0) should fix this issue. Please follow the docs [here](https://eksctl.io/usage/gitops-v2/) for more information 👍🏻
