### ISSUE TITLE
Complete config file documentation

### ISSUE THREAD

**Issue by trondhindenes** [weaveworks/eksctl#658]
**Why do you want this feature?**
To avoid looking thru lots of config example files in order to find the parameter i'm looking for

**What feature/behavior/change do you want?**
A complete documentation of the available parameters in config files, for example by listing all cmd line flags/options to the respective config file setting

Right now, I'm looking for how to set the "ssh access" flag using a config file. I can't find it. To fix this, I would either a) create an example config with _all_ the things in it, or b) put a table in the readme with clear mappings between cmd line flags and their respective config file attribute. Yaml supports comments, so there's no reason not to fill an example file with descriptions etc. It would make it a lot easier to get going with config file-based deployments.

**Comment by whereisaaron** [comment]
Ref: #508

Yeah, using a config file is very challenging at the moment and requires groking a lot of source code. It would be nice to have a sample config file that had every available option in it with a comment.

**Comment by errordeveloper** [comment]
@trondhindenes thanks for reporting this!

This is largely dependent on new website, because current website is just single HTML page, and we will need a more structured sort of website for this.

I believe this is covered by #508 and #633 actually. Do you think it's okay to close this?

**Comment by trondhindenes** [comment]
I'm personally a fan of just looking it up in repo markdown, but I totally understand that there's always a risk of that info being outdated. The ability to export config as mentioned in #633. Looks like a good way of doing it. Okay to close.

**Comment by errordeveloper** [comment]
> I'm personally a fan of just looking it up in repo markdown

So actually a website with section is not your kind of thing? Or you are thinking example in repo/website vs something interactive like being suggested in #633?
