### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#666]
Is there a way to generate a Changelog as part of the release process.
This would make things easier than sifting through commits

**Comment by errordeveloper** [comment]
@cdenneen we do that already, it's on every release [release page](https://github.com/weaveworks/eksctl/releases/tag/0.1.25), did you not look there?

**Comment by cdenneen** [comment]
@errordeveloper yeah just found it... was looking in the repo itself but found it on release page so that is good enough... thanks for the quick response.

**Comment by errordeveloper** [comment]
@cdenneen cheers!
