### ISSUE TITLE
scale down node group by terminating cordoned node

### ISSUE THREAD

**Issue by elbek** [weaveworks/eksctl#6661]
I have a node group with 5 servers and would like scale down to 4. But to scale down I want to terminate particular node from the node group, not any one. I found that node that needs to go and I did drain and cordon node. Now How can I tell `eksctl` to terminate this particular node from node group? 

Thanks.

**Comment by TiberiuGC** [comment]
Hi @elbek 👋 - unfortunately, `eksctl` does not provide this level of control. To give you some context:

- when scaling down self-managed nodegroups -> [`asg:UpdateAutoScalingGroup`](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_UpdateAutoScalingGroup.html) is being called and [default termination policy](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-termination-policies.html#default-termination-policy) is being used.
- when scaling down EKS-managed nodegroups -> [`eks:UpdateNodegroupConfig`](https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateNodegroupConfig.html) is being called and we're editing [Nodegroup ScalingConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-nodegroup-scalingconfig.html). In this case, similar to above, the termination policies of the underlying ASG are being used.

I don't see any particular policy that would prioritise a drained & cordoned node.
