### ISSUE TITLE
[Feature] Update logic for determining whether add-ons support arm64 architecture

### ISSUE THREAD

**Issue by otterley** [weaveworks/eksctl#6676]
Every time a customer adds Graviton capacity to a cluster, `eksctl` checks to see whether several EKS add-ons are the latest version. This is arguably unnecessary today, since EKS add-ons have supported arm64 for quite some time. This presents an impediment for customers adding Graviton nodes and can dissuade them from adding Graviton capacity because updating the add-ons might have unknown adverse consequences.

Let's update the `DoAddonsSupportMultiArch()` function (which hasn't been updated in 2 years) to check whether the currently-installed addons actually support arm64, instead of just checking whether they are the latest version. This will allow customers to attach Graviton nodes with confidence and without having to make unnecessary changes to the cluster.

**Comment by otterley** [comment]
This check may also have outlived its usefulness - it may well be that all add-ons that can be installed for any version of EKS supported today support arm64, making this check moot.

**Comment by cPu1** [comment]
Good call out. While `DoAddonsSupportMultiArch` does check whether `aws-node` is on a version what supports multi-arch, it only checks whether CoreDNS and kube-proxy are the latest version, and that requires an unnecessary upgrade.

When that check was added, I think it wasn't clear which version of CoreDNS and kube-proxy added support for multi-arch, but as you pointed out, that check may not be relevant anymore. But we'd want to have some check to ensure the installed addons support multi-arch. 

The PodSpec for the latest versions of CoreDNS and kube-proxy both have a `nodeAffinity` that  matches nodes that are either `amd64` or `arm64`, so I propose using this information to determine whether the core addons support multi-arch or not. We'll work on this soon.

**Comment by hassaanakram** [comment]
Hi @cPu1 
I'd like to work on it. Plus I like the idea of using the ```nodeAffinity``` field for this check. Previously, I was going to propose using the EKS ```DescribeAddonVersions``` API, but this is better.

Let me know if I can take it up. 

Thanks!

**Comment by cPu1** [comment]
Hi @hassaanakram. I have already started looking into this issue. If you're able to find any other issues from the backlog that you'd like to pick, please comment on it and let us know.
