### ISSUE TITLE
Possible CloudFormation consideration, need cluster complete before creating ASGs

### ISSUE THREAD

**Issue by whereisaaron** [weaveworks/eksctl#668]
Saw this about node kubelets failing, just noting that if you deploy a cluster and a node group at the same timing, CF might not know to complete the cluster first. This may not be an issue for `eksctl` since separate stacks are used, and I guess one is created after the previous finishes?

https://github.com/awslabs/amazon-eks-ami/issues/178#issuecomment-466265867

> After banging my head against the wall for a few hours, I discovered adding DependsOn: Cluster to AutoScalingGroup and LaunchConfiguration fixed it.

**Comment by errordeveloper** [comment]
Feel free to re-open, if you think there is still something to be done about this.
