### ISSUE TITLE
App Mesh add-on

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/eksctl#669]
We could create an add-on similar to the CoreDNS one, that deploys the App Mesh components:
* Admission controller https://github.com/aws/aws-app-mesh-inject
* CRD controller https://github.com/aws/aws-app-mesh-controller-for-k8s

The add-on should implement the same install steps as https://github.com/stefanprodan/appmesh-eks/blob/master/install.sh

The installer should do the following:
* creates the appmesh-system namespace
* generates a certificate signed by Kubernetes CA
* registers the App Mesh mutating webhook
* deploys the App Mesh webhook in appmesh-system namespace
* deploys the App Mesh CRDs
* deploys the App Mesh controller in appmesh-system namespace
* creates a mesh called global (TBD)

Ref: https://github.com/aws/aws-app-mesh-inject/issues/3

**Comment by errordeveloper** [comment]
Yes, I think we should review most wanted add-ons and provide simple command for installing those before we have proper add-on management tooling in place.

**Comment by stefanprodan** [comment]
So it will be `eksctl utils install-appmesh` ?

**Comment by errordeveloper** [comment]
Yes, and perhaps we can provide `eksctl utils install-helm` and few other similar things.

**Comment by michaelbeaumont** [comment]
Closing, comment if still relevant
