### ISSUE TITLE
Support for Amazon EKS 1.12 Clusters

### ISSUE THREAD

**Issue by christopherhein** [weaveworks/eksctl#679]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
Everyone should be able to use the latest EKS version. :)

https://github.com/aws/containers-roadmap/issues/24

**What feature/behavior/change do you want?**
Support for `create`'ing and `update`'ing existing clusters with Kubernetes 1.12.

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by whereisaaron** [comment]
It looks like it is always the case we need to update eksctl before we can upgrade to a new version. Is there sufficient AW API to enable discovering the available control plane version and matching AMI versions? Or it inevitably a manual task?

**Comment by tabern** [comment]
@whereisaaron I think this will solve the problem you are describing https://github.com/aws/containers-roadmap/issues/231

**Comment by whereisaaron** [comment]
That sounds great for the AMI versions @tabern. @errordeveloper also [mentioned](https://github.com/weaveworks/eksctl/pull/680#issuecomment-477825608) that there is also currently no way to know what control plane versions are available? (to CF)
