### ISSUE TITLE
improve handling of deletions, add dry-run

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#682]
We currently have it done in a rather complicated way, we tend to try deleting things and then retry. We should instead collect a list of things we want to delete first and then try deleting those things. This will make the logic cleaner, but also help us to implement dry-run capability.

**Comment by errordeveloper** [comment]
It's important to add dry-run as we are going to allow deleting multiple NGs with a config file. Currently CLI works okay for single NG, as user types it all explicitly.

**Comment by mreferre** [comment]
I am not sure if dry-run will cut it but I believe it would be useful to have some sort of delete/termination protection mechanism similar to what we have in Cloudformation (or actually leverage the CF mechanism?). Deleting a cluster today is way to easy and we should consider make it less error prone. Dry run may help but I am not sure it will be enough.

**Comment by errordeveloper** [comment]
Yes, I think we should have deleting protection mode and have it enabled by
default. We will ultimately need to use CloudFormation for that.

**Comment by errordeveloper** [comment]
Closed via #695.
