### ISSUE TITLE
eksctl utils write-kubeconfig always creates a new context when using aws-vault with MFA

### ISSUE THREAD

**Issue by alexclifford** [weaveworks/eksctl#691]
**What happened?**
Each time I run `aws-vault exec test -- eksctl utils write-kubeconfig --name foo-bar-12345` a new context is written to `~/.kube/config`.

**What you expected to happen?**
Only a single context is used.

**How to reproduce it?**
This is likely because of `aws-vault` used in conjunction with MFA.

```
aws-vault exec test -- eksctl utils write-kubeconfig --name foo-bar-12345
```

**Anything else we need to know?**

**OS:** macOS 10.14.3
Version v1.11.9 of **kubectl** was explicitly installed to match AWS EKS version.
All other binaries installed via Homebrew.

Each context is unique by auth:

```
⇒  aws-vault test exec -- kubectl config get-contexts
CURRENT   NAME                                                                  CLUSTER                                           AUTHINFO                                                              NAMESPACE
          1554164462851493000@foo-bar-12345.us-west-2.eksctl.io   foo-bar-12345.us-west-2.eksctl.io   1554164462851493000@foo-bar-12345.us-west-2.eksctl.io
          1554168068482105000@foo-bar-12345.us-west-2.eksctl.io   foo-bar-12345.us-west-2.eksctl.io   1554168068482105000@foo-bar-12345.us-west-2.eksctl.io
*         1554168098178208000@foo-bar-12345.us-west-2.eksctl.io   foo-bar-12345.us-west-2.eksctl.io   1554168098178208000@foo-bar-12345.us-west-2.eksctl.io
```

My aws-vault `test` profile assumes an Administrator role with full AWS API access, and enforces MFA.

**Versions**
Please paste in the output of these commands:
```
⇒  eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.26"}
⇒  uname -a
Darwin picard.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
⇒  aws-vault exec test -- kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
⇒  ls -lha /usr/local/bin/heptio-authenticator-aws
lrwxr-xr-x  1 alex  admin    73B Apr  2 12:20 /usr/local/bin/heptio-authenticator-aws -> ../Cellar/eksctl-aws-iam-authenticator/0.3.0/bin/heptio-authenticator-aws
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by whereisaaron** [comment]
Hi @alexclifford this probably correct behavior, as each time you assume the role it looks like `aws-vault` is using an new per-session user name. It actually looks like it us using a unix timestamp as the session user name. 

Since it is a new user name each time, `eksctl utils write-kubeconfig` must create a new context for that new user name. I think you need to configure `aws-vault` to use a consistent session user name.

**Comment by alexclifford** [comment]
@whereisaaron while I understand aws-vault sessions are at play here, I'm still not sure why `eksctl utils write-kubeconfig` creates a new entry **each run**, even if the aws-vault session hasn't changed. The timestamp number in the context doesn't match up with my aws-vault session name either.

**Comment by alexclifford** [comment]
There is nothing session specific about the heptio-authenticator-aws config written to `~/.kube/config`:
```
 users:
  - name: 1554171958285363000@foo-bar-12345.us-west-2.eksctl.io
   user:
     exec:
       apiVersion: client.authentication.k8s.io/v1alpha1
       args:
       - token
       - -i
       - foo-bar-12345
       command: heptio-authenticator-aws
       env: null
```

Is the actual authentication happening via `aws-vault exec test -- heptio-authenticator-aws token -i foo-bar-12345`?

I can rename the context name and username after `eksctl utils write-kubeconfig` has been run and it still works. Is there some other sorcery at play here? It sounds like eksctl should be able to hardcode this if I chose to.

```
⇒  aws-vault exec test -- kubectl config get-contexts
CURRENT   NAME                                                   CLUSTER                                           AUTHINFO                                               NAMESPACE
*         alex@foo-bar-12345.us-west-2.eksctl.io   foo-bar-12345.us-west-2.eksctl.io   alex@foo-bar-12345.us-west-2.eksctl.io
⇒  aws-vault exec test -- kubectl get ns
NAME          STATUS    AGE
default       Active    3d
kube-public   Active    3d
kube-system   Active    3d
```

**Comment by alexclifford** [comment]
The problem with this though is that if I switch context the `~/.kube/config` file gets reset from:
```
 users:
  - name: alex@foo-bar-12345.us-west-2.eksctl.io
   user:
     exec:
       apiVersion: client.authentication.k8s.io/v1alpha1
       args:
       - token
       - -i
       - foo-bar-12345
       command: heptio-authenticator-aws
       env: null
```
to:
```
 users:
  - name: alex@foo-bar-12345.us-west-2.eksctl.io
   user: {}
```

**Comment by whereisaaron** [comment]
> I'm still not sure why eksctl utils write-kubeconfig creates a new entry each run

It definitely doesn't. It creates or updates a context - for the current IAM user (`aws sts get-caller-identity`) and the specified cluster. I can run it over and over and I still only have one entry. If the entry already exists, it will update the existing entry with a fresh token (which might have expired).

I don't know `aws-vault` but looks like it is creating a new session and a new session user name every time you run it. If you can fix that, you should be sweet.

It is unusual, in your examples, you have `heptio-authenticator-aws` rather than AWS's `aws-iam-authenticator` which is what AWS supplies for EKS access. But maybe you have a special set-up.

**Comment by errordeveloper** [comment]
hi @alexclifford! thanks for reporting this. As @whereisaaron pointed out, it's to do with that we try to use your username.

This functionality is reliant on this one simple function:

https://github.com/weaveworks/eksctl/blob/d76ef8a6dd60f51d60d9a8816f152c8ae3c49394/pkg/eks/auth.go#L140-L145

This function works for AWS ARNs, but clearly there is something different in the case of vault.

If you use `--verbose=4` you should get the ARN printed out, I'm curious to see how Vault presents it, so please share it here. If you like, do feel free to play around by modifying that function and find a way to fix it, so it handles Vaults format, as long as it keeps handling native ARNs as it currently does.

Alternative fix would be to add `--context-name` flag in `eksctl utils write-kubeconfig`.

**Comment by errordeveloper** [comment]
> It is unusual, in your examples, you have `heptio-authenticator-aws` rather than AWS's `aws-iam-authenticator` which is what AWS supplies for EKS access.

Yes, they do supply `aws-iam-authenticator`, but if you are to look for latest released version, you will find that the binaries are still [`heptio-authenticator-aws`](https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.3.0). We have #169 to track this, latest release was `v0.4.0-alpha.1` in October, and it's unclear which revision is currently being shipped.

**Comment by whereisaaron** [comment]
Oh I use the binaries from the [AWS EKS 'Getting Started'](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html) page, which are called `aws-iam-authenticator`.

They refuse to reveal what version they are:
```
$ aws-iam-authenticator version
{}
```
Though they are in folders matching the k8s version, and are updated with each EKS release, e.g.
> Linux: https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator

**Comment by alexclifford** [comment]
@whereisaaron @errordeveloper thanks very much for pointing out the verbose flag and how the username was built, that pointed me in the right direction.

I had not set a `role_session_name` in my `~/.aws/config` file as per https://docs.aws.amazon.com/cli/latest/topic/config-vars.html so one was being automatically generated each time.

**Comment by errordeveloper** [comment]
@alexclifford glad to hear you have resolved this! If you want to blog about what you didn't, I'd very keen to read your post :)

**Comment by ts094r-att** [comment]
Hi All,
when i try to create a config file using given command getting the below error message. please assist.

PS C:\Users\abc> aws-vault exec default -- eksctl utils write-kubeconfig --cluster=att-offers --region=us-east-1                                                                        
aws-vault: error: exec: Error getting temporary credentials: profile default: credentials missing
