### ISSUE TITLE
Option to disable NAT gateway

### ISSUE THREAD

**Issue by mcfedr** [weaveworks/eksctl#694]
**Why do you want this feature?**

Creating the NAT gateway is an unneeded cost when nodes are going to be in public nodegroups anyway.

**What feature/behavior/change do you want?**

I dont know if its best to disable private subnets and the gateway with the same flag, probably makes it a much more complicated feature request, but is an option.

I'm thinking just '--no-nat-gateway' for create cluster.

**See also**

Seems that gateway provisioning is of limited usefulness anyway, https://github.com/weaveworks/eksctl/issues/392

**Comment by cdenneen** [comment]
@mcfedr you can have public subnets with Managed-NAT (really depends upon VPC topology and how network routing tables are configured) as well in some cases so maybe an option to disable NAT gateway should be completely independent of public/private use case.

**Comment by errordeveloper** [comment]
> I'm thinking just '--no-nat-gateway' for create cluster.

@mcfedr yes, something of that sort, but let's consider making this a config file option to begin with, as it's relatively advanced.

Perhaps something like
```YAML
vpc:
   natGateway:
     mode: <none|single|ha>
```
We might want to provide more options here in the future, such as using pre-allocated IPs or flexible per-zone config, so seems plausible to add a sub-section.

> an option to disable NAT gateway should be completely independent of public/private use case

@cdenneen I suppose it could be, at least in theory, as one should be able to deploy private nodegroup   without access to the internet... however until recently EKS control plane was only reachable via the internet, and that's not been fixed. One other thing to look into is ECR, as all of the default add-on images are in ECR.

**Comment by mcfedr** [comment]
Maybe the simple option then is '--no-private-subnets' - I guess for me, this was an unexpected cost, and one i dont need, and i wanted a simple way to disable it - in my mind the private subnets are a more advanced option - if it was me i'd default to not having private subnets, but seems that would be a bigger change as it changes the existing behaviour

**Comment by errordeveloper** [comment]
We have to have all subnets in place, because one should be able to create
private nodegroups at any time, and initially EKS didn't let you add
subnets (this may have changed rectantly, or it's about to change).

Quick question - do you use only flags, not the config file?

**Comment by mcfedr** [comment]
So far I've been using the commands, but actually very much in favour of the config file approach
