### ISSUE TITLE
Proxy Request URLs don't work

### ISSUE THREAD

**Issue by bensussman** [weaveworks/eksctl#699]
**What happened?**
`curl` requests through the port created with `kubectl proxy` work fine for service description endpoints but do not work for `proxy` endpoints. I am referring specifically to "apiserver proxy URLs" described here: https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls 

**What you expected to happen?**
I expect apiserver proxy URLs to work in my EKS cluster.

**How to reproduce it?**
1. Create a new EKS cluster using: `eksctl create cluster -n proxy-test -N 1 --ssh-access --ssh-public-key my-aws-public-key`
2. When finished, create a service and deployment that listens on port 80. Here is the yaml i used with `kubectl apply -f hello-world.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hw-container
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
  - name: www
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: hello-world
  type: ClusterIP
```
3. You can verify that this service is up and serving traffic by getting the clusterIP from `kubectl get svc`, and then ssh-ing to the one node by doing `kubectl get nodes -owide` and then `ssh ec2-user@<ip-from-prev-cmd>`, and then while on the node doing `curl <cluster-ip-from-kubectl-get-svc>`. When you do this, i see a nice `<title>Welcome to nginx!</title>` html response. 
4. Exit the `ssh` session, and run `kubectl proxy`. This should proxy `localhost:8001` to the cluster api.
5. run `curl "localhost:8001/api/v1/namespaces/default/services/hello-world/"` You should see a nice output of information about the hello world service. `kubectl proxy` is working great!
6. run `curl "localhost:8001/api/v1/namespaces/default/services/hello-world:www/proxy/"` THIS REQUEST HANGS AND THEN FAILS with:
```
Error: 'dial tcp 192.168.11.3:80: connect: connection timed out'
Trying to reach: 'http://192.168.11.3:80/'
```
This is unexpected, i would expect this curl to work and to print out the same `<title>Welcome to nginx!</title>` html response from step 3 above. I am able to use `kops` to create a cluster where this DOES work, so it seems like an `eksctl` and/or `eks` issue.

Ultimately, my goal is to interact internal services within my cluster programmatically from golang using `ProxyGet` https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/service_expansion.go#L30 but I believe that these steps to recreate reveal the issue. If i can get these steps to work, it will likely fix the `ProxyGet` issues i'm having as well.

**Anything else we need to know?**
Should be using vanilla everything, i am on OSX 10.14.3, i used `brew` to install `eksctl`.

**Versions**
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.23"}
$ uname -a
Darwin benno-mbp 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```
$ eksctl create cluster -n proxy-test -N 1 --ssh-access --ssh-public-key spell-shared
[ℹ]  using region us-west-2
[ℹ]  setting availability zones to [us-west-2a us-west-2b us-west-2d]
[ℹ]  subnets for us-west-2a - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for us-west-2b - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for us-west-2d - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng-a0af582d" will use "ami-0c28139856aaf9c3b" [AmazonLinux2/1.11]
[ℹ]  SSH public key file "spell-shared" does not exist; will assume existing EC2 key pair
[ℹ]  found EC2 key pair "spell-shared"
[ℹ]  creating EKS cluster "proxy-test" in "us-west-2" region
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-west-2 --name=proxy-test'
[ℹ]  creating cluster stack "eksctl-proxy-test-cluster"
[ℹ]  creating nodegroup stack "eksctl-proxy-test-nodegroup-ng-a0af582d"
[ℹ]  --nodes-min=1 was set automatically for nodegroup ng-a0af582d
[ℹ]  --nodes-max=1 was set automatically for nodegroup ng-a0af582d
[✔]  all EKS cluster resource for "proxy-test" had been created
[✔]  saved kubeconfig as "/Users/ben/.kube/config"
[ℹ]  nodegroup "ng-a0af582d" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "ng-a0af582d"
[ℹ]  nodegroup "ng-a0af582d" has 1 node(s)
[ℹ]  node "ip-192-168-3-221.us-west-2.compute.internal" is ready
[ℹ]  kubectl command should work with "/Users/ben/.kube/config", try 'kubectl get nodes'
[✔]  EKS cluster "proxy-test" in "us-west-2" region is ready
```

**Comment by errordeveloper** [comment]
> run curl "localhost:8001/api/v1/namespaces/default/services/hello-world/" You should see a nice output of information about the hello world service. kubectl proxy is working great!

Yes, just access the API. (As we discussed on Slack).

> run curl "localhost:8001/api/v1/namespaces/default/services/hello-world:www/proxy/" 

That means that EKS cannot access pod on that port. Which is arguably a feature, at present we only allow port 443 and all ports above 1025, which is something that originates from [the official EKS nodegroup temple](https://github.com/awslabs/amazon-eks-ami/blob/2caf69b451b9f18126253f70e742075a3b1aa818/amazon-eks-nodegroup.yaml#L220-L262).

I do think it's a wrong feature and we should fix it, I'll open a PR to fix it and we can discuss there.

@christopherhein @mhausenblas would either of you have an opinion on this? Opening all ports between EKS and nodes/pods to me seems like a safe thing to do.
