### ISSUE TITLE
Add config file options to enable EKS control plane logging to CloudWatch

### ISSUE THREAD

**Issue by whereisaaron** [weaveworks/eksctl#704]
**Why do you want this feature?**
We want to see the EKS control plane logs for monitoring, troubleshooting, and security audit.

**What feature/behavior/change do you want?**
The ability to enable/disable in the config file, each of the [five control plane log types available in EKS](https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html):
- `api`
- `audit`
- `authenticator`
- `controllerManager`
- `scheduler`

Documentation on EKS control plane logging API and CLI commands:
https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html

`aws eks --region us-west-2 update-cluster-config --name prod \
--logging '{"clusterLogging":[{"types":["api","audit","authenticator","controllerManager","scheduler"],"enabled":true}]}'`

Ref: https://github.com/aws/containers-roadmap/issues/26

**Comment by errordeveloper** [comment]
Thanks for opening this, Aaron! I'd like to do this soon, but will need to update goformation first, and ewe need to think about what we should enable by default.

**Comment by StevenACoffman** [comment]
Ref: awslabs/goformation#198

**Comment by JasonSwindle** [comment]
Any progress on this? :)

**Comment by StevenACoffman** [comment]
ref aws/containers-roadmap#242
Nope. 
> As soon as this is in CloudFormation (and the new [resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) is published, we can get it included in goformation.
> 
> You can run `go generate` in your goformation repo directory to update goformation to the latest resource specification (EKS logging isn't there as of right now) - or wait for our CI job to automatically update goformation and release a new version.

**Comment by errordeveloper** [comment]
We are going to enable this by calling EKS API directly. Hopefully in the next release.

**Comment by whereisaaron** [comment]
Wise move @errordeveloper! Hoping for CloudFormation to catch up with API changes is a mug's game 😢. Like I'm the mug still holding out hope for EIP tags, we all gotta dream 🤣

**Comment by errordeveloper** [comment]
@whereisaaron see #778 =)

**Comment by cdenneen** [comment]
@whereisaaron haha I’ve raised this to my AWS account team
