### ISSUE TITLE
eksctl get cluster returns ResourceNotFoundException while cluster is provisioning

### ISSUE THREAD

**Issue by oneilcin** [weaveworks/eksctl#715]
**What happened?**

After creating a cluster with:
eksctl create cluster --name cindy1 --region us-east-1
In another terminal session get cluster:
eksctl get cluster --name cindy1 --region us-east-1

It returns a ResourceNotFoundException error for at least a minute before it will return the Creating Status.

eksctl get cluster --name cindy1 --region us-east-1
[✖]  unable to describe control plane "cindy1": ResourceNotFoundException: No cluster found for name: cindy1.
status code: 404, request id: 851e214f-561f-11e9-bd9d-a1debad5d25d

**What you expected to happen?**
I am able to see the CREATE_IN_PROGRESS when I run eksctl utils describe-stacks --name cindy1 --region us-east-1.  I would expect that eksctl get cluster would return a STATUS CREATING instead of the error for the initial period.

**How to reproduce it?**
After creating a cluster with:
eksctl create cluster --name cindy1 --region us-east-1
In another terminal session get cluster:
eksctl get cluster --name cindy1 --region us-east-1

It returns a ResourceNotFoundException error for at least a minute before it will return the Creating Status.

Keep executing the eksctl get cluster command in the second terminal window.

**Anything else we need to know?**
We want to run the eksctl commands asynchronously, without blocking.
We are using a downloaded binary

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.23"}
$ uname -a
We are using alpine linux
$ kubectl version
1.11.3
```
Also include your version of `heptio-authenticator-aws`

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by errordeveloper** [comment]
Hi @oneilcin! Thanks for reporting this, something we should definitely fix. The reason to this is that `eksctl get cluster` command user EKS API, and not CloudFormation. When `eksctl create cluster` calls CloudFormation to create cluster stack, there is a period of time when VPC and other dependencies are being create before CloudFormation actually creates the EKS cluster itself.
To fix this, we will need make `eksctl create cluster` call CloudFormation API first, i.e. call `stackManager.DescribeStracks` or one of the similar functions.

**Comment by alvarodelvalle** [comment]
Created cluster, waited over 8 hours (sleep 😴), and ran 
`eksctl update cluster --name devops --approve` 
```Error: fetching cluster status to determine update status: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: devops. status code: 404, request id: b5a913d7-30cd-4427-90fb-cbd2d4727f0e```
`❯ eksctl version
0.15.0`
What's going on here??

**Comment by kitsirota** [comment]
I just ran into this issue trying to run the following (describe and update returned not found also)
eksctl utils associate-iam-oidc-provider --cluster=foo --approve

The fix was to specify the region
eksctl utils associate-iam-oidc-provider --region us-east-1 --cluster=foo --approve

**Comment by michaelbeaumont** [comment]
Closing this issue as it's out of date, feel free to open a new issue if this is still a problem or new issues for other, unrelated problems.
