### ISSUE TITLE
Contain AMI Search Based on EKS Account ID for AL2 images

### ISSUE THREAD

**Issue by christopherhein** [weaveworks/eksctl#732]
**Why do you want this feature?**
This could lead to EKS clusters being created with non AWS owned AMIs.

**What feature/behavior/change do you want?**
Current search could include AMIs not AWS owned but made public using the same tags with a more recent created at, the request is to add an additional check for Image searching using `auto` and the `make generate-ami` list to only be AWS owned. *Ubuntu images can be from any account for now*

**Comment by errordeveloper** [comment]
Thanks! This was documented as a TODO one day, but looks like it slipped away.
