### ISSUE TITLE
Hold changes to docs for next release (v1alpha5)

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#738]
We have made a few changes to readme and examples that are not yet part of a release. I'm going to revert these, and we can put those back in once the release is out.

We should find a better way long-term (see #461).

**Comment by martina-if** [comment]
Right, I see. Maybe we can either publish the github pages from a different branch that is updated when we make a release (but then the README, since it's based on master, could be not correct). Or perhaps ask in the PR to open another PR just for docs that we merge after the release.
