### ISSUE TITLE
Feature request: Role option with eksctl utils write-kubeconfig

### ISSUE THREAD

**Issue by knorby** [weaveworks/eksctl#749]
**Why do you want this feature?**
`aws-iam-authenticator`has a [role option on the token command](https://github.com/kubernetes-sigs/aws-iam-authenticator#4-set-up-kubectl-to-use-authentication-tokens-provided-by-aws-iam-authenticator-for-kubernetes) that's used for authentication in the kubeconfigs produced, and it would be useful if `eksctl utils write-kubeconfig` would allow for a role to be used in the produced config. `aws-iam-authenticator` assumes the given role before grabbing a token, which has the benefit of eschewing individual user assignments in the `aws-auth` configmap (see https://github.com/weaveworks/eksctl/issues/625). This would make the `write-kubeconfig` subcommand more useful and allow eksctl to support this approach to authentication.

**What feature/behavior/change do you want?**
A new option flag added to `eksctl utils write-kubeconfig` of a role arn to use for authentication, e.g. `-R --role-arn <ROLE_ARN>`. If included, the `aws-iam-authenticator token` calls in kubeconfigs should add `-r <ROLE_ARN>`.

**Comment by errordeveloper** [comment]
I think it'd be good to add this, for sure, thanks for posting the issue!
I don't know if you might have already discovered a work-around, I can think of two:
- use a profile
- edit the output kubeconfig file

**Comment by knorby** [comment]
I was able to work around it, but yeah, just seemed like a nice feature. I use eksctl to setup kubeconfig as needed on developer machines, through another script, so I was thinking of using a role as kind of an IAM group management strategy; profiles would definitely work for that too, but that wasn't how I was approaching it.
The change looks pretty straightforward. If I get a chance soon, I'll try to take care of it myself :).

**Comment by nikolai-derzhak-distillery** [comment]
Just for collection(feel like on stackoverflow). One more workaround:
```
aws --region $AWS_REGION eks update-kubeconfig --name  $CLUSTER_NAME --role-arn $AWS_ROLE 
```
