### ISSUE TITLE
NAT Gateway should be able to reuse existing EIP

### ISSUE THREAD

**Issue by hden** [weaveworks/eksctl#777]
**Why do you want this feature?**
When communicating with legacy networks via specified IPs, it might be better if we let users manage and reuse EIPs.

**What feature/behavior/change do you want?**
- One should be able to configure one NAT Gateway per az to achieve higher availability.
- One should be able configure existing EIP for each NAT Gateway.
  - If no EIP is specified eksctl should create one.
- When deleting the cluster, make sure not to delete user-specified EIPs.

**Related issues**
- #392 
- #440 
- #694

**Comment by lapidus79** [comment]
A vote on the:

* One should be able configure existing EIP for each NAT Gateway.
* When deleting the cluster, make sure not to delete user-specified EIPs.

**Comment by lapidus79** [comment]
any ETA on this issue?

**Comment by whereisaaron** [comment]
Hi, I do this by creating a VPC, subsets, and NAT first. Then deploying `eksctl` clusters into that VPC. It has the advantage that you can deploy multiple clusters that share the same NAT. I shared a stack template here:

https://github.com/weaveworks/eksctl/issues/392#issuecomment-460908638

**Comment by lapidus79** [comment]
Progress on this would be much appreciated

**Comment by lapidus79** [comment]
Still a vote for this one

**Comment by aairbag** [comment]
i am unable to see that a resolution was reached regarding adding this feature. if that is the case, please note there is still interest in being able to assign existing EIPs to NAT gateways and re-opening this issue would be much appreciated thanks!
