### ISSUE TITLE
Semantic versioning?

### ISSUE THREAD

**Issue by armandmcqueen** [weaveworks/eksctl#782]
**What happened?**
The same config.yaml file works in 0.1.29, but does not work in 0.1.31. The error appears to be related to the `nodeGroups.allowSSH` field - I think that field got renamed. 

More generally, there is not a definitive API reference, there is not a version changelog (or at least I can't find it) and there is not semantic versioning. Combined, these make it pretty painful to use eksctl over time. We can pin to a specific `0.X.X` version, but this is a young tool and you keep adding great features so that's not a very good solution.

**What you expected to happen?**
I would expect non-breaking behavior when using the same minor version and I would expect minor version changes to be backwards compatible. Alternatively, comprehensive documentation and a changelog would make it easier for us to keep up with eksctl versions.

**Comment by armandmcqueen** [comment]
Ah, the release page has a changelog. The larger point about having versioning that indicates backwards compatibility remains.

**Comment by armandmcqueen** [comment]
Compounding the issue, it looks like only the most recent version is available via Homebrew

**Comment by errordeveloper** [comment]
The 'apiVersion' field is meant to reflect this, it changed from 'v1alpha4' to 'v1alpha5', which implied changes. Going forward we are looking to support multiple API versions, and move on to beta, making it more stable. Full reference documentation is to be expected in due course also.
