### ISSUE TITLE
Question about RBAC 

### ISSUE THREAD

**Issue by mmaryo** [weaveworks/eksctl#789]
Hello 

I'm following this guide https://www.getambassador.io/user-guide/getting-started/

When I run this command line, nothing appear : 

    ~ kubectl cluster-info dump --namespace kube-system | grep authorization-mode
    ~ 

Is it normal RBAC is not activated ?

Best,

**Comment by stefanprodan** [comment]
RBAC is enabled by default in EKS, the correct way of checking is with `kubectl api-versions | grep rbac`

**Comment by mmaryo** [comment]
thank you @stefanprodan
