### ISSUE TITLE
Allow the use of existing IAM profile and enable cluster autoscaling for nodegroup

### ISSUE THREAD

**Issue by adamjohnson01** [weaveworks/eksctl#791]
**Why do you want this feature?**
We would like to use existing IAM roles for our nodegroups as well as enabling autoscaling on the nodegroups.

**What feature/behavior/change do you want?**
Currently the only way to enable a nodegroup to be managed by the autoscaler is to set

```
iam:
  withAddonPolicies:
    autoScaler: true
```

This gives the nodegroup IAM role unnecessary permissions. The permissions set are only required if the nodegroup is also running the cluster autoscaler pod and setting this along with iam.instanceProfileARN currently causes an error.

I would like to add and additional config option for autoscaling which would allow autoscaling of the nodegroup without also giving it the IAM permissions required to perform the autoscaling. Something like this.

```
autoScalerEnabled: true
```
I also think that it may be better to use this option to manage the autoscaling and remove the functionality from the the code that runs when iam.withAddonPolicies.autoScaler: true as there could be situations where you do not want the cluster autoscaler to manage the nodegroup where it is running. 

I am happy to work on this.

**Comment by errordeveloper** [comment]
Yes, `iam.withAddonPolicies.autoScaler` is indeed for cluster autoscaler. Could you please clarify what would you be looking to use instead? Is it an external autoscaler of some sort?

**Comment by adamjohnson01** [comment]
> Yes, `iam.withAddonPolicies.autoScaler` is indeed for cluster autoscaler. Could you please clarify what would you be looking to use instead? Is it an external autoscaler of some sort?

I would still be using the cluster autoscaler, I have opened a pull request to show you what I mean. Apologies if my explanation was not very good.

**Comment by adamjohnson01** [comment]
This can be resolved by setting tags explicitly like this

```
nodeGroups:
- name: ng-1
  tags:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/<clusterName>: "owned"
```
