### ISSUE TITLE
Print concrete error message for instance types not supported in region

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#792]
Some regions don't support all instance types. For example, eu-north-1 is a rather new DC that doesn't support t2 instance family. When we try to create an ASG in that region with t2.small instances, for example, we get an error message like this:

```
[✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed."
```

We should try to alert about this issue before trying to create the ASG with a better error message. 

- We could do this by keeping a map of known unsupported instance families.
- Another issue would be to use this file https://stackoverflow.com/questions/33120348/boto3-aws-api-listing-available-instance-types But since it's +700MB big we could cache it in a lambda based service.
- Another option could be that we parse the JSON data and generate a map

**Comment by errordeveloper** [comment]
See also https://github.com/weaveworks/eksctl/issues/834, sometimes this is due to instance usage policy also.

**Comment by errordeveloper** [comment]
In some case you can also get this:
```
 [✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "API: autoscaling:CreateAutoScalingGroup You are not authorized to use launch template: eksctl-kube-test-nodegroup-kube-nodes"
```

**Comment by errordeveloper** [comment]
This is covered by #491.

**Comment by martina-if** [comment]
Wouldn't it be better if we could warn the user before attempting to create the nodegroup instead of failing after several minutes?

**Comment by errordeveloper** [comment]
Maybe, but we would have to maintain a list of known regions or AZs. I'm a little fuzzy, but I recall hearing/reading it was an AZ thing, and if so, we will need to determine physical AZs IDs (i.e. `us-east-1a` is not the same physical AZ for everyone). It just seems too complicated, we should try simpler approach first.
