### ISSUE TITLE
Compatibility for older versions

### ISSUE THREAD

**Issue by Jeffwan** [weaveworks/eksctl#797]
**What happened?**
A description of actual behavior (with error messages).
Newer version can not build cluster with alpha4 cluster config.
I am using manifest to build some tools and customers may upgrade eksctl and then my cluster_config.yaml will be outdated.

**What you expected to happen?**

At least 2 version need be be supported. 

**How to reproduce it?**
Include the steps to reproduce the bug

Download newer version and using Alpha4 cluster config to create cluster.

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Comment by errordeveloper** [comment]
Hi @Jeffwan! Yes, I agree, and the plan is to fix it for the next version. Ideally, the next version will be v1beta1, and when it comes out we will support v1alpha5 and any forthcoming v1beta's.

**Comment by Jeffwan** [comment]
@errordeveloper  Cool. BTW, I am using eksctl as provision tool for some projects. Just like to know is there a way to generate cluster config based on current eksctl version. Right now, I use fix number and would like to know if it's possible to provide more reliability and decouple with eksctl upgrade for minor versions.

**Comment by kalbir** [comment]
I think this is covered by https://github.com/weaveworks/eksctl/issues/888. Re-open if you feel we are missing something.
