### ISSUE TITLE
allow asg-access via config

### ISSUE THREAD

**Issue by ysle** [weaveworks/eksctl#798]
may a have a bit of help, how to achieve all what the [`--asg-access`](https://github.com/weaveworks/eksctl#enable-autoscaling) does, but using a config file instead please ?

**Comment by ysle** [comment]
probably [like this](https://github.com/weaveworks/eksctl/blob/master/examples/05-advanced-nodegroups.yaml#L21) i guess.

**Comment by errordeveloper** [comment]
Yes, indeed. Thanks for closing the issue. For the record, we are planning on creating better documentation very soon.
