### ISSUE TITLE
Failing to supply a config file name still creates cluster

### ISSUE THREAD

**Issue by JasonSwindle** [weaveworks/eksctl#799]
**What happened?**
If you fail to supply a config file name

```bash
eksctl create cluster --config-file=
```

the cluster will still create.

**What you expected to happen?**
It to throw an error about config file being missing or not supplied.

**How to reproduce it?**
Include the steps to reproduce the bug

**Anything else we need to know?**
N\A

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.31"}
$ uname -a
Darwin Kernel Version 17.7.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:13:37Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
```
Also include your version of `heptio-authenticator-aws`

**Logs**
```
eksctl create cluster --config-file=
[ℹ]  using region us-west-2
[ℹ]  setting availability zones to [us-west-2d us-west-2c us-west-2b]
[ℹ]  subnets for us-west-2d - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for us-west-2c - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for us-west-2b - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng-05aec8d4" will use "ami-0923e4b35a30a5f53" [AmazonLinux2/1.12]
[ℹ]  creating EKS cluster "ferocious-badger-1557850366" in "us-west-2" region
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-west-2 --name=ferocious-badger-1557850366'
[ℹ]  2 sequential tasks: { create cluster control plane "ferocious-badger-1557850366", create nodegroup "ng-05aec8d4" }
[ℹ]  building cluster stack "eksctl-ferocious-badger-1557850366-cluster"
[ℹ]  deploying stack "eksctl-ferocious-badger-1557850366-cluster"
^C
```

**Comment by errordeveloper** [comment]
It's a known behaviour, at present, this is equivalent to not setting the flag, i.e. `eksctl create cluster`. This is how flag parser (cobra) behaves. You can, for example, pass `--config-file=foo` followed by `--config-file=`, and second flag cancels out the first one. There may be a way to handle this, and we will surely investigate.

**Comment by michaelbeaumont** [comment]
IMO, we should just not auto generate names by default, [helm 3 got rid of auto generated names by default](https://helm.sh/docs/faq/#name-or---generate-name-is-now-required-on-install) for example.
@martina-if @cPu1

**Comment by Skarlso** [comment]
After looking at the code on various things which require this configFlag, it's actually a feature and not a bug. If a config file is not provided, we do things on purpose. Generally speaking doing `--config=file=` sets it to an empty value. And an empty value happens to be an accepted value and will not throw any errors.
