### ISSUE TITLE
utils write-kubeconfig generates extra "env: null " attribute

### ISSUE THREAD

**Issue by BrionStone** [weaveworks/eksctl#801]
**What happened?**
After running `eksctl utils write-kubeconfig --name (farm_name)`  ,  a `~/.kube/config` file is created with an extra key/value pair at `users[name=foo@bar]/user/exec`  of `env: null` 

This generates a python error when you try to parse that file:
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected key env in kube-config/users[name=foo@bar]/user/exec

**What you expected to happen?**
no errors.

**How to reproduce it?**
Against a working EKS farm:
Run `eksctl utils write-kubeconfig --name (farm_name)`   (confirm `env: null` pair is at the end of the `.kube/config` file in the user section.)
Attempt to parse the kubeconfig in python:
$ python
>>> import kubernetes      # pip install kubernetes if you don't have it already
>>> cfg = kubernetes.config
>>> cfg.load_kube_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 512, in load_kube_config
    loader.load_and_set(config)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 394, in load_and_set
    self._load_authentication()
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 185, in _load_authentication
    if self._load_from_exec_plugin():
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 346, in _load_from_exec_plugin
    status = ExecProvider(self._user['exec']).run()
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/exec_provider.py", line 35, in __init__
    for item in exec_config['env']:
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 431, in __getitem__
    % (key, self.name))
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected key env in kube-config/users[name=foo@bar]/user/exec

**Anything else we need to know?**
downloaded eksctl.

Workarounds:
Edit ~/.kube/config to remove the `env: null`.
use  `aws eks update-kubeconfig --name (farm_name)` instead.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.32"}
$ uname -a
Linux foo.f.q.d.n 4.4.0-146-generic #172-Ubuntu SMP Wed Apr 3 09:00:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

-----
python:
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2

kubernetes python client:
kubernetes-9.0.0

awscli
1.11.13-1ubuntu1~16.04.0
```
Also include your version of `heptio-authenticator-aws`
Version unknown:
```
$ md5sum heptio-authenticator-aws
c7867c698a38acb3e0a2976cb7b3d0f9  heptio-authenticator-aws
```

**Logs**
n/a

**Comment by martina-if** [comment]
Hi @BrionStone , thank you for your report.

I think this happens because the `env` field is marked as required in the schema and as far as I know, null is a valid value in this case. This seems like an issue in the python library you are using or the schema. I can look a little bit more into this though.

This is what another user experiencing a similar issue suggested as a work around: `aws eks --region <region>  update-kubeconfig --name <name>`

**Comment by errordeveloper** [comment]
This is a known issue with Python client. If you use `kubectl`, you will end up with this, and `kubectl` is "the golden standard", so it's down to Python client to implement the same behaviour that the Go client and `kubectl` does. I was under impression that this was fixed, let me check.

**Comment by errordeveloper** [comment]
Yes, it was fixed: https://github.com/kubernetes-client/python/issues/637. Perhaps you should try client-python 10.0?

**Comment by martina-if** [comment]
I am closing this since it's an issue with the python client. Please feel free to reopen if you want.
