### ISSUE TITLE
Import an existing EKS cluster

### ISSUE THREAD

**Issue by bnutt** [weaveworks/eksctl#807]
**Why do you want this feature?**
As a user who has created an eks cluster via the AWS Console, I would like to be able manage the cluster via eksctl.

**What feature/behavior/change do you want?**
Ability to manage clusters not created by eksctl to manage upgrades of control plane, worker nodes management via yaml, and addons. 

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by errordeveloper** [comment]
Hi @bnutt! Thanks for proposing this, however I must say that it would be fundamentally quite difficult for us to implement this, because most of the functionality eksctl provides is tied into how cluster is setup and relies on CloudFormation. Essentially, we would have to reimplement a lot of the functionality.

**Comment by bnutt** [comment]
Thanks @errordeveloper , completely makes sense, I will close this out then. My motivation for this was to be able to manage the worker nodes via yaml, but I will find another solution.

**Comment by errordeveloper** [comment]
If you create a cluster with eksctl, you should be able to do that and more :)

**Comment by walkafwalka** [comment]
@errordeveloper How about now?

**Comment by infa-ddeore** [comment]
> @errordeveloper How about now?
> https://aws.amazon.com/blogs/aws/new-import-existing-resources-into-a-cloudformation-stack/

importing EKS isnt supported yet :-( https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

**Comment by bienchu** [comment]
@infa-ddeore Until EKS is officially supported in CloudFormation, you may need to write a custom resource and use it to import existing EKS cluster and return its attributes so that other resources can refer to them
