### ISSUE TITLE
Support for AWS CloudWatch Container Insights 

### ISSUE THREAD

**Issue by JasonSwindle** [weaveworks/eksctl#811]
**Why do you want this feature?**
Amazon CloudWatch Container Insights for Amazon EKS and Kubernetes is now now in Preview.

https://aws.amazon.com/about-aws/whats-new/2019/05/cloudwatch-container-insights-for-eks-and-kubernetes-preview/

**What feature/behavior/change do you want?**
Added support to enable this via a flag and config file.

**Comment by voxxit** [comment]
#831 adds the IAM part of this. I think that's all needed from an AWS standpoint. The rest is a Helm chart (which I am going to work on soon unless there is a PR on helm.sh already...)

**Comment by mreferre** [comment]
Hi Josh (@voxxit). I am interested in seeing this feature coming to life. I am not a "go pro" (no pun intended :) ) but I'd like to give as much support as you need. For background I created a [tool](https://github.com/mreferre/ekstender) to "ekstend" an EKS cluster. Among many things it includes Container Insights ([here](https://github.com/mreferre/ekstender/blob/master/ekstender.sh#L274) is the relevant part of the code). There isn't an existing helm chart for the setup and the instructions are [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-EKS.html). The Ekstender tool is nothing more than a script that bundles those instructions. Happy to pair on working on this feature. Feel free to get in touch offline either on twitter (@mreferre) or via email (mreferre at amazon).

**Comment by ismailyenigul** [comment]
There is really a nice feature to have. I installed AWS EKS with `eksctl` then I had to attach policy and create daemonset based on https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-prerequisites.html guide.
It will be cool if we can do it with eksctl

**Comment by spicysomtam** [comment]
Just discovered this does not work. Although cloudwatch logs works fine (although lack of cli arg for it is a bit odd and inconsistent), cloudwatch metrics/Container Insights does not work. The policy CloudWatchAgentServerPolicy is missing from the EC2 instance role.

Some links
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-prerequisites.html
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html

You need to follow instructions for the first link to setup the logging resources in the cluster, and then attach the policy on the second link. 

IMHO container insights (aka metrics) should be combined with the cw logs setup and not be a separate setting for eksctl.

**Comment by absmith82** [comment]
any update no this?

**Comment by code-uri** [comment]
any update on this?
