### ISSUE TITLE
Creation of cluster cause cloudformation rollback complete

### ISSUE THREAD

**Issue by AkiraKane** [weaveworks/eksctl#812]
I am using the nodejs to execute the commands in AWS cloud 9. when I run the eksctl create  cluster ... it will start to create the cluster in cloudformation. However, after the few seconds, I got an error, and show the Rollback Complete status in the Cloudformation, I am not sure if this is the code behavior or a bug?

**Comment by martina-if** [comment]
Hi @AkiraKane ! Thank you for the report. Can you give us more information like the complete command that you used and the logs it produced? You are also welcome to [join us on slack](https://weave-community.slack.com/messages/eksctl).

**Comment by AkiraKane** [comment]
Hi @martina-if , I was using the nodejs to execute the eksctl command
```
const command = `eksctl create cluster --name=nebula-${target_environment}-${new_build_number} --nodes=${number_of_instances} --node-type=${instance_type} --region=${devopsConfigFileData["aws_region"]} `

execSync(command);
```

if I run those commands at the first time, I pretty much got the rollback error in the CloudFormation most of the time, then I have to manually delete the rollback in the CloudFormation, then run the commands again, it will be working fine.

**Comment by martina-if** [comment]
Hi @AkiraKane , usually before the rollback error there are other messages that explain exactly what happened (the rollback can occur for different reasons) . Can you post those here?

**Comment by errordeveloper** [comment]
@AkiraKane could you please run `eksctl utils describe-stacks --events` for the cluster that failed and share the output?

**Comment by AkiraKane** [comment]
Sorry about the delay, it seems that we have fixed the issue. and I am going to close the issue. Thanks guys :)
