### ISSUE TITLE
Document eksctl usage/process best practices

### ISSUE THREAD

**Issue by voxxit** [weaveworks/eksctl#815]
**Why do you want this feature?**
As a Kubernetes cluster admin using eksctl, I want to know "the right way" to perform certain tasks/maintenance so that I can perform these tasks easily and safely on any given day.

**What feature/behavior/change do you want?**
I'd like to see some documentation around:
* Creating clusters - and node groups - using a config file
  * How to iterate on a cluster and all node groups, or just one
* How to store/iterate on that config file - examples include:
  *  Updating the AMI (e.g. if I need to harden the node AMI for security/PCI reasons, etc)
  *  Changing the instance type (if my cluster needs more resources)
* What does the current CloudFormation template generated by `v1alpha5` config files assume about the rollout/replacement strategy for EC2 nodes?
  * How can I update/replace node groups safely, and with no-to-minimal downtime to my users?

**Comment by michaelbeaumont** [comment]
This seems to be largely covered by the current documentation, anyone looking for specific information, please create an issue. Thanks!
