### ISSUE TITLE
Ubuntu1804 AMI family for v1.11+

### ISSUE THREAD

**Issue by paavan98pm** [weaveworks/eksctl#818]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
To use Ubuntu1804 AMIs for worker nodes https://github.com/weaveworks/eksctl/blob/master/pkg/ami/static_resolver_ami.go

**What feature/behavior/change do you want?**
Support Ubuntu1804 ami os in 1.11+

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

**Comment by whereisaaron** [comment]
The AMI’s didn’t used to be available, great if they are now. Do you have a reference or a list of AMI for 18.04 and 1.11?

**Comment by martina-if** [comment]
@paavan98pm as a workaround you can override the AMI used with the arguments: `--version 1.11 --node-ami=ami-0142ca7f --node-ami-family=Ubuntu1804` (or replace the ami id with the one you would like). Would that help?

**Comment by paavan98pm** [comment]
That would certainly help. Let me try this with 1.12. Thanks!
