### ISSUE TITLE
Remove aws-iam-authenticator dependency

### ISSUE THREAD

**Issue by whyvez** [weaveworks/eksctl#819]
**Why do you want this feature?**
`aws-iam-authenticator` is not required anymore for awscli >= 1.16.165

https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-eks-simplifies-kubernetes-cluster-authentication

**What feature/behavior/change do you want?**
Remove the dependency on `aws-iam-authenticator` and recommend using awscli >= 1.16.165

**Comment by errordeveloper** [comment]
Yes, and we have an issue for this - #788.
