### ISSUE TITLE
Change kubelet config (--container-runtime flag) in Ubuntu1804

### ISSUE THREAD

**Issue by paavan98pm** [weaveworks/eksctl#820]
Please [search existing issues (open & closed)](https://github.com/weaveworks/eksctl/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if there is a similar one. If there is, add comments or vote where appropriate.

If you did not find a similar issue or if it did not help then ask for help in our [slack channel](https://weave-community.slack.com/messages/eksctl/)

**What help do you need?**
I'm looking to change the kubelet config on Ubuntu. Can this be done? I see `cat /snap/kubelet-eks/2/run-with-config-args` has some high-level pointers. I can't locate the kubelet config file in Ubuntu, though. Thanks!

**Comment by errordeveloper** [comment]
The Ubuntu images are only available for 1.10, we are not adding new Ubuntu-specifc features until newer images become available. Would you use Amazon Linux 2 (AL2) instead?

**Comment by paavan98pm** [comment]
I am looking to run a different CRI - Ubuntu provides better support for CRIs like contianerd afaik. Btw, good to meet you at the AWS BoF last week. :)

**Comment by paavan98pm** [comment]
Here's the steps (that eventually fail due to [lack of support](https://snapcraft.io/kubelet-eks) for `kubelet-eks` snap.

1. `sudo systemctl status snap.kubelet-eks.daemon`
2. `sudo snap set kubelet-eks container-runtime=containerd`
3. `sudo service snap.kubelet-eks.daemon restart`
4. `sudo systemctl status snap.kubelet-eks.daemon`
5. `sudo snap set kubelet-eks container-runtime=docker`
6.  `sudo systemctl status snap.kubelet-eks.daemon`

**Comment by hi-artem** [comment]
@paavan98pm have you ever managed to make containerd work as container-runtime with kubelet-eks?
