### ISSUE TITLE
instanceRoleName makes node group upgrades impossible

### ISSUE THREAD

**Issue by forsberg** [weaveworks/eksctl#824]
**What happened?**
First, I created a nodegroup:

```
nodeGroups:
 - name: ng-1
    ...
    iam:
      instanceRoleName: nodegroup-role
```

Creating this works fine.

Now I modify the nodegroup:

```
nodeGroups:
 - name: ng-2
    ...
    iam:
      instanceRoleName: nodegroup-role
```

`eksctl create nodegroup --config-file=...` now fails with cloudformation complaining about the nodegroup-role already being present, created by the stack for ng-1.

**What you expected to happen?**
Expected to be able to modify my nodegroup, move the load, then remove the old one.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.32"}
$ uname -a
Darwin erfor-macb 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin
$ kubectl version
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
```

So instanceRoleName is pretty useless in its current incarnation. 

I see two possible solutions:

1. Create the noderole via a separate cloudformation stack, and refer to it via instanceRoleARN. This takes away some of the usefulness of eksctl.
2. Extend eksctl configuration and functionality so it creates instance roles in a separate stack, with separate configuration.

**Comment by errordeveloper** [comment]
Hi @forsberg, I am not sure if there is an easy way to fix this, what requires you to use a named role? I If you must have a named role and keep it, you have 2 work-arounds:

- manage the role externally and only specify the ARN in eksctl config
- keep old nodegroup, but scale it down, look-up role ARN and use that for your new nodegroup

**Comment by martina-if** [comment]
Hi, since this field was meant to be used name the instance roles created by eksctl and not to reference them (for that we have the instance role ARN) and there's no specific use case to use a named role I think I will close this. But if you would like to contribute to eksctl we are more than happy to accept PRs :)

If you disagree and think this issue should be kept open please feel free to reopen it.
