### ISSUE TITLE
Can I arbitrarily modify the prefixed to the objects I create?

### ISSUE THREAD

**Issue by junu0723** [weaveworks/eksctl#825]
Hi, I'm trying to create k8s cluster using eksctl. 

However, to prevent some possible operational issues, I want to take control the name of instances and sg, etc... 

Can I arbitrarily modify the prefixed to the objects I create?

**Comment by errordeveloper** [comment]
Could you please illustrate this a little more? You can add tags, wouldn't that be sufficient?

**Comment by xDeany** [comment]
I have a similar request that I was sent to here - would I be able to simply disable the 'eksctl' prefix that appends to all cloudformation scripts? We use the prefix of the resource names to track different projects internally

**Comment by errordeveloper** [comment]
@xDeany so you are asking about CloudFormation stack prefixes, right?

**Comment by junu0723** [comment]
@errordeveloper I think my problem is similar to @xDeany .
I want to disable 'eksctl' prefix from all resources that created by eksctl via cloudformation.

**Comment by errordeveloper** [comment]
This will be covered by #581,  as special case of empty prefix.
