### ISSUE TITLE
EKSCTL with existing Vpc

### ISSUE THREAD

**Issue by moretti-truelogic** [weaveworks/eksctl#826]
Hi

I am trying to create a CLuster using eksctl cluster.yaml:

# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: us-west-2

vpc:
  id: "vpc-xxxxxxxxxxxxxxx"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.18.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      us-west-2a:
        id: "subnet-0b6022x669d"
        cidr: "172.18.6.0/24" # (optional, must match CIDR used by the given subnet)

      us-west-2b:
        id: "subnet-xxxxxxxxxx2b038c8464e3a3"
        cidr: "172.18.7.0/24"  # (optional, must match CIDR used by the given subnet)

      us-west-2c:
        id: "subnet-xxxxxxxxxxxxxx4658bee91"
        cidr: "172.18.8.0/24"   # (optional, must match CIDR used by the given subnet)

nodeGroups:
  - name: test-ngv2
    instanceType: m4.xlarge
    desiredCapacity: 3
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled   
-------------------------

But i alwayz receive this error:
[ℹ]  nodegroup "sandbox-ng" has 0 node(s)
[ℹ]  waiting for at least 1 node(s) to become ready in "test-ng"
[✖]  timed out (after 25m0s) waiting for at least 1 nodes to join the cluster and become ready in test-ng"

**Comment by errordeveloper** [comment]
I've seen reports of a similar issue in the past, most of the time it is to do with the configuration of the existing VPC.

**Comment by errordeveloper** [comment]
Closing due to lack of context.
