### ISSUE TITLE
Enable/disable EC2 auto scaling group metric collection

### ISSUE THREAD

**Issue by voxxit** [weaveworks/eksctl#827]
**Why do you want this feature?**
As a cluster administrator, I want to be able to enable group metrics collection on my EC2 auto scaling groups created via eksctl node groups so that I can keep track of scale-up/scale-down activity, min/max node group sizes over time, etc.

**What feature/behavior/change do you want?**
See: https://docs.aws.amazon.com/cli/latest/reference/autoscaling/enable-metrics-collection.html

**Comment by errordeveloper** [comment]
This is possible to do in CloudFormation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#aws-properties-as-group--examples

I would guess we'd just add nodegroup property called something like `asgMetricsCollection`. As with other CloudWatch-based things, we should keep off by default. With respect to field values, granularity should be expressed in Kubernetes-native units as well as AWS-native i.e. `1m` and `1Minute` should be valid. Other than that, it sounds like a fairly simple feature.

**Comment by setevoy2** [comment]
> Jun 4, 2019

Hi!
Any updates on this?
