### ISSUE TITLE
common kubectl operations

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#830]
We occasionally get asked about e.g. how to update nodegroup labels, which is something we don't support directly, but can easily be done with `kubectl`. We should document these things.

```
kubectl label nodes -l alpha.eksctl.io/nodegroup-name=ng-1 new-label=foo
```

There are probably other things, it'd be good to create a section in the docs dedicated to what you don't need `eksctl` for, we might need to cross-reference this from other sections also. Or, perhaps, we should have a more specific section on nodegroup lables and taints etc under nodegroup management?

**Comment by michaelbeaumont** [comment]
We have at least this example already under https://eksctl.io/usage/managing-nodegroups/#update-labels
