### ISSUE TITLE
2 subnets in the same region

### ISSUE THREAD

**Issue by kiahmed** [weaveworks/eksctl#833]
why can't I mention 2 different subnet in the same AZ ? How to do that. Also, is there a way to attach a node-group to selected subnets only?

**Comment by errordeveloper** [comment]
We currently only support subnet-per-AZ. You can attach a nodegroup to a particular subset of AZs, e.g. single AZ or two instead of 3 (default).

What is you use-case for multiple subnets per AZ?

**Comment by kiahmed** [comment]
well, it requires 2x by 2x so. I have 2 private subnets but when I create another 2 public in the same AZ as the AWS Tokyo region has only 3 az, could'd find a way to feed in to eksctl config whereas aws cli and console itself accepts it. Ins't it superposed to covert all to aws compatible clouformation then why eksclt has this lacking or coming up with its own settings /restrictions ?

**Comment by errordeveloper** [comment]
It's not very clear where is the issue exactly. Please show the commands you tried to use and be more specific - what is it that you are trying to achieve overall? Why do you need to create two public subnets in the same AZ - do you need to use them for isolation, or you want to avoid wasting IP addresses, or is it something else?

**Comment by kiahmed** [comment]
it is simple .. i want 4 subnets but have only 3 AZ . I could go with 1 subnet in each AS but it doenst work like that .. trying to create eks cluster

**Comment by errordeveloper** [comment]
Ok, so it's to do with IP addresses being wasted if you were to use only 3 subnets.

We are considering to review this, but I'm not sure when we would be able to implement a change that would allow you to do this. In the meantime, perhaps you could use 2 larger subnets in 2 AZs, or 3 subnets in 3 AZs and leave one unused until we fix this issue.

If you urgent help, please contact me on [Slack](https://slack.weave.works).

**Comment by kiahmed** [comment]
" 2 larger subnets in 2 AZs" didnt work for me . .you mean one in private and another public in two different AZ i?

**Comment by errordeveloper** [comment]
No. I mean 2 AZs with 2 private and/or 2 public subnets, total of either 2
or 4 subnets (depending on whether you need just private ones or public
also).

**Comment by errordeveloper** [comment]
Your use-case is still not very clear to me, but I would assume that this is will be covered by #806.

**Comment by kiahmed** [comment]
my case is i need to use 4 subnets spreading across 2/3 AZ, but when eksctl sees an AZ was already used it complains why? Then how we supposed to have multiple subnets in same AZ

**Comment by aravindgv** [comment]
I am also looking for multipe Az's
