### ISSUE TITLE
add command to inspect CloudWatch logs

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#849]
We should be able to just use [`github.com/TylerBrock/saw/blade`](https://godoc.org/github.com/TylerBrock/saw/blade).

/cc @TylerBrock

/xref #514, #704, #811

**Comment by TylerBrock** [comment]
How can i help?

**Comment by TylerBrock** [comment]
I could try to extract some of the saw stuff into a library to make it easier to embed in other CLIs eventually

**Comment by errordeveloper** [comment]
@TylerBrock thanks, that would be great! I've looked at the API, seems like it should be usable, but I don't know if there maybe side-effects or any sort of assumptions. If you know of stuff that can be improved, it'd be great to see a lean library.
