### ISSUE TITLE
iamidentitymapping prints incorrect error message

### ISSUE THREAD

**Issue by timfallmk** [weaveworks/eksctl#863]
**What happened?**
Running `eksctl get iamidentitymapping` produces the error:
`--cluster must be set`
However this flag is not available or required. `--name` is likely the required flag.

**What you expected to happen?**
Print the correct error

**How to reproduce it?**
- Run `eksctl get iamidentitymapping`
- Get error

**Anything else we need to know?**
Base configuration. Nothing special

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
```
`[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.35"}`
```
$ uname -a
```
`Darwin <redacted> 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`
```
$ kubectl version
```
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-dispatcher", GitCommit:"1215389331387f57594b42c5dd024a2fe27334f8", GitTreeState:"clean", BuildDate:"2019-05-13T18:18:50Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
N/A

Reference to #814

**Comment by errordeveloper** [comment]
Thanks for reporting this, it will be fixed in the next release!
