### ISSUE TITLE
Add `mapUsers` support to `iamidentitymapping` command

### ISSUE THREAD

**Issue by patstrom** [weaveworks/eksctl#876]
With the recent addition of the `iamidentitymapping` command I noticed that it currently only supports the `mapRoles` functionality of the `aws-auth` configmap. It would be nice to have it support the `mapUsers` functionality as well. In other words get/create/delete mappings for both IAM roles and users to Kubernetes users and groups.

**Comment by patstrom** [comment]
I would love to do it myself but I won't be able to get to it until earliest on the 24th so I'll just create an issue in the meantime :sweat_smile:

**Comment by errordeveloper** [comment]
@patstrom sure thing! just let us know when you get to it, if you have any questions - feel free to ping us on [slack](https://slack.weave.work).

**Comment by nikolai-derzhak-distillery** [comment]
Just to link it to PR: https://github.com/weaveworks/eksctl/pull/814

**Comment by patstrom** [comment]
I've implemented the first draft of this functionality in https://github.com/weaveworks/eksctl/pull/932!

The plan is to implement tests (and update the existing tests) once there has been some kind of initial feedback.

**Comment by patstrom** [comment]
Some time cleared up so I've now implemented the tests as well!
