### ISSUE TITLE
no eksctl-managed CloudFormation stacks found

### ISSUE THREAD

**Issue by kiahmed** [weaveworks/eksctl#877]
getting VPC configuration for cluster "my-clstr": no eksctl-managed CloudFormation stacks found for "my-clstr"

created the cluster with aws console as it wasnt working with eksctl for existing vpc and subnet mix, but when try to create a node group on the existing vpc get the error which makes sense but is there a work around for this. Dont ask me why I couldn't create clstr with eksctl in first place we already [went through](https://github.com/weaveworks/eksctl/issues/833) that and its not possible for my req

**What help do you need?**
Describe the type of help you need

**Comment by errordeveloper** [comment]
Hi @kiahmed this is unsupported at the moment. If you need help, please send me an email - ilya@weave.works and we can discuss your use-case.

**Comment by brunojcm** [comment]
Any chances of supporting this use case?

**Comment by akhon** [comment]
+

**Comment by brunojcm** [comment]
I ended up recreating my cluster, and I understand it would be very hard to support "adopting" a manually created cluster, especially because CloudFormation also does not support adopting existing resources.

**Comment by abdennour** [comment]
@brunojcm I got the same error, even though, I didn't create the cluster manually. Instead I used this terraform module : [terraform-aws-modules/terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks)

**Comment by PeterLaiAndDigital** [comment]
+

**Comment by quickbooks2018** [comment]
same issue, any updates???

root@ubuntu:/home/asim/Desktop/eks/environment/dev# eksctl create iamserviceaccount \
>        --cluster=cloudelligent-dev-eks-cluster \
>        --namespace=kube-system \
>        --name=alb-ingress-controller \
>        --attach-policy-arn=arn:aws:iam::400812563931:policy/ALBIngressControllerIAMPolicy \
>        --override-existing-serviceaccounts \
>        --approve
[ℹ]  eksctl version 0.13.0
[ℹ]  using region us-east-1
Error: no eksctl-managed CloudFormation stacks found for "cloudelligent-dev-eks-cluster"

**Comment by quickbooks2018** [comment]
> @brunojcm I got the same error, even though, I didn't create the cluster manually. Instead I used this terraform module : [terraform-aws-modules/terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks)

https://www.youtube.com/watch?v=YqouJI3HWPI&t=226s

**Comment by sudhakarVuppalapati** [comment]
https://s3.amazonaws.com/aws-quickstart/quickstart-amazon-eks/templates/amazon-eks-master.template.yaml  

me too getting Error: no eksctl-managed CloudFormation stacks found for "EKS-Y8B4fXevkgeJ"

eksctl create iamserviceaccount  --region eu-west-1 --name alb-ingress-controller --namespace kube-system --cluster EKS-Y8B4fXevkgeJ --attach-policy-arn arn:aws:iam::CCCCCC:policy/ALBIngressControllerIAMPolicy  --override-existing-serviceaccounts --approve
[ℹ]  eksctl version 0.13.0
[ℹ]  using region eu-west-1
Error: no eksctl-managed CloudFormation stacks found for "EKS-Y8B4fXevkgeJ"


please can some help me regarding this

**Comment by serverlessguru** [comment]
Hitting this same issue.. Creating the EKS cluster and supporting AWS resources through CloudFormation directly.

Trying to create fargate profile:
```
eksctl create fargateprofile --cluster express-api-cluster --name express-api-cluster-profile --namespace kube-system --labels app=express-api --region us-east-1
```

Error:
```
Error: no eksctl-managed CloudFormation stacks found for "express-api-cluster"
```
