### ISSUE TITLE
Why are both Kube-DNS and CoreDNS installed by default ?

### ISSUE THREAD

**Issue by webmutation** [weaveworks/eksctl#891]
Just created a new 1.12 cluster, and both kube-dns and coreDNS are installed. The one that is running is Kube-DNS but the resources to run coreDNS are there by default... is there a reason why both DNS services are installed?

Seems a bit strage... perhaps I am missing something. 
The command i used to create the cluster was 
`eksctl create cluster --name=eks-qs --nodes=1 --node-type t3.small`

**Comment by errordeveloper** [comment]
@webmutation what are you seeing exactly?

In a new 1.11 or 1.12 cluster, I'd expect to see `service/kube-dns`  and `apps.deployment/coredns`, both in `kube-system` namespace. You should only see `coredns` pods, and no `kube-dns` pods.

**Comment by webmutation** [comment]
Hi,
Here are the resources 

NAMESPACE     NAME                           READY   STATUS    RESTARTS   AGE
kube-system   pod/aws-node-lz6p7             1/1     Running   0          5h14m
kube-system   pod/coredns-7b5c8bfcfc-9dn5l   1/1     Running   0          5h20m
kube-system   pod/coredns-7b5c8bfcfc-m46mk   1/1     Running   0          5h20m
kube-system   pod/kube-proxy-74btx           1/1     Running   0          5h14m

NAMESPACE     NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
default       service/kubernetes   ClusterIP   10.100.0.1    <none>        443/TCP         5h20m
kube-system   service/kube-dns     ClusterIP   10.100.0.10   <none>        53/UDP,53/TCP   5h20m

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/aws-node     1         1         1       1            1           <none>          5h20m
kube-system   daemonset.apps/kube-proxy   1         1         1       1            1           <none>          5h20m

NAMESPACE     NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   2         2         2            2           5h20m

NAMESPACE     NAME         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
default       kubernetes   ClusterIP   10.100.0.1    <none>        443/TCP         5h54m
kube-system   kube-dns     ClusterIP   10.100.0.10   <none>        53/UDP,53/TCP   5h54m

On a 1.11 cluster created today. kube-dns is still there...

**Comment by errordeveloper** [comment]
@webmutation as I said, it's only the service, i.e.:
```
NAMESPACE     NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
kube-system   service/kube-dns     ClusterIP   10.100.0.10   <none>        53/UDP,53/TCP   5h20m```
```
There are only CoreDNS pods, no kube-dns pods:
```
NAMESPACE     NAME                           READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-7b5c8bfcfc-9dn5l   1/1     Running   0          5h20m
kube-system   pod/coredns-7b5c8bfcfc-m46mk   1/1     Running   0          5h20m
```

The reason for this is that `kube-dns` service is considered to be something that application depend on, so it remained unchanged when CoreDNS was introduced. It is by design.
If you check, you will see that `kube-dns` service points at CoreDNS pods. Take a look at the lable selector it uses and run that selector agains pods in the same namespace.

You should see this:
```
$ kubectl describe -n kube-system service/kube-dns
Name:              kube-dns
Namespace:         kube-system
Labels:            eks.amazonaws.com/component=kube-dns
                   k8s-app=kube-dns
                   kubernetes.io/cluster-service=true
                   kubernetes.io/name=CoreDNS
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"9153","prometheus.io/scrape":"true"},"labels":{"eks.a...
                   prometheus.io/port: 9153
                   prometheus.io/scrape: true
Selector:          k8s-app=kube-dns
Type:              ClusterIP
IP:                10.100.0.10
Port:              dns  53/UDP
TargetPort:        53/UDP
Endpoints:         192.168.13.160:53,192.168.16.86:53
Port:              dns-tcp  53/TCP
TargetPort:        53/TCP
Endpoints:         192.168.13.160:53,192.168.16.86:53
Session Affinity:  None
Events:            <none>
$ kubectl get pods -n kube-system -l k8s-app=kube-dns                                                                        
NAME                       READY   STATUS    RESTARTS   AGE
coredns-5f6dccd954-m6846   1/1     Running   0          4h26m
coredns-5f6dccd954-wn97m   1/1     Running   0          4h26m
$
```

**Comment by webmutation** [comment]
Ok, it is clear now, thank you very much for the explanation.

So even though the service name is called kube-dns, it is CoreDNS that is running, this was confusing me since I saw no pods for kube-dns but the service is still named kube-dns.

**Comment by errordeveloper** [comment]
@webmutation sure, I can see how it can be confusing!
