### ISSUE TITLE
shared VPC

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#892]
It would be useful to provide a way to create eksctl-managed VPC that can be used for one or more clusters. This would help users who want to have multiple clusters in one VPC, but also cases where different level of access is required for managing VPC resources.

Something like this was also proposed by @whereisaaron in https://github.com/weaveworks/eksctl/issues/560#issuecomment-465807918.

**Comment by errordeveloper** [comment]
It's plausible to consider having VPC in a separate stack by default, per https://github.com/weaveworks/eksctl/issues/1123, but also because user doesn't know when they create cluster whether they may need to share the VPC with another cluster.

**Comment by errordeveloper** [comment]
It's plausible to consider having VPC in a separate stack by default.

Per @sstkwayne's comments in https://github.com/weaveworks/eksctl/issues/1123:

> When using eksctl to create a cluster with a new VPC, it would be great to have the VPC and all it's resources created as a separate Cloudformation stack from the EKS cluster. I recently had to tear down a cluster and because it is in the same stack with the VPC i had to tear that down as well. This is inconvenient because there wasn't anything wrong with the VPC configuration,
>
> **Why do you want this feature?**
> Having a separate VPC stack would allow users to create and destroy EKS clusters without having to teardown the VPC which might have other resources in it such as a DB, Peering connections, etc.
>
> **What feature/behavior/change do you want?**
> I would like to see eksctl create cluster command result in the creation of a VPC stack, a cluster stack and a nodegroup stack if defined in the yaml. 

Also because user simply doesn't know when they create cluster whether they may need to share the VPC with other clusters or not.

**Comment by errordeveloper** [comment]
Another important uses-case is RDS, one may wish to keep VPC as it has RDS beyond lifecycle of a cluster, e.g. they wish to re-create the cluster for any reason.

**Comment by oemdaro** [comment]
I have an issue when using [VPC Sharing](https://aws.amazon.com/blogs/networking-and-content-delivery/vpc-sharing-a-new-approach-to-multiple-accounts-and-vpc-management/). When I try to create cluster on the sharing VPC and subnets, I got the following error.

```
Error: couldn't import subnet subnet-2222222222: subnet ID "subnet-1111111111" is not the same as "subnet-2222222222"
```

How to solve this problem?

**Comment by michaelbeaumont** [comment]
Hi, thanks for bringing this up! Can you please include the exact config or the command and arguments you're using as well as the log output? Please feel free to open a new issue as well.

**Comment by oemdaro** [comment]
Hi @michaelbeaumont , thank you. I have created a new issue #2910 for it.
