### ISSUE TITLE
Simplify the flow of update cluster command

### ISSUE THREAD

**Issue by arun-gupta** [weaveworks/eksctl#906]
As listed at https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html, the following command is needed for all cluster updates:

```
eksctl utils update-kube-proxy --name dev --approve
```

Why is this a separate command? Can this not be subsumed in `eksctl update cluster`?

Ditto for DNS provider and CNI plugin commands.

**Comment by errordeveloper** [comment]
This is certainly a subject for discussion. The reason it was done this way is because each of the add-ons is a somewhat of a special case, each has a different procedure on upgrade.

**Comment by arun-gupta** [comment]
Would DNS or CNI provider be considered as add-ons? These are essential components needed to get cluster up and running. Can we classify core and optional add-ons?

**Comment by michaelbeaumont** [comment]
Relevant for #2774
