### ISSUE TITLE
Version option for update cluster command

### ISSUE THREAD

**Issue by arun-gupta** [weaveworks/eksctl#909]
`eksctl update cluster` does not allow to specify a version to upgrade to:

```
eksctl update cluster --help
Update cluster

Usage: eksctl update cluster [flags]

General flags:
  -n, --name string          EKS cluster name
  -r, --region string        AWS region
  -f, --config-file string   load configuration from a file
      --approve              Apply the changes
  -w, --wait                 wait for all update operations to complete before exiting (default true)
```

How does eksctl know which version to upgrade to?

**Comment by errordeveloper** [comment]
@arun-gupta this was covered by initial discussion, but we didn't have an issue for it - thanks for opening it. The challenge her is that you can only go up by one version at a time, we will need to decide if we should automatically chain X number of upgrades, which will make the logic a little more complex.

**Comment by arun-gupta** [comment]
Agreed, that per [skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/), control plane can be upgraded only one minor version. But chaining X upgrades would be a simplified experience. Particularly, if https://github.com/weaveworks/eksctl/issues/906 makes the update a holistic experience.

**Comment by scottyhq** [comment]
It would be great to also clarify how patch versions are dealt with (for example how to upgrade from 1.13.7 to 1.13.8). https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html 

`eksctl get cluster` simply shows 1.13. 

But Sometimes situations come up where it is desirable to apply patched versions to the cluster and nodegroups: https://github.com/aws/amazon-vpc-cni-k8s/issues/282#issuecomment-518518687

**Comment by aclevername** [comment]
Closed by https://github.com/weaveworks/eksctl/pull/2318
