### ISSUE TITLE
create cluster does not provide to enable logging

### ISSUE THREAD

**Issue by arun-gupta** [weaveworks/eksctl#911]
`eksctl create cluster` command does not allow to specify control plane logging to CloudWatch logs. This needs to be explicitly enabled using AWS Console or CLI after cluster creation. This is specified at https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html.

This can be introduced using a CLI option.

**Comment by errordeveloper** [comment]
It's being worked on. Original issue is #704, and the PR is #847.
