### ISSUE TITLE
create public mailing list

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#923]
At present we don't have an official channel to announce things, e.g. community events or major changes, and release.

- [x] crate a list
- [x] announce it
- [x] document it

**Comment by whereisaaron** [comment]
Plus a Usenet group!! 😂 Do people still use mailing lists? Would a project twitter handle with tweets linking to announcements on the upcoming website be a better option?

**Comment by errordeveloper** [comment]
@whereisaaron good point! I think it's important to have an official list where things are announced and discussed, or we could use something like discuss.kubernetes.io. I think the most important factor would be about having a low-noise channel with an archive that one can browse easily.

We could consider using GH, say we could use `announcement` label... But GH notifications are broken for many people, so I struggle to see how that would make it visible.

**Comment by errordeveloper** [comment]
> tweets linking to announcements on the upcoming website be a better option?

Actually, I like the idea of just using the website, e.g. `ekctl.io/news` or `ekctl.io/announcements`.

**Comment by dholbach** [comment]
Please join: https://groups.google.com/forum/#!forum/eksctl-dev ... also please let me know if any description or setting is misleading or wrong.

**Comment by dholbach** [comment]
Announcements would be one thing, slower and more detailed discussions would be another.

discuss.kubernetes.io is nice for release announcements, but could be considered off-topic for other things. The other bit about using a Google group as referenced above is that it's nice to use it for calendar invites, sharing docs, etc.

We can always re-evaluate - for now I feel it's a good step forward.

**Comment by errordeveloper** [comment]
I 100% with Aaron on this to be honest.
