### ISSUE TITLE
Error with loading config file "cluster.yaml": no kind "ClusterConfig" is registered for version "eksctl.io/v1alpha#" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:60"

### ISSUE THREAD

**Issue by dalbhanj** [weaveworks/eksctl#925]
**What happened?**
I tried creating cluster using ClusterConfig and eksctl failed with the error below. 

`Error with loading config file "cluster.yaml": no kind "ClusterConfig" is registered for version "eksctl.io/v1alpha#" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:60"
`

I saw this with v1alpha4 and eksctl version 0.1.38, worked fine with 0.1.29. 

**What you expected to happen?**
I think error message is fine but it would be helpful if there is troubleshooting/debugging docs added to the repo which can clarify why they are seeing this and what to do as next steps

Another improvement is to add release notes that can suggest when and what changes were made

**How to reproduce it?**
Use eksctl version 0.1.38, create ClusterConfig and create cluster

```cat >cluster.yaml <<EOF
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig
metadata:
  name: fsx-csi-driver
  region: $AWS_REGION
  version: "1.12"

nodeGroups:
  - name: ng-1
    desiredCapacity: 2
EOF
```
`eksctl create cluster -f cluster.yaml`

**Anything else we need to know?**
Installed eksctl on my Mac using homebrew

`brew upgrade eksctl`

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.38"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-27T15:15:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
I don't think this is required but happy to share if needed

**Comment by errordeveloper** [comment]
Hi! You should use 'v1alpha5' now, please see examples for, there were a few small changes, but you simple config should just work as is. In the future we are going to provide schema migration (see #888).

**Comment by ricardodani** [comment]
I am gotting this erros but I'm using eksctl 0.61.0, apiVersion v1alpha5 and 1.22.0

```
unable to write kubeconfig , please retry with 'eksctl utils write-kubeconfig -n cluster-name': unable to read existing kubeconfig file "...kubeconfig.yaml": error loading config file "...kubeconfig.yaml": no kind "ClusterConfig" is registered for version "eksctl.io/v1alpha5" in scheme "pkg/runtime/scheme.go:100"
```

**Comment by toonarmycaptain** [comment]
+1

**Comment by Skarlso** [comment]
@toonarmycaptain hi. This has been fixed with the latest version in eksctl. You have to re-create the config file for the cluster. Then it will work. Thanks.

**Comment by ZillaG** [comment]
Is this issue back?

```
$ eksctl version
0.109.0

$ kubectl version --short
Client Version: v1.22.13
Server Version: v1.20.15-eks-18ef993
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```
I have a YAML configuration file that I sued to create my AWS EKS cluster that has the following
```
kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
...
```
I want to delete my cluster and start over so I do
```
$ kubectl delete -f eks-sandbox-cluster.yaml
```
But get
```
error: unable to recognize "eks-sandbox-cluster.yaml": no matches for kind "ClusterConfig" in version "eksctl.io/v1alpha5"
```
