### ISSUE TITLE
eksctl utils update commands show not up-to-date

### ISSUE THREAD

**Issue by braderhart** [weaveworks/eksctl#926]
**What happened?**
Running `eksctl utils update-aws-node` or the other updates without `--apply` show they are not up-to-date

**What you expected to happen?**
If these services are up-to-date show that they are already at the latest version

**How to reproduce it?**
`eksctl utils update-coredns --name=<cluster-name>`

**Anything else we need to know?**
- What OS are you using: 5.1.12-arch1-1-ARCH
- Are you using a downloaded binary or did you compile eksctl: Downloaded binary
- What type of AWS credentials are you using (i.e. default/named profile, MFA): default

**Versions**
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.38"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"archive", BuildDate:"2019-06-20T22:55:20Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
```
eksctl utils update-coredns --name=dev
[ℹ]  using region us-west-2
[ℹ]  (plan) would have replaced "kube-system:Service/kube-dns"
[ℹ]  (plan) would have replaced "kube-system:ServiceAccount/coredns"
[ℹ]  (plan) would have replaced "kube-system:ConfigMap/coredns"
[ℹ]  (plan) would have replaced "kube-system:Deployment.apps/coredns"
[ℹ]  (plan) would have replaced "ClusterRole.rbac.authorization.k8s.io/system:coredns"
[ℹ]  (plan) would have replaced "ClusterRoleBinding.rbac.authorization.k8s.io/system:coredns"
[✖]  (plan) "coredns" is not up-to-date
[!]  no changes were applied, run again with '--approve' to apply the changes
```

**Comment by errordeveloper** [comment]
We rely on the Kubernetes client library, but it's possible there is something about our usage that affect the dry-run functionality.

**Comment by braderhart** [comment]
Thanks. They always show `not up-to-date` even after just updating from `eks utils`
