### ISSUE TITLE
Update Amazon VPC CNI Plugin to v1.5.0

### ISSUE THREAD

**Issue by braderhart** [weaveworks/eksctl#927]
**What happened?**
New clusters and `eksctl utils update-aws-node --name=<cluster-name> --approve` use v1.4.1 of Amazon VPC CNI Plugin. To be fair, AWS docs appear to be a bit outdated here as well from what I can tell.

**What you expected to happen?**
New cluster and `eksctl utils update-aws-node --name=<cluster-name> --approve` use v1.5.0 of Amazon VPC CNI Plugin.

**How to reproduce it?**
Create a new cluster or run the `eksctl utils update-aws-node --name=<cluster-name> --approve` command

**Anything else we need to know?**
- What OS are you using: 5.1.12-arch1-1-ARCH
- Are you using a downloaded binary or did you compile eksctl: Downloaded binary
- What type of AWS credentials are you using (i.e. default/named profile, MFA): default

**Versions**
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.38"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"archive", BuildDate:"2019-06-20T22:55:20Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
Not relevant for this issue

**Comment by errordeveloper** [comment]
Hi @braderhart, thanks for reporting this! We currently trust the docs on this, but are you saying that when you create a new cluster it has 1.5.0?

**Comment by braderhart** [comment]
@errordeveloper No, it is using version 1.4.1 as mentioned in the EKS docs:

https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/cni-upgrades.md

It does appear that version 1.5.0 has been released, but I could be wrong:

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.5.0
https://github.com/aws/amazon-vpc-cni-k8s/tree/master/config/v1.5

I've created an issue for the docs to see if they change it:

https://github.com/awsdocs/amazon-eks-user-guide/issues/51

**Comment by errordeveloper** [comment]
@braderhart thanks! We are going to follow what AWS ships, I'd expect them to be running 1.5.0 in some clusters and testing it under load over a period of time.

**Comment by braderhart** [comment]
@errordeveloper The AWS EKS docs have now been updated and list version 1.5.0 as the latest.
