### ISSUE TITLE
node labels for spot and on-demand in a mixed ng

### ISSUE THREAD

**Issue by pahud** [weaveworks/eksctl#929]
*Before creating a feature request, please search existing feature requests to see if you find a similar one. If there is a similar feature request please up-vote it and/or add your comments to it instead*

**Why do you want this feature?**
A clear and concise description of why you want this feature. Include use-cases and any specific constraints you may have.

eksctl supports nodegroup of mixed instance types and purchase options now. However, we can't select on-demand or spot based on their labels. Would be great if the provisioned nodes can automatically have a `lifeCycle` label.

**What feature/behavior/change do you want?**
A clear and concise description of the change you would like to see in eksctl.

When nodegroup is created with the [sample yaml](https://github.com/weaveworks/eksctl/blob/master/examples/08-spot-instances.yaml) provided, all on-demand instances would have `lifecycle=OnDemand` and spot instances have `lifecycle=Ec2Spot`. Just as it was mentioned in eksworkshop.com https://eksworkshop.com/spotworkers/workers/

Would be great if the taints on spot is being handled as well.

More implementations details with cloudformation can be found here:

https://github.com/pahud/eks-templates/blob/d9844c3e22cc0e094e9db01ea52baa396c7212ae/cloudformation/nodegroup.yaml#L466-L471

**Comment by errordeveloper** [comment]
I can foresee that may turn out to be a not very easy to implement, but we will certainly look into it. Ideally, we shouldn't make API calls from the instances by using AWS CLI. I'd recommend using a controller for this instead of doing it a bootstrap, I am not fully aware if such controller exists already and will need to do some research. In the meantime, I recommend nodegroup label/taint for this, as in a mixed nodegroup you will risk getting spot instances anyway.

**Comment by errordeveloper** [comment]
> we shouldn't make API calls from the instances by using AWS CLI

That said, calling metadata is not forbidden, so I guess it maybe possible to do that.

**Comment by ruecarlo** [comment]
In the current implementation, users can override the bootstrap and pass their own sequence. Not pretty, but if anyone needs to do it at this point, the example below should work.

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: demo-cluster
    region: us-west-2

nodeGroups:
    - name: bootstrap-override-spot-labels-and-taints
      availabilityZones: ["us-west-2a","us-west-2b","us-west-2c"]
      ami: ami-03a55127c613349a7
      amiFamily: AmazonLinux2
      minSize: 1
      maxSize: 20
      instanceType: mixed
      instancesDistribution:
        instanceTypes: ["t3.medium","t2.medium"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 50
        spotInstancePools: 2
      labels:
        environment: dev
        costcenter: engineering
        project: default
      iam:
        withAddonPolicies:
          autoScaler: true
          cloudWatch: true
          albIngress: true
          appMesh: true
          xRay: true
      overrideBootstrapCommand: |
        #!/bin/bash
        set -o errexit
        set -o pipefail
        set -o nounset
        function get_max_pods() {
          while read instance_type pods; do
            if  [[ "${instance_type}" == "${1}" ]] && [[ "${pods}" =~ ^[0-9]+$ ]] ; then
             echo ${pods}
             return
            fi
          done < /etc/eksctl/max_pods.map
        }
        EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
        AWS_DEFAULT_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed 's/[a-z]$//'`"
        NODE_IP="$(curl --silent http://169.254.169.254/latest/meta-data/local-ipv4)"
        INSTANCE_ID="$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)"
        INSTANCE_TYPE="$(curl --silent http://169.254.169.254/latest/meta-data/instance-type)"
        source /etc/eksctl/kubelet.env # this can override MAX_PODS
        INSTANCE_LIFECYCLE=$(aws ec2 describe-instances --instance-ids  ${INSTANCE_ID}  --query 'Reservations[0].Instances[0].InstanceLifecycle' --output text)
        if [ "$INSTANCE_LIFECYCLE" == "spot" ]; then
          NODE_LABELS="${NODE_LABELS},lifecycle=Ec2Spot"
        else
          NODE_LABELS="${NODE_LABELS},lifecycle=OnDemand"
        fi
        if [ "$INSTANCE_LIFECYCLE" == "spot" ]; then
          if [ "$NODE_TAINTS" == "" ]; then
            NODE_TAINTS="spotInstance=true:PreferNoSchedule"
          else
            NODE_TAINTS="${NODE_TAINTS},spotInstance=true:PreferNoSchedule"
          fi
        else
          NODE_TAINTS="${NODE_TAINTS}"
        fi
        cat > /etc/eksctl/kubelet.local.env <<EOF
        NODE_IP=${NODE_IP}
        INSTANCE_ID=${INSTANCE_ID}
        INSTANCE_TYPE=${INSTANCE_TYPE}
        MAX_PODS=${MAX_PODS:-$(get_max_pods "${INSTANCE_TYPE}")}
        NODE_LABELS=${NODE_LABELS}
        NODE_TAINTS=${NODE_TAINTS}
        EOF
        systemctl daemon-reload
        systemctl enable kubelet
        systemctl start kubelet 
```

**Comment by ruecarlo** [comment]
That's my understanding of what the configuration above does.

Here are the pointers to it: When the cfn stack gets built, [this section ](https://github.com/weaveworks/eksctl/blob/master/pkg/cfn/builder/nodegroup.go#L56) get's called to cover the nodegroup launch template, and then that calls the [NewUserData](https://github.com/weaveworks/eksctl/blob/master/pkg/nodebootstrap/userdata.go#L177) which delegates into the specific implementation ones [Amazon Linux 2](https://github.com/weaveworks/eksctl/blob/master/pkg/nodebootstrap/userdata_al2.go#L46) , [Ubuntu](https://github.com/weaveworks/eksctl/blob/master/pkg/nodebootstrap/userdata_ubuntu.go#L48) where the `preBootstrapCommands`  and the `overrideBootstrapCommand` are taken into consideration, concatenated and used as entry for the `UserData`

The criteria to leave that file instead, is just to get as close as possible to the [default one used by eksctl itself](https://github.com/weaveworks/eksctl/blob/master/pkg/nodebootstrap/assets/bootstrap.al2.sh).

Another potential implementation would be using the preBootstrapCommands and change the NODE_LABELS and NODE_TAINTS there. I have not tried this approach I must confess, but thought that would be better to have all the moving parts in the same script (easier to digest IMO). 

Unless I'm missing something here ! :)

**Comment by techdragon** [comment]
@ruecarlo Something about your posted script seems to interrupt things and causes the nodes to never join the cluster.

**Comment by ruecarlo** [comment]
Very likely that what I wrote last Aug breaks something in eksctl as of today; There was a refactoring exercise done about 2 months ago that may have changed the way it works; Will try and see, as soon as I get some spare time, to reproduce and post the changes here.

**Comment by techdragon** [comment]
@ruecarlo Thanks for the quick follow up. On my end I'm currently looking at writing a lightweight script to run as a DaemonSet, similar to how https://github.com/kube-aws/kube-spot-termination-notice-handler checks for the termination notice, but instead of issuing a request to drain the node its running on, it will try and update the labels/taints, maybe based on a basic runtime argument passed to it if it works well... However the ideal solution would be to have the modifications taken care of _before_ the node comes online to avoid running a needless pod, and using the node startup security context which will avoid the need to manage security permissions for the DaemonSet container executing the request. So I'll definitely still be  looking forward to your update when you find that spare time 😁

**Comment by Hakob** [comment]
> Unfortunately `InstanceLifecycle` is not available from the metadata. As far as I know a call to the [describe-instances API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html) will be required for the qualification of the node being Spot or not.
> 
> In the current implementation, users can override the bootstrap and pass their own sequence. Not pretty, but if anyone needs to do it at this point, the example below should work.
> 
> ```
> apiVersion: eksctl.io/v1alpha5
> kind: ClusterConfig
> 
> metadata:
>     name: demo-cluster
>     region: us-west-2
> 
> nodeGroups:
>     - name: bootstrap-override-spot-labels-and-taints
>       availabilityZones: ["us-west-2a","us-west-2b","us-west-2c"]
>       ami: ami-03a55127c613349a7
>       amiFamily: AmazonLinux2
>       minSize: 1
>       maxSize: 20
>       instanceType: mixed
>       instancesDistribution:
>         instanceTypes: ["t3.medium","t2.medium"] 
>         onDemandBaseCapacity: 0
>         onDemandPercentageAboveBaseCapacity: 50
>         spotInstancePools: 2
>       labels:
>         environment: dev
>         costcenter: engineering
>         project: default
>       iam:
>         withAddonPolicies:
>           autoScaler: true
>           cloudWatch: true
>           albIngress: true
>           appMesh: true
>           xRay: true
>       overrideBootstrapCommand: |
>         #!/bin/bash
>         set -o errexit
>         set -o pipefail
>         set -o nounset
>         function get_max_pods() {
>           while read instance_type pods; do
>             if  [[ "${instance_type}" == "${1}" ]] && [[ "${pods}" =~ ^[0-9]+$ ]] ; then
>              echo ${pods}
>              return
>             fi
>           done < /etc/eksctl/max_pods.map
>         }
>         EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
>         AWS_DEFAULT_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed 's/[a-z]$//'`"
>         NODE_IP="$(curl --silent http://169.254.169.254/latest/meta-data/local-ipv4)"
>         INSTANCE_ID="$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)"
>         INSTANCE_TYPE="$(curl --silent http://169.254.169.254/latest/meta-data/instance-type)"
>         source /etc/eksctl/kubelet.env # this can override MAX_PODS
>         INSTANCE_LIFECYCLE=$(aws ec2 describe-instances --instance-ids  ${INSTANCE_ID}  --query 'Reservations[0].Instances[0].InstanceLifecycle' --output text)
>         if [ "$INSTANCE_LIFECYCLE" == "spot" ]; then
>           NODE_LABELS="${NODE_LABELS},lifecycle=Ec2Spot"
>         else
>           NODE_LABELS="${NODE_LABELS},lifecycle=OnDemand"
>         fi
>         if [ "$INSTANCE_LIFECYCLE" == "spot" ]; then
>           if [ "$NODE_TAINTS" == "" ]; then
>             NODE_TAINTS="spotInstance=true:PreferNoSchedule"
>           else
>             NODE_TAINTS="${NODE_TAINTS},spotInstance=true:PreferNoSchedule"
>           fi
>         else
>           NODE_TAINTS="${NODE_TAINTS}"
>         fi
>         cat > /etc/eksctl/kubelet.local.env <<EOF
>         NODE_IP=${NODE_IP}
>         INSTANCE_ID=${INSTANCE_ID}
>         INSTANCE_TYPE=${INSTANCE_TYPE}
>         MAX_PODS=${MAX_PODS:-$(get_max_pods "${INSTANCE_TYPE}")}
>         NODE_LABELS=${NODE_LABELS}
>         NODE_TAINTS=${NODE_TAINTS}
>         EOF
>         systemctl daemon-reload
>         systemctl enable kubelet
>         systemctl start kubelet 
> ```

The overridden config is not helped me to launch nodes with appropriate labels on them. After provisioning nodes are remaining unschedulable

**Comment by martina-if** [comment]
closed by https://github.com/weaveworks/eksctl/pull/2615
