### ISSUE TITLE
Retaining environment variables when using update-aws-node

### ISSUE THREAD

**Issue by andrew-ha** [weaveworks/eksctl#933]
**What happened?**
When using eksctl utils update-aws-node to update their cluster, environment variables on the aws-node daemonset (e.g. WARM_IP_TARGET) gets removed.

**What you expected to happen?**
Expected the environment variables to be retained

**How to reproduce it?**
1. Set WARM_IP_TARGET on the aws-node daemonset
2. Wait for restart of the daemonset
3. Run eksctl update-aws-node
4. Check yaml of the daemonset.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.38"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

**Comment by martina-if** [comment]
Hi @andrew-ha, thank you for reporting this. When eksctl updates the `aws-node` it applies the [latest manifests](https://github.com/aws/amazon-vpc-cni-k8s/blob/61c8d18c0e097c0b7e8477e1afc61d6f2601295d/config/v1.6/aws-k8s-cni.yaml). 

I don't see a good way to respect the previous environment variables or any other manual modification to the existing manifests. I guess the only workaround is to update this add-on manually. I will close this but please feel free to reopen it if you have any ideas on how to fix this.

**Comment by dschunack** [comment]
Hi, we have the same Problem and for us is this a lot of additional work. One solution is to use a configmap maybe for the ENV parameter or you can us the patch command. We write our own patch for the aws-node ds.

**Comment by andrew-ha** [comment]
Reopened: https://github.com/weaveworks/eksctl/issues/1993
