### ISSUE TITLE
eksctl 0.1.36 launches GPU instances with unready GPU

### ISSUE THREAD

**Issue by Jeffwan** [weaveworks/eksctl#934]
**What happened?**
The AMI ID eksctl using doesn't match EKS Optimized AMI ID.

**What you expected to happen?**
`nvidia-smi` should work and device plugin should work. 

**How to reproduce it?**
Include the steps to reproduce the bug

`eksctl create cluster` with GPU instances and ssh to GPU AMI run `nvidia-smi`

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version 0.1.36
$ kubectl version 1.12
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by Jeffwan** [comment]
@arun-gupta

**Comment by errordeveloper** [comment]
We should automate this, maybe we could do it easily with GitHub actions now, I believe there is an easy way to raise to make a bot raise a PR. Perhaps to begin with we should try to automate creating issues.

**Comment by errordeveloper** [comment]
@Jeffwan it would be good to know if we should say something specific in release notes about the new AMIs, any ideas?

I'm looking at https://github.com/awslabs/amazon-eks-ami/commit/e8b50ba230e82b6a5c6fdab37660a8868cb126a3, but appears that there were some AMIs that came as part of recent CVEs, and then other features got added and that resulted in new AMIs? If so, what exactly applies to these latest AMIs?

**Comment by errordeveloper** [comment]
Also, you should be able to use `--node-ami=auto` (or `ami: auto`) to pick latest AMI.

**Comment by errordeveloper** [comment]
Closed via #940. This should be available in the next release, which I'd hope will happen next week.

**Comment by Jeffwan** [comment]
@errordeveloper Sorry for late response. I was on vacation and just come back. This looks good to me. 
BTW, I am trying to understand when static resolver will be used? Is it by default being used? 
`--node-ami=auto` will use auto resolver to get latest AMI Ids?
