### ISSUE TITLE
Allow passing `--enable-docker-bridge` to `amazon-eks-ami` bootstrap

### ISSUE THREAD

**Issue by danielchalef** [weaveworks/eksctl#942]
**Why do you want this feature?**
A number of common Kubernetes use cases, including CI and machine learning experiment management, require building docker images on Kubernetes (more generally known as "docker-on-docker"). Amazon recently disabled the docker bridge on the `amazon-eks-ami` family of images, breaking this capability (see [Docker in Docker no longer works without docker0 bridge](https://github.com/awslabs/amazon-eks-ami/issues/183)). Even more recently, Amazon added a `--enable-docker-bridge` switch to the AMI bootstrap script to reenable the bridge.

**What feature/behavior/change do you want?**
Allow configuring an eksctl nodegroup for "docker-on-docker" use. If a nodegroup is configured in this way, eksctl will pass the  `--enable-docker-bridge` to the AMI bootstrap.

**Comment by errordeveloper** [comment]
I believe this will be doable by allowing to customise `/etc/docker/daemon.json`, in the spirit similar to how we handle `kubelet.yaml`.

So you would be looking to do something like:
```
nodeGroups:
  - name: ng1-with-docker-in-docker
     extraDockerConfig:
       bridge: docker0
       live-restore: false
```

**Comment by tobemedia** [comment]
Run in the same problem using eksctl to setup a binder / jupyterhub setup. The built in docke-on-docker build process fails due to dns errors. Is there a workaround to pass --enable-docker-bridge to eksctl commands?

**Comment by SkySonR** [comment]
Looks like it's possible. See https://github.com/weaveworks/eksctl/pull/522

**Comment by mhumeSF** [comment]
@SkySonR #522 looks specific to ubuntu amis? Not eks amazon linux default ami's. Is there documentation on how this flag can get passed to bootstrap on eks-amazon-linux?

**Comment by diestrin** [comment]
I'm having the same DNS problem. @SkySonR do you know how can we pass the argument for that PR you mention?

**Comment by Arau** [comment]
Same here. Is there a way to achieve this in the meantime that this is developed properly? 
Can I edit the host template by hand or anything alike?

Thank you for the work and great project!

**Comment by tobemedia** [comment]
Using a workaround described at the [Jupyter Forum](https://discourse.jupyter.org/t/binder-deployed-in-aws-eks-domain-name-resolution-errors/766/10) a was able to fix the dns errors.
Create a new eks cluster using this config as a starting point

`eksctl create cluster --config-file aws_eks_config.yml`

`
# file: aws_eks_config.yml
# AWS EKS ClusterConfig used to setup the BinderHub / JupyterNotebooks K8s cluster
# using a workaround from https://discourse.jupyter.org/t/binder-deployed-in-aws-eks-domain-name-resolution-errors/766/10
# to fix broken DNS resolution
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-dns-production
  region: eu-central-1

nodeGroups:
  - name: eks-dns-workers-production
    instanceType: t2.small
    minSize: 0
    maxSize: 4
    desiredCapacity: 2
    preBootstrapCommands:
        # Replicate what --enable-docker-bridge does in /etc/eks/bootstrap.sh
        # Enabling the docker bridge network. We have to disable live-restore as it
        # prevents docker from recreating the default bridge network on restart
       - "cp /etc/docker/daemon.json /etc/docker/daemon_backup.json"
       - "echo -e '.bridge=\"docker0\" | .\"live-restore\"=false' >  /etc/docker/jq_script"
       - "jq -f /etc/docker/jq_script /etc/docker/daemon_backup.json | tee /etc/docker/daemon.json"
       - "systemctl restart docker"`

**Comment by antodoms** [comment]
@tobemedia Your solution worked! I was trying to build docker container using buildkite agent inside our Kubernetes cluster and it was throwing this error!

**Comment by kalbir** [comment]
I'm closing this given the workaround from @tobemedia above. We are unlikely to implement any other features for this in eksctl.

**Comment by duanyutong** [comment]
Why not implement something clean like `--enable-docker-bridge`? The above workaround in the yaml config is prevent my p3 nodes from joining the cluster when I call `eksctl create nodegroup --config-file=nodegroups.yaml`.
