### ISSUE TITLE
eksctl utils write-kubeconfig --all-clusters --all-regions

### ISSUE THREAD

**Issue by ORESoftware** [weaveworks/eksctl#946]
I shouldn't have suffered:
https://stackoverflow.com/a/56782763/1223975

if you want to put it behind a flag, then use:

```
$ aws eks update-kubeconfig --all
```

--all meaning all clusters

**Comment by errordeveloper** [comment]
There are a few options you can set when you run `eksctl create cluster`, and after that you can use `eksctl utils write-kubeconfig`. You shouldn't have to use `aws eks update-kubeconfig`.

**Comment by errordeveloper** [comment]
Please have a look at what `eksctl utils write-kubeconfig` offers, and let us know if it's somehow insufficient for you.

Example:
```
eksctl create cluster --write-kubeconfig=false --name=cluster-1
eksctl utils write-kubeconfig --name=cluster-1 --kubeconfig=./kubeconfigs/cluster-1.yaml
```

**Comment by ORESoftware** [comment]
Not every machine has called `create cluster`, the point of the question is any authenticated machine can retrieve the available cluster information from AWS (or wherever) and put it into ~/.kube/config

**Comment by errordeveloper** [comment]
Sure, so I said there is 'eksctl utile write-kubeconfig'. My question is - do you want to a flag for fetching kubeconfigs for all of your clusters in one go? Your suggestion above is about AWS CLI, which read as if you might be posting this in a wrong place, I just want to be clear on what is it you are asking for.

**Comment by ORESoftware** [comment]
> do you want to a flag for fetching kubeconfigs for all of your clusters in one go? 

yeah, that's what I want :) thanks

**Comment by cPu1** [comment]
This does not seem like a feature that should belong in eksctl. There's already a command that lists clusters in all regions (`eksctl get cluster --all-regions`). Using its output, it should be straightforward to make a script that adds the context for each cluster. For example, with bash:

```bash
while read -r line; do
  values=($line);
  eksctl utils write-kubeconfig --cluster ${values[0]} --region ${values[1]}
done <<< $(eksctl get clusters --all-regions | tail -n +2)
```

**Comment by cPu1** [comment]
Closing the issue for now, but if we get more requests for this feature, we may consider adding it to eksctl.

**Comment by nethershaw** [comment]
I would +1 the issue itself, but I don't think that will reach anyone as a visible metric. I don't want to bother you with a whole new issue, so if you are gauging interest in this feature by counting requests, please count this as one.

Simply wanted to note I landed here searching for a way to do just what was described, and I'll happily use bash to do it, but also good mnemonics are good. I don't think I would naively have come up with that particular script.
