### ISSUE TITLE
Drift Detection and onboarding an existing EKS cluster

### ISSUE THREAD

**Issue by gjmveloso** [weaveworks/eksctl#948]
**Why do you want this feature?**
Having the ability to detect changes (via [CloudFormation Drift Detection](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/detect-drift-stack.html), for example) on a given cluster outside of `eksctl` responsibility and having the ability to onboard an existing EKS cluster like `eksctl pull cluster <cluster-name>` would unblock massive adoption of `eksctl` without the need of extra work.

**What feature/behavior/change do you want?**
`eksctl get cluster --detect-drift` triggering [CloudFormation Drift Detection](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/detect-drift-stack.html) plus evaluating last known cluster state from eksctl vs. what's is really in place

`eksctl pull cluster <cluster-name>` onboarding an existing EKS cluster to be managed by eksctl

**Comment by errordeveloper** [comment]
@gjmveloso aren't these two separate feature requests?

**Comment by gjmveloso** [comment]
Might be. The reason that I filled just one feature request is just because I assumed some "drift detection" at cluster settings (`~/.kube` and/or something else `eksctl` uses to keep track of configuration changes locally) might be related to the effort on onboarding a EKS cluster managed outside `eksctl`.

If that assumption is not accurate, I agree this could be split into two different feature requests.

**Comment by michaelbeaumont** [comment]
Possible solution for #2773
