### ISSUE TITLE
Can't verify whether AMI code is up to date in CI

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/eksctl#949]
**What happened?**

In CircleCI

```
$ make generate-ami
go generate ./pkg/ami
generating list of AMIs for the static resolvers
2019/06/27 21:46:18 looking up Ubuntu1804/1.10 images
2019/06/27 21:46:18 looking up images matching "ubuntu-eks/k8s_1.10/images/*" in "us-west-2"
2019/06/27 21:46:21 error querying AWS for images: RequestExpired: Request has expired.
	status code: 400, request id: 36040efe-3ad7-45e4-a949-05c1f4cd696d
exit status 1
pkg/ami/static_resolver.go:8: running "go": exit status 1
make: *** [generate-ami] Error 1
```

**What you expected to happen?**

There should be no error, resulting in `static_resolver_ami.go` being regenerated properly

**How to reproduce it?**

```
make generate-ami
```

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**

Current master

**Comment by errordeveloper** [comment]
The error is a bit confusing, it should say "token expired", not "request expired" :)

I just ran it and got the same, refreshing MFA auth token fixed it.

```
 [0] >> make generate-ami
go generate ./pkg/ami
go: finding github.com/alecthomas/jsonschema v0.0.0-20190530235721-fd8d96416671
generating list of AMIs for the static resolvers
2019/06/28 08:54:46 looking up AmazonLinux2/1.10 images
2019/06/28 08:54:46 looking up images matching "amazon-eks-node-1.10-v*" in "us-west-2"
2019/06/28 08:54:50 error querying AWS for images: RequestExpired: Request has expired.
	status code: 400, request id: 241559d0-72ab-42aa-9b24-efe353a45cb4
exit status 1
pkg/ami/static_resolver.go:8: running "go": exit status 1
make: *** [generate-ami] Error 1
 [2] >> aws-mfa 
INFO - Validating credentials for profile: weaveworks 
INFO - Your credentials have expired, renewing.
Enter AWS MFA code for device [arn:aws:iam::***:mfa/ilya] (renewing for 43200 seconds):******
INFO - Fetching Credentials - Profile: weaveworks, Duration: 43200
INFO - Success! Your credentials will expire in 43200 seconds at: 2019-06-28 19:59:27+00:00
 [0] >> make generate-ami
go generate ./pkg/ami
generating list of AMIs for the static resolvers
2019/06/28 08:59:31 looking up AmazonLinux2/1.10 images
2019/06/28 08:59:31 looking up images matching "amazon-eks-node-1.10-v*" in "us-west-2"
2019/06/28 08:59:32 looking up images matching "amazon-eks-node-1.10-v*" in "us-east-1"
2019/06/28 08:59:32 looking up images matching "amazon-eks-node-1.10-v*" in "us-east-2"
2019/06/28 08:59:33 looking up images matching "amazon-eks-node-1.10-v*" in "ca-central"
...
```

**Comment by 2opremio** [comment]
Problem is we get this error un CI, not allowing to verify that the code is up to date

**Comment by errordeveloper** [comment]
Yes, but that is a separate problem. CI has no access to AWS at the moment,
we need to discuss it separately. And we should find a way to detect whe
AMI updates are needed, but I see those as two separate issue that don't
match description of this issue.

**Comment by errordeveloper** [comment]
Thanks for updating the title, makes more sense. Let me see if there was another issue that says something along these lines, I am sure we had one.

**Comment by errordeveloper** [comment]
https://github.com/weaveworks/eksctl/issues/314

**Comment by martina-if** [comment]
This is a bit old and after giving it some thought I think we should consciously update the AMIs rather than blocking random PRs when a new AMI is published.
