### ISSUE TITLE
Docs mention --name when real flag is --cluster-name

### ISSUE THREAD

**Issue by Lawouach** [weaveworks/eksctl#97]
Hello,

It seems the readme/doc is not synced up with the code as the former mentions --name as a flag when the command exposes --cluster-name.

Am I reading it wrong? :)

**Comment by errordeveloper** [comment]
`--cluster-name` was used in older versions, it's been remove in #81.

**Comment by Lawouach** [comment]
Gotcha! I haven't updated yet :)

I'll close this one for now then.
