### ISSUE TITLE
Provide instant feedback for invalid arguments

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#970]
**Why do you want this feature?**
Some commands like `eksctl utils describe-stacks`,  `eksctl utils write-kubeconfig` and `eksctl delete iamidentitymapping` (non-exhaustive list) authenticate with AWS first (using `sts.GetCallerIdentity`) before validating arguments for correctness. Since the auth check is an HTTP call, it takes some time to complete and any invalid arguments are reported only after that check is complete.

**What feature/behavior/change do you want?**
To provide instant feedback, eksctl commands should report any invalid arguments that can be validated locally before making any auth calls.

**Comment by errordeveloper** [comment]
Most command actually do this. Which arguments/flags are you thinking of specifically?

Also, do keep in mind that bulk of parameters will lie in config files and we'd hope to reduce the number of flags over time. I believe that in most of the case we do validation and defaulting of config files before we do the auth check.

https://github.com/weaveworks/eksctl/blob/0b50182498491ff0ed3643fac222ec288af5d322/pkg/ctl/create/cluster.go#L89-L102

It would be best to focus on getting config file loading in a better shape. It would be great if we can get to a place where error messages around config file fields or flag usage don't need to be coded as very specific error message that refer to either field path or flag name.
We have something that works now, but there is still a bunch of stuff that can be cleaned-up and refactored. I think we should look at this with long-term goal of creating a library (see #813). We also have #488 that needs some attention long term. Any short term improvements would need to relate to those long term goals.

**Comment by aclevername** [comment]
Closing due to staleness
