### ISSUE TITLE
document Kubernetes version choices

### ISSUE THREAD

**Issue by kalbir** [weaveworks/eksctl#979]
We update the default Kubernetes version in line with AWS doing it (on release of a new version of EKS). Users might get caught out with this if they build a new cluster without realising that the version has updated.

To make this easier we will:

- [x] ~~Print the Kuberenetes version as part of the CLI output for `eksctl create cluster`~~ Implemented by this [PR](https://github.com/weaveworks/eksctl/pull/978#pullrequestreview-258053566)
- [x] Make it explicit in the documents that you get the latest Kubernetes version supported by AWS as default
- [x] Make it clear in the documentation how to specify a Kubernetes version

**Comment by tkang007** [comment]
Hello,
I found --version option to specify kuberenetes version.
This option cannot be used with -f config.yaml option.  

How to specify the version at the config.yaml file ?

Thanks in advance.
