### ISSUE TITLE
searching dependency tree

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#986]
With `dep`, I was able to simply `git grep` for anything in `vendor/`. It's no longer possible to do as easily. We need to a fast and easy way for searching `$GOPATH/pkg/mod/`.

Additionally, it's not clear if things that one will find in `$GOPATH/pkg/mod/` are not stale. In fact, they can easily be stale or unrelate, as it's a shared tree. I personally set `$GOPATH` per project, but even then I'm not very clear on how tightly it's managed in reality.

**Comment by martina-if** [comment]
I believe this is possible with the IDE.
