### ISSUE TITLE
Question about packer ssh key

### ISSUE THREAD

**Issue by cbluth** [weaveworks/eksctl#99]
First note, eksctl is great so far, wonderful tool.

To start, I provisioned my cluster like this: 
`eksctl create cluster --name=foo --kubeconfig=./foo-cluster.yaml --ssh-public-key=~/.ssh/foo-key.pub`

I then do `ssh -i ~/.ssh/foo-key.pub ec2-user@ip.of.my.ec2` to access one of the nodes of my cluster, works great. 

But in these two files:
```
[root@ip-of-my-ec2 ~]# file /home/ec2-user/.ssh/authorized_keys /root/.ssh/authorized_keys 
/home/ec2-user/.ssh/authorized_keys: OpenSSH RSA public key
/root/.ssh/authorized_keys:          ASCII text, with very long lines
[root@ip-of-my-ec2 ~]# 
```

Contains this key:
```
[root@ip-of-my-ec2 ~]# grep packer /home/ec2-user/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCI4LH7ahSzFltCqqcryx6Bf9+GpXNblDcT1or5tvE10GaUiQQU2MqlD/TzAjSD+mrhQ2Teb7DS9Hy2Gq4kGBI1iKOCt1B6+DiZvEw2q4TgxF8ZtbA43ltmHkuHBMcnkbbXN753j4HsWA8Zf6+7H8HfJ2tGS4CwuDf7n/OnWCTnAalTL7rUdD684lxiCeehth0C8kvLvgwbfnmMLFSCvIgEvzi6CRD4FpmsFvZV0Unpzpw/S6rSwigZsKHmsg4WaYeB7kQzfEmg9pN9ngFpa359+AtIqskazAzga8WQXNUHos8OUCqCHEp0tricpD4kEQIpJvNLMi5D2L+9BwgLIPqV packer_5b14d570-55f8-be00-00e9-ab4d5a91be9c
[root@ip-of-my-ec2 ~]# 
```

Its quite obvious that this is *just* a packer key.
But, my question is, did aws inject that packer key, or is this some leftover key that needs to be cleaned up?
Shouldnt the ec2 provisioning process clear those "pre-existing" keys?

**Comment by errordeveloper** [comment]
@cbluth ah! thanks for reporting this. It looks like a bug that would need be fixed elsewhere, but @christopherhein would know best where to report it!

**Comment by errordeveloper** [comment]
https://github.com/awslabs/ami-builder-packer/issues/7
